### ISSUE TITLE
Errorcode 80110306 when trying to load a savegame in this game...

### ISSUE THREAD

**Issue by ElektroStudios** [hrydgard/ppsspp#10000]
Hi.

## Environment Specifications:
PPSSPP version: 1.4.2.0 ( [this](https://ppsspp.org/files/1_4_2/ppsspp_win.zip) )
S.O: Windows 10 x64

## Affected game:
Title: **Gunhound EX**
Disc ID: **NPJH-50723**
ISO Download -cut-
(THE DOWNLOAD IS JUST FOR EDUCATIVE PURPOSES IF NEEDED BY THE DEVELOPERS OR HELPER USERS TO TEST OUT THE PROBLEM, if this violates the rules I'm sorry and then please delete the url)

## Affected savegame:
Savegame download: [here](https://www.gamefaqs.com/psp/681782-kisou-ryouhei-gunhound-ex/saves)
Savegame folder name: **NPJH5072300GHSAVE00**

## Problem Description:
The emulator displays this message when initializing the game due it can't load the savegame for some reason:

![errorcode](https://i.imgur.com/5CMcK9P.png)

After that, the game works as normally... but it can't load savegames.

## Steps to reproduce the problem:
1. Download the specified savegame linked above.
2. Run your copy of **Gunhound EX** in PPSSPP.
2. Wait for the errorcode to appear.

## Research:
I'm 100% sure this is not a problem of user rights neither a corrupted save data, it is an issue with the emulation. Also be aware that I have a private collection of many, many many games that runs perfectly in PPSSPP and the savegames too. Please avoid typical things like "_you have admin privileges?_" and that..

I had another similar problem with another japanese game ( **Strike Witches - Hakugin no Tsubasa** ) which It was unable to load a savegame and it gaves me an error code 80110306 or maybe 80110307, I'm not totally sure, but the thing is that I solved it by following this strange guide:

![solution](https://i.imgur.com/aSY0f0k.png)
Source: http://forums.afterdawn.com/threads/help-saved-game-give-error-code-80110306-and-also-80110307.580858/

Yes, I don't know how and why, but doing those weird things (which are not much good explained at all) I solved the errorcode in that other game and my savegame start loading correctly. Unfortunately that thing didn't worked for **Gunhound EX**.

Also I noticed that the **Gunhound EX** is not listed in the official PPSSPP compatibility list: 
http://forums.ppsspp.org/showthread.php?tid=1473
( However **Strike Witches - Hakugin no Tsubasa** is not listed there too, but it is perfectly playable game. )

It was unable for me to find any info about this strange error. I read that maybe it could be due to some games requires a higher firmware and then... it breaks when trying to load a savegame or something like that?. Or maybe just what happens is the game is not compatible with PPSSPP? maybe it never get tested by the developers...due it does not appear in the compatibility list?.

## Other:
I'm glad to contribute to PPSSPP's project being my issue the magic number #10000. Is there any reward for this, like... you know, a month of free Domino's Pizza or some coupon to buy a PS4?. ;)

Thanks for read!

**Comment by LunaMoo** [comment]
Sharing copyrighted content without being the copyright holder is illegal doesn't matter what reasons you have behind it, so for your own good I removed the link.

 As for the problem, technically it's not an emulator issue, PSP would get the same "error" as you can see by searching the net for that error code, it's caused by savedata(from outdated firmware) being encrypted with a different method. People typically use plugins on PSP to fix it.

 Since the problem shows on PSP it should also happen on emulator, however I guess it could be acceptable maybe at least as an ini-only and non-default setting to allow upgrading savedata from outdated firmware as it really shouldn't be much of a problem for emulator to do such savedata "upgrade", much easier than the plugins for sure.

 As for the compatibility list it's updated manually by maybe like one moderator who might not be around often and probably is missing a lot of things sometimes because nobody created a thread for the game and sometimes probably just overlooked as this game does have it's thread in [here](http://forums.ppsspp.org/showthread.php?tid=1743).

**Comment by LunaMoo** [comment]
@ElektroStudios just in case you're unsure what to do to make this savedata work now:
- use latest PPSSPPP from [buildbot](https://buildbot.orphis.net/ppsspp/) and run it at least once for a second and close for new option to be added into ini file,
- edit your ppsspp.ini(by default it should be in memstick\PSP\SYSTEM),
- find "SavedataUpgrade = False" and change it to "SavedataUpgrade = True" then save changes.

 And that's pretty much it, next time you run that game whenever it reads that "corrupted" savedata you'll instead of error get a message on the screen from PPSSPP that old savedata was detected giving you a hint that it will stop working on older firmwares. Now just save in-game to upgrade your savedata and you will stop seeing the message.

**Comment by Hydroque** [comment]
@ElektroStudios Please update us if you get this problem fixed with the latest patch

**Comment by ElektroStudios** [comment]
@Hydroque 
Yes of course, I always answer, I just was sleeping :). I confirm the savegame loads perfect with the latest PPSSPP build/patch.

@LunaMoo 
Many thanks for the help and for the brief guide to solve it, without those steps probably I would still be "lost"...

Thanks to both!. Regards.
