### ISSUE TITLE
V8 Supercars Australia 3 - Graphical glitches

### ISSUE THREAD

**Issue by Levan7** [hrydgard/ppsspp#10036]
V8 Supercars Australia 3 - Shootout
I am using the v1.4.2-567-g872b0307e build for windows and i notice graphical glitches even on software mode. 

![ed](https://user-images.githubusercontent.com/5770076/32135771-a43c3e4e-bc15-11e7-8557-c0985277b95f.gif)

Software rendering

![restricted](https://user-images.githubusercontent.com/5770076/32135774-b05a7fce-bc15-11e7-98d9-c5099ae1c34f.gif)

[debug.zip](https://github.com/hrydgard/ppsspp/files/1424351/debug.zip)

**Comment by LunaMoo** [comment]
This issue is already tracked in #5001, that game was unfortunately released under different names for each region, so it was probably hard to find;p. Anyway I'll close this as duplicate.

 Note this problem was already fixed with #9527, it just doesn't work with all games suffering from that problem yet and as such wasn't merged.:]
