### ISSUE TITLE
PPSSPP crash when saving state

### ISSUE THREAD

**Issue by NaturalHarmonia** [hrydgard/ppsspp#10044]
When I made a new save state the screen flashed for a second and then PPSSPP exited out. Then when I opened it again to load the save state I keep getting the save state from before.

**Comment by hrydgard** [comment]
PPSSPP shouldn't exit when saving states. Was this on Android or PC? Which game were you playing?

**Comment by NaturalHarmonia** [comment]
Android. The game was Yu-Gi-Oh! 5D's Tag Force 6. PPSSPP and the game take up a lot of space on my phone so do you think the lack of space on my phone could have anything to do with it? It happened when I played Tag Force Special and the other 5D's Tag Force games in the past as well.

**Comment by unknownbrackets** [comment]
What device are you using?

It's possible PPSSPP crashed while trying to save state - I believe this can currently be caused by running out of RAM.

If it crashed when saving the save state, the bad news is that the old state is all you have.  The good news is that at least the old state wasn't lost (this used to happen too.)

-[Unknown]

**Comment by unknownbrackets** [comment]
Are you still able to reproduce the crash when saving state?

-[Unknown]

**Comment by hrydgard** [comment]
@NaturalHarmonia We've made a few fixes, please test the latest builds again. https://buildbot.orphis.net/ppsspp/

**Comment by Carter07** [comment]
Seems to work now!
