### ISSUE TITLE
Brave Story birds in Birdbrawl are missing HP bars and shadows.

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#10045]
OGL/d3d11/Vulkan all have same issue:
![hardware](https://user-images.githubusercontent.com/5485237/32406173-cf4208f4-c173-11e7-9e3f-b7d536d46202.png)

 Those bars shows fine in software mode:
![software](https://user-images.githubusercontent.com/5485237/32406183-f14d7078-c173-11e7-9dd4-8db439667ba8.png)

I made a dump from it:
[ULUS10279_0001.zip](https://github.com/hrydgard/ppsspp/files/1443248/ULUS10279_0001.zip)
but weirdly HP bars and shadows show fine while running the dump itself even in hardware mode.

 I noticed this in a hunt to find games with other missing graphics using TRIANGLE_STRIP type prims, but they seem to be working fine here, one thing which differ between working(software and dump in any mode) and not working seems to be the texture which differs in preview even through size and address seems to be correct.

**Comment by unknownbrackets** [comment]
The texture is at 0x04000780, which is 480 pixels into the framebuffer.  Basically, the game is using the space between the width and the stride for the texture.  That's why the preview shows the bound framebuffer as the texture.

Since the texture ix 32x32, it's probably possible to detect that it's doing this and use RAM.  The problem is, I've also seen games render into this area, and then texture from it.

If we could detect the upload and transfer it to the framebuffer, that would cover both...

-[Unknown]
