### ISSUE TITLE
Save states apply to video/audio dump

### ISSUE THREAD

**Issue by InfamousKnight** [hrydgard/ppsspp#10099]
I am aware that there's a feature for frame advance, and video/audio dumping, but the problem that I have is save states apply to the encode.

So my solution would be:
1: begin dumping video/audio - check
2: creates file called dump0 and adump0 - check
3: when making a save state, end dump0 and adump0, and create dump1, and adump1 -unchecked
4: when loading a save state, end dump1 and adump1 and delete them, and make a another dump1 and adump1
5: and so on so forth.

So there would be an integer for what current dump you're on, such as currentdump, and when making a save state, it would increment that value.

There would still be multiple files, but you would just simply combine all of them instead of editing out all the mistakes in a video editor.

**Comment by LunaMoo** [comment]
This feature is really barebones so far due to lack of interest and more important priorities.

 Would probably be more useful to use game ID and maybe a timestamp in the name instead of generic name to begin with. I guess savestates keep emulated time so using that time instead of real system time loading savestate would generate same name as the one which it was saved with without really doing much else other than stopping/starting it at state save/load.

**Comment by unknownbrackets** [comment]
I could see someone else complaining that when they load a save state it starts a new file (not for TAS, but if they just wanted to record their gameplay, maybe for a game review or something, or to show settings they like, or even display a bug.)

What it sounds like you're really asking for is video checkpoints, which you want tied to save states: creating a save state would create a new checkpoint, and loading a save state would go back to the checkpoint that save state created.

Probably makes the most sense to use emulated time timestamps, yeah.

-[Unknown]

**Comment by InfamousKnight** [comment]
What are emulated time timestamps?

As for the other perspective with recording gameplay, or game review or something, you could just have an option to toggle "apply save states to encodes".
