### ISSUE TITLE
Vulkan: GTA:LCS Crash after title logos. [Andriod]

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#10129]
My device: Huawei P9+
Spec: CPU: Kirin955, GPU: Mali-T880, GLES 3.2, Vulkan driver v.1.0.11.
PPSSPP settings: default.

On Windows is not found this problem.

![videotogif_2017 11 14_17 49 56](https://user-images.githubusercontent.com/26355472/32776474-4397293e-c965-11e7-8e70-5581dd17d4ff.gif)

Here is ADB logcat.
https://gist.github.com/Saramagrean/0c9ed800ace4e7a59c7d9bd8220a694b

**Comment by hrydgard** [comment]
Is that the entire backtrace at the end? I would have hoped to see a little more...

This game does work with Vulkan on Nexus 5X and Galaxy S8.

**Comment by hrydgard** [comment]
Wait, the fault address is 0x2318249700, starts with 0x23 which we use as our fake PSP RAM mapping. So that's an access to address 0x18249700 which is not a legal address in the PSP system. Seems like the actual game crashed, not the graphics code.

Does it work for you with OpenGL? You don't have any cheat codes enabled, right?

**Comment by Saramagrean** [comment]
Opps!!
Sorry, it's my fault. 😂

Thanks for help.

**Comment by hrydgard** [comment]
How was it your fault? :)

**Comment by Saramagrean** [comment]
Enable multiple cheat codes, haha. 😝
