### ISSUE TITLE
Galaxy S8 (Exynos) - Becoming more stable by the day (although still has OpenGL problems & crashes)

### ISSUE THREAD

**Issue by StephenH58** [hrydgard/ppsspp#10133]
Good Day Team

I would just like say that you guys have outdone yourselves with this emulator. This is more of an appreciation message to the PPSSPP team. Ever since the last few builds, this emulator has been running much better than before now with the Vulkan backend improvement. OpenGL is still currently unplayable due to graphics and text cut in half (but I know this is due to Mali's poor drivers). Vulkan runs much better and I have not yet encountered any graphical bugs/glitches with it yet (aside from the odd crash every now and then after playing for a few minutes). I know that this emulator will continue to improve over time, but it has seen a massive improvement over the years and I know it will just get better. Looks like it's finally getting stable enough to play on Vulkan. I don't have plenty of PSP games yet to test, so I can't say what happens with other games, but with what I currently have it works well.

Keep up the good work!

**Comment by hrydgard** [comment]
Thanks!

Whenever available, yeah, use Vulkan. OpenGL is just not a good API for emulation. Working on stabilizing Vulkan so we can get 1.5 out.

This doesn't seem to be an actual issue with specifics though, so I'll have to close it and refer further compliments to the forum: https://forums.ppsspp.org . Note that your first message will be delayed due to anti-spam moderation.
