### ISSUE TITLE
Can't input anything on Android when using virtual keyboard at Remote disc streaming settings.

### ISSUE THREAD

**Issue by peaceshi** [hrydgard/ppsspp#10142]
Yesterday I want to debug the "**Remote disc streaming**" tools, I found that **I can't input anything to set my remote port and server address**. And it doesn't work when I try to use **Android Return key** to return  to the Tools Menu from "Remote disc streaming" Menu. It may be a bug. Or must be : )

Test on:
**System** : Android 7.1.1
**Device** : XiaoMI Mi6
**PPSSPP ver** : v1.4.2-799-gbabfec523

**BTW**,what is the :
`FeedbackIncludeCRC = Note: Battery will be used to send a disc CRC` ??
What is it mean??? ....Cyclic Redundancy Check for disc and report ????
And the KEY MAPPING:
HOLD, REMOTE HODE,and NOTE ??
How to use it ?

Thanks very lot.

**Comment by Michal1324** [comment]
Does even virtual keyboard work in PPSSPP?

**Comment by peaceshi** [comment]
@Michal1324 only don't work there. I can change my PRO Ad hoc easily.

**Comment by hrydgard** [comment]
Yeah, that's an omission that should be fixed.

**Comment by peaceshi** [comment]
@hrydgard Thank you very much firstly.....emmmm........And I really want to know what is the meaning of the sentence that "FeedbackIncludeCRC = Note: Battery will be used to send a disc CRC". Because I am just translating it to other language at ppsspp-lang.

**Comment by hrydgard** [comment]
@unknownbrackets can probably explain better but the idea is to compute a CRC of the disc in the background, so that we can make sure that any reports are not from modified or corrupted images.

**Comment by unknownbrackets** [comment]
A lot of users end up with issues because their disc is corrupted - it might be missing parts, or it might be hacked with code to make it work on older firmwares (that inadvertently makes it not work in newer ones or in PPSSPP.)

The idea is that when you explicitly report compatibility (so this won't happen without you knowing), it'll check the disc CRC at the same time, which can help tell you if you're using a bad disc, or help other users by telling them you had a good experience with a good CRC.

-[Unknown]

**Comment by Michal1324** [comment]
Yeah I believe zip files with 7zip can check the CRC of content and the sites providing room probably have that CRC too
