### ISSUE TITLE
No multithreading option in system options as of most recent builds

### ISSUE THREAD

**Issue by gannon345** [hrydgard/ppsspp#10151]
There's no longer an option to turn multithreading on or off in system settings on the Android builds. Not sure if this is intended or not.

Not sure if it matters on PC, but on Android there are more than a few games that work better (we're talking 5-10fps difference) depending on whether multithreading is on or off.

**Comment by LunaMoo** [comment]
Removal of "Multithreading (experimental)" was intentional, it was a very buggy feature breaking a lot of games and even causing severe slowdowns causing lots of problems to people who often used it without even considering it might be what is ruining their experience then reporting their problems it as emulation issues.

 Just like with all the other dangerous speedhacks that done more bad than good and were removed in the past, that option will never return doesn't matter how much fps it gave to person X in game Y.

 Currently Vulkan backend which was a primary goal of the incoming PPSSPP 1.5, has much safer multithreading implementation activated by default, which might be backported to OGL, but it will be very unlikely to affect same games in same way, this project however is not maintained by M$ so you will never see any forced updates and are free to use outdated PPSSPP versions as long as you wish.

 Hopefuly this explains the situation, anyway this place is an issue tracker ment to track emulation issues not to ask support questions for which you're always free to use [PPSSPP forums](https://forums.ppsspp.org/index.php), as such I'm closing this.
