### ISSUE TITLE
Final Fantasy Tactics - inverted colors on some graphical elements in Direct3D 9

### ISSUE THREAD

**Issue by cliff7422** [hrydgard/ppsspp#10205]
I've noticed a small graphical error with this game using the new v1.5 Windows release. Under Direct3D 9 rendering, the battle cursor, facing indicators, and some text of certain menus appear to be negative images, or inverted colors. Also, if you look carefully, the cursor appears to be transparent, and so do the edges of the words "Ability Mp Turn". This issue does not occur when using the Direct3D 11 or OpenGL renderers in v1.5, nor does it occur in Direct3D 9 on PPSSPP v1.4.2.

D3D9:
![ulus10297_00002](https://user-images.githubusercontent.com/30216075/33405593-0f5e5628-d537-11e7-8f42-fed3d9befdb4.jpg)

D3D11:
![ulus10297_00001](https://user-images.githubusercontent.com/30216075/33405600-19f7a1de-d537-11e7-97c2-e402d91f3666.jpg)

D3D9:
![ulus10297_00000](https://user-images.githubusercontent.com/30216075/33405621-30c0e74a-d537-11e7-958e-acdab89870d8.jpg)

D3D11:
![ulus10297_00003](https://user-images.githubusercontent.com/30216075/33405626-353902d0-d537-11e7-9745-b80d15dde3df.jpg)

**Comment by unknownbrackets** [comment]
Could you try a few git builds?

https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

There's about 1000 changes made in PPSSPP between 1.4.2 and 1.5.0, but if you check v1.4.2-500-g424af6008 and it was a bug there, you can cut that in half.  If you try 8 to 10 builds this way (going by halves), you can find exactly the change that caused the bug.

-[Unknown]

**Comment by hrydgard** [comment]
Very likely some minor mistake with the 16-bit texture formats..

**Comment by cliff7422** [comment]
v1.4.2-372-g73a94f4b1 is the last build I found without the issue.
373 through 390 I cannot test, they all crash upon loading any game with D3D9 or 11.
v1.4.2-391-g393b3697c is the first build with the issue, and the crash is gone.

**Comment by unknownbrackets** [comment]
c2bd739 looks most suspicious.  There aren't texture cache changes in that range.

Some differences:
 * PSSetColorUniform3/VSSetColorUniform3 set alpha to non-zero now (unlikely to be the problem...?)
 * PSSetColorUniform3Alpha255 scales alpha to 0-1 instead of 0-25 (oops.)
 * Note: VSSetColorUniform3Alpha correctly scales alpha to 0-1.

Guessing it's the alpha.  `PSSetColorUniform3Alpha255` is used only for the color ref:
https://github.com/hrydgard/ppsspp/blob/39051f57fde588933da8826658a014837874420d/GPU/Directx9/ShaderManagerDX9.cpp#L264

Which to avoid rounding issues, was set as an integer value.

https://github.com/hrydgard/ppsspp/blob/1f0dfad4d7caeb703adb91df46aa106278ae3c58/GPU/Directx9/PixelShaderGeneratorDX9.cpp#L296

-[Unknown]

**Comment by hrydgard** [comment]
Oh, good catch. I'll fix it.

**Comment by hrydgard** [comment]
Let's see if that takes care of it.
