### ISSUE TITLE
Danganronpa on LG K8 (Mali-T720) (STILL not fixed)

### ISSUE THREAD

**Issue by Nexeno** [hrydgard/ppsspp#10200]
So, 1.4.2 still doesn't fix the bug, I have read contless issue reports here, my only way to play was with 0.9.1 and it worked for sometime, until chapter 1 and 2... There is a similer issue already posted on how when one object is selected another is interacted, My research has told me that it mostly happens with static(not moving objects/things in the background) objects. If this bug could be fixed by 1.4.3, It would be awesome!
Side Note: Everything works with PC and I am stuck in Chapter 2 because of a game progressing object having the switch bug(I call the bug where a object ,when interacted, interacts with another object the switch bug) 

-Nexeno

**Comment by hrydgard** [comment]
The bug? What bug? Sorry but that's the most confusing bug report I have ever read. There are thousands of games for the PSP, nobody can keep track of all the bugs that seem obvious to someone. Please state:

  * What should happen
  * What happens instead
  * Where in the game that is, preferably accompanied by a savegame.
  * On what hardware it works and doesn't work.

I can't even tell from your report whether the thing in Chapter 2 happens on PC or not ("Everything works with PC and I am stuck"). So it happens on Android, or does something else happen on Android?

Also please link to those "countless issues you've already read".

**Comment by Nexeno** [comment]
Sorry... I kinda got ahead of myself...

1: I played danganronpa on the pc too for sometime, that why I know that it only is on android.

2:when I select the object that is required to progress, it acts like I selected a diffrent object. This results in being stuck

3. It happens once in chapter 1 and chapter 2, I have not been able to play further. I manged to progress through chapter 1 because I had a save file from the pc. Chapter 2 however.... 

4. I know I am not the first person this had happened to because of:https://github.com/hrydgard/ppsspp/issues/6494

5: I own a LG K8 (2016) and the game often runs on 30FPS, and in ppsspp version 0.9.1, danganronpa works in buffered mode, but the bug still persists.

-Nexeno

**Comment by hrydgard** [comment]
This is one of those annoying issues where the game reads back stuff that it rendered using the GPU and expects it to match perfectly. Due to various kinds of precision issues it's hard to guarantee that exactly the right color will be returned. Most of the time it works but you know, mobile GPUs can be weird...

Maybe we should just intercept these particular draws and use the software renderer @unknownbrackets  ? :)

**Comment by unknownbrackets** [comment]
IIRC, the issue was generally dithering (even potentially on blit.)  If I'm understanding correctly, this has never worked on this GPU, which probably just means it's always had some color precision issue.

Does it happen on Vulkan?  I think there's a chance Vulkan may not have the same accuracy issues.

@hrydgard hmm... mixing them, huh?  I suppose it should work.  It is a smaller buffer so there's the possibility that it might render faster than a readback, heh.

-[Unknown]

**Comment by Nexeno** [comment]
If my phone CPU was weird I don't understand why it then works on 0.9.1 and doesn't work on 1.4.2 and on 0.9.1 danganronpa works in buffered mode.... Maybe there is some code in 0.9.1 that helps it work that way?

-Nexeno

**Comment by Nexeno** [comment]
I have not found Vulkan on my device and it still does not work with 1.5.3

**Comment by Nexeno** [comment]
Is this issue still being worked on? Please, I really want to play dangaronpa on my phone.

-Nexeno

**Comment by hrydgard** [comment]
The only surefire fix that is guaranteed to work (partial software rendering) is probably quite a lot of work. It'll happen, just not right now.

**Comment by hrydgard** [comment]
Is this still an issue?

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

We've reworked a lot of things with this rendering since the report, so it's very possible this has been fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
