### ISSUE TITLE
Could not connect to host (Error: P7011 S0)

### ISSUE THREAD

**Issue by JacobMrox** [hrydgard/ppsspp#10245]
What happens?
When trying to join an Ad-hoc (Plus or Original) match on Metal Gear Solid Portable Ops + on Coldbird.net (with DMZ/UPNP) or on Hamachi this error shows up on joining.
https://cdn.discordapp.com/attachments/384029697014628364/385958078270537738/unknown.png

What *should* happen?
Player should be able to join without this error showing up, surprisingly, no error is encountered in Free Vs mode, which is a barebones mode of the above, with one map and pre-loaded characters (can be accessed from the title menu).

Cheap fix: if the person joins with PPSSPP 9.9.1 this error doesn't show up, which I guess implies that something changed after this version and forwards which causes it.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Unrelated as far as I'm concerned.

**Comment by asferot** [comment]
Wasnt Coldbird shut down recently?

**Comment by JacobMrox** [comment]
No:
1- Coldbird.net is back, there were issues and reasons for it being down as a team member went rogue, its been restarted.
2- This has nothing to do with Coldbird, regardless of which server you're using, whether its local or not.

**Comment by unknownbrackets** [comment]
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
