### ISSUE TITLE
very laggy and sound choppy

### ISSUE THREAD

**Issue by fahadfoyjur** [hrydgard/ppsspp#10258]
What happens?

Sir the issue is very terrible ,
In my android mobile 3gb ram octacore 1.4ghz 
Still very laggy and choppy sound , i change every option and settings , bt not worked , why ?

What *should* happen?

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

**Comment by hrydgard** [comment]
What version of PPSSPP are you using? What phone model is it? Can you switch graphics backend to Vulkan?

If not, there's probably nothing more to do than to enable frameskipping, reduce the rendering resolution and live with it, your phone is not strong enough.

**Comment by unknownbrackets** [comment]
For octacore - just try to imagine how much better you would be at hammering in a single nail if you had 8 arms.  Not much better?  It's the same with emulating PSP games.  You could have 16 arms or 100 arms, and certain things (like hammering in nails) would take just as long.

Mhz is more important for PSP emulation than cores.

That said, probably even more important than that at this point is indeed Vulkan support...

-[Unknown]

**Comment by hrydgard** [comment]
With Vulkan we can at least make use of two arms for hammering :)

**Comment by leopard20** [comment]
@fahadfoyjur 
As hydgard and [unknown] said it's because your phone is not powerful enough.
Note that the amount of RAM or number of cores don't matter. Even if the CPU structure is inferior, the amount of MHz  doesn't matter either. 
Another thing that can affect the performance is whether your CPU uses a 64 or 32 structure. Your GPU and also RAM clock speed matter as well.
Take Apple products for example. Their dual-core CPUs beat most octa and deca core phones! Snapdragon is closely behind.

@hrydgard 
Congrats on the v1.5.4 release! How far are we till v 1.6.0?! I'm totally looking forward to it!

**Comment by fahadfoyjur** [comment]
I am using latest version of ppsspp , 
I am playing any games without lag , but psp games very lag ,
My phone not supported vulkan   , 
Model is symphony zviii  
Plz tell me the best settings , 
My phone is 1.4ghz octacore 
3gb ram 
Adreno 
Snapdragon 430

**Comment by fahadfoyjur** [comment]
and it use only one core of cpu why sir ?

**Comment by marosis** [comment]
Sir :D xD

**Comment by marosis** [comment]
What Are you playing of PSP games? You can try YouTube videos. Sometimes Is really good set Emulated CPU clock to 60Mhz. You will get extreme big Fps boost (5-15fps+)

**Comment by fahadfoyjur** [comment]
WHAT XD BRO ?
YEAH cpu speed 60mhz, 111,128  result best but sound sometime choppy , but fps some encrease 
 I wish devolaper add the dualcore enable button ,
Tnx bro

**Comment by fahadfoyjur** [comment]
I am playing call of duty roads to victory , and god of war

**Comment by marosis** [comment]
If you get lower MHZ, you will get better sound but you can have lover max fps. If you get higher Mhz, you will have choppy sound but can you have bigger fps if you have strong phone. Don't forget get 1xPSP resolution! It Is very good in places where is lot of graphics effects.

**Comment by marosis** [comment]
You Will have stable sound. And don't forget. In some games you could have problem with MHZ. like gran Turismo where you can only set 222MHZ for best sound(so this game Is nice benchmark:DD)

**Comment by marosis** [comment]
And i forgot. You can try some 20,30,60, unlimited fps cheat codes in forum. How to you can see in YouTube https://forums.ppsspp.org/showthread.php?tid=4799

**Comment by fahadfoyjur** [comment]
Yeah i undertand bro
any mazor update News ?

**Comment by SamueldeSena** [comment]
I already had a G3 bike with the same graphical settings that yours is as they said above is not only download and play and necessary time to have the best configuration for this device because as hrydgard your device is not powerful enough for this type of emulation by OpenGL then this topic can already be closed
