### ISSUE TITLE
Effects in Buffered rendering

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10252]
When i get non-buffered rendering, game Is realy nice Sharp but in Buffered rendering Is blury And dubled textures. You can see this on Kratos body:

https://photos.app.goo.gl/i3X6WcHX4lKcUTrf2

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

**Comment by marosis** [comment]
Android OpenGL

**Comment by marosis** [comment]
Sorry if this Is duplicate

**Comment by hrydgard** [comment]
Just increase the rendering resolution and you'll get the same sharpness. That blurry glow is intentional and happens on the real PSP - due to the low res it doesn't look blurred there though. Try this setting to simulate the same thing: "Lower resolution for effects" set to Aggressive, then you'll keep the sharpness but the glow will be blurry.

**Comment by marosis** [comment]
I've set resolution 1:1

**Comment by marosis** [comment]
Yes Is it better but not So much

**Comment by marosis** [comment]
Why this Is not working on 1xPSP resolution?
