### ISSUE TITLE
Call of duty roads to Victory fps 

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10261]
What happens?
When i swich to non-buffered Rendering game have still 60/60 FPS, but when i swich to Buffered rendering , game have fps lower, but There Are not any graphics effects. So why i have fps lower?  Non Buffered rendering: https://photos.app.goo.gl/kuJcSCPOPSQ5laNK2 Buffered rendering:https://photos.app.goo.gl/e0qYY9qhikbdN8Dw2 can we here improve Performance? Yes i know i can set 1xFrameskip but why?

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

**Comment by hrydgard** [comment]
Well, non-buffered saves quite a bit of graphics memory bandwidth so it runs faster, that's why we still keep the option - otherwise I'd have removed it by now.  It's normal that it's faster, but yeah, keep in mind that some effects might not work. That doesn't mean that you'll necessarily see extra effects with buffered, that depends entirely on what the game does.

There's not really much we can do about it.

**Comment by marosis** [comment]
Ok, i will try find 30fps cheat on forum because i hate frameskip ( game Is really laggyyyy with frameskip and get lower fps)
