### ISSUE TITLE
[Feature Request] Add brightness adjustment setting

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10375]
Can you add a setting for adjusting the brightness in games? Some games have a very dark atmosphere that makes them impossible to play during the day, even with native display brightness maxed up.
It's an essential in all emulators.

**Comment by LunaMoo** [comment]
You can do this very easily with any post process shader, just edit it's fsh file and on it's very end multiply the value that get's set to gl_FragColor.rgb(or gl_FragColor.xyz) by floating point value above 1.0 to increase or below it to decrease the brightness.

For example at the end of 5xBR-lv2.fsh:
````
gl_FragColor.xyz = res;
````
change to 
````
gl_FragColor.xyz = res * 1.1;
````
to increase the brightness by 10%

 You could also check my overgrown shader which can be easily customized which includes a lot of efffects including color modification in [here](http://forums.ppsspp.org/showthread.php?tid=6594).

**Comment by leopard20** [comment]
Thanks for the suggestion but it only works on the PC version. What about android?

**Comment by LunaMoo** [comment]
But it works just fine on android. Don't remember if default shaders can be edited there since I'm not using PPSSPP on android and some time passed since I last tried, but you can just add custom shaders to PSP/shaders folder(creating one if it doesn't exist ~ PSP folder definitely will exist;p as it stores all savedata/savestates and some other stuff) and they will be added to the list.

 When using my shader on android it's "M"(mobile) variant is prefered and if performance is huge issue just remember to disable all effects and enable only shadeboost with brightness or gamma whatever you preffer, my shader has big, but human-readable config at it's very top so it's really easy to edit without any experience or specific knowledge.

**Comment by leopard20** [comment]
I'll ckeck it out. Thanks again.

**Comment by unknownbrackets** [comment]
I think this was implemented on #12901, included in PPSSPP by default and should work on all platforms.

If that's not working, comment and we can reopen.

-[Unknown]
