### ISSUE TITLE
New build error on nexus one

### ISSUE THREAD

**Issue by endrare** [hrydgard/ppsspp#10392]
New build error when open on my nexus one android 2.3, I try to build v1.5.4-86-g3a44769f4 
screenshot: https://ibb.co/bRAX2w

**Comment by hrydgard** [comment]
Hm, I thought I tried just that recently. I'll take a look later today.

**Comment by hrydgard** [comment]
I just built a new build myself, it ran just fine on Nexus One. Did you build yourself or download from buildbot or which build is it?

**Comment by endrare** [comment]
I try to download again the new version in buildbot, and the result is still the same in my nexus

**Comment by unknownbrackets** [comment]
I think this has been confirmed fixed since - is it still happening with 1.6.x?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
