### ISSUE TITLE
Right analog stick for first person Shooter games

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10412]
games in FPS mode use for viewing four buttons triangle, square, circle, cross. For gamepads with the right analog stick, you could create a mapping button to convert from classic mode to FPS mode where you could play with the right analog stick. if we went to the game menu, we would switch over with a mapped button) into the classical mode in which we would move in the menu again over the cross, triangle, circle, and square

**Comment by marosis** [comment]
Right analog button must be mapped UP=Triangle, left=Square, right=circle, Down=cross

**Comment by hrydgard** [comment]
If you have a gamepad with a right stick, you can already very easily map its stick directions to the buttons in Control Mapping. Try it.

**Comment by marosis** [comment]
I tried but I must off button ANALOG( I using PS2 controler). When I offed ANALOG button D-pad Is not working And i need him for crouching, reloading or throthing Grenade. Pls only create new mapping button for this:)

**Comment by LunaMoo** [comment]
By control mapping Henrik ment Settings->Controls->Control mapping, not the mapping feature of your gamepad.

 In those old PS2 gamepads and their clones you really have to keep analog activated all the time as it's completely useless "feature" outside of running PS1 games on PS2 maybe. You should also have it activated before running app or at least before mapping your buttons in that app since it basically replaces analog input with d-pad/face buttons, reducing number of input you can map which is probably what is confusing you.

 Also there's no need to swap anything, typically if a game uses face buttons for aim and uses it for other things in menus people will just map PSP face buttons to their gamepad face buttons AND to their right analog stick. In PPSSPP nothing stops you from mapping multiply input for same emulated input or as a matter of fact other way around which makes a feature to swap things that could just be mapped at once - completely useless.

 For few titles there's an even better option to patch the game itself with real support for right analog using cwcheat, but such patches were only made to a handful of games.

**Comment by marosis** [comment]
It wouldn't be created for PS2 controler. Maybe for Xbox controlers because lot of people have Xbox and using him for PC( or for android)

**Comment by marosis** [comment]
And please every PS4 Controller have problem with bluetooth conection.(SLOW REACTIONS). This problem Is only in controler not in android or PC! Could you fix it?
