### ISSUE TITLE
Eyepet black screen when starting.

### ISSUE THREAD

**Issue by xiushudongfang** [hrydgard/ppsspp#10434]
#9927 add supporting usb camera  for android .Eyepet [UCES01531]  is a ar game  using camera.but it stuck when starting. the log is here:

12-23 16:46:11.967 26356-880/? E/PPSSPP: [HLE] UNIMPL sceUsbGetState: 0x222
12-23 16:46:11.967 26356-880/? E/PPSSPP: [HLE] Unknown syscall: Module: (unknown) (module: 255 func: 4095)
12-23 16:46:11.983 26356-880/? E/PPSSPP: [HLE] UNIMPL sceUsbGetState: 0x222
12-23 16:46:11.983 26356-880/? E/PPSSPP: [HLE] Unknown syscall: Module: (unknown) (module: 255 func: 4095)
12-23 16:46:12.000 26356-880/? E/PPSSPP: [HLE] UNIMPL sceUsbGetState: 0x222
12-23 16:46:12.000 26356-880/? E/PPSSPP: [HLE] Unknown syscall: Module: (unknown) (module: 255 func: 4095)
12-23 16:46:12.017 26356-880/? E/PPSSPP: [HLE] UNIMPL sceUsbGetState: 0x222
12-23 16:46:12.017 26356-880/? E/PPSSPP: [HLE] Unknown syscall: Module: (unknown) (module: 255 func: 4095)
12-23 16:46:12.033 26356-880/? E/PPSSPP: [HLE] UNIMPL sceUsbGetState: 0x222
12-23 16:46:12.033 26356-880/? E/PPSSPP: [HLE] Unknown syscall: Module: (unknown) (module: 255 func: 4095)

**Comment by LunaMoo** [comment]
![fail](https://user-images.githubusercontent.com/5485237/44123994-2fa77030-a02b-11e8-9737-02010d7d25d1.jpg)
 Either the returned state is wrong(0 would make the game boot, but seems wrong), or the unknown syscall here just needs to be implemented, no idea what it is and what it should be doing, but if it returns 0 instead of error, the game does boot just fine.

If someone wants to test on android, here's the cheat workaround made for eu version:
[code]
_S UCES-01462
_G EyePet
_C0 Workaround
_L 0xE0014D40 0x001BA22C
_L 0x201BA22C 0x00001021
_C0 Workaround [Disable]
_L 0xE0011021 0x001BA22C
_L 0x201BA22C 0x0E294D40
[/code]
No idea if it doesn't have more problems, as on pc ppsspp does not have camera support. I just got it on psp(whole package with psp 450x cam) and overall it requires:
- camera support,
- mic support(can't even hatch eyepet without it as you warm the egg then cool it down by blowing into the mic;]),
- a physical eyepet card.
