### ISSUE TITLE
Combo Buttons Using X360 Controller

### ISSUE THREAD

**Issue by BorbingoBoy** [hrydgard/ppsspp#10437]
Hello. I am trying to play PSP GTA games on my PC using my X360 controller. I want to make use of the right analog stick on my controller to be used to look around in the games. However, a combo button is required to make that possible, but it is impossible to map it - it's only available as an on-screen button. I tried to edit INIs in hope to be able to use the combo buttons, but that didn't work either. Can you, please, explain me how could I do this, or implement mapping combo buttons?

Thank you!

**Comment by LunaMoo** [comment]
The only reason touch controls got "combo buttons" is because they can't be mapped, just enabled/disabled for basic emulated input.

 Real/physical input is not restricted, you can just use control mapping screen to map your gamepad input into multiply emulated inputs at once so when you press one button, more emulated buttons will get pressed.

  I'll close it, you can still post in here, if you need a better explanation, but I think your problem here was just a missunderstanding on what control mapping can do - as it can do more than all touch control features combined allow doing. By pressing + near control mapping you can add new mapping without replacing existing, so you can also have multiply real input doing same thing.

 Just to note, for a few games you can also find around the forums fan made cwcheat patches, that can do things like that better by modding how game works, in some cases adding real analog aim to games that never supported it as most psp games used thumbstick in very limited ways since it's not exactly as comfortable or accurate as analog stick of a full size gamepad.
