### ISSUE TITLE
Street fighter alpha 3 is not saving the game

### ISSUE THREAD

**Issue by SamueldeSena** [hrydgard/ppsspp#10462]
the street fighter game does not save this problem occurs in android i have used all the settings but not dru sure i use the american version USA ULUS10062 to not recent version of the emulated by the build my phone and moto g5s plus adreno 506 snapdragon 625
![screenshot_20171227-144702](https://user-images.githubusercontent.com/34135636/34387564-0261ea26-eb16-11e7-98fe-ad21216d3b27.png)
![screenshot_20171227-144709](https://user-images.githubusercontent.com/34135636/34387580-23eb2ee6-eb16-11e7-98de-244fb74d267e.png)
![screenshot_20171227-144731](https://user-images.githubusercontent.com/34135636/34387595-4387c746-eb16-11e7-814c-25db53c98fe2.png)

**Comment by unknownbrackets** [comment]
Can you upload a debug log of the game?  You may need to run it on a PC with DebugLog.

-[Unknown]

**Comment by ppmeis** [comment]
Tested with latest Windows build. First game will not let you create a savefile, we have to skip the load at first boot. Then go to options and create the savefile manually. After that, we can load save file everytime we load the game.

**Comment by DarrenBranford** [comment]
I'm just going to mention this as some people may not be aware.

This is an issue with the game which also affects physical PSP's.

The game was originally released when the maximum capacity Memory Stick a PSP could use was 2GB. After firmware updates increased the maximum capacity, this game could not read Memory Sticks with more than 2GB of free storage. The accepted "fix" (as recommended by Capcom) was to simply make sure you had less than 2GB of storage.

Strangely, though, while using PPSSPP, I have noticed that if you have much more storage (more than 6GB free, if I remember correctly) the game will be able to read the Memory Stick.

So, due to some weird coding bug with the actual game, it will fail to recognise a Memory Stick if you have between 2GB and 6GB of free storage in your SAVEDATA directory. Both in PPSSPP or with an actual PSP.

**Comment by unknownbrackets** [comment]
Ah, this also happens in some Harry Potter game.  There may be a pattern - for example, it might stop working again at 6GB and work again at 8GB.

I guess there are a few options:
 * Always limit to 2GB storage space, instead of 9GB as current.  I don't know if this works in Harry Potter.
 * Detect and patch out the math somehow (ugh.)
 * Limit specific game ids to specific storage amounts.

There are games which can record high quality video (like Dissidia) but I don't know how large they can really get.  So not sure what a good max would be for everyone.

-[Unknown]

**Comment by DarrenBranford** [comment]
I've just finished a quick test and there is indeed a pattern. Starting off at 9GB free, adding a 1GB junk file and testing the game, it also fails to auto load between 6GB and 8GB.

I couldn't find any specific lists of affected games but I also remember Lego Star Wars II and a Tony Hawks' game being problematic on my PSP.

**Comment by hrydgard** [comment]
Yeah I was hoping that this would be just a case of different firmware versions the game requests, so we could limit the storage reported for certain firmware versions, but if it's a real game bug where even capcom recommends to shrink the space, I think a compat.ini setting for affected games should be fine, where we simply lie about free space to listed game IDs.

**Comment by SamueldeSena** [comment]
My problem has already been resolved I close this topic

**Comment by vnctdj** [comment]
This doesn't look like it should be closed...

**Comment by Panderner** [comment]
it's seems the save data issue for this game are now fixed along with Harry Potter and the Goblet of Fire.

**Comment by ninjz** [comment]
So how do we fix this? I'm still getting this issue

**Comment by hrydgard** [comment]
@ninjz what version of PPSSPP are you using?

**Comment by ppmeis** [comment]
I just tested in latest windows build. I confirm in compat.ini ULES00235 in my case is on the list. I don't if this is an issue but on the first startup the game ask for enable autosave. You need to create the save manually under Options Mode:

<img width="1094" height="841" alt="Image" src="https://github.com/user-attachments/assets/d7404fb0-ab84-491b-ba88-e488ce8876fe" />
