### ISSUE TITLE
Detect the X/O memstick warning in Japanese games?

### ISSUE THREAD

**Issue by unknownbrackets** [hrydgard/ppsspp#10497]
This is a frequent problem:
http://forums.ppsspp.org/showthread.php?tid=23857

Many Japanese games, for some reason, have a convention of showing a warning when you don't have any save data.  A lot of people think games don't work, or get confused and stuck because they keep pressing X to bypass the message, but they need to press O.

Wondering if it would make sense to detect if...
1. The game is a J region game.
2. There's no save data or save states for the game.
3. The game has checked for save data at least 3 times in a row.
4. It's still within maybe 60? seconds of initial game start.
4. Perhaps even, the user has only pressed X.

Maybe not an ideal heuristic, but we could show an on screen message and potentially help a lot of unsuspecting users.  But maybe it's not worth the complexity... thoughts?

-[Unknown]

**Comment by unknownbrackets** [comment]
Anyone have thoughts on the above?  Maybe there's a simpler way.  It's clear that a lot of people get confused by this.  For example, see here:
https://report.ppsspp.org/game/NPJH50588_1.01

Another simpler thing I thought of was, if the game is a Japanese game and does a memory check, we just show an osm at start (maybe once, and set an ini setting) about the X/O business.

-[Unknown]

**Comment by LunaMoo** [comment]
I think the general idea here is wrong. Not all games follow that generalization, you can find games from japanese region that used X for confirm and O for cancel just as you can find games from EU or US regions which used O for confirm and X for cancel. I can't tell from memory any examples, but I'm sure I saw at least a few such games in the past.

 OSK is an annoying thing to force on everyone to solve an issue that basically only affects mindless pirates that download all PSP games without knowing anything about them.

 If you look around, many games in compatibility reports seems to have very low rating not even on the fact people can't boot them, but even more based on the fact someone disliked the gameplay(or lack of it), but that's something people who download random games of the net do all the time especially mobile users which see "stars" as their feelings towards certain title and nothing else, this emotion based rating among mobile users is soo stupid that you can even see popular games rated high on devices that could never physically be able to run it without awful glitches or/and unplayable performance.

 Probably it's impossible to validate user-provided compatibility results without some form of human curation over it. Basically reviews of reviews, but even that would not work if left to random users as they would only end up trying to rate their opinion higher than actual facts. But that and how unreal those reports are is a whole different issue.

 The NPJH50588_1.01 which you linked does include mostly screenshots from english fan translation which does translate what button should they press everywhere except that first screen and fan translation team left that info in the release text, it turned out to be a better copy protection than denuvo on steam.

 Despite not feeling like this should be solved I really don't think this issue even CAN be solved at least not by a text which can be ignored, because people affected by it will most likely do exactly that - ignore it. You'd have to include some annoying popup that can be closed only after reading with understanding that O = confirm and X = cancel in most japanese games.

**Comment by unknownbrackets** [comment]
Well, I don't think it's fair to assume everyone playing a Japanese game that uses O for confirm either knows that or is a pirate.  It's basically this:

https://xkcd.com/1053/

There must be some lucky people importing games for the first time, probably lots of things to think about and excitement for them, and they miss this one thing in a README they skim as they are jumping to finally play the translation of a missed game or enhanced version in some series they like.

But it's a fair point that they'd probably miss this message too.  You're definitely right that assuming any J region game uses O as confirm is wrong too...

I'm not really trying to solve the poor quality feedback problem, as much as I've seen messages on IRC, Discord, the forum, even other sites - where people thought a game didn't work or a translation was glitched, but it was actually because of this.

And to be fair, I've fallen into the trap myself.  Start a game up for testing, press X a few times, "oh no, did my change actually break it this early?  but how?"  Then realize, "oh right, I should be mashing O.  Derp."

-[Unknown]

**Comment by LunaMoo** [comment]
While I can agree this might affect other people not just "preservationists" aka pirates, the way of "blah, doesn't work, imma give it 1 star" is really not a mentality of someone that paid a lot for something old. Person like that will read, most of the time google or ask on the forums why he can't pass some screen or at least use a google translate to try to figure out the message on the screen, in case of importing physical copy, people like that will read a lot even before buying the game or while waiting for it to arrive.

 There are also other quirks like those enhanced reality games which require physical cards to play where people will also have no idea what to do once those games are fully playable, I don't think emulator should be telling the player how to play a game or provide solutions for somebody's lack of knowledge or lack of the required content just so they can play.

 For things like that FAQ is a place to go, but again most users probably never even saw PPSSPP site.

 Maybe we could get another "FAQ", a bit different from the one on the site, inside PPSSPP UI linked to a button on main screen and there it could explain this among many other things and common issues, including performance problems, savestates time travel issue, the fact that default are BEST settings, not some awful hacks shared on random youtube videos with "BEST PPSSPP SETTINGS" in the title etc..

**Comment by unknownbrackets** [comment]
I think your point about the camera games is very valid.

A FAQ might be a challenge to keep translated.  But I think you're right that it'd be the more effective way to solve this.

Going to close this issue.

-[Unknown]
