### ISSUE TITLE
PES 2014 MULTIPLAYER

### ISSUE THREAD

**Issue by Endarko** [hrydgard/ppsspp#10513]
hy, why if multiplayer pes2014
file option or save data back
to the beginning does not go
to save the latest transfer
data?

**Comment by unknownbrackets** [comment]
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
