### ISSUE TITLE
sceSas.cpp:649  invalid type error when logitech headphone got plugged in

### ISSUE THREAD

**Issue by Raymond-yao** [hrydgard/ppsspp#10510]
What happens?
When we are using PPSSPP to play Monster hunter P3 online together, it broke the connection frequently, and I looked at the log, it got 

01:44:658 CsePspSndDrv E[SCESAS]: HLE\sceSas.cpp:649 80420020=sceSasRevType(0a000940, 65535): invalid type
04:34:880 idle0        E[SCEKERNEL]: HLE\sceKernelThread.cpp:12 KernelGetWaitID ERROR: thread 312
04:34:880 idle0        E[SCEKERNEL]: HLE\sceKernelThread.cpp:11 __KernelGetWaitValue ERROR: thread 312

My computer had a Realtek sound adapter and a logitech headphone with its software. So I thought it may input a invalid PSP_SAS_TYPE number to the sceSas instance.

What *should* happen?
If this has a compatible issue with sound adapter, is there a way to disable the  

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
i7 6700HQ, GTX970m. Win 10

**Comment by Raymond-yao** [comment]
![1](https://user-images.githubusercontent.com/20074378/34643503-ff5a9a28-f2d9-11e7-8330-3985c7504454.jpg)

I found more error log, and pasted there (sorry for the picture quality lol). I am not sure whether the socket error were caused by the scsSasRevType invalid type. the error codes I got here were 10035 10037 and 10056. I searched online and it reflected a socket reconnect issue (raise a connection that has already been raised).

**Comment by unknownbrackets** [comment]
sceSasRevType simply indicates that the PSP game passed an invalid parameter to a PSP API.  Many games send invalid parameters normally, even on a real PSP.  This probably isn't directly caused by plugging things into / unplugging your headphones, since we don't even communicate that to the game.

10035 (WSAEWOULDBLOCK) probably means a bug in the networking code in PPSSPP.  Same with 10037 (WSAEALREADY) and 10036 (WSAEINPROGRESS), it means that PPSSPP wasn't handling blocking network IO correctly.

However, this could ultimately have been caused by latency.  For example, it could be that PPSSPP assumes packets are being sent between clients quickly, and this error might only happen when they are slow enough that a buffer fills up.

(also, sorry - multithreading was a mistake, meant to select adhoc.)

-[Unknown]

**Comment by Raymond-yao** [comment]
Thanks for your reply! So you believe the sceSasRevType is not supposed to be able to break the connection even if it is invalid right ? This happened so frequently that we connected to the hall for several minutes and the connection broke without even feeling there was any latency from the game character or the game. So I doubt it may not be a network issue but a PC setup issue that it crashed the instance and killed the socket on its own.

**Comment by unknownbrackets** [comment]
It sounds like this may be related to, or possibly the same as, #10832.

-[Unknown]

**Comment by unknownbrackets** [comment]
Is this still an issue on the latest git build with recent networking improvements?  Changes were made to use async more.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
