### ISSUE TITLE
ppsspp crashes while playing

### ISSUE THREAD

**Issue by gyanprakash13** [hrydgard/ppsspp#10524]
What happens?
I used this app a long time back now it works more smooth but in harry Potter goblet of fire it crashes in between after playing a minute even the saved file doesn't work, any solution?
I'm using the latest version of ppsspp on android

What *should* happen?

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

**Comment by hrydgard** [comment]
Why close? Did it stop crashing?

**Comment by gyanprakash13** [comment]
This stopped crashing by changing the settings but now the saved files in the menu aren't working and the game is being stuck in recognising a memory

**Comment by hrydgard** [comment]
How about the latest build, do you still have problems?

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
