### ISSUE TITLE
[iOS]The archive may be corrupt or unreadable.

### ISSUE THREAD

**Issue by RoJoHub** [hrydgard/ppsspp#10527]
**What happens?**

When i finish archive.The xcarchive is in `~/Library/Develop/Xcode/Archives/`

I click the file but show `The archive may be corrupt or unreadable.` 

---------

**What *should* happen?**

I want to build a IPA.But it failed

---------

**What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.**

- Mac OS 10.13.2
- XCode 9.2(9C40b)

**Comment by unknownbrackets** [comment]
This probably means a problem with Xcode or something - it might be better to ask a question like this on stackoverflow or something.

-[Unknown]

**Comment by RoJoHub** [comment]
Did anyone encounter the same problem as me?

**Comment by RoJoHub** [comment]
@unknownbrackets 
In other project,i can archive normal.

**Comment by KentuckyCompass** [comment]
1. What phone and iOS version?
2. What is **Architectures** set to under Build Settings? (should be armv7 arm64)
3. What is **Build Active Architecture Only** set to? (should be No)
4. Make sure you don't have any Code Signing or Provisioning Profile problems

If it's an iPhone 5 or 5c, it's important that **Architectures** contains **armv7** because those phones are 32 bit.
If it's iOS 11 or up, it's important that that **Architectures** contains **arm64** because iOS started strictly requiring 64 bit and refusing to launch 32 bit apps.

Normally that shouldn't be a problem because **Architectures** should have both. The default is "armv7 arm64". It is possible that you accidentally configured cmake to generate a project that builds for the simulator instead of a real phone.

**Comment by Vertpin** [comment]
^i have mine set to arm64 only, yet it won’t build on my ios11 iPad. :/

**Comment by danphamus304** [comment]
arm64

**Comment by RoJoHub** [comment]
-  What phone and iOS version? (Just archive)
- `Architectures `  => `armv7`  `arm64`
- `Build Active Architecture Only` => `No`
- Both company and enterprise are failed (It seems that my account is no problem )

> It is possible that you accidentally configured cmake to generate a project that builds for the simulator instead of a real phone.

I don't understand.How can generate a project that builds for a real phone.

<img width="770" alt="1" src="https://user-images.githubusercontent.com/15648309/35513329-a001493e-053d-11e8-8cf1-27af0c991b1d.png">

**Comment by KentuckyCompass** [comment]
@RoJoHub since your Architectures is set to "armv7 arm64" it looks like you are building for real phones and not the simulator. I'm not sure what's wrong.

**Comment by unknownbrackets** [comment]
Is this still an issue?

-[Unknown]

**Comment by hrydgard** [comment]
I believe this is outdated, I'll close it.
