### ISSUE TITLE
Prince of Persia Rival Swords - Yellow Screen

### ISSUE THREAD

**Issue by XTutorials** [hrydgard/ppsspp#10522]
What happens?
When I start the game it seems it starts normal, until I get to the menu or in-game where everything is yellow.

What *should* happen?
The game should've worked fine and without all that yellow mess.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
 I am running this on a iPhone 7 with iOS 11.2.2 non-jailbroken. Is the issue solvable or I won't be able to run one of my favorite games on this emulator?
![img_0172](https://user-images.githubusercontent.com/26814078/34827205-1774c294-f6e2-11e7-8a1a-f813924ae6c2.PNG)
![img_0173](https://user-images.githubusercontent.com/26814078/34827213-1e1e777a-f6e2-11e7-883c-de73e5004043.PNG)
Here are some images with the problem.

**Comment by brujo5** [comment]
![screenshot_20180111-125134](https://user-images.githubusercontent.com/4172898/34844304-4211a9b8-f6ce-11e7-92d8-0a38eae3a040.png)
![screenshot_20180111-125117](https://user-images.githubusercontent.com/4172898/34844327-4b3510f2-f6ce-11e7-82a8-12b6e2cdbb93.png)

Working perfect in Android

**Comment by XTutorials** [comment]
I am running it on iOS. But still, can you provide me the link for the iso and what settings did you use?

**Comment by leopard20** [comment]
Switch to vulkan if you can. I had the same issue on my Snapdragon 821. Using vulkan backend fixed it for me.

**Comment by leopard20** [comment]
Oh wait I do! See if this works for you:
[savedstate.zip](https://github.com/hrydgard/ppsspp/files/1625018/savedstate.zip)

**Comment by brujo5** [comment]
iOS not use Vulkan, they have Metal API  but not supported in ppsspp
The issue could be related to slow effects on/off

**Comment by XTutorials** [comment]
@leopard20 I have placed the savestate into the right folder and it does not even get recognized it the app. Also I saw that your savestate is named like this: ULUS10240_1.01_0 ,where mine is named ULUS...._1.06-0. Is that a version name or something and is why it doesn't work? I think you ran it on a older version of PPSSPP. But thanks for the effort of trying to help me.

As @brujo5 said, iPhones have their own prioritary API which is Metal. Maybe that causes the error. I've played with the settings for more than 1 hour and it still does't work. Either yellow screen, either black screen when I change some settings.

**Comment by leopard20** [comment]
I have no clue as to why the names are different.
But yeah I used to play it on v1.4.2. Later I decided to play PoP Revalation first so I abandoned it.

`As @brujo5 said, iPhones have their own prioritary API which is Metal. Maybe that causes the error`
That's why I said "if you can" 'cause I wasn't sure!😉
It's a shame thought, cuz iOS could really use that feature. It gives a massive performance boost!

Why don't you try the Windows version? Run the game on PC, and after selecting New Game and skipping the cutscene, save the state, then transfer the files to your phone (use different backeneds to see which one does the trick). I think as long as you don't run into a loading screen or cutscene you can play fine. But if things get messed up again you'd have to transfer the files to PC, pass that cutscene or level and then transfer the files back again. 
I just hope that saved states are cross compatible between PC and iOS (I know they are for Android).

I used to have an issue in PoP Revelations, where the keys got stuck after I rotated a lever. So I transferred the files to PC, passed that part, and then transfered the files back to my phone.

**Comment by XTutorials** [comment]
Well, I didn't think of that but that was useless. At least on mystery solved-- my save state from PC had same version as my iPhone's so I was able to transfer it and to be recognized by PPSSPP. However, when I try to load the state the app crashes, unfortunately. So that leaves me to just hopefully wait for a fix or not play this game on my phone.
But thank you for your help!

**Comment by unknownbrackets** [comment]
Some games were released in different versions.  For example, they might've fixed bugs and released new discs.  ULUS10240_1.06 indicates version 1.06 of the game.

Of course, this could be other changes too.  When hackers modify games, they may also change this version to keep track too.

It could be different versions of the game have different problems, or that hacks cause certain problems.  But it could also just be the PowerVR OpenGL drivers on the iOS device.

Are you able to save in game, and the load the save game from your PC?

-[Unknown]

**Comment by XTutorials** [comment]
Yes. I am able to run the game perfectly on my PC with latest PPSSPP.

**Comment by Afridi007** [comment]
Can you give me the save state of the city garden save point??

**Comment by leopard20** [comment]
I think your phone supports the Vulkan backend. Using that will fix this issue.

**Comment by weihuoya** [comment]
yellow screen on android opengl backend, pc opengl backend don't have this issuse. weird

**Comment by weihuoya** [comment]
This is int precision problem for opengl es.
in DepalettizeShaderCommon.cpp file, function `GenerateDepalShader300`,
add this for opengl es
`WRITE(p, "precision highp int;\n");`

**Comment by leopard20** [comment]
@weihuoya 
You're pretty good! 😉 Why don't you create a pull request yourself?!

**Comment by weihuoya** [comment]
ok, pull tomorrow, sleep.

**Comment by hrydgard** [comment]
Fixed by #11111.
