### ISSUE TITLE
Natural Postprocessing Shader is awesome but Blurry

### ISSUE THREAD

**Issue by tilkinsc** [hrydgard/ppsspp#10535]
So natural looks very blurry unless you upscale the rendering resolution. This is bad when you want to run full screen as you must have `rendering resolution: auto` on to get good detail. It would be nice for there to be an upscale switch on post processing so that it looks better. Natural looks so good then.

So a hack would be to guesstimate what upscale you need by some calculations done by taking your screen resolution into account and setting the appropriate rendering resolution. Then setting it up a level or two.

**Comment by asferot** [comment]
But you can set rendering resolution manually. Most people use manually set resolutions anyway, depending on power of their PC and such.

**Comment by Hydroque** [comment]
Correct, but auto can scale to make it more perfect.

**Comment by LunaMoo** [comment]
Not really, auto set's closest rendering resolution which only includes standard multipliers, it's not "custom res" which PPSSPP by choice will never have, so if you use it on some popular resolution which isn't a multiplier of PSP res like 1366x768. etc. it will be using closest res above it, in that example x3.

 Also blurry effects of shaders are often desired, we should not force every blurry shader out there even those designed for AA to be used for SSAA, that was always an user choice.
 I would add that when trying to use a blurry post process for super sampling anti aliasing(SSAA), it's best to add OutputResolution=True to it's ini file options if it doesn't already set it, doing so will still use whatever size of rendering resolution you set, but use your display resolution for the output which will then avoid resizing with linear/nearest filtering(screen scaling filter) that could mess up details, it will also make it less demanding for the gpu if rendering resolution was set to much bigger than display screen since the output of the shader will be already downscaled to fit the display.

 If you're requesting a new flag/shader ini file option which will force rendering resolution to be twice the display size(for SSAA) ignoring the rendering resolution setting completely, that could be done, we already have a flag for upscaling shaders doing the opposite. Such flag should not be set to default shaders that people might be using as it would make that shader 4 times more demanding than it already was.(resolution changes are exponential)

**Comment by leopard20** [comment]
@LunaMoo
Didn't I fix this already?

**Comment by LunaMoo** [comment]
No, at least to my understanding the person here didn't wanted a shader with most of it's code removed, he wanted the shader to use double the resolution automatically. Higher resolution combined with blurry effects is used for super sampling anti aliasing.

**Comment by leopard20** [comment]
@LunaMoo
Right. I only read the title!

**Comment by tilkinsc** [comment]
Not automatically, but have an option to upscale it easily accessible.

**Comment by LunaMoo** [comment]
You're missusing the word upscale, upscaling means rendering at low resolution and then scaling it up to fit the screen, 5xBR shaders are doing that for example. What you described is called downscaling, that means rendering at resolution above display res and then scaling it down to fit the screen/window.

 We already have a non automatic easy setting to do that already - it's called rendering resolution, you simply set it above your display resolution and that's it, the only "easier" way is automatic.

 And as for that since we do it already with upscaling shaders, I now opened a PR with similar change for downscaling shaders, I don't agree on adding it to existing shaders by default even if it would make them look much better on modern pc's since downscaling is very heavy and PPSSPP is used by many people with weak/ancient hardware, however as all shader flags, changing any shader to use it means editing an ini file, so anyone will be able to easily change any blurry shader of their choice to behave that way using any basic text editor.
