### ISSUE TITLE
What are the minimum/recommended hardware requirements?

### ISSUE THREAD

**Issue by Kovaelin** [hrydgard/ppsspp#10560]
I found a thread on the forums from years ago, but I'm wondering if anything has changed between then and now. Would it be possible to include this information in the readme.md, please? Thank you.

**Comment by ppmeis** [comment]
Hello @Kovaelin 

1st - You have the answer in website on Guides & Help:
http://www.ppsspp.org/faq.html - What are the PC CPU and GPU requirements?
http://www.ppsspp.org/guide_hardware.html - Recommended hardware for PPSSPP

2nd - Please use forum for questions, Issue tracker is just for investigating emulator issues and game errors.

Thanks.

**Comment by hrydgard** [comment]
The absolute minimal hardware requirements are so small these days that they're not worth mentioning. Any device out there should be able to run PPSSPP to some degree, even if the more heavy games will run slow.

**Comment by Kovaelin** [comment]
Does that include tablets? The hardware on those have not progressed nearly as fast as phones. The price tags are still relatively high just for something as simple as 2 GB of RAM.

**Comment by unknownbrackets** [comment]
RAM is probably not the best measure of what works well for PPSSPP.

Here are the main categories that affect whether a device works well with PPSSPP:
 * RAM
 * Storage
 * CPU Cores
 * CPU Mhz
 * GPU
 * OS

RAM: The PSP had 64 MB of RAM (games were allowed to use less than 50% of this.)  Between save states, emulator overhead, your operating system, etc. as long as you have around 1.5 GB of RAM you're gonna be fine.  More for higher quality settings.

Storage: Keep in mind the size of PSP games, save data, save states, and also non-PPSSPP things you want to store on your device.  You probably want at least 16 GB of storage, and likely more.

CPU Cores: Think of cores as extra arms.  Emulating the PSP's CPU is like hammering in a nail.  So if you're wondering whether a 16 core device will help PPSSPP, just think about how much easier it'd be to hammer in a single nail if you had 16 arms.  In practice, 2-4 cores is ideal.

CPU Mhz: The higher, the better.  This is how fast that nail gets hammered in.  You want something 1.5 Ghz or faster, ideally at least 1.8 Ghz.

GPU: This is harder to compare, but also important for performance.  At a minimum, you want it to support OpenGL 2 or GLES 2.  But if possible, you want support for GLES 3.1 or Vulkan.  Vulkan is best.

OS: You want to run at least Android 7 or Windows 7, if possible.  Older still works.  Recent Linux or Mac OS X otherwise.  Performance on iOS is worse.

For most tablets, it will come down to:
 * Ghz: more is better
 * OS: Android 7 or higher

Most other specs will be okay for most devices.  A lot of popular devices have lower Ghz, and there were NEW tablets released in 2017 that only run Android 5.  These devices probably aren't best for PPSSPP.

-[Unknown]

**Comment by Kovaelin** [comment]
Thanks for the breakdown!

**Comment by LilianaStrixyBerry** [comment]
-cpu = 8 core @2.0GHz
-gpu = 450 mp4 (4 core) @750MHz (limit driver console opengl 2.0)
-os = android kitkat 4.4.1
-ram = 1gb

Can it run ppsspp on kitkat? Opengl 2.0? Ram 1gb?

**Comment by unknownbrackets** [comment]
Yes, it can run.  That GPU is known to have problems that cause graphical glitches, though.  Will probably also require frameskip.

-[Unknown]
