### ISSUE TITLE
Ridge racer 2 vulkan problem? Partially white reflections

### ISSUE THREAD

**Issue by Mancuser** [hrydgard/ppsspp#10573]
What happens?

When using the vulkan backend some cars (not all) sporadically flash bright white when using buffered effects.  This problem is the same on both the Windows builds (stable and latest builds) and android. The problem does not happen when using opengl on Windows.  Here is a short video 

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

My desktop is running Windows 10 i7 4760 and nvidea gtx970 and my android device is galaxy s8+ (uk Exynos)

**Comment by Mancuser** [comment]
https://drive.google.com/file/d/1mpRwXyR0mu5r3loY18NWAbs5mFT9d7vA/view?usp=drivesdk

**Comment by hrydgard** [comment]
Yeah that looks odd... interesting.

**Comment by Mancuser** [comment]
I think it might be cars that have white as a basis colour.  Not sure, ill check after this game of rocket league.

**Comment by Mancuser** [comment]
Actually, I can expand on my first post, this problem  only occurs when the view is from in the car.

**Comment by unknownbrackets** [comment]
Just to confirm - this happens even when vertex cache and lazy texture caching are off, right?

About how often would you say it happens?  For example, once every 10 seconds?

-[Unknown]

**Comment by Mancuser** [comment]
This definately happens with vertex cache and lazy texture caching off or on.  And it is definately certain cars not a 10 second issue.  I will get another video showing this.

**Comment by Mancuser** [comment]
https://drive.google.com/file/d/1MvkUUtQy3tPFmCa46jQPsblzcxkF9IuW/view?usp=drivesdk

**Comment by unknownbrackets** [comment]
Okay, I've reproduced it.  Interestingly, a dump does not replicate the issue.... so it's probably a flushing problem.

-[Unknown]

**Comment by hrydgard** [comment]
Dug into this with RenderDoc. The issue is that the first render pass, which should draw a texture looking like this (in GL, upside down due to coord system):

![ridge_good](https://user-images.githubusercontent.com/130929/66721905-d8bda600-ee07-11e9-9518-7641bc29883e.PNG)

Instead fails to draw anything most of the time, resulting in an overbrightened ring due to feedback:

![ridge_bad](https://user-images.githubusercontent.com/130929/66721907-db200000-ee07-11e9-8e8c-49eae3504fdc.PNG)

This ring is what's visible as white on the cars.

I can't figure out even in RenderDoc why that first renderpass simply fails drawing stuff. It looks in RenderDoc visualizations like all three of the depth, stencil and cull fail, but they really shouldn't.

**Comment by hrydgard** [comment]
Happens with DX11 too.

**Comment by unknownbrackets** [comment]
Here's a dump of the issue: [ULUS10001_#10573_ridge_racer_reflektion.zip](https://github.com/hrydgard/ppsspp/files/4003758/ULUS10001_.10573_ridge_racer_reflektion.zip)

The texture/render target in question is 0x041fe000.  In this dump, draws 2-104 draw to that framebuffer.

To start, it does a 512x272 clear of depth (despite bufw=64 and scissor = 63,63).  Draw 103 is the white circle.  The first time, things go correctly, but then it builds up since the earlier draws indeed... don't draw.

I tried to clear and disable all the caches (state cache, cleared texture/depal each frame, cleared shader caches each draw, etc.) but it still becomes more white.

-[Unknown]

**Comment by hrydgard** [comment]
So this turns out to be another reformat thing, it seems... "Fixed" by #12882 .
