### ISSUE TITLE
PPSSPP1.5.4 Stop Running

### ISSUE THREAD

**Issue by mpamxl** [hrydgard/ppsspp#10598]
Press the home button while running the game, and return again to stop running.

**Comment by mpamxl** [comment]
Starting from version 1.5.4-387

**Comment by unknownbrackets** [comment]
Does this happen with Vulkan?  Or only with OpenGL?

Presumably on Android, right?

-[Unknown]

**Comment by mpamxl** [comment]
Yea. My Android version is 5.1.
So only have OpenGL.

**Comment by mpamxl** [comment]
Please help fix this bug, the new version is very smooth, so cool.

**Comment by mpamxl** [comment]
1.5.4-555 Open black screen

**Comment by unknownbrackets** [comment]
We've made a lot of changes to OpenGL handling, has anything improved in 1.6.0 or the latest git build?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
