### ISSUE TITLE
Kingdom hearts vulkan crash 

### ISSUE THREAD

**Issue by Blacob777** [hrydgard/ppsspp#10592]
Opengl working 
![screenshot_2018-02-08-02-36-41-064_com miui bugreport](https://user-images.githubusercontent.com/29165096/35934710-4478b64a-0c79-11e8-88a3-30f268c8d11b.png)

**Comment by hrydgard** [comment]
Does it happen immediately or after a while?

**Comment by Blacob777** [comment]
First menu after start, press "okay" freeze and crash

**Comment by marosis** [comment]
Can i ask what application are you using for showing crashes?

**Comment by Blacob777** [comment]
This is Xiaomi phones specific option

**Comment by unknownbrackets** [comment]
VK_ERROR_INITIALIZATION_FAILED, which can mean any of a lot of things, unfortunately...

-[Unknown]

**Comment by zminhquanz** [comment]
Yes , it was crashed on my Galaxy S7 using Qualcomm Snapdragon 820 , Adreno 530 too

**Comment by zminhquanz** [comment]
But on my PC using NVIDIA it wasn't crashed , i think about driver quality

**Comment by zminhquanz** [comment]
@Blacob777 on 1.6.3 latest , it's work on Vulkan correctly , i think you can check this again and close this issue

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
