### ISSUE TITLE
ppsspp new version 1.5.4 555  post proc and perf issues

### ISSUE THREAD

**Issue by kokoalpha** [hrydgard/ppsspp#10607]
It's crashing again probably because of 

I'm testing it with god of war ghost of Sparta

the last fix GLES

huge fps drop 

freezing like 2 seconds every 10 min 

I'm using note edge with opengl and Android 5.1.1 but before I was enjoying the gaming performance even at like 30 to 35 fps but the game play was smooth almost no lagg no stuttering everything was ok the 1.5.4 555 has a serious performance issue 

Oh another problem is that when I'm using costume shader's it doesn't apply directly like the older versions to apply the costume shader's I must apply it first and then exit the game and going to settings again and apply it and start the game 

What *should* happen?

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

**Comment by unknownbrackets** [comment]
Since what version?  Be specific about version numbers before and after.

Performance doesn't seem worse on a Google Pixel with the very latest changes, at least.

-[Unknown]

**Comment by hrydgard** [comment]
Broke out the post processing ("costume shader"?) issue: #10609

**Comment by hrydgard** [comment]
Alright, try now. (560 or later)

**Comment by kokoalpha** [comment]
thank you sir now its perfectly working 
how can I send you a video because there's some minor problems like texture problems I wanted to show you
anyway I've noticed something weird 
when I receive a notification from YouTube a video notification the fps massively increase and then decrease what does this means and again great job sir

**Comment by kokoalpha** [comment]
sorry sir but is there a possibility to increase fps even further on opengl 
thank you sorry again

**Comment by unknownbrackets** [comment]
We're always trying to improve performance.  Are there any more graphic issues here?

The notification may be caused by device throttling.  This is one of those strange, paradoxical things about mobile devices.  Basically, device makers had these options:

1. Run apps like PPSSPP at MAX SPEED ALL THE TIME, and have a battery life of 30 minutes.
2. Run apps only as fast as they absolutely NEED to be, and have hours or days of battery life.

Some device makers picked option 1, but no one bought their phones because crappy battery life sucks, so those companies or divisions received Darwin Awards and everyone left was choosing option 2.  Now they had a new choice:

1. Ask apps how fast they want to run.
2. Decide on the operating system level how fast the apps ought to run.

Some device makers again picked option 1.  Unfortunately, app makers all wanted their apps (and only theirs, not other loser apps made by other people) to be FAST, so it became the same as option 1 the other time around (since every app said it wanted MAX SPEED), and no one bought those phones.  A new round of Darwin Awards, and all the phone makers left had chosen option 2.

And that's where we are now.  Phone makers call the shots and "figure out" what speed your phone should be when running PPSSPP.

When you run an app for a while, it decides it needs to maximize battery life and gives that app the slow mode dunce cap.  When a new app pops up and wants its 5 seconds of glory, that app gets MAX SPEED.  Those are just the rules on Android - PPSSPP has no say in the matter.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, I don't think there's much we can do there, though it's quite annoying that such issues still persist.
