### ISSUE TITLE
Simulate block transfer effect

### ISSUE THREAD

**Issue by GuilhermeGS2** [hrydgard/ppsspp#10628]
Can someone explain me what the "Simulate block transfer effect" option does? The only effect I noticed when it is enabled is a considerable performance decrease on most games on my phone. If this option is needed only for some especific games I think it should be disabled by default.

**Comment by zminhquanz** [comment]
@GuilhermeGS2 Some game if you doesn't enable , it's incorrect some graphic scene . For example : Ys Seven when you disable this , it's incorrect where you stand in the map , or Grand Knight History , it's blackboxes on characters and flickering texture
![image](https://user-images.githubusercontent.com/11285640/36362378-a7ba471e-1566-11e8-89db-7926f550a21d.png)

**Comment by unknownbrackets** [comment]
Unfortunately, it's not some straight-forward thing like higher render resolution.

It's a tool games use.  Some games use it, but wastefully - it was faster on a PSP than it is on modern devices.  But some games use it for important reasons - usually it just effects graphics, but sometimes it can effect gameplay.

When it was implemented, it made a lot of games playable, work better, or render certain scenes properly.  I don't think it should be off by default just because a few games misiuse the feature.

-[Unknown]

**Comment by marosis** [comment]
GuilhermeGS2 more important Is compatibility than performance. Performance Is last think what you need. Firstly, game must be playable.

**Comment by GuilhermeGS2** [comment]
Fine then. Naruto Ultimate Ninja Impact runs with 2x performance with this option disabled, some other games I get 5-10 FPS more. Anyway, thanks for explanation! :)

**Comment by kurayami6** [comment]
I never got good performance in Daxter, even with all the OpenGL optimizations. When I turned off Simulate block transfer effect, the game suddenly ran at full speed.

**Comment by marosis** [comment]
Some games need it for fix glitches, some games are bad with this, but how i told-game must be playable and turn on or turn off this can everybody

**Comment by GuilhermeGS2** [comment]
Many games I had FPS drop when tried to play 2x Resolution, with this option disabled I can play with same speed as 1x Resolution or closer, this option forces a GPU bottleneck, should not be an issue for mid/high-end mobile GPUs.

**Comment by marosis** [comment]
Some games are ok with 2x PSP resolution, but if you playing god of war where is a lot of effects of flame or smoke it Is very good to use 1xPSP.

**Comment by hrydgard** [comment]
It might be interesting to investigate games that get a performance hit when this is enabled but work just as well with the option disabled - that could indicate that we are missing some optimization (but sometimes unavoidable I'm sure). If this turns out to be common we could make a game specific option that turns it off for games where it has a purely bad impact, but feels a bit iffy to do that.

**Comment by Emulatorer** [comment]
Block Transfer Effect is now fast thanks to #11528

**Comment by hrydgard** [comment]
Well, it hasn't been enabled yet in all games that can benefit.
