### ISSUE TITLE
Can't use DirectX11 in WIN7 X64

### ISSUE THREAD

**Issue by leoxxx** [hrydgard/ppsspp#10651]
Select DirectX11.
PPSSPP crash after restarting.And I don't start it.
So I edit ppsspp.ini.

> GraphicsBackend = 2

I edit it to 0 (It's not 2 that PPSSPP is fine.).

CPU:I5 3470
GPU:HIS 7850 1G
DRIVER:Adrenalin 18.2.1
OS:WIN7 X64

**Comment by LunaMoo** [comment]
On Windows 7 for d3d11 to work, you need to place d3dcompiler_47.dll into ppsspp folder(where the exe is), you can find it https://github.com/hrydgard/minidx9/tree/7751cf73f5c06f1be21f5f31c3e2d9a7bacd3a93/8.1/Redist/D3D or installed with windows SDK, there are no redistributable installers for files like that, since they are included in windows 10(as well as 8.1) and MS doesn't care about supporting outdated operating systems.
 Those files should also be shipped with ppsspp installation, but they will not be included in automated builds which you might be using.

**Comment by unknownbrackets** [comment]
Did that help?  If not, do older versions of PPSSPP work?

-[Unknown]

**Comment by leoxxx** [comment]
@unknownbrackets
I have given up.
My network is too bad lately.I  can't download these dll files.
But thank you all the same.
BTW.Can these dll files be packaged in exe in last version?

**Comment by hrydgard** [comment]
If you download PPSSPP from the official site, it should be included in the zip or installer. It's just not included in the buildbot builds.

**Comment by leoxxx** [comment]
@hrydgard 
http://www.ppsspp.org/files/1_5_4/ppsspp_win.zip
It crash also with these dll files.

**Comment by unknownbrackets** [comment]
Does this still happen even with updated drivers?

-[Unknown]

**Comment by leoxxx** [comment]
@unknownbrackets 
Yes.
1.6.2 doesn't work with this mode in WIN7 X64. I think it must work in WIN8 or later.
I give up. THX.
Please close.

**Comment by unknownbrackets** [comment]
Sorry that you've given up.  I'm using Windows 7, 64-bit, but I have an NVIDIA card.  Direct3D 11 works fine here - I've never actually tried the Direct3D 11 backend of PPSSPP on Windows 8 or newer.

I can only imagine it's a driver issue, then.

-[Unknown]

**Comment by leoxxx** [comment]
I have solved it.
It's need install KB2670838.

**Comment by hrydgard** [comment]
Huh, strange. Should probably investigate at some point, but not sure if it's possible to replicate the setup (install Win7 without updates...)

**Comment by leoxxx** [comment]
https://walbourn.github.io/directx-11-1-and-windows-7/
It's a DirectX 11.1 issue.
