### ISSUE TITLE
Black screen in Midnight Club games

### ISSUE THREAD

**Issue by oli0371** [hrydgard/ppsspp#10681]
With midnight club 2 and 3 game screen stay black.

S7 edge exynos
Mali t880-mp12
Gpu driver r22p0
Oreo 8.0 samsung experience 8.0 beta

**Comment by unknownbrackets** [comment]
Is this a recent problem or has it always happened with old versions of PPSSPP?

OpenGL or Android?

-[Unknown]

**Comment by oli0371** [comment]
Recent maybe because i use new gpu driver.

Android version - oreo with samsung experience 9.0
Open gl es 3.2 v1.r22p0
Gpu renderer mali t880-mp12

Issue happen only with vulkan api
Ppsspp version v1.5.4 build 623

**Comment by fahadfoyjur** [comment]
My device android 4.2.2 new build blackscreen 😥😥😥

**Comment by unknownbrackets** [comment]
Was this fixed, or did you close it because you it's not fixed yet?

There isn't a lot of info to go on here (and I personally don't have the game in question, iirc), but if it's still happening it should probably stay open.

Remember - PPSSPP is open source.  PPSSPP gets better the more people contribute.  You could be that amazing person who solves this problem for everyone... or it might just have to wait for the Hero to come along and slay it.  But pretending the bosses aren't there isn't a way to win the game.

-[Unknown]
