### ISSUE TITLE
Touch controls don't become inverted when you select Inverted Landscape layout

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10709]
What happens?
*Title*

What *should* happen?
The touch controls should also become inverted.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Android 7.0

**Comment by hrydgard** [comment]
Hm. We have two ways to rotate the screen. First, the landscape/portrait thing, which lets you reverse the entire screen including controls. If you instead want to just invert the emulator display without inverting the controls, we have a different setting here:  Settings/Graphics/Display Layout Editor, the top dropdown.

**Comment by leopard20** [comment]
That's the problem. The controls should be inverted too. I mean, what sense is there in inverting the display but not controls?!
Here's a screenshot:
![screenshot_2018-03-15-00-08-55-049_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/37430213-b3d37d80-27e6-11e8-9a6f-81245e3008d8.png)

**Comment by hrydgard** [comment]
Oh, you were using that. Well, display rotation is mostly for "vertical" games like Star Solder when you rotate 90 degrees, just added 180 degrees too because it was easy :) 

You want to use the Settings/System/Screen Rotation setting instead.

I do admit that the existance of two settings like this in different parts of the emu is confusing :)

**Comment by leopard20** [comment]
Oh! Thanks for clearing it up! I close this issue then.

BTW a Landscape Auto would be a really nice addition (I'v already opened a feature request for that)
