### ISSUE TITLE
Alien vs predator requiem tharmal vision glitch 

### ISSUE THREAD

**Issue by fahadfoyjur** [hrydgard/ppsspp#10702]
I am enable the tharmal vision and alien version on alien vs predator , but not worked . white screen glitch . plz reply . (sorry for my bad english ) 

What *should* happen?

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

**Comment by unknownbrackets** [comment]
What device?  What version of PPSSPP?  What is supposed to happen and what does it look like exactly?

Are you using OpenGL, Vulkan, ...?  Check your settings, it may work in some graphics backends and not others.

-[Unknown]

**Comment by fahadfoyjur** [comment]
I am using Ppsspp version 1.5.4 , 
Trying very settings but still tharmal vision glitch . darkest area i cannot see anything.  Sorry for my bad english 😥😥😥
My device cannot support vulkan.  
Only open gl

**Comment by unknownbrackets** [comment]
Could you try exporting a GE frame dump?  These help a lot.  Make sure you're using a recent git build.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by Emulatorer** [comment]
What kind of graphics glitches?
Because I didn't see anything wrong 🤔
![Screenshot_2019-08-14-21-09-42](https://user-images.githubusercontent.com/37603562/63023705-3309bb80-bed8-11e9-9100-626a94410b08.png)
![Screenshot_2019-08-14-21-09-17](https://user-images.githubusercontent.com/37603562/63023729-3d2bba00-bed8-11e9-974d-17f28f9e4574.png)
![Screenshot_2019-08-14-21-09-33](https://user-images.githubusercontent.com/37603562/63023756-4b79d600-bed8-11e9-8e51-c6612eacf58f.png)
![Screenshot_2019-08-14-21-09-29](https://user-images.githubusercontent.com/37603562/63023771-559bd480-bed8-11e9-8ea1-01d1c1e1e99d.png)
![Screenshot_2019-08-14-21-09-26](https://user-images.githubusercontent.com/37603562/63023787-5fbdd300-bed8-11e9-8a9e-6187778afbc5.png)
ppsspp v1.8.0-500 build
mali-450 gpu
android lollipop

**Comment by hrydgard** [comment]
Seems either we fixed the bug, or it's something specific to the reporter's device. 

I'm gonna close, reopen if you still see this.
