### ISSUE TITLE
Rendering backend other then Vulkan crashes with any shader active.

### ISSUE THREAD

**Issue by mlwj1993** [hrydgard/ppsspp#10748]
What happens?
When using any shader (default or custom one) PPSSPP crashes when not using the Vulkan backend.

What *should* happen?
Shader should function normally.

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Windows 10 Home 64 bits (10.0, build 16299).

Intel core i7-6700HQ @2.60 GHz (8 CPU's)
Intel HD Graphics 530
Nvidia Geforce GTX960M (Geforce game ready driver 391.01)

Using PPSSPP version: 1.5.4-719-g24b9fb6ea

**Comment by unknownbrackets** [comment]
TranslateShader() is crashing.

-[Unknown]

**Comment by unknownbrackets** [comment]
Hm, it seems like an API change for glslang (#10728.)

As a hack, setting `spirv[1] = 0x10000;` works, but if I call `shader.setEnvTarget(glslang::EShTargetNone, glslang::EShTargetSpv_1_0);` it fails because there's no location directive in the shader src. Seems like setting the target enables SPV rules.

Always calling `ConvertToVulkanGLSL` (with some tweaks to avoid push constants) works, but I'm not sure if that might be short-sighted for some reason - @hrydgard?

-[Unknown]

**Comment by hrydgard** [comment]
Oops. Thanks @unknownbrackets , I'll take a look.
