### ISSUE TITLE
black loading on starting game.

### ISSUE THREAD

**Issue by Rokkest** [hrydgard/ppsspp#10770]
its just boried on new build update,
on my best setting always black waiting on first start loading my hh x86 but its fine on another hh[arm] :

Version: 0.54
Language: en
layout:     
Mode: 1
App: com.opera.mini.native
Android: 4.4.2
Model: ASUS_Z007
Manufacturer: asus
ID: KVT49L

clear system folder fix this but when try to create config and setting grap/control start going black
sample system.ini
http://upfile.mobi/EwoanKFgaxv
http://addfile.org/bXlKNxPskkP

**Comment by Michal1324** [comment]
@Rokkest Please next time upload logs here on Github because those sites looks like they contain malware some sort of

**Comment by unknownbrackets** [comment]
I'm closing this because it has met three criteria for spam:
 * Mentions another app (Opera Mini) as a significant portion of the report.
 * Links to malware.
 * Description describes PPSSPP inaccurately.

If this is a legitimate issue report, I apologize.  Please provide any ini files via https://gist.github.com/ or upload via zip, and carefully describe the specific behavior that's a problem and when it changed.  This issue will be reopened if you provide a usable issue report.

-[Unknown]
