### ISSUE TITLE
Hammerin' Hero Texture Problem (invisible characters?)

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#10777]
I Have a Bug while playing a game 

There's is no Character Textures and boxes except Gen's hair and backgrounds

**Comment by Panderner** [comment]
![screenshot_2018-03-25-09-00-52](https://user-images.githubusercontent.com/37503397/37870533-0fdcc9de-300b-11e8-896c-2c30b648dbc3.png)

**Comment by weihuoya** [comment]
disable slower effects may cause this issue, I met in other game.

**Comment by Panderner** [comment]
No the textures are not fixed

**Comment by Panderner** [comment]
![screenshot_2018-03-25-20-07-43](https://user-images.githubusercontent.com/37503397/37874807-d700a3f2-3068-11e8-8d03-5e4389920772.png)

**Comment by hrydgard** [comment]
Please, I asked you which device you have this problem on. It's important.

**Comment by Panderner** [comment]
Opengl es 2.0

**Comment by Emulatorer** [comment]
I think this game required OpenGL 3.0+ phone like Jean D'Arc
I tried latest gitbuild enable/disable the option in jit debug tools nothing change
### Screenshots
![Screenshot_2019-06-14-17-44-47](https://user-images.githubusercontent.com/37603562/59501232-ad649200-8ecd-11e9-91db-d1f1884ddd47.png)
![Screenshot_2019-06-14-17-46-12](https://user-images.githubusercontent.com/37603562/59501255-b8b7bd80-8ecd-11e9-8aeb-d2de9ed0fa35.png)
![Screenshot_2019-06-14-17-48-22](https://user-images.githubusercontent.com/37603562/59501286-c705d980-8ecd-11e9-85f9-9450f298f8bc.png)

**Comment by unknownbrackets** [comment]
If you can upload a GE dump, probably could verify that.

-[Unknown]

**Comment by Emulatorer** [comment]
@unknownbrackets I cant get GE dump using the latest gitbuild
![Screenshot_2019-06-15-14-31-25](https://user-images.githubusercontent.com/37603562/59547970-71d3d180-8f7a-11e9-8fdc-08aa0b3b8e5e.png)

**Comment by Emulatorer** [comment]
### Screenshots
![Screenshot_20190615-155619](https://user-images.githubusercontent.com/37603562/59548839-2e339480-8f87-11e9-8472-de84c8cd1754.png)
![Screenshot_20190615-155639](https://user-images.githubusercontent.com/37603562/59548844-3986c000-8f87-11e9-86a2-896f2f2a307e.png)
![Screenshot_20190615-155706](https://user-images.githubusercontent.com/37603562/59548846-42779180-8f87-11e9-92fc-90dd7d1e318b.png)
### Phone Specifications
Snapdragon 430 Adreno 506
1.4GHz Octacore Proccesesor
PPSSPP v1.8.0-291 gitbuild default settings

**Comment by unknownbrackets** [comment]
Hm.  It's possible that the phone is pausing PPSSPP when you switch to the browser due to RAM constraints - if possible, it'd be good to try it with PPSSPP still running, connecting to the debugger from a PC on the same wifi network.

-[Unknown]

**Comment by Emulatorer** [comment]
@unknownbrackets I finnally solve the problem in my chrome I disable the lite mode in the settings 🤣
Here's the GE Dump 
[Download.zip](https://github.com/hrydgard/ppsspp/files/3293696/Download.zip)

**Comment by Emulatorer** [comment]
Any update about this?

**Comment by unknownbrackets** [comment]
Even if I disable the depth thing (that Jeanne d'Arc uses), it still draws mostly fine.  The hat shadow is just wrong.

It draws in two passes from a framebuffer-as-texture.  First pass draws a blurry shadow using lighting (it does this in several scissored draws that seems annoyingly inefficient for modern rendering...)  At 1259/1608, it switches to regular lighting and draws the actual character.

Since neither part shows up, I guess it's either failing to use a framebuffer as a texture at all, or else the original framebuffer (0x000cc000) is not being populated properly.  It starts drawing characters at about 595/1608 and it takes until 1098/1608.  The main character starts around 847/1608 (hammer), the others appear to be offscreen.

In this part, it uses dual source blending, but even when I disable dual source blending, it draws fine.  Maybe it's an issue with some hack (like Chainfire3D) lying and saying that framebuffer fetch is supported...

-[Unknown]

**Comment by Emulatorer** [comment]
PPSSPP-v1.8.0-342-g44685a731-android
![Screenshot_2019-06-24-13-47-19](https://user-images.githubusercontent.com/37603562/59994585-f8796480-9686-11e9-9bc2-64417d63482c.png)
![Screenshot_2019-06-24-13-47-32](https://user-images.githubusercontent.com/37603562/59994592-0202cc80-9687-11e9-9f4c-35ffc4d752bb.png)

**Comment by unknownbrackets** [comment]
Yeah, that commit wasn't expected to fix this...

In this screenshot, I see a faint outline though, that's interesting.  I also see the other person.  Hmm.  Does it show anything with framebuffer_fetch in the GL extensions tab of system information?

-[Unknown]

**Comment by Emulatorer** [comment]
@unknownbrackets here's my OGL & EGL extension bsytem information
![Screenshot_2019-06-24-16-51-29](https://user-images.githubusercontent.com/37603562/60005187-962d5d80-96a0-11e9-8bf6-fc4b7b40ef9f.png)
![Screenshot_2019-06-24-16-51-35](https://user-images.githubusercontent.com/37603562/60005202-9ded0200-96a0-11e9-85c7-0c548aa04bc4.png)
![Screenshot_2019-06-24-16-51-39](https://user-images.githubusercontent.com/37603562/60005223-a6453d00-96a0-11e9-9f1a-68964a69f50d.png)

**Comment by unknownbrackets** [comment]
It initially clears the color/alpha/stencil without touching depth.

This isn't being replicated 100% accurately by the dump, because the framebuffer probably already has depth data in it.  If you were to cause framebuffers to be recreated (for example by putting your phone to sleep and then unlocking it), the characters would probably show.

If so, it is in fact related to the GLES3 depth problem, same as Jeanne d'Arc.

We probably should make frame dumps include starting depth data, which I think is now mostly doable with the shader download path.  Then this would've reproduced with less effort - but, my bad for not noticing before.

-[Unknown]

**Comment by Panderner** [comment]
No problem when I'm using realme C2 
![Screenshot_2019-08-25-10-03-30-95_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/63644630-e1570180-c71f-11e9-914e-b89e61136fc2.png)

**Comment by Emulatorer** [comment]
@Panderner because your phone is OGL 3.1+ supported unlike my phone is OGL 2.0 only :/

**Comment by Panderner** [comment]
Yeah it only happened for opengl es 2.0 devices

**Comment by hrydgard** [comment]
In that case, I don't think there's much we can or want to do here. It'll just work on newer devices, it's unfortunate that some OpenGL devices don't support the depth buffer copy operation that we need.
