### ISSUE TITLE
Medal of honor Heroes 2 crashing after mission

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#10795]
What happens?
after first mission game crashing when loading statistics what you did and what not
MoH Heroes 1 is fine

What *should* happen?

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Android 6.0 OpenGL Lenovo K10A40. Used default settings. CPU clocks=Auto

**Comment by unknownbrackets** [comment]
Does it also crash on PC, or does it only crash on Android?

I know older versions had major graphics issues, but if you're able to make it through a mission even with broken graphics, it'd be helpful to know if old versions crashed too.

Also, are you able to post an adb logcat of the crash?

-[Unknown]

**Comment by LunaMoo** [comment]
Can't reproduce the crash on windows, however if that device supports Vulkan I suspect it would just stop responding, since the post mission stats are extremely heavy when using Vulkan backend, even my desktop with haswell is being maxed out around 17% speed (11/60fps) in that particular screen, other backends are fine.
 Might have something to do with backgrounds of menus in this game being videos, example even from different, less laggy menu is showing pretty extreme difference:
Vulkan 77 fps (not a typo, it's just soo slow:P)
OGL 600 fps
D3D11 595 fps

 Dump is showing different graphics and doesn't show much difference in performance between different backends so might not be worth looking at.

**Comment by unknownbrackets** [comment]
Hmm, interesting.  Can you try using VerySleepy (you can use [this one with support for PPSSPP's jit](https://github.com/unknownbrackets/verysleepy/releases/tag/v0.90-pre-jit) or just the standard one) or another profiler to see where it's spending all its time during any of those?

-[Unknown]

**Comment by LunaMoo** [comment]
Not sure if that's the result I should be looking at, but I launched PPSSPP from that Very Sleepy, then ran the game and loaded a savestate from heavy menu, then just waited for a while before breaking:
 ![very sleepy](https://user-images.githubusercontent.com/5485237/38469113-f414918c-3b4f-11e8-89d0-ec7a14324bf4.png)

**Comment by unknownbrackets** [comment]
92% exclusive in SfmDxSetSwapChainStats?  I'm not sure what that is, but unless it's a profiler bug I guess this is the driver doing draw calls.

Do debug statistics show a lot of draw calls or anything?

-[Unknown]

**Comment by LunaMoo** [comment]
Not much draw calls there:
![ulus10310_00020](https://user-images.githubusercontent.com/5485237/38469335-6d97920e-3b53-11e8-98ac-45571201bcc2.jpg)

Here's also PPSSPP frame profiler with values printed
![ulus10310_00017](https://user-images.githubusercontent.com/5485237/38469349-9d738208-3b53-11e8-87a2-ec4190193003.jpg)

**Comment by hrydgard** [comment]
Bizarre. Your profile is a bit odd though as there's so much window managment stuff and so little PPSSPP - did you capture all threads?

**Comment by LunaMoo** [comment]
Profile of a frame dump:
![ulus01457_00000](https://user-images.githubusercontent.com/5485237/38469565-1c695e18-3b57-11e8-847c-b527d03c0eb9.jpg)
And the dump itself:
[ULUS10310_0005.zip](https://github.com/hrydgard/ppsspp/files/1887638/ULUS10310_0005.zip)
but as mentioned dump doesn't suffer from the problem.

I didn't changed any code with the frame profile, just added a secondary way of showing the results and the screenshot has both.

**Comment by LunaMoo** [comment]
There's very little happening when stepping through prims, but definitely the background which is a big full screen texture is changing a lot/every frame since it's a video. One thing which might or might not be odd is that after it draws the video frame, it does a bunch of DRAW PRIM LINES, DRAW PRIM POINTS and
DRAW PRIM TRIANGLE STRIP all without texture before continuing to draw on top of the video.

**Comment by LunaMoo** [comment]
Don't have anything with vulkan right now so can't test properly. But as I mentioned above, the dump does not suffer from performance problems. It also doesn't show the actual menu, but after drawing it, it covers everything with some frame from before(as can be seen above a scope view instead of menu).

 Those menus are nothing special for other backends so if DXT5 is a problem, it might as well be a problem with vulkan drivers, potentially limited to some devices.

**Comment by unknownbrackets** [comment]
Actually, DXT5 reads back each block to put in the alpha values.  This might be torture for uncached read memory.

-[Unknown]

**Comment by unknownbrackets** [comment]
Yeah, that's exactly it.  Making it re-decode the texture every frame murders performance on Vulkan.  Fix incoming.

-[Unknown]

**Comment by unknownbrackets** [comment]
Oh, okay, I was hoping the crash was just a hang.  Are you able to get an adb logcat?

If not, it'd help if you or anyone you know could try it on other hardware to figure out if it only crashes on certain devices.

-[Unknown]

**Comment by marosis** [comment]
How i can get log from the emulator, when i'm on android

**Comment by marosis** [comment]
Tested on my new device. OpenGL And Vulkan no crashes

**Comment by Gamemulatorer** [comment]
This is not crashing anymore @marosis ?
I tried this game so far so smooth and no crash after the 1st mission.
![Screenshot_2021-08-09-23-59-28-613_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/128737308-c3389987-9a37-4083-8f12-18262a7bc7c1.jpg)

Redmi Note 9
Android 11 MiUI 12.5.1
ppsspp latest build for android

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

There were some fixes to DXT decoding in the recent builds, so this may have been fixed.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
