### ISSUE TITLE
PostShader didn't work in UWP

### ISSUE THREAD

**Issue by Slippy2k** [hrydgard/ppsspp#10812]
What happens?
I have selected grayscale and post processing shader but the games start in color

What *should* happen?
post processing shader should work under UWP in games

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Windows 10 UWP App

**Comment by TehPlayer14** [comment]
Isn't UWP version wip at the moment?

**Comment by dominater01** [comment]
it might be because the shaders folder wasnt included in the uwp build

**Comment by unknownbrackets** [comment]
Does this still not work, if you have the shader files themselves?  Do the shaders not show in the list, or do they show and not work?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
