### ISSUE TITLE
[Android] Why Digimon Adventure is so lag in OpenGL?

### ISSUE THREAD

**Issue by Jinzombie** [hrydgard/ppsspp#10842]
What happens? Digimon Adventure is so lag in OpenGL Ill tried the latest build but it is still super lag 😢 while other phone that support Vulkan can run this game smooth?

What *should* happen?

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

Mali-450 MP
2GB RAM
Octacore
1.4Ghz

Sorry for my bad english 😅

**Comment by leopard20** [comment]
Your GPU is very weak

**Comment by Jinzombie** [comment]
@Leopard20 I also try it in Mali-T720t (OpenGL) using the latest build but still lag so that's means Digimon Adventure is only playable with Vulkan Support ?

**Comment by unknownbrackets** [comment]
If I remember right, this game does a special effect to draw lines around things.  Old GPUs could do the effect relatively fast, but for new GPUs it's the "bad way" to add outlines to things.  Because of this, it's kinda slow on modern GPUs because they're no longer optimized for it.

You can try disabling "Simulate block transfers" or use "Disable slow framebuffer effects".  They might make other graphics in the game worse too, but they should disable that effect I think (I don't actually have the game, though.)

-[Unknown]

**Comment by leopard20** [comment]
🖕@Jinzombie 🖕 Fuck you asshole

**Comment by Jinzombie** [comment]
@leopard20 what's your problem???

@Unknownbrackets you can download and try this game its full english patch
https://drive.google.com/uc?id=1e18gc2n6lpjS6RpTOmKj1ATkO4LZs4LI

**Comment by leopard20** [comment]
@Jinzombie 
What is YOUR problem, kissass?

**Comment by unknownbrackets** [comment]
Sorry, no piracy please.

-[Unknown]

**Comment by Jinzombie** [comment]
@Unknownbrackets Sorry 😅

**Comment by hrydgard** [comment]
Don't think there's much we can do about this, so I'm closing.
