### ISSUE TITLE
Stuttering when loading replacement textures?

### ISSUE THREAD

**Issue by GorrillaRibs** [hrydgard/ppsspp#10894]
On my GPD Win (A tiny computer w/ an Atom z8750 and 4GB RAM), when trying to play persona 3 portable with an HD texture mod from [here](https://forums.ppsspp.org/showthread.php?tid=23509), the HD textures load (wonderfully!) but, every time a new (external) texture is loaded, there's a fair bit of stuttering (i.e when pausing for the first time in a new area, first time a dialog box shows up, first time the battle ui is loaded), but then it runs smoothly until a transition between areas/scenes (when I guess loaded textures are cleared?). Without the external textures, it runs silky smooth with no stuttering/lag I could notice, and the speed indicator didn't show otherwise. I suspected this was an issue with my lower ammount of RAM/VRAM (neither of which get close to max usage when playing, both hover around ~50%), and I get similar behaviour on my main computer (i7-7700, 16GB RAM, GTX 1070 8GB, Arch Linux), though it's less pronounced (I'm also playing at 5x resolution and textures on this computer, as opposed to 3x on the Win).

I'm trying to diagnose it I just don't have enough RAM/my storage isn't fast enough to handle loading the textures, or if there's some setting I'm missing that could fix the issue. Alternatively, if it would be possible to just keep textures loaded in RAM/wherever they're loaded initially so it only sutters when they're initially loaded. Any help would be appriciated!

Unsure if there's any logs I should post, the issue seems to be present on both the latest stable version (Windows 10) and the lastest git version as of a couple days ago (Linux and windows 10, on linux installed via PPSSPP-qt-git from the AUR)

**Comment by LunaMoo** [comment]
There are at least three potential reasons of stutter when replacing textures:
 - storage speed,
 - png decoding and texture creation,
 - too big size / too many textures.



 First could be worked around pretty easily on pc's by using ram disk already, eventually could be preloaded by PPSSPP before / during launch of the game, the second would require a texture format instead of PNG or overall much faster cpu & gpu, the third would also require a much faster hardware or being more humble with replacement sizes.

 Either way, everything that can be done on PPSSPP side is planned, but not done yet, which is why #4630 is still opened, so I'll just close this as we don't need two issues opened for same reason.
