### ISSUE TITLE
After task switching away and back on Galaxy S3, screen aspect ratio is wrong

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#10916]
As described in title, it's annoying enough that it pretty much has to be fixed before 1.6. Touch is also way off in this case.

**Comment by leopard20** [comment]
Why does it happen only on Galaxy S3? Doesn't it use a standard 16:9 ratio? Other phones with that ratio have no problem.

**Comment by hrydgard** [comment]
It may well happen on many other models, but I found the issue on my S3. No idea why, some platform bug I think which we'll need to work around.

**Comment by unknownbrackets** [comment]
Perhaps a race condition in the handling of the resize events?  Or else just too many too quickly?

I know we saw bugs before.  I wonder if the best thing is to debounce those events, by which I mean:
 * Have a handler that receives each event and uses a delay to send to the actual handler.
 * If the handler receives a new value before the delay is up, don't delete the timer, but update the pending value.

Presumably Android normally does this internally with rotations, at least on recent devices, because there's a delay when I rotate and it doesn't "go through all the steps" if I rotate it quickly.  But maybe older Android versions didn't debounce?

-[Unknown]

**Comment by hrydgard** [comment]
I know the term debounce from digital electronics, don't you worry about that ;) https://hackaday.com/2015/12/09/embed-with-elliot-debounce-your-noisy-buttons-part-i/

Been trying to figure out what the hell is going on but I can't make another conclusion than a platform bug, I tried adding sleeps etc to work around potential races but no dice. Really don't understand what's going on. So I've reintroduced the hack but only for older Android versions that don't support windowing anyway, so that part shouldn't regress...

**Comment by leopard20** [comment]
I got the same issue on OpenGL too. It doesn't happen all the time though.
