### ISSUE TITLE
unable to see the slot and pictures of a save data. ( and also the screen is flickering. )

### ISSUE THREAD

**Issue by sephiroth0396** [hrydgard/ppsspp#10912]
Unable to see the slot when I'm about to save the game. ( happening in Fate/extra, fate/extra CCC, shadow of destiny and some japanese games. ) the same things is happening when I'm about to load the data. 
However, you can see it if you change the rendering mode to buffered rendering and sometimes set frameskip to 1 or 2. 
My device: nexian helios Mi531 kitkat
OpenGL ES, quadcore, mali-400mp, 1.4GHz ( I think.. )

**Comment by hrydgard** [comment]
Huh, that sounds odd. Screenshot?

**Comment by sephiroth0396** [comment]
Here.

**Comment by sephiroth0396** [comment]
https://m.youtube.com/watch?feature=youtu.be&v=mdtVOFgMTN8

**Comment by hrydgard** [comment]
I see, that's indeed strange...

**Comment by sephiroth0396** [comment]
Yeah.. It's happening on the oldest version too.

**Comment by unknownbrackets** [comment]
Seems like there are glitches in how we're detecting draws then.  Maybe we're not always accounting for PPGe draws?  Definitely something going wrong here...

> if you change the rendering mode to buffered rendering

Just to note: this option intentionally nerfs PPSSPP's drawing to make it faster.  It will always have graphics glitches, and most of them we can't fix without actually using buffers when the game wants to use buffers.

-[Unknown]

**Comment by sephiroth0396** [comment]
how about the frameskip thingy? Does it causing glitches as well? Because in those games, sometimes I need to turn frameskip on/off to stop the flickering.

**Comment by RaduNastase** [comment]
I have a pretty similar issue in libretro core. Changing options does not help. I asked in their forums some weeks ago, but no one could help yet.

In games like BlazBlue series, Dbz:shin budokai or Soul Calibur (Guilty Gear xx and Street Fighter Alpha 3 are not affected), when the save/load screen appears at the start of the game, the game either freezes or it doesn't display the save/load graphics and i can not do anyhting but quit the game.

The core is 1.4.2 build. 1.2.2 behaves identically.

**Comment by unknownbrackets** [comment]
So the basic problem here is that drawing to the framebuf is not aligned to vblank period.

1. Vblank / flip occurs.  Disable skip
2. [NOSKIP] PPGe -> framebuf A
3. [NOSKIP] Drawing -> framebuf A
4. Display framebuf A immediate
5. [NOSKIP] Drawing -> framebuf B
6. Vblank / flip occurs.  ENABLE SKIP
7. [SKIP] PPGe -> framebuf B
8. [SKIP] Drawing -> framebuf B
9. Display framebuf B immediate (dirty from before, so displayed)
10. [SKIP] Drawing -> framebuf A

Shadow of Destiny loops like this.  The issue here is that the drawing is half offset from the vsync interval.

I think frameskip would have to account for sceDisplaySetFramebuf (although not only, because some games don't ever call it...) to properly skip.

-[Unknown]

**Comment by Gamemulatorer** [comment]
I cannot reproduce this.
There are many improvement lately about frameskipping this should be closed now.

**Comment by hrydgard** [comment]
Hm, I agree, if there's no repro anymore, let's close.
