### ISSUE TITLE
[Question] About refresh rate option under cheats... 

### ISSUE THREAD

**Issue by leopard20** [hrydgard/ppsspp#10939]
Sorry for asking this here. 
The Refresh Rate under cheats is actually a "rate" right, not an interval? (as in the higher the rate the more the number of refreshes)
If true, can setting the refresh rate too high cause more CPU/battery consumption?
Also,  does it use the conventional unit for rate (cycles per second/Hz)?

**Comment by LunaMoo** [comment]
I'm pretty sure it's not your first time doing that, so instead of writing an anwer I'll tell you to stop being lazy and post support questions on forums or even better search the forums for already existing answers.

 Issue trackers are as the name says for issues, not for personal support, attention and spam discussions. Closing.

**Comment by leopard20** [comment]
🖕
