### ISSUE TITLE
A Couple Small Text Issues in Metal Gear Acid 2

### ISSUE THREAD

**Issue by TideGear** [hrydgard/ppsspp#10943]
Note the garbage text...
![screenshot_20180420-002337_ppsspp](https://user-images.githubusercontent.com/16357059/39042014-b8d7c83a-443e-11e8-8c28-8272de0095ca.jpg)

It might be trying to say the name of this area...
![screenshot_20180420-002309_ppsspp](https://user-images.githubusercontent.com/16357059/39042068-d6aa1980-443e-11e8-9d5b-01dc03fde1e1.jpg)

Also, not that it's a useful feature with PPSSPP, but the Subsistence Link screen (choosable from the game's main menu) has clipped off text...
![screenshot_20180420-014617_ppsspp](https://user-images.githubusercontent.com/16357059/39042215-220ca942-443f-11e8-9dac-a84dcb372349.jpg)

This was with v1.5.4-919-g19ddeea8e on a Galaxy S9+ (USA).

**Comment by hrydgard** [comment]
The first one is probably due to us using a crappy font system for the ingame system dialogs. This has been reported many times and is a very hard one to fix.

The latter is just that you're not using original fonts from the real system (can be installed into assets/flash0/font. Our free replacement fonts are not correctly dimensioned.
