### ISSUE TITLE
opengl versus vulkan

### ISSUE THREAD

**Issue by joelolopez** [hrydgard/ppsspp#10989]
using the previous versions vulkan backend really standup... but now opengl  is more faster than vulkan backend in some games..for example

how did itest the speed?
 in kingdom hearts birth by sleep: 
-keyblade master examination
-fight lots of orb monsters
-use flame salvo - max 15 tragets 

kingdom hearts birth by sleep when i use vulkan in a very busy and crowded place of the game the fps rate is ranging from 69~72 , but when i use opengl fps rate is ranging 99 ~ 100 !!!! omg! haahhaaha

 is it because opengl is improving? there are these cases that i need to switch to opengl instead of vulkan because of its speed improvements..  (im not complaining about the speed xp just little disappointed with vulkan)

is it possible to make vulkan more faster than current opengl? if its possible, maybe  there is a possiblity that silenthill will be playable

### What *should* happen?

OS android 7.0 , Octa-core, 2360 MHz, ARM Cortex-A53, 64-bit, 16 nm , Mali-T830 MP2 , 4 GB RAM

**Comment by hrydgard** [comment]
Yeah, we multithreaded the OpenGL backend too recently so it can make use of two CPU cores. Was a ton of work but apparently worth it :)  It will still usually use up a lot more CPU than Vulkan and thus eat more battery. On Android you can get strange power effects like the OS clocking down the CPU if it's not fully used, which can slow things down. Alternatively, this could just be a case of immature Vulkan drivers.

Anyway, there's a reason we still allow you to choose OpenGL - sometimes it might work better. Plus, there's still further room for optimization of both backends for the future.

**Comment by leopard20** [comment]
@hrydgard 
Told you OpenGL was faster! 😁

**Comment by leopard20** [comment]
I'm still not convinced about Vulkan being better right now (not even in terms of battery)

After I created the issue that was similar to this, I tweaked my kernel a bit to improve performance on Vulkan. It's better than before that's for sure, but still I get occasional frame drops (a lot shorter and better than before)
But no such issue on OpenGL.

Also, regarding CPU consumption, I tested 5 minutes on both backends playing the same game.
Remember I said OpenGL usage was a bit higher back then? Well, after optimizing my kernel they're fairly on the same level now!

I know you want to keep blaming "immature drivers" because you get a good performance on your S8, but let's not forget it has a beast of a CPU. It may be clocked nearly the same as my Snapdragon 821 (2.2GHz little cores, 2.4GHz big cores), but it performs better in terms of GFLOPs (also faster in terms of I/O)

Another strange thing I notcied that might be worth looking into is, Vulkan cache creation loading takes a lot longer than OpenGL (nearly 2-3 times).

**Comment by hrydgard** [comment]
Well, I can definitely believe that OpenGL is faster *on your device*. On most of my machines and devices, Vulkan wins. Don't worry, we're gonna keep both backends, so just use what's faster on your device. I'm a bit confused too as to how OpenGL is beating Vulkan though...

**Comment by marosis** [comment]
Me too

**Comment by LunaMoo** [comment]
Problematic weird cases aside(ie Medal of Honor), I think more devices might suffer from enabling MT in Vulkan aka see increased cpu usage without difference in performance. Maybe we need an option to disable Vulkan MT to test it on more devices.

**Comment by leopard20** [comment]
Here's a quick comparison between Snapdragon 821( having the same API and driver version as mine) and Snapdragon 835 in S8+:
https://vulkan.gpuinfo.org/displayreport.php?id=2136#device
https://vulkan.gpuinfo.org/displayreport.php?id=2830#device

**Comment by hrydgard** [comment]
Closing because this is not really a specific issue. There are many ways left to improve performance in the future...

**Comment by leopard20** [comment]
@hrydgard
Have you made any significant changes since build 971? I don't know why I can get extremely good performance on my phone! No lag or sound issues on Vulkan. Also, my phone doesn't heat up at all (played for 2 hours straight and still cool...hm...as a cucumber?!)
I'm not sure if it's what you did to the emulator or what I did to my phone but everything looks great right now!

**Comment by hrydgard** [comment]
good to hear, but very little that should affect performance has changed since then. maybe you just rebooted :) Are you using "sustained performance mode"?

**Comment by leopard20** [comment]
Rebooting is the technique they used on old Android phones! Don't think it works on today's phones with over 4GB of ram!

No my ROM doesn't support sust perf mode for unknown reasons (it's android 7.0 though)

The only thing I did was raise my phone's thermal throttling limit, which actually should make the phone warmer (I can definitely confirm that in Dolphin!)
 I don't know what's going on here!

**Comment by leopard20** [comment]
@hrydgard Could it have been an I/O issue? I remember turning off an option in Developers Options called "Mock SD Card Optimization". Don't know what it means (not literally) anyway!

**Comment by Jinzombie** [comment]
Also noticed that OpenGL is using more than 2 cores?
![screenshot_2018-05-11-19-09-21](https://user-images.githubusercontent.com/37603562/39921924-42cb46ce-550c-11e8-86ae-69c2c60a3b1c.png)
