### ISSUE TITLE
Nfs Carbon Own The City immediately crashes after winning any race

### ISSUE THREAD

**Issue by Rafidmuhaiminwafi** [hrydgard/ppsspp#10991]
The first four races of prologue were fine. But when I prompted to buy a car, I buy a car and start the story mode. But after winning any races of storyline ppsspp shows this error 'PPSSPP isn't responding'. Also it doesn't count the race I won. So, I can't progress through the game and the game is not playable, it's ingame. Also I can't upload the log because I don't know where the log is located.

**Comment by leopard20** [comment]
Weird. I'm pretty sure I could play the game a few builds back.

What is your PPSSPP version? What is your OS? Which backend are you using?

**Comment by Rafidmuhaiminwafi** [comment]
I'm using the PPSSPP 1.5.4 which I found in the download page. I'm not using the orphis build. My OS is Win 10 Pro 64bit. Here the backend doesn't matter because I have tried using every option I found in the settings. I have tried every backend, rendering mode, frameskip. Even I have tried by mixing them. But nothing changes.

**Comment by marosis** [comment]
So Wait to 1.6.0 a few days

**Comment by Rafidmuhaiminwafi** [comment]
I think it's 1.7.0 not 1.6.0

**Comment by leopard20** [comment]
It is 1.6.0! 

By the way, you're not using frameskip or cheats do you? Don't use either once and let us know if anything changes.

If you want to use frameskip, preferably do it after the EA logo. Or after getting in the menu.

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
