### ISSUE TITLE
Failed to saved settings need to restart/reboot the phone to saved

### ISSUE THREAD

**Issue by Jinzombie** [hrydgard/ppsspp#11020]
Using ppsspp build 1.5.7-971 failed to saved settings.
I need to manually on the permission in phone
settings if not need to restart/reboot the phone

Android 6.0
Mali-T720

**Comment by Jinzombie** [comment]
Even granted the permission ppsspp always say failed to saved
![screenshot_20180508-171414](https://user-images.githubusercontent.com/37603562/39770462-9c636214-52de-11e8-878f-4c1c4fe0c621.png)

**Comment by Jinzombie** [comment]
So I need to manually on the permission in the phone settings
![screenshot_20180508-171456](https://user-images.githubusercontent.com/37603562/39770505-bd623cb0-52de-11e8-91e1-5419d383d33e.png)

**Comment by leopard20** [comment]
So you mean if you uninstall the app and reinstall it, the permission dialog doesn't appear automatically? Or maybe not saving the granted permission?

Have cleared the app data? It can also reset the permissions.

**Comment by hrydgard** [comment]
We do show a button to allow the user to retrigger the question. Or at least I think we do...

**Comment by Jinzombie** [comment]
Here's my screen redorder it show up the button and I allow the permission but always failed to saved settings.
https://youtu.be/nSdbdPAssFQ

**Comment by unknownbrackets** [comment]
So permission was definitely granted then, if it could see the games, right?  I wonder why the setting had to be turned on again?

-[Unknown]

**Comment by Jinzombie** [comment]
If I exit in the ppsspp (remove from recent app) and open it again all of the changes in the settings will back to default.

**Comment by hrydgard** [comment]
That means it has indeed failed to save the config...

**Comment by Jinzombie** [comment]
Yes

**Comment by hrydgard** [comment]
Tried a lot of things but can't get it to misbehave on my S8...

**Comment by Jinzombie** [comment]
Maybe my tablet  has the problem in not the ppsspp? 😟

**Comment by Jinzombie** [comment]
Just downloaded now build 1.5.4-980 and I test it on android 7.1 Mali-400 my friend phone but the issue of saved settings is still happen.

Note:First time to install in his android phone

**Comment by leopard20** [comment]
@hrydgard 
I don't think this has anything to do with storage permission. If the permission was not granted or saved, then you couldn't even display the contents of the memory.

The real issue here is (or at least I think it is) that you're accessing the sdcard from an invalid path, which only grants reading permissions not writing permissions. (generally /storage/emulated/0/) You have to access it via the valid path which is not that easy and varies across devices (or rather ROMs).

It's an Android bug not that of PPSSPP.

**Comment by hrydgard** [comment]
Well, we do ask the system for the path to the SD card...

Ideally we should probably move ppsspp.ini to app-private storage which always works, with an option to have it in the current location too in case you want to manually edit it..

**Comment by leopard20** [comment]
Why not save it in the private storage in these cases, then try to move it to the PSP directory?

**Comment by leopard20** [comment]
Oops! Deleted my comment accidentally! 😅 Here it is again:

@hrydgard 
I don't think this has anything to do with storage permission. If the permission was not granted or saved, then you couldn't even display the contents of the memory.

The real issue here is (or at least I think it is) that you're accessing the sdcard from an invalid path, which only grants reading permissions not writing permissions. You have to access it via the valid path which is not that easy and varies across devices (or rather ROMs).

It's a ROM bug not that of PPSSPP.

@Jinzombie 
Have you inserted a memory card into your device?

**Comment by hrydgard** [comment]
I plan to do something like that but it's too scary a change for 1.6, I can foresee all sorts of bizarre problems that could arise...

**Comment by leopard20** [comment]
Maybe create a temporary PoC app for testing? (do not merge it to the main branch just upload it here!)

**Comment by Jinzombie** [comment]
@leopard20
No! Phone Storage Only.
This issue can easily bypass by rebooting/restarting my android phone 😅

**Comment by Jinzombie** [comment]
Opps... I will close this because I figured out if I delete the system folder or just newly installed a ppsspp build the problem happen but if I had already a system folder this isn't happen and also restarting the ppsspp fix the issue ✌😅

*Sorry for mistake 🙇

**Comment by hrydgard** [comment]
Oh! Hm, that's worth fixing....

**Comment by leopard20** [comment]
Told you it was because of an invalid path! Although not exactly what I had in mind! ;)

**Comment by hrydgard** [comment]
Adding it.

**Comment by hrydgard** [comment]
This should be ok now, please confirm :)

**Comment by Jinzombie** [comment]
its OK now 👍
@hrydgard thank you!

**Comment by unknownbrackets** [comment]
Awesome, glad to hear it.

-[Unknown]
