### ISSUE TITLE
Ppsspp for windows only works if you hold and drag the top bar of the application ...

### ISSUE THREAD

**Issue by IgoowMts** [hrydgard/ppsspp#11036]
### What happens?
the ppsspp in my positive windows only runs if you hold that bar from above where the buttons to minimize close and etc ... it gets the screen type frozen and things only move if you hold and drag the bar from above app ...

### What *should* happen?
My ppsspp should run normal without having to hold a bar from the top of the app

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
windows 10 pro
Processor: Intel (R) Celeron (R) CPU N3010 @ 1.04GHz 1.04GHz
Memory Installed RAM: 4,00GB
system type: 64-bit operating system, 64x based processor
ppsspp for windows version 1.5.4

**Comment by LunaMoo** [comment]
Can't reproduce anything like that, the only thing I got was OGL backend taking a while to initialize showing black screen for a few moments, but it happened once, not sure if random as I couldn't reproduce it. Also seems that OGL might have some problems in general as it seems to be limited to 30 fps in window, requiring full screen for 60 in 60fps games.

 Most likely all problems are caused by some windows 10 update, it's not like M$ has a reason to make sure their updates doesn't break stuff for all the people that agreed to be free beta testers of constantly changing OS. Would recommend trying different backend if ogl was used as windows 10 problems might not be an easy thing to work around.

**Comment by tilkinsc** [comment]
They should try an older build, too, and multiple rendering options. They could be playing on a device with old intel integrated graphics which were so buggy. 

https://ark.intel.com/products/91710/Intel-Celeron-Processor-N3010-2M-Cache-up-to-2_24-GHz

Processor Graphics
    Graphics Base Frequency 320 MHz
    Graphics Burst Frequency 600 MHz
    Graphics Video Max Memory 8 GB
    Execution Units 12
    DirectX* Support Yes
    OpenGL* Support Yes

**Comment by unknownbrackets** [comment]
Does this still happen with the latest PPSSPP git build, latest graphics drivers, and latest Windows version?  Are you using GeDoSaTo?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.  We're assuming this is a driver issue or conflict with GeDoSaTo.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
