### ISSUE TITLE
flOw fails to clear the screen when using Vulkan, quickly brightening to white

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11079]
From Reddit in thread about 1.6:

"I've been playing flOw on 1.5.4. Tried it on this version and I'm only basically getting a white screen. Sometimes I see the in game for a second and then it all goes white again".

**Comment by UroshUchiha** [comment]
Yeah, I wrote that. I always get a white screen while the music and stuff works in the background. I didn't tinker with the settings, pretty much left everything on default.

**Comment by unknownbrackets** [comment]
If possible, could you try some git builds to see when this started?

https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

There are about 1000 changes since 1.5.4, so if you try 500 first, then 750, etc. it'd take less than 10 tries to figure out when this started.

-[Unknown]

**Comment by UroshUchiha** [comment]
v1.5.4-673-g3cd92b4d9 is the last build that had it working

**Comment by unknownbrackets** [comment]
That implicates #10725.  Hmm.

-[Unknown]

**Comment by UroshUchiha** [comment]
You can see what's happening in the game for a split second when you double click to go into full screen and out of it.

**Comment by hrydgard** [comment]
Ah! Well that is interesting.

You should be able to play using the OpenGL backend. But this obviously needs investigation.

Can you make a frame dump? https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by UroshUchiha** [comment]
OpenGL backend makes it work on the newest version. 

And here's the frame dump:
[NPUG80086_0003.zip](https://github.com/hrydgard/ppsspp/files/2042358/NPUG80086_0003.zip)

**Comment by wilkovatch** [comment]
The bug only occurs when the backend is Vulkan and the rendering mode is "Buffered rendering", using OpenGL or the rendering mode "Skip buffer effects" fixes it. Also, every 10-40 seconds the screen returns to normal, and goes back to white some seconds later.

Here are two frame dumps (one recorded while the screen was white and one recorded while the screen was normal, both using Vulkan and Buffered rendering):
[NPUG80086_white_and_normal.zip](https://github.com/hrydgard/ppsspp/files/2042481/NPUG80086_white_and_normal.zip)

This is what happens when the screen goes white (slowed down 3x):
![bug](https://user-images.githubusercontent.com/29335145/40584832-8d2424f4-61a8-11e8-80fd-b551b0061b1f.gif)

**Comment by hrydgard** [comment]
Thanks guys, very helpful! I will look into it soon.

**Comment by unknownbrackets** [comment]
Ha, seeing that gif makes it seem pretty much like we're skipping some clear.

-[Unknown]

**Comment by hrydgard** [comment]
It appears that it clears a buffer, then uses it as a texture without drawing to it. Not the most optimal thing to do, but we should handle it. Our clear->renderpass merging does however not handle that scenario too well...

**Comment by unknownbrackets** [comment]
I can't tell from the dump if that will fix it but there's a decent chance - can either of you validate with the latest git build (when available from the buildbot)?

-[Unknown]

**Comment by UroshUchiha** [comment]
It's working now.

**Comment by unknownbrackets** [comment]
Hurray, thanks for verifying.

-[Unknown]
