### ISSUE TITLE
Medievil forceclose systemui when using vulkan

### ISSUE THREAD

**Issue by oli0371** [hrydgard/ppsspp#11075]
Each time the game load i got black screen and systemui force close i try open gl and the game work i only got this issue with vulkan on latest ppsspp build

Samsung galaxy s8 exynos
Mali g71 mp20
Opengl es 3.1
Gpu driver v1.r9p0-01rel0
Android oreo

**Comment by leopard20** [comment]
@hrydgard 
It's possibly a memory leak issue. (that's the only thing that closes the UI)

**Comment by unknownbrackets** [comment]
Is this using 1.6.0?  Did this used to work in 1.5.4?  Can you test git builds in between where it worked and where it stopped working?

You can test by halves, and it won't take that many tries (less than 10 tries for 1000 changes.)  This will help narrow it down a lot.

If it never worked since Vulkan was supported, it helps to know that too.

-[Unknown]

**Comment by oli0371** [comment]
I don't know exactly on which build the issue come because previously i was playing this game on s7 edge running nougat but i will try my best to search the build where the game work correctly.

**Comment by unknownbrackets** [comment]
Does this still happen with the latest git build / version?

-[Unknown]

**Comment by ResurrectionRedmi9** [comment]
Update your phone could possibly fix issue or use ppsspp latest git.
