### ISSUE TITLE
Please put New configurations that further improve the speed of ppsspp to run 60 fps god of war.

### ISSUE THREAD

**Issue by SuperBrowserProject** [hrydgard/ppsspp#11082]

**Comment by ppmeis** [comment]
Without any more info they can't do anything.

"What hardware, operating system, and PPSSPP version? On desktop, GPU matters for graphical issues." It's very clear this question.

**Comment by marosis** [comment]
Easy to say this, but hard to do it! In new version 1.6 have ppsspp extremely improved performance. If you can't reach playable FPS, you have Slow (maybe old) device. Henrik and team working on ppsspp everyday! CLOSE THIS-uselles info

**Comment by unknownbrackets** [comment]
Yeah - the trouble is, this is like someone's boss coming in and saying "start getting twice as much done."

I'd love nothing else than to get twice as much done, I just don't know how.  I was already trying to do better every day before and I'll keep trying, but without any specific ideas I don't know how to get twice as much done.

That said, there is one thing - someone has created a 30 FPS cheat for the game which makes it run better on weaker devices:
https://forums.ppsspp.org/showthread.php?tid=22159

Note that we have improved the "limit FPS" setting since that was created, but I think the 30 FPS cheat should help in any case.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, try the speed hacks and frameskip and whatnot, but we can't have an issue here for every game that's slow on some particular device. Closing.

**Comment by marosis** [comment]
Sorry for asking, but how to do FPS cheat code? Is it something hard, or can do it everybody?

**Comment by unknownbrackets** [comment]
It should just be via the cheat feature, I think there are instructions in that forum post.

-[Unknown]

**Comment by marosis** [comment]
Ah thank you
