### ISSUE TITLE
Provide release tarballs for packaging

### ISSUE THREAD

**Issue by bentley** [hrydgard/ppsspp#11090]
Package systems typically don’t directly support downloading from version control systems like Git.

GitHub “provides” automatically generated .tar.gz and .zip files that can be used instead, but these aren’t suitable for packaging for a number of reasons: the checksums are unstable and sometimes change due to updates to GitHub’s backend (upgrading git or gzip, for example), and **these tarballs don’t include submodules.**

Currently the OpenBSD package works around this by fetching autogenerated tarballs of the correct commits for each individual submodule and symlinking everything into the appropriate places. FreeBSD and Gentoo are similar. This is a hassle and is still subject to unstable checksums.

I would really appreciate if creating a distfile were part of the release process. It would make things much easier for us.

* Once the release has been tagged, clone: `git clone --recurse-submodules -b v1.6 https://github.com/hrydgard/ppsspp ppsspp-1.6`
* Remove `.git/` (saves >800 MB as of 1.6): `find ppsspp-1.6 -name .git -exec rm -rf {} \;`
* Create a tarball: `tar czf ppsspp-1.6.tar.gz ppsspp-1.6`
* Finally, upload the tarball as an asset on [the releases page](https://github.com/hrydgard/ppsspp/releases/tag/v1.6).

**Comment by unknownbrackets** [comment]
https://github.com/hrydgard/ppsspp/issues/9106#issuecomment-257322260
https://github.com/hrydgard/ppsspp/issues/8859#issuecomment-233106014

```
git clone --depth 1 --shallow-submodules --recursive https://github.com/hrydgard/ppsspp.git --branch v1.6
```

`.git/` won't be as large if you do a shallow clone.  You already get checksum and disk failure detection with git, that's why it uses shas in the first place.

-[Unknown]

**Comment by bentley** [comment]
>  You already get checksum and disk failure detection with git, that's why it uses shas in the first place.

That only helps if the packaging system uses git. But every packaging system I can think of relies on tarball distfiles. And Github’s tarballs are not usable because they have inconsistent checksums and don’t include submodules.

A single generated tarball provided by PPSSPP with each release would make packagers’ work significantly easier—both creating new packages and updating existing packages.

> `git clone --depth 1 --shallow-submodules --recursive https://github.com/hrydgard/ppsspp.git --branch v1.6`

This seems to fail for at least one submodule:

    error: Server does not allow request for unadvertised object 90966d50f57608587bafd95b4e345b02b814754a
    Fetched in submodule path 'ext/SPIRV-Cross', but it did not contain 90966d50f57608587bafd95b4e345b02b814754a. Direct fetching of that commit failed.

>  Otherwise, we'd have to store the tarballs somewhere, and worry about them and their .asc files getting hacked or something to get the same thing.

They can be attached to the Github release.

**Comment by rofl0r** [comment]
i second this. here's a detailed description of the issue with github auto-downloads. https://github.com/sabotage-linux/sabotage/wiki/Why-github-downloads-suck

in order to package ppsspp for my distro i'd basically have to download all the sources locally and create and upload my own tarball, but then consumers of the repo can't trust my tarball as it's not from the official upstream. the alternative would be to create 10 submodule tarballs for each submodule and use them as a dependency, but that's a huge effort for each release and would seriously bloat the package script directory.

**Comment by rofl0r** [comment]
here's a script you could use to create a dist tarball.

```sh
#!/bin/sh
test -z "$1" && { echo "error: need to supply version number as argument"; exit$
COMPRESS_THREADS=16
VER="$1"
me=$(pwd)

proj=ppsspp
projver=${proj}-${VER}
repo="$me"

tempdir=/tmp/${proj}-0000
rm -rf "$tempdir"
mkdir -p "$tempdir"

cd $tempdir || { echo ERROR CDing ; exit 1 ; }
# usually we would use git clone so the dirty changes aren't copied but
# --recursive is stupid and downloads everything again from the net
cp -r "$repo" $projver
cd $projver
git stash && git stash drop && git clean # drop changes and untracked files

rm -rf .git
# remove 100s of MBs of binary crap
for x in Window10 Windows linux android symbian ios macosx wiiu blackberry ; do 
rm -rf ffmpeg/"$x"
done

cd ..

echo bundling...
tar cf $proj.tar $projver/
echo compressing with $COMPRESS_THREADS threads...
xz -z -9 -e -c -T $COMPRESS_THREADS < $proj.tar > $proj.tar.xz
mv $proj.tar.xz $me/$projver.tar.xz && echo "done, $projver.tar.xz created"
```

i was pretty wtf when i noticed i just downloaded 700MB of prebuilt libraries in the "ffmpeg" directory, instead of the source code. i suspect most people building ppsspp from source never noticed that they're using someone else's (potentially malicious) binaries even though they specifically chose not to use binaries.
