### ISSUE TITLE
Detect DLC PSP file on MicroSD instead of Internal Storage

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#11115]
It'll help on some device have low internal storage size , you can copy DLC into MicroSD card and play it

**Comment by unknownbrackets** [comment]
Even though it seems logical, unfortunately games don't actually say "hi PSP OS, is there any DLC?"

Instead, they say "hi PSP OS, could you tell me what files are in /PSP/GAME/?"  From PPSSPP's perspective, maybe the game is checking if you had played a previous entry in the series.  Or maybe it's a homebrew that lists games you've installed for some reason.

Once PPSSPP answers, the game asks what files are in that folder.  Sometimes these files are data files for the game.  They could even be there because of a data install from UMD.  Or they might be DLC.  PPSSPP doesn't actually know.

How these files work and what they contain is all managed by the game code.  Even where they live.

So in effect, there are two ways to make it possible to put DLC onto your micro SD card:

1. The straight forward way: make it so that you can simply have the entire emulated storage at any location.
2. The really hard and complex way: translate any file IO to check for files in multiple paths, handling reads and writes, overrides, listing, and even free disk space requests properly.

#11812 implements the simpler option, but I think it still solves this general problem.

-[Unknown]

**Comment by ResurrectionRedmi9** [comment]
This can affect scoop storage?

**Comment by hrydgard** [comment]
The new scoped storage support lets you put your entire PSP directory on your MicroSD. Any additional support for this is not planned.
