### ISSUE TITLE
GPD XD (original): Manual Display Scaling not respected

### ISSUE THREAD

**Issue by radiocaravan** [hrydgard/ppsspp#11153]
Even though I set the screen to 2x PSP resolution manually, the games still play at full screen (2.67x resolution).

GPD XD original, running LegacyROM, PPSSPP 1.6.3

**Comment by unknownbrackets** [comment]
Are you using "skip buffer effects" for rendering?  Does this happen on the latest git build?

-[Unknown]

**Comment by ShelterPush** [comment]
I am having this same issue on a different device.

I am on a Kindle Fire HD 8 10th Gen, Fire OS 7.3.2.6 (based on Android 9, according to [https://developer.amazon.com/docs/fire-tablets/fire-os-7.html](https://developer.amazon.com/docs/fire-tablets/fire-os-7.html)) running PPSSPP 1.13.2

Relevant settings (I think):
Backend: Vulkan
Mode: Buffered rendering
Display layout editor: Zoom - 2.000 * PSP res
Fullscreen: True
Rendering resolution: 2x PSP
Display resolution (HW scaler): Auto

Having the Display layout editor set to Manual Zoom 2.000 is functionally identical to having it set to Auto or Zoom 2.666. Changing the backend to OpenGL does not fix it. 

Setting the Zoom to 1.000 does change it to PSP screen size, so I do not believe the Zoom setting is entirely broken on my device.

**Comment by unknownbrackets** [comment]
Can you try the latest git build?  The way the display layout editor works has changed quite a bit, so this setting doesn't exist exactly the same way.

-[Unknown]

**Comment by ShelterPush** [comment]
I tried [v1.13.2-2483-g5c27b3e01](https://github.com/hrydgard/ppsspp/commit/5c27b3e0122acb6ed274b3010021a5bd6b0c7f6e) from [https://buildbot.orphis.net/ppsspp/](https://buildbot.orphis.net/ppsspp/), and I can freely resize the game (and it keeps the setting), but I cannot see any option to set it to a specific scale. In fact, I only see a portion of the new Shaders menu (which is very useful, from what little I can see of it). It seems the implementation is incomplete (which makes sense, for an unreleased build). I have attached a screenshot (I hope in-game is okay).

![Screenshot_20221213-102049](https://user-images.githubusercontent.com/38357508/207373329-67d4dad2-c01b-453a-8d0a-0f4af760775f.png)

**Comment by hrydgard** [comment]
The clipping there is of course a bug, I'll fix that. Does your device happen to have an inset camera notch?

Settings a specific scale factor isn't all that useful anymore, in my opinion. You'll nearly always want to stretch to a desired size, rather than scaling the PSP pixels a specific amount, with today's high res screens, so scale is now specified in relation to the display size, that makes it behave more reasonably when changing the window size on PC too.

Aspect ratio useful together with some plugins that adjust the internal projection matrix of games to fit a different ratio (there is one for GTA now), and we might add some built-in support that will work for some games later.

**Comment by hrydgard** [comment]
Actually really struggling to find an explanation for the clipping problem there.... Weird. Not seeing that on my test devices, not even ones with insets.

**Comment by ShelterPush** [comment]
The Fire HD 8 10th gen does not have a camera inset, so I'm uncertain what makes it different as well. Haha.

I personally put all my handheld emulated games at a specific multiple of the original resolution. It typically looks better that way, in my opinion. The PSP looks surprisingly good at 2.67 times, probably because of the increased rendering resolution, but since it is rendering at 2x PSP resolution I would like it to also display at 2x PSP resolution, since I am on a 1280x800 screen.

Thank you for looking into this. It is ultimately a minor issue

**Comment by hrydgard** [comment]
Yeah like I said, there is a small usecase for exact scales that I might consider in the future. 

Anyway, do you get the weird clipping issue in both Vulkan and OpenGL modes?

**Comment by ShelterPush** [comment]
It appears to only be in Vulkan. Switching to OpenGL displays the whole window.

**Comment by hrydgard** [comment]
How screen scaling works has changed a lot since then, and there's now an explicit mode for integer scaling. I'm closing, but please report if there are still use cases that don't quite work.
