### ISSUE TITLE
Changing render libs should crash if not supported and return to previous, working one - Future Feature request

### ISSUE THREAD

**Issue by tilkinsc** [hrydgard/ppsspp#11166]
Before I installed vulkan redist, PPSSPP crashed on me. Similar thing happened with directx. I had to either go into the config and manually switch it, which I didn't because this end user couldn't find it within 2 seconds of opening, or re-extract it. Also makes sharing my hard drive with multiple devices weird.

Probably could be fixed by a series of init tests on startup, i.e. find out where the GFX API crashes at. Probably at `xInit();` or context creation.

**Comment by unknownbrackets** [comment]
Is this about Windows, Linux, or some other platform?

Does this happen with stable version releases, or only git builds?  The Windows git builds don't come with redist dlls.

-[Unknown]

**Comment by tilkinsc** [comment]
Windows, probably linux if it wasn't configured for vulkan
Both stable and git release

**Comment by hrydgard** [comment]
It tries to check for success, but yeah if it crashes we're in trouble...

**Comment by leopard20** [comment]
Here's what a newbie like me would do:

I suppose you could save the selected backend temporarily, but also add a new parameter like PreviousBackend that stores the previously selected backend to fall back to.
Once a backend is selected, store the new backend in the existing GraphicsBackend parameter, create an empty file called .restarting (I'm assuming creating an empty file is faster than writing a parameter to the config, reading it later and then again resetting it's value) and then let the app restart. 
The .restart file should be cleared on each startup if exists, then the config be read and use GraphicsBackend. If GraphicsBackend != PreviousBackend, then as soon as we're in the menu we set PreviousBackend = GraphicsBackend.
If however, we crash, since there's no .restart file and still GraphicsBackend != PreviousBackend, then we use the PreviousBackend and this time we set GraphicsBackend = PreviousBackend.

Seems a bit crazy but doable! LOL

**Comment by unknownbrackets** [comment]
With #11346 and #11802, we're now mostly doing this.  Not as much for Direct3D, but if a crash occurs it'll usually work to try starting PPSSPP again.

That said, if you're currently set to Vulkan and we detect Vulkan is unavailable, I don't think we switch away (and probably wouldn't want that...?)

As long as it's not the driver crashing, and just us doing insufficient validation before calling an unavailable API, this ought to be fixable...

-[Unknown]

**Comment by tilkinsc** [comment]
`(and probably wouldn't want that...?)`
If I don't use vulkan and no desire to obtain it, I shouldn't have to learn to read the ini and change a value so PPSSPP boots, for example on a flash drive without the first time run.

**Comment by unknownbrackets** [comment]
Well, that assumes that the Vulkan detection code is never broken and never needs troubleshooting.  Having the option to bypass it and try anyway, or even have it crash if I'm trying to figure out why it's crashing, can be nice.

It's kinda like if I set my computer to boot off a hard drive, but the hard drive had disk errors.  I wouldn't actually want it to silently boot off a different hard drive, I would want it to complain.

But I do realize this is at odds with the shared ini between different setups use case, as I'd mentioned.

-[Unknown]

**Comment by tilkinsc** [comment]
It doesn't silently fail. It tells you what it set to render with on init, even first time init.

**Comment by unknownbrackets** [comment]
How's this working now?  We've improved some of the handling, so generally speaking it should correct after the crash on the first run.  We can't always detect if the device is supported due to driver problems, but we've improved that too.

-[Unknown]

**Comment by tilkinsc** [comment]
I think I was merely, and crpytoly, suggesting to fall back to other renderers? I have vulkan now and would be fearful to uninstall it to test this case. As long as Vulkan doesn't fail, as it is the default renderer, and it crash the entire program, then you should be A OK!

**Comment by unknownbrackets** [comment]
Great, I'm going to close this then - I believe it's working well and we haven't gotten further reports of issues when it's set wrong either.

-[Unknown]
