### ISSUE TITLE
SD Gundam Generation Overworld Texture Issues

### ISSUE THREAD

**Issue by AkagiShiroe** [hrydgard/ppsspp#11236]
![08dc6e10dcad4170420e681e](https://user-images.githubusercontent.com/14356240/42134133-67e44eb0-7d70-11e8-812f-766c8d4e81e6.png)
everytimes texture are used, its treated as a "new texture" and generating random HASH like this:
000000005381dfea00000000 (the first and last "00000000" are randomized, only CLUT remains)
that's a huge slowdown for texture replacement (which take a damn 5-15 minutes just to load whole hash)
the problem is.. im loading around 10K+ hash replacement for this game. if you could fix this CLUT-only texture issues it will help the game performance also allowing faster texture replacement (and of course fixing this garbled texture), thanks for reading this.. if this isn't worth consideration, please close it.
Note: originally this texture are only 384x384.. PPSSPP will treat any non-standard resolution texture like this, so i think that's the root of the problem itself.

**Comment by LunaMoo** [comment]
PSP textures are only in power of two, images the game loads for textures aren't textures and ppsspp can't do anything with them. 

You can use "partialHash" flag for this game, but make sure to replace incomplete font textures with a complete one as mentioned https://github.com/hrydgard/ppsspp/pull/9668#issuecomment-299729846

Closing since it's just how some games work/can't do anything about it.
