### ISSUE TITLE
Ridge Racer and Ridge Racer 2 - Car model flicking

### ISSUE THREAD

**Issue by tabnk** [hrydgard/ppsspp#11247]
### What happens?

Car model flicking

### What *should* happen?
 
Ingame and car selection.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Latest build (v1.6.3-276-g53f162432) and IOS version 11 (IPad Air)

**Comment by unknownbrackets** [comment]
Can you post a screenshot or some more information?  Is this the same as #10573?

-[Unknown]

**Comment by tabnk** [comment]
Not same. I’m will try to post video later.

**Comment by tabnk** [comment]
Attached video. Ridge Racer

https://streamable.com/tnf2x

**Comment by YvanDroid** [comment]
I can also confirm that it does not exhibit this issue on Mali GPUs (Xperia XA1 Mali-T880). I would also suggest trying this again with a different settings. E.g Turning vertex cache off.

**Comment by hrydgard** [comment]
Does this still happen?

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
