### ISSUE TITLE
Tokimeki Memorial 4 weird white Lines on characters

### ISSUE THREAD

**Issue by rkguy** [hrydgard/ppsspp#11249]
### What happens?
Lines appear on characters' faces, probably due to the engine trying to simulate character movement.
![image](https://user-images.githubusercontent.com/17938431/42544555-9a1b015a-8480-11e8-9921-08833e7f3405.png)

It seems like I'm not the only one having the issue either.
https://forums.ppsspp.org/showthread.php?tid=397&page=2

### What *should* happen?
It should be free of white lines.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Desktop, Version 1.6.3

**Comment by unknownbrackets** [comment]
Guessing this is antialias / related to #6483.

-[Unknown]

**Comment by unknownbrackets** [comment]
Could you try exporting a GE debugger dump on PC?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by benderscruffy01** [comment]
this can be closed
i cant find any problem with it so far

**Comment by LunaMoo** [comment]
I believe the problem here only happened in D3D9, @benderscruffy01 could you re-test it on that backend?

**Comment by benderscruffy01** [comment]
yep only happens on D3D9 backend
[DUMP.ZIP](https://github.com/hrydgard/ppsspp/files/3026182/DUMP.ZIP)

**Comment by unknownbrackets** [comment]
This is a dual source blending issue.

The correct output (from a PSP):
![NPJH50127_#6379_tokimeki_memorial_4_arms](https://user-images.githubusercontent.com/191233/55689245-16141900-5937-11e9-96a8-c855cf6737b9.png)

And what renders in Direct3D9 (also has #6379 problem):
![NPJH50127_#11249_tokimeki_memorial_4_arms-d3d9](https://user-images.githubusercontent.com/191233/55690129-4ca36100-5942-11e9-8510-1340f98c0e66.png)

The face is "built" by a series of draws.  If you watch it draw, everything will look fine as it draws to the framebuffer.  But because it's blending (standard `src.a + (1 - src.a)`) and setting stencil to FF at the same time, the alpha becomes wrong.

The "lines" are just areas where the edge of the face parts had less than full alpha, so blended those areas to have partial alpha.  That said, we can fix this by more replacing alpha blending better in this scenario.

-[Unknown]
