### ISSUE TITLE
Alternative speed 2

### ISSUE THREAD

**Issue by HypeChangerIvan** [hrydgard/ppsspp#11257]
I know it is unrelated but what is the purpose of alternative speed 2? Does it affect my performance or graphics?

**Comment by 1234Sameer** [comment]
You can assign two different controller buttons for alternative speeds that can hold two different values.
Alternative speed 2 works same way as 1. They are like fast forward buttons. And you don't need them to play games. If you are using mobile you can turn them on under visibility.

**Comment by HypeChangerIvan** [comment]
How about the purpose of "alternative speed 2" in framerate control under graphic settings?

**Comment by 1234Sameer** [comment]
This is under framerate  control because if you use alternative speed you will notice Your game speed will try to catch the alternative speed value but also your framerate will decrease drastically. It is not like speeding up the game all the time. You can use them to skip long cut scenes. If you got answer to your questions you can close the issue. If you have any question you can ask in the forum. There is also an wiki guide of detailed settings explanation.

**Comment by LunaMoo** [comment]
Closing as non issue. This is an issue tracker, for support questions and such visit [forums](https://forums.ppsspp.org/index.php) instead.
