### ISSUE TITLE
Mapped keys can easily collide with debugger keyboard shortcuts on Windows

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11255]
Found this reddit post:

https://www.reddit.com/r/PPSSPP/comments/8z0iro/how_do_i_stop_the_memory_screen_from_showing_up/

It has a legitimate issue that if you map Ctrl and for example R to actions, and then press both at once, you'll trigger the debugger window. It's pretty easy to work around by simply not using Ctrl as an action button, but still, it might be nice if this worked better. Not sure what the best fix might be though.

**Comment by halotroop2288** [comment]
Why is this still an issue 2.5 years later? There's already a button mapping screen. Just add the hard-coded functions to the mapping screen.

I myself have been having trouble with this because right CTRL is my Discord push-to-talk key, and CTRL+W is the default binding for closing the current game, which I often end up pressing because WASD is bound to the (left) analog stick.

**Comment by unknownbrackets** [comment]
Can this be closed now that we have #14229?

-[Unknown]

**Comment by hrydgard** [comment]
It's a workaround, but it'll have to do - a full input overhaul is not happening soon.
