### ISSUE TITLE
Overbrigthness/Bloom in Raspberry Pi 3 with 1.5.4 in some games

### ISSUE THREAD

**Issue by luizthiagor** [hrydgard/ppsspp#11266]
### What happens?

Some games like the Ratchet and Clank , Jak and Daxter (all of same producer - High Impact Games) has an overbrigthness/bloom in raspberry Pi3 running the 1.5.4 version of ppsspp in batocera Linux. Only if i have checked the "disable lower effects (fast)" option ...if i not check this option the screens goes black in game and not possible to play ...

### What *should* happen?

This overbrigthness not exists in game and if i uncheck the "disable lower effects (fast)" option the screen not goes black ....

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

RPI3 , Batocera Linux 5.15 with ppsspp in 1.5.4

**Comment by unknownbrackets** [comment]
Does this happen in the latest git build?  Any new fixes will happen on the latest version - there's not really any chance of a "1.5.5".  If this issue is only in v1.5.4 and not newer versions, it's not an interesting issue.

Does this affect both Vulkan and OpenGL backends?

Disable slower effects is a setting to break the game a bit in order to make it faster.  Some games will become black.  The only way to fix that is to remove the setting entirely.  If it was a magic pill that made the game faster with no downsides, of course we would force it enabled always and remove the checkbox too.

The overbrightness could be missing dual source alpha support.

-[Unknown]

**Comment by luizthiagor** [comment]
my problem is reffered a Raspberry Pi 3 hardware with batocera Linux 5.15 with 1.5.4 version of ppsspp... i can't update this because i'm not the developer ...

but, in the 1.5.4 for raspberry, if i disable this option for "disable lower effects (fast) , the screem goes black and no image ...

In the new tests for 1.6.3 update i'm having bad performance in this hardware...in 1.5.4 the performance is very good, even with the "low speed" of the raspberry Pi 3 ...in 1.6.3 i believe this speed should to be more better, but it's contrary ...it's low compared to the 1.5.4 in same hardware ...

**Comment by luizthiagor** [comment]
in the version 1.6.3 i'm testing , this problem does not occur, if i disable the option "disable lower effects (fast)" , the overbrigthness not present and screen normal, not goes black like the 1.5.4 ...

the main problem in 1.6.3 for raspberry Pi 3 it's performance ... very low compared to the 1.5.4, but i not understand this .... the new version is "the fast one", but not in raspberrys .... it's can be related to the openGL version ? ... as i remember the raspberry only supports until now the OpenGL 2.0 , but not the 3.1 ...and, im my verification, the system information says has running in OpenGL ES 1.00 ! ...this performance problem in the 1.6.3 can be related to this ?

**Comment by LunaMoo** [comment]
Since the problem happens only when activating a game breaking speedhack and another problem mentioned here happens only on outdated versions, it's not a valid issue, as such closing.

**Comment by luizthiagor** [comment]
Ok... no problem . Sorry
