### ISSUE TITLE
Fast-forward broken on android on the libretro core

### ISSUE THREAD

**Issue by fr500** [hrydgard/ppsspp#11279]
What happens?

Fast-forward no longer seems to do anything on Android

What *should* happen?

It should Fast-forward

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.

Shield ATV 6.1, Android, Tegra X1, OpenGL backend

Related: https://github.com/libretro/ppsspp/issues/18

**Comment by orbea** [comment]
Fast-forward works here in Linux fwiw.

**Comment by m4xw** [comment]
@fr500 Is this still a Issue?

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]

**Comment by fr500** [comment]
No problem, I'm no longer associated with RetroArch at all (banned) so feel
free to close my issues.
