### ISSUE TITLE
"HellBoy The Science Of Evil" Grapical glitch (like locking bloom effects) when disable slower effects is ON

### ISSUE THREAD

**Issue by Emulatorer** [hrydgard/ppsspp#11306]
This video will tell the problem

https://youtu.be/9vSKVcFi480

I also try ppsspp v1.6.3 v1.5.4  but the issue still happen :( v1.3 did not happen

Phone Use:
Android 5.1
Mali-450 MP GPU
Octacore CPU
2GB ram
1.4Ghz

**Comment by Emulatorer** [comment]
As you can see in the video "Disable Slower Effects" speed up the game same problem in #11092

**Comment by Emulatorer** [comment]
Also I try skip-buffer effects (non-buffered) but this is what happen.
![screenshot_2018-08-15-14-33-07](https://user-images.githubusercontent.com/37603562/44228222-44fd3500-a184-11e8-90bb-a7053ec3baaa.png)

**Comment by marosis** [comment]
So off it. This settings not improving performance. I think it is absolutely uselles. I don't using it too. In a lot of games it is problematic

**Comment by LunaMoo** [comment]
The option is not useless and it's not there to "improve performance" universally at no cost as that's impossible and if it would be, it would never have an option and just be active all the time. That option is there because in some games it CAN improve performance sometimes even with no visual difference, but most of the time at cost of breaking graphics partially or completely, same can be said about skip buffer effects and all other speedhacks which are supported because PPSSPP supports a lot of crappy hardware.

 What is useless however are issues based on speedhacks, so I'm closing this.

 The general speed reduction is tracked in other issue already, through it's normal that fixing bugs and implementing more effects naturally slows down emulation, so even through there also are performance improvements, they cannot be as significant as a performance difference lost on compatibility between not doing something at all and doing it properly. In other words you should never expect newer versions of the emulator to reach higher performance and it's normal to use outdated emulators on bottom end hardware.
