### ISSUE TITLE
F1 2009 have performance issues

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#11314]
### What happens?
I think performance in intro what have Broken sound Is known even it running on 60 fps.(maybe different issue what have Dante's inferno). I cathed something what maybe can help.
![screenshot_20180823-115553](https://user-images.githubusercontent.com/33152267/44523061-dadf1580-a6d8-11e8-9445-821434c4e1ae.png)
![screenshot_20180823-115547](https://user-images.githubusercontent.com/33152267/44523129-209bde00-a6d9-11e8-91c6-f41673ce92a2.png)
On the top left side you will see two different files? Saying it am right? A lot of games are working great with 222MHZ. A lot of games have locked 30 fps (ingame) but this have still 60 and i don't think, this game is running with  60 fps on Real HW.(i think this is issue too)+ i think we didn't find a Real performance. Maybe this is why Juiced 2 HIN is too Slow. Maybe here is same problem. Interresting is that when i set Real clock synch. ON. It greatly improved performance over 2-3 fps. If i talking bullshits* and it is not relevant please tell me it and i will close it. Tested on OpenGL.

**Comment by marosis** [comment]
And yeah how i see i never reach 100% speed in 60 fps. I think this issue was somewhere on this site

**Comment by unknownbrackets** [comment]
If your device doesn't physically support 60 FPS, you will need to enable auto frameskip, and you'll never get 60 FPS - as noted in #11264.

-[Unknown]

**Comment by marosis** [comment]
I really don't know how the hell is possible for this game reach 60 fps ingame. Tested on PSP E-1004 and it is really reaching 60 fps on some places. Interresting

**Comment by marosis** [comment]
This game is really hard to emulate

**Comment by hrydgard** [comment]
Don't close stuff without a comment on why, unless it's really obvious.

**Comment by unknownbrackets** [comment]
Has any of this improved?  The real clock sync setting may have been misbehaving before, so I'm not sure if it will not improve or hurt performance.

-[Unknown]

**Comment by marosis** [comment]
Real clock sync decreased perf -3 fps

**Comment by unknownbrackets** [comment]
Most games don't use mp3s - I don't know if this one does, but it probably doesn't.  So most likely that pull request will not affect this.

Real clock sync changes how we time things, but it was only working sporadically before.  Probably, it's affecting the heuristics that make your OS decide when to downclock your CPU.

Without that setting, every frame (at 60fps, that's every 16.6ms) we do all the work for the frame, and when we're done, we wait until the next frame.  So if we're going faster than an actual PSP, we might do work for 3ms, and then have nothing to do for 13ms.

But if we had a lot to do, it gives us chances to catch up.  If you imagine we had 16 things to do, and on the PSP they each took 1ms, then if we're slower even on one of those things - we'll end up taking too long and you won't get 60fps.  But since we do it all at the start, if we are a bit slower for one thing, but faster for another - we might still be OK.

Real clock sync changes this.  Instead of syncing up every frame, it syncs up every 2ms.  This gives us a lot less wiggle room to be slower than an actual PSP.

The benefit, really, is if you press a button or if another player does something in multiplayer mid frame - the game can see it within 2ms.  That should mean better input lag.  The downside is, if we had a list of 16 things to do, and one of them is faster - we'll sit and do nothing right after it to keep in sync.  So now if another thing is slow, you'll almost definitely lose performance.

That's always been what the setting does.  Before, sometimes it would accidentally turn itself off after working for a short while.  Then it would be exactly like the setting was off.  Most likely, if this made any device faster, it was because of some weird OS CPU downclocking heuristics.

-[Unknown]

**Comment by Panderner** [comment]
Same happens in Dirt 2 logos and intros

**Comment by hrydgard** [comment]
Please add that as a separate issue, it doesn't belong in an issue about F1 2009.
