### ISSUE TITLE
[KH Birth by Sleep] Weird graphical anomalies in a few cutscenes.

### ISSUE THREAD

**Issue by AkiraJkr** [hrydgard/ppsspp#11316]
I assumed being a D3D9 error, but recently found out to be wrong as a friend of mine had found the same issue as me, and he even attempted seeing if they would be gone changing the backend, which didn't. I'll have the screenshots of some(if not all) of these situations, and their respective Cutscenes.
To prove this is not a issue with my texture pack, and more with the emulator, I turned it off.

Cutscene: **Terra - Unlocking the Door**
![There should be a image here](https://i.imgur.com/gEHhNQ7.png)

Cutscene: **Any cutscene that includes the mirror and this room.**
![There maybe should be a image here](https://i.imgur.com/w3jo2d9.png)

Cutscene: **Any cutscene that showcases the Radiant Garden logo**
![There definitely should be one here, I think](https://i.imgur.com/xLH6SZj.png)

Cutscene: **First Keyblade Graveyard cutscenes, where the logo shows up**
![Please there should be a image here too](https://i.imgur.com/EBoHMjd.png)

If any test is necessary or something for not having the game avaiable, please tell me.

And to assure you, this happens in any version of the game. Even Final Mix.

**Comment by unknownbrackets** [comment]
Could you try exporting a GE debugger dump on PC?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by AkiraJkr** [comment]
[PPSSPP_STATE.zip](https://github.com/hrydgard/ppsspp/files/2316502/PPSSPP_STATE.zip)

Throwing a save state here per request on Discord, later uploading a GE dump from someone.

**Comment by unknownbrackets** [comment]
> Any cutscene that includes the mirror and this room.

So, this happens only in Direct3D 9 and Direct3D 11.  It's fine in Vulkan and OpenGL.  Probably also doesn't work on mobile for Vulkan or OpenGL, though.

The bad part of the mirror is drawn with texturing disabled, and:
 * Alpha blend on: 2.0 * src.a + fixed 1.0
 * Alpha test on: a > 0
 * Depth test on: ALWAYS
 * Logic op on: noop

So the important thing is this only affects depth, since logic op is set to "noop" and stencil test is disabled.  Following the logic:

1. Replace blend is set to `REPLACE_BLEND_PRE_SRC` because of source alpha doubling.
2. Replace alpha is `REPLACE_ALPHA_NO` since no stencil op.
3. Because `replaceBlend` is not `REPLACE_BLEND_NO`, we don't try to emulate the logic op, so `noop` is ignored.

Presumably the blending settings were left on by accident and don't matter in this case.  There's a decent chance the other issues are also logic ops, but it's not for sure.  But a game using logic ops once is probably a game using them other places too.

-[Unknown]

**Comment by AkiraJkr** [comment]
Leaving here another cutscene that I forgot to add, incase it helps in some way.

Cutscene: All Characters - Mark of Mastery
![image](https://user-images.githubusercontent.com/27028529/44589150-20114f00-a78e-11e8-9ac5-019bdbff2d37.png)
