### ISSUE TITLE
[KH Birth by Sleep] Another graphical anomaly

### ISSUE THREAD

**Issue by AkiraJkr** [hrydgard/ppsspp#11326]
This one is also as old as the previous one I have submitted.

Cutscene: All Characters - Any that happen in this room.
![image](https://user-images.githubusercontent.com/27028529/44623548-dfa5f400-a8a7-11e8-81ab-01b4e6f7b195.png)

For some mysterious reason...this issue is not present during the gameplay...

![image](https://user-images.githubusercontent.com/27028529/44623559-2dbaf780-a8a8-11e8-9519-5d75d2a8159c.png)

This was tested without texture replacement so I can confirm that's not it.

**Comment by unknownbrackets** [comment]
Confirmed this happens only in Direct3D 9, not any other backend.  Could be a dual source blending issue.

In the GE debugger, it draws the ground perfectly fine at first.  This is the result of drawing the shadow.  I think it's related to this code:

```c++
	// For now, we just clear alpha/stencil from 565, which fixes shadow issues in Kingdom Hearts.
	// (it uses 565 to write zeros to the buffer, than 4444 to actually render the shadow.)
```

The backends do different things, though... and don't match that comment:

 * Vulkan: from 565, clears color/depth/stencil.  Seems to work fine for this game.
 * GLES: from 565, also clears color/depth/stencil.
 * Direct3D 11: from 565, clears color/alpha, but not depth or stencil.  Then seems to pointlessly also draw a clear (maybe the goal was to clear stencil)?
 * Direct3D 9: ALWAYS clears color/alpha, even from non-565.  Also clears stencil and alpha from 565.

This is a hack no matter what.  The original goal I think was to clear stencil/alpha when coming from 565, mainly because Kingdom Hearts cleared to zero in 565, then changed it to 4444 (and this caused us to have full alpha for the framebuffer, which is wrong.)

It's also concerning that Direct3D 9 always clears color/alpha, which is most probably wrong.

-[Unknown]

**Comment by unknownbrackets** [comment]
It's the draw causing it - it assigns a texturing shader, with no texture.  I guess it ends up with 0, 0, 0, 1.

The easiest solution is to clear everything on 565 only, like Vulkan/GLES does now.  Even keeping as a hack, it'd be better to only clear alpha/stencil everywhere, I think - less likely to break something, maybe.

-[Unknown]
