### ISSUE TITLE
Question to ISO Recent [TAB]

### ISSUE THREAD

**Issue by Slippy2k** [hrydgard/ppsspp#11320]
### What happens?
Hello,
can I deactivate in the source code Recent ISOs or they are not cached until only the latest games from the PPSSPP Store are displayed which I have started?

**Comment by unknownbrackets** [comment]
Open ppsspp.ini and set MaxRecent to `-1` instead of whatever number it's set to now.

I'm not sure what you mean by the PPSSPP store stuff.  The [forum](http://forums.ppsspp.org/) or [Discord](https://discord.gg/5NJB6dD) may be a better place for asking how to use PPSSPP - this is an issue list.

-[Unknown]
