### ISSUE TITLE
PPSSPP core won't load in Lakka for PC

### ISSUE THREAD

**Issue by ProgPete** [hrydgard/ppsspp#11343]
### What happens?
In Lakka the PPSSPP core won't load. PPSSSPP expects ppge_atlas.zim to have a MD5 sum of **a93fc411c1ce7d001a2a812643c70085** yet the latest version of that file has a MD5 checksum of **f46570c34bcf6a01cf20b93add725c3b** I have already placed the asset files in system\PPSSPP

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Platform: x86 (64bit) OS: Lakka version 2.1.1

**Comment by LunaMoo** [comment]
Added the Libretro label, but imo this is not a problem that can be fixed here since AFAIK we don't check for assets files checksums, wrong asset file would simply display incorrectly.

**Comment by orbea** [comment]
This is not a problem with my own built package, I think this should be brought up with the Lakka maintainers.

**Comment by natinusala** [comment]
Is this issue still present with latest Lakka ?

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.  This is even more true when the bug appears to exist in another system.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
