### ISSUE TITLE
[Direct3D9] Exaggerated effects in Gods Eater Burst

### ISSUE THREAD

**Issue by AkiraJkr** [hrydgard/ppsspp#11342]
![image](https://user-images.githubusercontent.com/27028529/44942152-e938cb80-ad81-11e8-83e3-4a67194edaf6.png)

Does not happen in phones, or other backends as far as I'm aware, as in the image example above, the bloom, and several other effects unrelated to bloom are applied way too much than they should, and it even causes huge issues to navigate interfaces like the Terminal.

**Comment by unknownbrackets** [comment]
Does it help to use "lower resolution for effects"?

-[Unknown]

**Comment by AkiraJkr** [comment]
I don't seem to notice any difference.

Safe
![image](https://user-images.githubusercontent.com/27028529/44942607-f22e9a80-ad8b-11e8-8dd9-727a0a553d14.png)

Balanced
![image](https://user-images.githubusercontent.com/27028529/44942609-fc509900-ad8b-11e8-993e-e1aebc4592ff.png)

![image](https://user-images.githubusercontent.com/27028529/44942611-070b2e00-ad8c-11e8-8fe2-916b41a224b8.png)

**Comment by unknownbrackets** [comment]
Comparing this scene with Vulkan and software rendering, I don't think it's wrong.  Software rendering is a bit dimmer overall (I think from handling some of the blending, fogging, and dithering more accurately), but it's not that different.  I didn't notice any differences anymore between Direct3D 9 and Vulkan.

Going to close this assuming it's been fixed in the meantime.

-[Unknown]
