### ISSUE TITLE
[OpenGL][Android] Persona 3 Portable closes the emulator

### ISSUE THREAD

**Issue by VoSed** [hrydgard/ppsspp#11355]
### What happens?
The emulator closes when selecting the protagonist's gender or after loading save files

### What *should* happen?
The game must be played

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
- Hardware, OS: Nokia 5 TA-1053, Android 8.1
 - PPSSPP version: Standalone (1.6.3) / RetroArch core (f87dcef ARMv7)

**Comment by TehPlayer14** [comment]
New nokia's I sense they are going to be pain to fix...

Can you try the rom on your pc if it's not corrupted?

**Comment by VoSed** [comment]
On PC with OpenGL working fine. Also working on my phone with Vulkan, but not OpenGL

**Comment by VoSed** [comment]
I want to use OpenGL because some of RetroArch cores not working with Vulkan

**Comment by unknownbrackets** [comment]
I'm able to reproduce, that's interesting.  Pixel with latest Android 9.

```
W Adreno-GSL: <gsl_ldd_control:548>: ioctl fd 49 code 0xc040094a (IOCTL_KGSL_GPU_COMMAND) failed: errno 35 Resource deadlock would occur
```

It then dies, unceremoniously.  No crash log, so I guess the driver kills it?

Someone reports that something similar happens when gl_FragDepth is written to [on Qualcomm's forum](https://developer.qualcomm.com/forum/qdn-forums/maximize-hardware/mobile-gaming-graphics-adreno/28771), but that's not the cause in PPSSPP - made sure.

I tried the following settings, which seemingly delay the crash, but don't prevent it:
 * Buffered rendering off
 * Block transfer off
 * Hardware transform off
 * 1x PSP resolution
 * Disable slower effects

If it doesn't crash right away at gender select, simply swap back and forth.  It will crash.

Vulkan indeed does not crash.

Unfortunately, I think this may just be a driver bug.  Can you check if any past version works?  If so, we may be able to figure out when it stopped working.

-[Unknown]

**Comment by unknownbrackets** [comment]
Tried one more thing, with interesting results.  I peppered GLRenderManager and GLQueueRunner with `glFinish()` calls.  It still gets "Protocol error" messages, but doesn't crash.  However, the display stops updating.

It updates again if I switch out of the app and back, and keeps working until I try to switch characters.  If I press left or right, I hear the sound that indicates my selection is changing, so I know it's still running.  But even going back to the UI (without app switching) doesn't update.

Hm.

-[Unknown]

**Comment by zminhquanz** [comment]
@unknownbrackets Yes , on my Galaxy S7 USA , using Adreno 530 , when i'm update Android Oreo , using new driver , i'll crash on OpenGL when playing persona 3 , but on Vulkan , it's working

**Comment by unknownbrackets** [comment]
This crash still happens on Adreno 5xx / Android 9, but doesn't happen on Adreno 6xx / Android 8.  It could be specific to Adreno 5xx.

-[Unknown]

**Comment by VoSed** [comment]
Just tried PPSSPP ca992d3 RA core. Game is working!

**Comment by Panderner** [comment]
Have you turned off fast memory?

**Comment by unknownbrackets** [comment]
This has nothing to do with fast memory.  The graphics driver logs an error right before the crash, which seems to happen within the graphics driver.

-[Unknown]

**Comment by Gamemulatorer** [comment]
This can be also fix by adding this game to ***PixelDepthRounding*** :)
I think it's time to create a compat fix for adreno 3xx and 5xx series opengl bug
