### ISSUE TITLE
Custom resolution

### ISSUE THREAD

**Issue by GuilhermeGS2** [hrydgard/ppsspp#11369]
I've been lookingn the source code trying to find where is set the rendering resolution, but I couldn't find it. I'd like to make an "1.5x resolution" (720x408) and try it here, should be useful for my (crappy) phone. 1xPSP is too low for my screen, and 2xPSP is too much for my GPU, then "1.5x" should do.

**Comment by marosis** [comment]
This can be i think incompatible+ maybe resolution glitches

**Comment by marosis** [comment]
Something like #11289

**Comment by LunaMoo** [comment]
Closing this since it was said many times in the past that there will not be a custom rendering resolution in PPSSPP since devs don't want to deal with mass bug reports that follows any new hackish option that causes glitches for the sake of performance, at this point in time the exact opposite - removal of such options - is desired.

 Also as written when closing #5413 there's few enough hardware that can't use x2 to bother.

**Comment by GuilhermeGS2** [comment]
Man, I just want to know WHERE are the codes I need to change, just want to make my own build. I probably missed something, but I didn't find it.

**Comment by marosis** [comment]
Please read!

**Comment by Emulatorer** [comment]
1X rendering resolution it's ok when 4X MSAA is on in my developers options in android looks good see #10889

**Comment by Emulatorer** [comment]
I have a settings for that game
https://youtu.be/HY-oyPARhTY
but not stable @30FPS because my phone gpu is too weak but it's running smoothly 😅

**Comment by GuilhermeGS2** [comment]
@Emulatorer well, 65 MHz of emulated clock will lock down the FPS around 15-20, it'll feel very laggy.
