### ISSUE TITLE
[Long broken issue]Any fix on the PPA?

### ISSUE THREAD

**Issue by WattanaGaming** [hrydgard/ppsspp#11383]
My issues mostly get closed, but not for this time. the build version was not working properly, shaders wont work and often corrupt the config file resulting in crashes. the PPA version is also outdated, its still stuck on 1.5 while the build has already gone to 1.6. 

**_I have reported for a few times and if you close this issue it meant you ware ignoring Linux only problems!_**

**Comment by unknownbrackets** [comment]
That's not how this works.  This isn't a support helpdesk, or the place you call in to when your food refrigerator is broken.  This is an issue list - for an open source project.

If your refrigerator is broken, you don't just keep adding a new refrigerator to your shopping cart until it starts working.  That'd be silly.  Kinda like creating a duplicate issue would be.  It might be good for a laugh, or so you can vent about your broken refrigerator, but it's still obviously pointless to add more to your shopping cart.

So this is being closed.  Because #11138 is already in the shopping cart.  We don't need two refrigerators.  Just one.

I'm sorry it's not fixed, but I'm not seeing you try to fix it.  PPSSPP is open source.  Muster up some courage, roll up your sleeves, stop griping at other people not doing your bidding for free, and do something about it yourself.

If you're not feeling that brave, but still want the latest PPSSPP?  Just compile it yourself.  It's super easy.  Anyone who can run Linux and figure out how to open a GitHub account and create an issue can definitely figure out how to compile PPSSPP.  You've got this, don't let the haters tell you otherwise.

Or if you really can't be bothered, I guess you'll just have to be patient.  If we thought #11138 was fixed, it'd be closed.  Someone's working on it, but maybe they have other priorities than you or other things in their life.  It won't say "Open" on it anymore when it's fixed.

-[Unknown]
