### ISSUE TITLE
[Request] Change just one specific key for the default button mapping settings

### ISSUE THREAD

**Issue by AkiraJkr** [hrydgard/ppsspp#11406]
The request is to change one of the default control mapping settings.

Simply Swap"W" for "E" for the "L Button".

The buttons Q and W don't like to be pressed at the same time in most of the normal, usual keyboards, so fixing this should stop issues like people asking that pressing both buttons don't work in games like Kingdom Hearts for example like issue #11394.

**Comment by LunaMoo** [comment]
That statement isn't true, each keyboard differ and there's really no standard between them at least not outside of specific brands which sometimes can follow same design, for example on mine qwer keys can all be pressed at once just fine.
 Also the mentioned issue has a guy who remapped keys to use L for L, R for R and O for circle you can literally read it in the first post.

 I don't think changing defaults would really help as most keyboard users will change defaults quickly anyway, the real problem is that some users have no idea about the keyboard design flaw despite using keyboard for playing.

**Comment by unknownbrackets** [comment]
I guess if we wanted we could show some sort of "wizard" to help them identify rollover issues and test keys...

-[Unknown]
