### ISSUE TITLE
[Discussion]Advanced GLSL shader and unstable PPA hype train?

### ISSUE THREAD

**Issue by WattanaGaming** [hrydgard/ppsspp#11419]
## First topic: Advanced GLSL shaders
Since the emulator can manipulate the graphic easily since it was HLE, advanced GLSL shader might be possible. If the shader can have more access to the rendering then it might be possible to implement something like Godrays and advanced bloom. The question was "Will it came soon?". Optifine for Minecraft already done this and enabled shaders to do something like volumetric lighting and more.

*Oh and I have seen many updates recently. Is it me or is it a hype train?*

**Comment by hrydgard** [comment]
There are many things that could in theory be done but things like godrays would necessarily be game specific. We actually don't know as much as you'd think about what is what in a scene - no sure way to tell which light is the sun, for example. And a lot of games don't even use hardware lighting very much or at all, it's common that games implement their own. 

So really, not much is likely going to happen here. Maybe we'll add a mode for per-pixel instead of per-vertex lighting at one point but apart from that, no.

As for any kind of hype train, don't know what you're talking about, but development is progressing.

**Comment by WattanaGaming** [comment]
I just feel like the unstable ppa update more frequently.
