### ISSUE TITLE
[Controller] PPSSPP doesn't detect controller if plugged after launch.

### ISSUE THREAD

**Issue by AkiraJkr** [hrydgard/ppsspp#11446]
Controllers are properly detected and working normally if it's already plugged while you're starting, but the case is different if you try to plug a controller while PPSSPP is open.

**Comment by unknownbrackets** [comment]
Has this ever worked?

Even when I plug in a controller, I keep getting `ERROR_DEVICE_NOT_CONNECTED` from XInput for all pads.  I even tried unloading and reloading the DLL.

-[Unknown]

**Comment by unknownbrackets** [comment]
It may work with #11461, but only for devices exposed as both DirectInput and XInput.  When plugged in after launch, it will be detected as a different pad, and use a different control mapping because of this.

Which is not really ideal... but I'm not sure how to get the XInput devices to register after app start.

-[Unknown]

**Comment by LunaMoo** [comment]
Is it really a problem for Xinput controllers? I have a few logitech controllers and they work fine if connected after ppsspp starts, as far as I remember always did. They all have a physical switch between dinput-xinput, but they definitely aren't/can't use both at once.

**Comment by unknownbrackets** [comment]
Oh, so maybe it's just a problem with the PS4 controller I tested, or just on Windows 10?  In that case, perhaps this is fixed now with DirectInput being detected.

-[Unknown]

**Comment by AkiraJkr** [comment]
Can confirm this is fixed, sorry for delay.
