### ISSUE TITLE
Significant stuttering issues on Windows 8.1

### ISSUE THREAD

**Issue by MisterDigitalGuy** [hrydgard/ppsspp#11469]
After recently upgrading from 1.5.4 to 1.6.3, I have noticed that the game runs significantly slower on my PC than it did in the previous version. Specifically, the sound runs much slower than it did on the previous version (in which the sound ran virtually interrupted), and I've had to use frameskipping rates ranging from 3 to 5 to completely eliminate the sound stutters (1 appears to be insufficient), but this ends up impacting my FPS significantly

I am currently using a Lenovo Y70 laptop with an Nvidia GeForce GTX 860M and Intel Core i5 processors, PPSSPP is using Direct3D11 as no other modes work on my machine

**Comment by LunaMoo** [comment]
You should include the game's name and describe the place where in-game the problem happens.

 A quick note: sound is synchronized with the video, saying sound slows down is irrelevant as it means the game slows down. Also sound emulation would practically never be a bottleneck which in case of PSP emulation typicaly lies with graphics that often is hardcore to emulate on modern gpu apis, commonly also affected by buggy drivers.
 
  If a game becomes much slower after update, it usually means PPSSPP emulates more effects which were missing previously, this doesn't mean the game will look prettier or have more effects as many PSP games used really hard to emulate effects for practically no reason whatsoever and sometimes there's no difference between having some effect in game or not outside of reduced performance. If new effects are the reason of your performance drop, you can check "disable slower effects" in the graphics settings to restore older performance(and also older glitches if there were any).

  Also before doing anything else, I would recommend to update to latest ppsspp version as the performance drop could be a reason of some issue which could already been solved as the 1.6.3 you're using is awfuly outdated by now. You can get latest ppsspp versions from the bottom of the official download page or directly at the buildbot page here https://buildbot.orphis.net/ppsspp/

**Comment by MisterDigitalGuy** [comment]
Game is G-Force (2007), issue occurs mainly in places with multiple sounds playing at once or lots of "stuff" occurring (such as multiple enemies together with close proximity), though brief slowdowns can occur rather randomly (impact is negligible though, and the slowdowns are not nearly as great as they are in the previously described scenario)

**Comment by unknownbrackets** [comment]
You mentioned that performance got worse between the two versions.  It'd help a lot if you could try git builds in between them and see when it first failed:

http://buildbot.orphis.net/ppsspp/index.php?m=fulllist

In this list, v1.5.4-1005-ge8da82c01 came right before v1.6.  There's about 1000 changes between v1.5.4 and v1.6.3.  Since I can't reproduce the issue, my only option is to stare at these 1000 changes - one by one - and try to guess which might maybe have caused it.

You, however, have a special power - you can reproduce the issue.  By testing even just one build, like v1.5.4-501-gf99983002, you would cut down half the small fry like they were nothing.  If v1.5.4-501-gf99983002 is fast, the problem was introduced between 501 and 1005.  If 501 is slow, it was introduced between 1 and 501.  As the hero of this story, you could cut down the enemies that overwhelm me with about 10 swings of your blade.

So if you could test a few builds by halves like that, you might find which change started things moving slower for you.  Then we can just look at a few changes and figure out why they aren't working for you.

But as LunaMoo mentioned - it'd also help to test the latest git build there.  It's v1.6.3-569-gc514a27c8, so you can tell we've already made 569 changes since v1.6.3 came out (and some of them improve performance.)

-[Unknown]

**Comment by unknownbrackets** [comment]
Has this changed in the latest git builds?  Any feedback on the above?

Also, just to be sure, can you try changing SeparateSASThread to False instead of True in ppsspp.ini? I don't think this will help, but I just want to eliminate it as a possibility.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
