### ISSUE TITLE
Midnight Club 3 DUB Edition freezes in garage

### ISSUE THREAD

**Issue by iArti** [hrydgard/ppsspp#11501]
### What happens?
Game freezes when I'm exiting "body shop' section in garage (somehow, it only affects "body shop" but not "performace" or vynils section)
[Screencast](https://cloud.mail.ru/public/5e5f/Atrjt5CBX)
It happens on both OpenGL and Vulkan
### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues
I'm using PPSSPP 1.7 on Xiaomi Mi Max (Snapdragon 650/Adreno 510, Android 7.1.2). On 1.5.4-855 I haven't faced such issue
Also, I can't reproduce this bug on Windows, so it only affects Android

**Comment by unknownbrackets** [comment]
Does it happen in v1.6.3?

I don't have the game, and there were almost 1000 changes between the two versions.  For me, it would take forever to guess which of those caused the issue.

But you have a super power.  You can reproduce the issue, so if you tried a game half way between - it would cut down half of those versions like the small fry they are.  As the hero of this story, you can swing your sword about 10 times, and you'd find exactly the gremlin that started causing the issue.

When you try one in the middle, if it works, go up by half, and if it still doesn't work, go down by half.

Also, since it only affects Android - it might help to try the same thing with "CPU Core" set to Interpreter (under Developer Tools in settings.)  It may be a bit slower, but if this fixes it, it helps hone in on the problem.

-[Unknown]

**Comment by hrydgard** [comment]
Hopefully this is another manifestation of the elusive ARM64 jit bug..

**Comment by iArti** [comment]
> Also, since it only affects Android - it might help to try the same thing with "CPU Core" set to Interpreter (under Developer Tools in settings.) It may be a bit slower, but if this fixes it, it helps hone in on the problem.

I switched to "interpreter", but it hasn't fixed the problem
It still freezes

**Comment by benderscruffy01** [comment]
could the label android be add as this doesnt happen on windows

**Comment by unknownbrackets** [comment]
It would be interesting to check now if the IR Interpreter makes it work / not work, for those using Android.

-[Unknown]

**Comment by hrydgard** [comment]
How is this now? Make sure you use a clean UMD dump, appears some bad ones are floating around, see #12084.

**Comment by unknownbrackets** [comment]
Any feedback?  If this is still an issue, you can help by trying it out again and checking your disc.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
