### ISSUE TITLE
Configure option to disable Discord

### ISSUE THREAD

**Issue by bentley** [hrydgard/ppsspp#11512]
Currently Discord support is disabled on iOS. It would be nice to have a CMake option to turn it off on other operating systems.

**Comment by jbeich** [comment]
The intent here is unhardcoding the following conditionals in order to avoid building dead code, assuming it doesn't increase maintenance too much. Discord desktop client (Electron-based app) is closed-source, so the integration cannot be used on any platform the vendor didn't provide prebuilt binary for. While FreeBSD and NetBSD can translate Linux syscalls Electron (like Chromium) requires a lot that weren't implemented.
https://github.com/hrydgard/ppsspp/blob/fdb07323e0878e4773011a7a51a43a8900ad9d4a/UI/DiscordIntegration.cpp#L10-L18
https://github.com/hrydgard/ppsspp/blob/fdb07323e0878e4773011a7a51a43a8900ad9d4a/ext/CMakeLists.txt#L15-L17
