### ISSUE TITLE
Gta lcs & vcs stuck on multiplayer screen

### ISSUE THREAD

**Issue by kyousuke77** [hrydgard/ppsspp#11522]
Device:Xiaomi Redmi 5a
Buffered rendering open GL
https://postimg.cc/SJF3kNT5

**Comment by Emulatorer** [comment]
Similar #9450?

**Comment by kyousuke77** [comment]
Yep,same

**Comment by sisxgame** [comment]
Working whith my two phones. 
The settings. 
https://imgur.com/a/nHGbp6G
Generating random mac adress.

**Comment by unknownbrackets** [comment]
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by ANR2ME** [comment]
GTA VCS worked fine by now, not sure about LCS tho.

**Comment by unknownbrackets** [comment]
This issue is being closed because it's likely fixed and hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]

**Comment by DavidTamas** [comment]
Both LCS and VCS work but only if both UPnP settings are enabled.

Played on PPSSPPWindows64, v1.11.1.
Tested with:
```
ULUS10160_1.03 GTA: Liberty City Stories
ULUS10041_3.00 Grand Theft Auto: Vice City Stories
```
Keep in mind that there are around 12 LCS and 6 or 7 VCS game versions.

Here are my Networking settings:
```
Enable networking/WLAN: ON
WLAN channel: Auto

Enable built-in PRO ad hoc server: off
Change PRO ad hoc server IP address: myneighborsushicat.com

Enable UPnP: ON
UPnP use original port: ON

TCP No Delay: doesn't matter
Forced first connect: doesn't matter
```

They also both work on localhost with multiple instances.
