### ISSUE TITLE
[OpenGL] SD Gundam Generation Overworld battle stages Issues

### ISSUE THREAD

**Issue by LightVR0** [hrydgard/ppsspp#11548]
### What happens?
If the mobile suit attacks to other, the ground on the battle stages is missing.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
This issue only affects on OpenGL as backend (tested on Alcatel Pixi4(5)). Other backends (as Direct3D9 on Windows 7 (Olidata J10IL1)) aren't affected by this issue.

**Comment by LightVR0** [comment]
A screenshot:
![screenshot_20181210-160120 1](https://user-images.githubusercontent.com/16720683/49755151-e447ba00-fc96-11e8-8d41-dc54dc6694cf.png)

**Comment by unknownbrackets** [comment]
Any chance you could upload a GE frame dump?  It's like a 3d screenshot and helps us figure out why things aren't drawn.

-[Unknown]

**Comment by Panderner** [comment]
@LightVR0 No feedback?

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.  There's a decent chance it was fixed by some changes in depth range clipping/culling.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
