### ISSUE TITLE
Bad performance at MT6592 cpu ?(

### ISSUE THREAD

**Issue by Karaulov** [hrydgard/ppsspp#11540]
I got low FPS in all games.

Can something speed up the game on this CPU? :(

8 cores with 2ghz speed!!! (cortex a7 :( )

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Android 6
MT6592
PPSSPP version - latest build 

GPU Type:
ARM Mali-450 MP4
Max GPU Frequency:
700MHz

**Comment by Karaulov** [comment]
i got 55% of performance (fps) in tekken 6

**Comment by Karaulov** [comment]
I never in my life can't play PSP games on this brick? :(

**Comment by leopard20** [comment]
Sadly there's little you can do, since the MT6592 chipset is kinda weak.
Also, this is more of a question than an issue, so you should post it on the forum or on discord. https://discord.gg/sdCwGGQ

Maybe try this 30 FPS cheat for Tekken 6 (if you have the US version):
`_C0 Force 30 FPS
_L 0x20452890 0x00000000`

Please don't post any follow up questions you may have in here.

**Comment by Karaulov** [comment]
But problem in all games. Tekken just for example. 

This is not error? MT6592 can't play PSP games at 100% performance?

**Comment by leopard20** [comment]
https://www.notebookcheck.net/Mediatek-MT6592-SoC.111604.0.html
You can play lighter games at 100% speed. But it's not enough for heavy games like Tekkn 6 or GoW.

As a rule of thumb, your SoC must achieve a minimum AnTuTu score of 60000 for most games to play fluently (some games still require tweaks), while your SoC barely goes over 30000. So it's 50% weaker than the minimum requirement.

**Comment by Karaulov** [comment]
Thanks :( 

Minimum system requirements never decrease? :(

**Comment by marosis** [comment]
Yeah how @leopard20 said. Here is nothing What developer's can do. Only what you can do is wait (1 year for see better performance) or buy new phone.

**Comment by Emulatorer** [comment]
@Karaulov we have the same chipset but yours is a little bit faster because your cpu clock speed is 2.0ghz while mine is just 1.4ghz only but I can say still enjoying playing ppsspp even I can't reach the full speed/fps of the game.

The only thing you should do is find the best settings for everygame you want to play in ppsspp that's the only thing you/we can do

HERE'S MY SAMPLE VIDEO GAME PLAY OF TEKKEN USING MALI-450 MP 1.4GHZ CPU
https://youtu.be/Eea9bqyiMYg




p.s sorry for my bad english hope you understand me :)
