### ISSUE TITLE
Controller stick range

### ISSUE THREAD

**Issue by VirgilChen97** [hrydgard/ppsspp#11552]
### What happens?
Xbox One S controller analog stick can't reach full range 
![problem](https://user-images.githubusercontent.com/26373319/48310459-637b9c80-e5ca-11e8-9194-d6470b5dad1d.png)
### What *should* happen?
When using the on-screen controls, the stick can reach the top-left, top-rigth, bottom-left, bottom-right corner, but a contrller can't. 
### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Android 8.0, PPSSPP version 1.7.1

**Comment by VirgilChen97** [comment]
In game it cause my character can only run when the stick moves to up/down/left/right. For other direction, my character can only walk which means the controller doesn't reach its full range.

**Comment by unknownbrackets** [comment]
Does it show the same way in the "Game Controllers" control panel within Windows?  Or does it show the full range there?

-[Unknown]

**Comment by VirgilChen97** [comment]
Seems like it behaves the same in windows settings, here is the example:
![responsive](https://user-images.githubusercontent.com/26373319/79034092-f8e0de80-7b78-11ea-88f3-b6ecb6b22792.gif)
But it works just fine in games on Windows.

**Comment by unknownbrackets** [comment]
Hm, we do boost the corners on Windows, but I think we might not on Android.  I wonder if we can tell if the controller reports a circular or square area...

-[Unknown]

**Comment by fu8765** [comment]
as above, noticed this on Dissidia, with an nvidia shield TV, and dualshock 3

**Comment by hrydgard** [comment]
Should probably make some form of corner boost configurable and available on all platforms...

**Comment by hrydgard** [comment]
Risk of regression is too large for 1.10, I'm gonna push this to 1.11 (but it will be implemented). 

We should probably remove all remapping that's done in XInput.cpp and DInput.cpp, extract it to a function, and call it from __CtrlSetAnalogX/Y . That way it will be automatically available on all platforms. We should also redo the analog tester screen to actually show the mapped joystick instead of just the first two axes it finds, and it should contain some options for corner expansion so it can be configured right there.

**Comment by Kzitold** [comment]
What kind of controller uses square analog sticks?

And couldn't this be easily solved with Pythagorean theorem? `(X^2 + Y^2)^0.5 = diagonal tilt`

**Comment by hrydgard** [comment]
The PSP has square analog stick input.

**Comment by hrydgard** [comment]
Haven't gotten around to this for 1.11 but I have a plan.

* Change all the "input backends" to just output raw coordinates
* Add an AnalogMapper thingy that takes raw coordinates and applies deadzones, corner boosts, etc.
* Add a visualization and a bunch of sliders for the settings, so you can both see the raw input and output coordinates and easily configure the best range
* Expose some sorts of consistent device name so that different joysticks still can have different settings for this
* Have preset defaults for common inputs like XInput controllers so they will still act consistently by default

This all is too big to make it into 1.11 unfortunately, but should improve the experience a lot.

**Comment by Gamemulatorer** [comment]
This issue should probably resolve via https://github.com/hrydgard/ppsspp/commit/25cfb92a9ca356931ee1f998d39dd825696e6ddd

**Comment by hrydgard** [comment]
This should be fixed now with the new analog calibration screen.
