### ISSUE TITLE
Spectral vs Generation (Europe) bottom of screen flashes

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#11581]
during the developers screens and videos the bottom of the screen flashes
happens in both opengl and Direct X11
![spectral](https://user-images.githubusercontent.com/2696404/48966164-c88db400-f006-11e8-95ff-6ba2d41877f0.PNG)
[DUMP.ZIP](https://github.com/hrydgard/ppsspp/files/2612108/DUMP.ZIP)

**Comment by Panderner** [comment]
Pressing the unthrottle button to fix this bug

**Comment by unknownbrackets** [comment]
The dump unfortunately didn't capture the issue.

I wonder if we're misdetecting this as an offset framebuffer texture.  The game seems to be doing the very typical thing of alternating at +272/+0 for the video frames.  If we were somehow looking at the bottom 240 pixels of a 512 tall texture (missing the 32 pixels below that), the above is about what it would look like.

-[Unknown]

**Comment by Panderner** [comment]
Somehow this game is originally released on the arcade running PolyGame Master hardware. PGM uses 448x224 resolution which is almost fit for psp's resolution but stretched to 16:9

**Comment by sergioad** [comment]
This issue is also present in the libretro core

![Spectral vs Generation Europe-210812-112051](https://user-images.githubusercontent.com/5375145/129233484-97145d62-fbd9-48bf-8879-8161d881d72f.png)
![Spectral vs Generation Europe-210812-112106](https://user-images.githubusercontent.com/5375145/129233488-92d39236-f577-4eb4-b70c-cf8bea645bf3.png)
![Spectral vs Generation Europe-210812-112124](https://user-images.githubusercontent.com/5375145/129233491-9d859a70-f680-4446-ab0a-da89c438f91a.png)

The issue disappears upon reaching the title screen and thus gameplay is unharmed

![Spectral vs Generation Europe-210812-112414](https://user-images.githubusercontent.com/5375145/129233693-90083454-c0b9-4f6c-8313-16325c6b3cbc.png)

**Comment by benderscruffy** [comment]
PPSSPP v1.13.1-249-gf80dd088b
issue is still present
doesn't happen in the software renderer

**Comment by unknownbrackets** [comment]
Does this still happen?  Maybe it was somehow related to depth or some of the changes to texture or reinterpret buffer matching.

-[Unknown]

**Comment by Panderner** [comment]
It's fixed now no more bottom of screen flashes.
