### ISSUE TITLE
VK: Super Robot Wars Advance Portable - Bad VShader Cached

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11599]
As reported in the forums:

http://forums.ppsspp.org/showthread.php?tid=24427

This error keeps appearing when the Vulkan backend is selected.

Got to be some state caching bug. A frame dump (from any API) would be most useful: https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by hrydgard** [comment]
Is this the same games as Super Robot Taisen?

**Comment by unknownbrackets** [comment]
Hm.  In Execute_Bezier / Execute_Spline, we don't actually flush before we `gstate_c.Dirty(DIRTY_VERTEXSHADER_STATE);`.  `SubmitCurve` flushes, but this is already too late, as we've already prevented transform.  That seems like an issue.

But, I'm not sure it's causing this, since `useHWTransform` won't have changed.

This might help if someone can reproduce it:

```c++
		if ((*vshader)->UseHWTransform() != useHWTransform) {
			VShaderID CorrectVSID;
			ComputeVertexShaderID(&CorrectVSID, vertType, useHWTransform);
			ERROR_LOG_REPORT(HLE, "Wrong: %s, right: %s", VertexShaderDesc(VSID).c_str(), VertexShaderDesc(CorrectVSID).c_str());
		}
```

-[Unknown]

**Comment by unknownbrackets** [comment]
This recording was provided near the error, but unfortunately it doesn't trigger the error for me:
https://cdn.discordapp.com/attachments/480103153803460614/517100741723291658/recording.ppdmp

-[Unknown]

**Comment by unknownbrackets** [comment]
It seems like this can, at least, happen when switching hardware transform on/off mid game.

-[Unknown]

**Comment by unknownbrackets** [comment]
My theory is that this was happening with the prim inner loop, when the prim type switched from triangle to rectangle.  `SubmitPrim()` would flush, but not dirty the vertexshader state.  `SetDrawType()` does dirty the state, though.

So I suspect #11613 may have fixed this since it added a call to `SetDrawType()`.

Does this still happen?

-[Unknown]

**Comment by Emulatorer** [comment]
I have this game but ma phone support only OGL a frame dump is still useful Sir @hrydgard?

**Comment by PikachuEXE** [comment]
Seems not having it in v1.7.5-431-g9736bc431
Tested with window 64bit version

**Comment by unknownbrackets** [comment]
Thanks again for reporting this is fixed.

-[Unknown]
