### ISSUE TITLE
Reports of crash on save state

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11607]
Email report:

> I was running PPSSPP 1.7.1 and could not figure out why it kept force closing. I found it by accident. The game would be running fine then I use a save state then the game would freeze.  It did it to me an several games. If I clear the save state folder the games will run fine until I save a state. Then it force  and it does not do it closes again. I downgraded to 1.6.3 and it does it too but not as bad. Then I downgraded to 1.5.4 and it does not do it ata ll. Downside of 1.5.4 is that not many of my games work with  that version. They work with 1.6. and 1.7.1. Any way you can check into that save state force closing 1.7.1 ?

**Comment by unknownbrackets** [comment]
It could be out of memory, since most people are not having any issues with save states.  While we try to catch that for the main large allocation, there are some smaller allocations (like vector copies etc.) that are hard to work around.

Without details on the exact game or a reproduce case, not sure what we can do on this?

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, me neither.  You're probably right that it's likely an OOM issue.

**Comment by hrydgard** [comment]
Inconclusive, closing.
