### ISSUE TITLE
A connection error has occurred in Yugioh Tag Force 6

### ISSUE THREAD

**Issue by dikorommel** [hrydgard/ppsspp#11611]
Game:yugioh tag force 6 
Pict:https://ibb.co/DWqkqb2

**Comment by Emulatorer** [comment]
I think that game doesn't support ad hoc multiplayer?

**Comment by Saramagrean** [comment]
It's working, with PPSSPP custom build by Onelight . :)

https://i.imgur.com/nxsPmYL.jpg

**Comment by dikorommel** [comment]
@saramageran:link

**Comment by Saramagrean** [comment]
Here.
http://forums.ppsspp.org/showthread.php?tid=12357

**Comment by unknownbrackets** [comment]
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
