### ISSUE TITLE
Long-term goal: Remove "Disable slower effects" checkbox, and "Simulate Block Transfers"

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11610]
This checkbox breaks so many games and creates many unnecessary bug reports. My goal is to look into all cases that really are very slow, and fix them to work at reasonable performance.

First success here is the virtual readbacks , #11531 , that improved performance of Digimon Adventure (it's still a fairly demanding game for some devices, but at least the massive performance-killing readbacks are gone).

I'm interested in other cases where we end up doing unnecessarily costly operations that this checkbox avoids.

Of course, very weak GPUs might still get stressed from the actual GPU part of the effects so we might not be able to completely remove it, but we should be able to move it into the more obscure options eventually.

Cases:
~~#11531~~ Digimon Adventure
#11573 Call of Duty
~~#11092 3rd Birthday~~
~~Burnout Legends sun  (should be fixable with the #11531 method with some work)~~
Tactics Ogre?
~~Test Drive (#11531 can be used, though needs more fixes)~~

Related, "Simulate block transfers" has similar problems and should also be removed.

**Comment by hrydgard** [comment]
One alternative might be to simply force the checkbox to off for games that require these effects.

#11573 would be a candidate.

**Comment by Emulatorer** [comment]
#11092 could also be a candidate?

**Comment by hrydgard** [comment]
Yeah, that should definitely be listed here.

**Comment by marosis** [comment]
#11953

**Comment by leopard20** [comment]
@hrydgard Burnout Dominator is also affected by "Simulate Block Trans." (disabling it makes the game 2 times faster)

**Comment by Emulatorer** [comment]
Burnout Dominator and Burnout Legend benefits from Simulate Block Transfer Effects fixing small square in the sun

Just add the game ID to [BlockTransferAllowCreateFB] compat.ini I just tried both Dominator and Legend game are faster even Simulate Block Transfer Effects is enable I just need to set the rendering resolution to X1 as my phone is low specs 😅

**Comment by nassau-tk** [comment]
I'm tunr off "Simulate Block Transfers" these game on Android device.
*Windows PC is not need them. Because, I think thatPC has enough CPU&GPU Power.

OS：Android 9.0
DeviceName：SONY SO-02K / Xperia XZ1 Compact（Japan）
CPU：Snapdragon835（Octa-core）
GPU：Adreno 540
Resolution：720×1280
RAM：4GB
ROM：32GB
ExternalStrage：microSDXC 512GB

[Simulate Block Transfers Off==>Can getting enough FPS.]
ARMORED CORE FORMULA FRONT(ULJS00003)
ARMORED CORE FORMULA FRONT International (ULJS19001)
These games get enough FPS and not happen graphic glitched on Android device.

[Getting enough FPS.But happen glitched.]
Tactics Ogre - Unmei no Wa (ULJM05753) will get ennough FPS.
But, It's not drawing some graphics correctly.  

**[Tactics Ogre-Simulate Block Transfers On/Graphic OK/Goes down FPS]**
![ULJM05753_BlockTrans_On](https://user-images.githubusercontent.com/48179091/95076713-3fd91680-074d-11eb-863e-f97395246b72.png)

**[Tactics Ogre-Simulate Block Transfers Off/Graphic Bad/Enough FPS]**
![ULJM05753_BlockTrans_Off](https://user-images.githubusercontent.com/48179091/95076830-744cd280-074d-11eb-92d3-b32da8975dfa.png)


GachiTora-Abarenbou kyoushi in HighSchool- (NPJH50409) too.
**[GachiTora Block Transfers On/Graphic OK/Goes down FPS]**
![NPJH50409_BlockTrans_On](https://user-images.githubusercontent.com/48179091/95076930-97778200-074d-11eb-9cc2-c7536ff68581.png)

**[GachiTora Block Transfers Off/Graphic Bad/enough FPS]**
![NPJH50409_BlockTrans_Off](https://user-images.githubusercontent.com/48179091/95076963-a65e3480-074d-11eb-8f4c-f74a6a74fb58.png)

For reference!!

**Comment by IrfanH495** [comment]
is 3rd birthday included?
Simulate Block Transfers Effects ON
![Screenshot_20221006-212424_PPSSPP](https://user-images.githubusercontent.com/78854859/194339542-1d9e017f-77c3-4bfa-878d-90e44e42a516.jpg)
Simulate Block Transfers Effects OFF
![Screenshot_20221006-212412_PPSSPP](https://user-images.githubusercontent.com/78854859/194339837-086f63d5-c383-48c6-9684-38a36e32ac6d.jpg)

**Comment by Gamemulatorer** [comment]
> Are the colors correct in the upper or lower image?

I can't tell what is correct on those screenshots.

I aslo discover that there's an issue in the recently build using OpenGL backend.

***OPENGL***
![Screenshot_2022-10-08-00-26-33-62](https://user-images.githubusercontent.com/37603562/194602554-35d1781c-f3c2-45e0-bc81-5684187c2800.png)

***VULKAN***
![Screenshot_2022-10-08-00-26-17-24](https://user-images.githubusercontent.com/37603562/194602613-86f25e51-f337-4f8e-ab40-4e360d0691ac.png)

***Software***
![Screenshot_2022-10-08-00-26-58-12](https://user-images.githubusercontent.com/37603562/194602663-1fd9dace-4c37-4914-9b32-d650d9df3634.png)

**Comment by Gamemulatorer** [comment]
GE Dump.
[BraveStory.zip](https://github.com/hrydgard/ppsspp/files/9735617/BraveStory.zip)

**Comment by hrydgard** [comment]
Thanks. We should separate out the Brave Story problems in a separate issue..

**Comment by hrydgard** [comment]
These checkboxes have been refactored into a single speedhack, "Skip GPU readbacks". Closing.
