### ISSUE TITLE
Mali T760 performance not as anticipated

### ISSUE THREAD

**Issue by hissingshark** [hrydgard/ppsspp#11664]
Hi,

I'm trying to find a Linux SBC to improve just a little more on the Vero4k (S905x) performance.  That's was a Mali T450 MP2 (?clock speed) and an A53 clocked at 1.4GHz.

I've just built PPSSSPP from master on a Tinkerboard, running under Armbian.  So that's a Mali T760 MP4 clocked at 600MHz and an A17 clocked at 1.8GHz.  The performance is certainly not RPi3 bad, but it's not as good as the Vero4k.  **Am I wrong to have expected an improvement with these specs?**

My main suspect is that the T760 is offering ES 3.2, 3.1, 3.0 and 2.0, whereas the T450 was 2.0 only.  I'm assuming that newer ES versions bring newer features, but at greater overhead, so I'd see better performance if PPSSPP fell back to 2.0.  I've tried to force this in `/SDL/SDLGLGraphicsContext.cpp`

```
#ifdef USING_GLES2
//		{3, 2}, {3, 1}, {3, 0}, {2, 0},
		{2, 0},
#else
```

but with no obvious benefit.  **Is the process more complicated than that?**

I also wondered about I/O performance to the shader cache folder as I'm using MicroSD here rather than EMMC.  I could test this by using a ramdrive for the folder to improve performance, but I imagine the shaders are cached in memory during a given run anyway, so this will be to no benefit.

Many Thanks in advance.

**Comment by hissingshark** [comment]
Ah ok, thanks for excluding that then.

I've just found that my old Mali T450 was actually an MP**3** and may be running as high as 750MHz.
**Does PPSSPP performance scale better against clock speed than the number of processor units then?**  I suppose it would depend how genuinely threaded things are.

**Comment by hrydgard** [comment]
It's very hard to compare performance across these embedded GPUs, there are so many factors (maybe they're connected to slow memory, etc?). I couldn't tell you if it's as expected or not.

**Comment by unknownbrackets** [comment]
Another factor could be driver.  It could be that the device giving better performance has just spent time updating the graphics driver more recently than the other device.  It's entirely possible this could have more impact than hardware would - unfortunately.

In theory, most graphics rendering should scale well to multiple cores.  There's some rendering (complex blending modes) which might impact this.  I think comparing the "cube" demo performance would be interesting, since it should have no real complexity.

IO is not likely to be a bottleneck.  The shader cache is lazily updated when new shaders are seen, but not written to / read from otherwise, except on startup.  It's just used to preload shaders into RAM on startup, really.

The way you used to downgrade GLES should work, though as noted probably isn't a good lever for performance.

This might be a better discussion for the forum...

-[Unknown]

**Comment by hissingshark** [comment]
@unknownbrackets I think the driver used in the Vero4k will have seen significantly more attention as it's been developed primarily as a Kodi platform, so that would totally bear out against the Tinkerboard.  Maybe time will do it justice.
I'll check out that cube demo too.
> This might be a better discussion for the forum...

As I require no further advice on the code front I'll close this, rather than pollute the issues list.
***
@Emulatorer Thanks for the real world comparison.  From a quick lookup I assume the T450 is the quad (MP4) and the T720 was the octacore, but I take your point.  MP8 > MP4
***
So on paper at least an ODROID XU4 with a Mali-T628 MP6 would represent best value for money in terms of GPU cores, (the CPU is totally excessive but I could shut off cores to save power) but the quality of the drivers would decide everything...
