### ISSUE TITLE
AdhocServer connect error

### ISSUE THREAD

**Issue by wdy8841693** [hrydgard/ppsspp#11663]
### What happens?
When I use ppsspp1.7.1 to connect with others, sometimes it will fail.

### What *should* happen?
Connected successfully every time

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
hardware:  computer
OS: windows
PPSSPP: 1.7.1

I have tracked the code. The reason is that proAdhocServer has lost the event.

In Function <int matchingEventThread(int matchingId) >
          When the loop ends once, the function will call clearStack to clear the entire stack.

         When the function runs to:

                for (ThreadMessage * msg = head; msg != NULL; msg = msg->next)>.

          Other threads call linkEVMessage to add events to the top of the stack.But the function only checks the tail of the stack.
          So when the loop ends, the events added later are lost.

void linkEVMessage(SceNetAdhocMatchingContext * context, ThreadMessage * message)
{
	// Lock Access
	context->eventlock->lock();

	// Link Message
	message->next = context->event_stack;
	context->event_stack = message;

	// Unlock Access
	context->eventlock->unlock();
}

I originally wanted to solve this problem myself and submit it, but my overall understanding of the software is not enough. Where can I find information about the ppsspp software architecture? In this way, I will be able to solve the problem myself afterwards.

Sorry for my poor English.

**Comment by Emulatorer** [comment]
Try to use the ppsspp build hack of @lightfirst it's good in adhoc multiplayer http://forums.ppsspp.org/showthread.php?tid=12357

**Comment by wdy8841693** [comment]
> Try to use the ppsspp build hack of @lightfirst it's good in adhoc multiplayer http://forums.ppsspp.org/showthread.php?tid=12357

I just looked at the code and they have the same problem.

**Comment by Emulatorer** [comment]
@wdy8841693 PPSSPP networking/WLAN
is still in beta :/

**Comment by adenovan** [comment]
for psp architectue try to look on psp sdk source https://github.com/pspdev/pspsdk

use jpcsptrace or pspautotest to trace the call on actuall psp to see how the call should be implemented if you want more info on the game itself.

that adhoc matching event use udp socket , and send udp datagram between peer to link event so if the packet not arrived due to firewall or something blocking the event packet it will fail because some of event are lost . also it use weird port 1, 2 which is system port on some game , try to set port offset more than 1024 it will workaround the event link on some game but not guaranteed the game will continue the connection. some game refuse ppsspp matching event implementation.

what game did you try to fix?

**Comment by unknownbrackets** [comment]
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by ANR2ME** [comment]
Yes, the cleared stacks issue that cause some events to be lost upon exiting the thread has been fixed.
