### ISSUE TITLE
ppsspp1.7.4 for Windows not see the cheats!

### ISSUE THREAD

**Issue by DStrifer** [hrydgard/ppsspp#11670]
Why 1.7.4 not see the Cheat.db ? The other versions and android version works fine with cheats.

**Comment by unknownbrackets** [comment]
This doesn't seem to be broken for me, but can you try git builds here?

https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

Try the latest git build, v1.6.3-588-g61e38b453, and v1.6-9-g87beddc39.  If these all work, it's probably an issue with your installation of 1.7.4.  If the latest and v1.6.3-588-g61e38b453 don't work, try somewhere in the middle like v1.6.3-267-gfb9524b63.

By going by halves, you can find where it broke with only a few tries.  Since you're able to reproduce this issue, and other people aren't, you are the hero of this story: you're the only person who can defeat the evil bug.  Everyone else is pinned down by the small fry.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
