### ISSUE TITLE
undefine eglQueryString after install libglvnd

### ISSUE THREAD

**Issue by bullghost** [hrydgard/ppsspp#11707]
Trying build ppsspp for Odroid XU4 using GBM SDL2 

### What happens?
before its work fine but after i install the libglvnd package and recompile ppsspp with no error 
but error when i run it with error message :
symbol lookup error : ./PPSSPPSDL : undefined symbol : eglQueryString
even if i build from source , it still happening.
if i complete remove libglvnd and recompile again PPSSPPSDL is working fine 
### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Odroid XU4 
Mali GPU
using GBM SDL2
build by following this url [https://forum.odroid.com/viewtopic.php?f=98&t=32173](url)
source libglvnd i get from here [https://github.com/NVIDIA/libglvnd](url)

ppsspp get from branch latest commit was 4cef8038bb3501c95e35f92959234edc2331262c

**Comment by unknownbrackets** [comment]
Is your libglvnd actually compiled with EGL?

https://patchwork.freedesktop.org/patch/131239/

-[Unknown]

**Comment by bullghost** [comment]
i see the configure help  of  libglvnd, by default it was enable

`  --disable-egl           Disable EGL support [default=enabled]
  --disable-glx           Disable GLX support [default=enabled]
  --disable-gles          Do not build the libGLES*.so libraries
                          [default=enabled]
`

**Comment by unknownbrackets** [comment]
Well, we just need a `eglQueryString` function to be able to use EGL.  This isn't a PPSSPP function, it's an EGL function.

It's possible this is a linking problem, so you could try changing the order of libraries in the linker command.  If that fixes it, a pull request would be great.

Otherwise it's probably an issue with the libraries on your system.

-[Unknown]

**Comment by unknownbrackets** [comment]
Any luck getting this to work, perhaps with a different linker order?

-[Unknown]

**Comment by unknownbrackets** [comment]
I'm going to close this because it hasn't been updated with feedback.  If you've got more information, feel free to comment here again and we'll reopen it.

Based on #11778, it sounds like it is possible to compile PPSSPP on ODROID XU4, although that user was seeing issues with the SDL2 library needing to be recompiled with proper options, it seems like.  You might try again with the latest git build.

-[Unknown]
