### ISSUE TITLE
Save menu hides text

### ISSUE THREAD

**Issue by tilkinsc** [hrydgard/ppsspp#11711]
### What happens?
![image](https://user-images.githubusercontent.com/7494772/50628208-113d6480-0f05-11e9-920c-13e0fb8966ec.png)

The text is hidden behind the gui from ppsspp

### What *should* happen?

The save state text and image should be raised, or at least the text

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Windows, vulkan, gtx 1080ti, 1.7.5 dev 345 g12e54baeb

**Comment by hrydgard** [comment]
Yup, our layout can't handle quite that much text it seems.

**Comment by tilkinsc** [comment]
Oh yeah and these are official fonts rather than PPSSPP fonts from my fat psp-1000

**Comment by hrydgard** [comment]
Yeah, it doesn't matter in this case though. Since the save menus are normally provided by the PSP OS, we've had to simulate them, and we're always using our own font in this case. These simulated menus have some deficiencies, like this one. Any chance you could get a screenshot of what the layout looks like with this save data on a real PSP?

**Comment by unknownbrackets** [comment]
It looks like this on a real PSP:

![trails_savedata](https://user-images.githubusercontent.com/191233/50727253-44325480-10cd-11e9-85cb-288b318ffd97.png)

The same in PPSSPP:
![trails_ppsspp_savedata](https://user-images.githubusercontent.com/191233/50727282-97a4a280-10cd-11e9-8a7c-8fa9bafa0638.png)

So clearly, it ellipsizes the text, but we also have much higher leading / line height, while a thinner, more shorter font face.  That said, I think it's clear that the intent in this case was to expose all the levels to the user and that it doesn't is probably just a shortcoming in the UI.

-[Unknown]

**Comment by hrydgard** [comment]
I suppose the easiest fix would be to just check if the text layouts too big, and in that case scale it down...

Not prioritizing it for 1.8.0 though myself.

**Comment by tilkinsc** [comment]
Do you feel like we should keep a consistent style with the real PSP?

**Comment by hrydgard** [comment]
I think it should be roughly similar, but where we can make minor improvements there's no reason not to.

**Comment by tilkinsc** [comment]
Where exactly is the code for the positioning? I could make a temp hack for myself.

**Comment by hrydgard** [comment]
The various system UIs are in Core/Dialog/PSP*.cpp. It uses an internal drawing library that generates PSP GPU commands that are fed to our GPU backend, to integrate cleanly, called PPGe which resides in Core/Util/PPGeDraw.*.

**Comment by tilkinsc** [comment]
I wonder if implementing a scrolling text area would solve this problem if the text > y of the screen. Controlled by the joystick?

This area should contain only the text and not the title or image. That would be an awesome solution, as it would fit the style (and thus of a mechanic of the psp) while improving functionality.

**Comment by unknownbrackets** [comment]
I wouldn't be against a joystick, though some might expect that to scroll between save items.

It could be something like hold the R key + up/down, since there's a legend at the bottom already.  If it's only slightly taller, I think smaller makes more sense.  In this case, it probably has up to 4 names and levels, so scrolling would probably be better.

An argument against (though I think this is doubtful) is that perhaps some games have garbage after several \n\ns that they didn't care about since no one could see them anyway.

-[Unknown]
