### ISSUE TITLE
Deterministic RNG

### ISSUE THREAD

**Issue by InfamousKnight** [hrydgard/ppsspp#11728]
Okay, so one more problem with tasing in particular. So far re-recording and save states are working fine with libtas. But rng resets every time we play back, making it hard to and annoying to work with. I first tested Star Wars battlefront 2(a really good game to tas) and was disappointed when I found out rng wasn’t deterministic.

Anyone know how to solve this?

**Comment by unknownbrackets** [comment]
The start time, and RNG parameters, of a game are based on the real time when you start the game.  So if you start it on 2019-01-12 at 16:04:30, then that's what the game sees.  This is the same experience you get on a real PSP, which is why we do that.

However, if you create a save state, it saves everything - including the time.  To get deterministic RNG, you can start from a shared save state at the very beginning of emulation.  So you would want a time=0 save state (you can get this by setting the emulator to enter debugging on load) and to start all TAS - recording and playback - from this state.

-[Unknown]

**Comment by InfamousKnight** [comment]
Interesting. Thanks again

**Comment by MiYakuGaming** [comment]
Any updates on this?

**Comment by unknownbrackets** [comment]
Nothing has changed.  All the state is saved in a save state, and the current time (like on all modern consoles/devices) is used and displayed by games.

Users would be confused if every game said it was March 24, 2005 or something.  In fact, some savedata would fail to load because the game would think you hacked it (since it'd be dated in the future for other play sessions.)

This isn't really a problem on older systems where games had no access to a real time clock, or only had access to one that could count seconds from an arbitrary time.  In contrast, the PSP firmware asks you for the current date when you first turn it on, and all games know this.  Many games base their random generator off of the current date and time (on the PSP and on other modern consoles / PCs.)

So, just use a save state with a shared start time.

-[Unknown]
