### ISSUE TITLE
Ace Combat X: Skies of Deception Framerate Drop

### ISSUE THREAD

**Issue by TideGear** [hrydgard/ppsspp#11754]
Ace Combat X has occasional framerate drops and I caught it with a savestate...

[Ace Combat X Framerate Drop.zip](https://github.com/hrydgard/ppsspp/files/2824220/Ace.Combat.X.Framerate.Drop.zip)

I'm using v1.7.5-394-g4816e80b4 on a Galaxy S9+ (USA) on OS 9.0. It seems to happen in both OpenGL and Vulkan.

**Comment by LunaMoo** [comment]
The game has to draw much more when you're flying low above the ground like in your savestate, if you fly higher it becomes much lighter since most of the ground geometry get's hidden in the fog.

 You should not expect the game to have same requirements in different places, it's not a bug and it's completely normal that drawing more requires stronger hardware than not drawing it especially in a very active game where you fly fast and all the world around has to constantly change, same would happen if you switch display in-game to see a plane, game will become more demanding than when only displaying HUD as in your savestate as it has to process more geometry, can only recommend to use auto frameskip, reduce rendering resolution(if it's not already x1) or playing on something more powerful like a desktop with dedicated gpu.

**Comment by hrydgard** [comment]
It's possible that games framedrop more in PPSSPP than the real PSP if we get the timing estimation of the GPU emulation wrong, we've adjusted the factors before. But please compare to a real PSP.

**Comment by LunaMoo** [comment]
The game doesn't drop frames in that savestate, it just becomes heavier to render since it's doing much more of the same thing due to close proximity of the ground, it's perfectly smooth(well ~ as good as 30fps can get;p) on stronger hardware.
