### ISSUE TITLE
Network sync failed error when playing via hotspot tethering

### ISSUE THREAD

**Issue by kyousuke77** [hrydgard/ppsspp#11759]
Dissidia 012 Final Fantasy
Xiaomi redmi 5a
we played with hotspot tethering
device:xiaomi redmi 5a&4a
ppsspp version:android 1.7.5

**Comment by unknownbrackets** [comment]
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]

**Comment by MillZou** [comment]
This still happens.

The Ad Hoc server is enabled on ppsspp v1.11.3-597 on Windows.
An Android device running ppsspp 1.11.2-299 and tries to connect the one running on Windows.
The Windows and Android devices are connected to the same WiFi, and connected via LAN IP distributed by the router.

All operations before the battle start (lobby screen, customization, battle intro video, etc.) are smooth and successful. After the battle starts, if no one takes any actions, the problem is unlikely to happen. If anyone takes any action (move/attack, etc.), the "network sync fail" error will appear in 2 seconds, and the battle is forced to end on both end.

**Comment by unknownbrackets** [comment]
That sounds like #14361.  Maybe it's better to keep it to that issue.

Also, it's better if you can use the same git build between clients.  There have been changes (like the sin/cos stuff mentioned in #14361) that may improve network sync, but both clients need to have the updates.

-[Unknown]
