### ISSUE TITLE
User report: Long notes in Rock Band Unplugged are not registered correctly

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#11798]
He tried using both touchscreen and a iPega 9087 controller, on Android.

**Comment by LunaMoo** [comment]
When this was posted on the forums, quick google search said such issue with this game happens on real PSP as well when played with RemoteJoy and can be affected by PSP cpu clock, so it's most likely a timing issue.

**Comment by hrydgard** [comment]
Ah, didn't notice a forum post, I got an email. A timing issue of some sort would not surprise much indeed.

**Comment by unknownbrackets** [comment]
What sceCtrl polling method does it use?  Cycle based on vblank based?

A log showing sceCtrl would answer this.

-[Unknown]

**Comment by unknownbrackets** [comment]
http://forums.ppsspp.org/showthread.php?tid=24949&pid=133406#pid133406

This person makes it sound like it's some sort of controller issue?

-[Unknown]

**Comment by hrydgard** [comment]
According to the latest posts it seems to be a regression from 1.6.3. Bumping priority to 1.8.0.

**Comment by Hacsev** [comment]
Will this issue ever get fixed? I saw a video on youtube from 2015 that managed to do sustained notes on Android. The top commenter posted two months ago that they are having the same issue of not being able to do sustained notes.

**Comment by unknownbrackets** [comment]
@Hacsev you could help significantly by trying to find when it stopped working.  Unfortunately, I don't think there's a history of Mac builds, but if you're willing to use Xcode (it's free from Apple, but a large download) you could try different versions to find out when the bug was introduced.

There have been around 8000 individual changes since 2015.  Since I don't experience the issue in other games, and don't have the Rockband game - that leaves me just staring at a haystack, wondering where the golden needle is.

You, in comparison to me, have a super power.  By testing one version half way between 2015 and now, you could eliminate 4000 of those changes as being the problem in one fell swoop.  You're the hero of this story - by testing just 14 different builds of PPSSPP, you would mow down all the small fry and find either the exact change that introduced this problem, or very close to.

It will probably be fixed eventually either way, but it'll probably be fixed a lot sooner if you're willing.

-[Unknown]

**Comment by unknownbrackets** [comment]
This is probably fixed now.  Can anyone confirm using the latest git build?

It's currently building so make sure to check 20 minutes after the time of this comment.

-[Unknown]

**Comment by Hacsev** [comment]
Well, I got up to this point and nothing was created:

[100%] Linking CXX executable PPSSPPQt.app/Contents/MacOS/PPSSPPQt
No such file: /Users/adminis/Downloads/ppsspp/build/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL!
make[2]: *** [PPSSPPQt.app/Contents/MacOS/PPSSPPQt] Error 1
make[2]: *** Deleting file `PPSSPPQt.app/Contents/MacOS/PPSSPPQt'
make[1]: *** [CMakeFiles/PPSSPPQt.dir/all] Error 2
make: *** [all] Error 2

**Comment by Hacsev** [comment]
I used ./b.sh and it built successfully. I tried Rock Band Unplugged and can confirm that the issue with long notes has been fixed.

**Comment by unknownbrackets** [comment]
Great, thanks for confirming.

The Qt issue is a separate bug, but probably this line:
https://github.com/hrydgard/ppsspp/blob/4c83d30b592f56f2cc1fdcdeb883276a4b2550f1/CMakeLists.txt#L1994

Should be `if(NOT USING_QT_UI)` or something.  Or maybe macbundle should support Qt...

Going to close this issue, though.

-[Unknown]
