### ISSUE TITLE
Burnout Dominator: Black screen in Ad Hoc multiplayer mode ready to play

### ISSUE THREAD

**Issue by kyousuke77** [hrydgard/ppsspp#11837]
screenshot:https://ibb.co/ZBhZzPn
Game:Burnout Dominator
Ppsspp lastest version from github
I'm trying to host ad hoc multiplayer,but it always showing black screen when entering "ready to play confirmation" screen

**Comment by kyousuke77** [comment]
for more detail 
https://imgur.com/a/AiXwDYw

**Comment by unknownbrackets** [comment]
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
