### ISSUE TITLE
Sorting saves by date makes ppsspp to crash

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#11892]
Using 1.8.0 x64 and you need to do something specific to make ppsspp to crash(maybe I have some problematic save)

1.Run ppsspp and maximize the window(with window size below 4x it will not crash)
2.Go to the Save Manager and try to sort by date the saves(not the save states)

If you scroll all the way down and then try to sort them,it will not crash and it will also not crash if you sort them first by size and then by date.
Going back after successful sorting  and into the saves manager again and resize them by date first,it will crash.

**Comment by unknownbrackets** [comment]
Hm, I can't reproduce, I'm not sure what could be wrong here.  If it's possible to run PPSSPP using Visual Studio and get a stack trace of the crash, that would help significantly.

-[Unknown]

**Comment by vsub** [comment]
I don't have Visual Studio but do you have a lot of saves.
It seems to be because of some save(or multiple saves)but the problem is I have a lot of saves for a lot of games and if the visible saves are less than 12,it will not crash
I tried removing all of the saves and save 18 times in only one game but ppsspp didn't crash

Here some random saves,it always crashes(some of the saves are done while using ppsspp 0.9.1(I tried limiting the number of saves as much as possible)
At maximized window,11 saves are visible without scrolling.
[SAVEDATA.zip](https://github.com/hrydgard/ppsspp/files/2974088/SAVEDATA.zip)

**Comment by unknownbrackets** [comment]
This is strange.  I can reproduce it now with that savedata.

When it crashes, it's happening because `SavedataBrowser::ByDate` (the std::stable_sort callback) was given a `v2` that is not a valid pointer (it's complete garbage, not even the wrong view), so accessing it segfaults.

It feels like another thread is somehow modifying the views_ vector, but I tried copying it and sorting the copy which did not help.  Adding:

```c++
	char temp[1024];
	sprintf(temp, "HELLO %p / %p\n", v1, v2);
	OutputDebugStringUTF8(temp);
```

To ByDate logs the wrong pointer, but adding more to that function stops the crash (again, making it seem like some threading/timing issue.)  Also, removing any significant amount of stuff inside ByDate stops it from crashing.  Moving the lambda to a static regular function makes no difference.

-[Unknown]

**Comment by vsub** [comment]
Now this is weird.
If I have only those saves in SAVEDATA from the archive and create a new save for any games while using 1.8.0,then it will not crash
Also if I delete that new save while using the saves manager=>exit the manager and go back in and try to sort,it will crash again

Sadly that don't work on the folder with all of my saves where I have 105 folders

**Comment by unknownbrackets** [comment]
Padding the `views` array with nulls doesn't help prevent the crash, and it seems to consistently crash on basically the data at `views[-1]`.  But now I realize the cause: the data is changing during the sort.  This causes the comparison func to fail the strict weak ordering test and then STL crashes.

-[Unknown]

**Comment by vsub** [comment]
Yes,it works on the folder with all of my saves,thanks
