### ISSUE TITLE
Graphical glitch on loading screen in Kingdom Hearts: Birth By Sleep

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp#11891]
Every time you leave the Mirage Arena there's a brief loading screen and this shows up on it. Happens with both Vulkan and OpenGL. Resolution on auto. Windows 7, i5, GTX 970.

![kh](https://user-images.githubusercontent.com/31968468/54426232-669abb00-476b-11e9-8657-f5a411896eaf.PNG)

**Comment by unknownbrackets** [comment]
This is the sort of thing that should be handled by simulate block transfer, and might have been to do with frameskipping.

Because the author of this issue has deleted their account and this is a fairly popular game, I'm going to close this hoping that it's been fixed.  If you're seeing this exact issue and reading this comment, please feel free to reply with details of your settings and PPSSPP version, and we'll reopen the issue.

-[Unknown]
