### ISSUE TITLE
(UWP) Doom Legacy Crash (Homebrew)

### ISSUE THREAD

**Issue by dominater01** [hrydgard/ppsspp#11895]
doom legacy is crashing in latest build 1.8.0-3

it used to be playable on build 1.4.2-199

i dont know why the uwp build specifically crashes

on the windows build for pc when i start it a dialog box says

http://oi67.tinypic.com/28vztsm.jpg

after loading doom.wad

maybe its crashing due to that arg

**Comment by unknownbrackets** [comment]
Hm, @hrydgard it seems that since MAX_LOG_LEVEL includes debug, `_dbg_assert_msg_` is now triggering on release.  Oops.

That said, I don't see any funcs with c in the argmask.  @dominater01 could you try changing that line to `_dbg_assert_msg_(HLE, false, "Invalid argmask character: %c (%s)", argmask[i], latestSyscall->name);` and see what it logs?  Have you customized any HLE functionality?

It would also help to find the build where it stopped working.  You can narrow it down a lot by trying in halves.

-[Unknown]

**Comment by dominater01** [comment]
im not sure what you mean, i dont know how to do that

**Comment by hrydgard** [comment]
@unknownbrackets  hah, yeah indeed (though that only applies for PCs where we generally have excessive CPU anyway so a few more asserts doesn't hurt - as long as they don't fire...)

I'll look into this one soon.

**Comment by dominater01** [comment]
i found another homebrew game that brings this up and more

https://www.youtube.com/watch?v=MvWSY-XlwrM

**Comment by hrydgard** [comment]
Turns out we indeed had a bad argument string for a function called kuKernelLoadModule which is only used by some homebrew.

**Comment by unknownbrackets** [comment]
Huh, I must've made some mistake in my grep string, darn.

-[Unknown]
