### ISSUE TITLE
Criminal Girls (Japan) graphic glitches 

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#11903]
v1.8.0-3-gd6d6dbb77
during gameplay there is green squares everywhere
happens on all the backends
here is a GE dump
[NPJH50316_0001.zip](https://github.com/hrydgard/ppsspp/files/2974721/NPJH50316_0001.zip)

![crimson](https://user-images.githubusercontent.com/2696404/54484491-0b6be400-48a3-11e9-82d9-b935c68e430d.PNG)

**Comment by unknownbrackets** [comment]
The green is the old problem with transparency "leaking".  Using texture scaling helps, but otherwise you have to run it at 1x or force texture filtering to nearest.

If you're interested in the technical reasons, see here:
http://forums.ppsspp.org/showthread.php?tid=13556&pid=96350#pid96350

The outlines around the shadows are incorrect too, which seems to be a depth issue for a related reason.  It also doesn't happen at 1x... except in the software renderer.  So there's a bug there.

-[Unknown]

**Comment by unknownbrackets** [comment]
Hmm.  It's probably not right, but if I start drawing offset by one subpixel (`ScreenCoords pprime(minX + 1, minY + 1, 0);`), it fixes it.  Otherwise, it's getting a subpixel offset in the texturing.  Somewhere we've got an offset, I guess..

-[Unknown]

**Comment by unknownbrackets** [comment]
Just a note, I was checking some dumps which were wrong in the software renderer before, and with #15279 this renders exactly (pixel for pixel) like the PSP does, now.

The only remaining issue is the linear filtering pulling in the green background color at higher render resolutions.  This game seems to draw entirely in throughmode, so I'm not sure there's much gain with > 1x PSP render resolution, anyway.

-[Unknown]
