### ISSUE TITLE
OutRun 2006 - Coast 2 Coast (USA) missing water 

### ISSUE THREAD

**Issue by benderscruffy01** [hrydgard/ppsspp#11928]
happens in both opengl and dx11 backend and have tried it with simulate block transfers effects both on and off
![outrun](https://user-images.githubusercontent.com/48821663/54876697-316b2880-4e4f-11e9-975f-01279c947329.PNG)
[DUMP.ZIP](https://github.com/hrydgard/ppsspp/files/3000157/DUMP.ZIP)

EDIT: This appears to be the same problem as https://github.com/hrydgard/ppsspp/issues/13012 (Dirt 2 water).

**Comment by unknownbrackets** [comment]
In one of the dumps, it seems like the water is drawn by 703/1355 from 0x041c45e0 (64x64).  For me, it only works in the software renderer.

There are a few suspicious things, but the direct problem is a stencil test (& FF == FF) not passing.  It's a 5551 buffer, but the stencil is zero in the hardware backends.

The stencil value is established by the 0x040d4000 (64x64) texture being drawn at 701/1355.  The texture looks radically different in the software renderer.

040d4000 is rendered to using 5551 several times in the beginning of the frame, but at 198/1355 it's drawn again using 5650.  However, as a texture it's indicated as 4444 (which makes the colors very vibrant, heh.)

The 701 draw uses an ALWAYS FF stencil test, so that's our one.  The alpha test is (a & 0xE0 == 0x20), in other words checking that the 0xC0 bits are not set.  From the original 5650, that's checking part of blue.

We're also not even binding the framebuffer because we're worried it might be a video or some other texture with a different format in RAM.  So currently, we're treating it as RAM instead... changing that could have unexpected (good or bad) effects in other games.

But that's not all.  It also uses RGB masking to draw this little helper texture, which is how it figures out the correct areas for water, etc.  And also various logic ops too (draws 198 through 202.)

-[Unknown]

**Comment by theboy181** [comment]
I noticed that when its working you can change the resolution multiplier, and it will break immediately. Its such a great looking game so I do hope it gets fixed soon.

```
_S ULES-00262
Date: 9-2-2019
_G OUTRUN 2006: COAST 2 COAST [Public Version 1.1]
_C1 Enhanced GFX v1.0
_L 0x200BCA84 0x1000000F // Car Level of Detail Max
_L 0x203034D4 0xC47A0000 // Max Draw Distance
```

**Comment by Panderner** [comment]
![Screenshot_2020-04-02-10-36-30-97_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/78205193-1dc8b800-74ce-11ea-89ee-21e06e1ad15a.png)
The water is no longer black but it's incorrect on lastest version

**Comment by velezsarain** [comment]
About what the previous comment said, the water is completely missing in both the latest PC and Android builds. Maybe the picture was taken in a different stage where the water does not disappear?

**Comment by hrydgard** [comment]
Seems the water works in some stages but not others.

**Comment by Panderner** [comment]
PPSSPP:
![Screenshot_2020-11-17-19-10-34-41_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/99383275-974fd200-2908-11eb-8254-6378a37d318c.png)
Software Renderer:
![Screenshot_2020-11-17-19-03-05-96_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/99383335-aa62a200-2908-11eb-9960-45451e28bd28.png)

it seems the water has graphical glitches.

**Comment by inukaze** [comment]
![001](https://user-images.githubusercontent.com/1647332/147380485-0e5a0253-7086-44d5-a3b2-8365648a8df3.png)

Importing the GFX Hack Activating :
![002](https://user-images.githubusercontent.com/1647332/147380487-35c27999-e78d-43d3-93ff-abf29b95c910.png)

Restart the game and test : 
![003](https://user-images.githubusercontent.com/1647332/147380527-b5a4cd82-964f-4301-b85c-92c323382d54.png)

**Comment by Panderner** [comment]
Outrun 2006 and Dirt 2 are using same engine that does not render water properly in hardware renderers as mentioned in https://github.com/hrydgard/ppsspp/issues/13012

Screenshots from software renderer:
![Screenshot (2)](https://user-images.githubusercontent.com/37503397/181270591-d35d77af-bead-48f9-90d9-f1615235c2d7.png)
![Screenshot (4)](https://user-images.githubusercontent.com/37503397/181270614-fe0b5aa1-67d1-467b-887d-d623c7d0fc20.png)

GE dumps:
[ULUS10471.zip](https://github.com/hrydgard/ppsspp/files/9199866/ULUS10471.zip)
[ULUS10064.zip](https://github.com/hrydgard/ppsspp/files/9199867/ULUS10064.zip)

**Comment by inukaze** [comment]
Hi there, well sorry but in the PAL version [ ULES00262 ] of OutRun 2006 the issue persist :

Well i can't use any another thing except « OpenGL »
![PPSSPP-v1123-PAL-OutRun2006-001](https://user-images.githubusercontent.com/1647332/182004672-c94a0299-3ba9-4f1c-ac35-a5ce30b6dd89.png)

The Water still render : 
![PPSSPP-v1123-PAL-OutRun2006-002](https://user-images.githubusercontent.com/1647332/182004680-06f9a737-f234-44ad-813a-78f308d396bc.png)

![PPSSPP-v1123-PAL-OutRun2006-003](https://user-images.githubusercontent.com/1647332/182004688-f3152d3a-ca47-45c8-bfe1-94963af7296a.png)

On the « Desert Stage » near entrance in the right side, the water looks completly in blank

Dunno : Is not possible make the PPSSPP emulator print the Game Serial on the title window like for example : 
PPSSPP v.1.12.3 ( ULES00262 ) ?

**Comment by Panderner** [comment]
> Well i can't use any another thing except « OpenGL »

@inukaze what device are you using?

**Comment by hrydgard** [comment]
Not gonna matter right now which device you're using, there's something still going fundamentally wrong here, even now after fixing all the framebuffer reinterpret stuff. I will look into this again soon.

**Comment by unknownbrackets** [comment]
I should've read this one again, I noticed it used logic ops here, years ago.  It's pretty clear this is the same underlying issue as #13012 at this point.

-[Unknown]

**Comment by hrydgard** [comment]
Note: Not yet fully fixed on all platforms. D3D11 and OpenGL ES coming up. Keeping closed, since the mystery is solved.
