### ISSUE TITLE
Networking crashes when server IP is not reachable

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp#11920]

**Comment by ToppestOfDogs** [comment]
My bad, I didn't realize the default server IP doesn't work, and then I tried a different server that also wasn't working,
It's fine on a working server.

**Comment by unknownbrackets** [comment]
A lot of networking issues have been improved since this issue was created.  Since the author has deleted the account, I'm going to close hoping the issue is fixed.

If you're seeing the same issue, and you're sure it's because of the server IP being unreachable, please comment and we can reopen.

-[Unknown]
