### ISSUE TITLE
Homebrew game "strife" seems to be stuck in game

### ISSUE THREAD

**Issue by dominater01** [hrydgard/ppsspp#11939]
when starting up the game everything is fine til in game you can hear music but you cannot move what so ever

this isnt a problem with the game its how its emulating it

and as far as i know im not missing any files

http://www.mediafire.com/file/6ibpn83i1jajpyu/PSP-STRIFE-R1.7z/file

game gets stuck at this screen
![Untitled](https://user-images.githubusercontent.com/8470028/54995999-88cbde80-4f9e-11e9-8874-d69951766649.png)

**Comment by dominater01** [comment]
here's a video on how the game should run 
https://www.youtube.com/watch?v=5bGfU57F06Q

**Comment by LunaMoo** [comment]
Seems like it fails to save / can't open or create some of it's files, the video shows that the game saves on loading the level before allowing the player input and that fails here hence it's stuck in a loop trying to save.

**Comment by LunaMoo** [comment]
I tested my theory above and the game does run if I fake sceIoOpen success or at least if I nop the branch that checks for sceIoOpen to fail allowing the game to run, through fail at saving.

 Maybe it's because the path has a dot in folder name and lacks a dot in file name or it's just too long? It's:
````
ms0:/PSP/GAME/PSP-STRIFE-R1/savegames/strife1.wad/strfsav0.ssg/current
````
