### ISSUE TITLE
Function wrapper "WrapI_IVVVVUI" doesn't return correct pointers

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#11957]
I can't figure it out and don't have more time to try today, so opening a new issue.
This template is used only by one function ~ sceNetAdhocPdpRecv which currently breaks "Obscure" adhoc causing freeze in PPSSPP, while I was checking it, the debug log from the start of that function get's incorrect values for 4 included pointers like for example 0000024EE986F532 instead of the correct address which in this case was 09FFF532, it's like they all get increased by some very high value ~ actually now while I think about it, it might simply be pointing to address in RAM instead of PSP memory, either way this causes bad things and freezes PPSSPP completely.

Edit: yeah the values it get's are increased by base in physical memory, but I think that whole function "sceNetAdhocPdpRecv" is messed up in more than one way. Blah;3.

**Comment by hrydgard** [comment]
Maybe we simply have the function signature wrong?

**Comment by unknownbrackets** [comment]
The "V" means a `void *` which would be a host pointer (i.e. 0000024EE986F532) rather than a PSP pointer (i.e. 09FFF532.)  It basically calls GetPointer automatically.

The log line using `sceNetAdhocPdpRecv(%i, %p, %p, %p, %p, %i, %i)` is not useful.  It should probably switch to using `hleLogSuccessI` and `hleLogError` etc. to get the args right.  That will log the original argument value (i.e. 09FFF532) rather than the host/C pointer.

-[Unknown]

**Comment by unknownbrackets** [comment]
I'm going to close this - I think there's an issue with that function, but it sounds like it's more likely we have the signature wrong than that the template is wrong.

-[Unknown]
