### ISSUE TITLE
Cheats not working Xiaomi Black Shark 2 SD 855 ANDROID

### ISSUE THREAD

**Issue by mrtawsiti3** [hrydgard/ppsspp#11968]
### What happens?
ANDROID, It doesn't create Cheats folder and when i create it manually and put cheats file all set, it doesn't show cheats, all blank. Works on windows but doesn't work on Xiaomi Black Shark 2

### What *should* happen?
When you pause game and click on Cheats they should appear on the right side since they are added properly by making folder PSP/Cheats and putting .ini file with proper game ID and text of code in it.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Snapdragon 855, Octa-core (1x2.84 GHz Kryo 485 & 3x2.41 GHz Kryo 485 & 4x1.78 GHz Kryo 485) CPU with Adreno 640 GPU, Android 9, PPSSPP Gold 1.8.0.

**Comment by mrtawsiti3** [comment]
Textures are also not working, the same exact thing as cheats

**Comment by LunaMoo** [comment]
You should not need to create a PSP/Cheats folder, if you launch any game with cheats enabled it would create the path and empty ini file already. Probably files are stored in different place on your phone than you're expecting to because the naming of the drives and locations on android can vary between vendors.

**Comment by mrtawsiti3** [comment]
Yes i changed memstick folder location. Closing thread, thanks.
