### ISSUE TITLE
Random crashes when loading screen triggers on Pump It Up Exceed Portable

### ISSUE THREAD

**Issue by armenlokota** [hrydgard/ppsspp#11975]
I'm getting random crashes when the loading screen on pump it up exceed portable triggers, it doesn't always crash, but after 3, 4 or 5 times the loading screen triggers the whole PPSSPP crashes. Debug console shows this right before PSSPP shuts down:

![image0](https://user-images.githubusercontent.com/30017287/56235005-1786c500-604c-11e9-9e46-a8275081408a.jpg)

I'm using PPSSPP 1.8.0 on windows 7 on a desktop PC with default PPSSPP settings.

**Comment by unknownbrackets** [comment]
Not sure, someone reported that this game was running well:
https://report.ppsspp.org/game/ULKS46042_1.02

I'd suggest checking your CRC against the one that worked well there.  It could be a bad copy of the disc, or one with modifications that cause it not to work.  Best bet is to take a clean copy from a real disc.

It could be a bug these people didn't notice, though.  Does the same thing happen even with the latest git build?

-[Unknown]

**Comment by armenlokota** [comment]
Gameplay works right while songs are playing, but the crash happens when I exit to the main menu and try to select another game mode or option. I've tried 3 different copies of the iso so far, one of them ripped directly from my brother's umd. I just tried the latest git build and still the same random crash when the black screen with the circle in the corner attempts to start. I also tried on the new switch port and it does exactly the same, I also tried previous versions of ppsspp and it also crashes. At the end of the BREAK! error on the log it shows this:

![Capture](https://user-images.githubusercontent.com/30017287/56273794-18a70900-60c3-11e9-87c7-7dfb0f454e32.PNG)

**Comment by armenlokota** [comment]
Yeah I'm sorry heh. Plesea tell me if you need some other file, test or info. Here's the full log of the crash:
[mylogfile.txt](https://github.com/hrydgard/ppsspp/files/3091220/mylogfile.txt)

**Comment by armenlokota** [comment]
New update, I tried the game in an old ppsspp version I had lying around and I can't seem to reproduce the crash, seems like the issue doesn't exist there. This is the version I tried:
![ppsse](https://user-images.githubusercontent.com/30017287/56391323-f5c84200-61f3-11e9-82d6-0b77d6d77307.PNG)

**Comment by hrydgard** [comment]
In that case, I think you know what to do: try intermediate versions until you've found the change that broke it.

**Comment by unknownbrackets** [comment]
`sceKernelStopUnloadSelfModuleWithStatus` mostly means life got so bad for a game, it decided to jump off a ledge.  I guess the `sceKernelWaitThreadEnd` error is related, but the log doesn't explain much unfortunately.

I don't have this game, but if you check by halves it'll go fastest to see when this broke.  We've made 13,198 changes since v0.9.8, and probably just one of those changes broke the game.

Since I don't have the game, my only hope is to play the lottery and hope I can figure out which of those 13k changes caused the problem.  However, you're the hero of this story: by testing just one version (for example v1.1.1), you could half that number.  I'd be fighting the small fry for years, but you can brush them aside like the nothing they are.

If the change is recent enough that it's still available here (meaning, if v1.4.2-390-g97b82100b or older work):
https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

Then you can probably narrow down almost exactly where it broke by only trying 11 versions or so.  With the enemy cornered, then even side-characters like me could help defeat the final boss.

-[Unknown]

**Comment by armenlokota** [comment]
Thank you so much for helping :) I'm also happy to contribute with my grain of sand to this great project of yours.

I've discovered something weird, when I try to run the ppsspp v0.9.8 from the releases section the game doesn't even run well, it's unplayable, so slow, I counldn't get to try the game on the normal v0.9.8 due to that. Slowness gets fixed on v0.9.9, I tried to reproduce the crash and it happened. This is the log of the crash on v0.9.9:
[mylogfile9.9.txt](https://github.com/hrydgard/ppsspp/files/3096976/mylogfile9.9.txt)
I also took a screenshot so you can see where the red text is:
![log](https://user-images.githubusercontent.com/30017287/56404913-13ff6380-622f-11e9-9fd4-105367fd67f3.PNG)


I assume the crash didn't happen before v0.9.9. The revision where the crash doesn't happen is v9.8-561-561g2b50fcb. Here's the log of me trying to reproduce the crash on that version. The code way too long and repeats itself a lot since it's just me trying to trigger the crash by selecting the options that activate the Loading screen (Black screen with a circle spinning in the corner).

[mylogfile9.8-561-561g2b50fcb.txt](https://github.com/hrydgard/ppsspp/files/3097001/mylogfile9.8-561-561g2b50fcb.txt)

And here's the screenshot with colors, basically the log is that chunk of code repeating itself several times:
![log2](https://user-images.githubusercontent.com/30017287/56405431-d223ec80-6231-11e9-84c1-74825ed9704b.PNG)

Sorry if I mispelled or wrote something you don't understand, my english is not that good. But feel free to ask me whatever additional info. you need.

**Comment by unknownbrackets** [comment]
Thanks, that's helpful.

So the working version does this:

```c++
19:21:445 displayThrea W[ME]: HLE\scePsmf.cpp:1290 scePsmfPlayerReleasePsmf(098bfb44)
19:21:446 displayThrea I[KERNEL]: HLE\sceKernelThread.cpp:2303 sceKernelExitDeleteThread(0)
19:21:446 user_main    I[ME]: HLE\scePsmf.cpp:1237 scePsmfPlayerDelete(098bfb44)
```

While the not working one does this:

```c++
01:18:477 displayThrea W[ME]: HLE\scePsmf.cpp:1429 scePsmfPlayerReleasePsmf(098bfb44)
01:18:477 displayThrea I[KERNEL]: HLE\sceKernelThread.cpp:2292 sceKernelExitDeleteThread(0)
01:18:477 user_main    W[KERNEL]: hle\sceKernel.h:459 Kernel: Bad object handle 318 (0000013e)
01:18:477 user_main    E[KERNEL]: HLE\sceKernelThread.cpp:2753 sceKernelWaitThreadEnd - bad thread 318
01:18:477 user_main    I[IO]: HLE\sceIo.cpp:845 stderr: assertion "false" failed: file "../../psp/movie.cpp", line 173
```

318 is the displayThread:

```c++
01:08:869 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2114 318=sceKernelCreateThread(name=displayThread, entry=0883f454, prio=11, stacksize=2048)
```

So I think it's because of the `sceKernelWaitThreadEnd()` result.  I think that the issue here is related to the fact that HLE threads can "last" a tiny bit of time before they actually get deleted.  The range 2b50fcb...v0.9.9 added an HLE thread for handling Psmf more accurately, but this probably affected the timing of the thread delete.

Had forgotten that the thread delete thing wasn't emulated yet, but this looks like a probable case where that's needed.

-[Unknown]

**Comment by armenlokota** [comment]
That sounds a bit complex for my basic php skills 😅 
But please let me know how I can help and I'll at least try :)

**Comment by Panderner** [comment]
Great! good news. This game no longer trigger random crashes when i play this game for 10 minutes of repeated loading screen triggers.

**Comment by shenweip** [comment]
Oh, thanks for your patient test.
