### ISSUE TITLE
Black Shark 2 playing online not working

### ISSUE THREAD

**Issue by mrtawsiti3** [hrydgard/ppsspp#11973]
### What happens?
When i set everything up, same settings tried with 2 different phones, 1 works and other don't, it doesn't work online, it works fine on my Xiaomi Pocophone F1 but on Black Shark 2 it can't go online.
### What *should* happen?
It should work on Black Shark 2 just like it works on my other phone since it has all same settings. 

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Snapdragon 855, Octa-core (1x2.84 GHz Kryo 485 & 3x2.41 GHz Kryo 485 & 4x1.78 GHz Kryo 485) CPU with Adreno 640 GPU, Android 9, stock android, PPSSPP Gold 1.8.0.

**Comment by adenovan** [comment]
not a bug as i can play with blackshark 2 normally @unknownbrackets

**Comment by unknownbrackets** [comment]
Okay, maybe this is related to security settings on the device or a wifi problem.

Does the latest git build work for you, @mrtawsiti3?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
