### ISSUE TITLE
Feature Request: Add VR through OpenXR

### ISSUE THREAD

**Issue by newblar** [hrydgard/ppsspp#11979]
Would be a fun feature but probably would only be used by small portion of people.

**Comment by unknownbrackets** [comment]
This would just be like the Google Cardboard feature where it's a silver screen, right?

There are many barriers to full VR support, not the least of which that PSP games often don't render outside the forward visible area by default.

-[Unknown]

**Comment by newblar** [comment]
It is an open standard being developed to work with any VR headset that exposes the api. Developed by the same company that develops Vulkan with the aim to reduce fragmentation.   https://www.khronos.org/openxr

**Comment by hrydgard** [comment]
Unlike past APIs, OpenXR has a structure and licensing that makes it fully usable from GPL software. Since finally (since a few weeks) both Oculus and SteamVR support OpenXR (SteamVR in beta), we now indeed have a workable way to do VR without possible legal issues.

However, it's very much not an easy task and PSP games are generally not really suitable for VR. There was some work before with some other VR API, not sure whether that code is still around somewhere, and could be ported to OpenXR?  It's probably quite bitrotted by now...

**Comment by unknownbrackets** [comment]
#15901 was just merged and marked as resolving this, so I'm going to close.  It probably needs to be allowed on more platforms, but the initial work is there.  Thanks @lvonasek.

-[Unknown]
