### ISSUE TITLE
Black screen when launching LBP on iOS

### ISSUE THREAD

**Issue by flre** [hrydgard/ppsspp#11987]
### What happens?
I try to launch LBP (nostalgia), and all I get is a black screen. Been trying to fix for an hour.

### What *should* happen?
the game should launch??

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
I’m on an iPhone X, iOS 12.1, and jailbroken.

**Comment by unknownbrackets** [comment]
iOS has a lot of unique issues and isn't as well supported.

You can try changing to IR Interpreter in developer settings.

-[Unknown]

**Comment by unknownbrackets** [comment]
Did changing the CPU core help?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
