### ISSUE TITLE
ppsspp android studio build - how to automatically launch iso file without main menu ?

### ISSUE THREAD

**Issue by aatopanrizky** [hrydgard/ppsspp#11982]
i want to create ppspp game apk directly using iso in asset folder
how to launch iso file in asset folder without select it in main menu for android so its just like apk with ppsppp iso directly playing
i want to build with android studio.
can i do it ?

**Comment by LunaMoo** [comment]
If you don't want to use widgets to launch games - you can do this - https://github.com/hrydgard/ppsspp/issues/11967#issuecomment-482862941 also note PPSSPP has command-line settings to leave when entering menu or leave from pause menu if you would also avoid entering PPSSPP interface and make it appear as normal non emulated game limited to preset settings.

**Comment by unknownbrackets** [comment]
I would recommend using a widget if you can, though.

I'm going to close this as it's more of a question [for the forum](http://forums.ppsspp.org/) rather than an issue, but feel free to reply here if you run into problems.  Note that the contributors who reply to issues here generally also look at the forum and reply there too.

-[Unknown]

**Comment by aatopanrizky** [comment]
hi do you know ho to do that ? what code i need to change

**Comment by unknownbrackets** [comment]
Check #11967 if you want to do this via code.

But you can also just use Android widgets which don't require any code changes.  They let you just add icons to your Android start screen that start certain games directly.

-[Unknown]

**Comment by aatopanrizky** [comment]
ok thanks you i will try this , if i have error can i discuss again ?
thanks you dude
