### ISSUE TITLE
Black screen on pspkvm with skip buffer effects

### ISSUE THREAD

**Issue by InfamousKnight** [hrydgard/ppsspp#11994]
So, a fork of ppsspp https://github.com/clementgallet/ppsspp/ has a new setting called enforcesinglethreaded which makes it deterministic with libtas. Hurray.. but not all games work with rendering set to 0.

With pspkvm, nothing but a black screen comes up with rendering set to zero and single threaded mode.

Is there anything that can be done about this? Do we have to resort to hacks just for tasing?

**Comment by LunaMoo** [comment]
In case of problems with non-buffered rendering we can only inform the user about it which we already do in more popular games via RequireBufferedRendering compat option, however it's not worth adding homebrew to that since they don't use proper game ID and we have to generate an unique one based on it's path which will be different depending on the user calling it.
 
 Either way skipping buffer effects is a hack, a nasty hack which does work ok-ish in some games and was kept for performance on bottom end devices, it will never work with all games causing in extreme cases black screen and in most other games will cause some effects to go missing.

 Closing and marking as non-issue.

**Comment by unknownbrackets** [comment]
We know there are issues with what that fork is trying to do, and simply commenting out asserts because they are saying "oh no, lots of assumptions in this code are being broken" won't make that go away.

If someone wants to create a fork of PPSSPP that is single threaded, and that will both be slower than PPSSPP and hard to bring compatibility improvements from the main PPSSPP into - then you should report issues with that to them.

-[Unknown]
