### ISSUE TITLE
Problem with installed.txt and other issues when using installer on windows 10

### ISSUE THREAD

**Issue by Drakkhonian** [hrydgard/ppsspp#12000]
### What happens?
When using the windows installer to update my ppsspp, my installer.txt gets overwriten everytime, wich i assume can be intended behaviour.
But it also doesnt exactly respects my choices to where i named it to install.
And when i tried to load a game in the new version, and then decided to change the installed.txt inside the setings with the game open, it literally zeroed one of my games cheat file.
Not only that, when i remove the option to load from installed.txt and try to set it again, ppsspp makes a randomish named folder for either the memstick or a new PPSSPP or PSP or PSPPSP somewhere inside the directory.

so namely:

1 opened the installer;
2 told it to install in G:/ppsspp_win/ppsspp/ (chosen from the browser inside the installer)
3 it installed inside G:/ppsspp_win/ppsspp/PSP/ AND it destroyed my installed.txt on the previous folder
4 copy and pasted the new installed version over the old one
5 tried to open ppsspp, still showed last played games so loaded my last one
6 didnt show and save states or cheats on
7 went to settings to set new installed.txt
8 when set on the old /memstick/ folder i was using before it zeroed the cheats on the game that was open
9 when i check the folders inside my ppsspp directory i realize new folders were created (namely PPSSPP and PSPPSP)

Edit 1: got the order of pics wrong

![before seting installed txt](https://user-images.githubusercontent.com/50035741/56843245-a5488880-6874-11e9-8864-97523852be56.png)
![before setting installed txt 2](https://user-images.githubusercontent.com/50035741/56843247-a7aae280-6874-11e9-80f0-83639f3e3b78.png)
![setting installed txt](https://user-images.githubusercontent.com/50035741/56843251-aa0d3c80-6874-11e9-8ac9-a2a8717cc61f.png)
![after setting installed txt](https://user-images.githubusercontent.com/50035741/56843253-ac6f9680-6874-11e9-9dc1-a12e8d611784.png)

Edit 2: While doing this test i also noitced this

![after seting installed txt 2](https://user-images.githubusercontent.com/50035741/56843329-8c8ca280-6875-11e9-8596-72a603b9d328.png)

ppsspp froze when closing and suddenly a memstickPSP folder was created....
Edit 3: and i realized it also DELETED my intalled.txt
guys please, this is major issues here, file handling and directory issues should be basics for it to work...

### What *should* happen?
 What i think SHOULD happen is ppsspp should do a better job at reading a folder that already exists, or at least give us the option to change that folder anytime without using a "installed.txt" file or without defaulting it to documents folder.
Also in the installer, ti should give us total control to where to install and give us the option to overwrite on where im installing, and not deleting my installed.txt, AND giving us an option to retain the configuration of the already installed version. Basically a previously installed detection system for the windows installer.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

ppsspp 1.8.0 but ive had this problem since ppsspp 1.4 where file directories get scrambled.

Edition: Windows 10 PRO
Version: 1703
OS Build: 15063.1387
Processor: AMD A10-9700 RADEON R7, 10 COMPUE CORES
RAM: 8.00 GB (5.93 Usable)

**Comment by LunaMoo** [comment]
Apparently you're the first / only person affected by this issue.


 Some notes:
 - PPSSPP by default doesn't even come with installed.txt, this is only created by installer and option in the system settings menu. Most people wouldn't ever use installer since it's pretty pointless and takes much longer time than simply extracting files via 7z or whatever other software.
 - Empty installed.txt in ppsspp executable folder will default to "my documents" because reasons I'll explain below.
 - Valid path in installed.txt will cause PPSSPP to try and use that path as memstick folder.
 - Without installed.txt PPSSPP will try to keep memstick in it's executable directory.


 I used word "try" because PPSSPP tests if it can write to selected directory before actually bothering to write actual files, if it fails it ends in "my documents" that's also why default with empty installed.txt is inside "my documents", because in modern windows this is the only place you always should have rights to write and installer would commonly only be used by people who have no clue about pc's and might have very limited rights on their user account(common case - parents limiting user account for their kids).

 Just to make it clear - changing memstick location WILL NOT move nor remove any existing files, they would simply be in different directory than you selected.

 I suspect you might have 2 different problems here, but it's just a quick guess:
 1) potentially installer is just dumb if you really selected one folder and it saved path to a different one, wouldn't be that surprising since it's really not maintained with most people not caring about it at all, it's actually very rare for emulators to come with an installer and typical emulation fans have no use for it,
 2) you're continuing to mess around installed.txt or other settings after changing that with PPSSPP running and weird things happen.


 No idea about the first problem, but in case of the second one maybe we need to force restart after using the option to change the installed.txt. As for now if you use that option restart PPSSPP right after and if you want to mess with installed.txt file in any other way, you should close any running instance of PPSSPP before doing it, hopefully that solves the weird folders like PSPPSP or memstickPSP, not sure through as it might be something specific to your system causing it. If you want to just use PPSSPP directory to store memstick folder I would recommend to simply remove installed.txt completely.

**Comment by unknownbrackets** [comment]
It sounds like what might've happened here is:

1. Have cheats in folder memstick1.
2. Reinstall PPSSPP, which points to memstick2.
3. Start game and realize cheats aren't working.
4. Pause game, and change path in settings menu to memstick1.
5. PPSSPP remembers empty cheats and saves back to memstick1 at some point.

There are other issues here, like probably the installer should not overwrite installed.txt if it already exists.  But focusing on what I described above (which was also described on Discord):

1. Changing memstick paths while a game is running is likely to be broken.
  1.1. Creating an internal save state and loading it would at least avoid a mix of old still-open files and new missing files, but I'm not sure it would be what users expect.
  1.2. Ultimately, I think the most obvious behavior will be to not allow users to change the path without exiting the game first.

2. The UI that updates the cheat file is probably involved here.
  2.1. Maybe it should have an explicit save action, instead of autosave on exit?
  2.2. If it does autosave on exit, maybe it needs to compute a checksum on load, and verify the file was not modified on save.
  2.3. In general, it seems like this would improve a class of issues (such as editing cheats via a text editor -  see #6356.)

-[Unknown]

**Comment by unknownbrackets** [comment]
Also, I wonder if we even want the installer to mess with installed.txt anymore.  I seem to remember that was needed when didn't auto-detect that it couldn't write to the directory it was running in.

Now that it does, maybe that's the easiest way to make sure previous installed.txt settings are preserved when running the InnoSetup installer.

-[Unknown]
