### ISSUE TITLE
[Regression] Recoverable periodic softlocks excepting music in Wolf3D homebrew

### ISSUE THREAD

**Issue by pal1000** [hrydgard/ppsspp#12002]
Get Wolf3D homebrew from [here](https://www.brewology.com/downloads/download.php?id=9730&mcid=1)
Save game to roam free the level and reproduce more easily:
[sodssav.zip](https://github.com/hrydgard/ppsspp/files/3124331/sodssav.zip)
Save is from spear of destiny shareware version included with homebrew.
### What happens?
Game softlocks after some time (2-5 minutes) and it recovers after more time passes (1-3 minutes)
### What *should* happen?
This shouldn't happen.
### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
CPU: Intel Core i3-2375M;
GPU: Intel HD Graphics 3000
Windows 10 v10.0.18362.86 (Release preview)
Known good: v1.8.0-102-g 057e720b2
Known bad: v1.8.0-105-g dcd2ff03b
This seams to be a JIT issue considering where bisecting with Orphis buildbot led me and most likely culprit is #11971

**Comment by LunaMoo** [comment]
Seems that to some extent it might affect all homebrew that depend on time to set framerate.

**Comment by LunaMoo** [comment]
My ancient fix still works to solve this issue:
https://github.com/hrydgard/ppsspp/commit/6827ed3fef6c719ffc9b7fc37a64aa57ad25ae9d
that's the one which was replaced in #9716 as a fix for similar issue in the past. (BTW it's cool that github shows now old replaced commits ;o I would not remember about it otherwise)
