### ISSUE TITLE
PPSSPP (Standalone) crashes because Vulkan being default backend

### ISSUE THREAD

**Issue by RokkumanX** [hrydgard/ppsspp#12038]
Hello everyone!

I'm on Windows 10 Enterprise LTSC 2019 x64 with these specs:

i7 8700K
Nvidia GTX 1070 6GB
16GB RAM

When using PPSSP for the first time and then close it without changing anything, it crashes.
It also crashes when changing backend from the GUI when I apply the prompt for restart.

It seems PPSSPP is using Vulkan these days as the default Graphics Backend and this issue never happened when OpenGL was default (maybe it did since I'm always using OpenGL)

If I change the GraphicsBackend option in the ppsspp.ini from 2 (Vulkan, default) to 0 (OpenGL) I don't have a single issue anymore and PPSSPP don't crash at all.

I don't even use Vulkan so I probably is missing something and that's probably why it crashes.

Why was the default OpenGL option changed to Vulkan to begin with?
(I have no problem changing a number from 2 to 0 every time I want to try a new version out in the ppsspp.ini but I'm just wondering)

Thanks in advance!

EDIT:

Maybe a check could be done on first startup depending if you can use Vulkan or not, in my case since I don't use Vulkan and never will, PPSSPP could default to OpenGL instead and Vulkan for those that have it.

**Comment by hrydgard** [comment]
After 1.8.0, PPSSPP doesn't actually default to Vulkan, so that shouldn't be the issue. Instead it defaults to D3D11...

**Comment by RokkumanX** [comment]
No I haven't had an AMD GPU since 2016, and I always use the latest Nvidia drivers.

OpenGL works solid once changed to.

It's a strange issue but nothing game breaking.

**Comment by unknownbrackets** [comment]
Vulkan crashes can also be caused by using outdated Intel drivers (maybe for an integrated GPU, may have been initially installed with drivers for chipset even) or having certain tools like GeDoSaTo installed.

But yes, due to the general instability (on mobile too, with the popular Adreno 5xx line and others) we switched away from Vulkan as default.  It's a shame.

You can also freely reuse ppsspp.ini between versions.

We actually do start a separate process (due to bad AMD drivers), and try to use Vulkan in that process.  If it crashes or fails, we don't even let you select Vulkan.  Is this working for you in the latest versions (working would mean, not allowing you to even select Vulkan in the UI)?

-[Unknown]

**Comment by RokkumanX** [comment]
An update on this!

I deleted the ppsspp.ini and the controls.ini starting over completely with a fresh configuration and I must say what I experienced yesterday must have been a complete fluke.

I could change between and restart with every single Graphics Backend and both Vulkan and D3D11 played games OK (I didn't even know I could use Vulkan to begin with)

I can't replicate what happened yesterday at all anymore so I think I'm going to close this issue.

Thanks for everything!
