### ISSUE TITLE
Texture Replacement: We should support .basis image format for fast texture loading

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#12059]
.basis is a new compressed image format that's basically a subset of ETC1, which can be very quickly transcoded into BC1 (DXT1) or ETC compression formats. This means that files in this format can nearly directly use native GPU compressed texture formats on both desktop and mobile.

This is pretty much ideal for us since for texture replacement we want a format that both loads fast and is efficient (takes little VRAM and texturing bandwidth) on the GPU. Basis can be transcoded to native GPU texture compression formats faster than you can load either PNG or JPG.

Here's the repo:

https://github.com/binomialLLC/basis_universal

and the blog post:

https://opensource.googleblog.com/2019/05/google-and-binomial-partner-to-open.html

**Comment by unknownbrackets** [comment]
Of course, a lot of PSP textures use alpha so it'll need to either use the alpha formats or do something to tie the alpha back together again/blend it when sampling if the alpha is in a separate texture layer.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, it always be a texture-by-texture choice. But lots of textures don't use alpha, and in the future Basis will also support alpha where possible.

**Comment by AkiraJkr** [comment]
I suggest waiting until it really has alpha support, and image viewers support it, since no one will be able to work with that new format if they don't know what the result looks like.

**Comment by LunaMoo** [comment]
You can use basis tool to get the result back into png file for preview, there's no need for viewing the format directly.
````
To unpack a .basis file to multiple .png/.ktx files:

basisu x.basis
````

 As for alpha doesn't it already support it? Just lacks some texture formats which are incoming/will be added soon? The demo has alpha(alpha3.basis) althrough loads example without alpha(kodim20.basis) by default also:
````
Here are the major texturing scenarios we support today:

For color-only textures, you can transcode to whatever format your target device supports. Remember that PVRTC1 requires square power of 2 size textures, and there's nothing Basis can currently do to help you work around this limitation. (Basic supports non-square PVRTC1 textures, but iOS doesn't.)

For alpha textures, you can create .basis files with alpha channels. To do this with the basisu compressor, either create 32-bit PNG files with alpha, or use two PNG files with the "-alpha_file" command line option to specify where the alpha data should come from. (For texture arrays, you can use multiple -file and -alpha_file command line options. Mipmap generation automatically supports alpha channels.)

Now deploy like this:

ETC1 only devices/API's: Transcode to two ETC1 textures and sample them in a shader. You can either use one ETC1 texture that's twice as high, or two separate ETC1 textures.

ETC2 devices/API's: Just transcode to ETC2 EAC RGBA, which the transcoder supports.

PVRTC1 devices/API's: Transcode to two PVRTC1 4bpp textures, and sample twice. We're working on adding PVRTC1 transparency support to the transcoder ASAP (but quality will definitely suffer a bit)

Devices/API's supporting only BC1-5: Use BC3, which the transcoder supports.

Newer devices supporting BC6H/BC7: You still need to transcode to BC3. We will support BC7 with transparency very soon, which will give you slightly higher quality.
````

 Either way it'll be nice to see how it performs for replacement as that's the most important part.

**Comment by RadarNyan** [comment]
>  can be very quickly transcoded into BC1 (DXT1) or ETC compression formats.
>  we want a format that both loads fast and is efficient

Then why not just use  BC1 (DXT1) or ETC directly? Although "very quickly" it still needs to be transcoded right?

So it works like this:

1. Originally we have the textures in common image formats (like .png)
2. Convert them to a uncommon format t**hat can't be directly viewed/edited**
3. Have textures in that format transcoded to a format can be used by GPU...

Why have this "middle format" in the first place? What benifit does it add? I'm confused.

**Comment by LunaMoo** [comment]
Much faster transcoding to various texture formats without being limited by platform. Also you think about this all wrong. Png's could still be used for creating texture packs, just when you'd like to release it, you would generate a texture pack with much more efficient format to get rid of some stutter.

**Comment by hrydgard** [comment]
Yeah, this middle format can be transcoded super fast, directly while uploading to the GPU. The major advantage is that you only need one set of files for both PC and mobile.

A new higher-quality version is on the way way too, which also can transcode to ASTC and BC7 if available, and looks really really good. 

Anyway, there are still lower hanging fruit to fix, like background pre-loading and so on which could also help with stutters...

**Comment by RadarNyan** [comment]
To clarify, I don't have anything against .basic, I just don't think "fast texture loading" is the correct use case of it.

#### Currently, textures load slowly because of slow disk I/O and slow image decoding, replacing .png with .basic solves neither.

I understand that .basic can be transcoded to many compressed texture formats very quickly, but there's still a transcoding process. And even after that using a compressed texture format means there will be additional calculations underhood on GPU - as far as I know, texture compression is for saving VRAM (at the cost of image quality), not faster loading time.

#### If the goal is fast texture loading and reducing stutter, any transcoding can be should be done ahead of time, and any calculation can be should be avoided at run time.
Which means:

- **Decode images from a texture pack ahead of time to a format that can be _directly_ used by GPU**. This only needs to be done once for a given texture pack, and I think this should be done by PPSSPP itself and provides the user an option to choose from a list of available formats of the platform. I for one would choose a uncompressed format (like GL_RGBA8 for OpenGL) rather than any compressed format as they're all lossy and tend to mess up small textures especially 2D sprites.

- If there's enough spare RAM/VRAM, just pre-cache the decoded textures to avoid slow stutter caused by disk I/O. I mean there's already an option to cache full ISO in RAM... might as well do the same for the decoded textures. One uncompressed 512x512 32-bit RGBA texture only takes 1MB, is texture compression really necessary?

**Comment by LunaMoo** [comment]
Basis supports uncompressed texture formats as well and will definitely be faster than uncompressed texture formats on their own in your use-case where io performance is also a problem(hdd's).

 Don't even compare transcode time of basis to any texture format to all the road png's have to take, it's whole different world. You probably missed the part how it does it and how fast it is. Read more about basis before proposing complex system that would only benefit you due to your current mindset.

 Personally I'd find more appealing to use basis texture pack directly, than waste time and space on per-platform-conversion especially when it comes to high quality.

**Comment by hrydgard** [comment]
I don't disagree though that there are many other changes that are needed too, to get smooth loading, including reading from disk ahead of time, and background thread decoding (while showing the original texture in the meantime) and stuff like that.

**Comment by unknownbrackets** [comment]
We have another issue about loading textures in the background, #12332.

This issue isn't about that.  I think we've already seen in that issue that disk IO has negligible impact on texture loading speed (unless the disk goes to sleep.)  But consideration about background loading, threading, prioritization, VRAM management ([lots of people run out of VRAM already today](https://report.ppsspp.org/logs/kind/995) - and GL doesn't really give us a way to know if there's "spare" VRAM), etc. belongs in that issue.

As for basis: it's a lossy image format that loads faster than PNGs.  Whether it's instant or solves all performance for texture loading isn't really a question.  If we implement #12332 (but probably not just into RAM), using basis will still likely mean less pop-in than PNGs.

Also, keep in mind that texture packs are usually for upscaled textures.  So one 512x512 texture will take 16 MB (512x512 * 4x4 upscale * 4 bytes per pixel.)  Looking at a pack, there's ~700 images, so that might average to what, 8 GB?  Good luck on mobile.

People already today complain about black textures when using texture packs because they ran out of VRAM.  Basis will use less VRAM, at the cost of slightly lower quality (lossy) images, but still much better than the originals.  And yes, it may render a bit slower, but texture read performance isn't the thing that's slow about texture replacement.  It's decoding and loading the texture into VRAM.  It's probably not even the IO, especially on an SSD or mobile device.

-[Unknown]

**Comment by RadarNyan** [comment]
There seems to be some misunderstanding... I'm not saying .png or any other common image format is good for textures, most of them are terrible because of the slow decoding time. I totally agree that .png shouldn't be used for texture packs, what I'm suggesting is: use a texture format that can be used by GPU directly instead of any other format that needs transcoding at run time.

@LunaMoo Yes, I've roughly read about basis_universal and how it transcodes to GPU texture formats very quickly, but there's still overhead introduced (the lookup table will take some memory, transcoding process itself although very fast still takes time)

And about lossless .basis, there's little information of it and it mentions "Deflate/Zstd" so... how is it gonna be different from .png then? I suppose it would be as slow or having larger file size?

---

Normally, I would not complain about using a middle layer to provide convenience (like how .basis works cross-platform) but when talking about gaming, at 60FPS there are only 16.67 ms per frame, **every single millisecond counts** if you don't want to see any stutter. If it's possible to save a millisecond for other things or simply just save power, why not? Yes, using .basis would be much faster than using .png, I do not doubt that, but it still would be slower compared to a native GPU format.

@hrydgard Maybe use .basis to generate the platform-optimized texture pack _before_ loading the game to take advantage of its ability to quickly transcode to many formats? I really don't think it's a good idea to put this transcoding process at run time when it can be easily done ahead of time.

---

@unknownbrackets Oh... I forgot about upscaling, all I was thinking was modding. Of course, a 16x texture would take 16x the space, and when it's upscaled texture compression artifacts wouldn't be that bad I suppose, now I see there's a very compelling reason to use compressed textures.

However, PPSSPP doesn't know which texture the game would need next right? So how is it possible to preload textures in the background... just load them ALL would apparently run out of VRAM/RAM on non-desktop platforms very quickly.

---

My point is: as convenient as it is, .basis shouldn't be the sole choice of texture format. While large textures for 3D objects or pictures may benefit from texture compression without many visible artifacts, textures for UI elements or pixel arts/2D sprites should always stay uncompressed.

**Comment by unknownbrackets** [comment]
I think storing uncompressed (especially upscaled) textures, especially on a mobile device, is not ideal.  I'm still thinking chiefly of upscaled textures.  At the least, we could use lz4.

It should definitely be a texture-by-texture choice.  A texture pack creator could continue to use PNGs, use PNGs + basis files, or maybe even some raw format.  But a raw format would have to be 32-bit fully uncompressed for universal support, or else modders would have to create multiple files per texture to handle different GPUs.  And that'd just take even more storage space.

I still think we need metrics on different devices to make these decisions.  We're only theorizing about disk, decompression, and upload times.  Maybe the slowness is VRAM allocation and none of this will even help.

As to preloading - yes, that's definitely a problem, as mentioned in #12332.

-[Unknown]

**Comment by eqprog** [comment]
If you need metrics, test it out with my texture pack (see my GitHub). It's at 3GB+, with almost every texture in the game upscaled 4x. I assume it's one of the larger packs. My machine runs it well enough (1080ti 8GB and a fast m2 SSD) but it stutters at times especially at loading areas. There are definitely players that have complained about performance however. So I'm starting to look at ways of increasing performance without resorting to compressing too much. An improvement would be nice... I dont know anything about graphics programming but I would be willing to help test etc.

**Comment by oabdellatif** [comment]
Has there been any progress on this issue? While I appreciate the detailed discussion regarding different texture formats, compressed vs. uncompressed, etc., it doesn't change the fact that PNG decoding is slow. From my experience, simply converting a texture pack to ZIM and compressing it into textures.zip is enough to solve 80-90% of stuttering on slower hardware. #12332 was very helpful in this regard, since I haven't seen this documented anywhere.

**Comment by chrisfand** [comment]
If you are okay with slightly lossy compression, I was able to remove virtually all my stuttering by using Pngquant. It also reduces filesize by almost 75%. 

You can run it in the commandline or use Pngyu (GUI) to convert them. Conversion is slow unless you run multiple instances of pngquant and convert your images in batches. 

I've attached an original PNG and two compressed versions using the highest quality settings in Pngyu (with and without dithering) so you can see the difference. There's also comparisons on the pngquant website, https://pngquant.org/.



![default](https://user-images.githubusercontent.com/3870029/219976927-d9f74480-a7d9-4aee-8a2e-7491bad773cb.png)
![compressed_dithering_off](https://user-images.githubusercontent.com/3870029/219976924-71efc0b1-fc41-4e74-a7c1-648f350060ec.png)
![compressed_dithering_on](https://user-images.githubusercontent.com/3870029/219976925-1c5d9a26-bc60-4e3f-866c-24344173c188.png)

**Comment by LunaMoo** [comment]
This probably might be closed now althrough we ended up with .ktx2 instead of .basis.

 If someone wants to quickly convert all his png's to .ktx2 here's a windows command which will go through all subfolders and deal with it:

````
for /r %%v in (*.png) do basisu "%%v" -ktx2 -uastc -mipmap -output_path %%~dpv
pause
````
Just save as .bat file and place in textures folder with basisu.exe, might also need to edit your texture.ini files with replace all option to switch from png's to ktx2's.

 From my short experience with it - it's as fast as ZIM files at half of the size(when used with -uastc and -mipmap and those in some cases can be avoided, ie ui textures might not need mipmaps, and some background textures might be fine without transparency and with lower quality).

**Comment by hrydgard** [comment]
Well we're using basis, just in a ktx2 container. The reason is that the ktx2 container format has direct support for zstd compression for UASTC, which the .basis format doesn't.

I think I should probably expose some memory stats too - you'd find that not only is it as fast as zim, but also takes up only a quarter of the RAM and VRAM.
