### ISSUE TITLE
Install the root stick to another directory

### ISSUE THREAD

**Issue by tilkinsc** [hrydgard/ppsspp#12053]
When I change the version of PPSSPP (and I keep up to date with git builds) I have to extract and drop my old PPSSPP's PSP folder out into the new directory.

On windows, I think it would be easier to contain this information in Documents, like pcsx2. Of course for the ini file, it would write default value for any value it couldn't find to make sure it updates normally.
On other operating systems, I wouldn't really know. On linux, it could be easier to create a ppsspp folder in $HOME or something. On Mac, I don't even know.

**Comment by LunaMoo** [comment]
You don't have to copy memstick to another folder, just extract to same folder and overwrite. 
 Also ppsspp can store memstick in any folder you want and with empty file called installed.txt(created by installer for example) it already goes to "my documents".

 As such closing since everything requested here already exists and also extracting to different folder and moving memstick is just a weird way you're updating making this harder for yourself than it really is.
