### ISSUE TITLE
Midnight Club 3 DUB Edition - Freezes, crashes and glitches

### ISSUE THREAD

**Issue by AutomotiveGaming** [hrydgard/ppsspp#12084]
1) The garage menu freezes when entering the paint shop for the 1968 Pontiac GTO. The game doesn't freeze, I can still move the camera, but can't go further or back in the menus.
2) The game freezes and crashes when trying to tune Class C Tuner cars. I didn't have the same issue with other vehicles, so at the moment the issue seems to appear just with these.
3) I have this glitch with the Ducati Monster, but only on rival bikes. Player's bike doesn't have such thing. https://i.imgur.com/sNkJLOl.jpg

Tested with PPSSPP 1.8.0, on PC.

**Comment by Emulatorer** [comment]
Similar  #11501

**Comment by unknownbrackets** [comment]
In #11501, it was said that some issues only affected Android or ARM.  This makes me think it could be related to more factors, since this is reported on a PC.

Can you try verifying this against your own disc?  If the crc is not 83AC132A, CAC66B91, E66C9C40, 2C57A623, or 95A71267, it's probably a bad copy.

If you downloaded it from some site on the internet, it could be a bad copy or a hacked version.  If you didn't buy this game, I'm not inclined to help with that - you should buy it.  Buying games like this (even used copies) helps the market for games like this, and hurts the market for crappy lootbox games.

-[Unknown]

**Comment by AutomotiveGaming** [comment]
So, all these issues are apparently caused by a bad disc. I've later tried with a good US copy of the game and this issue didn't happen at all. I had these problems with a bad copy of the EU version, so, just in case, if you have a good disc of the EU version of the game give it a try just to check if it doesn't cause any problems compared to the US one.
