### ISSUE TITLE
OGL, DX11 and Vulkan broken on 64bit Windows Executable with Latest Windows Preview Build

### ISSUE THREAD

**Issue by PhilDim1** [hrydgard/ppsspp#12117]
On opening PPSSPPWindows64, an immediate crash to desktop. Occasionally the application will open with a black screen and an info box which contains 'Defragment must not run on the render thread'. After executing the application again, it defaults to DX9, which works fine. The option for selecting Vulkan is not available, and changing it to OpenGL and DX11 produces identical results.

For whatever reason, the 32bit executable works perfectly fine. It also allows me to select Vulkan if need be.

### What *should* happen?
PPSSPPWindows64 should probably not crash when trying to use DX11, OpenGL or Vulkan.

### What hardware, operating system, and PPSSPP version?
Windows 10 Build 18922.rs_prerelease
i5-8400, 1050ti, latest NVIDIA drivers. I tried the latest git build and then tried 1.8.0.
Both were the same. Using the 32bit application on a 64bit system worked.

I don't think this is a bug, but rather an issue with the latest Windows build. I just thought someone who is experiencing the same issues might find a simple solution for the time being.

**Comment by LunaMoo** [comment]
Normally "Windows Preview Build" issus should b reported to Microsoft, not here. Through this seems to happen to two other users on different windows versions with different gpu's as seen [here](https://forums.ppsspp.org/showthread.php?tid=24779) and is probably not related to preview builds, maybe caused by some third party app/overlay.

**Comment by unknownbrackets** [comment]
Make sure to update drivers even for graphics cards you don't CURRENTLY have.  For example, if you previously had an AMD video card, or if you have an integrated Intel video card, it's necessary to update their drivers too.

The reason for this is that when Vulkan (or potentially other backends) initialize (outside of PPSSPP), it checks all the drivers to ask if the video card is present.  Some older/broken drivers just crash right away, or might crash because of a Windows update not being backwards compatible with old drivers.

When you start PPSSPP, we try to start PPSSPP in the background and init Vulkan.  If the graphics driver crashes while doing this, we hide the Vulkan option.  This is because Vulkan drivers (especially older AMD ones) have been so unstable.  That's why you don't even see the Vulkan option - we detected the video card driver crash.

GeDoSaTo, if you have it installed, can also cause crashes like this.

-[Unknown]

**Comment by benderscruffy** [comment]
please close as it hasn't been updated in years
