### ISSUE TITLE
Texture rendered in incorrect position in Tenchu Shinobi Taizen

### ISSUE THREAD

**Issue by jpfkd** [hrydgard/ppsspp#12115]
### What happens?
In level editor of Tenchu Shinobi Taizen, terrain texture in toolbar shows up in incorrect position.

![ULJS00018_00000](https://user-images.githubusercontent.com/20862542/59834501-12fbc700-9383-11e9-9f5a-80973738cf55.png)
The gray tile should appear in the darkened box in bottom left.

![ULJS00018_00001](https://user-images.githubusercontent.com/20862542/59834510-15f6b780-9383-11e9-94a1-9369a9bb7be5.png)
It affects the right one while changing the terrain type (Pressing L).

![ULJS00018_00003](https://user-images.githubusercontent.com/20862542/59834513-15f6b780-9383-11e9-950a-09ce38525729.png)
In case of walls,  one side of wall is rendered incorrectly.

### What *should* happen?
As described above, terrain parts to be placed should rendered in the darkened box in the bottom left of the screen.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Desktop.
GPU: Intel HD Graphics 4000 (Core i7-3770K)
OS: Arch Linux (kernel 5.1.11-arch1-1-ARCH)
PPSSPP: v1.8.0-298-g53e826337

**Comment by hrydgard** [comment]
That's really interesting.

A GE frame capture or two of the problem would be useful:

https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by jpfkd** [comment]
I followed the instructions of the page you linked. But PPSSPP Debugger says "Debugger could not connect"
PPSSPP leaves following log in terminal when I try to connect to PPSSPP Debugger.
```
I: http_headers.cpp:123: user-agent: Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0
I: http_headers.cpp:157: finished parsing request.
I: http_server.cpp:56: The request carried with it -1 bytes

**Comment by jpfkd** [comment]
I managed to make dumps with Chromium. (Should it be another issue that i couldn't use Firefox to connect remote debugger, or it isn't supported?)
Anyway, [here's the dumps](https://github.com/hrydgard/ppsspp/files/3317480/dump.zip).
recording1 is a tile rendered incorrectly. (similar to first image in the first post)
recording2 is while opening parts selector. (second image)
recording3 is only one side of a wall is rendered incorrectly. (third image)

**Comment by unknownbrackets** [comment]
Thanks for reporting.  Firefox used to work but started requiring HTTP/1.1 in responses which we weren't sending - will be fixed in #12120.

-[Unknown]

**Comment by jpfkd** [comment]
I tried bisection and found out when the issue is introduced. The last revision I can see it working correctly is 2ae2dd7d406342deb4851f583b359a87d874a11f. And the first one that glitches is f99fa02ba72146b0803f01371669bdf81aca0bff. Revisions between them give me compile error.

The glitch in f99fa02ba72146b0803f01371669bdf81aca0bff is even worse. Here's some screenshots.

![f99fa0_1](https://user-images.githubusercontent.com/20862542/59974207-6d479280-95e4-11e9-8dec-b3984b1c4a3b.png)
![f99fa0_2](https://user-images.githubusercontent.com/20862542/59974225-a122b800-95e4-11e9-8a4d-2c916f03d720.png)

As of 2b12776137fbf36840e081eb48a10b1709f75c41, the glitch became the same as the current state.

**Comment by unknownbrackets** [comment]
The correct display (from a PSP):
![ULJS00018_#12115_tenchu_editor_part](https://user-images.githubusercontent.com/191233/59983409-fdc9a700-95d3-11e9-87ad-f263f114d874.png)

Software is pretty close:
![ULJS00018_#12115_tenchu_editor_part_softgpu](https://user-images.githubusercontent.com/191233/59983418-0fab4a00-95d4-11e9-9c72-224b72ecf7cb.png)

Vulkan, Direct3D 11, and Direct3D 9 are all pretty close too.  This bug is OpenGL only.

![ULJS00018_#12115_tenchu_editor_part_gles](https://user-images.githubusercontent.com/191233/59983427-39647100-95d4-11e9-8594-82f324c06947.png)

Until 354/494, it's just drawing the ground.  The problem draw happens at 418/494.  Some interesting new bugs happen when stepping in the GE debugger, pointing to a state flushing issue.  It offsets the viewport offset to offset the drawing, which seems probably related... and some quick `true ||` bisecting confirms this, it's shader uniform state.

-[Unknown]

**Comment by jpfkd** [comment]
I confirmed the issue is fixed. Thank you for a great job!
