### ISSUE TITLE
This is the GOAT emulator . some questions about the project

### ISSUE THREAD

**Issue by Askmewho** [hrydgard/ppsspp#12129]
Ive run several test on desktop linux armhf with open source drivers on RPI3 and I get a lot of performance boost compared with the retropie attempt.

Example( I made a lot on my channel)

https://www.youtube.com/watch?v=tgjqlhsFGRo&lc=z224izjr5qzgzbl0vacdp4353wlogjxct2war2gajv1w03c010c

1) Best GUI Ive ever see on an emulator, simple snappy as hell, minimalist. 
2) Do you have any branch to test MT cpu or are you all trying to implement it??
3) I cant understand how well it runs on a poor RPI3
4) I love you all so much.
5) keep on it.

**Comment by unknownbrackets** [comment]
You might also get even better performance if you run `echo 5 | sudo tee /sys/devices/system/cpu/cpufreq/ondemand/up_threshold`, which will make your CPU keep max clock speed more often, but it may also increase its temperature.

Multithreading is enabled by default, and there's no option to turn it off.

That said, it's graphics rendering that happens on a separate thread (as well as IO and some audio stuff.)  Because the PSP itself only ran game code on a single core, Bad Things (TM) happen if we try to make PSP game code suddenly multithreaded.  Lots of crashes.

That said, we're still always looking for ways to improve speed more and use threading more effectively.

-[Unknown]

**Comment by Askmewho** [comment]
Weird, because ive only see one core running. I am on opengl 2.1 by mesa 19.

**Comment by unknownbrackets** [comment]
Depending on the game, CPU emulation may not be very expensive - you might see graphics emulation take most of the time, and so not really see two heavily active cores.

It sounds like the Raspberry Pi 4 may at some point support Vulkan, which could potentially take better advantage of threading.

-[Unknown]
