### ISSUE TITLE
[Android] Spider-Man 3 has better performance in v0.9.8 compare to the last build

### ISSUE THREAD

**Issue by Emulatorer** [hrydgard/ppsspp#12167]
### What happens?
As the title say it also I mentioned here https://github.com/hrydgard/ppsspp/issues/10196#issuecomment-509448272 that this game didn't crash in this version unlike v1.0, v1.2, v1.3, v1.4, v1.5, v1.6, v1.7 and v1.8 last gitbuild 🤔

### What *should* happen?
Last build of ppsspp should have a better performance compare to v0.9.8 also didn't crash?

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Android Lollipop
Octacore 1.4Ghz CPU
Mali-450 MP GPU
2GB of RAM

**Comment by marosis** [comment]
Yeah... last few months is perfomance of the emulator extremly horrible.

**Comment by hrydgard** [comment]
Extremely horrible? really?

**Comment by Emulatorer** [comment]
@marosis only Spider-Man 3 has a lower performance to the last build compare to the old version 0.9.8 aslo didn't crash

**Comment by unknownbrackets** [comment]
There are a lot of reasons this could happen, especially on a Mali-450 device.  In v.0.9.9, CLUT, blending, render-to-texture, stencil, and other things were all improved.  But it could be anything, really.  That range has a lot of changes:

https://github.com/hrydgard/ppsspp/compare/v0.9.8...v1.0.0 (3,469 changes)

And since then, we've made over 10,000 changes.  So it's really impossible to say.

It's for sure that compatibility has improved significantly since v0.9.8, and performance in most games has improved as well.  There's probably just something this particular game is doing that doesn't work out well.

It may also only affect older devices.  For example, it could be doing the RGB patch thing, and performance of that has improved in recent versions - but only for newer devices.  It might not look all that different in most scenes, and just be missing effects in some areas in v0.9.8 without this.

We really need a more narrow range to look into a performance regression.  3,469 is too many to manually sift through one by one and guess.

-[Unknown]

**Comment by Emulatorer** [comment]
@unknownbrackets can you giva a full list build apk of v0.9.9.1 - v1.0 if possible? 😅
I can't find it anymore in ppsspp buildbot :(
I will try to upload a logcat activity of v0.9.8 - v0.9.9.1 using Catlog App 😺

**Comment by Emulatorer** [comment]
![Screenshot_2019-07-11-12-56-43](https://user-images.githubusercontent.com/37603562/61023206-879eb000-a3db-11e9-9e6b-86fd21331e17.png)
Catlog (Logcat)
07-11 12:55:55.687 I/NativeApp(12885): 55:55:687 idle0        I[LOAD]: Core/Config.cpp:803 Config saved: /storage/sdcard1/PSP/SYSTEM/ppsspp.ini
07-11 12:55:55.695 W/PpssppActivity(12885): Skipping event: mainscreen
07-11 12:55:55.695 I/PpssppActivity(12885): Ad not ready yet. Showing next time.
07-11 12:55:56.346 E/InputDispatcher(1099): channel '115e63b2 org.ppsspp.ppssppgold/org.ppsspp.ppsspp.PpssppActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-11 12:55:57.676 D/recents.RecentsActivity(3174): updateRecentsTasks:update launchedToTaskId = 38 TASK = Task.Key: 38, u: 0, lat: 1562820777176, org.ppsspp.ppssppgold
Can't get the full activity of ppsspp v0.9.8 :(

Maybe this one can help?
Syslog (Logcat)
[PPSSPP v0.9.8 Logs.zip](https://github.com/hrydgard/ppsspp/files/3380316/PPSSPP.v0.9.8.Logs.zip)

**Comment by Emulatorer** [comment]
😌 Just forget this issue in focus us to the crash issue  #10196

**Comment by marosis** [comment]
@hrydgard im sorry i know it's hurt read that comment but yeah.... some my favourite games are slower maybe over 30%(god of war, flatout, etc...) and everything are doing blocktransfler effects. But yeah for that you have another issue  request
