### ISSUE TITLE
Consider re-implementing the FidelityFX CAS filter

### ISSUE THREAD

**Issue by nagisa** [hrydgard/ppsspp#12181]
FidelityFX CAS is a permissively licensed sharpening filter that has been demonstrated to work very well in upscaling mode in modern games, allowing one to render the game at a lower resolution and have improved frame throughput at almost no loss of visual fidelity. It has a minimal performance hit.

Since PPSSPP natively already renders at a lower resolution than most modern screens using CAS filter could allow for better looking results after upscaling – especially compared to the [traditional sharpening filter already available](https://github.com/hrydgard/ppsspp/blob/master/assets/shaders/sharpen.fsh).

https://github.com/GPUOpen-Effects/FidelityFX/tree/master/FFX_CAS has the source code and https://github.com/GPUOpen-Effects/FidelityFX/blob/master/FFX_CAS/ffx-cas-headers/ffx_cas.h has a description of the shader/algorithm.

This may be low-benefit thing to do as it can also be enabled at a driver level in AMD drivers on Windows as well as via a port to ReShade on Windows otherwise. However, implementing this filter in PPSSPP would make it portable to all of the platforms PPSSPP supports.

As a first step it would probably make most sense to verify the potential gains via enabling this in AMD drivers or ReShade before considering this further, but I have no means to do that myself.

**Comment by LunaMoo** [comment]
I don't think it's worth looking into amd FidelityFX CAS, same as it's not worth looking into nvidia DLSS. Those techniques are ment for 2k into 4k upscaling to produce a quality somewhat worse than real 4k, at much cheaper cost when rendering very complex PC native games.

 The thing is PSP games doesn't include complex geometry nor fancy effects, and a complex upscaling & sharpening effects will actually be heavier than just rendering at higher resolution, this would be even more true on mobiles that suck when it comes to shaders, so we really don't have ANY benefit from cheaping out and can simply render at whatever res we want. PPSSPP currently due to SSAA flag that can be set to any integer value above 1 has no max render resolution limit so you can easily see that for example 16k(32x psp res) in PPSSPP is easier to render than 4k in a modern PC game aka this is really not a good use case for such methods.

**Comment by benderscruffy** [comment]
is this going to be implemented ???

**Comment by hrydgard** [comment]
We have MSAA with sample rate shading now in Vulkan (and in the future in the other backends), I think that's a better path for PSP emulation. CAS is highly unlikely to beat in in quality.
