### ISSUE TITLE
BASE addresses for memory edditing with CE

### ISSUE THREAD

**Issue by theboy181** [hrydgard/ppsspp#12203]
I was wondering if there was a way to get the BASE ADDRESSES from PPSSPP?

I have been using a .bat file that sets debug mode, and writes a log.  I can get them them from the log, but this leads to HUGE 1GB+ files that can be destructive to SSD's.

Is it possible to have the base addresses listed somewhere in the menu, where it can be copied? This would be helpful to the hacking community.

**Comment by unknownbrackets** [comment]
This is really more appropriate for the forum.  I'm confident this has been discussed on the forum a lot.

That said, you could use the API or simply Debug -> Log Console.

This isn't really an issue, so closing.  The forum URL is:

http://forums.ppsspp.org/

-[Unknown]

**Comment by theboy181** [comment]
The debug log (window) clears itself before you can pause the emulator, and am not sure what you mean by using the API - 

Can you shed some light on this?

**Comment by LunaMoo** [comment]
You can just use my cheat table:
http://forums.ppsspp.org/showthread.php?tid=3590&pid=117172#pid117172
 It will not only give you PSP game address inside PPSSPP, it will also limit the search range to PSP user memory and even has options to create some simple write cwcheats automatically.

 Also includes instructions as it's not as straightforward due to windows bug which requires a workaround when used with mapped memory. Also Cheat Engine can't really be used for any "hacking", it's debugger doesn't understand mips and is useless. It's only useful for searching through memory for values, eventually code patterns(but that requires disabling JIT). PPSSPP has it's own debugging tools that are way more useful when actually trying to patch games or even to create better cheats.
