### ISSUE TITLE
"Warning: Battery save mode is on" incorrectly displayed on Galaxy J3 (user report)

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#12238]
Got a user report that his device shows this warning in PPSSPP, even if it's charged to 100%.

Not sure if there's much we can do about it other than remove the warning..

![Screenshot_20190812-202656_PPSSPP](https://user-images.githubusercontent.com/130929/62923641-7700a180-bdae-11e9-81db-b991cc7c468e.jpg)

**Comment by Florin9doi** [comment]
On my Note9, the message is displayed for Medium and Max power saving , but the state isn't checked unless the app is destroyed. If power state is changed (eg from power saving to high performance) while PPSSPP is minimized, the message is still displayed after the app is resumed. 
![...](https://i.imgur.com/v3RkxKt.jpg)

**Comment by hrydgard** [comment]
Oh right, I forgot that that's what it's for, I thought it was something that came up when battery was low and the device automatically entered power saving mode. Yeah it's a bit unfortunate that we don't react to changes. But apart from that, maybe there is no issue here, although it's hard to explain to users what they need to do to fix it in just a message. Considering getting rid of it altogether.

**Comment by Florin9doi** [comment]
May be resolved in #12241

**Comment by unknownbrackets** [comment]
I realize it might seem like a dumb message to someone who has written applications for phones, but I've helped multiple people realize that games or apps were slow on their modernish phone because they forgot they enabled power saving mode hours or even months ago.

It's stopped happening with PPSSPP since adding this message, so not ever hearing about it since may or may not indicate users have stopped being confused about power saving features.

-[Unknown]

**Comment by hrydgard** [comment]
You definitely have a point, and I don't feel strongly either way. Let's keep it around.

I'm gonna close this, let's assume that #12241 made this work well enough.
