### ISSUE TITLE
Could NOT find SDL during config - even though I have libsdl2-dev installed...

### ISSUE THREAD

**Issue by thebunnyrules** [hrydgard/ppsspp#12310]
I'm getting a message during Android config:

Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR)

I'm getting similar messages for LIBPNG LIBZIP and SNAPPY.

Yet have the latest package of libsdl2-dev (2.0.8 on ubuntu), libzip-dev + libzip4 (1.12),  libpng-dev (1.6.34). libsnappy-dev 1.1.7

The apk still compiled successfully but will it be unstable because these libraries and headers were not included during config? How vital are they?

Has anyone else had this issue? How would I  go about resolving this if they are essential?

**Comment by unknownbrackets** [comment]
On Android, we don't actually use SDL at all.

You probably have SDL installed, but as a Linux x86_64 package.  Android doesn't use those, so can't even compile using the same packages.  The message is technically correct (you don't have a version of the Android SDL2 library), but misleading since we don't actually use or need it for that platform.

For libpng, libzip, and snappy - PPSSPP's source code comes with versions of these.  It checks to see if it should use system versions instead.  These are used on Android, but not finding them isn't an issue.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah this is fine. Closing.

**Comment by thebunnyrules** [comment]
I'm glad to hear it. Thanks so much for taking the time to explain this!

**Comment by vnctdj** [comment]
This reminds me of a similar question I asked in https://github.com/hrydgard/ppsspp/pull/12012.
Could it be possible to append something like "using PPSSPP's one" to "Could NOT find x" warnings?
