### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by ShadMessa** [hrydgard/ppsspp#12321]
### What happens?
Hi, I lunched the emulator the first time all was working great, when i used it the second time the sound was gone. I am using the default settings (i tried to change the settings but nothing worked).

I used the android version 1.8.0 the first time with metal slug XX when i reopened it, there was no sound. I tested other games FF7, Brave story... no sound ether.
Then i updated to the latest 1.8.0-615 release and I tried older ones but the issue persisted.

android version= 7.1.0
GPU= mali T720 OpenGL api 3.1.0 ES (no vulkan support)
CPU= Cortex A53 (8core 64-bit)
bord= mediatek 6753

**Comment by unknownbrackets** [comment]
I assume that other apps still play sound at this point, right?

An adb logcat would likely help:
https://github.com/hrydgard/ppsspp/wiki/How-to-get-an-adb-logcat-from-a-PC

-[Unknown]

**Comment by leopard20** [comment]
You sure you didn't turn off the emulator sound from settings?!

**Comment by ShadMessa** [comment]
I found the source of the issue. It's some weird bugs in the implementation of the custom rom i use on my phone. It made the speakers unrecognized, the use of Bluetooth speakers fixed it, but it only happened in ppsspp for some reason. thanks anyway.

**Comment by unknownbrackets** [comment]
Strange.

Possibly related: PPSSPP tries to use a small buffer (if possible) because PSP games generate audio in very short bursts.  This reduces latency, but it's probably different from other apps/games that were written for Android and generate audio in larger bursts.

I think we use a larger buffer (i.e. force more latency) when Bluetooth audio is used, because otherwise you get choppy bad audio.

-[Unknown]
