### ISSUE TITLE
PPSSPP auto delete cheat after actived.

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#12320]
### What happens?
PPSSPP auto delete some cheat code after actived.

The game that I encountered mentioned problem.
- 007: From Russia with Love (only Asia region)
- God Eater Burst (JP)
- SD Gundam G Generation Overworld

Example video.
https://youtu.be/fHqseb1PWtE

### What *should* happen?
PPSSPP can be used cheat without that problems. :)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
- Windows 10 64 bit (CPU: i5-6200๊, GPU:Nvidia940M)
- Huawei P9+ (Android 8.1, Kirin 955, Mali T-880)

...with PPSSPP v1.8.0-615-gedcd5e1c7 use default settings.

**Comment by hrydgard** [comment]
Hm, so that's [Unicode Character 'LEFT-TO-RIGHT OVERRIDE' (U+202D)](https://www.fileformat.info/info/unicode/char/202d/index.htm) and it's companion.

We should probably try to strip those out without ruining the rest. Maybe these are applied by default in some locales and some editors, feels buggy when editing plaintext though...
