### ISSUE TITLE
Crashes/hangs up when attempting to load a save file

### ISSUE THREAD

**Issue by MooseMoosington** [hrydgard/ppsspp#12350]
[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/3649876/ppsspplog.txt)
[ppsspplognofastmem.zip](https://github.com/hrydgard/ppsspp/files/3649909/ppsspplognofastmem.zip)
[Moose's DxDiag.txt](https://github.com/hrydgard/ppsspp/files/3649877/Moose.s.DxDiag.txt)

It's crashing when trying to load a save with fast memory on, and it just gets hung up when it is off. The ppsspplog is too big when I have fast mem turned off so had to zip it.

**Comment by hrydgard** [comment]
What game is the save from? Looks like Tactics Ogre. Can you upload the actual save file?

**Comment by MooseMoosington** [comment]
Yep it is Tactics Ogre.  
[ULUS10565DATA00.zip](https://github.com/hrydgard/ppsspp/files/3653303/ULUS10565DATA00.zip)

**Comment by unknownbrackets** [comment]
I tried loading the game and was able to head to Qadriga.  Where does it crash?

The log did contain "ms0:/PSP/SAVEDATA/ULUS10565SQEXTACO/".  Did you possibly run the data install?  If you get rid of the install data, does it work fine?

Do other saves, such as the ones here, have similar problems?
https://gamefaqs.gamespot.com/psp/999440-tactics-ogre-let-us-cling-together/saves

My goal is to be able to reproduce the crash, and the quicker / simpler the steps, the better.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
