### ISSUE TITLE
[UCES01250] Motorstorm Arctic Edge bugged lightning

### ISSUE THREAD

**Issue by DanteDraconi** [hrydgard/ppsspp#12363]
### What happens?
The lightining on Motorstorm seems to be either darker or more bright than on real hardware

### What *should* happen?
Here's a comparison between a real PSP (left) and PPSSPP 1.9 (right)

- Map: Goldrush - Starting point
On a PSP it looks a bit more bright 
![UCES01250_00000](https://user-images.githubusercontent.com/9718875/65781732-73519000-e14c-11e9-8369-c605d8ad8743.png)

- Map: Wolfpack Mountain - Starting point
These are almost identical
![UCES01250_00001](https://user-images.githubusercontent.com/9718875/65781818-a09e3e00-e14c-11e9-9e22-58834a79061e.png)

- Map: Wolfpack Mountain - Past the start line
This is where it clearly shows the lightning difference being way more bright than it should be
![UCES01250_00003](https://user-images.githubusercontent.com/9718875/65781878-c4618400-e14c-11e9-8fdd-0652aa9e8527.png)

On software rendering the lightning looks fine
![UCES01250_00005](https://user-images.githubusercontent.com/9718875/65782462-017a4600-e14e-11e9-9762-8d8ad39ae8d9.jpg)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
PSP: Slim 2000 6.38 ME-3
PPSSPP Ver. : 1.9
Resolution: 1x
Texture scale: 1x
OS: Windows 10 x64 build 18362
GPU: GTX 1060

Here's a savestate of the most noticeable area
[UCES01250_1.01_0.zip](https://github.com/hrydgard/ppsspp/files/3663518/UCES01250_1.01_0.zip)

**Comment by hrydgard** [comment]
Software seems broken in other ways though!

Could you get some GE captures of these three locations, for easy investigation?

https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by DanteDraconi** [comment]
It seems to happen in any map not localised in a specific location
Oh and I've just noticed that switching to software renderer and loading the state with the bright lightning it was gradually lowered it until the lightning was the correct amount. 
While on software, I've saved a state when it was "fixed" and upon loading that fixed state on hardware renderer the lightning seemed to be fine and it stayed on the correct levels even after switching to different maps

![UCES01250_00008](https://user-images.githubusercontent.com/9718875/65784299-0640f900-e152-11e9-907e-dfa43468edfd.jpg)

So here's three states fiddling with that
[before_software.zip](https://github.com/hrydgard/ppsspp/files/3663587/before_software.zip)
[softare_rendering.zip](https://github.com/hrydgard/ppsspp/files/3663588/softare_rendering.zip)
[after_software.zip](https://github.com/hrydgard/ppsspp/files/3663589/after_software.zip)

**Comment by hrydgard** [comment]
Wow. That suggests that the game is trying to do a variant of modern HDR lighting, with the limited hardware of the PSP, where it computes a brightness level and adjusts rendering brightness up and down automatically. Wonder if it does CPU readbacks that we don't detect, or uses some other way to create a brightness feedback loop...

**Comment by unknownbrackets** [comment]
The way software is broken is noted in #11623.  I wonder if it's doing the brightness handling during the render to self?

In the before dump at 491/645, it does a `dst * src + 2.0 * src.a * dst` blend using a solid fefefe color.  This is hard to handle correctly.  I believe it should result in `dst = 3.0 * 0xfe/0xff * dst`, but really results in `dst = 2.0 * src.a` because src.a clamps to FF.

Software should do that right, but shouldn't correct it.  Looks like the Goldrush map.  Does that one also fix if you load a software save state?

The after dump (Wolfpack) does a similar draw at 1427/1581, using the same blending but the color 5d5d5d5d.  That should be `dst = 3.0 * 5d/ff * dst` or `dst = 1.094 * dst`, which we should be doing correctly (5d is low enough not to suffer from clamping issues.)

In both cases, the render to self is done with lighting on, and separate specular.  It also makes a smaller copy of the screen to 0x0417c000, but it doesn't seem to ever draw from that.  Maybe it's used, maybe it's for screenshots/menu later...

I wonder if it uses the brightness of the data in 0x0417c000 (via CPU reads) to calculate the vertex color it uses for the gamma correction blend draw.  It'd be interesting if that color is different before/after software in the same scene.

-[Unknown]

**Comment by hrydgard** [comment]
Could be interesting to force it to readback 0x0417c000, similar to the forced readback we do in Dangan Ronpa..

**Comment by DanteDraconi** [comment]
I've tried the same methodology on the Goldrush track as you said, save state during software and load it on hardware. For this one however, after loading the software "corrected" state it instantly went back to being darker on the next frme

[goldrush1_before_software.zip](https://github.com/hrydgard/ppsspp/files/3693198/goldrush1_before_software.zip)
[goldrush2_during_software.zip](https://github.com/hrydgard/ppsspp/files/3693199/goldrush2_during_software.zip)
[goldrush3_after_software.zip](https://github.com/hrydgard/ppsspp/files/3693200/goldrush3_after_software.zip)

**Comment by unknownbrackets** [comment]
Thanks, so that means there are multiple problems here: blending causing some tracks to be too dark, and probably readback causing some to be too bright.

The smaller thumb is at 0x0417c000  and 256x128, which means it ends at 0x0419c000.  z_un_08942578 seems to read from that range.  It only does a few small reads spaced 160 bytes (40 pixels) apart, starting at 0417e850.

That means it reads at (20, 10), (60, 10), (100, 10), (140, 10), (180, 10), and (220, 10).  Seems slightly odd, but okay.  Here's the func:

```
struct Something {
	u8 pad1[24];
	void *base;
	u8 pad2[8];
	u16 width; // 0100
	u16 height; // 0080
	u16 byteStride; // 0400
	u16 flags; // 8080
	u8 pad4;
	u8 bitsPerPixel; // 20
};

u32 z_un_08942578(Something *a0, u32 a1, u32 a2) {
	u8 *addr = (u8 *)a0->base + z_un_089424b0(a0, a1, a2);

	if (a0->bitsPerPixel == 32) {
		// This one.
		return *(u32 *)addr;
	}
	if (a0->bitsPerPixel == 16)
		return *(u16 *)addr;
	if (a0->bitsPerPixel == 8)
		return *(u8 *)addr;

	u8 val = *(u8 *)addr;
	if ((a1 & 0x01) == 0)
		return val & 0x0f;
	return (val & 0xf0) >> 4;
}

u32 z_un_089424b0(Something *a0, u32 a1, u32 a2) {
	if ((a0->flags & 0x8000) != 0) {
		int mul2D = (int)a1 * a0->bitsPerPixel;
		int mul28 = (int)a2 * a0->byteStride;
		return mul28 + (mul2D / 8);
	}

	u32 a = 0x80 / a0->bitsPerPixel;
	int b = a1 % a;
	int c = (a0->width / a) * (a2 / 8) + (a1 / a);
	int d = b * a0->bitsPerPixel;
	int extra = (a2 & 7) * 16;
	return (c * 128) + (d / 8) + extra;
}
```

That's not hard to hook.

-[Unknown]

**Comment by hrydgard** [comment]
Regarding the blending func, the effective "dst = 3.0 * 0xfe/0xff * dst" should be possible to approximate by doing two draws, one to double dst and another to multiply by 1.5 * 0xfe * 0xff.

We don't really have the infrastructure to do dual draws to simulate blending right now though...

**Comment by deBoulangerie** [comment]
This happens to me on android: 
Same bug? 

![Screenshot_2019-11-20-22-18-48-993_org ppsspp ppsspp](https://user-images.githubusercontent.com/16673931/69287226-cba98900-0bf5-11ea-898f-a12d9b82083f.jpg)

**Comment by Gamemulatorer** [comment]
This game graphics is kinda correct on vulkan but lag/slow stutter a lot before and during racing
![Screenshot_2021-10-05-15-18-52-422_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/135977935-e4e51ee6-e602-4a53-bdab-602269d135db.jpg)
However on opengl the game performance is much better compare to vulkan but opengl is too bright
![Screenshot_2021-10-05-15-16-11-662_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/135978099-87f9f5ed-a017-409e-b098-e70a36a5ef29.jpg)

Im using the latest git build of ppsspp :/

**Comment by Gamemulatorer** [comment]
There's a bug on Vulkan using v1.12.3-607

There's a screen glitch using vulkan

https://user-images.githubusercontent.com/37603562/148721314-5e47bb8f-20b4-41c8-bb65-7780f88aa7a6.mp4

Opengl looks ok compare to vulkan

https://user-images.githubusercontent.com/37603562/148721340-8113de63-aa53-4992-b2ff-873aedcf736a.mp4

**Comment by unknownbrackets** [comment]
How does this look now?  We simulate some blending more accurately on Vulkan, and we've fixed some depth clamp clipping issues.  I'm wondering if performance or glitches have improved, especially on Vulkan.

Also curious if software rendering gets it right.

-[Unknown]

**Comment by Gamemulatorer** [comment]
Recently build
![Screenshot_20221025_204013_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/197775449-f9abd92d-ba2e-47f0-93f6-6675944b4004.jpg)

**Comment by hrydgard** [comment]
This is solved, it just doesn't perform super well on all hardware due to the unavoidable readback. Closing.
