### ISSUE TITLE
[GTA LCS/VCS] Audio/SFX Glitch

### ISSUE THREAD

**Issue by NABN00B** [hrydgard/ppsspp#12377]
From time to time, a sound effect (usually an engine sound) in GTA LCS & VCS "gets stuck" and keeps playing. If you're lucky, it goes away automatically after a few minutes, otherwise you can fix it by pausing and unpausing the game.

A consistent way to trigger this issue in VCS is by starting a 'Smuggling' mission. (As seen in [this video](https://streamable.com/fd8rh).) A common encounter in LCS is after completing the mission 'Booby Prize'. I can provide save files if necessary.

This is an universal issue that affects every emulator speedrunner I've talked to.

**Comment by hrydgard** [comment]
Yeah, I've seen this before once or twice.

Any idea if it happens on a real PSP too? It could be game bug, our sample playback stuff is pretty solid.

**Comment by DavidTamas** [comment]
I'm 99% sure it doesn't happen on real hardware.

**Comment by hrydgard** [comment]
Okay. It would be very useful if you could provide saves before these two triggers.

**Comment by DavidTamas** [comment]
[ULUS10160S92F0.zip](https://github.com/hrydgard/ppsspp/files/3670115/ULUS10160S92F0.zip)
Here's one for VCS, although it's unlikely to work on real PSP. Load the save, walk to the guy next to the exit and press D-Pad Up to start a misison. "LEVEL 8 - SUPPLY & DEMAND" should start (the other 2 mission types don't seem to trigger the audio glitch). Once the cutscene ends walk towards the exit, touching the railing on the way.

One thing I'd like to mention is that I'm starting to think this glitch is CPU speed related because I'm unable to trigger it with lowered emulation clock speed.

**Comment by hrydgard** [comment]
Hm, in that case it might be very tricky / impossible to fix in other ways....

**Comment by DavidTamas** [comment]
I triggered the glitch even with 110 CPU speed, at which the game already runs considerably slower than it would on a real PSP. Maybe not a game issue after all.

**Comment by benderscruffy** [comment]
Is this still an issue ??
Please update

**Comment by NABN00B** [comment]
I'm for closing this, as it seems to have been fixed in 1.16.0 (probably by #18076).
