### ISSUE TITLE
Investigate slow startup on Android

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#12378]
Google Play Developer Console complains that the amount of users getting a slow app start is higher than in comparable apps. Should investigate if we are spending any unnecessary time during startup.

**Comment by unknownbrackets** [comment]
It doesn't give any metrics on average startup time or anything does it?

How do we define end of startup?  When the PPSSPP logo is showing and fading out, I assume it has already started up, right?

-[Unknown]

**Comment by hrydgard** [comment]
I don't know how it's defined. Maybe first rendered frame or something? It doesn't say.

**Comment by hrydgard** [comment]
Hm, maybe task-switching back in and recreateing a lot of textures and render target would do it...

**Comment by unknownbrackets** [comment]
Maybe we should render a loader or something in that scenario.  The tricky thing is, on GL at least, we'll be busy trying to create all those textures etc. at the point we might decide it worth displaying a loading frame.

I guess we could do something like...

```c++
for (size_t i = 0; i < steps.size(); i++) {
   if (firstFrame_) {
      time_update();
      if (time_now_d() > loadingTime_ + MAX_START_LAG) {
         loadingTime_ = time_now_d();
         renderLoadingFrame();
      }
   }

   // ... init CREATE steps ...
}
firstFrame_ = false;
```

When running init steps?  But I'm not sure if adding additional frames would... work.  And I'm not sure if our Vulkan code would like such a reality...

-[Unknown]

**Comment by hrydgard** [comment]
Yeah... I don't know if it's worth even trying that kind of stuff...

**Comment by ADHSoft** [comment]
I had this related problem a few days ago,  I had a microSD as an "adoptable storage", and the psp path was the default ( /storage/emulated/0/psp/ )
When I loaded a game (for example ULKS46236) the emulator showed nothing on the game screen for 2 to 4 minutes before the game could start. This was a serious issue. 
I fixed it by moving everything into a subfolder, let's name it "MS" . So the full iso file path became "/storage/emulated/0/MS/PSP/GAME/game.iso"
That fixed the problem.
I think this doesn't happen when not having the microsd as an "adoptable storage".

Possible cause: there is some function that looks for something in the entire microsd before starting a game. It could even be the game itself who does this searching. If games have access to "/storage/emulated/0/" as that is the emulated mem.stick path, that is possible, because some games look for files made to bypass protections.

I suggest this solutions :
1) The memstick default root path should be a subfolder, not /storage/emulated/0/
2) Prevent the app from accessing any non-critical files outside the /psp/ folder.

**Comment by unknownbrackets** [comment]
If we wanted, we could add some timing and log it to report.ppsspp.org.  This way we could measure startup time, resume time, etc. separately.  If we did, it'd only be for people with reporting enabled.

-[Unknown]

**Comment by benderscruffy** [comment]
No feedback/outdated?

**Comment by hrydgard** [comment]
It's gotten better, I'm gonna close.
