### ISSUE TITLE
Bug in Tomb Raider Anniversary (Europe)

### ISSUE THREAD

**Issue by dhanial** [hrydgard/ppsspp#12429]
Device : Xiaomi Redmi Note 4x
Android OS : 8.1.0
GPU : Snapdragon 625
PPSSPP Backend : OpenGL
PPSSPP Version : 1.9.3-82
Got totally black screen and no sound when i tried to play

**Comment by fahadrashid7705** [comment]
same issue here full blackscreen

**Comment by iota97** [comment]
It was broken by #12328 for me (same as #12400), and fixed by #12432, could you try the latest build from the build bot?

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback, but it sounds likely it's fixed now.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
