### ISSUE TITLE
Can't map right analog on screen controls

### ISSUE THREAD

**Issue by PilipinoAko** [hrydgard/ppsspp#12439]
![Screenshot_20191022_094443](https://user-images.githubusercontent.com/52031664/67254767-745ab080-f4b1-11e9-9f0c-3cfc0a952fff.png)

### What happens?
For gamepad its compatible but in screen controls Its not.  Some games are support with analog patch.
Mh3rd had analog patch but mhfu have no analog patch. I need it i broke my controller for some reason

### What *should* happen?
Tutorials for bigginers for make analog cheat or can do map right analog mapping in game or in game setting

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
1.9.4 latest

**Comment by LunaMoo** [comment]
Beginers in this case would mean to have some low level programming experience.
 The best guide or tutorial I made on that would be in [this post](https://forums.ppsspp.org/showthread.php?tid=25352&pid=134597#pid134597) where I explain how such patches work and partially walk through an existing function that with some changes could be reused for most games since while it only prepares some info, it makes other things easier.

 Note that MHP3rd wasn't really "patched" to have right analog support. MHP3rd HD supports it natively, but also not as analog, it simply re-maps some d-pad functionality to right analog axis without even trying to do more.


 Anyway for what you want, especially if you consider MHP3rd HD "patched to use right analog" which it doesn't as explained above, right analog mapping itself will not do anything to games which can't use it, but you can do it the other way, and just map your physical right analog to any other functionality for example d-pad.

 This is a non-issue and support is better kept to forums, so I'm closing this.
