### ISSUE TITLE
Texture scaling takes 2-3 seconds to apply after changing a scene

### ISSUE THREAD

**Issue by mcabel** [hrydgard/ppsspp#12453]
### What happens?
Whenever a scene changes, it will be pixelated for several seconds. Then after 2-3 seconds, the scene will apply the texture scaling. No other shader is used. Resolution change 1-10/auto makes no difference. V-sync does not help. Lazy texture cache enabled or disabled make no difference.

Alternatively, instead of using texture scaling, A full post processing processing 5xbr can be used to smooth the screen, but in this case, the screen is jittery when "moving" across the scene.

This was tested with Persona. Similar effect was seen with Valkyrie profile Leneth.

![pixelated](https://user-images.githubusercontent.com/10392829/67700891-38c65780-f985-11e9-88dc-e9180c95f6fe.png)
### What *should* happen?
The image should looks smooth all the time or maybe the image could be pre-cached(if that's even possible).

![after few seconds](https://user-images.githubusercontent.com/10392829/67700890-38c65780-f985-11e9-8c26-9b378a3b2374.png)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
ppsspp-v1.9.3-125-gb4438c574
i7@2400
Win 8.1
nvidia gforce gt 755m

**Comment by LunaMoo** [comment]
I'll close this as it's basically covered by #9518 and #1934, texture scaling running on the CPU has heavy limits, otherwise instead of textures popping in with time, you would suffer from constant frame drops and pauses, in fact even with those limits and on powerful desktop pc's, the frametime will get horrible when scaling happens and you can often hear it with sound popping or animations loosing smoothness in many games.

 This will not improve, textures are cached, but can't be pre-cached for automatic scaling, we don't know a texture before it shows up in-game as we do with texture replacement which can indeed improve in such way in the future.

 Also the direction PPSSPP is going is GPU based texture scaling see #10393, we currently have it only for Vulkan and it has to be activated by ini-file editing, it also has only one filter which has a problem with alpha, but for most games still looks great and since it uses GPU power, given gaming hardware it's ultra fast and doesn't need any limits, it just scales everything instantly. Probably not much hope on your hardware through as I doubt this mobile gpu supports vulkan.

**Comment by mcabel** [comment]
@LunaMoo hi, my GPU supports Vulkan. Which ini and which setting Should I modify?

**Comment by LunaMoo** [comment]
Change TexHardwareScaling = false to TexHardwareScaling = true in ppsspp.ini you'll also need to use render res above x1 and texture scaling multiplier.
