### ISSUE TITLE
Add option to verify ISOs against redump.org?

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#12469]
redump.org provides metadata for most of the PSP discs, but of course don't host any downloads. 

I didn't actually know that redump.org had a PSP database because it's not visible from the main website's list of platforms, but it's really there:

http://redump.org/discs/system/psp

So if we can get our hands on the actual database, or find an easy way to query it, it should be easy to add a way to check that an ISO has not been modified from its original form.

**Comment by Drasikk** [comment]
I have all the games in ISO, so if I would be interested in that new option.

**Comment by DavidTamas** [comment]
What purpose would this serve? Display a warning on top of the screen if the ISO failed the verification or refuse to launch it? Either way, I doubt there's a complete database anywhere so this would be very likely to cause some confusion in the future.

**Comment by LunaMoo** [comment]
It's more about stopping people from blaming emulation while abusing broken pirated copy or otherwise corrupted disc and wasting people's time, not doing anything at launch. We could add an requirement of validating users copy before posting issues here and also display at reporting site which copies are good/broken as PPSSPP is collecting hashes for a while already.

 In theory ISO should not exactly be the most popular container, I for example use PBP for pretty much everything simply for it's best compression, psstore games as well as pre-patched ones or just an umd backups. CSO are also extremely popular and some of them can modify/remove content for better compression which is awful, but used historically by many desperates with small memsticks.
 Thankfully pirates share ISO's exclusively and most pirating users don't know we support compressed formats from the PSP or might just be to lazy since it's not that important on devices PPSSPP runs on, so it might still prove useful in practice.

**Comment by unknownbrackets** [comment]
Well, some PBPs simply just have the UMD image (aka ISO) inside them, as I recall.  Not certain how we calculate CRCs today, but we may already do those correctly.  Could you compare the CRC of one of your games (as recorded on report.ppsspp.org when you report compatibility) with the ISO's expected CRC?

We already have a [database of each game id and version](https://report.ppsspp.org/games) based on reports.  So we could just import verified CRCs into this database for cross referencing.

On the downloads page, we can get an XML export of that database, but it lacks IDs.  Better would be to scrape it, probably.  Not sure we would expect a lot of updates in the future anyway.

Of note, we do already have reported CRCs.  For more popular games, it's already pretty obvious / easily detectable which CRC is right:
https://report.ppsspp.org/game/ULES01044_1.00

In fact, we do that already, although the heuristics aren't perfect:
https://github.com/unknownbrackets/ppsspp-report/blob/6cead3ca4d17dd4702cc2b1e9f19b22c9fbc95f7/lib/compat/suggest.js#L170-L171

-[Unknown]

**Comment by Abbanon** [comment]
It looks like they offer mass .txt file downloads, displaying all of their information by platform and game title (crc, md5, sha1)
http://redump.org/downloads/
Maybe this could be used?

**Comment by benderscruffy** [comment]
is this going to be implemented ???

**Comment by hrydgard** [comment]
That is great as mentioned, and now that it has game serials / IDs, we can easily do lookups into it to verify ISOs.

I plan to add support for ISO verification in the near future. I think I'll just bundle the csv as a file in /assets.

I can also think of a bunch of different uses for this, such as specifying compat.ini options by game name instead of by ID, etc.

**Comment by hrydgard** [comment]
Printed is fine as it's generally gonna match the internal one, if there are one or two misprints or mistakes it won't take away much from the usefulness. We use the ID found in PARAM.SFO on the ISO file.

**Comment by hrydgard** [comment]
Yeah, that's fine, doesn't look hard.

**Comment by hrydgard** [comment]
This is now implemented, checks happen on the game info screen only currently, not during game startup. Let me know how it works for you.
