### ISSUE TITLE
Monster hunter 3rd trouble shooting

### ISSUE THREAD

**Issue by GAMING4LIFEMHFU** [hrydgard/ppsspp#12461]
First of all my phone is Redmi note 7, the iso is Monster hunter 3rd portable ps3 version English patched. It opens properly. I go to a quest, everything ok, but then when i change an area except the base camp, it says it's loading, then the screen goes black and ppsspp crashes. Does anyone have any idea what could possibly cause that? Pls help me with this issue

**Comment by LunaMoo** [comment]
Cheats, corrupted game files or playing abusing savestates simulating very long time without restart would be my guesses as the game works fine assuming HD version as standard one would not even boot without decrypted pauth files.

**Comment by Saramagrean** [comment]
Similar https://github.com/hrydgard/ppsspp/issues/11410?

**Comment by GAMING4LIFEMHFU** [comment]
I disabled the cheats, same result, i downloaded the game from different
sites many times, same result. If i need any specific settings for the game
to run properly, pls i would like to know. Also if you know any site with
the iso being fully functioning pls send me a link too 👍

Στις Κυρ, 3 Νοε 2019, 1:13 μ.μ. ο χρήστης Benjamin Benda Gates <
notifications@github.com> έγραψε:

**Comment by Gamemulatorer** [comment]
@GAMING4LIFEMHFU try ppsspp latest git build and see if this issue is still reproduce.

**Comment by Gamemulatorer** [comment]
@GAMING4LIFEMHFU no feedback updated?

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
