### ISSUE TITLE
GPU texture scaling issues (slow in Valkyrie Profile, alpha issues)

### ISSUE THREAD

**Issue by bajolzas** [hrydgard/ppsspp#12463]
### What happens?
I was testing the "TexHardwareScaling = true" setting in ppsspp.ini and noticed these problems:

-In Valkyrie profile, some scenes just kill my GPU, with that setting, for no apparent reason (in this case those in Angrim's house)
-FMV scenes in Lunar desappear, only the sond remaining.
-In Lunar as well, some text that was white is now green.
-Havent tested much else, but I've noticed some spikes to 100% GPU usage here and there; hope it can be fixed.

### What *should* happen?
Better performance (I think) and no visual bugs.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

GPU: NVIDIA GeForce 940MX
Windows 10
PPSSPPv1.9.3-130-g9a5766bcf

**Comment by LunaMoo** [comment]
The algorithm it uses currently doesn't respect alpha, that's a known problem, probably causes both green background and black screen on fmv's.

 By "kill gpu" do you just mean performance?
 The plan is to support any compute shader filter via external files similary to post process shaders and there might be cheaper algorithms out there more usable on low end hardware. That being said this feature's requirements will always differ a lot depending on what's the game's doing and I don't think it ever should have hardcore limitations just to run well on low end gpu's as in such case you might as well return to using the cpu based scaling which scales things with a delay and skips scaling some textures altogether as that's the only way to get rid of such performance "spikes" where game loads a lot of new textures or constantly modifies existing ones, effectively leading to same thing.

**Comment by unknownbrackets** [comment]
Texture scaling on the GPU currently ignores how frequently textures change and how many other textures were scaled on the same screen.  It's killing your GPU just because the scaling is too much without these limits.

For CPU based texture scaling, we currently skip scaling textures the game animates in place in certain ways, and scale only a max number of pixels per frame (causing pop-in of detail.)  This probably needs to be applied to GPU based scaling, but perhaps with different or auto-detected limits.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, some 2D games reuse the same large texture with small tile changes or palette changes, this is a worst case for texture scaling and even a GPU can't crunch through rescaling the entire texture multiple times per frame fast enough. Possibly the secondary texture cache option can help this though?

**Comment by bajolzas** [comment]
"By "kill gpu" do you just mean performance?"
Yes, weird that, from what I tested (wich wasn't much) it only really happened in that specific scene, in that specific place.

It'd be nice if we could use some of the performance workarounds of the CPU sclaling in the GPU one.

Also being able set the max number of pixels being scaled per frame would be nice (and/or the emulator be able to autodetect a sensible number).

Also I dont think my GPU is considered low end, sure it is a laptop GPU, but low end is a bit of a stretch.

**Comment by LunaMoo** [comment]
With Nvidia naming scheme you have xx70/xx80 as a high end, xx50/xx60 for mediocre budget cards and anything under is a low end typically not much different from integrated graphics performance wise outside of having dedicated memory.

 The difference between 940mx which not only being a low end model, but also it's mobile version and something like a desktop rtx 2060 or even still likely the most popular gtx 1060 is soo high, that most of your performance killing problems would not even cause a noticeable frame drop and people have way stronger gpu's than that.

 Since hardware texture scaling was a proposed solution for texture scaling popping in with a delay and avoiding scaling some textures alltogether, it should be free of those hardcore limitations and if it really has to get some as there are some extreme situations like some FFT0 effects, especially the tutorial "???" boss, it should not be so awful at punishing people with higher end hardware as with CPU based scaling where no hardware in existence could scale textures in real time, heck it ruins frame time noticeably even with the limitations it has on modern cpu's and should not be compared to GPU's situation which are way better at doing this and top end ones can actually do it in real time.

 Imo it at most should have a limitations of texels per frame, but even with that, it should be much higher than what's set for cpu based scaling or at least should be user selectable instead of a constant forcing people with gaming hardware into their own builds. And to be clear I don't advocate about it for myself as I would use my own builds to play anyway.;p

**Comment by Gamemulatorer** [comment]
Valkyrie Profile - Lenneth still slow with upscaling texture shader using vulkan backend.

**Rendering resolution** 2x
**Display resolution** native
**Texture shader** 4xBRZ

[recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7503141/recording.ppdmp.zip)

**Comment by hrydgard** [comment]
At least it should be an improvement from before... is it not?

But we may need to take measures to prevent some textures from being upscaled in this game.

**Comment by Gamemulatorer** [comment]
> At least it should be an improvement from before... is it not?
> 
> But we may need to take measures to prevent some textures from being upscaled in this game, and we need to be smarter about alpha.

I Can't compare before because 4xBRZ is buggy on my phone with mali gpu :(

**Comment by hrydgard** [comment]
Oh, right. Well, at least it works now and didn't before :D

**Comment by Gamemulatorer** [comment]
This issue can be close now performance improvement in vulkan with 4xBRZ texture shader is malupet 😎👍

https://drive.google.com/file/d/1CdxPZ1ruFnkPyemEUerlLWZSEud5v6Ok/view?usp=drivesdk

**Comment by hrydgard** [comment]
Thanks for reporting!
