### ISSUE TITLE
Gran Turismo screen shaking

### ISSUE THREAD

**Issue by marosis** [hrydgard/ppsspp#12468]
When i am using 333Mhz, screen Will start shaking And it Is really 'hurt' my eyes. But default 222mhz Are ok.
Pocophone F1
SD 845 Vulkan OpenGL

**Comment by hrydgard** [comment]
This can be fixed in-game in Options by changing the Video Output setting to External. There are also cheats, but I'd recommend this method.

A bit odd, but what can you do... the game uses the limited resolution and slow display of the real PSP to fake antialiasing by shaking the screen by half a PSP pixel. This does not work so well at higher resolutions.
