### ISSUE TITLE
dx11 vsync not implemented

### ISSUE THREAD

**Issue by hoholee12** [hrydgard/ppsspp#12493]
### What happens?
dx11 vsync is broken on 1.9.3
runs fullspeed
enabled or disabled, it always tears screen like hell.
opengl vsync works though..
it happens on every game...

### What *should* happen?
idk

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

windows 10 1903 64bit
ppsspp 1.9.3
intel iris6100 with latest driver

**Comment by unknownbrackets** [comment]
That setting has never been implemented for Direct3D 11.

-[Unknown]

**Comment by OCRBonk** [comment]
Would be nice if FSE+Vsync was implemented in DX9 as well. Otherwise the only way to get Vsync (And proper frame pacing for 30FPS games) is to use RTSS and Scanline Sync.

Using DX9 is the only way to be able to force SGSSAA and still use Buffered Rendering.(But there are DX9 specific issues. And some games don't play nice with Scanline Sync.) In OpenGL you can force Vsync and 1/2 refresh rate vsync from the driver. But in OpenGL with Nvidia cards you can't force Anti Aliasing unless you are using unbuffered rendering.

Trying to use Resolution Scaling for Super Sampling instead is very ineffective. As the downsampling to display resolution is very poor quality. Leading to it looking like there is almost no AA at all.
https://imgsli.com/MTEyMDE
https://imgsli.com/MTEyMDI
