### ISSUE TITLE
Persona 3 Portable Lines in Tartarus transformation scene

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#12558]
When I Saw a Tartarus transformation scene in 4/21 dark hour in P3P I saw these Lines In the Emulator but it does not appear in real PSP.

PPSSPP:
![Screenshot_2020-01-11-16-19-48-96_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/72201373-440e2700-348e-11ea-953d-e2400d93c282.png)

Real PSP:
![Screenshot_2020-01-11-16-20-10-92](https://user-images.githubusercontent.com/37503397/72201377-4ff9e900-348e-11ea-851c-9e866d8fe3ee.png)

**Comment by Panderner** [comment]
Same happens in 1x Resolution
![Screenshot_2020-01-12-06-20-38-56_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/72211286-b1a86a80-3503-11ea-8ce6-22347512c783.png)

**Comment by unknownbrackets** [comment]
Could you try exporting a GE frame dump?  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by Panderner** [comment]
[DUMP.zip](https://github.com/hrydgard/ppsspp/files/4272655/DUMP.zip)
Here.

**Comment by Panderner** [comment]
![Screenshot_2020-03-05-00-32-59-97_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/75901068-f522b380-5e78-11ea-9725-3d173fb47804.png)
On software rendering the lines don't appear

**Comment by unknownbrackets** [comment]
That dump isn't of the correct scene?

![image](https://user-images.githubusercontent.com/191233/75950015-e29a8100-5e5c-11ea-9902-8fb08a20803f.png)

A GE dump is like a screenshot.  If you take it at the wrong time, it'll show the wrong thing.

-[Unknown]

**Comment by Panderner** [comment]
> That dump isn't of the correct scene?
> 
> ![image](https://user-images.githubusercontent.com/191233/75950015-e29a8100-5e5c-11ea-9902-8fb08a20803f.png)
> 
> A GE dump is like a screenshot. If you take it at the wrong time, it'll show the wrong thing.
> 
> -[Unknown]

No it's not a correct scene like this:
![Screenshot_2020-03-07-13-39-37-60_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/76137537-223db480-6079-11ea-9714-73d7bc28e7c3.png)
[DUMP.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/4301408/DUMP.ppdmp.zip)

**Comment by unknownbrackets** [comment]
This is an antialias issue.  It actually sets the texture to itself, but the UVs are garbage.

There are actually two incorrect sets of lines there.  It should correctly look like this:

![ULUS10512_#12558_persona3_lines](https://user-images.githubusercontent.com/191233/76137659-66d33c80-5ff4-11ea-9665-a21679990d21.png)

Software rendering isn't terrible, although you'll notice more aliasing on the rightmost object:

![__testfailure](https://user-images.githubusercontent.com/191233/76137678-8e2a0980-5ff4-11ea-8bbc-5dfa12a66285.png)

It uses GE_PRIM_LINES but skinning is not enabled, so our crummy heuristics in hardware don't skip it.  If we did skip, it'd look like this (taken from the GE debugger before presenting, that's why it's darker):

![image](https://user-images.githubusercontent.com/191233/76137766-67200780-5ff5-11ea-90fa-e0a9d7b2576c.png)

A lot more aliasing in the same object, but certainly better than the lines.  We could probably do what software does if we made a copy (like we already do for special blending modes.)

-[Unknown]

**Comment by Panderner** [comment]
And this one too:
![Screenshot_2020-03-07-17-51-55-54_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/76141158-93db2a00-609c-11ea-8d63-23baddd9f525.png)
[Second dump.zip](https://github.com/hrydgard/ppsspp/files/4301664/Second.dump.zip)

**Comment by hrydgard** [comment]
We could always add a compat setting to kill off all AA lines... 

What game was it that required us to not kill AA lines? I think we might want to either do the above or adjust our indeed pretty crummy heuristics.

**Comment by hrydgard** [comment]
Found the issue where @unknownbrackets did some good research on this in https://github.com/hrydgard/ppsspp/issues/6483 . 

Possibly simply discard AA lines when texturing is enabled and the current framebuffer is bound as texture (and a few of the other modes are set right)?

**Comment by unknownbrackets** [comment]
This game is drawing the lines with:
 * tex func replace RGB
 * alpha test > 0
 * alpha blend src.a / inverse src.a
 * lighting enabled

I guess it must just be the lighting.  I'll add some notes about echochrome to the other issue.

-[Unknown]
