### ISSUE TITLE
Glap.Play p/1 gamepad randomly disconnects

### ISSUE THREAD

**Issue by VirtualBoyFreak** [hrydgard/ppsspp#12555]
The Android gamepad Glap.Play p/1 randomly disconnects from the phone's Bluetooth while playing PPSSPP. I notice it because it stops responding to my movements and short afterwards, the light indicator of the gamepad starts blinking, indicating it has disconnected from Bluetooth and tries to reconnect. It can't reconnect while I'm in the emulator, but as soon as I exit the emulator to the phone's main screen, the gamepad reconnects to the phone. I then go to the app "gamepad tester" and all buttons are responding correctly and everything is fine again.

I'm using a Pocophone F1 (Xiaomi) with latest official Android version (Android 9 and MIUI 11.0.5.0 stable) non-rooted, a Glap.Play P/1 gamepad with latest firmware and PPSSPP Gold for Android (latest version, 1.9.4, official Google Play version). The game I play with is Ridge Racer 2, and gamepad disconnections tend to happen after several minutes playing, but I can't find any pattern which forces the gamepad disconnection.

I've tried the following, without success:

- Play with Game Turbo active (Game Turbo is a game optimizing app specially designed for the Pocophone F1 by Xiaomi).
- Deactivate Game Turbo.
- Clean all tasks from background prior to playing.
- Rebooting phone.

**Comment by hrydgard** [comment]
I don't think this issue is at a level that PPSSPP has influence over. It just asks the OS for available gamepads and reads them, it does not care about Bluetooth or similar.

Do other games and emulators work reliably?

**Comment by VirtualBoyFreak** [comment]
Yes, other emulators and games that specifically work with the gamepad (SF IV SE, for example) don't get these disconnections.

**Comment by hrydgard** [comment]
Yeah, PPSSPP might be a little harder on the system than some other emulators, depending on the game...

**Comment by VirtualBoyFreak** [comment]
I've also set to "on" the sustained performance mode in PPSSPP. Do you think that can help? I'm not sure what that option exactly does, but I feel it can help with the system performance overall.

**Comment by hrydgard** [comment]
Sustained performance is supposed to slow the device down so it can run at a speed where it never overheats and needs to throttle down - so should make performance more consistent (it's common to see good PPSSPP performance for a minute or so until the device gets hot and downclocks, especially on older hardware, Nexus 5 is a particularly bad example).

**Comment by VirtualBoyFreak** [comment]
Well, unfortunately, after nearly 2h playing Ridge Racer 2, it happened again. I was racing against Angel (to try and win that car) and the gamepad disconnected. This time around though, as soon as I exited to the PPSSPP menu, the gamepad reconnected to the phone and all the buttons were working fine. I didn't need to quit PPSSPP for the gamepad to reconnect.

I was using Open GL, sustained performance was on and the battery usage for PPSSPP was set to "unrestricted". I understand it's a very painful bug because it's random and it can be caused by anything related to PPSSPP, Bluetooth, Xiaomi... Anyway, I'll try to find a pattern or see if it happens after long play sessions in other games, but at the moment it only happens to me with PPSSPP. I'll update the post when I find something else.

**Comment by hrydgard** [comment]
Either way I don't think there's anything PPSSPP can do to fix it. As I said, we don't even touch Bluetooth, we just listen to joystick events.

**Comment by VirtualBoyFreak** [comment]
I think it doesn't have to do with the Bluetooth per se, but PPSSPP must be killing a process related to the Bluetooth connection from memory when cleaning the memory to recover resources. My guess is that Xiaomi is loading something into a memory section where it shouldn't be and PPSSPP kills the process when needed.

I played PPSSPP for 30 minutes with the gamepad and my Samsung smartwatch connected to the phone simultaneously and had the bug happen once. Then I played with MAME4droid for more than 2 hours finishing Final Fight, Captain Commando, World Rally and Shadow Dancer while I was interrupted by WhatsApp (loading it on a floating screen without stopping MAME) and I had zero issues.

Is there any way I can get an event log while playing PPSSPP to register when the gamepad disconnects? I don't think it would give the origin of the problem, but it might help to know where to begin with (maybe I should report to Xiaomi too?)

**Comment by unknownbrackets** [comment]
Killing other processes when system memory is scarce is a function of the operating system.  Apps like PPSSPP just ask for memory, and the OS says "yes" or "no" (often the OS will say yes even if it is broke, though.  They all hate saying no.)  Traditionally, OOM Killer in Linux kicks in when it's time for the OS to pay its debts, but I don't think Android uses OOM Killer (it uses something else.)  Nevertheless, nothing in PPSSPP kills other processes.

That said, if we're somewhere overallocating memory or leaking memory, that could indirectly lead to unleashing something like the OOM Killer's murderous rage.  It seems like it shouldn't kill important Bluetooth related processes (normally it would murder something like Whatsapp first?), but we have no control over what it might murder.  That's determined by some heuristics designed by your device manufacturer or etc.

If you're using (or have enabled) any of the following features, they may contribute to memory overuse, and I suggest turning them off:
 * Rewind
 * Texture scaling
 * Retain changed textures
 * Remote debugging

PPSSPP will clean up its own internal memory allocations (not by blindly murdering other processes, though) on a regular basis, but the above features tend to allocate a lot of RAM or keep clean up less rigorously.

I would suggest using adb logcat to view logs, and inspect the logs around when a disconnect happens ASAP.  This is an Android system facility, so even if something else is causing it there's a decent chance info will get logged about it.

https://github.com/hrydgard/ppsspp/wiki/How-to-get-an-adb-logcat-from-a-PC

Separate from that, if using sustained performance / disabling battery optimization for PPSSPP has a consistent impact on how frequently this occurs, that would imply it has more to do with CPU/thermal throttling.  Those settings probably don't impact memory usage or allocation at all.

It might be that Android (again, this is the OS's job) isn't scheduling the Bluetooth process frequently enough, because PPSSPP or other background processes are being too needy.  This could cause a device to disconnect if it gets angry when it's ignored for too long.  This still might be something PPSSPP could indirectly control (by using less CPU), if so.  Hopefully even in this case, adb logcat would show some useful details.

That said, it might be useful to try enabling frameskip and reducing quality settings (more than necessary for good speed.)  If that makes the problem go away or become even more infrequent, then that points to CPU - and not memory - as being a likely problem here.

-[Unknown]

**Comment by VirtualBoyFreak** [comment]
Thanks a lot [Unknown] for all the information you've given me there, I'll try your suggestions.

I have Auto frameskip enabled and I use PSPx2 resolution with FXAA effects, so I'll try disabling FXAA and lowering the resolution to standard PSP. I don't use rewind, but I use savestates quite often. I'll check the texture and debug options to see how they are, because I don't use them that I'm aware, but I have to check. Hopefully that will solve the issue. If not, then I'll get to check the Logcat through my PC.

From reading your instructive post, I'm afraid the disconnections have to do with the phone itself and how it copes with the resources PPSSPP asks for... Anyway, thanks again for making me clear how Android works. I'll be back with more info as soon as I have it.

**Comment by VirtualBoyFreak** [comment]
So I'm upset, ashamed, angry... Anyway, long story short: I finally got the gamepad to disconnect... With another emulator. This time it was Redream (Dreamcast) and it happened exactly the same as with PPSSPP. Therefore, the issue is not with the emulator, but with my gamepad, phone... Or both. I think I'll stick to my good old ipega 9025. I'm really sorry for all the hassle. Closing the issue now (I wanted to explain why I close it).

**Comment by hrydgard** [comment]
Thanks for reporting your testing results! No need to be ashamed or angry, just a little exasperated at the state of hardware and software in the year 2020...

**Comment by VirtualBoyFreak** [comment]
While using the old ipega I noticed that the keyboard of the "overlaid WhatsApp" wasn't showing at all (I usually use standard Gboard with multi language Spanish-English), while with the Glap.Play gamepad the overlay keyboard was shown perfectly. I then remembered that the ipega 9025 connected to phones as a physical keyboard, which makes the on-screen keyboard deactivate while the gamepad is connected, so I thought "what if my connection problem has to do with an incompatibility of the standard unmodified Gboard with the gamepad and the Xiaomi MIUI interface, or even with my multi language keyboard settings?

It sounds crazy, but it's not the first time I see an issue related to language settings in a phone. In the old N-Gage, there was a game similar to F-Zero which had the following bug: if the phone was set to a non-English language, the last track was completely corrupted graphic-wise, you could barely race it until the first turn. The only solution was to switch the N-Gage phone language to English and then the game was perfectly playable until the end.

Therefore, I have set the Pocophone to use the official Xiaomi keyboard (which uses Gboard as basis and is similar, but doesn't allow multi language input) and I still have to try it more in depth, but I was able to play for 1 hour without issues, with all the PPSSPP settings set as I had them before (all to HW, FXAA, etc.), with the Samsung watch connected to the phone at the same time and replying to WhatsApp messages while in the emulator using the overlaid WhatsApp. I still have to try more, but it looks promising. I'll keep you updated to confirm if it's this or not (and in case anyone else suffers the issue).

**Comment by VirtualBoyFreak** [comment]
Update: it's not the Glap.Play gamepad, because I've had the issue happen with my old iPega 9025 too. It isn't the Gboard either, because before getting the issue with the iPega, I had the issue with the Glap.Play without having the Gboard loaded onto memory (I had the Xiaomi keyboard). So the only thing left is the phone itself (hardware or software). I incline myself as a software/driver issue, mainly because my Bluetooth watch doesn't disconnect throughout the whole day... Anyway, thanks for everything. Being clear it's not a PPSSPP issue, I'll have to look elsewhere to find a solution :-(

**Comment by BarevnejRadek** [comment]
Interesting read, I'm just having the exact same problem with the latest Gamesir X2s Bluetooth and Pixel 6 Pro. 
Didn't you come up with a solution?

**Comment by VirtualBoyFreak** [comment]
Mmm... it was long time ago, but if I'm not mistaken, it had to do with
updating Android itself, not with the emulator. I ended up buying a new
controller that wasn't so picky...

**Comment by BarevnejRadek** [comment]
I'll see, I updated the FW drivers, it's very new, so maybe there's a bug in it.

**Comment by VirtualBoyFreak** [comment]
The bug could also be in Android itself. Try updating your phone to the
latest version and see if it works.
