### ISSUE TITLE
Stutters/Micro-stutters while playing DBZ Shin Budokai 2

### ISSUE THREAD

**Issue by MojoJojoDojo** [hrydgard/ppsspp#12618]
### What happens?
When playing the game Shin Budokai 2 the game will exhibit stutters and micro-stutters while using
the DX11 and Vulkan renderers on Windows 10 (while the game still reports 60 fps).
The issue does not occur or  might not be noticeable on Android TV with the OpenGL ES renderer and on Linux with the Vulkan renderer (unlike Win10).
I did notice that the micro stutters begins to occur when aura effects appear in battle.
You could see the issue here in this video if you pay attention : https://www.youtube.com/watch?v=fFeLVH8nndo
The issue is not solved by using post processing shaders with 60 fps on in the ini file or by using the CRT shader.
### What *should* happen?
The game should play smooth 60 FPS all the way.
### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
OS: Windows 10 (Linux and Android TV used for testing)
GPU: Radeon 530/Intel UHD 630
CPU : i7 8550U
PPSSPP 1.9.3.

**Comment by LunaMoo** [comment]
Do you mean it runs at 60/59fps or that your FPS goes between 60 and 59? Because 59 would be weird for a max fps in game and could be a timing issue. On the other hand fps varying between 60 and 59 could mean your stutter is just performance related, texture scaling would easily cause that even on much more powerful pc's.
 The solution from the other issue would only help games that run under 60fps natively ie 30 or 20 fps, not when your fps drops in 60 fps game.

**Comment by MojoJojoDojo** [comment]
Sorry i should have been more exact i mean its moving between 100% and 99%.
The FPS stays at 60 FPS all the way.
If it's still related to the other issue you could close this one as well :X.

**Comment by unknownbrackets** [comment]
Personally, I don't think this is sufficiently different from #9736.  There's no indication this is game specific, and it's probably all the same concerns/questions/settings/etc.

-[Unknown]

**Comment by MojoJojoDojo** [comment]
I will close this and put the info on that issue for others to know.
