### ISSUE TITLE
MoltenVK: We need to handle texture swizzling not being available

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#12615]
I think we'll just reuse the code used in DX11 on Windows 7 to avoid the 16-bit formats.

See #12583

**Comment by Degerz** [comment]
https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf

Unfortunately, Metal does not appear to have a native equivalent to VK_FORMAT_B4G4R4A4_UNORM_PACK16 when I checked the supported packed 16-bit pixel formats. You [could](https://github.com/hrydgard/ppsspp/blob/master/GPU/Vulkan/TextureCacheVulkan.cpp#L60) try VK_FORMAT_R4G4B4A4_UNORM_PACK16 instead if Vulkan [gpuinfo](https://vulkan.gpuinfo.org/displayreport.php?id=2664#formats) is anything to go by. Also, VK_FORMAT_A1R5G5B5_UNORM_PACK16 has no equivalent as well in Metal. 

If we had Vulkan extensions to use Metal formats would it be possible for you to use ABGR4Unorm in place of BGRA4Unorm and A1BGR5Unorm in place of A1RGB5Unorm too ?

**Comment by unknownbrackets** [comment]
We use 4444 formats for two main reasons:
 * When generating font or other data that doesn't need 8888.  In this case, we auto-detect support and generate appropriately.
 * When uploading texture data directly from the PSP game.

So if the device doesn't natively support the PSP game's format, then we have to convert it.  We already do this on Windows 7 with Direct3D 11, and this is just about extending that to Vulkan (when necessary.)

If we're already going to reprocess the PSP texture data into new RAM, I think moving it to 8888 is the simplest option, rather than trying to change it to another 16-bit format the device supports.

-[Unknown]
