### ISSUE TITLE
[Feature Request] Improved MAC Address options

### ISSUE THREAD

**Issue by Abbanon** [hrydgard/ppsspp#12616]
Some games (such as **Invizimals: Shadow Zone**, **Invizimals: Lost Tribe**, and **SOCOM: Fireteam Bravo 2** just to name a few) have a special encryption in the savedata that uses the current PSP system's MAC address at savedata creation.
If you load this savedata in another PSP (or PPSSPP) with a different MAC address, the savedata refuses to load.

Currently in PPSSPP, the only in-UI option for setting a MAC address is a randomized generator. So if you want to set a specific MAC address, you need to edit the `MacAddress =` line found within ppsspp.ini.
I'm sure some improved MAC address functionality in the UI options would be ideal for some users that wish to import their saves (for these specific games) from real hardware into PPSSPP, mainly for ease of access and not having to delve into files to edit the .ini directly.

My proposition
- Adding an "**Input manual MAC address**" UI option that functions similarly to the "**Change PRO ad hoc server IP address**" UI option
- Renaming the currently existing "**Change MAC address**" UI option into "**Generate random MAC address**", which will input/overwrite whatever is typed in the manual field 
(would be a good idea to have a Y/N confirmation popup for the random generation option, in case someone mis-clicks or fat-fingers the menu and selects it by mistake, saving them the effort of having to manually type their MAC address all over again)

**Comment by LunaMoo** [comment]
That option started as a hand-edited one if I recall and random-generated one was a huge improvement from that reducing possibility of people having same one to practically 0 outside of copy pasted ini files.

 Would be better if affected games did it in a way that could be universally hacked as savedata mac address dependency feels stupid and would be confusing for most people even if they could manually input it from UI, instead of having to edit ini file manually as now.

**Comment by hrydgard** [comment]
This has been fixed a while ago, closing.
