### ISSUE TITLE
Allow Remote Debugger automatically disconnects

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#12630]
I turned on Allow Remote Debugger When I press multitask or home button it automatically disables Allow Remote Debugger and disconnects Debugger I can't download frame dump from GE Debugger

Video here:https://streamable.com/q03n2

I'm using Android 9 PPSSPP v1.9.3-285-ge7ddc94fb

**Comment by unknownbrackets** [comment]
This might be because your battery is so low.  Does the same thing happen if you:

1. Make sure to charge your phone over 20%.
2. Count to 10 before multitasking away.
3. Close the settings and go back to the main menu before multitasking away.

Or does it still uncheck itself in that case?

-[Unknown]

**Comment by Panderner** [comment]
Same happens when I  my battery has over 20% and I cleared all the tasks

**Comment by Drasikk** [comment]
The same thing happens to me, it's deactivated when I minimize. It should be built-in emulator itself, although I don't know if it's possible.

**Comment by unknownbrackets** [comment]
You may need to long-press the PPSSPP app, select app info (or otherwise get to the app info for PPSSPP), and then select Battery under Advanced.  There, make sure PPSSPP is allowed to use battery in the background.

Some versions of Android may phrase this differently, but if PPSSPP can't be run while in background, you'll need to use the remote debugger from a separate device (different phone, tablet, laptop, desktop, etc.)

-[Unknown]

**Comment by Panderner** [comment]
> You may need to long-press the PPSSPP app, select app info (or otherwise get to the app info for PPSSPP), and then select Battery under Advanced. There, make sure PPSSPP is allowed to use battery in the background.
> 
> Some versions of Android may phrase this differently, but if PPSSPP can't be run while in background, you'll need to use the remote debugger from a separate device (different phone, tablet, laptop, desktop, etc.)
> 
> -[Unknown]

I selected Allow Background Running inside Battery Saver on the PPSSPP Still Didn't Work

**Comment by Panderner** [comment]
I used split-screen for chrome and PPSSPP and it happened:
https://streamable.com/fd7ft

**Comment by Panderner** [comment]
> The same thing happens to me, it's deactivated when I minimize. It should be built-in emulator itself, although I don't know if it's possible.

I don't use android emulators I'm using Realme C2

**Comment by Panderner** [comment]
Thanks but the newer builds is only for windows. The latest build for android stuck at v1.9.3-302-g3af63b6b8

**Comment by hrydgard** [comment]
Whoops, that's not good, didn't notice. I'll check what's going on.

**Comment by Panderner** [comment]
> Whoops, that's not good, didn't notice. The buildbot needs an NDK upgrade, I've notified @Orphis .

What!? The buildbot needs an NDK update?! What should I do for update latest builds for Android?

**Comment by hrydgard** [comment]
@Panderner  you don't have to care, we are fixing it.

**Comment by unknownbrackets** [comment]
Are you still seeing this?

-[Unknown]

**Comment by Panderner** [comment]
The latest build fixed this bug! Thank you! I'm closing now

**Comment by Panderner** [comment]
And I've updated to v1.9.3-351-gc363c16af on Android too!
