### ISSUE TITLE
Mednafen_pce_fast_libretro.pbp RetroArch PSP - Blue Screen Fix This Problem

### ISSUE THREAD

**Issue by penzovakid** [hrydgard/ppsspp#12642]
**Mednafen_PCE_Fast_libretro.PBP 
 RetroArch PSP**

* Blue Screen - Issue

* Fix This Problem
 RetroArch PSP Another Core Are Working Good But PCE Core Blue Screen.
![Screenshot_2020-02-24-21-34-44-970_org ppsspp ppsspp](https://user-images.githubusercontent.com/61286261/75168811-81342d00-574d-11ea-8e57-d0ef9fa71054.jpg)

* PPSSPP All Version

**Comment by Panderner** [comment]
This should be listed in #12481

**Comment by LunaMoo** [comment]
Refer to my post https://github.com/hrydgard/ppsspp/issues/12481#issuecomment-552916267 for how to run homebrew. It most likely just copies bytes to vram instead of rendering correctly as such it will never be fixed, switch to software rendering to see it's graphics. Either way we don't need duplicate issues so closing in favour of existing one linked above.

**Comment by Abdallah-amara021** [comment]
![Screenshot_20220505_155921_1_org ppsspp ppsspp](https://user-images.githubusercontent.com/104996176/166942142-1d73b9e9-f03e-48ce-9743-d5592f470e44.jpg)

I can't save the game dragon Ball z tag team any one know what should i do
![Screenshot_20220505_155919_org ppsspp ppsspp](https://user-images.githubusercontent.com/104996176/166942210-f0c94310-3ec8-4b92-95de-1a10936b84ac.jpg)
