### ISSUE TITLE
Phantasy Star Portable 2 Infinity sound stutters when "Load full game into RAM" checked

### ISSUE THREAD

**Issue by eleriaqueen** [hrydgard/ppsspp#12650]
### What happens?
In Phantasy Star Portable 2 Infinity (the only game I own), sound stutters a lot during videos AND gameplay while "Load full game into RAM" option is active.
After unchecking it and restarting the game sound playback is much smoother.

### What *should* happen?
"Load game into RAM" shouldn't degrade performance. 

### What hardware, operating system, and PPSSPP version?
PPSSPP Version :  1.9.3 - 287 - g25726deb4
CPU : Intel Core i7 7700 (3 Ghz, with 3.6 Ghz Boost mode)
RAM : 16 Go @ 3 Ghz (Dual Channel) .
Graphics Card : Nvidia GTX 1660 Ti
Storage : Samsung 850 EVO 500 Go SSD
OS : Windows 10 fully updated as of Feb 2020
Windows Memory Diagnostic says "No Problem Detected".

PPSSPP process uses around 15 % of CPU when running the game.

Edit : Audio section of PPSSPP's DevMenu shows there are lots of Underruns when the audio stutter happens.

**Comment by unknownbrackets** [comment]
This is very strange especially if it's reading off an SSD.  Are the games actually on your SSD, or are they on some sort of network or USB storage?

I'll note that the "Load game into RAM" option ought to yield no benefit on an SSD, but it should not cause stuttering either.  It should just waste RAM with no observable positive or negative performance impact.

How it currently works:

 * It reads the ISO or CSO into RAM, 256 KB at a time, starting from the beginning of the file.
 * On an 850 SSD, this should read a 1 GB ISO into RAM within 4 seconds.  There should be no performance impacts after 4 seconds.
 * If the game tries to read data not cached yet, it loads the requested data immediately.  Later, the precaching will skip loading this data.
 * On all systems except Android (and even on Android for reads below the 2GB mark, so 99.99% of them) precaching reads and random reads run concurrently.  There's only a slight window where cache is updated that things lock.

Because of that, the only negative performance impact, in theory, should be if the storage device's bandwidth is saturated when a random read request comes in.  If the precaching makes it too busy or too high latency to perform well, you might see this behavior.  That should definitely not happen on an SSD, but could happen with network storage perhaps.

-[Unknown]

**Comment by eleriaqueen** [comment]
Game is on my SSD yes as ISO (It's in " C:/Emu/ISO/ "). The only other storage device I have is an USB HDD but I don't have it connected often. Audio stutters still happen minutes after starting the game.
I almost tried every PPSSPP option in order to try and fix the issue then I thought, "let's try unchecking this thing that should never negatively impact performance" and it made a huge difference.
So if I understand how you described the way it works there shouldn't be buffer underruns once ISO is fully loaded into RAM, at least not -more- than before.
Oh by the way, my total RAM usage is typically 35 % when I have Vivaldi (Internet Browser) with a few tabs open, Discord, and Foobar2000 (Music Player) open as well.

**Comment by unknownbrackets** [comment]
Is the CPU usage 15% whether or not the option is enabled?  Or is it only 15% when the option is enabled?  Is that 15% continuous even on the pause screen?

-[Unknown]

**Comment by eleriaqueen** [comment]
15 % when standing still in-game, 16.5 % when moving about. Regardless whether the option is enabled or not.

**Comment by unknownbrackets** [comment]
Hm, I suppose you can use prim95 of memtest to check memory speed.  I would setup a ramdisk using [ImDisk](https://sourceforge.net/projects/imdisk-toolkit/) personally, but that's a bit complicated to setup.

I'm using an 8700 CPU with a GTX 9xx, and 16 GB RAM which should be pretty similar to your system (except that I have 12 cores.)  My RAM is 2x the Mhz of yours, but that should still be plenty enough.

"Cache full ISO in RAM" (from a mechanical disk) for me did cause a brief stutter at the start of the first video for Phantasy Star Portable 2, but after that all music and videos (including the story mode intro video) were nice and smooth.  Reloading the game doesn't reproduce the stutter, likely because Windows has cached the ISO.

We could probably improve the heuristics to make the precaching focus on areas that recently loaded data (which works well for streaming ISOs over network already), though it's still strange that this would affect your system so...

-[Unknown]

**Comment by eleriaqueen** [comment]
More RAM info... 
![aze](https://user-images.githubusercontent.com/4411178/75618777-467a2c80-5b73-11ea-88ac-146bb89fa7ed.png)

**Comment by unknownbrackets** [comment]
Oh, that's just showing one channel speed.  Your RAM is 3 Ghz (assuming you have it in the right slots), so just a bit slower than mine.

I will say, it's somehow more concerning that your CPU usage is 15% in game, unless you have texture scaling or other settings up.  Might try updating graphics drivers or switching the graphics backend PPSSPP is using (I'm using OpenGL.)  I don't know that that will affect this issue, though.

If anything, I'd be more concerned about your SSD read speed here.

-[Unknown]

**Comment by eleriaqueen** [comment]
I'm currently using OpenGL backend, and rendering at 4x Internal Resolution.
I'll try and look into my SSD read speeds.

**Comment by unknownbrackets** [comment]
Vsync wasn't implemented for those two before, and is now in the latest git builds.

That said, audio is affected by rendering speed because of how games work.  Games eke out tiny chunks of audio data in between rendering frames.  If emulation isn't able to keep up with the speed a PSP rendered at, then PPSSPP will also be behind on audio.

-[Unknown]

**Comment by benderscruffy** [comment]
v1.13.2-2369-gb06ea9784
just loaded full game into ram and had no sound stuttering during videos or gameplay
can be closed

**Comment by unknownbrackets** [comment]
Okay, I think we've made various improvements to performance and vsync since this, so let's hope it's resolved for everyone.  Haven't heard anyone report an issue like this since, either.

-[Unknown]
