### ISSUE TITLE
PPSSPP builds problem

### ISSUE THREAD

**Issue by spotanjo3** [hrydgard/ppsspp#12788]
I am using macOS Catalina the latest version. I build several emulators just fine on my macOS. This is the problem. What I do is:

git clone https://github.com/hrydgard/ppsspp.git

cd ppsspp

mkdir build

cd build

git submodule update --init --recursive

cmake ..

make 

then

SUCCEED but.....I got an error:

[100%] Linking CXX executable PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL
Undefined symbols for architecture x86_64:
  "_avcodec_parameters_from_context", referenced from:
      MediaEngine::setVideoStream(int, bool) in libCore.a(MediaEngine.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL] Error 1
make[1]: *** [CMakeFiles/PPSSPPSDL.dir/all] Error 2
make: *** [all] Error 2

HELP ?

**Comment by azoreseuropa** [comment]
Hello. Can you help me out ?

**Comment by unknownbrackets** [comment]
That should only be called when `LIBAVFORMAT_VERSION_INT >= AV_VERSION_INT(57,33,100)`, which it should not be if you are using the ffmpeg submodule.

Is it possible you ran cmake before `git submodule update --init`?  It may cache include paths.

As I mentioned, it could also help to recompile ffmpeg via `cd ffmpeg && ./mac_x86-64.sh`.

-[Unknown]

**Comment by azoreseuropa** [comment]
Cloning into '/Users/azoreseuropa/ppsspp/ffmpeg'...

And it is stuck.

**Comment by azoreseuropa** [comment]
Thanks to someone at discord... You have to brew unlink ffmpeg and build it. It works!
I brew install ffmpeg before. I shouldn't and now everything's working properly. MacOS PPSSPP update to the latest version works!

**Comment by unknownbrackets** [comment]
Hm, sounds like there's some case where we use system ffmpeg by mistake.

-[Unknown]

**Comment by azoreseuropa** [comment]
> Hm, sounds like there's some case where we use system ffmpeg by mistake.
> 
> -[Unknown]

I don't know. I just type brew install ffmpeg and it caused the problem for build the PPPSPP so I unlink it through terminal and try again and everything's working fine.

**Comment by firodj** [comment]
What is your cmake generator? Xcode or Makefile, since it may behave differently.

I found same issue 3 years ago, on my case the `Core` package that depends on FFmpeg using system `avcodec.h` instead vendored ffmpeg (in `ffmpeg/macosx/universal`). This turns out when compiling the `MediaEngine.cpp` the newest functions is being used with expectation not being used because guarded by `#if LIBAVFORMAT_VERSION_INT`. Then the linker throw error because cannot find that newest function in the vendored ffmpeg.

It is becuase when invoking clang,  the include path for system ffmpeg (`/usr/local/include`) comes first before (`./ffmpeg/macosx/universal/incude`). So to solve this issue we should change the orders, here is what I've done:

```
if(FFmpeg_FOUND)
	target_compile_definitions(${CoreLibName} PRIVATE USE_FFMPEG=1)
	set_target_properties(${CoreLibName} PROPERTIES NO_SYSTEM_FROM_IMPORTED true)
	target_include_directories(${CoreLibName} BEFORE PUBLIC ${FFmpeg_INCLUDE_avcodec})
	target_link_libraries(${CoreLibName}
		FFmpeg::avcodec
		FFmpeg::avformat
		FFmpeg::avutil
		FFmpeg::swresample
		FFmpeg::swscale
		${ZLIB_LIBRARY}
	)
endif()
```

Another note:, who add system `/usr/local/include` path? This syntax in my case:
```
if(PNG_FOUND)
	include_directories(${PNG_INCLUDE_DIRS})
else()
```

**Comment by spotanjo3** [comment]
I used Makefile.

**Comment by firodj** [comment]
I tried using Makefile, and it build successfully.

**Comment by unknownbrackets** [comment]
Hm, NO_SYSTEM_FROM_IMPORTED seems slightly dangerous, but should be fine.  Want to open a pull request?

-[Unknown]
