### ISSUE TITLE
Make Full screen enabled by default

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#12806]
Some Emulators defaults to immersive mode (Retroarch, Redream and M64Plus FZ) but PPSSPP turned off immersive mode by default. Can you make Full screen enabled by default?

**Comment by hrydgard** [comment]
I could very easily, but should I? I'm not sure. I personally kind of like having the buttons there by default.

**Comment by Panderner** [comment]
Most newer Android games always enables immersive mode including older games added this feature via update. Immersive mode is introduced in Android 4.4

**Comment by Panderner** [comment]
![Screenshot_2020-04-08-17-55-34-97_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/78771217-68f93400-79c2-11ea-9f1e-a58c993a4362.png)
Look at this full screen feature. It's disabled by default.

**Comment by hrydgard** [comment]
I very clearly explained that it's intentionally disabled by default, no need to show a screenshot.

My current opinion is that immersive mode is confusing because it's hard for at least new users to find the back button. But if more and more games move over to it, eventually it will be ok since everybody will be used to it anyway. I'm not sure if now is the time yet.

**Comment by Panderner** [comment]
Most newer phone and tablets has no built-in buttons. It's simple to just swipe left in the end of right side (swipe up in the bottom side in portrait mode)

**Comment by hrydgard** [comment]
Turned this on now.
