### ISSUE TITLE
We should disallow overclocking on some games that can't handle it

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#12811]
An example is here: https://github.com/hrydgard/ppsspp/issues/5468

This would probably best be done with a compat.ini setting.

**Comment by LunaMoo** [comment]
We already have a compat ini for informing user about games requiring default CPU clock.

 I would be for blocking it for all games broken by it, not just informing how it's done now, especially since it doesn't take off the freedom to just change compat.ini settings for those that really want to, but this also means Tekken and God of War series. Those are very popular and people choose to break those games just to play part of it at single digit FPS "full speed". Ofc later then say PPSSPP sucks because their game crashes, scripted events never trigger etc. so it kind of evens out the hate the project get's for locking that option from those games.

**Comment by unknownbrackets** [comment]
I guess we can just show the message too.

Do we show the message if they change the setting while in game?

-[Unknown]

**Comment by LunaMoo** [comment]
Nah, currently it's shown only on boot.
 If left at informing instead of disabling it, it definitely should be made more annoying, to show on activation as well as every time save state is loaded if the setting was ever affecting it.

**Comment by Panderner** [comment]
Why God of War Ghost of Sparta needs the CPU clock to be default?

**Comment by hrydgard** [comment]
Who knows? It just does.

**Comment by unknownbrackets** [comment]
Probably the developer never tested changing the CPU clock, so didn't know they had bugs.

Then again, hard to blame the developer because changing the CPU clock was not actually an option on OFW PSPs.  Just like it's hard to blame developers for not testing PSP games at 1080p.

-[Unknown]
