### ISSUE TITLE
Burnout Dominator Things not rendering correctly with DX11 and DX9

### ISSUE THREAD

**Issue by Aeylie** [hrydgard/ppsspp#12831]
### What happens?
![Burnout Dominator Glitch](https://user-images.githubusercontent.com/63867248/79589994-99ce1d00-80d6-11ea-9035-f1b1f0d89371.png)
![Burnout Dominator Glitch 2](https://user-images.githubusercontent.com/63867248/79590421-4b6d4e00-80d7-11ea-8b6f-06919886189a.png)

In Burnout Dominator (I'm using the EU Version) both in the car selection screen and while racing cars have missing textures and objects seem to be rendered in incorrect order (I think? I don't how you actually call what is happening :P)

This only happens with DX11 and DX9, everything seems to work fine with OpenGL.
Don't know about Vulkan as my GPU doesn't support it.

I'm not sure if this is a duplicate because I found another closed issue (#10655) that seems to be the same but from 2018 and the other issue linked there (#11557) is also closed.

### What *should* happen?
Cars shouldn't have missing parts and objects behind other objects shouldn't appear in front of them.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Tested on PPSSPP v1.9.3 and PPSSPP v1.9.3-683-gcc916180b

OS: WIndows 10 Home 64 bit version 1909 (build SO 18363.778)

PC: Lenovo Yoga Pro 3
Processor: Intel(R) Processor 5Y70 CPU @ 1.10GHz (4CPUs), ~1.3GHz
Ram: 8GB
GPU: Intel(R) HD Graphics 5300
DirectX Version: DirectX 12

I'm using Buffered Rendering, and changing to Skip Buffer Effects has no effect.
I tried switching the Performance Options on and off but nothing made a difference.
Turning off Simulated Block Transfer Effects also didn't change anything.
I/O Timing and Forcing Real Clock Sync have no effect.
PSP CPU Clock is set to Auto and Fast Memory is off.

I'm not using any hacks.

**Comment by leopard20** [comment]
It's a depth issue. It could be a driver bug.
Upload a frame dump of that scene so the devs can analyze it:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by Aeylie** [comment]
Here it is,
It's from the beginning of a race.

[recording.zip](https://github.com/hrydgard/ppsspp/files/4495107/recording.zip)

**Comment by unknownbrackets** [comment]
Apparently, Mali had z-fighting issues:
https://github.com/hrydgard/ppsspp/commit/fc0f3513bd94bbe0b3449380882a1f2d00fd6455

So we disabled accurate depth on Mali.  But we actually enable it now in most other games and places.  Since Direct3D requires depth to be ordered, I don't understand how we can disable accurate depth for any driver there, but we only disable it for a few games (including this one), and only on Intel and more obscure GPUs - not on AMD or NVIDIA.

I'd say Direct3D needs to ignore this "DisableAccurateDepth".

If I disable accurate depth on NVIDIA, I reproduce the problem in the dump.  It's because the Direct3D API simply doesn't support inversed depth, has nothing to do with driver or GPU vendor.  The PSP API also happens not to support inverse depth, but only the accurate depth path actually maintains that.

-[Unknown]
