### ISSUE TITLE
Mana Khemia 2 | Background Disappear During Conversation on Vulkan

### ISSUE THREAD

**Issue by C4rrotMilk** [hrydgard/ppsspp#12858]
What happens?

As mentioned in the title.

Vulkan
![Screenshot_20200427-172234](https://user-images.githubusercontent.com/38028835/80358134-8842fd00-88ae-11ea-826f-9cab4a341b7f.jpg)

OpenGL
![Screenshot_20200427-172359](https://user-images.githubusercontent.com/38028835/80358188-985adc80-88ae-11ea-8320-e24784b4d3db.jpg)

What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Huawei Mate 9 MHA-L29 | Kirin 960 Mali-G71 MP8 | Android 8.0.0

[Dump.zip](https://github.com/hrydgard/ppsspp/files/4538810/Dump.zip)

**Comment by Gamemulatorer** [comment]
#12934 Has merge any improvement @C4rrotMilk ?

**Comment by unknownbrackets** [comment]
The game downloads the frame once, then stretches it to a 256x256 surface (both Mana Khemia and Mana Khemia 2 do this.)

The stretch is done with depth=32767, but this transforms to 0.  Viewport scale/offset is -/+32500.  Depth clamp is enabled.

Min Z is 0001, and max Z is fde8.  Depth test is enabled and ALWAYS (same as STENCIL.)  It does this to set stencil to 1 on each pixel during the stretch.

Because of the minz, it clips this and doesn't draw it.

[Here's a dump of the actual draw](https://github.com/hrydgard/ppsspp/files/4671334/ULJM05519_.12858_khemia2_dialog_black.zip) - it's hacked together because it's the one frame, so ignore the repeating.
On a PSP, it does indeed draw:
![ULJM05519_#12858_khemia2_dialog_black](https://user-images.githubusercontent.com/191233/82724152-e1713700-9c88-11ea-9596-8b3cbba57794.png)

We draw nothing, and in software rendering too.  Maybe it's some precision issue in the transform?

Mana Khemia 1 draws a bit differently, when doing the same thing.  It sets minz to 0 and transforms a bit differently.

-[Unknown]

**Comment by C4rrotMilk** [comment]
Still the same in latest build. It's not really a big deal since I can play with OpenGL, just take your time :D

**Comment by Gamemulatorer** [comment]
@C4rrotMilk issue is already fixed in what build of ppsspp?

**Comment by Spicy-Kimchi** [comment]
v1.10.3-46-g6009bf7b7 https://github.com/hrydgard/ppsspp/pull/12952

**Comment by unknownbrackets** [comment]
Does it work on all backends?  I thought there was still some depth issue.

-[Unknown]

**Comment by Spicy-Kimchi** [comment]
Didn't notice any issues on DX9 & DX11 as well. I will report if there got issues on other games. 🤔
