### ISSUE TITLE
Need For Speed Own The City - Can't reach full FPS without frameskip

### ISSUE THREAD

**Issue by HiImBrala** [hrydgard/ppsspp#12871]
### What happens?
Well,game can't go 30/30.Frameskip needed,performance same on 1x Resolution,frameskip needed

### What *should* happen?
Game should run fine

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues
PPSSPP GOLD 1.9.3
GPU:Intel (HD) Graphics
OS:Windows 8.1

Phone:Xiaomi Redmi 6
GPU:PowerVR Rogue GE8320
OS:MIUI 10.2.3.0 Android 8.1

P.S - I'm sure this is not my phone/PC issue since report.ppsspp.org results use frameskip to achieve perfect score

**Comment by Panderner** [comment]
It means your phone is not powerful enough to run this game at full speed. Some mid-range devices runs full speed for this game. Next time you buy a powerful phone.

**Comment by HiImBrala** [comment]
> It means your phone is not powerful enough to run this game at full speed. Some mid-range devices runs full speed for this game. Next time you buy a powerful phone.

Maybe if you saw last message in post

**Comment by LunaMoo** [comment]
PPSSPP reporting is not a place to believe in everything you see, but a place where anyone can submit anything they want based on their humour. We have tons of completely invalid reports or reports with settings that has no sense whatsoever in there and reports which does not match actual known compatibility. People give 3 stars to games they like on hardware which can't ever run it at full speed and mark perfectly playable games as "doesn't boot" just because they dislike the gameplay.

 Either way there are many versions of this game and many "perfect" reports, not all using frameskip. I also just tested this game and get easily 700% speed with 10x render res on a pc with actual gpu. Your hardware is simply too weak for the game and most likely for many other games and nothing can be done to "fix" that as you can't optimize everything to run on a potato and the users should finally stop expecting that and mentioning they use GOLD version just to put a pressure on Henrik. Gold release is just a form of donation, does not matter at all for functionality, my personal builds are violet, color doesn't matter.

**Comment by unknownbrackets** [comment]
Reporting noise aside, I do think in general people give a sense of what settings work or don't work.  Plus you get screenshots, like this one with slow effects disabled:
https://report.ppsspp.org/uploads/ULUS10114_1.00/compat-330398.jpg

Anyway, I tend to agree that this is a device power issue.  For example, my old Pixel gets 21 FPS on "Sling Shot Extreme Unlimited" here:
https://benchmarks.ul.com/en/hardware/phone/Google+Pixel+review

This phone, on the other hand, gets 3 FPS.  It just doesn't have the graphics processing power to handle emulating all PSP games.

"Intel (HD) Graphics" is not really very specific, it refers to a whole family of graphics cards that range from the super weak to the okay.  If it's not a laptop and is newer than 5 years old, I'd be surprised if it can't run this game on modest settings, though.

If you go to Start -> Run -> type "dxdiag" (without quotes) and hit enter, you'll get a window pop up.  It may say something about WHQL, it's okay to say yes (doesn't really matter.)  What does it say under "Processor"?

For example, my processor is an Intel Core i7-8700 CPU.  That means it comes with Intel UHD Graphics 630.  I can only get about 90 FPS in God of War with that GPU, but I get much better with an NVIDIA GTX 9xx card.

-[Unknown]

**Comment by HiImBrala** [comment]
> Reporting noise aside, I do think in general people give a sense of what settings work or don't work. Plus you get screenshots, like this one with slow effects disabled:
> https://report.ppsspp.org/uploads/ULUS10114_1.00/compat-330398.jpg
> 
> Anyway, I tend to agree that this is a device power issue. For example, my old Pixel gets 21 FPS on "Sling Shot Extreme Unlimited" here:
> https://benchmarks.ul.com/en/hardware/phone/Google+Pixel+review
> 
> This phone, on the other hand, gets 3 FPS. It just doesn't have the graphics processing power to handle emulating all PSP games.
> 
> "Intel (HD) Graphics" is not really very specific, it refers to a whole family of graphics cards that range from the super weak to the okay. If it's not a laptop and is newer than 5 years old, I'd be surprised if it can't run this game on modest settings, though.
> 
> If you go to Start -> Run -> type "dxdiag" (without quotes) and hit enter, you'll get a window pop up. It may say something about WHQL, it's okay to say yes (doesn't really matter.) What does it say under "Processor"?
> 
> For example, my processor is an Intel Core i7-8700 CPU. That means it comes with Intel UHD Graphics 630. I can only get about 90 FPS in God of War with that GPU, but I get much better with an NVIDIA GTX 9xx card.
> 
> -[Unknown]

If it is device power,closing this,sorry for any incovenience that happened.We need something that would inform us if the game is slow because of device or bugs,so you wouldn't get openned issues like this
