### ISSUE TITLE
[Libretro] Core hasn't been built for Windows since early October.

### ISSUE THREAD

**Issue by bslenul** [hrydgard/ppsspp#12893]
Hey! There's no issues board for the the RetroArch core so I'm posting here, if that's not OK sorry in advance, I'll close the issue!

Latest version of PPSSPP core currently available on Windows is 0b17dd0 which is from early October.
Today's buildbot logs for x86: http://paste.libretro.com/206207
And for x64: http://paste.libretro.com/206182

Don't know much about compilation and stuff but there's this same error on both logs: `../ext/native/image/png_load.cpp(8): fatal error C1083: Cannot open include file: 'png.h': No such file or directory`.

Unfortunately that 0b17dd0 version has a few issues like black screen in God of War games (#12622) and weird font issues when using latest assets:

![Grand_Theft_Auto_-_Liberty_City_Stories-200429-214636](https://user-images.githubusercontent.com/33353403/81818151-ef5ae580-952d-11ea-94a7-41f97bfa1279.png)

Which is a problem for a lot of people because the Libretro docs tell us to grab the latest: https://docs.libretro.com/library/ppsspp/#bios 😅 

I built that same commit on my Linux VM to check if those were Windows only issues, but they also happen, black screen on GoW games even happens on the standalone with that commit.

**Comment by LunaMoo** [comment]
PPSSPP project does not provide any libretro core builds. You can get latest PPSSPP from the buildbot provided by Orphis - https://buildbot.orphis.net/ppsspp/ or you can build PPSSPP yourself. 

 Either way support for lack of libretro builds should go to libretro project or whoever maintains their builds and is not an issue of PPSSPP nor even a libretro core of PPSSPP.

 As such closing.

**Comment by unknownbrackets** [comment]
In previous versions (including presumably that version), you have to use the same assets as the PPSSPP version, because metadata about them is included in the program.

This has caused confusion, but not that much.  However, with libretro docs suggesting you should pull the latest PPSSPP assets no matter what, we've changed the way assets work so the metadata is not part of the program anymore and is part of the assets.  You may still get missing icons or letters, but not total garbage.

But of course, that doesn't help older versions that still had the metadata in the code.

To say, I still think it's kinda silly to expect people to have to search for and download the assets separately.  Obviously, releases of PPSSPP proper just include the assets...

Honestly not even sure how to test an arbitrary build and how it runs (I'm told it's a pain.)  That said, I've made a blind change that may help this compilation error - I'd assume the build server must not have libpng headers.  See #12895.

-[Unknown]

**Comment by bslenul** [comment]
Thank you for the reply! I can't figure out how to build the core so we'll see in a few day when the buildbot will try to compile it again with these changes :p And if it doesn't work, thank you anyway for looking at the issue, really appreciated 👍 

And sorry for posting here! On the Libretro PPSSPP repo there's no issues board, and since I saw here a few issues with the "Libretro" tag, I thought \*maybe\* it would be OK.

Thanks again!
