### ISSUE TITLE
Prince of Persia rival swords graphics glitch lines on flames

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#12943]
### What happens?
There are lines on flames
![Screenshot_20200522-004347](https://user-images.githubusercontent.com/37603562/82584682-685ddb00-9bc7-11ea-802b-244f7ea7b673.png)
### What *should* happen?
![Screenshot_20200522-005448](https://user-images.githubusercontent.com/37603562/82584737-7ca1d800-9bc7-11ea-8c4f-4b380aabfdd3.png)
screenshot from PSP gameplay on yt https://youtu.be/CBNq1u8cs0o
### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Android 6.0.1
Mali-450
GLES 2.0
PPSSPP v1.9.3-908

**Comment by Gamemulatorer** [comment]
I finally manage to captured ge dump for this game 😅 
[ULUS10240.zip](https://github.com/hrydgard/ppsspp/files/4665223/ULUS10240.zip)

**Comment by Gamemulatorer** [comment]
@Panderner would you like to test if this can repro on your c2 phone?

**Comment by Panderner** [comment]
> screenshot from PSP gameplay on yt https://youtu.be/CBNq1u8cs0o

no. that video source is not recorded on a real PSP they recorded a PPSSPP on Android Phone Instead.

**Comment by Gamemulatorer** [comment]
@Panderner Im asking if you experiencing the same issue that I have encountered 🤷

**Comment by hrydgard** [comment]
Is this a new error, or does it happen in earlier versions too?

**Comment by Panderner** [comment]
> @Panderner Im asking if you experiencing the same issue that I have encountered

@Gamemulatorer Did you tested this game on your Real PSP or PS Vita?

**Comment by Gamemulatorer** [comment]
> Is this a new error, or does it happen in earlier versions too?

Yes it also happen in a earlier version of ppsspp.

**Comment by unknownbrackets** [comment]
Can you try to make a dump with the latest git build?  This has CLUT alignment issues.

Also, the fire in the dump is red.  Is that expected or potentially because of the alignment issue?

Actual output (specks is from alignment issue I think):
![actual](https://user-images.githubusercontent.com/191233/82836926-7e47f600-9e7c-11ea-9bbd-b698a529d804.png)

Software rendering:
![softgpu](https://user-images.githubusercontent.com/191233/82836935-8869f480-9e7c-11ea-8a5c-3f6779e2efe0.png)

GLES:
![gles](https://user-images.githubusercontent.com/191233/82836991-b0595800-9e7c-11ea-9ad6-1fd1e661b8ef.png)

There are some slight differences but it looks close.  Obviously the glitching is different, and ideally should be the same too...

-[Unknown]

**Comment by Gamemulatorer** [comment]
Here yeah 👇
[ULUS10240.zip](https://github.com/hrydgard/ppsspp/files/4679017/ULUS10240.zip)

**Comment by unknownbrackets** [comment]
Thanks, this one is interesting.

Actual PSP rendering:
![persia-white-triangle](https://user-images.githubusercontent.com/191233/82846005-aabf3a80-9e9b-11ea-881f-47e353eb72c5.png)

That white triangle looks suspicious.  Either it's a bug in the game itself, or we've got an issue that caused it to calculate the wrong coordinates/etc. for that on the CPU side.

-[Unknown]

**Comment by Gamemulatorer** [comment]
No more lines on flame using the latest git build
![Screenshot_2020-08-07-17-29-08](https://user-images.githubusercontent.com/37603562/89632291-8983bd00-d8d4-11ea-948f-9aad884eab7b.png)
