### ISSUE TITLE
Feature Request: restore software rendering ui setting on android

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#12958]
As the title say, I know there's a compat.ini to enable SW rendering but that hussle.
Also SW rendering is better now compare before, will you consider restoring the ui setting?

**Comment by LunaMoo** [comment]
Situation didn't changed much from when it was hidden.

 Software rendering was hidden on mobiles since it was never ment for playing games with, but to debug hardware renderers, it's still less accurate and horribly slow, some common features are also very iffy with it and a lot of negative reports were from people abusing it accidently or through some confusion.

 Under normal conditions even top end desktop cpu's might not draw most 3D games at full speed. Some 2D games are much lighter to draw for software rasterizer, but even then a game which had it forced for compatibility reasons uses a specialized hack without which it becomes much slower, hence it's not recommended to run Darkstalkers on android with original aspect ratio - since it disables the hack(at least from in-game options, post process shader correction should be fine).

 Just because SR doesn't really make use of your GPU effectively avoiding horrible drivers of some unlucky mobile devices, doesn't mean it makes games playable on those devices.

 The only place where IMO it would be worth re-enabling software rasterizer option for android are homebrew apps/games as those commonly require it do display anything, but can't be effectively enabled via game ID since they don't have one and need a fake one to be generated.

**Comment by hrydgard** [comment]
I hid it on Android because I was seeing unacceptable amounts of crashes from the software renderer in the Google Play report. Presumably, large amounts of users were enabling it either by accident or as an experiment and crashing (at the time it had crash bugs and it may still have).

Also, it's practically unusable on mobile anyway and indeed is more meant as a development tool.

**Comment by Gamemulatorer** [comment]
Close via https://github.com/hrydgard/ppsspp/commit/6fd082f14113aaa89b3679e293c26a9627fef16b
