### ISSUE TITLE
Having problems with battery drain  

### ISSUE THREAD

**Issue by HelloDefender12** [hrydgard/ppsspp#12995]
Good Morning, Hydgard

I am having problems with my iOS 12 device after playing ppsspp 1.9.3 dev latest I encounter battery drain issues even if ppsspp is off
![AA4801AB-9B86-4F7F-ACFD-4703532D03C3](https://user-images.githubusercontent.com/30011736/83576797-1f157000-a565-11ea-8bd3-b431b15bcf53.png)

Battery even doesn’t charge properly after playing ppsspp

**Comment by HelloDefender12** [comment]
![D473F839-CCC9-4C4E-8124-1147E8775180](https://user-images.githubusercontent.com/30011736/83576829-3bb1a800-a565-11ea-8d6d-0b054e477f32.png)

**Comment by HelloDefender12** [comment]
Charging current just got low from 605 Mah to 457 Mah

**Comment by hrydgard** [comment]
That is odd, but I doubt it really has something to do with PPSSPP. Drain when PPSSPP is not running at all cannot possibly be affected.

**Comment by HelloDefender12** [comment]
Maybe It affects Battery calibration XD

**Comment by HelloDefender12** [comment]
I’ll try recalibrating my battery

**Comment by LunaMoo** [comment]
No idea about iOS, but it's normal for the OS to charge battery faster at low level than when it's near full, it's safer for the battery, that's kind of why all claims about fast charge techniques advertise going from almost empty to like 50% instead of advertising going to full(but fast charge in general is bad for the battery chemistry, reducing it's capacity much quicker than standard charge over time),

**Comment by fahadrashid7705** [comment]
try ppsspp emulated cpu clock limited like 111mhz

**Comment by unknownbrackets** [comment]
I'm going to mark this closed given the comments above.  We can't do much about what your OS does when PPSSPP isn't running...

-[Unknown]
