### ISSUE TITLE
Delete the Android.mk build system?

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#13145]
The worst of the horrendous performance problems of command-line gradle and Android Studio have long been fixed, and it's actually quite a tolerable experience these days. 

Anyone opposed to killing off the old Eclipse-compatible Android.mk build? Note that I am fine with keeping it if there are good reasons, but not exactly sure what those would be today.

(This would require updating the build commands on @Orphis buildbot, too).

**Comment by boy13epic** [comment]
i think delete

**Comment by unknownbrackets** [comment]
Travis still uses Android.mk.  I think Orphis might actually be updated.

From what I recall, the biggest problems were:

1. Setting up the SDKs/NDK using Gradle on Travis required tricks to agree to the licenses.  It's [now more natively supported by Travis](https://docs.travis-ci.com/user/languages/android/), which will probably make that easier.  Although we had maybe already worked that part out.

2. If we want to see errors from Travis builds, we seemed to have two options:
    Option 1. Enable verbose gradle logging.  Build failures will not be visible because the log will be truncated by Travis before they happen.
    Option 2. Disable verbose gradle logging.  Build failures will not be visible because they will not be output.

3. Gradle was buffering all cmake output (even if you tried to filter or grep out the pointless noise) until the end of the build, which made any changes to Travis very painful.  Other systems output the status in realtime, so you can see if caching is working, warnings are appearing, or etc. right away.

From my perspective, if item 2 above is still an issue, gradle fails at a very basic level as a build system.  It's like if I built an emulator, but all controller input takes 3+ seconds to register OR you can write all the controller input in a text file, which it'll run without lag, but you cannot change it without restarting the emulation from the beginning.  I'm sure some people would find that useful (TAS), but I'd consider that a basic failure as a general emulator too.

Combined with item 3, it zeros my interest in working on any Travis scripting/caching for it, since not only will the process be painful, but the results will be entirely useless anyway.  I have no real interest in Travis just saying "CMake external build failed" with no detail.

For my local purposes, I'm still using the Android.mk build system, which works for now and allows me to still control parallel jobs, enable debugging, etc. without much grief.

At the time, it also seemed like C++ debugging (breakpoints and stepping, not just symbols etc.) wasn't working but I have to assume that, at least, is working fine now.

Importantly, the mk build system also allows me to build ppsspp_unittest and pppsspp_headless as static binaries and run them directly via adb, which has proved very useful in debugging and fixing specific problems (especially jit bugs.)  I assume this cannot be done with gradle but probably can be done with cmake directly, but isn't setup right now.

-[Unknown]

**Comment by hrydgard** [comment]
Thanks for your writeup Unknown!

While I do believe that there are solutions now for a couple of the issues (for example, I can get continuous log output from the compilation on my machine nowadays), it's clear that we can't cover all these usecases with the gradle build. So Android.mk sticks around. 

When I get this idea again in a couple of years and have forgotten the arguments, this will be a good reference :)

**Comment by unknownbrackets** [comment]
If that's at least working, it might be more reasonable at least to use careful grep strings to workaround 2.  And if that's actually fixed now, then I think switching would be more realistic.

It's not that I want multiple build systems or anything, and I assume eventually the .mk stuff won't even work anymore.  But it's no good if it doesn't do the right things.

-[Unknown]
