### ISSUE TITLE
Where is my Heart - Weird Flickering - 1.10.2

### ISSUE THREAD

**Issue by itsXPCT** [hrydgard/ppsspp#13152]
### What happens?
Hi,me again.I found some issue where game has some weird flickering that appears and disappears in a second ,i tried to catch it but it is really hard to do so,but i managed to catch it somehow.

Game shows white/black squares for a second,like this:
![NPUZ00243_00013](https://user-images.githubusercontent.com/67833785/87512096-bac2f180-c676-11ea-94f5-a851490180b4.jpg)

### What *should* happen?
Game should be normal,like this:
![NPUZ00243_00012](https://user-images.githubusercontent.com/67833785/87512261-fb226f80-c676-11ea-9f0b-46095defc5d2.jpg)

Tested on 3 different devices,including D3D backends at PC.

TIA

**Comment by boy13epic** [comment]
yea,it’s flicker

**Comment by Gamemulatorer** [comment]
No screen flickering using latest git build on my but super slow performance.
Screen record
[recording_20200715_174311.mp4.zip](https://github.com/hrydgard/ppsspp/files/4924351/recording_20200715_174311.mp4.zip)

### Logs
40:59:723 mainThread   N[SYSTEM]: Debugger/Record.cpp:518 Recording starting on display...
40:59:755 idle0        N[SCEDISP]: HLE/sceDisplay.cpp:534 Dropping frames - budget = 33.37ms / 30.0fps, actual = 35357.79ms (+35324.42ms) / 0.0fps
Kernel processing time: 46.00 ms
Slowest syscall: sceGeListUpdateStallAddr : 0.72 ms
Most active syscall: sceKernelLibcClock : 34.77 ms
DL processing time: 9.24 ms
Draw calls: 371, flushes 371, clears 1
Cached Draw calls: 0
Num Tracked Vertex Arrays: 0
GPU cycles executed: 38586 (20.000000 per vertex)
Commands per call level: 5593 0 0 0
Vertices submitted: 1370
Cached, Uncached Vertices Drawn: 0, 1998
FBOs active: 3
Textures active: 261, decoded: 0  invalidated: 0
Readbacks: 0, uploads: 0
Vertex, Fragment, Programs loaded: 3, 4, 4

40:59:756 idle0        I[G3D]: Common/TextureCacheCommon.cpp:1585 Texture cached cleared from 261 textures
40:59:756 idle0        I[FRAMEBUF]: Common/FramebufferCommon.cpp:1719 Destroying FBO for 04000000 : 480 x 272 x 1
40:59:756 idle0        I[FRAMEBUF]: Common/FramebufferCommon.cpp:1719 Destroying FBO for 040cc000 : 512 x 512 x 1
40:59:756 idle0        I[FRAMEBUF]: Common/FramebufferCommon.cpp:1719 Destroying FBO for 04044000 : 480 x 272 x 1
40:59:799 mainThread   I[FRAMEBUF]: Common/FramebufferCommon.cpp:373 Creating FBO for 04044000 : 480 x 272 x 1
40:59:827 mainThread   I[FRAMEBUF]: Common/FramebufferCommon.cpp:373 Creating FBO for 040cc000 : 512 x 512 x 1
Debugger disconnected
Debugger connected
45:30:794 mainThread   N[SYSTEM]: Debugger/Record.cpp:518 Recording starting on display...
45:30:828 idle0        N[SCEDISP]: HLE/sceDisplay.cpp:534 Dropping frames - budget = 33.37ms / 30.0fps, actual = 6410.03ms (+6376.66ms) / 0.2fps
Kernel processing time: 50.19 ms
Slowest syscall: sceDisplaySetFrameBuf : 4.89 ms
Most active syscall: sceKernelLibcClock : 33.57 ms
DL processing time: 10.09 ms
Draw calls: 370, flushes 370, clears 1
Cached Draw calls: 0
Num Tracked Vertex Arrays: 0
GPU cycles executed: 38476 (20.000000 per vertex)
Commands per call level: 5578 0 0 0
Vertices submitted: 1366
Cached, Uncached Vertices Drawn: 0, 1992
FBOs active: 3
Textures active: 262, decoded: 0  invalidated: 0
Readbacks: 0, uploads: 0
Vertex, Fragment, Programs loaded: 4, 4, 6

45:30:829 mainThread   I[G3D]: Common/TextureCacheCommon.cpp:1585 Texture cached cleared from 262 textures
45:30:830 mainThread   I[FRAMEBUF]: Common/FramebufferCommon.cpp:1719 Destroying FBO for 04044000 : 480 x 272 x 1
45:30:830 mainThread   I[FRAMEBUF]: Common/FramebufferCommon.cpp:1719 Destroying FBO for 04000000 : 480 x 272 x 1
45:30:830 mainThread   I[FRAMEBUF]: Common/FramebufferCommon.cpp:1719 Destroying FBO for 040cc000 : 512 x 512 x 1
45:30:890 mainThread   I[FRAMEBUF]: Common/FramebufferCommon.cpp:373 Creating FBO for 04000000 : 480 x 272 x 1
45:30:920 mainThread   I[FRAMEBUF]: Common/FramebufferCommon.cpp:373 Creating FBO for 040cc000 : 512 x 512 x 1

**Comment by EX-e-LD** [comment]
@Gamemulatorer 
Wrong.Honor 9S,game runs full speed,no flickering on OpenGL,maybe Direct3D bug?

**Comment by Panderner** [comment]
I can't reproduce this issue in my POCO M3 on OpenGL and Vulkan.
![Screenshot_2021-02-04-20-23-16-961_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/106892458-1219d380-6727-11eb-90da-7f8d2466ab2b.jpg)

**Comment by unknownbrackets** [comment]
Does this only happen with vertex cache or lazy texture hashing on?  Or with secondary texture cache on?

-[Unknown]

**Comment by Panderner** [comment]
> Does this only happen with vertex cache or lazy texture hashing on? Or with secondary texture cache (retain changed textures) on?
> 
> -[Unknown]

Even vertex cache, lazy texture caching and retained changed textures is turned on it does not happen.

**Comment by unknownbrackets** [comment]
I checked chapter 3 (this area) and do see this bug in Direct3D 11.

The game renders the actual level to a temporary surface (0x040cc000), and then draws the "shattered" version of it to the screen from there.  The glitches, when they occur, are visible even on the shattered surface.  Here's an example:

![where_is_my_heart_d3d11](https://user-images.githubusercontent.com/191233/127961661-2479a330-5622-4565-afa1-1d5b4d39d575.png)
(in my case the glitch was in a different location.)

The game draws in layers of 32x32 tiles, similar to an old school tile based game.  Sometimes, one of the tiles is incorrectly drawn is a white box like this.

I caught one of the glitches, and it was really just the same as the previous tile draw with a different texture address.  Then I noticed the intro menu screen even has this glitch, which is easier to debug because it's simpler and doesn't do the FBO thing.

The flickering is pretty cyclical, and when I watch debug statistics the GPU cycles, draw calls, and vertices all jump during the glitchy frames.  But not texture decodes, so this isn't some texture cache issue, presumably.  The spike in stats is followed by 0 stats, probably caused by the game rendering (incorrectly) at 30.30 FPS instead of 29.97 FPS.

This cycle happens on all backends, so it's not the direct cause.  That said, replacing the function at 088E2D5C with:
```asm
addiu sp, sp, -0x10
sw ra, 0(sp)
jal zz_sceDisplayWaitVblankStart
nop
lw ra, 0(sp)
jr ra
addiu sp, sp, 0x10
```

"Fixes" the issue and the FPS, and also improves the performance of the game (doubling the max frame rate when I fast forward.)  Its current timing function is very inefficient, as well as getting the wrong FPS.

This does seem to be draw state related, though, as I disabled all draw state caching and it went away.  Debugging more...

-[Unknown]
