### ISSUE TITLE
Add a fps limiter to help devices that cannot run games at 60 fps

### ISSUE THREAD

**Issue by gianca54** [hrydgard/ppsspp#13185]
On some devices, the ability to run a game at 60 fps is not possible, but in some cases the emulator only allows you to run the game at high fps, causing the game to run at lousy speed and unstable fps.
So I recommend adding a fps limiter to the ppsspp emulator, since for more settings to quickly return the game and lowering its graphics quality, the game remains the same. And that in this menu the number of fps that can be selected (30 or 60 fps) is shown so as not to limit a game to only 30 fps if a person feels more comfortable with 60, in addition to whether their device is capable of emulating the game at that amount of fps.

**Comment by unknownbrackets** [comment]
There's already frame skip, which is a frame limiter.

It might be that you're saying: skipping frames sometimes makes graphics bad, so instead there should be a proper frame limiter.  The problem is, PPSSPP is an emulator.  Its job is to take games, which have lots of complicated code and AI management and other things all tied together into their internal rendering logic, and run them on other devices.  It runs the same original PSP game code, just translated to work on your device.

There are patches and cheat codes on the forum where people have spent hours messing with some game to figure out how to modify its code to make it run at a lower (or usually higher) FPS.

-[Unknown]
