### ISSUE TITLE
Pilot Academy Sound Too Quiet

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp#13222]
Opening because @hrydgard asked me to do so in e-mail reply.
### What happens?
Sound is too quiet.All settings in emulator and game were at highest volume possible.I checked this on phone and PC.It is same.

### What *should* happen?
It should be at least bit louder.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
PPSSPP Gold 1.10.2
PC:
GPU:Intel (HD) Graphics
CPU:Intel Pentium N3520 (Quad Core)

Phone:Mi Redmi 6
GPU:PowerVR Rogue GE8320
CPU:Mediatek Helio P22

**Comment by Panderner** [comment]
@HiImBrala have you maximized the volume on device settings and game setting?

**Comment by HiImBrala** [comment]
Oh hi Panderner.Yeah i did,everything,and way too quiet,even quiter Surf's Up.

**Comment by HiImBrala** [comment]
@hrydgard 
Due to the many reasons,school,mental health etc.I decided it is best that i retire from PPSSPP at all,because i see that it is obvious that i failed what i came for;helping the community.This is my decision i think you would understand,*this is just character i don't want to play anymore*,and more i do,more my mental health suffers.I'm really sorry for everything i did bad here,regarding my dramas here just around something simple as game,knowing owning a big server won't help me in real life or *"fix"* my life issues like some miracle,which reminds me to do something.

@boy13epic,@MojoJojoDojo,i'm sorry for issues i caused,you have every right to call me a**hole,kid or whatever you want.I was unhappy and i took it out on you,because i was simply jealous that everyone could make something but me,and i lost.I wish both of you healthy life,as anyone deserves more than me at this point.

Thank you @EX-e-LD,for talking to me yesterday,you made me realize what i was doing wrong all this time,and you opened my eyes to something out of limits,something i had but forgot in search of my happiness here.

**I will assist with remaining issues until 15.8.2020,after that day i'm retiring,and i WON'T reply to issues,comments etc.I have school to attend,sort out my biggest curse (life),and enjoy every moment.Thank you everyone who helped me,i appreciate it a lot.**

**Comment by EX-e-LD** [comment]
@HiImBrala 
Hi,me again.I can't say anything more than,that you're right.Everyone has need to correct their lives at some point,you can't live forever of playing PPSSPP,it isn't possible.After all,this is just a emulator for games,just games,not your life.I hope you'll be successful in whatever you plan to do,talking to you yesterday was really a weird,but such good experience,hearing from someone who is considered PRO of the PPSSPP community,hearing your opinion,your view of the community as it is.Stay safe,do what you need to do,sort out your life and be happy,and thank you on great experience yesterday.

**Comment by hrydgard** [comment]
Noted, but please leave this type of discussion and announcements on Discord - here on Github we should discuss the actual issues only.

**Comment by benderscruffy** [comment]
this is not a bug
just tested it on my psp
it is quiet to start with but when you turn up the music and voices and sound fx then save it everything is good
can be closed

**Comment by hrydgard** [comment]
Oh, thanks for testing.
