### ISSUE TITLE
[Libretro/Windows 10 x64]OpenGL doesn't work

### ISSUE THREAD

**Issue by Immersion95** [hrydgard/ppsspp#13228]
The core is built with the latest commits but :

The core still fallbacks to GLcore when anything else is selected, I have to force it by disabling "Allow cores to switch the video driver". 

GL still doesn't work then and it is needed to make "Darkstalkers Chronicle" work. **----->Wrong but GL still doesn't work**

**Comment by i30817** [comment]
You should give some context of your host operating system.

In my case, the core doesn't work on retroarch compiled without x11 support and opengl driver (because i wanted to test retroarch without using xwayland).

It works if instead i build both the core and RA to support opengles but then other cores don't work, so that's a bummer.

**Comment by Immersion95** [comment]
Sorry for the lack of information.

I edited the title, it's on Windows.

I'm trying to make Darkstalkers work on RA but to no avail.

**Comment by LunaMoo** [comment]
Darkstalkers require software rendering not openGL, it's enforced via compat.ini, but third party frontends might not use it. Still you can manually enable software rendering for it unless it doesn't have software renderer either:0.

**Comment by bslenul** [comment]
I played a couple fights on Darkstalkers, worked fine for me. I have D3D11 selected as video driver for PPSSPP, not sure if it falls back to software or not (no notification or anything) but since it's apparently required for that game I guess it does :p 

![image](https://user-images.githubusercontent.com/33353403/89112387-3b993000-d462-11ea-86d3-39e2e94c5595.png)

GL gives me a black screen (with sounds) on that game, but works fine with others (tested with GoW games and Castlevania).

**Comment by Immersion95** [comment]
I'm closing this issue as glcore does work even if it's really behind dx11, few things to note : 

- Unfortunately we still need to disable "Allow Cores to Switch the Video Driver" to use dx11
- There are 3 frames of input lag added to gl compared to dx11

Also regarding Darkstalkers, how can I chose Nearest Neighbor instead of Bilinear in Retroarch ? I can do it in standalone though.
