### ISSUE TITLE
[macOS] Latest PPSSPP drops frames and stutters

### ISSUE THREAD

**Issue by ExperiBass** [hrydgard/ppsspp#13285]
### What happens?
PPSSPP will stutter once every 2 seconds but will still accept input, causing me to oversteer on WipEout Pure.

### What *should* happen?

PPSSPP doesnt stutter and plays like it would on a normal PSP.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

macOS version:

![Screen Shot 2020-08-14 at 12 52 07 PM](https://user-images.githubusercontent.com/33764485/90273435-f810cf80-de2c-11ea-9bb3-56acc2554c21.png)

PPSSPP version:

![Screen Shot 2020-08-14 at 12 52 24 PM](https://user-images.githubusercontent.com/33764485/90273464-019a3780-de2d-11ea-8251-94b891fa2660.png)

**Comment by hrydgard** [comment]
Any idea around which build this started happening in? Also, that's not that new, if you can try a fresh build.

**Comment by GingkathFox** [comment]
really? git lied to me, i updated my clone and then rebuilt it

and i would assume around this build, last build had no issues and that was maybe in january when i built it

**Comment by unknownbrackets** [comment]
1d783dde0 is 3 months old, older than the latest stable release, and behind latest git by 808 commits.  Pretty stale.

If you're compiling, git can help you narrow it down.  See here:
https://github.com/hrydgard/ppsspp/wiki/How-to-bisect-to-find-what-broke-a-game

You may want to try resetting to default settings (maybe backup ppsspp.ini first.)  Some settings that can cause stutter (this would be true in old and new versions):
 * Texture scaling
 * Rewind (even if not rewinding)
 * CPU clock changes
 * Cheats, such as 60 FPS cheats

Also, it's worth noting that other updates on your device - such as driver updates - can of course impact things.  That's another reason it's good to go back and narrow down what commit changed the performance you are getting.  We could collectively spend months searching through the 1300+ commits in the last 8 months to find the commit that did it, just to find - oops - it was actually Apple making some change and nothing in those commits at all.

But even if it's in the 500 commits between January and April, that's still quite a haystack to find a needle.  You could compile and test just thrice, and cut that down to ~120 commits.  Another three swings of your mighty sword, and it'd be down to ~16.

Since I'm not getting any stutter, I can brandish my staff all I want, but it'll cause almost almost no damage to this bug.  Can you cut it down to size for us?

-[Unknown]

**Comment by GingkathFox** [comment]
ill try re-cloning, it seems like git isnt giving me the latest master. If it still occurs ill start working out which commit broke it.

**Comment by unknownbrackets** [comment]
Is this any different on the latest git builds?

I'm not sure why FFmpeg would not be found.  Make sure if you're using a fresh clone that you've pulled submodules.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
