### ISSUE TITLE
Gamepad affects the emulation speed

### ISSUE THREAD

**Issue by greedy12** [hrydgard/ppsspp#13311]
My external controller slows down the emulation speed of all my games

What should happen?

maybe I'll just wait until devs fix the issue  and play without external controller

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Android 9
Hardware:mt6765 mediatek helio p35
Gpu:powervr ge8320
Gamepad:Mocute 050

**Comment by Gamemulatorer** [comment]
What kind of controller wired or wireless?

**Comment by Gamemulatorer** [comment]
Read more info here https://github.com/hrydgard/ppsspp/issues/10452#issuecomment-366480242

**Comment by Panderner** [comment]
> Read more info here [#10452 (comment)](https://github.com/hrydgard/ppsspp/issues/10452#issuecomment-366480242)

is this input lag on something @greedy12?

**Comment by LunaMoo** [comment]
Can't find the issue about it, so maybe it was a forum discussion, but this is not related to PPSSPP, your device simply clocks down when you use your gamepad(or probably more accurate it clocks up when using touchscreen), don't remember how affected users solved it if they even could, maybe creating some gaming/performance profile via smartphone specific setting or app, but nothing can be done about it on the PPSSPP side.

**Comment by unknownbrackets** [comment]
Given the above, I'm going to close this.  You may get better, or at least more consistent, performance by using "sustained performance mode".

Because many smartphone users care about battery life, manufacturers are incentivized to try to reduce power consumption using heuristics like this.  Android doesn't give PPSSPP any way to override this - and it's not just touch screen that can impact it.

-[Unknown]
