### ISSUE TITLE
[Switch] Freeze/Crash on loading Final Fantasy Tactics: WOTL Save States

### ISSUE THREAD

**Issue by LusciousPear** [hrydgard/ppsspp#13334]
### What happens?

I am able to play Final Fantasy Tactics: War of the Lions fine. However, when I load any save state, both PPSSPP and RetroArch both freeze. I am running with the Valeria 2.2 patch, but I don't think that would impact anything. 
https://ffhacktics.com/smf/index.php?topic=11872.0

Loading save states on SNES games is fine so I think the problem is PPSSPP.

I have attached a log. I can also send the savestate to someone. 

[01598241574_010055d009f78000.log](https://github.com/hrydgard/ppsspp/files/5124676/01598241574_010055d009f78000.log)

I have disabled fast memory, locked CPU, networking, and never used cheats.

### What *should* happen?

A savestate should be loaded. 

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Switch HAC-001, Hekate/Atmosphere 5.00, PPSSPP 1.9.0 244a601

**Comment by unknownbrackets** [comment]
Libretro has long standing save state problems with PPSSPP, because it is internally designed for NES/smaller emulators.  PPSSPP is multithreaded, and libretro doesn't really support that.

Is there a log for standalone crashing?  Does the same save state crash if you load it on PC?  Save states are portable across platforms (no idea if this is true of libretro, since it overrides our standard save state handling, which is where it handles threading incorrectly and causes crashes.)

-[Unknown]

**Comment by LusciousPear** [comment]
Thanks -- it works fine on standalone switch PPSSPP so I'll stick with that :)
