### ISSUE TITLE
Game crashes (ios14)

### ISSUE THREAD

**Issue by wsjyhaozi** [hrydgard/ppsspp#13349]
### What happens?
I can normally run PPSSP (installed by Altstore). Everything seems well in the main page, but when I try to start a game it crashes. So far all the games I tried have crashed. I also tried all the methods mentioned in your link. 

### What *should* happen?
Games should run properly.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
IOS14 beta6
PPSSPP 1.10.3
In fact since I installed ios14(beta3) it keeps crashing...

**Comment by Panderner** [comment]
Have you changed the CPU core to IR Interpreter?

**Comment by Gamemulatorer** [comment]
duplicate #13255 can't also be fixed 🙁

**Comment by unknownbrackets** [comment]
I'm going to close this based on iOS 14 and the above.  Feel free to still comment if you're using IR Interpreter and we'll reopen.

In the past, I've warned the community that Apple might, in fact, be working exactly to prevent what has allowed PPSSPP's jit from working on Apple devices.  Turns out they were, and completed this work in iOS 14.

Just to repeat myself from another issue:

> Just so people don't spam me personally: I don't have an iOS device, and fighting Apple doesn't sound as interesting as making PPSSPP run better on platforms where it's welcome (every other platform.)  If Apple wants to sell me a device, they should change their policies on what apps are allowed.

-[Unknown]
