### ISSUE TITLE
[Adhoc] Gran Turismo is stuck at "waiting for other players" after race start

### ISSUE THREAD

**Issue by MojoJojoDojo** [hrydgard/ppsspp#13366]
### What happens?
The game is stuck at "waiting for other players" even though all players are ready.

### What *should* happen?
The race should start normally.

Note: tried over multiple instances and not over the internet.

Pictures of the game and logs:

![image](https://user-images.githubusercontent.com/33392696/91734331-7ef6d380-ebb3-11ea-9bc9-603a2043c466.png)

**Comment by ANR2ME** [comment]
Looks like the target peer member is no longer in the member list, i'll check that out.

**Comment by ANR2ME** [comment]
Hmm.. this is a strange bug indeed.
Based on this logs:
![image](https://user-images.githubusercontent.com/7974720/91865831-fe5fd200-ec9b-11ea-8f1b-62dcaf4f4766.png)
The correct MAC address is `93:3a:0f:23:61:a2` but the one passed as argument is `92:3a:0f:23:61:a2` not sure how the first byte got corrupted like this, this never happened on other games

**Comment by ANR2ME** [comment]
Hmm.. it's also possible that the API is only checking for the last 4 bytes (for optimization reason) instead of the full 6 bytes of MAC address, since the 1st 3 bytes of MAC address is to identifies the manufacturer, they're most-likely the same on each PSP (assuming Sony is using the same manufacturer for their wireless adapter)
https://www.geeksforgeeks.org/introduction-of-mac-address-in-computer-network/

**Comment by MojoJojoDojo** [comment]
Ah well when i use multiple instances I dont care about the MAC address part so it stays the same on both instances.
I need to check if it works on JPCSP as more games work there over adhoc.

**Comment by ANR2ME** [comment]
> 
> 
> Ah well when i use multiple instances I dont care about the MAC address part so it stays the same on both instances.
> I need to check if it works on JPCSP as more games work there over adhoc.

it should probably works if you use prx files, since it's an official module

**Comment by Pik-a-boo** [comment]
Also it's only an emulator issue it wont work if you try to play it over Xlink Kai and real PSPs.
Strange thing.

**Comment by ANR2ME** [comment]
> 
> 
> Also it's only an emulator issue it wont work if you try to play it over Xlink Kai and real PSPs.
> Strange thing.
> (Its Mojo i have another acc lol)

Well it's probably some kind of protection if the game is tampering with it.
The only solution i can think of to fix this is by ignoring the 1st byte.

**Comment by ANR2ME** [comment]
Hmm.. looks like the bug isn't as simple as ignoring the 1st byte :( i did managed tp progress from that stage, but when i try again, i'm getting this kind of logs O.o it replaces all the bytes to `00`
![image](https://user-images.githubusercontent.com/7974720/91888223-22301180-ecb6-11ea-8960-88e35c2457a2.png)
It should be 02:02:02:02:02:02 but the game is using 00:00:00:00:00:00 instead :(

**Comment by ANR2ME** [comment]
Okay i findout why the 1st byte was always 1 number below the original 1, it was because of the opcode at:
```
08B306DC  ins v0,zero,0x0,0x1
```
It's replacing the 1st bit with 0 not sure for what reason...
Now it makes me wondering whether the 2nd argument is actually a mac address or not...

**Comment by ANR2ME** [comment]
> 
> 
> Ah well when i use multiple instances I dont care about the MAC address part so it stays the same on both instances.
> I need to check if it works on JPCSP as more games work there over adhoc.

Btw did you managed to get it to works on JPCSP? i tried to use prx files but after both players ready and the race started, it stuck with the loading screen (the one with GT logo), since it took a long time without any progress i closed it down LOL may be because my laptop is too slow to run 2x JPCSP :( 

I also notice something different, with prx files the Host is always located on top of the list while with PPSSPP whenever a player joined the Host pushed to bottom LOL

well i've made some changes to sort the member list last month but stashed it since i wasn't able to confirm how the list supposed to look like back then.

**Comment by MojoJojoDojo** [comment]
Well I couldn't get it to work over JPCSP - The client cant see the host for some reason.
I tried with the latest JPCSP build so maybe I need another one ? Tried with an earlier build and I couldn't even start the game lol.

**Comment by ANR2ME** [comment]
I managed to get this game to work on PPSSPP
![image](https://user-images.githubusercontent.com/7974720/91967189-13d90880-ed3d-11ea-9d0d-b5a087d13b63.png)
But it's kinda hackish because of the modified MAC address, while it wasn't modified when using prx files.

**Comment by MojoJojoDojo** [comment]
Damn I will like to try it out and play it.
Well if does not break any game its not that bad right? so close lol.

**Comment by ANR2ME** [comment]
Hmm.. after reading some more of MAC format, the 1st bit of the 1st byte the game was changing, seems to be the unicast/multicast type, so i guess this fix is already correct by ignoring the 1st byte when comparing
![image](https://user-images.githubusercontent.com/7974720/91972716-47b82c00-ed45-11ea-82b1-f87c451f6898.png)

**Comment by ANR2ME** [comment]
Wow because of this game i find so many bugs, and some of them are general bug and not specific to this game.
Currently i'm still stuck trying to sort the member list to a satisfying order (all players to show the same order with the Host), but it's difficult to "predict" where to insert the local MAC among all the children, since the local MAC never get added to the peerlist :(

**Comment by hrydgard** [comment]
@ANR2ME  Does the order displayed even matter? Is the order always the same on all the devices on the real PSP?

**Comment by ANR2ME** [comment]
I've made the PR to fix this
