### ISSUE TITLE
Pro Yakyu Spirits 2010 (NPJH50234): character shadows are not cleared properly per frame

### ISSUE THREAD

**Issue by nassau-tk** [hrydgard/ppsspp#13391]
### What happens?
Strange characters shadow appear.
But, May be it won't getting the dump corectly I think.
(It isn't understood by my knowledge.)
So,Please see attached screenshot & dump.

### What *should* happen?
Graphic drawing corectly.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
PPSSPP Ver.：1.10.3-581
OS：Android 9.0
DeviceName：SONY SO-02K / Xperia XZ1 Compact（Japan）
CPU：Snapdragon835（Octa-core）
GPU：Adreno 540
Resolution：720×1280
RAM：4GB
ROM：32GB
ExternalStrage：microSDXC 512GB

PPSSPP Ver.：1.10.3-581
OS：Windows10（64-bit）Japanese
CPU：Ryzen7 3800X（8-core）
GPU：RADEON RADEON RX5700XT
Resolution：2560×1440
RAM：32GB

**[Before the issue happen.]**
![ProYakyuSpirits2010_000](https://user-images.githubusercontent.com/48179091/92323489-2e302080-f074-11ea-9d44-157f39a87e8f.png)

**[After the issue happen.]**
![ProYakyuSpirits2010_001](https://user-images.githubusercontent.com/48179091/92323517-72232580-f074-11ea-9b15-89b899f8ef2e.png)
**and**
![ProYakyuSpirits2010_002](https://user-images.githubusercontent.com/48179091/92323524-7a7b6080-f074-11ea-84ff-aa307e995847.png)

Dump files here.
[NPJH50234_ProYakyuSpirits2010_Dump.zip](https://github.com/hrydgard/ppsspp/files/5179608/NPJH50234_ProYakyuSpirits2010_Dump.zip)

**Comment by Panderner** [comment]
@nassau-tk how is this look for software renderer and real hardware?

**Comment by nassau-tk** [comment]
@Panderner 
Software rendering is not happen the strange shadow.

Is it meaning "Real Hardware" equal "Real PSP"?
If it's right.
Please,See below.**[Real PSP ScreenShot animationGIF]**
![ProYakyuSpirits2010_RealPSP](https://user-images.githubusercontent.com/48179091/92327097-39924480-f092-11ea-9f20-6a242769f91e.gif)

The dumpfiles isn't draw strange shadow isn't it?

**Comment by nassau-tk** [comment]
This strange shadow is  cleared when switch the window to back ground on Andrpid.
Cleared by switch to full screen on Windows(Not every time).
I can't get these strange shadow in GE Dump.
So,I attached MP4 file.
Please,See it.
[NPJH50234_2020-09-19_05-20-45.zip](https://github.com/hrydgard/ppsspp/files/5248003/NPJH50234_2020-09-19_05-20-45.zip)

**Comment by nassau-tk** [comment]
@hrydgard 

This game is not working on "D3D11" at v1.10.3-711.
But, Working from v1.10.3-712.

**v1.10.3-712-g7ed1ade56 | Henrik Rydgård | 2020-09-19 14:14:06
A couple of D3D11 fixes.**

Just Report!!

But,This issue is still happen.

**Comment by nassau-tk** [comment]
And,This Baseball game has more seriese.

Pro Yakyu Spirits 2011 (NPJH50336).
Pro Yakyu Spirits 2012 (NPJH50520).
Pro Yakyu Spirits 2013 (NPJH50730).
Pro Yakyu Spirits 2014 (NPJH50838).

These games happen the same issue.

**Comment by hrydgard** [comment]
Thanks for detailed reporting!

**Comment by nassau-tk** [comment]
The issue still happen v1.10.3-1375.

**Comment by nassau-tk** [comment]
Re-tested on v1.10.3-1552 (Windows10/64-bit)

I found a point.
If change to "Skip buffer effects(non-buffered, faster)" then shadow will draw correctly at [Vulkan/D3D9/D3D11].

[OpenGL] is still happen the issue on any settings.

**Comment by unknownbrackets** [comment]
I'd guess something (possibly a reinterpret or memory transfer) should be clearing the buffer used for shadows.

-[Unknown]

**Comment by nassau-tk** [comment]
I got a log.
There is a few red code when timinmg of start up .

https://gist.github.com/nassau-tk/45c8f1aa599e3c48dcf536acb2cf7668

**Comment by unknownbrackets** [comment]
The original dump should look like this:

![playback expected](https://user-images.githubusercontent.com/191233/105645828-0853be80-5e51-11eb-91a4-3cdc62be468e.png)

In playback, it does.  This seems to be an issue with clearing previous shadows.

The lower shadow is drawn at step 41/275 from 0x0418e000.  That buffer is rendered to at 67/275.  To draw, it:
* Clears 128x128x16-bit at 0x0418e000 to 0x00000000 using a 5551 clear (color/alpha/stencil, not depth.)
* The clear has the 0x7F bits of stencil masked, but it's 5551 anyway so that should change nothing.
* Renders to 0x0418e000 as 5551 using 5551, flat, lighting color, and weights.
* During that render, it uses and ALWAYS stencil test to increment stencil.
* The render has color masked off and stencil 0x7F masked, so it writes stencil only.
* Once done, it does a stencil != 0 test to blend using fog I think.  This causes the shadow.

When using that as a texture (back at 41), it sets it as a 5551 texture with blending based on src.a.

So that shadow (on the mound) should rely on simple stencil clearing.

The shadow for the pitcher is similar, but without a temporary (maybe because no mound deformation.)  It:
 * Draws shapes with everything but 0x80 masked off for stencil, but again it's 5551 so that just means write stencil.
 * At draw 66, it unmasks color and does a full screen draw with a stencil != 0 test.

Interestingly, we begin the frame with a color-only clear, 5551.  Then we do a alpha/stencil clear (separately...) with 0x7F masked for stencil.  Then we do ANOTHER clear, this time stencil + depth but with stencil masked.

We seem to be handling the masking during stencil clears on 5551 incorrectly.

-[Unknown]

**Comment by hrydgard** [comment]
Interesting! Do we manage to actually convert it to a real clear in DrawEngine or is it drawn as triangles?

Our state mapping for stencil is rather complex so would not surprise me if we had a bug in either place...

**Comment by unknownbrackets** [comment]
Not a real clear - primitives.  It looks like the stencil mask fails to take into account the framebuffer format.

-[Unknown]

**Comment by hrydgard** [comment]
This is probably working now - please test.

**Comment by nassau-tk** [comment]
@hrydgard 

OK! I tested it.
OpenGL with Buffered Rendering.
Vulkan with Buffered Rendering.
D3D9 with Buffered Rendering.
D3D11 with Buffered Rendering.

All backends solved the issue!

**Comment by nassau-tk** [comment]
Oops!!
Sorry!!

Windows10(64-bit) is no problem.
But, My Android Galaxy S20 is not appear the pitcher's shadow at Vulkan.

![Screenshot_20210125-215113_PPSSPP](https://user-images.githubusercontent.com/48179091/105709913-bcd90780-5f59-11eb-9ca7-8d2cec37dad6.jpg)

OpenGL is Good.
![Screenshot_20210125-220114_PPSSPP](https://user-images.githubusercontent.com/48179091/105709956-cbbfba00-5f59-11eb-8ea6-2318c8ab639e.jpg)

**Comment by Panderner** [comment]
@nassau-tk what chipset for your s20?

**Comment by nassau-tk** [comment]
PPSSPP Ver.：1.10.3-1636
OS：Android 11.0
DeviceName：Samusung Galaxy S20 / SC-51A
CPU：Snapdragon865（Octa-core）
GPU：Adreno 650
Resolution：3200 x 1440 (Max)
RAM：12GB
ROM：128GB
ExternalStrage：microSDXC 512GB


GEdump here.
[Uploading proyakyu2010.zip…]()
This dump was got from my phone.
But, If open on the Windows then it will appear correctly.

**Comment by hrydgard** [comment]
Weird! But that is not as distracting as the old problem, I'll look at this after 1.11.

**Comment by nassau-tk** [comment]
YEs! I think so too!

**Comment by unknownbrackets** [comment]
It might be related to dual source blending.

-[Unknown]

**Comment by Panderner** [comment]
> It might be related to dual source blending.
> 
> -[Unknown]

@nassau-tk have you tried direct3d 9?

**Comment by nassau-tk** [comment]
> > It might be related to dual source blending.
> > -[Unknown]
> 
> @nassau-tk have you tried direct3d 9?

@Panderner 

I did it on Windows.
It's no problem.

Android?
I have only OGL or Vulkan.

**Comment by hrydgard** [comment]
Okay, it's not dual src blending then (since d3d9 doesn't support it). thanks for testing though!

**Comment by unknownbrackets** [comment]
When playing back the latest frame dump on a PSP, there's actually no shadow:
![#13391_NPJH50234_pro_yakyu_shadow2](https://user-images.githubusercontent.com/191233/201498034-2b7f1032-aafd-452c-887d-528abcce3c72.png)

Maybe it's a bug in the frame dump handling, though.  Software rendering matches the PSP in any case.

The previous one does have one (as noted above):
![#13391_NPJH50234_pro_yakyu_shadow](https://user-images.githubusercontent.com/191233/201498045-98e17700-e223-4fb5-b568-2d661081e3c9.png)

Seems like Android Vulkan is not showing either shadow.  After digging a bit, it's caused by the workaround for #10421.  Not hard to fix.

-[Unknown]
