### ISSUE TITLE
[Feature request] Rewind feature.

### ISSUE THREAD

**Issue by InfamousKnight** [hrydgard/ppsspp#13412]
Plus an ability to rewind during a video dumping(if possible).

What i mean by that is when recording a video dump, rewind would also rewind the encode as well.

Recently I preferred using rewind over save states when making a tas.

**Comment by LunaMoo** [comment]
We already have a rewind feature.
 You can't really "rewind" video encoding through, i could at most do what savestates now do that is dump video/audio into new file using past save timestamp whenever you stop rewinding, you'd still have to combine them manually into one video.

**Comment by InfamousKnight** [comment]
Oh, I didn't know it already exists. I just couldn't find under any feature documentation anywhere(retroarch page also says rewind isn't supported).

It sounds kinda hard to do then.

So if I record from frame 0 to 20, rewind to frame 15, what would happen there?

And if like I kept recording after frame 15 up to frame 20 and then rewind to frame 13, yeah, this could be quite a mess.

**Comment by LunaMoo** [comment]
Retroarch is not PPSSPP and it's features or support for them are not part of this project.

 About PPSSPP rewind.
 PSP is not a "RETRO" console, it's modern enough for rewind to not be as seamless, it requires much more powerful hardware mostly due to it's memory size which is very hard to save / load within a frametime budget, it also requires a lot more memory to store all of those save points than just running a game.

 Your "record X frames, rewind Y frames back" is not realistic, you should rather think about rewind usage in PSP games in terms of "I messed up some action, reload an state from few seconds ago".
 Not sure, but I don't think recording interacts in any way with rewind currently, and that's the only reason to keep this open I guess.

 If done like savestates best we could do is probably dumping into new video/audio file every time rewind point is created and then remove ones with newer timestamps after rewind being used, you'd still have to combine all the tiny video/audio files with  video editing software.

**Comment by InfamousKnight** [comment]
Yeah, I don't really know. I'm not that bothered by manually merging everything though.

**Comment by unknownbrackets** [comment]
The rewind feature in PPSSPP essentially takes an internal save state every so often (configurable in settings), and you can press a button to cycle back through them.

Currently it does not reset/start a new video file.

-[Unknown]

**Comment by InfamousKnight** [comment]
I have an idea: have another video audio dumping method where it writes a png / wav file every frame, and when you rewind, it simply deletes those frames too.
