### ISSUE TITLE
Alternate speed not working correctly in latest android build

### ISSUE THREAD

**Issue by ferrazpedro** [hrydgard/ppsspp#13437]
### What happens?
When I select any percentage above 100%, the game keeps running at normal speed. When I select a lower percentage, or when I keep in unlimited it actually works.

### What *should* happen?
It should permit the user to control the speed the game runs

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
It's happening in a Xiaomi Mi A3, in Android 10. 
PPSSPP v1.10.3-686-g68735b4e5

**Comment by kintsugi** [comment]
Can confirm this bug on windows 10, the android version on a nintendo switch and samsung s6 tablet, and the nintendo switch version of ppsspp.

**Comment by unknownbrackets** [comment]
It's working fine for me, Android and Windows with default settings.  Does this still happen?

Things to note:
 * Alternate speed isn't a miracle.  If your device can't run at 200% speed, it won't.  Your device needs to be able to do twice as much to achieve 200%.
 * You can set two alternate speeds and toggle between them or separately activate them.  Maybe you've configured a different one than you're activating.
 * On some devices and backends/drivers, vsync may get in the way.  For best results, I recommend `UnthrottleMode = SKIP_FLIP` in ppsspp.ini (see #13865.)  `CONTINUOUS` is unlikely to work outside Windows.
 * If you're using libretro or something, there may be special problems there.

-[Unknown]

**Comment by unknownbrackets** [comment]
Is this still an issue?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
