### ISSUE TITLE
Phantasy Star Portable 2 crash on Adreno 3xx

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#13542]
Reported on Discord by gotem.

> gotem: hey there! I was trying to run Phantasy Star Portable 2 on PPSSPP (android build). I have apparently played this game earlier, like an year or two ago, and it was pretty much fine. Though right now it seems to be being problematic
> First of all there is no text in initial prompts, and it crashes when I click on New Game. For some reason, the way other applications reacted to crash make it seem like RAM usage was too high during the crash.
> I downloaded older version since I do remember it being completely fine
> PPSSPP 1.7.4 ran it completely fine. Though 1.8 seems to have exact same issue as 1.10+ versions
> My friend had same issue as mine , different device, different source of the game file
> OpenGL graphics. Her device has 3 Gigs RAM and Adreno 330, mine has 2 GB RAM and Adreno 308

**Comment by sum2012** [comment]
Maybe related to #13680

**Comment by unknownbrackets** [comment]
See #11732.  I think this problem is related to pixel depth rounding.

-[Unknown]

**Comment by Gamemulatorer** [comment]
This can be closed now?
see https://github.com/hrydgard/ppsspp/pull/16422#issuecomment-1326539473

**Comment by unknownbrackets** [comment]
Well, since none of the people experiencing this issue are participating in this issue itself, I think it's fair to close it since we made a change we do really expect to have fixed it.

If you're seeing this message and experiencing a crash in this game on a device with a Adreno 3xx GPU, please reply in a comment (or perhaps open a new issue, with as much detail as possible), and we'll reopen.

-[Unknown]
