### ISSUE TITLE
Socket support?

### ISSUE THREAD

**Issue by jmoseman01** [hrydgard/ppsspp#13557]
I'm trying to add socket support to your input mapper.  I got your source code to build, but I'm unsure where to start making a socket receiver for ppsspp.  The hope is to use the socket to take input data and move the character in the game.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
ppsspp - 1.10.3, windows 10

**Comment by unknownbrackets** [comment]
I assume this is related to #13558.

Currently, there's no API for this, but we could add one.  There's a websocket interface that functions as an API.  An example usage of that is here:
https://github.com/unknownbrackets/ppsspp-debugger

To sue the API, you'd start with something like this:

https://stackoverflow.com/a/58285551

But instead of `await client.Send("Echo");`, you'd sent an event encoded as JSON, like this:

```c#
await client.Send(@"{""event"":""game.status""}");
```

You would potentially need an onMessage or similar to get responses back.  See the JavaScript SDK for an example:
https://github.com/unknownbrackets/ppsspp-debugger/blob/master/src/sdk/ppsspp.js

If this seems like something you can use, I could fairly quickly add some APIs to allow sending button presses and analog events.

-[Unknown]

**Comment by jmoseman01** [comment]
I think ViGem is the way to go, not sure why it's not working with ppsspp though. - https://github.com/ViGEm
