### ISSUE TITLE
Planning to build for WebAssembly?

### ISSUE THREAD

**Issue by ogawa0071** [hrydgard/ppsspp#13567]
## What is WebAssembly (WASM)
WebAssembly (WASM) is a format in which native code such as C, C++ runs on a web browser.
Today it is included in the latest versions of all major browsers.

## Why we need

It would be great if PPSSPP works in a web browser, and can be used without the need for installation.

It's worth noting that WebAssembly is also available in iOS Safari.

Until now, PPSSPP has not become an iOS native app.
This is probably due to the restrictions of the App Store rules that emulators cannot be listed.

However, once PPSSPP can work with WebAssembly, PSP Emulator will work for the first time on iOS without the need for jailbreaking.

This is amazing.

## Similar WebAssembly project

WebAssembly implementations of emulators other than the PSP, such as Game Boy Advance or PlayStation 1, already exist.
https://github.com/torch2424/wasmboy
https://github.com/tjwei/pcsxjs

There are also WebAssembly implementations of existing complex and long programs written in C, C++ such as FFmpeg.
https://github.com/ffmpegwasm/ffmpeg.wasm

---

Please let me know if you are planning the WebAssembly version as a future plan.
If you have already decided not to plan the WebAssembly version, please tell us why.

**Comment by hrydgard** [comment]
It's not in the plans because it's would be a lot of work, none of it fun or useful for almost anyone.

Besides, how will you feed a web-based PPSSPP with ISO files on iOS?

**Comment by devinprater** [comment]
I mean, it may help with accessibility, and you can feed it a file from iOS' Files app by requesting a file, I think, or connect it to Dropbox or some such, but I don't think it could still use JIT, and PPSSPP works fine on iOS jailed, just use AltStore. Admittedly, AltStore takes a good 5 minutes to get all set up, whereas a web app would take less time and setup to get on one's phone screen and such. Either way, if one wants PPSSPP bad enough, one can get it on iOS. Even before AltStore, there was the signing services. Of course, those are *still* on like 1.6.2 or so, LOL.

My point is, a web app would be cool, but there are other ways to get it on all devices.

**Comment by ogawa0071** [comment]
@hrydgard 
Thank you for your reply.
I understand that there is no plan. We expect to be planned!

I think BrowserFS can be used to mount ISO in the web browser.
https://github.com/jvilk/BrowserFS

BrowserFS is also used in Boxedwine, which is a WebAssembly implementation of Wine.
https://sourceforge.net/p/boxedwine/source/ci/master/tree/

**Comment by adenovan** [comment]
how wasm emulator performance compared to native one ? 

wasm introduce another layer which is browser thats make it far away into machine language again , i never got a predictable code on javascript behavior so microsoft write typescript to make it more compiler and transpiler hell and what is the benefit of wasm if asm is faster ?

Another layer of tls security ? most low level network protocol layer there is avoiding it as https is another gigantic bloat also , websocket compared to raw socket is another performance degradation also , security degrade performance no need for benchmark.

So why should port it into wasm ? for google chrome os ?

**Comment by ogawa0071** [comment]
@adenovan 
Hi!

In my opinion, the advantage of WebAssembly (or asm.js) is that it may be possible to port some of the existing PPSSPP code code written in C++ and C.

TypeScript is a great language, but it's not practical to rewrite everything.

The reason I think PPSSPP should work in a web browser is because the browsers are a common application execution environment.
Even if it doesn't support many devices one by one (including iOS, Chrome OS, PS4, PS5), it will work with a browser.

In addition, if it works in a browser, it does not require installation, so even users who are not familiar with computers can use it easily and with peace of mind.

**Comment by adenovan** [comment]
bad environment bad emulation its happen everywhere  , https://github.com/jspspemu/jspspemu 4 years ago already saw an implementatoon on the environment its pretty agile but its pretty fragile too. 

Most of high performance code optimize the machine language down into the bare metal , from my pespective its faster and more usefull to switch the environment rather than pushing an environment to its limit when its just a bad choice from design perspective on very beginning.

ppsspp + clang + vulkan already on the right direction and many of old port and machine support already dropped also , not sure if someone really has time to push their limit into this feature. 

Its better to make remote play feature than this one like playstation do it with their new console.

**Comment by unknownbrackets** [comment]
When thinking about storing ISOs remotely like on Dropbox, there are many concerns: latency (your internet connection likely has worse latency than the PSP's UMD drive, even if it has greater speeds), API limitations (some APIs won't allow dynamic seeking or will rate limit seeking in a way that would ruin the experience), and data charges (for network connections paid by usage.)  In some ways, this has the same problems as #11997.

There's already jspspemu indeed for a PSP emulator written in JavaScript.  WASM would more likely be implemented using something like emscripten, meaning it would stay - largely - in C++.  So if you're thinking there's some pros or cons from rewriting PPSSPP in JavaScript from scratch, that's an very unlikely direction.  If someone did do it, it'd just be another emulator - like jspspemu is.  I know this was said above, but I wanted to say it more clearly.

Anyway, people often propose that Java is a common environment that will run anywhere, showing that it'd be much better to write things in it with little loss in performance.  It's probably notable in that case to compare PPSSPP's speed and portability with JPCSP, to evaluate that argument because it's a similar situation to WASM.  Java is, if anything, a much smaller departure from C++ than WASM is.

Anyway, if you expect to be planned there's a very simple solution: start planning and give it a shot.  PPSSPP is open source, and all the ports except Windows and Android have been contributed by someone new interested in porting to that platform.

-[Unknown]

**Comment by 44670** [comment]
File input is now supported by iOS Safari, after user selects the local file, js code can perform random access on that blob without having to read all the data into the memory. 

By using a worker, you can even have a synchronized file access API.

Since WebGL2 is supported by latest iOS, I guess the GLES backend can be reused for a porting to browsers.

The most difficult problem is the CPU simulation.
