### ISSUE TITLE
PPSSPP screen glitched after go to home screen when multitasking

### ISSUE THREAD

**Issue by PhilipPurwoko** [hrydgard/ppsspp#13730]
### What happens?
The PPSSPP screen has glitched after entering the home screen while multitasking on battery saver mode, even though it can still function normally.

### What *should* happen?
The screen should still normal after switching windows on multitasking

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
I use PPSSPP on android 7.1.2 Nougat, Redmi 5A, 3GB RAM, ARM Corted-A53 1.40 GHz,

**Comment by Panderner** [comment]
@PhilipPurwoko screenshot?

**Comment by PhilipPurwoko** [comment]
Here's the screenshot
![Screenshot_20201201-120337.png](https://user-images.githubusercontent.com/53051809/100699428-835aa480-33cd-11eb-984e-0ab8827fee8f.png)

**Comment by Panderner** [comment]
have you reset the on-screen controls?

**Comment by PhilipPurwoko** [comment]
I didn't change any settings yet after the screen glitched

**Comment by Panderner** [comment]
so what's the overlay is glitched?

**Comment by PhilipPurwoko** [comment]
😫  I don't really know how PPSSPP on android is working. Sometimes the button glitched too. The button's textures is destroyed altough it can still function normally.

**Comment by unknownbrackets** [comment]
Does this only happen with certain settings?  If you make sure buffered rendering is on and frameskip, does it still happen?  If no, which setting makes it happen?  If yes, does it happen with all default settings?

-[Unknown]

**Comment by Gamemulatorer** [comment]
I can't reproduce this switching apps from ppsspp to another apps both OGL & VK.
![Screenshot_2021-08-10-11-01-30-619_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/128801925-b115e620-8089-4a4b-895d-0f56bd6f2c3d.jpg)

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

We've made changes to try to make sure the right texture is always used in drawing, which this issue appears related to.  It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
