### ISSUE TITLE
[libretro] Image goes black ONLY after gameplay starts

### ISSUE THREAD

**Issue by ner00** [hrydgard/ppsspp#13737]
### What happens?
Quite a few games are unplayable but used to work, the screen goes black moments after the player can move the character, the game keeps running, you can move the character and hear the sounds but in some games it's either pitch black (Castlevania - The Dracula X Chronicles). In others only a few thing remain visible like a few light effects, explosions and the HUD (Ultimate Ghosts 'n Goblins), then others seem completely fine (Dragon's Lair). 

Unfortunately I don't have a backup to roll back and see what might have broken it. I've tried virtually every video driver, including the one that works perfectly by default in the desktop version (d3d11), but didn't help, I reiterate that standalone PPSSPP works fine, and even RetroArch core only goes black a few seconds after the player gaining control of the game.

### What *should* happen?
Should not lose image and go pitch black after staring to play.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Intel i5 4590T, 16GB RAM, Intel HD Graphics 4600 GPU, Windows 10 Pro (20H2)

Not sure what else I could add of value, RetroArch is latest, PPSSPP core and assets too... so yeah, it's not working on my hardware any longer.

**Comment by hrydgard** [comment]
Is your retroarch configured to use OpenGL or Vulkan?

**Comment by ner00** [comment]
It was by default using glcore, yes, but since then I downloaded the latest zip from RetroArch with all the defaults and tried every core (restarting RA in between changes) and even with d3d11 I get the same result. So, at this moment I'm testing with a completely untouched RA, with not special settings at all, only changing the core as a test.

Result is always the same, game handles just fine until the gameplay starts, here's a few screenshots below (notice that player character's proportions are very weird, don't think it's the case in Castlevania though).

**RetroArch, all defaults with d3d11 (or any other core), 1sec. after gameplay starts**
![Graphics ok but weird proportion on player char](https://i.imgur.com/aOXRbvl.png)

**RetroArch, all defaults with d3d11 (or any other core), 3sec. after gameplay starts**
![Graphics go almost entirely pitch black, some exceptions](https://i.imgur.com/HjB9pF2.png)

**RetroArch, all defaults with d3d11 (or any other core), 3sec. after gameplay starts**
![Running like a champ](https://i.imgur.com/t0fbWlV.png)

**Comment by ner00** [comment]
I found a compiled version of libretro_ppsspp (d6399b6) which works fine for me, not sure if that's of any help because I don't know exactly after which update did it break for me (hardware combo).

**Comment by Tasosgemah** [comment]
Yeah, black screen in Ghosts n Goblins is still an issue with the latest core (1.11)

Can someone share an unbroken compiled core?

**Comment by ner00** [comment]
> Can someone share an unbroken compiled core?

If Windows, try this one which I mentioned above and am still using currently: https://mega.nz/file/W9x20aoK#cdKCiptYQvoaVD85waq6awcbgvX9OyYOWAgcPW6xMeQ

**Comment by Tasosgemah** [comment]
> 
> 
> > Can someone share an unbroken compiled core?
> 
> If Windows, try this one which I mentioned above and am still using currently: https://mega.nz/file/W9x20aoK#cdKCiptYQvoaVD85waq6awcbgvX9OyYOWAgcPW6xMeQ

Thanks. But it's still broken for me. I'm still getting the black screen effect and on top of that, a huge main character model.

**Comment by ner00** [comment]
I'll try testing later today to see if they occurs with me,.and report back

**Comment by ner00** [comment]
> Thanks. But it's still broken for me. I'm still getting the black screen effect and on top of that, a huge main character model.

Don't know then. I had trouble with recent builds, but the one I shared solved it for me.
Using glcore video driver, iGPU Intel HD Graphics 4600.
Not sure if the assets could contribute to this issue, I would assume not.

**Comment by Tasosgemah** [comment]
> **EDIT:** Tried the latest core build with latest assets from master branch and it's working fine for me now, no longer having the initial issue and it seems to be working fine, at least with the games I mentioned.

-Updated assets
-Updated RetroArch itself
-Downloaded latest core
-Used fresh/default settings

Still getting a black screen when the first enemies appear.

Though i have a Nvidia 1060 card.

**Comment by Tasosgemah** [comment]
Just wanted to say, i updated the PPSSPP system folder with the files from the latest standalone and the issue is fixed.

I was updating the wrong "assets" before because i i'm stupid.

**Comment by unknownbrackets** [comment]
So this is just a way with how assets are managed in libretro - it's fine as long as they're present?

-[Unknown]

**Comment by msheehan79** [comment]
I can confirm @Tasosgemah's report that updating the assets does fix the issue. I had initially set up the PPSSPP core around a year ago and played Ultimate G'n'G without any issues at the time. I have since kept the core relatively current, so after seeing this report recently I tried the game again and had the same black screen issue with the latest PPSSPP core.

Based on the reported solution, I updated the assets in the Retroarch system folder as suggested and this does indeed solve the issue. I guess the biggest takeaway from this is that when updating the core itself I need to remember to also update the assets separately.

**Comment by ner00** [comment]
> I guess the biggest takeaway from this is that when updating the core itself I need to remember to also update the assets separately.

That's a good rule of thumb, but not strictly necessary. I opened this issue because, at the time, the latest core build wasn't rendering properly for me, even after updating the assets. The only solution was downgrading the core. In practice you should just resort to update the assets if you know that it is absolutely needed or if something breaks. 

Now I have a  different approach to RetroArch and **any** of its cores, which is to have multiple backups. Because I don't play all the games or all platforms every other time they are updated, and in that way I can remediate things if an updated core breaks compatibility.

**Comment by unknownbrackets** [comment]
You're always supposed to use the latest assets, although recent versions allow using old assets with newer PPSSPP versions.  It used to crash, and the change was mainly made because retroarch made it so complex for people to have proper assets.

Really, the assets are part of the program - just like assets are part of Photoshop or anything else.  You never here about people saying they updated Photoshop.exe, but made sure to keep the other files the same.  It seems ridiculous for other programs.  Of course there would be bugs.

For example, some games were fixed recently by using fonts with better metrics.  If you use old assets, those games are not actually fixed and will still crash.  Yes, it's data, but it's part of the release.  That's how all software actually works.  If you played some beta version of a game but replaced its executable with the newer version, it'd still have bugs and unfinished areas too.

Seems like this isn't a bug really, to the extent that it's not a PPSSPP bug.

-[Unknown]

**Comment by hrydgard** [comment]
Sometimes I miss Rust's `include_bytes!( filename )` macro, some of the assets would really be better off embedded in the binary heh. No convenient-enough way to do it in C++ though.

**Comment by jserodio** [comment]
I'm also getting a blackscreen after Konami splash in Castlevania Dracula X.
I'm using v1.11.2 PPSSPP standalone on the RG351M console
I can confirm it used to work in previous PPSSPP versions, not sure what has been changed.

**Comment by ner00** [comment]
This issue is exclusively about libretro core of PPSSPP and not standalone. Coincidentally I updated to RetroArch to v1.9.1 and latest PPSSPP core and assets. Castlevania X and Ghosts 'n Goblins were two of the game I tested and worked fine.
