### ISSUE TITLE
Yarudora Portable: Double Cast

### ISSUE THREAD

**Issue by zander1995** [hrydgard/ppsspp#13759]
What happens:
The game is primarily made of FMVs, and during play on PPSSPP (both PC and Android), the FMVs have extreme artifacting and corruption issues.

What *should* happen:
The FMVs should play normally. The visual issues are exclusive to PPSSPP and branches of it. The visual glitches are not present in JPCSP or on real hardware.

What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Hardware: Asus TUF Gaming laptop | Samsung Galaxy Tab S6
OS: Windows 10 Home v20H2 | Android 10
PPSSPP versions: Latest, and 0.9.9.1, x64 | Latest APK from PPSSPP site

Other specs: 
Processor: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx 2.10 GHz
Ram: 8.00 GB

**Comment by Panderner** [comment]
does it happens in all backends?

**Comment by zander1995** [comment]
Yes it does. I’ve tried basically every setting combination with every backend I can think of and nothing seems to change with it.

**Comment by sum2012** [comment]
Do you mean the FMVs artifacting of this ?
![2](https://user-images.githubusercontent.com/2177532/102008377-dab42980-3d6a-11eb-8c44-bb966ca91ea2.jpg)

**Comment by zander1995** [comment]
Yes, that is what happens. It doesn’t look like that on other emulators or real hardware.

**Comment by sum2012** [comment]
v1.10.3-1319-gc546c6032-windows-amd64 log:
 https://gist.github.com/sum2012/9ab51781a2b5444eb78042dcfcde5b39

**Comment by sum2012** [comment]
The worse case is that we need imp sceVideocodec

**Comment by shenweip** [comment]
`10:36:987 wlibMpeg     I[ME]: hw\mediaengine.cpp:87 FF: non-existing PPS 0 referenced`
`10:36:962 wlibMpeg     I[ME]: hw\mediaengine.cpp:87 FF: error while decoding MB 8 4, bytestream -4`
Actually, I have noticed similar log info many times in different games.

Thinking about this problem again, I think it's because ppsspp is using threads to decode videos now, which will increase decoding delay. Some games can't provide enough frames at one time, especially in the beginning, which will lead to blurring like this. Consider the possible impact on performance, a possible solution is to reduce decoding delay by reducing number of threads instead of disabling using threads.

I have fixed some similar issues in other games based on this idea, I think would help this game too.

**Comment by unknownbrackets** [comment]
Basically, I assume this is similar to the Valkyrie Profile issue.  We let ffmpeg start processing a block before it's complete, and ffmpeg gets confused and uses it's error correction (used when a network stream has errors) to attempt correction.  Implementing sceVideocodec won't help that.

-[Unknown]

**Comment by sum2012** [comment]
Yeah,Real psp return ERROR_MPEG_NO_DATA on this game
JPCSPTrace full log:
https://gist.github.com/sum2012/4aab09db951696bf50c31e6e1cdfe412

**Comment by sum2012** [comment]
Fix by #14199 Closing
