### ISSUE TITLE
NASCAR 07 graphics glitch - car bodies missing after reload

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#13830]
Reported by SpeedRC on Discord.

![image](https://user-images.githubusercontent.com/130929/103236769-04ae4400-4946-11eb-93b0-78736cf6a503.png)

> When i try to do the season mode with the custom car, it's work pretty well
> But...

![image](https://user-images.githubusercontent.com/130929/103236782-0f68d900-4946-11eb-9cc0-ead22ca7882d.png)

> But when i exit the game and try to get in again, it like this!! NO body of my Custom Dodge
> My graphic backend is OpenGL ES+

**Comment by unknownbrackets** [comment]
Could be this was fixed by some of the state fixes.  Hard to tell.  Would need a frame dump when it's happening to look into it more.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]

**Comment by EternalsDarkhole** [comment]
This issue should remove from future milestone.
