### ISSUE TITLE
Remote disc streaming doesn't seems to work anymore

### ISSUE THREAD

**Issue by ANR2ME** [hrydgard/ppsspp#13848]
### What happens?

I'm using my Android phone as hotspot (tethering) and i'm using PPSSPP on Win10 as Remote disc Server, but when i goes to Tools->Remote disc streaming->Browse games, all the icon boxes are just empty rectangle and PPSSPP on android will eventually frozen and crashed/forced close after awhile while waiting for the icons to appears (which never appeared)

![image](https://user-images.githubusercontent.com/7974720/103439619-055e1780-4c71-11eb-8c29-84a0f4bf9eaa.png)

Debug Logs on [IO]
![image](https://user-images.githubusercontent.com/7974720/103439621-0abb6200-4c71-11eb-9e6d-c4b1c096ec9d.png)

### What *should* happen?
Games icon should appears as usual and remote games can be played as usual.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Realme C12 - Android 10
Win10 v20H2 64bit
PPSSPP Android and Win64 v1.10.3-1438-g3c59e2351

**Comment by unknownbrackets** [comment]
Hm, requests are happening.  Can you run `adb logcat -s DEBUG PPSSPPNativeActivity PPSSPP NativeGLView NativeRenderer NativeSurfaceView PowerSaveModeReceiver InputDeviceState` with the Android device plugged in via USB while you do this?  Any log errors from it?

-[Unknown]

**Comment by ANR2ME** [comment]
I only saw this when PPSSPP got frozen and eventually crashed/forced close
![image](https://user-images.githubusercontent.com/7974720/103448276-dde76900-4cc9-11eb-8f2d-ae38fb89daf6.png)

**Comment by unknownbrackets** [comment]
On your Android device, what happens if you navigate to http://192.168.43.171:6500/?  This should show a text list of your ISOs, along with / and potentially /debugger.  If you paste one of those paths after the URL base URL, it should say "This server only supports range requests."

If those things don't happen, there may be a firewall problem in the way between the devices.  For example, if you have multiple wifi routers and they're connected to different ones.

That said, if it's worked before on the same network setup, both the above are unlikely... and Windows Firewall would be alerted if it was a problem...

It's weird that it force quit.  That really shouldn't happen...  Maybe try an unfiltered `adb logcat` (no parameters) after an `adb logcat -c` (clears the history) and see if the crash is logged in any way...

-[Unknown]

**Comment by ANR2ME** [comment]
using chrome:
![image](https://user-images.githubusercontent.com/7974720/103448592-48020d00-4cce-11eb-9931-7550611cc3c9.png)
And yes, when i added /Tekken%206.iso in the URL i'm getting "This server only supports range requests."

**Comment by unknownbrackets** [comment]
It's still working okay for me.  If you go back to an older version, like v1.10.3, does it work again?

You might also try disabling ipv6 in your Windows networking adapter settings.  Shouldn't be necessary, but from the above log it looks like ipv6 is not working correctly on your connection.

-[Unknown]

**Comment by ANR2ME** [comment]
Ah i think i found out the reason, it probably because i was running out of free space on my android.

After i cleared 300mb+ of free space remote disc seems to be working fine again, even when the display goes off it won't freeze/forced close anymore, probably the logcat got problem when in low space and causes freezes/forced close.

So i'll close this issue.

**Comment by ANR2ME** [comment]
Hmm.. looks like i have a different issue now.

When i lauched Valhalla Knights 2 (USA) for the first time through remote disc it worked fine, but after closing ppsspp and try again through recent games and also through remote disc, it's saying that the iso is corrupted.

I tried other games but didn't get this kind of issue...

Did the iso being cached? how do i reset the cache so it can redownload/restream it again?

**Comment by unknownbrackets** [comment]
You can long press on the PPSSPP app and go to clear cache.  This will clear the remote disc streaming cache.  Maybe it doesn't handle disk full well.

-[Unknown]
