### ISSUE TITLE
Problem detecting Opengl 

### ISSUE THREAD

**Issue by wellinton-capixaba** [hrydgard/ppsspp#13856]
Hello. I tried to compile the latest 1.10.3 version (and also one of the first, the 0.4 after the latest did not work) but faced a bunch of

Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY)
Call Stack (most recent call first):
  /home/leopoldo/Arquivos-de-Programas-Linux/cmake-3.19.2-Linux-x86_64/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  /home/leopoldo/Arquivos-de-Programas-Linux/cmake-3.19.2-Linux-x86_64/share/cmake-3.19/Modules/FindOpenGL.cmake:421 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:178 (find_package)

The point is that I do have many OpenGL libs and headers.

For instance LibGL.so.12 it is on /usr/lib/mesa. On /usr/local/include there is a GL folder with several header files. I never used Cmake before, so I don't know what its looking for when searching for OpenGL. If one could provide me with a full list of necessary headers and libs I would appreciate that, since I can search for the necessary package, build it and then create symbolic links to it.

**Comment by unknownbrackets** [comment]
What distro are you using?  Are you sure you have libraries for the same platform you're compiling for (i.e. x86_64)?

I'd recommend trying to install and make sure you have the "dev" packages (depending on distro):
https://stackoverflow.com/questions/31170869/cmake-could-not-find-opengl-in-ubuntu

-[Unknown]

**Comment by wellinton-capixaba** [comment]
Hello. I do not use dev packages anymore, I use what the system provides me by default and then use source packages as necessary. I need to know the exact files necessary to cmake's check of OpenGL, so that I can "point" to them somehow (with configure I use CPPFLAGS and LDFLAGS) or then create symbolic links to default system dirs, since I install everything in non default directories.

**Comment by unknownbrackets** [comment]
TBH, I'm not entirely sure what CMake looks for.  Ultimately, I imagine we need the so and include files, but I think CMake is using pkg-config or similar to look them up.  It might work to use `-DOPENGL_LIBRARIES=GL` on the cmake line, or otherwise you might have to edit CMakeLists.txt:
https://github.com/hrydgard/ppsspp/blob/57fda69e5064dae3cbccba211af0905f3cc1a753/CMakeLists.txt#L191

See also:
https://cmake.org/cmake/help/latest/module/FindOpenGL.html
https://github.com/Kitware/CMake/blob/3aca3f81449a282fc684999b2bcd6db4537c5661/Modules/FindOpenGL.cmake#L210

-[Unknown]

**Comment by orbea** [comment]
Probably missing headers and / or includes, what distro is this? Doesn't seem like a ppsspp issue.

**Comment by wellinton-capixaba** [comment]
Probably apparently solved using CMAKE_PREFIX_PATH to point to libGL that was on /usr/lib/mesa, outside default directory search list.
