### ISSUE TITLE
Crash: Mind over Mutant missing visible circle in digging

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13886]
When I digging a hole using spinning in Crash: Mind over Mutant the visible circle is missing for Vulkan but not OpenGL.

OpenGL: 
![Screenshot_2021-01-07-10-25-12-985_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/103843515-ee854e00-50d2-11eb-81b0-63a1f1dfdc79.jpg)

Vulkan: 
![Screenshot_2021-01-07-10-25-20-925_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/103843533-f6dd8900-50d2-11eb-89ff-0a60852cf30e.jpg)

GE dump: 
[ULUS10377_0001.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/5779166/ULUS10377_0001.ppdmp.zip)

**Comment by UbiSergei** [comment]
Somewhere In Main Windiw UI:


Pixel 127..

**Comment by Gamemulatorer** [comment]
PPSSSPP latest development build
Redmi Note 9 Vulkan
![Screenshot_2021-07-16-03-13-31-608_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/125844483-643ffa66-60f8-48b5-8280-0b5aad832956.jpg)

**Comment by Githubot1957** [comment]
@Panderner no feedback!?

**Comment by Panderner** [comment]
Still occur in latest build. I'm using POCO M3

**Comment by Gamemulatorer** [comment]
So this is adreno gpu vulkan issue only

**Comment by Panderner** [comment]
And yes it does not occur for my PC using Vulkan:
![Ppsspp Screenshot 2021 07 16 - 13 53 56 91](https://user-images.githubusercontent.com/37503397/125899013-5fa0bc79-c15a-4b52-9c3c-631dbb759b77.png)

**Comment by Panderner** [comment]
This must be Adreno GPU specific

**Comment by hrydgard** [comment]
Probably yet another minor stencil/blending bug in the driver, sigh. Not sure we can do much about it.

**Comment by unknownbrackets** [comment]
The circle is drawn at 35/100 (as 90 vertes for 30 TRIANGLES.)  It uses:
 * Depth test (ALWAYS)
 * Stencil test (ALWAYS REPLACE 4C)
 * Depth write disable
 * Depth clamp
 * No texture
 * RGB masked

In other words, it should directly write 4C to depth, and do nothing else.  After that it does smaller circles that are the same: stencil=99, then stencil=e5.

After that, it uses alphablending with dst.a vs 1.0 - dst.a to draw only in the masked areas with bevel.

The Adreno bug we knew about was not being able to discard stencil when there's no depth.  This bug seems different - it seems like alpha is failing to be written (maybe.)  I'm also able to reproduce this issue on a Google Pixel that has the previous bug patched.

-[Unknown]

**Comment by hrydgard** [comment]
s/directly write 4C to depth/directly write 4C to stencil

right?  (and yeah thus also to alpha, because of how we try to keep those in sync).

A lot of bugs in this area for sure...  Seems they get a little aggressive with their optimizer when they see ALWAYS ?

**Comment by unknownbrackets** [comment]
Oops, yes.  I agree.  Luckily, this is a fairly simple frame dump and a simple draw.

-[Unknown]

**Comment by unknownbrackets** [comment]
Just an update: this is also an issue on an Adreno 620 with the latest Android updates.

-[Unknown]

**Comment by unknownbrackets** [comment]
This was also coming from the #10421 workaround, and works with the changes in #16379 (at least the frame dump.)

-[Unknown]
