### ISSUE TITLE
Bad viewport in Hot Shot Tennis: Get A Grip

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#13921]
![image](https://user-images.githubusercontent.com/130929/104740864-bd4af480-5748-11eb-8949-a1c0f7352a09.png)

Happens since 1.10.3-328-g937042b3d ?

Reported by verymelon on Discord.

**Comment by hrydgard** [comment]
That change should have worked around it. 

There's still probably something wrong with the viewport math, postponing that.

**Comment by hrydgard** [comment]
For later investigation, repro instructions from VeryMelon:

* Get a completed game save from gamefaqs
* In "Story mode" choose Worldmap "World Television Studio" from first room (Entrance) walk into second room (Corridor) goto "Audition room" and talk with NPC Terio.

**Comment by ANR2ME** [comment]
I didn't get that popup but there is a lot of vulkan error message in the logs
![image](https://user-images.githubusercontent.com/7974720/104814720-139c5e00-5843-11eb-8946-ea67ad170c8b.png)

**Comment by ANR2ME** [comment]
I tried to run debug it from VS2019 and it hit a vulkan breakpoint when i talked to that NPC
![image](https://user-images.githubusercontent.com/7974720/104815093-1ef08900-5845-11eb-932c-041e89a4e44e.png)

![image](https://user-images.githubusercontent.com/7974720/104815078-fd8f9d00-5844-11eb-891a-2cc98c1933c9.png)

So i can't continue it to check the stack trace of the assertion popup when exiting ppsspp

**Comment by hrydgard** [comment]
Thanks, so Vulkan doesn't actually allow zero-pixel viewports... Not sure what exactly we should do in this case, maybe just discard draws...

**Comment by ANR2ME** [comment]
>
The application can specify a negative term for height, which has the effect of negating the y coordinate in clip space before performing the transform. When using a negative height, the application should also adjust the y value to point to the lower left corner of the viewport instead of the upper left corner. Using the negative height allows the application to avoid having to negate the y component of the Position output from the last vertex processing stage in shaders that also target other graphics APIs.

The width and height of the implementation-dependent maximum viewport dimensions must be greater than or equal to the width and height of the largest image which can be created and attached to a framebuffer.

The floating-point viewport bounds are represented with an implementation-dependent precision.

Valid Usage

    VUID-VkViewport-width-01770
    width must be greater than 0.0

    VUID-VkViewport-width-01771
    width must be less than or equal to VkPhysicalDeviceLimits::maxViewportDimensions[0]

    VUID-VkViewport-height-01773
    The absolute value of height must be less than or equal to VkPhysicalDeviceLimits::maxViewportDimensions[1]

>
https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#vertexpostproc-viewport

**Comment by unknownbrackets** [comment]
I wonder what a zero viewport on a PSP actually does.  If scale X and scale Y are zero, I guess it'd make all verts use the center coords (not necessarily not draw, but it'd just be a point I guess?), and it could do interesting things to depth.  But those are just guesses.

-[Unknown]

**Comment by ANR2ME** [comment]
I bumped on that subscript out of range issue on vulkan when closing down PPSSPP window while debugging Ratchet & Clank
![image](https://user-images.githubusercontent.com/7974720/104830677-7f1e1400-58b3-11eb-8172-b9729a272839.png)
Where `swapchainImageCount_` is larger than `swapchainImages_.size()` and used in for-loop.

**Comment by unknownbrackets** [comment]
The correct behavior seems to be not drawing anything when viewport width or height is 0, at least for triangles and sprites.  Didn't try points or lines.

So it seems like discarding draws is the right thing.

-[Unknown]

**Comment by UbiSergei** [comment]
Bug In A Sound Driver

Don't Divide By Zero, +1

**Comment by hrydgard** [comment]
I think for now I'm just gonna clamp to 1 pixel, then maybe do something better in the future. I think that's the least likely to break games...
