### ISSUE TITLE
Can't play over the internet with more then 2 devices on the same LAN on a public server

### ISSUE THREAD

**Issue by MojoJojoDojo** [hrydgard/ppsspp#13926]
I am not sure if this issue got posted before but basically if you use a public server like socom.cc etc you wont be able to play
online if you use more then 1 device on the same LAN/Network.
The only solution I know is to use a VPN instead but not a lot of people would like to do that.
If this got reported before close it.
Thanks.

**Comment by ANR2ME** [comment]
It's not possible for 2 players on the same network using the same internet connection to use public adhoc server, because all of their public IP will be the same, thus only one player will be allowed to use that IP.

It's Adhoc Server limitation to identify players by IP, and most public adhoc server server didn't change any of the logic from the old aemu project to improve it.

**Comment by MojoJojoDojo** [comment]
I mean it could be possible if someone modified the logic no?
I will keep this open for now because it might be able to be fixed in the future.

**Comment by ANR2ME** [comment]
Well you will need to contacts the owner of that public AdhocServer to add support for multiple players using the same public IP ;)

**Comment by MojoJojoDojo** [comment]
> It's not possible for 2 players on the same network using the same internet connection to use public adhoc server, because all of their public IP will be the same, thus only one player will be allowed to use that IP.
> 
> It's Adhoc Server limitation to identify players by IP, and most public adhoc server server didn't change any of the logic from the old aemu project to improve it.
> 
> Isn't the same thing happened when 2 players using the same internet connection to play adhoc multiplayer on real PSP (pro online) using the same public adhoc server?
> While XLink Kai might be an exception since it worked just like tunneling.

The issue is that the aemu/ProOnline implementation is ignoring the socket source port.
Unless that changed in the PPSSPP current source code I never looked at it..
Which is what could also cause the "incorrect port" issue but you didnt comment on it...
Anyway https://github.com/hrydgard/ppsspp/issues/7268 covers this issue so I gonna close it.

**Comment by ANR2ME** [comment]
Because "incorrect port" issue is not related to AdhocServer/aemu, since AdhocServer is using TCP (which is connection-oriented) so it doesn't need to care about source port, as long the TCP connection can be connected & established, unlike UDP (which is connection-less) where you don't know who sent the data without checking the source IP (& sometimes the port too)

AdhocServer is only used to create player list who plays the same game on the same group (based on their IP), and then provides this list to all players in that same group, after that players communicates directly with other players (P2P) without going through AdhocServer, AdhocServer will update this player list whenever someone is joining or leaving the group.

In order to support multiple device on the same public IP, this list need to contains player's Port Offset too (each player using the same IP need to use different Port Offset), so it doesn't need to make use the source port.
However, changing this list format will breaks compatibility with aemu/ProOnline project.

**Comment by MojoJojoDojo** [comment]
I just wondered if the aemu infrastructure is so outdated it might be the reason you get issues like that on games.
But you described it very well I will never doubt again.
