### ISSUE TITLE
AtlasTool: Failed to load font file

### ISSUE THREAD

**Issue by LunaMoo** [hrydgard/ppsspp#13949]
Tried to re-create atlas with some changes today on Win 10 x64 and the script didn't work at all so I tried on unmodified master and it also failed, so added $SHELL to buildatlas.sh just to stop it from closing the window and see what's happening and it fails at:

````
Failed to load font file assets/Roboto-Condensed.ttf
````

The font is there, I also tried to change it to full path also tried removing it altogether, which just makes it fail at next font. Not sure when it broke, but it was definitely working in the past.

The font seems to actually be detected on the start of the script before the message it says it fails, through not sure if it detects everything correctly as it only shows chinese and korean for some reason:

````
Font: UBUNTU24 (assets/Roboto-Condensed.ttf) in size 34. Locales: UWER
381 Chinese characters learned.
0 Korean characters learned.
44 Korean characters learned.
417 Korean characters learned.
locales fetched.
Font: UBUNTU24 (C:/Windows/Fonts/ARIALUNI.ttf) in size 30. Locales: UWEhkcRGHKVTe
381 Chinese characters learned.
0 Korean characters learned.
44 Korean characters learned.
417 Korean characters learned.
locales fetched.
````

Edit: A version from march of the 2020 generated proper zim and meta files just fine(althrough the incorrect info about locales fetched was exactly the same back then) so maybe it was bugged sometime when moving things to common.

**Comment by nassau-tk** [comment]
What is the reason Roboto-Condensed.ttf which exists on PPSSPP ?

I tried open the font fils.
It was including only 1045 characters.

![image](https://user-images.githubusercontent.com/48179091/105108964-ce0bb980-5afe-11eb-8546-29d3a2a0be3c.png)

**Comment by unknownbrackets** [comment]
This font is used as the first choice for font rendering in our UI (outside games) and also some of our UI (save dialogs.)  It's not used directly by games and unrelated to PGF.  If a character is not available in this font, then a system font should automatically be used instead.

Not all platforms use this file, though.  Specifically, iOS and Linux/macOS (except Qt) use the "atlas" which has a subset of font characters in it (including some from Arial/similar outside Roboto.)  If you see "chinese.txt" and similar in the root, these files contain the letters included in the atlas.  For other characters, `?` is displayed.

Also, Roboto-Condensed.ttf is "v1" of the [Roboto font](https://fonts.google.com/specimen/Roboto+Condensed).  Personally I prefer v1, but also it's a bit thinner and lets more text fit.  The biggest benefit is all platforms get a consistent UI with the same font, roughly (well, I think - at one point Qt was not using Roboto.)


I'm not sure about the atlastool issue, though.  It's been a very long time since I used it.  Should really get around to implementing a freetype TextDrawer I suppose...

-[Unknown]

**Comment by nassau-tk** [comment]
@unknownbrackets 

OK, I understood it!

**Comment by unknownbrackets** [comment]
> it only shows chinese and korean for some reason

So the problem is we can only have up to a 4096x4096 atlas, iirc, which means we cannot have every single Chinese character.  So it's reading from chinese.txt and korean.txt to determine which characters need to be included.  For others, such as Greek, I think it just includes every character.

-[Unknown]

**Comment by LunaMoo** [comment]
Checked the input for RasterizeFonts in
https://github.com/hrydgard/ppsspp/blame/master/ext/native/tools/atlastool.cpp#L945

and it->second ends up random buch of chars, different each time atlas tool is ran, no idea, but it feels wrong.
