### ISSUE TITLE
Program CRC32 crash

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#13964]
I don't know what is wrong.
Please help.Thanks
Change:
https://github.com/sum2012/ppsspp/commit/a36907e68761eed2fc3c5f63f8b3f16ea909fa15

Crash:
![1](https://user-images.githubusercontent.com/2177532/105620894-aab57700-5e3c-11eb-8771-43036777395e.png)
edit,upload wrong picture
![2](https://user-images.githubusercontent.com/2177532/105622381-2cf96780-5e4c-11eb-96d6-eedb6b86957f.png)

**Comment by ANR2ME** [comment]
if `Crc32Table` is an 8-byte array (0..255) you should use `& 0xFF` last, similar to the one above it (Crc16Table)

**Comment by unknownbrackets** [comment]
If you want a CRC32 of a disc, use (from Reporting.cpp):

```c++
		std::unique_ptr<FileLoader> fileLoader(ConstructFileLoader(gamePath_));
		std::unique_ptr<BlockDevice> blockDevice(constructBlockDevice(fileLoader.get()));

		uint32_t crc = 0;
		if (blockDevice) {
			crc = blockDevice->CalculateCRC();
		}
```

What your code is currently doing is:

1. Retrieve the filename (`gamePath_.c_str()`) into `chrs`, example: `"hello.cso"`.
2. Cast the filename to a sequence of bytes, example: `[ 'h', 'e', 'l', 'l', 'o', '.', 'c', 's', 'o', '\0' ]`.
3. Calculate a CRC32 of the size of the CSO file (let's say 500 MB) starting at the 'h' of the filename.  The filename (`uchrs`) is less than 1 KB so this crashes when it's trying to CRC the bytes after the filename.

Even if you were getting the content of the file in step 2 (which is what I assume you intended), this wouldn't work for PBP or CSO files.  It would incorrectly calculate the CRC32 of the compressed file, not of the contents.

We've already done this for reporting, that's why the `CalculateCRC()` method exists.  It will always CRC32 the internal contents of a compressed file.

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets Why this doesn't work ?
https://github.com/sum2012/ppsspp/commit/d56e6ff1d38d951bf7c09580613c861ce28e8afb

**Comment by unknownbrackets** [comment]
Ah, you're missing `UIScreen::update();` inside `GameScreen::update()`.

That said, this will hang when they click the CRC button.  To not hang, you'd do this:

```c++
UI::EventReturn GameScreen::OnDoCRC32(UI::EventParams &e) {
	CRC32string = "...";
	return UI::EVENT_DONE;
}

void GameScreen::update() {
	UIScreen::update();

	// Has the user requested a CRC32?
	if (CRC32string == "...") {
		// Wait until the CRC32 is ready.  It might take time on some devices.
		if (Reporting::HasCRC(gamePath_)) {
				uint32_t crcvalue = Reporting::RetrieveCRC(gamePath_);
				CRC32string = int2hexstr(crcvalue);
		}
	}
}
```

This will make it remain responsive.  It'll calculate the CRC32 on a separate thread, and only display it once it's ready.  Since `update()` gets called once per frame, we can check there to see if it's ready and convert to a string when it's done.  We can't do that in `OnDoCRC32()`, because that only gets called once right when they tap the button.

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets done https://github.com/sum2012/ppsspp/commit/e383a83057bdba21642ab30fea856a00e0534316

Can we also add crc32 calc in this screen ?
![1](https://user-images.githubusercontent.com/2177532/106142407-68799600-61ac-11eb-9f9f-a6050aea08b5.jpg)
