### ISSUE TITLE
Dissidia 012 Final Fantasy flickering animations with IR/Interpreter

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13990]
Battle in Dissidia 012 has flickering bugs when the CPU core set to IR Interpreter and Interpreter but not JIT

https://user-images.githubusercontent.com/37503397/106131328-82f84300-619d-11eb-8724-7f377057f03e.mp4

https://user-images.githubusercontent.com/37503397/106131336-87246080-619d-11eb-8fc0-be8bc0c531f9.mp4

These videos may contain seizure warning.

**Comment by hrydgard** [comment]
Might be able to get close to the cause of this by disabling parts of the JIT (using the JIT options in Development Tools) until it breaks the same way as the interpreter ... kind of the reverse of our traditional way of debugging the JIT.

**Comment by Panderner** [comment]
This does not occur when the CPU core set to Dynarec (JIT)

**Comment by Panderner** [comment]
I got when I disable VFPU_VEC or VFPU_XFER in JIT debugging tools it happened.

**Comment by hrydgard** [comment]
Yeah exactly, run in JIT and disable stuff. Which you did.

Either of VEC or XFER? Or when both are disabled?

**Comment by Panderner** [comment]
Either VEC or XFEC are disabled, when XFER is disabled but VEC is enabled and VEC is disabled but XFEC is enabled

**Comment by hrydgard** [comment]
Ok, thanks for testing. Strange....

**Comment by MojoJojoDojo** [comment]
Happens on both PC and Android.
Both disabled all the VFPU related stuff to see it occur.

**Comment by ANR2ME** [comment]
Apparently not all characters showed the flickering issue.
And disabling VEC or XFEC will still showed the flickering issue on Cloud character intro/lose.

**Comment by ANR2ME** [comment]
Btw, when i disabled VFPU_XFER on Dynarec(JIT) i'm seeing this error in the logs
![image](https://user-images.githubusercontent.com/7974720/180700055-8a6761f5-8a91-4efb-994c-e046779fa70e.png)
This error didn't appeared when not disabling any jit functionality, so may be this error related to the flickering issue?

**Comment by unknownbrackets** [comment]
Well, VFPU_XFER controls setting prefixes so it's going to cause unknown prefixes.

Hm, so it seems in this case that one case that goes wrong is this:

````
	vpfxt	[3,3,3,3]
	vscl.q	C120,C120,S000
```

I remember vscl.q being one of the weird ones, but there must be more nuance to it than initial tests revealed.  In this case, IR is falling back to interpreter because there's a T prefix (which really jit should also do.)  However, clearly the `VFPU_SWIZZLE(2, 2, 2, 2)` forced swizzle is behaving wrong here.

Will need to do some tests, but I'm thinking maybe the forced swizzle on T depends on the register specified for T in some way (i.e. maybe S000 forces X,X,X,X swizzle and S002 or S020 or S200 forces Z,Z,Z,Z.)  Maybe I didn't account for that fully in my prior tests.  If it was X,X,X,X, then `[3,3,3,3]` here would "accidentally" work.

-[Unknown]

**Comment by unknownbrackets** [comment]
See #16302 - did some tests, and it's as I guessed above; it uses the column to force swizzle of all lanes when forwarding to an internal vmul.  vmscl had the same behavior, so corrected both.

-[Unknown]
