### ISSUE TITLE
Samurai Dou Portable - flickering ad-hoc menu and message "Network initialized" is stuck

### ISSUE THREAD

**Issue by MojoJojoDojo** [hrydgard/ppsspp#14065]
short video of how the log looks : https://streamable.com/upvepe
Image of how it looks : 
![image](https://user-images.githubusercontent.com/33392696/107125574-79648e80-68b3-11eb-8d36-08cd7d7e45d9.png)

**Comment by MojoJojoDojo** [comment]
Looks like the game is buggy on real hardware too.
A friend of mine tested it between 2 PSPs and got a signal lost error....

**Comment by ANR2ME** [comment]
This game is looping the Init and Term
On JPCSP+prx : It's doing the next `sceNetInit` without terminating it first with `sceNetTerm`
On PPSSPP: It's doing `sceNetTerm` before the next `sceNetInit`
So i guess that `sceNetTerm` might be where the flow goes wrong (due to wrong returned value may be?) ended causing the flickering.
