### ISSUE TITLE
[Android] Killzone Liberation

### ISSUE THREAD

**Issue by MiguelCardonaG** [hrydgard/ppsspp#14094]
### What happens?
Hello.

When I have enabled the option of "drawn by bufer" the game is very slow. 🤔

![Screenshot_20210209-171227_PPSSPP](https://user-images.githubusercontent.com/65356692/107393156-c2f2ea80-6afa-11eb-8a8a-34c3a459990f.jpg)

But when I have activated the option to "jump bufer effects" the game goes fast but there's no Image. 😔

![Screenshot_20210209-171336_PPSSPP](https://user-images.githubusercontent.com/65356692/107393546-3694f780-6afb-11eb-8b6f-717bcf667bd8.jpg)

### What *should* happen?
So, the option of "jump bufer effects" can be made to see the image?

### Please test newest version in https://buildbot.orphis.net/ppsspp/

Samsung Galaxy Note 10 Plus Exynos.
Android 11.
ppsspp-v1.11-14-g242e59094-android.apk

**Comment by unknownbrackets** [comment]
Skip buffer effects is a speedhack.  When games try to use buffers, we ignore it.  Some things can never render properly with this hack.  It's faster because it's skipping so much.

I recommend checking on the forum and Discord for better options to speed up this game.  Lowering resolution might be a good first step.

Closing this issue - the game needs buffers to render properly.

-[Unknown]

**Comment by MiguelCardonaG** [comment]
I've tried everything, but it's slower than a turtle. 🤣
