### ISSUE TITLE
The Warriors AdHoc

### ISSUE THREAD

**Issue by TemporaryPSP** [hrydgard/ppsspp#14113]
1P: Player 1 (network host, not necessarily the game host)
2P: Player 2

### What happens?
Prior to PR #13967 build, no matter which player hosts the game, it will never start. Since it's merged with 1.11, it should be fixed but no. If 1P hosts the game, 2P will be disconnected even if 1P hasn't started the game. If 2P hosts the game, 1P won't be disconnected from the lobby, but the game won't start.

### What *should* happen?
The game should start normally, even if 2P hosts it. (tested with PR build with multiple instances/localhost)

### PPSSPP version?
Tested with 1.10, 1.10.3-1628-g65af16bcb (PR build), 1.11.

**Comment by MojoJojoDojo** [comment]
It should work with the PR build at least with multiple instances.
If not then I think it's one of the games that are affected by I/O timing or force real clock sync in system options (or fast memory but i doubt that).

**Comment by ANR2ME** [comment]
Hmm.. i can't reproduce this issue on localhost, it always works on my side, but i'm running both instance from the same PPSSPP folder.
May i know which mission did you choose? i'm testing it on the Quick Rumble -> 1on1/Battle Royale

Are you using different folder for each instance? if you are, make sure both PPSSPP exe are excluded from firewall (based on your issue, seems to be one of the instance is being blocked by firewall)

**Comment by TemporaryPSP** [comment]
It works with localhost (1.11) but I tried 2 devices and it didn't work. (PC & Mobile)

Both instances are from the same folder, excluded from firewall, 5000 port offset, no cheats, with the same system settings.

**Comment by ANR2ME** [comment]
Okay i'm able to reproduce it, 
when PC is the host it is working fine, but when android is the host it will loop trying to connect to android but always failed with `EAGAIN/EWOULDBLOCK` error because it's non-blocking `connect` and the game will immediately close the socket and try to connect again with new socket, thus the `connect` attempt never successful as it's too soon to close the socket.

**Comment by ANR2ME** [comment]
@TemporaryPSP You can try this test build while waiting for PR https://github.com/hrydgard/ppsspp/pull/14117 to be merged

Android (ARMv7): https://www.dropbox.com/s/b41bm43mtn1gpnn/PPSSPP_1.11-testbuild_ARMv7.apk?dl=0
Win32/x64: https://www.dropbox.com/s/2t3mtdhb0f045cn/PPSSPP_1.11-testbuild_Win32x64.zip?dl=0

**Comment by TemporaryPSP** [comment]
I've tested mobile to mobile and localhost multiple times, but mobile to PC still doesn't work. Take a look at this video. (Be careful, flickering AVI dump, sorry)

https://user-images.githubusercontent.com/78895214/107971422-08288800-6fe5-11eb-8193-4e9af07ff8d2.mp4

**Comment by ANR2ME** [comment]
@TemporaryPSP Could you redownload the test builds, i've updated it yesterday to include the fix for communication issue between Android vs PC due to detecting an incorrect port. (the fix was intended for MGS:PW but other games could have similar issue too)

I've tested those test builds on The Warriors and found no problem playing on LAN Android vs PC using built-in AdhocServer on PC side.

**Comment by ANR2ME** [comment]
Looks like multiplayer on the Story also works if you waited a bit longer before joining, wait a few seconds after you see the game room before joining, and after joined wait a few seconds before starting the mission.

**Comment by TemporaryPSP** [comment]
Apologies for commenting on a closed thread, but just an update because the wait workaround doesn't work.
No matter which mode (be it 1 on 1, story or other modes) I can't get mobile and PC to work. I tried waiting for minutes before joining the lobby, the game kicks 2P so fast that the name doesn't get a chance to show up.

I could only get mobile-mobile and localhost to work (interchangeable game hosts too) and it worked flawlessly.
Mobile has built-in PRO adhoc server enabled (network host essentially, I tried different network connections too) because I could never get PC to do it.

I know that this issue will take a long time and isn't a priority but again, just an update comment. Maybe there are other workarounds?

**Comment by ANR2ME** [comment]
If mobile to mobile and multiple instances worked, it should also work on PC to mobile.

May be PPSSPP on your PC being blocked by firewall? You need to exclude the exe from firewall.

**Comment by TemporaryPSP** [comment]
It's excluded from firewall, and with the correct Adhoc server IP and everything. The game lobby is visible after all.

**Comment by ANR2ME** [comment]
Hmm have you tried both ways, try using the hosting on mobile and hosting on PC, because sometimes there are cases where both side need to run at the same FPS, so if one is slower than the other (ie. my old phone was struggling to get full FPS while my PC always runs at full FPS) the game could get desynced. 
usually, if the host is the slower one it will be more stable.

**Comment by TemporaryPSP** [comment]
Both devices run at 30 FPS, I tested with 10 FPS too, it worked and desync rarely happened (it only happened once, I even tested unthrottle and it keeps up pretty well) but this is the menu so FPS is not it.

I can't get PC to host at all (not game host) failed to connect to Adhoc server every time even though the IP is correct. (using the list)

**Comment by ANR2ME** [comment]
That's odd if it can't connect to Adhoc server on PC, is the Adhoc Server located on the PC or on mobile ? 

Could you take a screen shot of the Debug Log from Debug menu when it's showing "Failed to connect to Adhoc server", there should be an error code on it.

**Comment by TemporaryPSP** [comment]
As I was trying to reproduce the error, something new happened. Network initialized (this has never happened before) but mobile phone couldn't connect to it (the game kicked mobile from the network menu once instead of getting stuck trying to connect to adhoc server), I tried other devices too, but not a single one could connect.
![ULUS10213_00010](https://user-images.githubusercontent.com/78895214/110140075-4b1c9500-7e06-11eb-9e29-1fdcb8c47dd4.png)

**Comment by ANR2ME** [comment]
Well it's hard to tell without logs file.
And you haven't tell me whether PPSSPP on mobile can successfully connect to built-in AdhocSever on PC side, at this point you should only see Network initialized or Failed to connect to Adhoc Server, and testing built-in AdhocServer on PC will at least tells me that something on your PC is blocking incoming connection.

I suspect this is what will happen:
1). If built-in Adhoc Server on PC side, everyone will get Failed to connect to Adhoc Server, and nobody can see each other.
2). If built-in Adhoc Server on mobile side, everyone will get Network initialized, you can see game room but will have an issue.

If both case are true, that means something on your PC is blocking incoming connection, so PC can only receive data (ie. game room data) but no body can connect to PC side. 
This might happen if you have a network security app on your PC, for example i'm using anti-virus with built-in network secury called Eset Internet Security, and i need to allow "in/out" "UDP/TCP" on PPSSPP exe otherwise it will block incoming connection.

**Comment by TemporaryPSP** [comment]
I disabled network security and that did the trick. It's working perfectly now, I'm sorry for the inconveniences.

**Comment by ANR2ME** [comment]
You don't need to completely disable it since it could pose security risk, you just need to exclude PPSSPP exe from being blocked, or allow incoming/outgoing UDP & TCP.

**Comment by Nugss** [comment]
Why the multiplayer is laggy on 2player's screen? Even the connection is good but on 1player's screen it runs fine. Is that normal?
