### ISSUE TITLE
Tron Legacy PSP lags heavily

### ISSUE THREAD

**Issue by eltomas2003** [hrydgard/ppsspp#14220]
### What happens?
Tron legacy lags and runs at half the speed as it usually does

### Please test newest version in https://buildbot.orphis.net/ppsspp/
windows 10 home, amd ryzen 5

**Comment by ANR2ME** [comment]
It would be helpful if you can find out the last version without this issue.

Btw, have you tried changing the renderer backed to see whether this issue happened only on certain graphic backend or all of them?

**Comment by unknownbrackets** [comment]
Have you tried default settings?

-[Unknown]

**Comment by MojoJojoDojo** [comment]
Yeah this game kinda awfully on PPSSPP even on default settings dunno why.
It's strange because on JPCSP its the opposite - it runs too fast!! lol.

**Comment by unknownbrackets** [comment]
Can you post some screenshots with "show debug statistics" enabled?  And can you post a GE frame dump?

-[Unknown]

**Comment by Gamemulatorer** [comment]
Tron Legacy is also Tron Evolution on psp?

**Comment by unknownbrackets** [comment]
I think Tron Evolution is the name of the PSP game, but it's associated with the movie Tron Legacy.

-[Unknown]

**Comment by Gamemulatorer** [comment]
No lag on my phone
![Screenshot_2021-05-23-11-01-32-910_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/119246714-65207500-bbb6-11eb-94c7-5288e4200f3d.jpg)
![Screenshot_2021-05-23-11-01-45-888_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/119246716-6782cf00-bbb6-11eb-8c2e-c076acbdf718.jpg)

**Comment by unknownbrackets** [comment]
Not sure why it'd lag on Windows, then.  This issue is being closed because it hasn't been updated with feedback (screenshots indicating performance stats to investigate the slowdown.)

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
