### ISSUE TITLE
Ape Academy 2 is broken on versions after 1.8.0(?) - tested on latest nightly and 1.11.3

### ISSUE THREAD

**Issue by Mr-RSpeedy** [hrydgard/ppsspp#14271]
### What happens?
It has a (RESUME) button that wont unpause when you load the ISO

### What *should* happen?
It should go in-game

I have tested Ape academy 2 on the latest nightly as of today, i went back to 11.3 standard where it also did not work, so i checked the compatibility page and has been broken since 1.8.0, i tested it there where the game worked flawlessly. I even had another member of discord confirm and it did not work on 11.3 standard from the website on their desktop too.

**Comment by Panderner** [comment]
@Mr-RSpeedy how's the 1.7.4 worked?

**Comment by unknownbrackets** [comment]
There's not really enough report data to say it has been broken since v1.8.0:
https://report.ppsspp.org/game/UCES00302_1.00

There's only one test before v1.11.x on v1.9.4, which could mean it didn't work then, and could also mean that person used a bad disc (no CRC was included in the report.)

And since then, a user reported it playable (with the same CRC as worked before) in v1.11.2.  Maybe that was a mistake.  But the data isn't very conclusive.

It'd help if you could test more versions and find when it stopped working.  Note that savedata could influence this, if your savedata is corrupt.

-[Unknown]

**Comment by Panderner** [comment]
Please note that 1.9.4 is the last working version.

**Comment by Panderner** [comment]
The last build worked is v1.9.3-189-g6d8ddb7a7
The issue started in v1.9.3-204-g52156ec4e

**Comment by hrydgard** [comment]
Here's all the changes between those: https://github.com/hrydgard/ppsspp/compare/6d8ddb7a7..52156ec4e

**Comment by unknownbrackets** [comment]
So #12550 or #12559.  It seems likely to me it's loading some kernel module or otherwise that isn't working?

The long path one ought to be Windows only...

-[Unknown]

**Comment by Panderner** [comment]
> The long path one ought to be Windows only

It also happens for Android devices.

**Comment by hrydgard** [comment]
Right, so it's likely #12559. Maybe some prx we need to blocklist...

**Comment by unknownbrackets** [comment]
Does it work any better now?  That should fix at least one error, but we might still need to blocklist something.

-[Unknown]

**Comment by Panderner** [comment]
The game now playable in v1.11.2-341-g18525431b, it no longer crashes in boot.

**Comment by unknownbrackets** [comment]
Alright, glad that was enough.  Thanks for confirming.

-[Unknown]
