### ISSUE TITLE
Make ESC button as default pause menu

### ISSUE THREAD

**Issue by minintamvan** [hrydgard/ppsspp#14275]
### What happens?
When i or someone forgot set pause button on control mapping, we force closing the ppsspp because can't pause 
imagine want load state, save state, exit to menu, settings but u can't pause

### What *should* happen?
set ESC as default pause button. or add new system settings option (set as ESC default Pause button)

### What hardware, operating system, and PPSSPP version?  On desktop and mobile phone, GPU matters for graphical issues.
Windows 10 version 2004 | 64Bit

**Comment by unknownbrackets** [comment]
What platform are you on?  There's a reason for these questions.

-[Unknown]

**Comment by minintamvan** [comment]
windows 10 2004 64bit

**Comment by unknownbrackets** [comment]
I downloaded the latest Windows x64 git build (from [actions](https://github.com/hrydgard/ppsspp/actions/runs/633962902)), and extracted into a fresh folder with no settings.  Started that, and see Esc configured as the default pause key indeed:

![Control mapping screen showing Esc assigned to Pause](https://user-images.githubusercontent.com/191233/110569813-e022d500-8109-11eb-86e5-c34d6fe8b342.png)

It also, of course, works just fine in game to hit Esc because of this.

What does your control mapping show?  Have you tried deleting your settings (move ppsspp.ini and controls.ini to a backup folder)?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
