### ISSUE TITLE
The latest build version of ppsspp crashes 

### ISSUE THREAD

**Issue by KaiFujiro** [hrydgard/ppsspp#14280]
Yea it crashes 
crash when the skip buffer effect mode in persona 3.
Previously it was fine with the skip buffer effect mode, but why when I upgrade to the latest version of PPSSPP it crashes? 

•ppsspp-v1.11.2-312-g38e384d83
•Android 5.1.1

**Comment by ANR2ME** [comment]
Do you remember the last working version?

**Comment by KaiFujiro** [comment]
Yes 
I used this version before
v1.11.2-309-g8e90d0644

**Comment by unknownbrackets** [comment]
Hm, maybe #14273 crashes on some GLES drivers?

-[Unknown]

**Comment by hrydgard** [comment]
I restored the GLES behavior... let's see.

**Comment by unknownbrackets** [comment]
Is the latest git build working now?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
