### ISSUE TITLE
Audio lag

### ISSUE THREAD

**Issue by Agentwindex** [hrydgard/ppsspp#14282]
### What happens?
whenever Evangelion: Jo switches to a 3D environment the audio lags beyond being unusable. while 2D still works perfectly.

### What *should* happen?
The audio shouldn't lag into oblivion.

### What hardware, operating system, and PPSSPP version?  On desktop and mobile phone, GPU matters for graphical issues.
I don't know my hardware, but I'm using windows, and my PSP ver is 1.11.3

**Comment by ANR2ME** [comment]
Is this issue happened recently (ie. regression) or it's been like that since long ago?
If it's happened recently, do you remembered the last working version that works properly?

**Comment by hrydgard** [comment]
Audio lag happens when the emulator just can't keep up. 

If you enable the frame rate display (far down in graphics settings), do you see it dip hard from 30 or 60 when it happens?

**Comment by unknownbrackets** [comment]
Also try other graphics backends, restart your PC, and make sure you have texture scaling disabled.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
