### ISSUE TITLE
Texture Scaling - Upscale level Resetting

### ISSUE THREAD

**Issue by Jeff-Epic** [hrydgard/ppsspp#14298]
Whenever I play a game and I changed my Upscale level it's good at first but if I pause and go to Settings and unpause, it resets my Upscale level and this also happens when I continue a saved into my game, but it doesn't reset when I first ever start a game without saves.
![image](https://user-images.githubusercontent.com/80749644/111284191-defa2680-867a-11eb-8d25-477e3a1cde09.png)
![image](https://user-images.githubusercontent.com/80749644/111284329-fd602200-867a-11eb-981f-5fcde4b7355a.png)

**Comment by LunaMoo** [comment]
What do you mean by "level resetting"?

 Do you mean textures are getting scaled with different level? Screenshots doesn't really show anything obvious.

 Or maybe you just mean textures aren't scaled anymore and they scale after a few moments?
 If so that's normal and expected behaviour. Texture scaling runs on CPU and is too heavy to be ran in real time, so anything that would cause texture cache to be cleared would require all currently loaded textures to be re-scalled and that would take some time. If you're using a modern desktop gaming PC you can use Vulkan and activate hardware texture scaling, this doesn't have limits and runs on GPU which is fast enough to still run at full speed, at least if you own a decent gaming GPU.

 You can also use texture replacement instead which results in much higher quality, but if none exist, you'd have to create your own texture pack, pretty easy with AI scaling algorithms, but even with that need quite a lot of manual work.

**Comment by unknownbrackets** [comment]
What I see in the screenshots is the OSD in the top right.  Words help though - what's obvious to you isn't obvious to everyone, that's why humans communicate in the first place.

Does this happen if you use Vulkan and enable a texture shader in settings?  This will cause it to scale using the GPU.

-[Unknown]

**Comment by Jeff-Epic** [comment]
I only experience the upscale during the first time playing a game and it doesn't upscale when I load a save game from the in-built game save and it also resets if I pause and go to the Options tab then unpause, it doesn't reset while playing for a while. It also does that in every Backend but I use OpenGL and I just have a medium laptop.

**Comment by unknownbrackets** [comment]
Okay.  The problem is that scaling all textures immediately requires either:
* Doing it using the GPU, which is the part of your computer designed to process graphics.
* Using a liquid-submerged heavily overclocked 64 core supercomputer CPU to do it.

OpenGL (and Direct3D 9 or 11) can only use the second option right now, which in your case is a puny non-supercomputer CPU.  Vulkan is able to use your GPU, which would work even without access to a supercomputer (but works better with more powerful GPUs, of course.)

Because you're not using a texture shader, and your computer certainly isn't capable of scaling all textures immediately, the best it can handle is scaling some textures over time.  Eventually, it builds up upscaled textures and keeps reusing them.

When you change settings, it throws away all those "built up" upscaled textures and starts over.  That's why it "resets".

-[Unknown]

**Comment by Jeff-Epic** [comment]
Is there no way to fix it on my laptop? Because I don't have that stuff.

**Comment by LunaMoo** [comment]
If it's just about things like UI, you could use texture replacement, dump the UI textures, process them via for example ESRGAN with something like UltraYandere model and use such upscaled textures via replacement, would look better than texture scaling as well. I mean you could use the same thing for all textures, it's just that making a whole texture pack is time consuming and everything other than UI seems to be scaled on your screenshots even with limited CPU based xBRZ.

**Comment by Jeff-Epic** [comment]
ok
