### ISSUE TITLE
UI: Combine the Views on the startup screen; add sorting option

### ISSUE THREAD

**Issue by DavidTamas** [hrydgard/ppsspp#14296]
### What should happen?
From user experience point of view it makes no sense to have separate views for recently played games, another one for all games and a third for homebrew & demos (whose contents is identical to the second one anyway). Intead these should be combined into a single view and an option should be added to the Games List Settings menu to sort content by
- Game Name
- Last Played
- UMDserial_UMDversion (like the Display extra info -> Show ID option display them)

As an added bonus the Games List Settings menu would get a cleanup at the same time.

### Who would benefit from it?
End users would get a cleaner UI.

#### Checklist

 - [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
 - [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by LunaMoo** [comment]
Those 3 views aren't the same. 

 Homebrew is special case which need to be stored in PSP/Game folder, commercial games should NOT be stored there, that view also allow installing homebrew from PPSSPP store.

 Games view is just a file browser, it doesn't lists all games or anything like that, it just allows you to find your games whenever you stored them. 

 Recent view is what you see after running PPSSPP and can instantly run whatever you ran earlier, always sorted by last lauched so you can instantly jump in to what you player earlier.

 Most users got used to those 3 views and it would definitely NOT be a wanted change to remove those just because one user think otherwise. Sorting does have sense, but only for games and homebrew. Recent by name should always be sorted as it is now to keep it simple and pretty without extra icons other views are looking ugly from, since recent view is basically the "face" of PPSSPP.

**Comment by hrydgard** [comment]
What LunaMoo said.
