### ISSUE TITLE
Window size restarts on closing

### ISSUE THREAD

**Issue by JaegerFox** [hrydgard/ppsspp#14317]
### What happens?
Every time I start a game and close PPSSPP the "window size scale" preset stops working
The scale at which it resets takes up the entire screen.

### What *should* happen?
In previous versions 1.9.x it kept the scale of the window when closing PPSSPP in any way, in 1.10 for the first time it presented these problems

### What are you using?
Windows 8.1
Intel HD Graphics
using the last nigthly
I thought this problem was common, I looked and did not find something similar, I do not know if it is something related to my hardware. but in version 1.9.3 it works as it should

-This bug can be reproduced by opening a game, wait a bit and close PPSSPP, reopen it and the window size will restart. If this does not happen just try a few more times

**Comment by ANR2ME** [comment]
Are you using D3D ?

I experiencing random windows size almost every time i launched Debug version of PPSSPP on D3D, although it rarely happened on Release build but there might be some issue with D3D11 (didn't happened on vulkan/opengl)

**Comment by JaegerFox** [comment]
@ANR2ME 
This happens to me in D3D9/11 and OGL
and only one instance at a time ...

**Comment by unknownbrackets** [comment]
Do you have some window manager software?  For example, I use an ultrawide monitor and specifically avoided its window management software to avoid bugs like this.

I've never seen PPSSPP resize my window unexpectedly, although I don't generally use game-specific settings (and the rare times I do, the window size is not something I customize.)  Is it perhaps related to that?

I can't think of anything new in v1.10.x that would cause this, but the above are my best guesses.

-[Unknown]

**Comment by JaegerFox** [comment]
@unknownbrackets I do not use any of that kind of software, even so it is weird that only this happens in the new versions

**Comment by ANR2ME** [comment]
I also didn't use window manager software, similar to that video but sometimes the width is correctly set to 1x Window while the height is about the height of my desktop, which making it looks weird.
And in my case it only happened on D3D with Debug build, i haven't been getting this issue on Release build.

The first time i found this issue was when i was implementing multi-instance, back then i thought the settings got currupted when closing down multiple PPSSPP nearly at the same time, and then you guys made it not to save settings on the 2nd or more instances.
But recently, i just noticed it started to shows up again when i use D3D11, so i suspect it has something to do with D3D (i haven't been using D3D for a long time, and started to use it again because i started to feels annoyed with how often vulkan to caught assert exception while debugging)

**Comment by ANR2ME** [comment]
Btw which part of the code should i put breakpoint to find out whether the window's width and height arguments are correctly set or not when the first time PPSSPP window appeared ?

**Comment by unknownbrackets** [comment]
This happens in `SetWindowSize()` within MainWindow.cpp, but also `DetermineWindowRectangle()`.

Does it help to remove the `SavePosition();` call right below `RECT rc = DetermineWindowRectangle();`?  I'm not sure why it's there, `hwndMain` doesn't exist yet.  Maybe it's something related to that...

-[Unknown]

**Comment by ANR2ME** [comment]
After removing that `RECT rc = DetermineWindowRectangle();`  and tested 10 times of running 2x instances, this issue didn't seems to appear anymore.

**Comment by JaegerFox** [comment]
But with me appears just using one instance
by the way where I can find that build fix? @ANR2ME

**Comment by ANR2ME** [comment]
Okay i'll create the PR so you can download it from the artifact

**Comment by ANR2ME** [comment]
@JaegerFox you can download the artifact from that PR later to test it
Here is the one for Win 64bit https://github.com/hrydgard/ppsspp/pull/14329/checks?check_run_id=2223650293

**Comment by JaegerFox** [comment]
@ANR2ME definitely that solved the problem, I tried to close and reopen PPSSPP several times and in all it keep the window size
Thanks for your attention
