### ISSUE TITLE
Patapon 3 (Europe) stuck when selecting a language

### ISSUE THREAD

**Issue by ANR2ME** [hrydgard/ppsspp#14338]
A few seconds after launching the game you need to select a language, and when selecting a language (ie. English), the game will stuck and can't progress any further, with or without ignoring bad memory access.
![image](https://user-images.githubusercontent.com/7974720/113467606-387d9600-946e-11eb-8b62-1eceb25a96a8.png)

While with an older version (v1.11-4-gc4a4fbd5c) the game can be played by ignoring bad memory access
![image](https://user-images.githubusercontent.com/7974720/113467233-f5222800-946b-11eb-8d3b-6fca777d8046.png)
Anything newer (ie. [v1.11-9-g3af26a24e](https://github.com/hrydgard/ppsspp/commit/3af26a24edc50a1d4b9852e48c515c5e01cffe46) ) will stuck.

PS: The US version didn't have this issue, only Europe version.

Is this intended behavior with the new changes?

### What should happen?
Not to stuck and making it playable again, whenever possible

#### Checklist

 - [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
 - [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by ANR2ME** [comment]
Apparently when it stuck, Pausing emulation and then Continue/resuming it will make the game progress further, but it's a strange way to play this game, and i didn't aware this trick would work O.o (probably many players didn't know this trick too)

**Comment by unknownbrackets** [comment]
Well, resuming from a jump to 0 is tricky business.  Do you know if this ever worked before?  Is it affected by wlan?  I'd have expected it to be more widely reported.

It's been reported as working well (with ingame screenshots) in v1.10.3:
https://report.ppsspp.org/game/UCES01421_1.01

If it hung for many people at language select, I'd expect to see language select screenshots.

It seems like it crashed after asking for PSP_SYSTEMPARAM_ID_INT_LANGUAGE, I wonder if `sceImposeSetLanguageMode` is supposed to interact with that value and the game is confused because it isn't... it seemed to set PSP_SYSTEMPARAM_LANGUAGE_ENGLISH, is your language set to that / if you set it to that, does it behave differently?

-[Unknown]

**Comment by ANR2ME** [comment]
Yes, this game working fine before https://github.com/hrydgard/ppsspp/commit/3af26a24edc50a1d4b9852e48c515c5e01cffe46 although it's getting bad memory access in the log, but ignoring it will silently makes the game progressed further and can be played normally, while with the latest version it's getting blue screen now.

it's a bit strange, i was testing it yesterday many times while finding the PR where it starting to stuck, and strangely during my test it didn't get blue screen even though it's getting bad memory access, the screen still showing the language selection but stuck there, but now it's showing blue screen with the latest version.

Disabling WLAN have no difference.

I use English for PPSSPP, but selecting any language on Patapon 3 have similar issue (ie. bad memory access)

**Comment by ANR2ME** [comment]
Ooops sorry, i didn't realized that my Cheat is enabled, it probably for the US version
I will close this now.
