### ISSUE TITLE
Analog axis freeze

### ISSUE THREAD

**Issue by MRMaldani** [hrydgard/ppsspp#14336]
### What happens?
Analog axis sometimes freeze

### What *should* happen?
Analog axis working normally

#### What hardware / device and operating system?
Xiaomi, Android
#### What graphics card (GPU) or mobile phone model?
Redmi Note 8
#### What PPSSPP version (standalone/official), and did it work before?
v1.11.3, no it didn't
#### Which game or games?

ULUS10021

#### Checklist

 - [x] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [ ] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [x] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
This isn't a lot of detail.  Is this potentially the same as #12569?  How have you configured your controller?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
