### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by clondy999** [hrydgard/ppsspp#14339]
ubuntu16.04 64-bit compilation error.
Error log:
____________________________________________________
Determining if the pthread_create exist failed with the following output:
Change Dir: /root/Neo-EmuELEC-H3/build.EmuELEC-H3.arm-3.9/ppsspp-6ca01d5882a1517b941d7d6ff80a37b64c372e92/.armv7ve-libreelec-linux-gnueabi/CMakeFiles/CMakeTmp

Run Build Command(s):/root/Neo-EmuELEC-H3/build.EmuELEC-H3.arm-3.9/toolchain/bin/ninja cmTC_917b5
[1/2] Building C object CMakeFiles/cmTC_917b5.dir/CheckSymbolExists.c.o
[2/2] Linking C executable cmTC_917b5
FAILED: cmTC_917b5
: && /root/Neo-EmuELEC-H3/build.EmuELEC-H3.arm-3.9/toolchain/bin/armv7ve-libreelec-linux-gnueabi-gcc -march=armv7ve -mtune=cortex-a7 -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -mcpu=cortex-a7 -mfloat-abi=hard -mfpu=neon-vfpv4 -fomit-frame-pointer -Wall -pipe -O3 -march=armv7ve -mtune=cortex-a7 -Wl,--as-needed -fuse-ld=gold CMakeFiles/cmTC_917b5.dir/CheckSymbolExists.c.o -o cmTC_917b5 && :
CMakeFiles/cmTC_917b5.dir/CheckSymbolExists.c.o:CheckSymbolExists.c:function main: error: undefined reference to 'pthread_create'
CMakeFiles/cmTC_917b5.dir/CheckSymbolExists.c.o:CheckSymbolExists.c:function main: error: undefined reference to 'pthread_create'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

File /root/Neo-EmuELEC-H3/build.EmuELEC-H3.arm-3.9/ppsspp-6ca01d5882a1517b941d7d6ff80a37b64c372e92/.armv7ve-libreelec-linux-gnueabi/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
(void)argv;
#ifndef pthread_create
return ((int*)(&pthread_create))[argc];
#else
(void)argc;
return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /root/Neo-EmuELEC-H3/build.EmuELEC-H3.arm-3.9/ppsspp-6ca01d5882a1517b941d7d6ff80a37b64c372e92/.armv7ve-libreelec-linux-gnueabi/CMakeFiles/CMakeTmp

Run Build Command(s):/root/Neo-EmuELEC-H3/build.EmuELEC-H3.arm-3.9/toolchain/bin/ninja cmTC_98823
[1/2] Building C object CMakeFiles/cmTC_98823.dir/CheckFunctionExists.c.o
[2/2] Linking C executable cmTC_98823
FAILED: cmTC_98823
: && /root/Neo-EmuELEC-H3/build.EmuELEC-H3.arm-3.9/toolchain/bin/armv7ve-libreelec-linux-gnueabi-gcc -march=armv7ve -mtune=cortex-a7 -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -mcpu=cortex-a7 -mfloat-abi=hard -mfpu=neon-vfpv4 -fomit-frame-pointer -Wall -pipe -O3 -DCHECK_FUNCTION_EXISTS=pthread_create -march=armv7ve -mtune=cortex-a7 -Wl,--as-needed -fuse-ld=gold CMakeFiles/cmTC_98823.dir/CheckFunctionExists.c.o -o cmTC_98823 -lpthreads && :
/root/Neo-EmuELEC-H3/build.EmuELEC-H3.arm-3.9/toolchain/lib/gcc/armv7ve-libreelec-linux-gnueabi/8.3.0/../../../../armv7ve-libreelec-linux-gnueabi/bin/ld.gold: error: cannot find -lpthreads
CMakeFiles/cmTC_98823.dir/CheckFunctionExists.c.o:CheckFunctionExists.c:function main: error: undefined reference to 'pthread_create'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by unknownbrackets** [comment]
It looks to me like you're compiling for armv7 (i.e. 32-bit), not armv8 (64-bit.)  Are you cross compiling?

According to a quick Google search for your error messages, it sounds like this is a common CMake issue and it's caused by missing dev libraries (but potentially not pthreads, apparently that gets misreported by CMake sometimes.)

Is it possible you've not installed the dependencies in the build instructions?  Or that you've installed 64-bit versions of them only, and you're now compiling 32-bit so they are missing?

Also, if your CPU is capable of 64-bit armv8, I recommend compiling for that instead.  The jit performance should be better.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other builds, and sometimes certain system configurations prevent builds without being fixed at the system level.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.

-[Unknown]
