### ISSUE TITLE
Building on AARCH64:  b.sh error and cmake error

### ISSUE THREAD

**Issue by clort81** [hrydgard/ppsspp#14351]
system: devuan aarch64 (khadas vim3)
ppsspp git master (feb 23)

ppsspp/build$ cmake ..
-- Could NOT find PNG: Found unsuitable version "1.6.37", but required is at least "1.7" (found /usr/lib/aarch64-linux-gnu/libpng.so)

If i build the ext/libpng17 i just get a libpng17.a, not a libpng17.so to put in /usr/lib/aarch64-linux-gnu/

How could i build a libpng17.so or tell cmake to use libpng17.a?   I don't even find a libpng 1.7 on the libpng website or github or svn.  That's weird!

-----------------------------------------

trying ./b.sh -qt
configuring works, but make yields

/usr/bin/ld: cannot find -lSPVRemapper
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/PPSSPPQt.dir/build.make:669: PPSSPPQt] Error 1
make[1]: *** [CMakeFiles/Makefile2:496: CMakeFiles/PPSSPPQt.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

Any thoughts/tips on either problem?
cmakecache from ppsspp/
[CMakeCache.txt](https://github.com/hrydgard/ppsspp/files/6256585/CMakeCache.txt)
cmakecache from ppsspp/build/
[build_CMakeCache.txt](https://github.com/hrydgard/ppsspp/files/6256589/build_CMakeCache.txt)

**Comment by unknownbrackets** [comment]
As a workaround, you could delete these two lines:
https://github.com/hrydgard/ppsspp/blob/0081924fc48995ae25919ee51cd6348cf9d05a9e/CMakeLists.txt#L857-L858

That would force it to use the libpng17 as a static library.  Otherwise you'd need to build as a shared object, which the provided CMakeLists.txt won't help with.

For the latter error, it might work to put -DENABLE_SPVREMAPPER=OFF in the cmake args b.sh is passing, but I don't know why it's different for you.

-[Unknown]

**Comment by clort81** [comment]
Both worked.  Thank you sir knight!  Closing.

**Comment by clort81** [comment]
I found that grabbing the original libpng17 and building it gets me a libpng17.so
it can be grabbed here
[https://ftp-osl.osuosl.org/pub/libpng/src/beta/libpng17/](https://ftp-osl.osuosl.org/pub/libpng/src/beta/libpng17/)
