### ISSUE TITLE
Mouse Wheel Bug - Error en la rueda del mouse.

### ISSUE THREAD

**Issue by Mikarynn18** [hrydgard/ppsspp#14378]
Buenas, tengo una duda sobre un error que se ve presente a la hora de utilizar la configuración de "ajustar ratón", y este error se presenta en la rueda del mouse al establecerla, es decir juego Monster Hunter Portable 3rd y Freedom Unite, configure la rueda para que al subirla, esta suba la cámara, y viceversa cuando la bajas, sin embargo a la hora recurrir a esta acción no capta o recibe la orden de movimiento por lo cual tienes que volver a subir o bajar la rueda para que tome la acción el la camara, no se si es un error de la configuración, o esta herramienta de "Controles" no esta bien ajustada o es un bug.

- Google Traductor

Hi, I have a doubt about an error that is present when using the "adjust the mouse" configuration, and this error appears in the mouse wheel when setting it, that is, I play Monster Hunter Portable 3rd and Freedom Unite, configure the wheel so that when you raise it, it raises the camera, and vice versa when you lower them, however when resorting to this action does not capture or receive the movement order, so you have to raise or lower the wheel again so that take the action on the camera, I don't know if it is a configuration error, or this "Controls" tool is not well adjusted or it is a bug.

**Comment by LunaMoo** [comment]
Not sure if that's what you mean, but MH games does not have smooth camera control for up and down, that's just how this function works in the game itself. If you hold a key changing camera up or down it will only move once and since there's short animation involved I don't think it even reacts to all button presses if they're spammed too much which pretty much how mouse wheel works.
 Your best bet would be to just patch the game to work differently, it's camera control is pretty bad to begin with and even in HD remaster is just using digital with programmed accelerations and delays.

**Comment by unknownbrackets** [comment]
Does it work okay in other games?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
