### ISSUE TITLE
error fetching miniupnp repo with bitbake gitsm fetcher

### ISSUE THREAD

**Issue by MarkusVolk** [hrydgard/ppsspp#14386]
Trying to fetch the ppsspp Repo with bitbake gitsm fetcher i ran into the following problem:

```
WARNING: ppsspp-libretro-2021+gitAUTOINC+74f08bee2a-r0 do_fetch: Failed to fetch URL gitsm://github.com/hrydgard/miniupnp.git;protocol=https;name=ext/miniupnp;subpath=ext/miniupnp;bareclone=1;nobranch=1, attempting MIRRORS if available
ERROR: ppsspp-libretro-2021+gitAUTOINC+74f08bee2a-r0 do_fetch: Fetcher failure: Unable to find revision 7e229ddd635933239583ab190d9b614bde018157 in branch master even from upstream
```

On a closer look i encountered, that revision 7e229ddd635933239583ab190d9b614bde018157 indeed is not available in the default branch.

![Bildschirmfoto von 2021-04-17 10-17-33](https://user-images.githubusercontent.com/6180877/115107158-69c78d00-9f69-11eb-88b5-5d37bc34d660.png)

**Comment by unknownbrackets** [comment]
Well, it's actually on upstream:
https://github.com/miniupnp/miniupnp/pull/486

The git sha is accessible within .git/ from the server.  Git doesn't actually require the repo to have the sha in a branch, though you might normally do that to avoid it being garbage collected.  In this case, the sha won't go away because upstream has it on a branch.

So I'd really consider this a bug in gitsm.  It's not following git rules correctly.

With that said, we should probably update the master branch of that repo.

-[Unknown]

**Comment by hrydgard** [comment]
Made a PR to do the update.

**Comment by hrydgard** [comment]
Probable fix has been merged.

**Comment by MarkusVolk** [comment]
The Problem is solved. No Error while fetching and i also was able to build the current code for arm ( raspberrypi 4) and aarch64 (rock-pi-4) 

Thanks :)
