### ISSUE TITLE
The ability to alter analog zones.

### ISSUE THREAD

**Issue by Justice-Net** [hrydgard/ppsspp#14417]
I know that there's another issue posted that's similar, but I really don't understand what the user is referring to so I wanted to make my request separate.

Right now I'm having issues with the analog sticks on my SN30 Pro+ not registering as far as PPSSPP would like. This is causing me problems in games like The Warriors, where my character can only run in certain directions, where in others he can only walk.

It would be great if there was an option to 'resize' the area that determines how far your analog stick is pushed toward. You could make it like a red circle in the area where you test your analog sticks.

**Comment by LunaMoo** [comment]
We have something like that already althrough not sure if it exists outside of Windows where it's within Dinput/Xinput settings. It's called "analog mapper high-end".

**Comment by Justice-Net** [comment]
So I just found that option on android, but a couple of issues that can be ironed out:

1. Why in the world is it in the on screen controls section? If anything it should be in Control Mapping.
2.  It's difficult to get it right without trial and error. If there was a way to edit it in the analog stick test that would be great.

**Comment by LunaMoo** [comment]
Well all settings for controls are on the same screen, and mapping as well as test screens have no settings whatsoever.
  Also this is rare issue, most people aren't affected at all and if you are, you just set it once.

**Comment by hrydgard** [comment]
Also, just haven't spent the time yet - I want to do a big redesign of analog stick handling, but more urgent issues keep getting in the way.

**Comment by MojoJojoDojo** [comment]
The analog sticks feel kinda different from how the PSP analog sticks behave as well.
not by a small amount too.

**Comment by unknownbrackets** [comment]
Well, yes.  There's probably a different curve involved for the same amount of thumb movement for the PSP analog vs a real analog.  The PSP analog was basically linear, since it was just a sliding disc.  But a real analog stick is a ball, so you move a bit more at the edges.  At the same time, it had greater resistance, so outside the deadzone area, it was a bit stiff to get moving.  I really don't miss using the PSP analog nub.

Seems like what we really want is the ability to set a deadzone size, plus range scale and offset (to inverse deadzone) per device or potentially per axis.  That way it would apply generically to tilt, etc. as well.

So it probably makes sense as its own screen.  Maybe we can convert the existing device IDs for the existing dinput/xinput settings if we make it per device, at least.  But it might mean moving a device's axes to detect it.

-[Unknown]

**Comment by hrydgard** [comment]
This is now more configurable, you should be able to set up something that works for you with the new joystick calibration. Closing.
