### ISSUE TITLE
Version number control bug

### ISSUE THREAD

**Issue by Halo-Michael** [hrydgard/ppsspp#14427]
I think you may forgot to clean up the number of commits.
![1%8D8ZO 7P~YEU4FG_(}OKJ](https://user-images.githubusercontent.com/45062120/116814958-dfe50a00-ab8d-11eb-979f-4a8fe78f3da9.png)
This inherits the number of commits since 1.11.2.

**Comment by unknownbrackets** [comment]
It's actually the number of commits from v1.11.3.  v1.11.2 and v1.11.3 were only different by a few commits.  It was showing v1.11.2-* only because technically, v1.11.3 was created from a separate branch, so those extra few commits were a different "path" and not the past of git builds.

We fixed that, but the current code is still over 500 commits improved from v1.11.3.

This isn't wrong, it's just confusing because the branch wasn't merged back in right away.

Also, git is calculating these commits (correctly) based on the tags.  Even if we wanted to "reset the number", we actually couldn't without deleting the v1.11.3 tag and marking it incorrectly as if that release had included more changes.  This is a git feature to count number of commits since the tag.

-[Unknown]
