### ISSUE TITLE
Provide ppsspp core for retroarch ios

### ISSUE THREAD

**Issue by Stevie-T** [hrydgard/ppsspp#14430]
### What should happen?
Currently, ppsspp core is available on retroarch for android but not in the ios version. It would great if this can be added to the ios version as well. According to retroarch, core requests can only be handled by the core developer. https://github.com/libretro/RetroArch/issues/5230

### Who would benefit from it?
Altstore users who are only able to sideload two applications at a time. By adding the core to retroarch, users can emulate psp games through retroarch and allow to sideload another application instead of ppsspp.

**Comment by xSimone** [comment]
This would be nice.. ;x

**Comment by RenYang99431** [comment]
good suggest, I need iOS version for retroarch too.

**Comment by unknownbrackets** [comment]
We don't provide iOS builds officially in the first place.  We also don't provide libretro builds.  Both of those are provided by the community / others.

That said, PPSSPP standalone works on iOS (although jit can be problematic), especially with AltStore.  I assume it should work on iOS too, but I don't know if more is required for libretro.

Currently, there are iOS builds of PPSSPP itself available from the community, at https://p.xx.wtf/.  That said, the most active collaborators to PPSSPP tend not to do much with iOS due to Apple's stance on emulation.  That means, if you'd like to see this, you should really be thinking about how *you* could help make it happen.

-[Unknown]

**Comment by benjamingranados** [comment]
Nice! is a reality now!!!! I installed it via AltStore (I just removed all the other cores from the IPA file before installing it) and is awesome!!!! It includes the PPSSPP core. Remember to download the PSP additional files from the online updater on the iPhone for it to work in some games: https://buildbot.libretro.com/nightly/apple/ios-arm64/RetroArch.ipa

**Comment by unknownbrackets** [comment]
Great, I'm going to close this then.  Thanks for noting.

-[Unknown]
