### ISSUE TITLE
Keep connection alive [online ad-hoc netplay]

### ISSUE THREAD

**Issue by samosaphile** [hrydgard/ppsspp#14455]
### What should happen?
When in lobby and waiting for a player in a online ad-hoc game. If you multitask on android or put ppsspp as a background app, just to check something (e.g. discord) and then return back to ppsspp, it should still be connected to ad-hoc server and you should still be there in lobby almost as if you never left and see all chat messages. 

I also notice some games resume more gracefully than others. For example, Blazblue, as soon as ppsspp app, will instantly start scanning for games and players in lobby again. Whereas in most other games, it's abit more cumbersome. Sometimes you need to go back to main menu and re enter network mode or do something else manually, to get anything to show up.

### Who would benefit from it?
Ppsspp android build users.

#### Checklist

 - [ ] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
 - [ ] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by ANR2ME** [comment]
I think it's limitation on Android, some android OS will suspend app in background, thus causing the thread that supposed to ping adhoc server every few seconds to stop pinging.

Connection to adhoc server is being keep alive by pinging adhoc server every few seconds to prevent adhoc server from kicking that player out (the default timeout on adhoc server side is 15 seconds), but seems to work properly only on PC, because PC naturally allows multiple app running at the same time.

Anyway, once you're disconnected/kicked out from adhoc server you'll need to initialize network again by going back to main menu, because once you're no longer in a group/friendlist, all players will see you as leaving the group and you're removed from their friendlist, and there is no way to rejoin the group other than through lobby.
It's not something that can be restored in background because lobby procedure is complicated and depends on how the game were designed.

**Comment by samosaphile** [comment]
Yeah, I figured this might be the case that limitations on mobile platform suspended apps. 

I don't have such a option (lock / manage) on my phone. Seems like a vendor or custom ROM feature.

Oh well, I guess nothing can be done about it. You can close this issue. Sorry for wasting everyone's time and thanks for explaining!
