### ISSUE TITLE
[Linux] Controller mapping not working.

### ISSUE THREAD

**Issue by CloneMMDDCVII** [hrydgard/ppsspp#14471]
[gamecontrollerdb.txt](https://github.com/hrydgard/ppsspp/files/6493980/gamecontrollerdb.txt)

### What happens?
I'm using a Nintendo-licensed USB Switch controller (One like this https://www.walmart.com/ip/PowerA-Wired-Controller-for-Nintendo-Switch-Link-1506260-02/828491694?wmlspartner=wlpa&selectedSellerId=698). It's recognised by Dolphin on Linux, but PPSSPP is not letting me map controls using it.

PPSSPP detects it's not part of the SDL controller DB, and attempts to create a mapping for it :
`loading control pad mappings from gamecontrollerdb.txt: SUCCESS!
Control pad device 0 not supported by SDL game controller database, attempting to create default mapping...
Added default mapping ok
found control pad: Bensussen Deutsch & Associates, loading mapping: SUCCESS, mapping is:
03000000d620000011a7000011010000,Bensussen Deutsch & Associates,Inc.(BDA) Core (Plus) Wired Controller,x:b3,a:b0,b:b1,y:b2,back:b8,guide:b10,start:b9,dpleft:b15,dpdown:b14,dpright:b16,dpup:b13,leftshoulder:b4,lefttrigger:a2,rightshoulder:b6,rightshoulder:b5,righttrigger:a5,leftstick:b7,leftstick:b11,rightstick:b12,leftx:a0,lefty:a1,rightx:a3,righty:a4
pad 1 has been assigned to control pad: Bensussen Deutsch & Associates
` 
This matches the mapping I tried to create manually.

~~I also tried inserting the mapping into gamecontrollerdb.txt, and PPSSPP still reacts the same way.~~ It now loads the controller, still won't map though.

PPSSPP won't let me map controls with this gamepad.

### What *should* happen?
PPSSPP should import the mapping properly.

#### What hardware / device and operating system?
Linux Mint 20.1
Ryzen 1800X, NVidia 1070ti, Vulkan.
#### What PPSSPP version (standalone/official), and did it work before?
V1.11.3-635-g2987b8c17

I'm wondering whether this is due to the special character in the name (Bensussen Deutsch **&** Associates,Inc.(BDA) Core (Plus) Wired Controller)
evtest, jstest and SDL2 Gamepad Mapper all detect my controller properly

--EDIT
I hadn't edited the databse the right way. I now have, PPSSPP is loading the controller, but still will not allow me to map it to controls.

`Virtual pixels: 960 x 544
OpenGL 2.0 or higher.
loading control pad mappings from gamecontrollerdb.txt: SUCCESS!
found control pad: Bensussen Deutsch & Associates, loading mapping: SUCCESS, mapping is:
03000000d620000011a7000011010000,Bensussen Deutsch & Associates,Inc.(BDA) Core (Plus) Wired Controller,x:b3,a:b0,b:b1,y:b2,back:b8,guide:b10,start:b9,dpleft:b15,dpdown:b14,dpright:b16,dpup:b13,leftshoulder:b4,lefttrigger:a2,rightshoulder:b6,rightshoulder:b5,righttrigger:a5,leftstick:b7,leftstick:b11,rightstick:b12,leftx:a0,lefty:a1,rightx:a3,righty:a4,platform:Linux,
pad 1 has been assigned to control pad: Bensussen Deutsch & Associates
`

**Comment by CloneMMDDCVII** [comment]
Right, I found the issue, there is a comma in the Device Manufacturer's name.
When removing it from the database entry, PPSSPP is now able to load the gamepad and use it.

Maybe if PPSSPP ignored commas when coming up with a layout if not found in the database ?

**Comment by unknownbrackets** [comment]
This sounds like a bug either in the tool creating the database entry.  We don't actually parse the database, commas or not - SDL is doing that.  We just call `SDL_GameControllerAddMappingsFromRW()` from SDL.

What tool did you use to create the mapping?

I don't think the name in there matters, which is why it worked when removing the comma.  Probably the tool should either not allow commas or put quotes around the name if it has a comma in it.  So this is likely a bug in that tool.

-[Unknown]

**Comment by CloneMMDDCVII** [comment]
I used https://gitlab.com/ryochan7/sdl2-gamepad-mapper to create the mapping.

From what I see, PPSSPP imports the mapping either from the SDL library as you pointed out or from the GameControllerDB.txt, but in both cases is unable to make use of it if the name contains a comma. Is this a bug I should report to the sdl project instead ?

**Comment by unknownbrackets** [comment]
This isn't really an SDL bug either, most likely.  From a quick look, the bug appears to be here in that tool you used:

https://gitlab.com/ryochan7/sdl2-gamepad-mapper/-/blob/master/mappinggcviewbackend.cpp#L278

Think of it this way: if you tried to signup for GitHub, it would ask you for an email address.  If you typed "you can contact me at foo@bar.com" in the email address field, it would tell you your email address was invalid.  No matter who you talked to at GitHub, they probably wouldn't fix this.  The format you've provided them isn't valid - they just want an email.

It's the same in this case.  SDL is expecting a list of values, each separated by commas.  Because the name had an extra comma in it, SDL just assumed the "Inc" was the next value - how should it know that it's part of the name?  It's like if I filled out a shipping form, but all my address fields were in the wrong places.  Even if it accepts my order, it's not going to ship to me correctly.

This isn't even an uncommon issue, I did a quick Google and:

https://github.com/recalbox/recalbox-configgen/issues/119

-[Unknown]

**Comment by hrydgard** [comment]
Feel free to post a corrected and tested version of the line, so we can add it to the file that ships with PPSSPP.

**Comment by CloneMMDDCVII** [comment]
@unknownbrackets The issue ocured from the default config that PPSSPP attempts to generate, the tool is just something I tried as a troublehsooting step later.

The first snippet is the terminal output from PPSSPPSDL, when there wasn't a valid config line present.
It recognises the presence of a controller, but finds no assigned config.
It then (using SDL, presumably) attempts to create a default mapping, using the USB controller name.

I suppose it stores the created config as a temporary resource, but isn't able to use it, because the name contains a comma.
if the way the default config is invoked doesn't sanitise it's input, either by removing comas in the device name or quoting it, potentially resulting in an unusable default config, I think that's a bug ?

@hrydgard I'm not yet happy with the mapping line I've got, I'll submit it once I've adjusted it, some buttons need reconfigurations.

**Comment by hrydgard** [comment]
Adding a line will avoid it doing all that automatic stuff - which is not actually done by PPSSPP itself, but by SDL, so there might indeed be an SDL bug.

**Comment by unknownbrackets** [comment]
Ah, my bad.  This indeed does look like a bug in PPSSPP as well, I thought we just used SDL:

https://github.com/hrydgard/ppsspp/blob/0c40e918c92b897f745abee0d09cf033a1572337/SDL/SDLJoystick.cpp#L64

This is clearly not a file I've looked at much since I see "using namespace std;" which I'm not a fan of.

-[Unknown]

**Comment by CloneMMDDCVII** [comment]
`03000000d620000011a7000011010000,PowerA Nintendo Switch Wired Controller,a:b1,b:b2,x:b0,y:b3,back:b8,guide:b12,start:b9,leftshoulder:b4,rightshoulder:b5,leftstick:b10,rightstick:b11,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,platform:Linux,`

Everything seems to be good, apart from `L` and `R` that aren't consistent with the default mappings, and need to be assigned manually inside the `Control Mapping` sub-menu.

Thanks a lot for all your hard work
