### ISSUE TITLE
Assets are not loaded on RPi / Libretro

### ISSUE THREAD

**Issue by vjarskee** [hrydgard/ppsspp#14486]
### What happens?
I downloaded the assets folder, put it in ~ / .config / retroarch / system / PPSSPP / assets, but assets are still not loaded

### What are you using?
RPi 4, Raspbian, Libretro

**Comment by unknownbrackets** [comment]
https://github.com/hrydgard/ppsspp/issues/13737#issuecomment-781036910

You can't just grab the latest assets from the latest git and use them in an older version.  Assets have been updated with faster decompression and smaller file sizes, which will be in the next stable release.  If you're using some stable release, you need the assets for that release.

This is why all the proper releases of PPSSPP include the assets.  Just like proper releases of Photoshop include more than just the exe.

I know libretro/retroarch hasn't figured out how to achieve that yet.

Closing as this isn't an issue to be fixed in PPSSPP.

-[Unknown]
