### ISSUE TITLE
Movie Intro's lag and crash

### ISSUE THREAD

**Issue by Rstation4** [hrydgard/ppsspp#14491]
Raspberry PI 4 2gb
Emulator Frontend : Lakka OS - Lakka-RPi4.aarch64-3.0
Core: PPSSPP
Rom format: iso

In the prior Lakka Versions and Nightly versions for the RPi 4 I have noticed that PPSSPP has had some issues. The intro's tend to lag, which I had seen with plenty of roms for the PSP system. With this recent Lakka version I have tried several roms where the issue occurs as well such as "Metal Gear Acid (USA)", "Summon Night 5 (version 2) (USA)", "Metal Slug Anthology (USA)" and "Jeanne d' Arc (USA)". With the case of "Metal Slug Anthology" The intro lagged and then it froze the RPi 4 unit hard at the end of the intro which I needed to turn off the unit"

It kept repeating some last 2 lines and the original log bloated up to 140 Mb's.

I was told to report  the issue here. "_It's occuring in all retro distros. The issue is mainly on ffmpeg. You should report this to the core developers as it's not lakka related_"

logs
[Retroarch ppsspp.log](https://github.com/hrydgard/ppsspp/files/6566367/Retroarch.ppsspp.log)

**Comment by unknownbrackets** [comment]
Does this happen with PPSSPP proper?  Libretro is not really designed for multithreaded emulators so there are systemic issues.  I'm pretty sure performance is just always worse and has been for a while.  If this is libretro specific, it might not get fixed for some time.

If you're using system FFmpeg and a PPSSPP stable version, this is not performance related but because you're using system FFmpeg (which we never recommend.)  However, this issue has been improved in latest git (of course future FFmpeg versions may break it again, and we still don't recommend system FFmpeg.)

-[Unknown]

**Comment by unknownbrackets** [comment]
Per https://github.com/libretro/Lakka-LibreELEC/issues/1352 it seems like this has been updated in Lakka.

-[Unknown]

**Comment by gouchi** [comment]
@Rstation4 Please close this issue. 

Thank you.

**Comment by unknownbrackets** [comment]
Closing this, assuming that fix in Lakka took care of it.

-[Unknown]
