### ISSUE TITLE
Build failed on Ubuntu 20.04

### ISSUE THREAD

**Issue by Sunderland93** [hrydgard/ppsspp#14556]
### What platform, compiler, and build tools?
Ubuntu 20.04, GCC 9.3.0

### What compile flags or command did you run specifically?
`-DUSE_FFMPEG=ON -DUSE_SYSTEM_SNAPPY=ON -DUSE_SYSTEM_LIBZIP=ON -DUSE_SYSTEM_FFMPEG=OFF -DUSE_DISCORD=OFF -DUSE_WAYLAND_WSI=ON`

### What happens (don't forget logs)?
Build failed with `/usr/bin/ld: ./obj_qt/./ext/miniupnp/miniupnpc/miniupnpc.c:652: undefined reference to `addr_is_reserved'`
Full log: https://launchpadlibrarian.net/545139797/buildlog_ubuntu-focal-amd64.ppsspp_1.11.3-1~retrogames_BUILDING.txt.gz

#### What PPSSPP version (standalone/official), and did it work before?
PPSSPP v1.11.3

**Comment by unknownbrackets** [comment]
Seems like you forgot to update submodules or something, I recommend running `git submodule update --init`, deleting the build directory, and re-running cmake in a fresh build directory.

There should be an addr_is_reserved.c in the miniupnpc submodule, which your log never built.

Every commit is built on Ubuntu 20 / GCC 9.3.0: https://github.com/hrydgard/ppsspp/runs/2884436466

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.  I'm assuming it was submodule related.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
