### ISSUE TITLE
[Android] Jean D'Arc gfx issue vertical white line

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#14564]
### What happens?

There's a vertical white line in the right side during the intro of the game
![Screenshot_2021-06-26-19-57-33-924_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/123512459-2ea8af00-d6ba-11eb-8730-a20db285287b.jpg)

### What *should* happen?

No vertical white line
#### What graphics card (GPU) or mobile phone model?
REDMI NOTE 9
#### What PPSSPP version (standalone/official), and did it work before?
ppsspp latest development apk
#### Which game or games?

UCUS98700
#### Graphics backend (Vulkan, OpenGL, etc.)?

Both backend
#### Checklist

 - [✓ ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [ ✓] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ ✓] Try resetting settings or older versions and include if the issue is related.
 - [✓ ] Try changing graphics settings to determine if one causes the bug.
 - [✓ ] Include logs or screenshots of issue.

**Comment by Panderner** [comment]
@Gamemulatorer Screenshot?

**Comment by Gamemulatorer** [comment]
> @Gamemulatorer Screenshot?

Can you try on your poco m3 if this issue can also reproduce

**Comment by Gamemulatorer** [comment]
Loading a savestate on this game have an issue 🤔

**Comment by Panderner** [comment]
Save states works fine for me.

**Comment by Gamemulatorer** [comment]
> Save states works fine for me.

Try my savestate
[PPSSPP_STATE_UCUS98700.zip](https://github.com/hrydgard/ppsspp/files/6721057/PPSSPP_STATE_UCUS98700.zip)

**Comment by Panderner** [comment]
@Gamemulatorer here's my working save state:
[Working Save State.zip](https://github.com/hrydgard/ppsspp/files/6721465/Working.Save.State.zip)

**Comment by Gamemulatorer** [comment]
> @Gamemulatorer here's my working save state:
> [Working Save State.zip](https://github.com/hrydgard/ppsspp/files/6721465/Working.Save.State.zip)

Just try my savestate and see if you can reproduce my issue 🤷

**Comment by Panderner** [comment]
I already reproduced the save state issue It's not works

**Comment by unknownbrackets** [comment]
This save state is corrupted.  ZSTD doesn't seem to realize it's decompressing bad data, though, which is concerning.  It means one of a few things:

1. We somehow generated corrupt data, and then asked ZSTD to compress it, so the corrupted data is properly decompressed.
2. The compressed data was corrupted, and ZSTD didn't notice and it causes it to produce corrupt output data.
3. The data was generated correctly, but compression generated silently incorrect ZSTD data that decompresses as valid data.

The corruption specifically is that, near the very end, it suddenly stops (in the middle of save state data for an IntrHandler) and the rest of the buffer is all NUL bytes.  ZSTD claims it decompressed the correct number of bytes, which matches the header.

I haven't seen this with any other save states though, so it's hard to confirm which of the above scenarios it might be.

Have you seen this with any other save state since?

-[Unknown]

**Comment by hrydgard** [comment]
That is somewhat scary, and means that we should probably do a quick CRC of ZSTD data (cryptographic hash not necessary since it's just an integrity check). The same probably applies to other compression systems really.

I guess the smarter and better your compression codec, the bigger the chance that any random bytes accidentally is a valid stream for something... Good for ratio, bad for integrity.

**Comment by unknownbrackets** [comment]
I created #14692 motivated by the save state issue.  I'm still pretty concerned about this and still considering switching back to Snappy or adding a hidden ini option...

About the white line: I looked at the intro and didn't notice it.  Does it happen at 1x PSP render resolution without any texture upscaling?

-[Unknown]

**Comment by Gamemulatorer** [comment]
> About the white line: I looked at the intro and didn't notice it. Does it happen at 1x PSP render resolution without any texture upscaling?
> 
> -[Unknown]

It doesn't happen on 1X rendering resolution 🤔

**Comment by Gamemulatorer** [comment]
Closing this because saving issue is fixed and about the white line is cause by higher resolution and not a bug.
