### ISSUE TITLE
CMakeLists.txt:735 (find package) FFmpeg not found

### ISSUE THREAD

**Issue by revdeluxe** [hrydgard/ppsspp#14574]
### What platform, compiler, and build tools?
Architecture : x86_64
Window_mode: X11, Gnome 3.38.5
Compiler: Cmake

### What compile flags or command did you run specifically?
CMake Error at CMakeLists.txt:380 (add_subdirectory):
  add_subdirectory given source "ext" which is not an existing directory.

CMake Error at CMakeLists.txt:735 (find_package):
  By not providing "FindFFmpeg.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "FFmpeg", but
  CMake did not find one.

  Could not find a package configuration file provided by "FFmpeg" with any
  of the following names:

    FFmpegConfig.cmake
    ffmpeg-config.cmake

  Add the installation prefix of "FFmpeg" to CMAKE_PREFIX_PATH or set
  "FFmpeg_DIR" to a directory containing one of the above files.  If "FFmpeg"
  provides a separate development package or SDK, be sure it has been
  installed.
~This is the Actual Message~
### What happens (don't forget logs)?
i tried to if i have all the packages it seems some of them actually doesn't exist on Kali(Latest)
im not that Good in Builing from Source.

###
Currently Running
Kali Linux Rolling 64-bit
OpenGL 2.0/Opengles 3.0
Intel Celeron N3060 2.56ghz
4gb ram 500gb rom

#### What PPSSPP version (standalone/official), and did it work before?
nope, Definately first time building from a source.
i wanted to build SDL, because 1.7.5 PPSSPPSDL release was a charm 
because the PPA doesn't work
gpg key are missing. tried it tons of times...

retroarch PPSSPP is not stable, Spec Hungry...
Emustation/Retropie PPSSPP is working but has a lot of graphic issues especially on Monster Hunter...

Here's The log i got tired reading the Error one so i didn't read it, and im not that good at C++.
[Here](https://drive.google.com/file/d/18qHutPWtjZhZnU4jN92SI0hGz0zi8eLL/view?usp=sharing)

#### Checklist

 - [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [ ] Don't forget `git submodule update --init --recursive`.
 - [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ ] Try deleting the build directory and starting fresh.
 - [X] Include logs and help us reproduce.
 - [ ] Check GitHub Actions, which builds every merge and PR.

**Comment by LunaMoo** [comment]
Did you followed https://github.com/hrydgard/ppsspp/wiki/Build-instructions especially the part about cloning submodules? Most common scenario people can't build PPSSPP is exactly because they clone PPSSPP repo without submodules.

**Comment by unknownbrackets** [comment]
Every commit is built on Linux, and the errors indicate you've most likely done something wrong:

> add_subdirectory given source "ext" which is not an existing directory.

This directory should exist.  You've probably:

1. Run out of disk space while cloning / exacting PPSSPP, but ignored the errors.
2. Copied CMakeLists.txt to another folder, and tried to build using this copy, which won't work.
3. Corrupted your cmake arguments previously and never tried a clean rebuild.

This doesn't seem like an issue in PPSSPP.  I also briefly checked your logs and see you're building in SDL/build, which is theoretically fine, but unusual.  I recommend using `./b.sh` instead, as per the instructions.

I'm closing this because it's not an issue.  You can still reply in comments, but I recommend trying all the things in the checkboxes you didn't check, and follow the instructions LunaMoo sent.

-[Unknown]
