### ISSUE TITLE
AC:FFEB - Ad-hoc netplay broken

### ISSUE THREAD

**Issue by samosaphile** [hrydgard/ppsspp#14573]
### What happens?
In Armored Core Formula Front Extreme Battle (USA), when you send a versus battle request, the other person doesn't receive anything and vice versa. This was tested on both ports 15k and 20k on socom.cc.

![Screenshot_20210629-184411](https://user-images.githubusercontent.com/30265284/123847700-cb638a80-d90e-11eb-85e6-fea7c623bebc.png)

(To enable ad-hoc in this game btw, after you press start, go to connection and accept the enable wlan message, then select versus mode. I too was also abit confused how to do it in this game, at first)

### What *should* happen?
Players should be able to receive a battle request message if sent one and be able to accept.

#### What hardware / device and operating system?
Pixel 4a on stock PixelOS. (Android 11)
#### What graphics card (GPU) or mobile phone model?
Adreno 618 / Sunfish.
#### What PPSSPP version (standalone/official), and did it work before?
1.11.2-432 and 1.11.3-742.
#### Which game or games?

ULUS10034

#### Checklist

 - [ ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [ ] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ ] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
Was this game worked before? Or never worked?

**Comment by samosaphile** [comment]
Ok, I'm closing this issue now. My bad, I made a mistake and reported abit too hastily. But before I do, I would like to report some interesting findings:

1. When you do get this to work, it is super laggy. (So I've pretty much given up on this game, I mainly tested with a friend who lives quite far from me, so your mileage may vary if you play with someone much closer to you). But then again, my friend doesn't lag at all or much in many other games. Maybe this game just has poor netcode.

2. For me, I could not get this to work on port offset 10k, 15k, 20k. Only 60k. Afterburner black falcon is another game which is similar in this respect.

3. There seems to be very little difference between build versions for online play in games (which is why I kinda stopped specifying in the first place - as it really doesn't seem to matter) not saying there aren't improvements in newer builds but that they seem to be targeting or making fixing for a few select titles (e.g. metal gear solid, socom games).

4.  Against conventional wisdom, a port offset of 10k-20k isn't really needed. From my findings, atleast for me (on android, testing with mostly other mobile users), non problematic games work just fine with a port offset as small as 2500. and the few that dont, sometimes using an offset of 60k fixes.

**Comment by ANR2ME** [comment]
Regarding Port Offset, issue may happen if a game is trying to use a port that is already taken by another program (ie. background service), since different games are using different ports by using the same port offset some of these games might bumped into an already taken ports, and different Operating systems or device might have different port usage too.
Which is why Port Offset existed, so Players can find a good port for certain games that aren't being used by any programs.
And recently i found out that some games have a strange issue when using Port Offset 5000, where the port being used by the sender being detected as a different port on the receiver, causing them unable to communicate properly, it seems to be an undocumented behavior, and i haven't found an explanation why it happened yet.

Regarding fixes or improvements, we're trying to make them general instead of game-specific, and i've removed most of game-specific workarounds related to network with a proper fix (which should fix other games with similar issue too), but because we don't have an accurate timings on network/adhoc HLE, some timing changes might affect/regress other games too, and we can only wait for reports that can pinpoint which commits causing the regression.
