### ISSUE TITLE
Open project in android studio 

### ISSUE THREAD

**Issue by imad17** [hrydgard/ppsspp#14593]
I get lot of errors when i open project in android studio is this project support android ?

**Comment by hrydgard** [comment]
yes, it supports Android just fine, should build right out of the box.

Did you clone with submodules? If not do `git submodule update --init`

**Comment by imad17** [comment]
Aha thanks hrydgard for your fast replay i will try this

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
