### ISSUE TITLE
[Game List UI] Cursor does not follow Page Up/Dn (+ a couple of feature suggestions)

### ISSUE THREAD

**Issue by alpozcan** [hrydgard/ppsspp#14618]
### What happens?

If I scroll through a multiple-page game list in PPSSPP-SDL UI using Page Up and Page Down keys, the page scrolls but the cursor remains in the same location. If I then press up or down arrow keys it scrolls back to where the cursor was in an awkward manner.

### What *should* happen?

Page Up/Down should also move the selection cursor in game list.

#### What hardware / device and operating system?
Kubuntu 21.04 SDL build (from source) x64_64 on an 8th gen NUC.

#### What graphics card (GPU) or mobile phone model?
Intel IGP

#### What PPSSPP version (standalone/official), and did it work before?
https://github.com/hrydgard/ppsspp/commit/8aa78a8ef462e3eafc215dfae3f4aa3da4fb1a65.
Disclaimer: This build is recent but I did not recompile and test with the latest HEAD.

#### Checklist

 - [ ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [X] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

**Comment by alpozcan** [comment]
Also, it would be awesome to have these enhancements on the game list I think:
- Abiity to quick search - maybe just start typing and this starts a substring search on game list entries. At least, key presses can scroll to the first entry starting with that letter similar to a file explorer.
- Have a short delay before trying to read the ISO while scrolling through the list.

My archive is mounted via a network share over a wifi-connection. In relatively slow I/O scenarios like this, it is hard to find a game in a large game list and it becomes 'choppy' and unresponsive while simply moving the cursor through the list.

**Comment by unknownbrackets** [comment]
Hmm, yeah the page down thing seems like a bug.

Internally, search can be implemented in a similar way to #14414, but the blockers are just getting that merged and then figuring out the right UI for it.  I don't like the idea of only starting to type, because I want a consistent UX across platforms as much as possible and many don't involve keyboards.  This includes mobile phones and TV + controller setups.

> Have a short delay before trying to read the ISO while scrolling through the list.

This is strange.  On Android, I use PPSSPP most commonly through wifi (it even has a feature to browse and run a disc image off an internal network http server to make this even easier.)  I haven't seen these choppy scenarios, although I haven't done much remote browsing in recent git builds.

If you are running off a slow network storage, you may want to consider changing IO Timing to "Host" instead of "Fast".  The downside is that you'll get non-deterministic gameplay (it will depend on the storage speed), but this will replace stutters with loading screens.  Caching the ISO in RAM is asynhronous, so you can still get some stutter with only that setting.

-[Unknown]

**Comment by alpozcan** [comment]
Hi [Unknown],
With the default 'fast' IO timing, does that mean with the current config I could get stutters but only for a while after first booting an ISO?

Regarding the cursor bug, if you can point me to the source file or line(s) I can try my luck in fixing it (even though I haven't coded C/C++ in a looong time.

**Comment by unknownbrackets** [comment]
Sorry for the delay - yes, that's what it means.  In practice, your OS will probably also cache data so it'd be the first time after a boot.

There was some complexity here, but I went ahead and implemented page up/page down and also home/end in a more sensible way for keyboard focus.

-[Unknown]

**Comment by alpozcan** [comment]
thanks!
