### ISSUE TITLE
Focus regression in control mapping

### ISSUE THREAD

**Issue by iota97** [hrydgard/ppsspp#14780]
A couple of regression in master not happening in 1.11.3:

1) Control mapping screen used to refocus the key after binding it.

2) Kinda worse one if deleting a binding with the X choice while navigating with the keyboard (probably controller too, didn't test tho') the focus get teleported way down the list.

e7666e472f9cb03dfac4dacf0afc25bf57973f1b is the first bad commit.

Recreating the view in update() might have broke it ig?

**Comment by unknownbrackets** [comment]
Hm, it was handling focus in a strange and also very coupled way before...

-[Unknown]

**Comment by iota97** [comment]
Well I get this since that commit when I delete the binding: [video.zip](https://github.com/hrydgard/ppsspp/files/7073374/video.zip).

Might be a race condition on update that doesn't happen on all machine? Or was happening already to someone before?

**Comment by unknownbrackets** [comment]
Right, there were a few issues but basically it was caused by the view recreating its child views (refresh.)  The timing sorta worked before, but only based on an unfocusable view being force-marked focused.  This was being recreated a bit earlier now, so focus wasn't restored (since it's an unfocusable view.)

In #14781 it just uses SetFocus() and uses our standard refocusing logic, same that runs on screen resize, etc.

-[Unknown]
