### ISSUE TITLE
Problem with replacing textures

### ISSUE THREAD

**Issue by ASKUTKRIMSON** [hrydgard/ppsspp#14792]
### Game or games this happens in

ULUS-10466

### What area of the game / PPSSPP

![000000009182d82724f773ce](https://user-images.githubusercontent.com/84001806/132059432-d5bf0253-b86b-41ea-b5c5-f5c61a8f59fa.png)
![image](https://user-images.githubusercontent.com/84001806/132060369-0b2f381d-89b7-482d-a86e-55db652332a1.png)

![a](https://user-images.githubusercontent.com/84001806/132060494-aa3453ce-1bac-4ed7-8075-c847834bf11f.png)
![image](https://user-images.githubusercontent.com/84001806/132060614-5c4a8e71-2761-490b-b6de-ff1ded2f3ef8.png)

I like to make textures for tekken 6 in ppsspp, but I, like hundreds of other texturizers, have a problem that has not been fixed since version 1.9.3 - the emulator simply refuses to accept some textures, and if you use a special program to make the texture semi-transparent, the emulator will accept it, and not just accept it, but will also show it in the game as the original (without transparency). No one knows what caused this error, I only know that none of those who knew about this problem thought of writing about it on GitHub. All other texturizers just make the textures semi-transparent so that they work. However, such textures sometimes weigh almost 5 times more than the original, which GREATLY increases the size of the texture pack. Therefore, I ask you to fix this error, which has been in the emulator for many years.

### What should happen

It seems to me that since the emulator supports texture replacement, it should do it well

### Logs

with original texture
[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/7108309/ppsspplog.txt)

with 50% transparency
[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/7108298/ppsspplog.txt)

### Platform

Windows

### Mobile phone model or graphics card

GTX 1660 ti

### PPSSPP version affected

v1.11.3-1189-g2cf9b3d51

### Last working version

v1.11.3-1189-g2cf9b3d51

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by ASKUTKRIMSON** [comment]
I made a mistake with the second texture(this is not the original) here is the original
![000000009182d82724f773ce](https://user-images.githubusercontent.com/84001806/132061932-4a303f8f-374f-4438-9499-5befee3f4e38.png)

logs 
[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/7108332/ppsspplog.txt)

**Comment by unknownbrackets** [comment]
Texture replacement doesn't change the game's code or rendering logic - it just replaces the textures they used.

For some reason, which I cannot explain, the developers of this game decided to make the texture semi transparent.  Then they modify the colors during the actual 3D drawing, so that it comes out as the different colors.  Perhaps also the designers of the game who worked on the original graphics complained to the developers internally, asking why they did this.

You would need to contact Bandai Namco to learn why they chose to do this.  It could be they ported some of their code from PS2 or PS3, or something, and this made it easier to share code or assets between systems due to some limitation.  We could only guess as we were not involved in the development of this game.

As far as rewriting the game's rendering logic to work with textures the way you think the developer ought to have managed them, you'll need to modify the game's code (this will probably involve learning MIPS) and release a patch (i.e. xdelta3 modifying the ELF) to make this change.  The texture replacement syst5em isn't for code modifications, but PPSSPP does have a debugger and memory viewer.

Some games will do more significant changes to texture data during rendering, such as altering the colors using lighting, or doubling the colors, or expecting 100% transparency with color values.  You may even find games that alter game logic or AI behavior based on exact color values in textures.  All of this is just logic designed by the original developers of the game.  Texture replacement either has to work within this logic, or be accompanied by a game patch.

This is not a bug.

-[Unknown]

**Comment by iota97** [comment]
Are you really sure those not working aren't JPEG tho'? I tried both firefox and chrome and only with the non working one I keep getting a JPEG file named with `.png` extension. I can download other image just fine too.

Don't get me wrong, it might just be what unknownbrackets mentioned but 5 times bigger seem still kinda too much for an alpha channel to me (all 50% too, PNG should be able to compress that really good), but I want to make sure you didn't just renamed the file to get a png because that won't work.

Can you try with this one here if it work (behold my artistic skill :P)?
![out](https://user-images.githubusercontent.com/13517524/132063703-1b084da1-f060-4a80-98ff-da63d5987a54.png)

**Comment by unknownbrackets** [comment]
I wouldn't be surprised if GitHub is converting to a JPEG on upload/view.

As I briefly touched on, 50% alpha is a common technique used by PS2 ports or games that reuse PS2 graphics engines, because that's how PS2 blending worked.  The PSP graphics chip actually has a flag ("double alpha") meant to make it easier to port PS2 games.

If you use a full alpha value, it works just like it did on the PS2, increasing color intensity during blending.  So if you have a 50% gray color with 100% alpha, and this flag is used, it will actually render as 100% white.  As far as I can tell, that's what's being reported here (and in the first screenshot.)  The game is most probably using this flag.  I don't think it was released on PS2, so I couldn't say why.  Probably they reused the PS2 engine, but again this is just guesswork.  Maybe they wanted to have a way to brighten some parts.

So yes, it may also be a JPEG problem, but the overall complaint here is about the rendering technique the game uses.

-[Unknown]

**Comment by ASKUTKRIMSON** [comment]
> I wouldn't be surprised if GitHub is converting to a JPEG on upload/view.
> 
> As I briefly touched on, 50% alpha is a common technique used by PS2 ports or games that reuse PS2 graphics engines, because that's how PS2 blending worked. The PSP graphics chip actually has a flag ("double alpha") meant to make it easier to port PS2 games.
> 
> If you use a full alpha value, it works just like it did on the PS2, increasing color intensity during blending. So if you have a 50% gray color with 100% alpha, and this flag is used, it will actually render as 100% white. As far as I can tell, that's what's being reported here (and in the first screenshot.) The game is most probably using this flag. I don't think it was released on PS2, so I couldn't say why. Probably they reused the PS2 engine, but again this is just guesswork. Maybe they wanted to have a way to brighten some parts.
> 
> So yes, it may also be a JPEG problem, but the overall complaint here is about the rendering technique the game uses.
> 
> -[Unknown]

You absolutely right 🙂. 
Tekken 6 was released on 3 platforms: psp, ps3 and xbox360. However, the psp could not handle the engine from the ps3 or xbox360. I realized this when I was parsing textures from the xbox360 version. It turns out that Tekken 6 on psp was made on the tekken 5 engine, I also realized this when I disassembled tekken 5 with ps2. From-that and similar between t6 and t5. Here is an example of a texture with t5: dark resurrection:
![000000001f26d1e4fe53c64d](https://user-images.githubusercontent.com/84001806/132087031-474cc655-e34a-45a4-ae84-aace08f66488.png)

 and here is the texture with t6 psp:
![1630741349258](https://user-images.githubusercontent.com/84001806/132087096-33678623-afbe-498c-8df8-f526e67f107e.jpg)
