### ISSUE TITLE
[Vulkan] Fate/EXTRA incorrect shadow position on vulkan

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#15015]
### Game or games this happens in

ULUS10576

### What area of the game

School Building 1st Floor

### What happens

**vulkan** shadow position is incorrect
![Screenshot_2021-10-13-19-18-46-251_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/137124936-0fdb9347-e0f8-4a56-9e0e-0762fca668a6.jpg)

**opengl** shadow position is kinda correct?
![Screenshot_2021-10-13-19-19-05-776_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/137125000-a6f76f61-f29c-4d2e-8ec3-67d73816ec46.jpg)

### What should happen

**Software Rendering** is most likely the correct one.

![Screenshot_2021-10-13-19-24-15-157_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/137124065-4c959f7b-cb53-4ac0-a16f-0896c0f19995.jpg)

### GE frame capture

[ppsspp.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7285680/ppsspp.ppdmp.zip)

### Platform

Android

### Mobile phone model or graphics card

RN9 Android11 Helio G85 Mali-G52 GPU

### PPSSPP version affected

v1.12.2-2

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
Shadows are drawn on the floor at 343/554 - 409/554 from 0x04127780 using a tex matrix.

I think the actual shadows are rendered from draw 2/554 - 23/554.  But this draws to 0x040cc000, 0x040d4000, 0x040d6000, and not the texture addresses which are 0x04127780 and 0x0417f390.  I wonder if it downloads or if there's a block transfer or something.

Tried forcing dirty for all params and most of the shader uniforms, but still drawing wrong differently from GL.  Hm.  Interesting also, it's wrong in Direct3D 9 and Direct3D 11 as well, exactly like Vulkan.  Only GL is safe, *and* only GL with hardware transform on.  That's a crucial bit.

Now here's the kicker: it uses flat shading.  Which always uses software transform.  Disabling that makes it only misbehave in software transform.

Turns out this was a shader ID issue.  The relevant bit was being ignored in software transform.  Might fix some other similar bugs?

-[Unknown]
