### ISSUE TITLE
[Debugger] Adding/Removing Breakpoint shouldn't changed the disassembled address

### ISSUE THREAD

**Issue by ANR2ME** [hrydgard/ppsspp#15017]
### What should happen

Whenever i add/remove a breakpoint on a specific address while the CPU is still running, it always changed the disassembled view to this address near 08000000
![image](https://user-images.githubusercontent.com/7974720/137259440-6918cd8c-02cf-4e4d-95fb-a0d7303db4ca.png)
This can be annoying if we have multiple breakpoints that need to be added/removed, since we need to use the "Go To" feature to go back to the previous address for each breakpoint after the location changed.

Adding/Removing breakpoint without breaking shouldn't changed the view location isn't?

### Who would this benefit

Anyone using the Debugger

### Games this would be useful in

Any games

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by unknownbrackets** [comment]
FWIW, the web debugger already keeps position when you set a breakpoint while running.  This is only a bug in the Windows debugger.

I'm of two minds about this.  On one hand, I'm worried that eventually web standards are going to make our use case problematic because we can't really have a trusted certificate easily.  On the other, the web debugger is more cross platform and already has small improvements over the Windows debugger in some areas... though it's lacking some major features, like memory view and call stack, at the moment.

-[Unknown]

**Comment by Nugss** [comment]
Hello guys, is there any way to undo changes from debugger??

My game has graphics problem when i try this

**Comment by unknownbrackets** [comment]
There's not really a way to undo changes, but you can reload the game.

-[Unknown]
