### ISSUE TITLE
PPSSPP will hang after choose app private folder (scope storage)

### ISSUE THREAD

**Issue by Narugakuruga** [hrydgard/ppsspp#15011]
PPSSPP hanging after I skip the scope storage setting, and can be solve by forcing the app closed then restart. 
All behaviors are normal after restarting. Only the very first boot is affected (hanging up)

### Platform

Android

### Mobile phone model or graphics card

Redmi K30 5G Snapdragon 765

### PPSSPP version affected

1.12.2

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
-
![Screenshot_2021-10-08-09-52-40-985_org ppsspp ppsspp](https://user-images.githubusercontent.com/31060534/136934562-deb0d64a-516e-4f2d-b9a1-c46f8dcc3e34.jpg)

**Comment by unknownbrackets** [comment]
That's not good.  Thanks for reporting.

-[Unknown]

**Comment by unknownbrackets** [comment]
I've seen a few other people reporting issues here, though I didn't experience any myself.

Wonder if people just have slow storage, slow Android scoped storage overhead, and have some install data or otherwise that takes a long time to copy?  Maybe the answer to this is really better progress info / copy speed display / something that updates to tell them a large file is still going.

-[Unknown]

**Comment by hrydgard** [comment]
Note tp self for later that this repros on my Pixel 3a

**Comment by hrydgard** [comment]
Fixed now, silly oversight. Don't know how it got through my testing.
