### ISSUE TITLE
Error when updating id_ID.ini

### ISSUE THREAD

**Issue by PutuDesca** [hrydgard/ppsspp#15087]
how to fix it?

even though I have perfected all the translations but when I upload the uwp build error occurs

I have repeated the upload four times but the result is the same

HELP ME!!!

![IMG_20211102_113543.JPG](https://user-images.githubusercontent.com/93461649/139782951-e8f1b95a-c091-41fb-9e18-50da72fe72d4.JPG)

**Comment by PutuDesca** [comment]
Will this have any effect?

**Comment by unknownbrackets** [comment]
It's because you moved the file from "assets/lang/id_ID.ini" to "aktiva/lang/id_ID.ini".  With computers, names of things matter: it can't guess that it's probably the same file when you move it somewhere else.  It needs it to have exactly the right name.

You don't need to keep reopening PRs, if you push updated commits to the same PR the checks will try again.

-[Unknown]

**Comment by PutuDesca** [comment]
ok, i will try again

**Comment by PutuDesca** [comment]
finally it worked, thank you very much
