### ISSUE TITLE
"Bugged" Background with 4xBRZ Texture Shader

### ISSUE THREAD

**Issue by bajolzas** [hrydgard/ppsspp#15094]
### Game or games this happens in

ULES00176 : Tales of Eternia

### What area of the game

Initial screen, basically on every screen outside battle or world map (the background screen must be composed of various textures "blocks")

### What happens

When using 4xBRZ Texture Shader, the background texture grid gets filled with black dots.

![ULES00176_00000](https://user-images.githubusercontent.com/51722671/140200699-4fd9e0e0-2bc1-435d-b745-3a58258659f6.jpg)

The same does not happen when using the similar Upscale type xBRZ (the old one with delay). No black dots and the grid effect is much less noticeable.

![ULES00176_00001](https://user-images.githubusercontent.com/51722671/140200725-f7739fa4-1fbc-41a4-b000-cdb92a108b97.jpg)

### What should happen

4xBRZ Texture Shader should work more like how xBRZ Upscale type work (minus upscale delay), i.e. without creating artifacts or obvious texture banding.

### Platform

Windows

### Mobile phone model or graphics card

NVIDIA GeForce RTX 2060

### PPSSPP version affected

v1.12.3-146-gd917204da

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by LunaMoo** [comment]
Both are actually "bugged".
 This is just a slight difference in the corners since BR family of algorithms has tons of various versions with minor differences and CPU & GPU ones were based on different variants, you could get different upscaling algorithms for vulkan GPU based texture scaling, but the one we have is not worse in objective way, it just look worse in this example.

 The CPU based algorithm also causes very nasty glitches here, just doesn't bleed black in some corners which makes it less obvious at first glance, but once you see the glitches, you can't unsee them, it's worse than just looking at native res pixel art.
 
 Basically some 2D games have large textures made out of smaller ones and all texture upscaling algorithms treat those  just like any other texture and bleed between those tiles trying to blend sharp edges into more natural looking image, but this is creating artifacts when the game starts treating pieces of such large texture again as separate tiles to create an image.

 The only way currently to have upscaling in such games and have it glitch free is using post process based upscaling, as long as it's fully 2D game the difference is minimal and if it's not using native PSP res, I posted a special version of xBRZ which can be used at high res and have user selectable scalling, you can find it in [PPSSPP custom shader's thread](https://forums.ppsspp.org/showthread.php?tid=6594), but really if the game is using native PSP res, xBR included in PPSSPP is enough.

**Comment by Gamemulatorer** [comment]
This game also stutter a lot during intro using vulkan compare to opengl.

**OpenGL**

https://user-images.githubusercontent.com/37603562/140268670-56977347-4075-4aba-9191-a0eff33f37bb.mp4

**Vulkan**

https://user-images.githubusercontent.com/37603562/140268697-183f164c-d9c7-451b-a948-32e3d56ce5fc.mp4

**Comment by hrydgard** [comment]
This is actually a bug in the texture shader. Fixing in an upcoming PR.

**Comment by unknownbrackets** [comment]
Closing since that's merged.  Wish GitHub would detect "Fixes ＃1 and ＃2."

-[Unknown]
