### ISSUE TITLE
Dissidia particle glitches

### ISSUE THREAD

**Issue by Sanaki** [hrydgard/ppsspp#15182]
### Game or games this happens in

ULES-01270 - Dissidia Final Fantasy

### What area of the game / PPSSPP

Two effects occur that I've verified, after having this issue reported to me. First is the EX force particles splitting into 3x3 or 4x4 grids and sometimes lingering onscreen past when they should. This can be observed in any battle at any time. The second is a rectangular effect coming from overlay graphics/text on the screen, especially spammy when facing away from your opponent for whatever reason (such as being locked on to an EX core). I have a screenshot exhibiting both issues here:
![Dissidia - Final Fantasy (Europe) (En,Fr,De,Es,It)-211128-155412](https://user-images.githubusercontent.com/1374333/143792928-43565636-ff6a-4839-8fa6-43aec7e944df.png)

This was originally tested in the libretro core, but I confirmed the same issue on standalone. The user reporting to me was on Windows. I am on Linux. They used D3D11, OpenGL, and Vulkan, I used Vulkan and OpenGL. All graphic-related libretro core options were checked (and reset individually) to check for any change in behavior, with a full frontend restart between each test for surety. None made any difference.

Video of the issue in question, submitted by the original reporter:
https://clips.twitch.tv/InnocentTastyDogBuddhaBar-422s0j3vxontHla7

As well as a presumably related issue in a cutscene:
https://clips.twitch.tv/RelievedDelightfulCheesecakeRuleFive-fhbbQbLZZOi-c_X_

To confirm, I've been using Quick Battle, Tidus vs Tidus in the stage Dream's End. Apparently the issue is more pronounced in Chaos Shrine, but I do not currently have access to that level.

### What should happen

The EX force effects should render as a single dot/orb, while the rectangular effects should not occur.

### Logs

[dissidialog.txt](https://github.com/hrydgard/ppsspp/files/7614756/dissidialog.txt)

### Platform

Linux / BSD

### Mobile phone model or graphics card

NVIDIA GeForce GTX 1060 6GB

### PPSSPP version affected

v1.12.3-340-g2a9300698

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
ge dump

**Comment by ArethaCairn** [comment]
I'm the original reporter, so I just wanted to clarify a few things.

The EX Force turning into the grid, I've noticed, literally only ever happens on Dreams End. If the poster found it happening on all the stages that's even more strange, because that effect only ever happened on that particular stage. What I also noticed however was that it was several particle effects that caused it. Going into EX Mode as Onion Knight, for example, causes a stream of red dot grids to constantly come off of my character, and when I witnessed an Emperor enemy go into EX Mode, the same happened, but golden colored. These were all in the Dreams End stage

The effect of the rectangular sprites appearing on the screen is the effects that seem to happen more often in some stages than other, but also always happen when Tidus is in play. If you observe them closely, they seem to be a particle effect, in this particular case, coming from Tidus's sword, the bubble. The reason why it happens in stages like Chaos Shrine is because they must use a similar method to render particles, that in turn is glitching out in the same way, the Chaos Shrine has a lot of floating rocks and debris in the background, and the broken image appearing during those fights aren't bubbles like in this clip, but, as you guessed it, a brown rock. I also noticed this happening a lot on the stage Lunar Subterrane, but I cant place exactly where that image particle effect is coming from. Maybe the stars in the background?

Finally I want to apologize for the "cutscene" clip that was linked being down. I have absolutely no control over Twitch. I assume because it had Final Fantasy music in it, that was somewhat clear to the ear, that they took it down for copyright reasons.

**Comment by jcchikikomori** [comment]
Also exists on my Android devices as well. Since v1.12.3+

- An Samsung device with Snapdragon chipset (Adreno GPU)
- An Huawei device with Kirin chipset (MALI GPU)

**Comment by unknownbrackets** [comment]
If this used to not happen, it'd be very helpful to try specific git builds to find the first version it started happening in, and the most recent version it didn't happen in.  Trying by halves is the mathematically fastest way:

https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

-[Unknown]

**Comment by jcchikikomori** [comment]
Looks like it's fixed since this commit https://github.com/hrydgard/ppsspp/commit/1f5680e6146d96413a87a4af1b27a4e9fac6e8ad

Version: v1.12.3-501-g1f5680e61

**Comment by jcchikikomori** [comment]
Looks like it's fixed since this commit https://github.com/hrydgard/ppsspp/commit/1f5680e6146d96413a87a4af1b27a4e9fac6e8ad

Version: v1.12.3-501-g1f5680e61
PR: #15253

**Comment by hrydgard** [comment]
That commit only touches the software renderer, so seems unlikely that it specifically would have fixed this when using hardware rendering?

**Comment by Sanaki** [comment]
I don't have time for a proper bisect right now, but I can at least verify that I failed to reproduce the issue on v1.12.3-501-g1f5680e61 (1f5680e61) standalone. I'll test the libretro core and do a proper bisect to identify what fixed it when I have a bit more time.

**Comment by jcchikikomori** [comment]
> I don't have time for a proper bisect right now, but I can at least verify that I failed to reproduce the issue on v1.12.3-501-g1f5680e61 ([1f5680e](https://github.com/hrydgard/ppsspp/commit/1f5680e6146d96413a87a4af1b27a4e9fac6e8ad)) standalone. I'll test the libretro core and do a proper bisect to identify what fixed it when I have a bit more time.

Same here. I'll compare the last two official releases then this one (`v1.12.3-501-g1f5680e61`), but i cannot tell the timelines though

**Comment by jcchikikomori** [comment]
> That commit only touches the software renderer, so seems unlikely that it specifically would have fixed this when using hardware rendering?

I might missed the commits since this issue started. I will compare last two official releases first.

**Comment by hrydgard** [comment]
OK. Well, I'll close, but do report here if you find what fixed it :)
