### ISSUE TITLE
Analog stick works only after triggering breakpoint

### ISSUE THREAD

**Issue by ThirteenAG** [hrydgard/ppsspp#15240]
### Game or games this happens in

ULUS-10213 - The Warriors

### What area of the game / PPSSPP

So, here's something weird, I apply [this piece of code](https://github.com/TheOfficialFloW/RemasteredControls/blob/master/Warriors/main.c#L38-L43) to the game, LB+LS combo stops working, but right stick isn't moving camera.
I open the debugger, set breakpoint at 0x0881D9B8 and then unset it and resume the game. Right stick now works.
Can anybody explain why that happens?

https://user-images.githubusercontent.com/4904157/146589029-754c5c73-8652-45d0-8751-eb01feae5647.mp4

### What should happen

I think right stick should work right away, without a debugger involved.

### Platform

Windows

### Mobile phone model or graphics card

1060

### PPSSPP version affected

v1.12.3-410-gb352f6107

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by LunaMoo** [comment]
My guess is debugger now doesnt invalidate jit until a breakpoint. Just create a CWCheat out of it and it'll work fine.

**Comment by hrydgard** [comment]
If PPSSPP emulated the instruction cache properly, the combination of 

```
sceKernelDcacheWritebackAll();
sceKernelIcacheClearAll();
```

should be enough. We are a little reluctant to actually blow out the JIT cache on sceKernelDcacheWritebackAll, since it becomes an extremely heavy-weight operation and is often used for stuff like texture uploads.

We do seem to support sceKernelIcacheClearAll although it seems to me that sceKernelIcacheInvalidateAll would be more appropriate, but there's a comment that I've forgotten I wrote, about how such a large range might not actually wipe it.

There are some possible workarounds, the easiest probably making sure to write to the first instruction of the basic block that the instructions you are patching are in, due to PPSSPP's first-instruction-overwrite trickery. Or maybe try the more focused sceKernelIcacheInvalidateRange on the specific range of affected memory?

Either way, this is kind of a bug I guess...

**Comment by ThirteenAG** [comment]
@hrydgard `sceKernelIcacheInvalidateRange` worked, thanks.

**Comment by hrydgard** [comment]
Alright. I'll close this, although we should maybe look into being smarter about invalidateall, somehow.

**Comment by Nugss** [comment]
Wow that code is great, can you teach me how to apply it on android??

**Comment by ThirteenAG** [comment]
> Wow that code is great, can you teach me how to apply it on android??

https://ci.appveyor.com/api/projects/ThirteenAG/widescreenfixespack/artifacts/TheWarriors.PPSSPP.FusionMod.zip

**Comment by Nugss** [comment]
It doesn't work properly, the left analog controls the camera instead of right analog, how to fix it??

**Comment by ThirteenAG** [comment]
> It doesn't work properly, the left analog controls the camera instead of right analog, how to fix it??

Probably something to do with your emulator settings.

**Comment by Nugss** [comment]
Uploading Record_2022-01-21-17-35-18.mp4…

Here's the sample

**Comment by Nugss** [comment]
https://drive.google.com/file/d/12G6A7IK4Xg1qbgaDpm2i7mog0mVKgDjK/view?usp=drivesdk

**Comment by Nugss** [comment]
Dude, can you create CWCheat out of it? I really love this game so much💖

Anyway, here's my small contribution😅

https://drive.google.com/file/d/12Tdsc7mNwUbuu8JO-F7BQoJ-DIipA_2p/view?usp=drivesdk

It's a few PS2 texture of that game. I reshade and retexture their (the warriors) outfit based on the movie

**Comment by ThirteenAG** [comment]
No, I don't know CWCheat and don't want to know CWCheat. Besides, I've been told that plugin works fine on mobile.

**Comment by Nugss** [comment]
Okay, but is it editable? So i can make it on my own? And what tool did you use??

Thank you in advance ☺️❤️
