### ISSUE TITLE
Blade Dancer - Lineage of Light (USA) has broken flickering graphics with Vulkan

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp#15254]
### Game or games this happens in

ULUS10124: Blade Dancer

### What area of the game / PPSSPP

The graphics on the ghost during the opening are broken and flickering with Vulkan.

Vulkan

![Capture](https://user-images.githubusercontent.com/94656803/147532197-10988ae7-efe9-4cfb-acbb-7e862fd7bb69.PNG)

OpenGL

![Capture2](https://user-images.githubusercontent.com/94656803/147532209-ce824e10-1251-4bae-b521-3199c2e334be.PNG)

### What should happen

It shouldn't be broken.

### Platform

Windows

### Mobile phone model or graphics card

Nvidia GTX 1080

### PPSSPP version affected

PPSSPP v.1.12.3-501-g1f5680e61

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [x] Try resetting settings or older versions and include if the issue is related.
- [x] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
If it's a regression, you may need to find out the last working dev build from https://buildbot.orphis.net/ppsspp/index.php?m=fulllist so that the devs can fix it sooner.

**Comment by iamthelaw2041** [comment]
I tried v1.10.3-1024-gf4b28119a- which is the oldest version in the list and it still happens. 

![Capture](https://user-images.githubusercontent.com/94656803/147533880-ce61afb6-8d5f-4a3e-8fa1-79dc4745cc9d.PNG)

**Comment by unknownbrackets** [comment]
This game is drawing the character twice - first RGB masked, then with actual colors and a depth >= test.

I guess it's because of the transparency - they can't rely on covering up the face, front of her arms and legs, etc. by drawing the backs since it's partially blended.  So the first pass establishes the minimum depth, and then the second path draws only the matching parts.

It seems like both rounds use the same depth values, bone matrices, etc... so not sure why they don't match.  This bug happens on Adreno and NVIDIA, but only in Vulkan and Direct3D 11.

Dump file:
[#15254_ULUS10124_bladedancer_vulkan_flicker.zip](https://github.com/hrydgard/ppsspp/files/7795625/15254_ULUS10124_bladedancer_vulkan_flicker.zip)

64/146 - face first time
104/146 - face second time

-[Unknown]

**Comment by hrydgard** [comment]
hm, we might need to use the invariant qualifier on gl_Position, for cases like this, to prevent the driver shader optimizer from shuffling calculations around. See https://www.khronos.org/opengl/wiki/Type_Qualifier_(GLSL)#Invariance_qualifiers

**Comment by unknownbrackets** [comment]
I tried adding `WRITE(p, "invariant precise gl_Position;\n");` to the vertex shader and it didn't do anything.

Pixel depth rounding works.  Simply writing depth in the frag shader doesn't.  And it got mad at me when I tried to make that invariant, but maybe I did something wrong...

-[Unknown]

**Comment by unknownbrackets** [comment]
PixelDepthRounding "fixes" this, but it otherwise still happens even with the `invariant` we have.

The most noticeable is 95/146 and 135/146, and it actually uses a `==` test there, most of them do - not `>=`.  Using `>=` makes it look better, but still doesn't work.

It almost feels like any game that uses `==` should just automatically use the reduced depth range (1/256th to more closely match 16-bit.)

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, that might be a usable heuristic...
