### ISSUE TITLE
Linux Build Instruction aren't clear.

### ISSUE THREAD

**Issue by SalimF** [hrydgard/ppsspp#15325]
### Platform

Linux / BSD

### Compiler and build tool versions

cmake version 3.22.1

### Operating system version

Arch Linux 2022.01.01

### Build commands used

I Tried multiple source to get latest build on my machine and I tried AUR Build and they all fails,
So I come here to try to build it from the source 
I follow Build instruction on the Wiki 
`git clone --recurse-submodules https://github.com/hrydgard/ppsspp.git`
But i notice the build requirement are (_huge_) specially some are required to build for other platform `MacOS` 
I didn't find any isntuction guided me to make the Build for X86_64 Linux ?

![image](https://user-images.githubusercontent.com/16048674/149817035-76758501-1692-4ff2-94b4-100816661198.png)

### What happens

`Cloning into '/home/pc3/ppsspp/SDL/macOS'...`

### PPSSPP version affected

v1.12.3-716-g4ea1c0855

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] Make sure to run `git submodule update --init --recursive` before building.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try deleting the build directory and running the build again.
- [ ] Check GitHub Actions, which builds every merge and PR.
- [ ] Include logs and help us reproduce.

**Comment by unknownbrackets** [comment]
That's how to build on Linux.  the instructions aren't wrong.

We spend most of our time making the emulator better - emulating more accurately, more efficiently, fixing game compatibility, or adding enhancement features.  We also want it to be easy to build PPSSPP - even if you're on macOS, Windows, Linux, or building for Android, iOS, Raspberry PI, etc.

It's true that a sacrifice has been made for those goals, making the download larger.  Yes, we could take the time we spend making PPSSPP perform faster and instead dedicate it to making the download slight smaller.  We could craft complex, multi-page instructions and brittle scripts that have to be modified every week to download just the right files for your individual platform.  But it's a lot of work, and distracts from the really important stuff I mentioned above.

I'm going to close this issue, because the instructions are not wrong.

If you want to download only the minimal amount of code yourself, check the GitHub actions file.  You may also want to download a subset of the FFmpeg repo, since many of the files are not used for builds (we only use some codecs.)  You could also skip that and use system FFmpeg, just beware that it will have lower game compatibility.  But if your goal is to download less, and you don't care about performance or compatibility as much - those are the tradeoffs you can make.

-[Unknown]

**Comment by unknownbrackets** [comment]
If you're actually getting some error message, feel free to reply with the actual error in a comment and we can reopen.

-[Unknown]
