### ISSUE TITLE
Homebrew Store doesn't handle spaces in filenames

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#15352]
Got a report of this, apparently this used to work but doesn't now, gonna look into it soon as all path bugs are suspicious and might have other consequences.

**Comment by unknownbrackets** [comment]
I took a quick look, and the path taken for a download doesn't even use Path currently, it uses Url.  I don't see anything obviously wrong about that.

I would assert that `download-url` and `icon-url` should be expected to be URLs, which would not include spaces in the first place.  It is invalid for a URL to contain a control character (i.e. ASCII/Unicode < 32) or space.  It's also invalid for it to contain a % without the hex digits specifying the byte.

It does look like a space directly used in either of those would fail, because the URL is invalid.  In theory, the space could be detected and replaced with %20, but this is really a hack around bad input.

There are other characters that are technically illegal here, though from a HTTP protocol parsing perspective space is the most illegal within a URL because it'll cause the request line to fail to parse.

There are also characters that are confusing if you try to treat user-entered data as text - for example `#`.  If you ask a webserver for `GET /image#1.jpg HTTP/1.1`, you're really up to its whim on whether you'll get a 404 because `/image` doesn't exist and `#` is typically used as a subresource selector - i.e. https://github.com/hrydgard/ppsspp#ppsspp---a-fast-and-portable-psp-emulator.  Though typically you wouldn't send the # part to the webserver itself anyway.

Most people keep this simple by avoiding spaces and other special characters (even encoded) in URLs from the beginning.

-[Unknown]

**Comment by hrydgard** [comment]
Right, it should only work if the space is %-encoded, and if it already does that, then this is indeed not an issue and should be closed. I filed this after getting pinged on discord and then just forgot about it, heh.
