### ISSUE TITLE
Chinese characters missing in system UI

### ISSUE THREAD

**Issue by y2-Whyto** [hrydgard/ppsspp#15439]
### Game or games this happens in

None.

### What area of the game / PPSSPP

Open the PPSSPPSDL for macOS (v1.12.3), Settings -> System -> UI -> Language, and choose '简体中文' (Chinese Simplified, the second to last), and there will be some question marks (?) on the UI, which just looks like this:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/42339192/158050319-4300745f-f9b2-4c45-9a23-fcfb2fec790d.png">

and this:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/42339192/158050354-4d47c1c9-bf77-460a-977e-8b3cef4f6174.png">

I checked `PPSSPPSDL.app/Contents/MacOS/Assets/lang/zh-CN.ini` and the translated texts are just fine, so I think this maybe some issue with the font setting of this app? Yet I haven't found any solution for it.

What's more is this issue also happens to Chinese Traditional -- also '?' marks on the UI, but does not happen to Korean or Japanese (at least there's no '?' marks and characters are normally shown).

### What should happen

There shouldn't be '?' mark in the text area of the UI after switching to Chinese, which indicates character missing issue.

### Platform

macOS

### Mobile phone model or graphics card

Intel Iris Plus Graphics 1536 MB

### PPSSPP version affected

v1.12.3

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by Panderner** [comment]
This might be related to https://github.com/hrydgard/ppsspp/issues/9958

**Comment by y2-Whyto** [comment]
> This might be related to #9958

Oh, I just checked this issue. So is there any solution yet? Or is this font rendering enhancement already in consideration?

**Comment by Adilabdh** [comment]
.Sent via the Samsung Galaxy S®6 active, an AT&T 4G LTE smartphone
-------- الرسالة الأصلية --------من: y2-Whyto ***@***.***> التاريخ: ١٣‏/٣‏/٢٠٢٢  ١٠:٥٧ ص  (GMT+03:00) إلى: hrydgard/ppsspp ***@***.***> نسخة: Subscribed ***@***.***> الموضوع: [hrydgard/ppsspp] Chinese Simplified character missing in system UI
  (Issue #15439) 

Game or games this happens in

None.

What area of the game / PPSSPP

Open the PPSSPPDL for macOS (v1.12.3), Settings -> System -> UI -> Language, and choose '简体中文' (Chinese Simplified, the second to last), and there will be some question marks (?) on the UI, which just look like this:



and this:



I checked PPSSPPDL.app/Contents/MacOS/Assets/lang/zh-CN.ini and the translated texts are just fine, so I think this maybe some issue with the font setting of this app? Yet I haven't found any solution for it.

What's more is this issue also happens to Chinese Traditional -- also '?' marks in the UI, but does not happen to Korean or Japanese (at least there's no '?' marks and characters are normally shown).

What should happen

There shouldn't be '?' mark in the text area of the UI after switching to Chinese, which indicates character missing issue.

Logs

No response

Platform

macOS

Mobile phone model or graphics card

Intel Iris Plus Graphics 1536 MB

PPSSPP version affected

v1.12.3

Last working version

No response

Graphics backend (3D API)

OpenGL / GLES

Checklist



 Test in the latest git build in case it's already fixed.

 Search for other reports of the same issue.

 Try resetting settings or older versions and include if the issue is related.

 Try without any cheats and without loading any save states.

 Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
A possible workaround is to use WINE or Proton to run the Windows version of PPSSPP.  While not ideal, those should simulate the APIs we use on Windows to implement native font rendering and render these characters.

It's also possible to generate new font atlas files with the extra characters, but this is a bit complex.  We can resolve this for now in the next stable release, but it's hard to always keep up with the translations as far as characters.

Indeed, this is essentially a duplicate of #9958.

-[Unknown]

**Comment by y2-Whyto** [comment]
> A possible workaround is to use WINE or Proton to run the Windows version of PPSSPP. While not ideal, those should simulate the APIs we use on Windows to implement native font rendering and render these characters.
> 
> It might also be viable to use PPSSPPQt.
> 
> It's also possible to generate new font atlas files with the extra characters, but this is a bit complex. We can resolve this for now in the next stable release, but it's hard to always keep up with the translations as far as characters.
> 
> Indeed, this is essentially a duplicate of #9958.
> 
> -[Unknown]

OK, I got it. I'm now compiling PPSSPPQt, and I'm really sorry for the duplication. 🙏🙏
