### ISSUE TITLE
Can't mapping keys on Ppsspp

### ISSUE THREAD

**Issue by ak420314** [hrydgard/ppsspp#15527]
### What should happen

Hey i have a controller 2 months ago i can perfectly mapping keys with my controller on Ppsspp but now it is impossible

### Who would this benefit

I think developer should view my point

### Platform (if relevant)

Android

### Games this would be useful in

Mapping

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by Saramagrean** [comment]
Android 11?

**Comment by unknownbrackets** [comment]
Most often this is caused by an OS bug.  See here:

https://www.reddit.com/r/AndroidGaming/comments/kb8mzw/accessibility_services_block_controllers_android/

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
