### ISSUE TITLE
Still Graphics Glitchess and Flip Screen on  skip Buffer Effects mode.

### ISSUE THREAD

**Issue by palazos** [hrydgard/ppsspp#15568]
### Game or games this happens in

Wipeout Pulse, Need For Speed:Pro Street, etc

### What area of the game

All the game.

### What happens

When you skip buffer effects on any of these games, all the screen flips from the right to the left and looks really bad.
Some items on the GUI of the game glitch  and the positions changes all around the screen.
Have some information from other users about these glitches happens in other games too.

### What should happen

Like in older versions of PPssPP this glitch never existed its happening from around the version 1.10 dont know if it was already reported.

### GE frame capture

![UCES00465_00002](https://user-images.githubusercontent.com/90732131/171678502-6daa2caf-b502-4108-a974-f1d143812873.jpg)
![UCES00465_00001](https://user-images.githubusercontent.com/90732131/171678514-2dcddf0d-4f7d-4c0e-a1b0-ff270f75bbcd.jpg)

### Platform

Linux / BSD

### Mobile phone model or graphics card

RK3326 Mali-G31 GPU

### PPSSPP version affected

v1.12.13-1215

### Last working version

v1.9

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
Skip buffer effects is a hack so expect graphics glitches.

**Comment by palazos** [comment]
> Skip buffer effects is a hack so expect graphics glitches.

We all know, but the glitches didn't happened before.

**Comment by unknownbrackets** [comment]
#15570 helps Wipeout for me, but I was getting different issues.  Does that help?

I do want to note that sometimes things being drawn incorrectly looks "nicer", especially when you're skipping some effects.  Just because it once looked fine doesn't mean skip buffer effects will always look the same - it's a hack and when we fix something related to stencil handling, it may fix rendering to be more accurate but make skip buffer effects look worse.  It's an inherent limitation of the speedhack.

That said, the flipped rendering was simply a bug as corrected in that pull request.  I just don't want you to think every (even newly experienced) issue with skip buffer effects is a bug.

That doesn't mean I won't look if you're seeing other new issues, or if that pull only fixes some.

-[Unknown]

**Comment by palazos** [comment]
> #15570 helps Wipeout for me, but I was getting different issues. Does that help?
> 
> I do want to note that sometimes things being drawn incorrectly looks "nicer", especially when you're skipping some effects. Just because it once looked fine doesn't mean skip buffer effects will always look the same - it's a hack and when we fix something related to stencil handling, it may fix rendering to be more accurate but make skip buffer effects look worse. It's an inherent limitation of the speedhack.
> 
> That said, the flipped rendering was simply a bug as corrected in that pull request. I just don't want you to think every (even newly experienced) issue with skip buffer effects is a bug.
> 
> That doesn't mean I won't look if you're seeing other new issues, or if that pull only fixes some.
> 
> -[Unknown]

Nice catch man, this fix will really help all us who have china consoles and cannot play some games with buffered render.
Im go to try ask to amberElec team to know if we can test it on the prebuild
