### ISSUE TITLE
zettai zetsumei toshi 3 multiplayer

### ISSUE THREAD

**Issue by IrfanH495** [hrydgard/ppsspp#15596]
### Game or games this happens in

ULJS-00191

### What area of the game

Vulkan/opengl
Multiplayer is too slow sometimes picking up items will freeze the game 10/15+ seconds
![Screenshot_20220613-215558](https://user-images.githubusercontent.com/78854859/173386534-6f25ab88-a1f4-4bee-b926-93553cb11d3c.png)
![Screenshot_20220613-220629](https://user-images.githubusercontent.com/78854859/173386657-bbd70a2a-e7ab-4210-8ac4-c04dc5ecbf49.png)
![Screenshot_20220613-220757](https://user-images.githubusercontent.com/78854859/173389302-c17f4437-8075-4367-bf48-153a7b531fa1.png)

### Speed seen in PPSSPP

30/60

### Platform

Android

### Mobile phone model or graphics card

Samsung A03,sharp sh04h,vivo Y91

### PPSSPP version affected

v1.12.3-1272-gef0a0c1a3

### Last working version

v1.12.3-1272-gef0a0c1a3

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the slowdown.
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Hm, no longer happening?

**Comment by IrfanH495** [comment]
> Hm, no longer happening?

it still happens if i take an item or use an extinguisher, the fire won't go out wait a few minutes/second sometimes can't use the item can't re-select but the game doesn't freeze

**Comment by IrfanH495** [comment]
this is my save data
https://drive.google.com/file/d/179XZ7ACkR_DIXIjwhKLc7SEA8bmnNVh1/view?usp=drivesdk

**Comment by IrfanH495** [comment]
this is screen recording
https://drive.google.com/file/d/17bNVYpYvlhUtIny2fCX0v4nsTySLE0df/view?usp=drivesdk

**Comment by ANR2ME** [comment]
does the game worked fine on the v1.12.3 release version at play store?

**Comment by ANR2ME** [comment]
I tried using your save data, but after loading the save data, it asked me to select the character, but pressing O or X, nor arrows keys didn't show any kind of reaction, it felts like the input got ignored... or did i missed anything?
![image](https://user-images.githubusercontent.com/7974720/173753611-0e37a743-c5d9-4e2a-a7e1-7f0406fa002f.png)

**Comment by IrfanH495** [comment]
> I tried using your save data, but after loading the save data from the main menu, it asked me to select the character, but pressing O or X, nor arrows keys didn't show any kind of reaction, it felts like the input got ignored... or did i missed anything? ![image](https://user-images.githubusercontent.com/7974720/173753611-0e37a743-c5d9-4e2a-a7e1-7f0406fa002f.png)

use cheats, but the issue I'm having is in multiplayer
_C1 Freeze Workaround
_L 0xE0010004 0x00237218
_L 0x20237218 0x00000000
_C0 Freeze Workaround [Disable]
_L 0xE0010000 0x00237218
_L 0x20237218 0x50400004

**Comment by IrfanH495** [comment]
> does the game worked fine on the v1.12.3 release version at play store?
> 
> hmm.. based on the low FPS/performance, i'll need to check whether this game is one of those games where performance affected by the latency, or whether this game have the same "delayed" issue like Hokuto no Ken (due to `FIONREAD` not returning an accurate value on Linux)

the game works fine on the ppsspp play store, but if I play Multiplayer there is a delay when picking up or giving items, if I use extinguish the fire, the fire won't go out, wait 15 seconds or longer.

**Comment by ANR2ME** [comment]
Could you guide me which menu/selection should i choose to go to multiplayer mode after selecting the character?

**Comment by IrfanH495** [comment]
save data
load on save 1
https://drive.google.com/file/d/17qdAW0RWgjnVOlREmOzncUb9mIiuS9FM/view?usp=drivesdk
![Screenshot_20220615-132205](https://user-images.githubusercontent.com/78854859/173756976-ae82132d-28d0-4c22-b462-0b069f4469ba.png)
![Screenshot_20220615-132553](https://user-images.githubusercontent.com/78854859/173757329-e8460fa1-74fe-4b1f-a112-b5f426b8e06c.png)
![Screenshot_20220615-131329](https://user-images.githubusercontent.com/78854859/173757002-72ad6649-6de8-4d34-9d58-e8f9875bd4ab.png)
try quest 8

**Comment by ANR2ME** [comment]
I don't know how to get to the tunnel as in your video (which only shows walking around instead of picking items), so i can only picked items near the start of the game.

I've tested this game with simulated 500ms latency on localhost but didn't find any issue when walking around, but both instance were running full speed (30/30 FPS).
On the Host picking item took about 2 seconds from the moment i pressed the button to the appearance of the item window/dialog.
On the Joining one it took about 4 seconds.
However, i do notice a slight flickering when entering the 3D world for the first time sometimes, also saw a few GE warnings
```
33:21:794 Application  W[SCEGE]: HLE\sceGe.cpp:417 sceGeBreak(mode=0, unknown=08cb68e8): unknown ptr (valid)
33:21:794 Application  W[SCEGE]: HLE\sceGe.cpp:417 sceGeBreak(mode=0, unknown=08cb68e8): unknown ptr (valid)
33:21:795 Application  W[SCEGE]: HLE\sceGe.cpp:417 sceGeBreak(mode=0, unknown=08cb68e8): unknown ptr (valid)
```

I also tested simulated 500ms latency on LAN (Windows vs Android), on Windows i'm getting full speed 30/30 FPS, while on Android i only gets 12/29 FPS (41%), and have the same result with multiple instance on localhost.

Your internet connection might be worse than my simulated one if you're getting delays more than 10 seconds.

If you are using 60 FPS cheat, please disable it, try to use as minimum cheats as possible (ie. only use cheat to fix the input issue) when testing, since some games try to sync multiplayer data on every frame, making the FPS can potentially cause the game to send data faster (more than it should), thus can flood the socket buffer faster and resulting to delays.

Also, it would be nice if you can make a video how to get to the tunnel where you can get frozen just by walking around, in case there are a lot of GE warnings flooding in that causes the game unable to render properly and make the screen looked frozen (the FPS seems to be moving even when the screen looked frozen based on your video)

PS: it would be nice if PPSSPP can have the input issue fixed, so we don't need to use cheat at all when testing.

**Comment by IrfanH495** [comment]
> I don't know how to get to the tunnel as in your video (which only shows walking around instead of picking items), so i can only picked items near the start of the game.
> 
> I've tested this game with simulated 500ms latency on localhost but didn't find any issue when walking around, but both instance were running full speed (30/30 FPS) unlike in your video. On the Host, picking item took about 2 seconds from the moment i pressed the button to the appearance of the item's window/dialog. On the Joining one it took about 4 seconds. However, i do notice a slight flickering when entering the 3D world for the first time sometimes, also saw a few GE warnings
> 
> ```
> 33:21:794 Application  W[SCEGE]: HLE\sceGe.cpp:417 sceGeBreak(mode=0, unknown=08cb68e8): unknown ptr (valid)
> 33:21:794 Application  W[SCEGE]: HLE\sceGe.cpp:417 sceGeBreak(mode=0, unknown=08cb68e8): unknown ptr (valid)
> 33:21:795 Application  W[SCEGE]: HLE\sceGe.cpp:417 sceGeBreak(mode=0, unknown=08cb68e8): unknown ptr (valid)
> ```
> 
> I also tested simulated 500ms latency on LAN (Windows vs Android), on Windows i'm getting full speed 30/30 FPS, while on Android i only gets 12/29 FPS (41%), and have the same result with multiple instance on localhost.
> 
> Your (or the other player's) internet connection might be worse than my simulated one if you're getting delays more than 10 seconds, might be a combination of high latency and high packet loss rate.
> 
> If you are using 60 FPS cheat, please disable it, try to use as minimum cheats as possible (ie. only use cheat to fix the input issue) when testing, since some games try to sync multiplayer data on every frame, making the FPS higher can potentially cause the game to send data faster (more than it should), thus can flood the socket buffer faster and resulting to delays. And try to use the default setting as much as possible (ie. without enabling speedup settings on Graphics) when testing.
> 
> Also, it would be nice if you can make a video how to get to the tunnel where you can get frozen just by walking around, in case there are a lot of GE warnings flooding in that causing the game unable to render properly and make the screen looked frozen (the FPS seems to be moving even when the screen looked frozen based on your video)
> 
> PS: it would be nice if PPSSPP can have the input issue fixed, so we don't need to use cheat at all when testing.

I'm sorry, if this is not an issue you can close it
🙏🙏🙏🙏🙏🙏🙏

**Comment by ANR2ME** [comment]
The freezing issue you're getting while walking around might be a different issue, because walking around doesn't seems to be affected by the latency nor packet loss (at least from the moving player's perspective).
it would be nice if we can reproduce that freezing issue, so can you guide me how to get to the tunnel on your video?

**Comment by IrfanH495** [comment]
> The freezing issue you're getting while walking around might be a different issue, because walking/running around doesn't seems to be affected by the latency nor packet loss (at least from the moving player's perspective). it would be nice if we can reproduce that freezing issue, so can you guide me how to get to the tunnel shown in your video?

if use the save data above, he is in quest 4,5 & 6

**Comment by IrfanH495** [comment]
@ANR2ME you can close it.  I have completed 52 quests without any problems.  the problem that occurs may be because my device is very weak.  if I play with Sharp sh04h & samsung A03 only a short delay in getting.  if I play with Sharp Sh04H & vivo y91 then the delay is quite long
