### ISSUE TITLE
working emulator

### ISSUE THREAD

**Issue by Neeekoo-Chan** [hrydgard/ppsspp#15598]
### What should happen

Make ppsspp much more reliable such a working emulator like gbc,gba,snes,nes,mame emulation homebrew

### Who would this benefit

With this there is no need to download other app to play your favorite retro games and make it much better playing using your app i know that this is a lot of work but i hope for the next update that its working 

### Platform (if relevant)

Android

### Games this would be useful in

Retro games

### Other emulators or software with a similar feature

Original psp hardware

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by unknownbrackets** [comment]
Yes, it's a shame that PPSSPP is terrible and doesn't work.  As an open source project, remember that it gets better the more people contribute, so instead of complaining about it maybe search yourself and muster up the courage to work hard and contribute.  That way you might achieve great things for PSP emulation one day and benefit many others.

Closing this as not useful and unspecific.

-[Unknown]
