### ISSUE TITLE
texture applied to sprite incorrectly

### ISSUE THREAD

**Issue by mohasi** [hrydgard/ppsspp#15607]
### Game or games this happens in

Homebrew

### What area of the game / PPSSPP

I am learning basic PSP development and using PSPSDK to create a simple `Gu` example of drawing a sprite and applying a texture over it. I have a 2x2 texture as array as follows:

```
u16 __attribute__((aligned(16))) logo[2][8] = {
    {0xe05f, 0xf0f0},
    {0xffb0, 0xe0bf},
};
```

I draw it like this:
```
void gfxDrawSprite(s16 x, s16 y, u16 z, u16 width, u16 height) {
  TexturedVertex vertices[2] = {
      {0, 0, x, y, z},
      {2, 2, x + width, y + height, z}};

  sceGuTexMode(GU_PSM_4444, 0, 0, GU_FALSE);
  sceGuTexFunc(GU_TFX_REPLACE, GU_TCC_RGBA);
  sceGuTexImage(0, 2, 2, 8, logo);
  sceGuDrawArray(GU_SPRITES, GU_TEXTURE_16BIT | GU_VERTEX_16BIT | GU_TRANSFORM_2D, 2, NULL, vertices);
}
```

What I am finding is it looks good on PPSSPP:
![image](https://user-images.githubusercontent.com/47725053/174403481-e638c633-01a7-4e4a-a813-0c3264c7ac13.png)

But on real PSP 3000 it first looked like this:
![image](https://user-images.githubusercontent.com/47725053/174403538-e725ed07-939b-45f3-a3da-3eaa57aa53a0.png)

Then after I put in a clear command:
```
int main() {
  setupExitCallback();
  gfxInit();

  while (isRunning()) {
    gfxStart();
    gfxClear(); // this
    gfxDrawSprite(50, 100, 0, 64, 64);
    gfxFinish();
    sceDisplayWaitVblankStart();
  }

  gfxExit();
  sceKernelExitGame();
  return 0;
}
```

Which is:
```
void gfxClear() {
  sceGuClearColor(0);
  sceGuClearDepth(0);
  sceGuClear(GU_COLOR_BUFFER_BIT | GU_DEPTH_BUFFER_BIT);
}
```

Then I got:
![image](https://user-images.githubusercontent.com/47725053/174403701-3177e084-c726-4448-a849-7e62f487677a.png)

Which is progress, but the texture is rotated left by 90 degrees.

I had another similar issue before where using `GU_LINES` it was putting an empty pixel on top left of rectangle:
![image](https://user-images.githubusercontent.com/47725053/174403996-cb80d7f8-a985-47a2-9ebf-aea98d3335c1.png)

That would have been fine if it was the same as a real PSP, however a real PSP using the same code was putting the empty pixel on bottom right:
![image](https://user-images.githubusercontent.com/47725053/174404074-571884bd-c443-4222-b8a9-4eedcf109b4a.png)

### What should happen

- PPSSPP should be like a real PSP and not render properly without the clear
- PPSSPP should render the texture with the same rotation as a real PSP.

### Platform

Windows

### Mobile phone model or graphics card

Nvidia 1660Ti

### PPSSPP version affected

1.12.3

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by mohasi** [comment]
This is the EBOOT for the issue, it will look different between PPSSPP and a real PSP:
[EBOOT.zip](https://github.com/hrydgard/ppsspp/files/8931459/EBOOT.zip)

**Comment by ANR2ME** [comment]
Software rendered should have a higher compatibility with real PSP, you should also compare it with Software renderer in case it's also showing something different than a real PSP.

**Comment by unknownbrackets** [comment]
The line drawing is probably a bug, and the line drawing in hardware mode is really not very accurate.  It's better when using software rendering.

I tried this quickly, and I do see a different result on a PSP than in PPSSPP.  But, if I record the display list commands PPSSPP is being given and run exactly those on a PSP (with matching vertex data, texture data, etc.), then I get the same result as PPSSPP.

This makes me think you are not flushing dcache correctly.  See #7340.  PPSSPP doesn't really emulate the dcache accurately, and it may be impossible to do it without a major impact to performance.  If you're interested in working on it (it's complicated, though), I think it would be a good option to have.  That said, be prepared for potentially creating something that can't run at full speed in at least heavy games even on a powerful desktop.

Anyway, I might look more if you could provide the full code.  But I'd suggest you try inserting `sceKernelDcacheWritebackInvalidateAll()` in a bunch of places (mainly AFTER writing vertex data.)  `sceKernelDcacheWritebackInvalidateRange()` is better and will have a smaller speed hit.

On the PSP, the CPU has a local cache where memory writes and reads are kept.  Data actually goes to real memory in a few cases:
 * A pointer with uncached decoration is used.
 * Cache is full and a new cache line is required for data not currently in the cache.
 * A writeback request is generated.

The GPU does not use the CPU's local cache, so it won't see the data you've written.  Generally, I think the helper functions you're using (sceGu*) will writeback the displaylist data, but I don't think they'll do anything about the vertex data (or texture data, but it looks like yours is static from your code snippet.)

Note that an interrupt running at just the right time could cause a cache line to be flushed if the interrupt handler reads/writes enough data, so behavior can be a bit unpredictable even on a PSP when not flushing the cache explicitly.

In PPSSPP, all memory access operates as if it were uncached, so the GPU immediately sees writes from the CPU for things like vertex data.  However, PPSSPP does have some caches and listens for dcache invalidation to purge them, i.e. with texture data.

-[Unknown]

**Comment by mohasi** [comment]
Thanks both @ANR2ME and @unknownbrackets for the replies. I tried the software renderer and got the same result. I am attaching a copy of the requested code.

I am not very experienced in PSP development so I am assuming this issue even though it may be a bug in PPSSPP may be mitigated by me by some means. I am hoping it can as the emulator is a very useful tool in the learning experience.

I have seen something like ` sceKernelDcacheWritebackInvalidateAll()` used before, but in only in framebuffer graphics, pretty much all of the random samples of `Gu` code I come across online do not make use of it. In any case, I was not sure exactly where to place it, but I placed it here and it made no difference: 

![image](https://user-images.githubusercontent.com/47725053/174435913-6e168819-6456-4ace-9793-5fd274cf301e.png)

Willing to try any other experiments to figure out how this can be mitigated.

[code.zip](https://github.com/hrydgard/ppsspp/files/8933450/code.zip)

**Comment by unknownbrackets** [comment]
Ultimately it needs to be before the command is executed on the GE, so that ought to be okay, although I would put it right after setting the vertices.

This particular code snippet isn't really okay, though.  It's good to understand what's actually happening under the hood with these sceGu functions.

The PSP's GE (GPU) basically runs a series of commands.  Most commands set a register (examples: blend colors, texture mode, texture address, vertex flags, etc.) and some other commands perform an action (such as jumping to another command, drawing one or more triangles/lines/rectangles, etc.)

Functions like `sceGuTexMode()` are, behind the scenes, just constructing this list of commands in memory.  See here:
https://github.com/pspdev/pspsdk/blob/master/src/gu/sceGuTexMode.c
https://github.com/pspdev/pspsdk/blob/master/src/gu/sendCommand.c#L16

As you can see, it's just writing bytes to memory in the end.  Later, `sceGuFinish()` will actually run the commands:
https://github.com/pspdev/pspsdk/blob/master/src/gu/sceGuFinish.c#L19
https://github.com/pspdev/pspsdk/blob/master/src/gu/sendCommand.c#L35-L36

The reason this is important is that the values you set as vertex data, texture data, etc. must all be available until the GE actually runs those commands.  Technically, even when you update the stall address (which means, tell the GE to run commands until a certain address, and then stop or "stall" waiting for you to tell it to continue), it runs asynchronously.  So you have to wait until it's done too with `sceGuSync()`:
https://github.com/pspdev/pspsdk/blob/master/src/gu/sceGuSync.c#L14

In summary, until you finish and sync the commands, all vertex, texture, clut, etc. data must remain valid.

In your code snippet, `vertices[2]` is on the stack inside `gfxDrawSprite()`.  Once that function returns, the stack could be overwritten with other data by anything, maybe even an interrupt handler or a syscall.  You would need to either allocate that (which is why that get memory func exists), or sync right away.  If you called this multiple times, presumably the same bytes in memory would be used for each `vertices[2]` and they'd get overwritten.

---

As for rotation, the GE intentionally rotates rectangles when you specify the corners in certain ways.  If both the XYZ and UV are top left to bottom right (as in your case), it's not supposed to rotate the texture.  So I think somehow the texture positions or texcoords are getting to the GE as different values than you intend.

We actually have a test for rotation behavior:
https://github.com/hrydgard/pspautotests/blob/master/tests/gpu/textures/rotate.cpp

-[Unknown]

-[Unknown]

**Comment by mohasi** [comment]
The quality of my code, while not perfect may be irrelevant to this ticket. I opened this issue as a bug, posted screenshots and attached code which when run display different results on a real PSP. Even when switched to software rendering this occurred. I am hoping the emulator could be changed to display the same result as hardware as this helps tremendously while developing.

However, theory aside, if a specific line or block of code in my attached files could be identified as causing the inaccuracy of the emulator to show itself please let me know, I'll utilize that while I wait for a fix.

Thank you.

**Comment by unknownbrackets** [comment]
Well, you said you're learning here.  I'm just telling you about a bug in your code.  I don't even think that's the cause of what's happening here, it's more likely cache related as I explained before.  Whatever emulator or device you use to test your code, you want to avoid stack corruption.

-[Unknown]

**Comment by mohasi** [comment]
I improved my code by allocating memory on the GPU for the texture before rendering, which avoids the stack corruption @unknownbrackets was mentioning (thank you for that). Now magically it looks the same on HW as on PPSSPP. I am not sure if this sheds and light on the emulation inaccuracy I faced earlier. I am attaching my new code.

[code.zip](https://github.com/hrydgard/ppsspp/files/8935764/code.zip)

**Comment by hrydgard** [comment]
PPSSPP's main goal is to run correct PSP game code correctly. Yes it would be nice if buggy game code broke the same way as on the real hardware, but the cache hierarchy is the one thing that's just too expensive to be worth bothering with emulating accurately, and that's what you happened to hit in this case (very common mistake when programming the PSP, as it has a low-level approach to memory management which people coming from PC programming are not used to, and I guess the homebrew documentation still is lacking...).

**Comment by mohasi** [comment]
Not sure if you could call my code buggy, it was just using RAM to store texture data instead of VRAM.

I do get though that it is possibility related to caching and how it would be extremely hard to emulate the PSP to this level to the point that it would be easier to ignore these inaccuracies altogether.

What is still not explained is how without any textures involved, simple line drawing had a mixing pixel on the opposite side.

**Comment by unknownbrackets** [comment]
Okay, brief explanation.

When you call functions, they use a portion of RAM called stack.  Imagine a bunch of small cubby holes positioned above a table.  It looks like this (it's much bigger but let's just look at a slice of it):

```
[                    ] Stack slot 0 - available to put something in / next available slot
[                    ] Stack slot 1 - available to put something in
[                    ] Stack slot 2 - available to put something in
[                    ] Stack slot 3 - available to put something in
[                    ] Stack slot 4 - available to put something in
[                    ] Stack slot 5 - available to put something in
[                    ] Stack slot 6 - available to put something in
[                    ] Stack slot 7 - available to put something in
```

When you call a function, it uses some of the stack space to remember where the function call started, so it can go back there once it's done.  So, inside `gfxDrawSprite()` it looks like this:

```
[return address      ] Stack slot 0 - where to go back to after `gfxDrawSprite()` is done
[                    ] Stack slot 1 - available to put something in / next available slot
[                    ] Stack slot 2 - available to put something in
[                    ] Stack slot 3 - available to put something in
[                    ] Stack slot 4 - available to put something in
[                    ] Stack slot 5 - available to put something in
[                    ] Stack slot 6 - available to put something in
[                    ] Stack slot 7 - available to put something in
```

Next, when you define a local variable (I'm keeping this simple) it typically uses the stack for that too.  Oversimplifying a bit:

```
[return address      ] Stack slot 0 - where to go back to after `gfxDrawSprite()` is done
[vertices[0]         ] Stack slot 1 - local variable
[vertices[1]         ] Stack slot 2 - local variable
[                    ] Stack slot 3 - available to put something in / next available slot
[                    ] Stack slot 4 - available to put something in
[                    ] Stack slot 5 - available to put something in
[                    ] Stack slot 6 - available to put something in
[                    ] Stack slot 7 - available to put something in
```

Then you tell `sceGuDrawArray()` to draw what's in "stack slot 1".  So far, everything seems sensible, right?  But it has not drawn it yet - you've just told it where in memory to find the vertices.  It'll draw later.

Once the function returns, the stack goes back to where it was before the function was called.  Now it looks like this:

```
[return address      ] Stack slot 0 - available to put something in / next available slot
[vertices[0]         ] Stack slot 1 - available to put something in (also where the draw is pointed to)
[vertices[1]         ] Stack slot 2 - available to put something in
[                    ] Stack slot 3 - available to put something in
[                    ] Stack slot 4 - available to put something in
[                    ] Stack slot 5 - available to put something in
[                    ] Stack slot 6 - available to put something in
[                    ] Stack slot 7 - available to put something in
```

Technically, the return address and local variables are still there... but as far as code is concerned, those slots are free to put anything into and overwrite.  We still haven't drawn anything, but when it does draw, it'll use the vertex data in stack slot 1.

Okay, so now we call another function, and this function has its own local variable.  Let's call the function `sceGuFinish()` and that variable `stallAddress`.  So now it looks like this:

```
[return address      ] Stack slot 0 - where to go back to after `sceGuFinish()` is done
[stallAddress        ] Stack slot 1 - local variable (also where the draw is pointed to)
[vertices[1]         ] Stack slot 2 - available to put something in / next available slot
[                    ] Stack slot 3 - available to put something in
[                    ] Stack slot 4 - available to put something in
[                    ] Stack slot 5 - available to put something in
[                    ] Stack slot 6 - available to put something in
[                    ] Stack slot 7 - available to put something in
```

Have you noticed anything bad about this yet?  Because you let other code overwrite the memory you put the vertices in, some of your vertex data has been replaced by a completely unrelated local variable.  The vertex data is now corrupt.

In PPSSPP, some syscalls (system functions) don't "use" local variables, because they are emulated and we're not ripping off Sony's firmware code and violating their copyrights.  So our local variables are different than a real PSP's local variables, since our code is different from theirs.  Because of this, the corruption of the vertex data on the stack may be different.

This is a common programming error someone who doesn't understand memory and stack might make.  Once a variable goes out of "scope" (i.e. the `vertices` variable is only inside the `gfxDrawSprite()` scope), it is no longer kept valid by the compiler.  The `sceGuDrawArray()` function doesn't make a copy of the vertex data (last parameter) but rather takes a pointer.  It trusts you to keep the pointer you gave it alive until drawing happens.

It doesn't have to be VRAM or anything else.  It just has to be memory that isn't gonna be overwritten later.

-[Unknown]

**Comment by mohasi** [comment]
Thanks @unknownbrackets  you are right that the `gfxDrawSprite` was storing the local vertices on the stack, honestly after staring at it for ages I got used to it and did not notice it, for all my other methods I use `sceGuGetMemory` and use the pointer to store the vertex data.

PS. I am sure you are trying to be helpful writing these long replies but I personally find them very condescending. I actually very well know what a stack is, as I have programmed in assembly and written a couple of emulators myself (6502 and Chip-8), one of which is here on github. Also comments like, "coming from PC" and "not used to dealing with low level" are really not helpful.

I thank you guys for the invaluable tool, and I opened this issue with the intention to help improve the emulator, but have now realised nothing will be done about the issues, and instead fingers are being pointed at me, and am being tutored on how to program. I do not want to keep coming back here for the next tutorial instalments, so Ill be closing this ticket.
