### ISSUE TITLE
Static Guest Virtual Memory 

### ISSUE THREAD

**Issue by illusion0001** [hrydgard/ppsspp#15601]
### What should happen

Not sure if it's been opened before but guest memory isn't static last time I checked, there is memory editor in the emulator itself but for those who prefer external software like cheat engine will have to find base addr manually.

### Who would this benefit

Game patching users 

### Games this would be useful in

-

### Other emulators or software with a similar feature

Vita3k implemented this a few weeks back. https://github.com/Vita3K/Vita3K/pull/1802

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by ANR2ME** [comment]
It's not guaranteed to be static, just giving a hint for preferred address when possible
```
// preferred_address is only a hint for mmap, if it can't use it, the kernel will choose itself the address
```

But yeah, i wished there is an easier way to calculate the base address when using cheat engine to create cheats (ie. a base address that can be calculated with naked eyes without the need of calculator), as PPSSPP built-in memory viewer/editor is lack of advanced search engine like what CE have.

**Comment by LunaMoo** [comment]
>  i wished there is an easier way to calculate the base address when using cheat engine to create cheats

I made a cheat table that skips all manual calculating more than 6 years ago ~ [here](http://forums.ppsspp.org/showthread.php?tid=3590&pid=117172#pid117172), partially because I was sick writing long guides how to check PPSSPP log when the address is logged on first game's boot and explain how to deal with the issues CE has when attached to PPSSPP, partially because I was also lazy to do more than a few clicks to find something before going to disassembly with it to create a proper cheat.

 That cheat table can:
 - workaround windows debugger bug which causes CE unable to freeze values in PPSSPP(important to do it as first step),
 - attach to PPSSPP process via script,
 - find base address for you,
 - limit search range to user memory,
 - print out simple write cheats in CWC formatting from cheat table entries(as well as address for disassembly etc.),
 - uses AOBscan so rarely ever has to be updated(had to update it some time ago, but it still works in latest version).

**Comment by unknownbrackets** [comment]
I think hard setting it to something that will only sometimes work is potentially just more confusing, for the times when it fails.  FWIW there's also a websocket API that can be used to programmatically get the current base address too.

-[Unknown]

**Comment by hrydgard** [comment]
We used to use a static address in the past (0x2300000000), and ran into all sorts of weird issues. Mainly on non-Windows platforms though, but I think it's safer in general to let the OS choose where the memory is mapped. And as LunaMoo and unknownbrackets say, we do have ways of getting the base address out (and could add more if needed).

**Comment by NABN00B** [comment]
Maybe we can close this now with #15748 in, among other options such as the WebSocket message.
https://github.com/hrydgard/ppsspp/blob/9317fbdd5e8304de7fc0351b95cefbcc53228834/Core/Debugger/WebSocket/DisasmSubscriber.cpp#L255-L267
