### ISSUE TITLE
Add:Exporting game files from games

### ISSUE THREAD

**Issue by IX-285** [hrydgard/ppsspp#15655]
### What should happen

PPSSPP already has export textures feature which comes useful to lot of people but leaves lot to be desired considering it's texture only reach

New options should include exporting **all** game files read from emulator at current moment,even from game archive stored files

### Who would this benefit

This would benefit game translators,HD texture creators,modders and dataminers to preserve and learn techniques used in these games

### Games this would be useful in

Every PSP game

### Other emulators or software with a similar feature

Dolphin emulator has feature where it shows all files of emulated games

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by LunaMoo** [comment]
Lies, it doesn't help "learning" anything nor it helps "modders" and feature like that definitely doesn't teach anyone any techniques used in games.
 All of that learning and modding requires learning and understanding low level programming then reverse engineering how the game works, that's why every modder team requires at least one person dealing with it to even start doing anything and no projects ever are based on universal extractors.
 Image files are also not textures, if you want to create HD textures, you dump standard definition ones first. Extracting images doesn't help in any way with that as you can't just inject high res versions of the sprites in game and make it magically work.

 From my experience people extract files to reuse game content within their own projects etc. such reuse of copyrighted content is illegal through(and many japanese companies like SquareEnix for example are very defensive about their stuff), so their work doesn't get shared and as such doesn't benefit anyone but them.


 PPSSPP is not emulating nintendo console like dolphin, but sony's one, this means each and every game does things differently, most of the time various forms of compression are involved, file structure is often stored separately as well, PPSSPP doesn't really see or does anything with those, it only accesses files on the disc, it's games which extract those binary files, so an option like that doesn't seem to have any sense in PSP emulator. Dumping files which PPSSPP "sees" is equal to extracting ISO using 7z. The one file that was universally handled the same way and useful for modders to decrypt and dump is already dumped by PPSSPP - game executable.

 If you need files from some PSP game, I'd recommend learning mips and use PPSSPP debugging features. It's really easy to understand how PSP games work once you know mips and it leads to fun achievements, how often can a human claim do do something as first in the world? Well if you learn assembly it's pretty common, I have lots of first in the world achievements simply because of that hobby, first to play broken games, first to play japanese games with injected english scripts etc..

**Comment by hrydgard** [comment]
@LunaMoo It's not really nice to accuse people of lying, even if there are misconceptions. Please chill a little.

A much shorter way to state LunaMoo's point is: PSP games are just ISO file systems, which you can open in 7zip or any other ISO tool. Intercepting reads from the game is not really any different from you just poking around the files inside the ISO.

Texture dumping the way PPSSPP does it right now is different because we dump out data that games have already loaded into video memory. We could potentially do the same with sound effects, but there's not much else that could be reasonably automated like that.
