### ISSUE TITLE
Game texture error - Shin Sangoku Musou Multi Raid 2 Ppsspp

### ISSUE THREAD

**Issue by DjNmapin** [hrydgard/ppsspp#15716]
### Game or games this happens in

ULJM-05637

### What area of the game

During the battle the character chosen in cheat mode is all white, does anyone know what the texture error would be, and what is the way to solve it?
ID ULJM-05637 JAP

### What happens

![PPSSPP_2022-07-23-14-55-52](https://user-images.githubusercontent.com/109876444/180622377-b1cb3d61-21a4-40d7-beec-eb233d5b01ac.png)
![PPSSPP_2022-07-23-15-00-11](https://user-images.githubusercontent.com/109876444/180622380-d6d6a23c-12ba-4b20-9bf4-83049cf8ca61.png)
![PPSSPP_2022-07-23-15-03-06](https://user-images.githubusercontent.com/109876444/180622381-c865fc58-7179-47f3-8ba4-d016921dfd1d.png)

### What should happen

Fix

### GE frame capture

![Screenshot_20220707_203336](https://user-images.githubusercontent.com/109876444/180622519-ffe221a9-7d6f-4113-9e58-ae3d67372755.jpg)
7

### Platform

Android

### Mobile phone model or graphics card

J7 Metal 

### PPSSPP version affected

V1

### Last working version

V1

### Graphics backend (3D API)

Vulkan

### Checklist

- [ ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [ ] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [ ] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
Could you grab a "GE frame dump"? Instructions are here.

**Comment by DjNmapin** [comment]
Sim já efetuei o despejo de quadros GE, estão aqui anexado..
[ULJM05637.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9174851/ULJM05637.ppdmp.zip)

**Comment by LunaMoo** [comment]
If this is some character unlocked by cheat it could as well mean the cheat doesn't work properly on PPSSPP due to #11167

**Comment by DjNmapin** [comment]
> Se este for algum personagem desbloqueado por cheat, também pode significar que o cheat não funciona corretamente no PPSSPP devido a #11167

Yes, character unlocked by cheat, but in a sequence from 44 to 49 it has this texture error, but consequently the others work normally
![PPSSPP_2022-07-23-22-32-03](https://user-images.githubusercontent.com/109876444/180627382-91dbcce0-8b76-479a-baaa-97f3aeb36db2.png)
![Uploading PPSSPP_2022-07-23-22-34-04.png…]()

**Comment by Gamemulatorer** [comment]
@DjNmapin this graphics error happen in software, vulkan and opengl?

**Comment by DjNmapin** [comment]
> @DjNmapinesse erro gráfico acontece em software, vulkan e opengl?

It so happened that I've already done tests with both, but without any changes, everything remains the same error..

**Comment by DjNmapin** [comment]
I believe it is some texture error that is causing this incompatibility with the emulator

**Comment by DjNmapin** [comment]
Veja que com outros personagens desbloqueados pelo cheat, estão funcionando normalmente
![PPSSPP_2022-07-23-22-34-04](https://user-images.githubusercontent.com/109876444/180629984-46685e8c-c36d-4179-ba52-2944d62ef096.png)

**Comment by LunaMoo** [comment]
More likely it's just caused by cheat, you even posted a crash which is probably caused by memory corruption caused by cheat, just because it works in some stages doesn't mean it's safe for whole game as most cheats made on PSP were pretty poor and done by people who only started learning and assumed incorrect things about how games work.

 Probably the cheat overwritten some pointers at some stage causing both the graphic corruption and crash by game going to wrong addresses.

 My favourite example of similar case would be Patapon(Patapon 3 if I recall) where someone created cheat to change rewards, but it was just writing to a constant address all the time and those rewards were only stored there for like 10 seconds, afterwards game was storing pointers there, the cheat by accident caused corruption of game savedata which disabled leveling and people were blaming this on some nasty hacker intentional work to ruin everyone's fun which was never true as this was just poorly made cheat which bad side effects weren't immediately obvious.

**Comment by DjNmapin** [comment]
> É mais provável que seja apenas causado por cheat, você até postou um crash que provavelmente é causado por corrupção de memória causada por cheat, só porque funciona em alguns estágios não significa que é seguro para o jogo inteiro, já que a maioria dos cheats feitos no PSP eram muito ruins e feito por pessoas que apenas começaram a aprender e assumiram coisas incorretas sobre como os jogos funcionam.
> 
> Provavelmente, o truque substituiu alguns ponteiros em algum momento, causando a corrupção gráfica e o travamento do jogo indo para endereços errados.
> 
> Meu exemplo favorito de caso semelhante seria Patapon (Patapon 3 se bem me lembro) onde alguém criou cheat para mudar as recompensas, mas estava apenas escrevendo para um endereço constante o tempo todo e essas recompensas eram armazenadas lá apenas por 10 segundos, depois do jogo estava armazenando ponteiros lá, o truque por acidente causou a corrupção do saveata do jogo que desativou o nivelamento e as pessoas estavam culpando isso em algum trabalho intencional de hacker desagradável para arruinar a diversão de todos, o que nunca foi verdade, pois isso era apenas um truque mal feito, cujos efeitos colaterais ruins não eram imediatamente óbvio.

I understand perfectly, I'm aware that it could be something like texture incompatibility, but I'm also sure that there may be some way within the emulation to add other error correction experiences caused by the cheat..

**Comment by DjNmapin** [comment]
After all, I don't see another emulator better than ppsspp..

**Comment by LunaMoo** [comment]
Best way of emulator handling such problems would imo just be a big fat message telling you to disable cheats and restart emulation discarding old savestates affected by the cheat when the game crashes while you use cheats and keep nagging you if you simply reload a savestate which has a cheats flag active that this is bad and game might crash again.

**Comment by DjNmapin** [comment]
Yes, I already started from scratch, with nothing..
 But I was unsuccessful, the same texture error continues, causing this incompatibility, respectively causing this texture error in the emulator...

**Comment by DjNmapin** [comment]
> A melhor maneira de o emulador lidar com esses problemas seria apenas uma mensagem grande e gorda dizendo para você desabilitar os cheats e reiniciar a emulação descartando savestates antigos afetados pelo cheat quando o jogo travar enquanto você usa cheats e continuar incomodando você se você simplesmente recarregar um savestate que tem um sinalizador de truques ativo que isso é ruim e o jogo pode travar novamente.

In response to the message "Big and Fat" to disable and try again, I didn't understand about it, because until then I believe it's the important CHEAT part inside the emulator, otherwise it wouldn't have this function there, right?
![20220724_012552](https://user-images.githubusercontent.com/109876444/180630888-1807725e-d49c-495a-a300-992e774272df.png)

**Comment by DjNmapin** [comment]
Immense respect to all the developers of this emulator and their collaborators, and I faithfully believe in your work, I'm sure you will find a concrete solution..

**Comment by LunaMoo** [comment]
Cheat menu itself is important feature for some of us, but actually disabled by default and many people don't really care, but cheats themselves aren't and I will always advocate against including any of those big databases even when users say they tested every single one of them, because their testing is limited to like one spot and most of those cheats have 0 protections and are generally poorly made and unsafe to keep always on which most users end up doing. Even if emulator came with a list of cheats, it would not be responsible for any cheat correction, it's simply impossible to write a code that would automatically correct unsafe cheats and fix games or savedata already broken by the use of such cheats.

 Cheats are written by people, for example by me and those are just game modifications/soft patches(same as game plugins) that might and might not be used for cheating. If I modify a game in a way it causes a crash by unlocking something that's incomplete or by rewriting memory that stores something important etc. that's on me and not something which emulation can correct or fix, in fact it can't even detect it outside of knowing cheats were used.

 If a cheat causes problems, best thing you can do is contact a cheat creator reporting to him/her those faults and asking if he/she can fix it(if you even know who created that cheat as most of the time person creating them doesn't get any credit by people who spread them around on their sites full of ads).

 As for cheats always existing, well in case of PC games nowadays they already are going into oblivion varrying between monetization(paid cheat tables, trainers and cheat DLC's), bitcoin miners and keyloggers(everyone assumes false positive, but are often pretty malicious even when coming from original sources) and simply games which are casual fun that doesn't waste player time(most new games).

**Comment by unknownbrackets** [comment]
"Correction" is a complicated thing with cheats.  I don't think you have the right idea about what cheats are.

Imagine there's a restaurant you like to eat at.  And you've noticed that if you use a blowgun outside right before you order, your food tastes different.  You found the right thing to put in your blowgun and the right place to aim it, so you're feeling pretty proud of yourself.  You're not even sure WHY it works, just that it does make the food taste better.  That is the feeling a cheat author has.  That's basically how they create cheats.

Because it's working so well, you start taking friends with you.  You started doing it at lunch, but now sometimes you're bringing people for dinner and breakfast, and on weekdays not just weekends.  But you start noticing it doesn't always work.  You take your blowgun to the maker and ask them to fix it - clearly the blowgun is defective and not always firing properly, right?

But reality is cruel and more complicated.  It turns out that you just happened to be firing at the spot the apprentice chef normally works at, and by putting this person to sleep you got better food made by a better chef.  But this apprentice only works during lunch and some other shifts.  Other times you were actually hitting the most experienced chef with your blowgun dart and causing unexpected problems.

If you knew the real scenario, you wouldn't have blamed the blowgun maker.  The blowgun is working fine.  It just turns out that firing a dart at the same spot in the kitchen every time is not magic.  Unfortunately, this is very complicated to figure out and the vast majority of cheats are exactly like this - guesses that work sometimes and cause crazy problems other times.

Maybe this is a bug but I don't think anyone's even verified here that the cheat works correctly on a real PSP.

PPSSPP doesn't understand what a cheat "does", it just understands the orders the cheat gave: fire this dart exactly here in the kitchen.  It's hard to "correct" that if the location PPSSPP was told to fire the dart wasn't very smart.

-[Unknown]

**Comment by DjNmapin** [comment]
> O menu de truques em si é um recurso importante para alguns de nós, mas na verdade desativado por padrão e muitas pessoas realmente não se importam, mas os próprios truques não são e eu sempre defenderei contra a inclusão de qualquer um desses grandes bancos de dados, mesmo quando os usuários dizem que testaram todos um deles, porque seus testes são limitados a um ponto e a maioria desses truques tem 0 proteções e geralmente são mal feitos e inseguros para manter sempre o que a maioria dos usuários acaba fazendo. Mesmo que o emulador viesse com uma lista de cheats, ele não seria responsável por nenhuma correção de cheat, é simplesmente impossível escrever um código que corrija automaticamente cheats inseguros e conserte jogos ou savedata já quebrados pelo uso de tais cheats.
> 
> Cheats são escritos por pessoas, por exemplo, por mim e são apenas modificações de jogos/soft patches (iguais aos plugins de jogos) que podem ou não ser usados ​​para trapacear. Se eu modificar um jogo de uma forma que cause uma falha, desbloqueando algo incompleto ou reescrevendo a memória que armazena algo importante etc. de saber que trapaças foram usadas.
> 
> Se uma trapaça causar problemas, a melhor coisa que você pode fazer é entrar em contato com um criador de trapaças relatando a ele essas falhas e perguntando se ele pode corrigi-las (se você souber quem criou essa trapaça, pois na maioria das vezes a pessoa que as cria não não recebem nenhum crédito por pessoas que os espalham em seus sites cheios de anúncios).
> 
> Quanto aos cheats sempre existentes, bem no caso dos jogos de PC hoje em dia eles já estão caindo no esquecimento variando entre monetização (tabelas de cheats pagas, treinadores e DLC's de cheats), mineradores de bitcoin e keyloggers (todos assumem falsos positivos, mas muitas vezes são bem maliciosos mesmo quando provenientes de fontes originais) e simplesmente jogos que são diversão casual que não desperdiça tempo do jogador (a maioria dos novos jogos).

Muito obrigado pelas dicas, muito produtivo..
Vou procurar novas experiências dentro do game, gosto muito dos cheats, costumam ser interessantes, mais como você disse que alguns cheats são ruins.. 
– Alguma dica sobre configuração para melhores texturas e desempenho?

**Comment by DjNmapin** [comment]
> "Correção" é uma coisa complicada com cheats. Eu não acho que você tenha a ideia certa sobre o que são trapaças.
> 
> Imagine que há um restaurante em que você gosta de comer. E você notou que, se usar uma zarabatana logo antes de fazer o pedido, sua comida terá um sabor diferente. Você encontrou a coisa certa para colocar em sua zarabatana e o lugar certo para apontá-la, então você está se sentindo muito orgulhoso de si mesmo. Você nem sabe por que isso funciona, apenas que faz com que a comida tenha um sabor melhor. Esse é o sentimento que um autor de trapaça tem. É basicamente assim que eles criam cheats.
> 
> Porque está funcionando tão bem, você começa a levar amigos com você. Você começou a fazer isso no almoço, mas agora às vezes você está trazendo pessoas para jantar e café da manhã, e durante a semana não apenas nos fins de semana. Mas você começa a perceber que nem sempre funciona. Você leva sua zarabatana para o fabricante e pede para consertar - claramente a zarabatana está com defeito e nem sempre atirando corretamente, certo?
> 
> Mas a realidade é cruel e mais complicada. Acontece que você estava atirando no local em que o chef aprendiz normalmente trabalha e, ao colocar essa pessoa para dormir, você conseguiu uma comida melhor feita por um chef melhor. Mas este aprendiz só trabalha durante o almoço e alguns outros turnos. Outras vezes, você estava realmente acertando o chef mais experiente com seu dardo de zarabatana e causando problemas inesperados.
> 
> Se você conhecesse o cenário real, não teria culpado o fabricante da zarabatana. A zarabatana está funcionando bem. Acontece que disparar um dardo no mesmo lugar da cozinha todas as vezes não é mágico. Infelizmente, isso é muito complicado de descobrir e a grande maioria dos truques são exatamente assim - palpites que funcionam às vezes e causam problemas loucos outras vezes.
> 
> Talvez isso seja um bug, mas acho que ninguém verificou aqui que o truque funciona corretamente em um PSP real.
> 
> O PPSSPP não entende o que um trapaceiro "faz", apenas entende as ordens que o trapaceiro deu: dispare esse dardo exatamente aqui na cozinha. É difícil "corrigir" que, se o local PPSSPP foi informado para disparar o dardo, não foi muito inteligente.
> 
> -[Desconhecido]

Sorry, don't take this as a statement that the emulator is having problems;  I'm sure this emulator is the best, but it could be a bug generated by cheats, causing an error in the emulator, I just asked for an analysis for those who are professionally understood what was generating these errors..

**Comment by IrfanH495** [comment]
@DjNmapin You better look for a list of characters that can be used using cheats.
usually the person who makes the cheat will make a list of characters that can be used.
For example
http://yuuki0000.blog61.fc2.com/blog-entry-68.html
