### ISSUE TITLE
Missing macOS build for v1.13

### ISSUE THREAD

**Issue by p-linnane** [hrydgard/ppsspp#15737]
### Game or games this happens in

None

### What area of the game / PPSSPP

The GitHub release of `v1.13` does not have a macOS .app

### What should happen

A macOS binary should be released

### Platform

macOS

### Mobile phone model or graphics card

N/A

### PPSSPP version affected

v1.13

### Graphics backend (3D API)

Other

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
I took a quick look at Actions around the tag, and I don't see any that even ran the macOS steps.  @vit9696, not sure if you might be interested in looking into this?  Maybe Actions changed something.

The tarball action did run, but note that it has a different kind of trigger:
https://github.com/hrydgard/ppsspp/blob/a92e764c65b3248d1ddd7107ffa4c598a2ef4ff2/.github/workflows/tarball.yml#L5

That said, the release wasn't created automatically, and I assume the above only happened when it was created manually.

-[Unknown]

**Comment by darkuser89** [comment]
Only Arm Mac´s
[PPSSPPSDL_v1.13.zip](https://github.com/hrydgard/ppsspp/files/9205545/PPSSPPSDL_v1.13.zip)
[PPSSPPSDL_v1.13-10-gad59fe0fe.zip](https://github.com/hrydgard/ppsspp/files/9205553/PPSSPPSDL_v1.13-10-gad59fe0fe.zip)
Self build

**Comment by ANR2ME** [comment]
It worked fine on my fork tho, when i draft a new release both the tarball and macOS build appeared.
https://github.com/ANR2ME/ppsspp/releases
![image](https://user-images.githubusercontent.com/7974720/181430188-b4c4c126-b3e4-4cf8-b380-7c72f0272c82.png)

However, since the tarball action finished first, the description that appeared first were automatically generated from commits/PRs, and later when the `build.yml` finished, the text got replaced

**Comment by hrydgard** [comment]
Is there a way we can easily retrigger it? Or something I should think about when creating the 1.13.1 release?

**Comment by hrydgard** [comment]
But how do I ensure it doesn't fail again? To clarify, this is what I did:

* Created and pushed a tag.
* A couple hours later, created a release.

Is the delay between the problem? Should I just remove both and redo it, and create the release immediately after tagging?

**Comment by ANR2ME** [comment]
Rerunning the job seems to be able to Upload the build again, i tested it by deleting the released zip and then re-run the job

**Comment by vit9696** [comment]
> Created and pushed a tag.

Ok

> A couple hours later, created a release.

That's what GitHub Actions did for the last three releases. Creating it on your own will likely make a conflict.

**Comment by hrydgard** [comment]
Hm. But then it should have created the release within those hours in between, I'd think? 

Anyway, I'm testing now to first just rerun the whole CI for the 1.13 version, and if that doesn't work, I'll remove the release and do it again.

**Comment by ANR2ME** [comment]
looks like it skipped the Create macOS
![image](https://user-images.githubusercontent.com/7974720/181453398-b1405732-67e6-40d1-9f07-143533055dcf.png)

**Comment by vit9696** [comment]
> Hm. But then it should have created the release within those hours in between, I'd think?

That's what I would expect too, and I honestly thought that https://github.com/softprops/action-gh-release would add to an existing release if that is present as well.

**Comment by hrydgard** [comment]
well anyway, I removed the release, kicking the job again...

**Comment by vit9696** [comment]
My understanding is that you need to drop the tag here too: https://github.com/hrydgard/ppsspp/tags

**Comment by ANR2ME** [comment]
i think you need to trigger the action from "Draft a release" for it to have the tag job running
![image](https://user-images.githubusercontent.com/7974720/181454943-ae4c57f9-2304-48d9-908f-d2ce189f8e59.png)

**Comment by vit9696** [comment]
That can work too, I think. The event triggers when a tag is pushed.

**Comment by hrydgard** [comment]
For whatever reason, everything worked out just fine with https://github.com/hrydgard/ppsspp/releases/tag/v1.13.1, except that the tar.xz was not generated this time? Weird stuff.

**Comment by p-linnane** [comment]
Thanks everyone! I've opened a PR to update this in `homebrew-cask`.

https://github.com/Homebrew/homebrew-cask/pull/128766

**Comment by ANR2ME** [comment]
> For whatever reason, everything worked out just fine with https://github.com/hrydgard/ppsspp/releases/tag/v1.13.1, except that the tar.xz was not generated this time? Weird stuff.

The tarball action can only be triggered through "draft a release" at github during my test, so you need to create the new tag from github if you want to trigger all of those action at the same time & tag.

**Comment by rofl0r** [comment]
the root cause of this problem is https://github.com/hrydgard/ppsspp/issues/15761#issuecomment-1200290556

the mac release action uses an action that triggers to make a release from a tag automatically, which is quite a mess.

if @hrydgard is fine with having this happen automatically vs drafting the release himself manually, than imo the "create release from tag" should be a separate action, and the "upload mac binary" too, which should instead use the softprops/action-gh-release@v1 action, example code to do so can be taken from my PR here: https://github.com/hrydgard/ppsspp/pull/15762 - it appears the person creating the latter action just copy/pasted some sample which joined both logically separate steps into a single thing.
