### ISSUE TITLE
Tekken 6 Bonus Stage Nancy laser beam is invisible (lines)

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#15756]
### Game or games this happens in

ULES01376

### What area of the game

ppsspp v1.13.1 Nancy laser beam is invisible.
![Screenshot_2022-07-30-09-02-59-333_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/181909342-609a7b66-c69d-465e-9583-2c115b2db5f7.jpg)

ppsspp v1.12.3 Nancy laser beam is visible
![Screenshot_2022-07-30-09-03-23-299_org ppsspp ppssppgold](https://user-images.githubusercontent.com/37603562/181909389-fc286fd1-97fd-465f-9034-a0a4e48e5271.jpg)

### What happens

Nancy laser beam is invisible.

### What should happen

Nancy laser beam should be visible.

### GE frame capture

[ULES01376.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9226171/ULES01376.ppdmp.zip)

### Platform

Android

### Mobile phone model or graphics card

Redmi Note 9 Android 12 Helio G85 Mali-G52 GPU

### PPSSPP version affected

v1.13.1

### Last working version

v1.12.3

### Graphics backend (3D API)

Vulkan/OpenGL

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Thanks for the report! Likely related to the new line drawing method.

**Comment by hrydgard** [comment]
Every Extend Extra seems impacted according to Panderner on Discord:

![image](https://user-images.githubusercontent.com/130929/186216052-38d7c89c-8220-4a80-ae92-14b269757c36.png)

**Comment by Panderner** [comment]
Here:
[RROO00643.zip](https://github.com/hrydgard/ppsspp/files/9412960/RROO00643.zip)

**Comment by Gamemulatorer** [comment]
Tekken 6 is crashing on the latest build if set to skip buffers rendering!

**Comment by hrydgard** [comment]
Yeah, I'm not testing much with it off, I highly recommend to turn on buffered rendering. But I'll fix it of course.

**Comment by Gamemulatorer** [comment]
> Tekken 6 is crashing on the latest build if set to skip buffers rendering!

Juice 2 is also crashing using skip buffers rendering and some other games I tried.

**Comment by hrydgard** [comment]
Yeah, I'll get around to fixing that soon.

**Comment by hrydgard** [comment]
So the issue here is that the line is actually drawn, it's just so ridiculously thin that it doesn't cover more than a pixel or two, so something is wrong with the line expansion math. The GE dump reproduces perfectly.

The following change makes it look good, which is of course a ridiculous change to make:

```
			Vec2f addWidth = Vec2f(-vertical, horizontal).Normalized() * 10000.0f;
```

![image](https://user-images.githubusercontent.com/130929/191361795-53d98262-3afc-4175-af1a-ae0ce34fee5e.png)

**Comment by unknownbrackets** [comment]
The beam looks like this on a PSP:
![#15756_ULES01376_tekken_beam_line](https://user-images.githubusercontent.com/191233/191368551-262737d9-189c-4a14-abcb-7c66ecf6cdc7.png)

The software renderer (with #16066) gets close, just slightly off:
![#15756_ULES01376_tekken_beam_line_softgpu](https://user-images.githubusercontent.com/191233/191368905-0c60833e-3ed4-4cf6-b62b-67055b810c55.png)

The line drawn at 5780/5813 uses addWidth: 0.985653,0.168787 dx/dy: 0.004167,0.007353, or 0.00410721605 width for the rectangle.  That's slightly less than 1 pixel.  In renderdoc, it's the last indexed draw in the first render pass.

But in the render doc the positions are not different, however.  There's only two unique xyzw values going in or out of the vertex shader.  Which now makes sense, because of course, w.  That's why it's not adding anything after transform.  D'oh.

-[Unknown]

**Comment by Gamemulatorer** [comment]
> Tekken 6 is crashing on the latest build if set to skip buffers rendering!

I can exibit this issue again in the recent build.

**Comment by hrydgard** [comment]
crash on skip buffers? I'll get that fixed soon.

**Comment by Gamemulatorer** [comment]
> crash on skip buffers? I'll get that fixed soon.

Yes.
