### ISSUE TITLE
MO2:SP - Flickering textures (Android/Windows)

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#15856]
### Game or games this happens in

ULJM06097 - Musou Orochi 2 Special (Japan)

### What area of the game

In-gameplay.  

### What happens

Flickering textures, it happen on Vulkan, D3D9 and D3D11 only, OpenGL is fine.

![ULJM06097_00042](https://user-images.githubusercontent.com/26355472/185188007-369b3d94-3dd6-42e1-bb06-03907c1fd138.jpg)

### What should happen

Can rendering textures without flickering.

![ULJM06097_00043](https://user-images.githubusercontent.com/26355472/185188074-97cff7df-8285-4ed9-89b9-c9aac3f86e28.jpg)

### GE frame capture

[GE DUMP.zip](https://github.com/hrydgard/ppsspp/files/9364402/GE.DUMP.zip)

### Platform

Windows

### Mobile phone model or graphics card

Intel HD Graphic 520.

### PPSSPP version affected

v1.12.3-113-ga3a6bdc19

### Last working version

v1.12.3-102-ga9d7948f7

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
So that's #15069 . I assume some minor precision difference, but odd that OpenGL would be unaffected.

@unknownbrackets just FYI, don't mean to tell you to work on it :)

**Comment by unknownbrackets** [comment]
In OpenGL, 389/2495 draws some of the faded grass that ought to show in Vulkan but doesn't.

This draw has:
 * Depth clamp, test (src >= dst)
 * Fog, lighting (but no lights, separate specular)
 * Alpha blend (double a + inverse double a) and test (a > 0)
 * Simple 4 triangle fan

Depth test is what is failing.  The depth value there prior to 389 is what appears to be incorrect at ~1296 when it should be ~1164.  That's established at 178/2495, looking at the pixel at 271,99.

This draw is also a 4 vert triangle fan.  And neither of these draws seem to hit the software transform path...

It's caused by f35c7d04bd31, and reverting this part in current master does make it render as expected:

```diff
diff --git a/GPU/Vulkan/DrawEngineVulkan.cpp b/GPU/Vulkan/DrawEngineVulkan.cpp
index 2f65b18c9..fcfb09bfb 100644
--- a/GPU/Vulkan/DrawEngineVulkan.cpp
+++ b/GPU/Vulkan/DrawEngineVulkan.cpp
@@ -915,8 +915,11 @@ void DrawEngineVulkan::DoFlush() {
                // We don't have a "DrawStateEarly" in vulkan, so...
                // TODO: Probably should eventually refactor this and feed the vp size into SoftwareTransform directly (Unknown's idea).
                if (gstate_c.IsDirty(DIRTY_VIEWPORTSCISSOR_STATE)) {
-                       gstate_c.vpWidth = gstate.getViewportXScale() * 2.0f;
-                       gstate_c.vpHeight = gstate.getViewportYScale() * 2.0f;
+                       ViewportAndScissor vpAndScissor;
+                       ConvertViewportAndScissor(framebufferManager_->UseBufferedRendering(),
+                               framebufferManager_->GetRenderWidth(), framebufferManager_->GetRenderHeight(),
+                               framebufferManager_->GetTargetBufferWidth(), framebufferManager_->GetTargetBufferHeight(),
+                               vpAndScissor);
                }

                int maxIndex = indexGen.MaxIndex();
```

Seems like it's because of the optimization to avoid dirtying depth/proj when not necessary, but ignoring that here.  Oops.  I guess we can't really treat this Convert function as a stateless converter.

-[Unknown]
