### ISSUE TITLE
[Regression] Gripshift some objects rendering incorrectly

### ISSUE THREAD

**Issue by AryzenRS** [hrydgard/ppsspp#15878]
### Game or games this happens in

ULUS-10040 - Gripshift

### What area of the game

This occurs in any gameplay map, simply select the first level and look at the start and finish line during the fly-by.

Note, this happens in Vulkan as well as D3D11

### What happens

Certain objects will render incorrectly/render objects behind from certain angles and distances. 
![Screen Shot 2022-08-21 at 4 05 56 AM](https://user-images.githubusercontent.com/66155383/185783986-9621f66f-df66-4353-b6c1-a2c494864f65.png)
![Screen Shot 2022-08-21 at 4 06 18 AM](https://user-images.githubusercontent.com/66155383/185783989-da0ccf77-39f7-4b25-a492-644466266beb.png)
![Screen Shot 2022-08-21 at 4 06 48 AM](https://user-images.githubusercontent.com/66155383/185783991-50949a17-f738-4301-9ae5-e28d78940a14.png)

### What should happen

The objects in question should appear solid as they would intuitively be

![Screen Shot 2022-08-21 at 4 11 30 AM](https://user-images.githubusercontent.com/66155383/185784132-4ff35272-025e-4182-b563-90da247c6a7c.png)

### Platform

Windows

### Mobile phone model or graphics card

Nvidia GeForce GTX 1080

### PPSSPP version affected

v1.13.1-395-g5f30c88e3

### Last working version

v1.12.3

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by sum2012** [comment]
@AryzenRS  Please create a frame dump to help dev debug.
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by AryzenRS** [comment]
> @AryzenRS Please create a frame dump to help dev debug.

Here's a frame dump, I hope this was done correctly

[ULUS10040_0001.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9390022/ULUS10040_0001.ppdmp.zip)

**Comment by unknownbrackets** [comment]
Here's what that looks like on a real PSP:
![#15878_ULUS10040_gripshift_gap](https://user-images.githubusercontent.com/191233/185812970-69a54b56-f3bc-4a40-bbbf-29c899f0bef9.png)

Software rendering looks similar (there are some precision issues, though, the PSP one looks nicer):
![#15878_ULUS10040_gripshift_gap_softgpu](https://user-images.githubusercontent.com/191233/185813333-6dab9729-4e48-4b7d-b45d-ab273eedaebc.png)

That area is initially drawn around 156/257.  This is drawn in a bit of a distorted square 512x512 canvas.  It then stretches this to 480x272 at 232/257.  Vulkan seems to draw it incorrectly, even at 156/257, so the problem is there (or earlier.)

This is what I get from GL (and this visually matches Vulkan):
![#15878_ULUS10040_gripshift_gap_gles](https://user-images.githubusercontent.com/191233/185814532-406a72a7-8db3-4311-a839-0b4771de7f21.png)

Other lighting differences can also be observed, but let's focus on 156.  It is using mipmaps, and they seem a bit strange.  Every other mipmap level is blank.  This is actually true for the gate as well.  It seems like the mipmap levels are causing things to blur out of sight.

Back to software, the mip levels are all nice and correct.  No every other happening here, they've all got valid data.

Vulkan, Direct3D 9, and Direct3D 11 all have the alternating thing going on.
With OpenGL, all the mip levels are transparent.  It's interesting that this is different.

Ah, I see why - I got the sharing thing backwards in #15872 and didn't catch it.  Darn it.  OpenGL seems to have a GE preview issue now (I think?) reading the mips, so that's separate.

-[Unknown]
