### ISSUE TITLE
"Step Frame" in the GE debugger not reliable

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#15893]
Not sure when this started, but in several games I've tried recently, Step Frame just doesn't do anything, to get things to stop I have to click Step Tex for example.

To be investigated more

**Comment by unknownbrackets** [comment]
Currently it happens for any call to `sceDisplaySetFramebuf()` (immediate or upon latched), so I think GTA and Spongebob may not trigger it.  Doing it at vsync tends to put you in the middle of a frame in most games, so that's not a very tempting solution.

Recording will try for ~4 flips to hit a framebuf, and if that doesn't work it will use the after flip event.  I guess we could do the same in the debugger, but I figured it would be confusing for it to take so long to "find" the frame.

Since the game ostensibly does not actually flip frames, to me it doesn't seem like total nonsense that "step frame" never breaks (like step out from `main()` in a game that renders in an endless loop.)

-[Unknown]
