### ISSUE TITLE
Slow loading textures in version 1.13.1

### ISSUE THREAD

**Issue by endrare** [hrydgard/ppsspp#15993]
### Game or games this happens in

Monster hunter portable 3rd hd

### What area of the game

every change of map will see a changed texture

### What happens

V1.13.1

https://user-images.githubusercontent.com/33047223/189379111-e7dbb9b4-e029-407c-a6da-4f6c7df2ad7a.mp4

### What should happen

V1.12.3

https://user-images.githubusercontent.com/33047223/189380091-3a0bb328-b45d-48ea-8cf5-9990f3be99ec.mp4

### Platform

Android

### Mobile phone model or graphics card

Redmi note 8

### PPSSPP version affected

v1.13.1

### Last working version

v.1.12.3

### Graphics backend (3D API)

OpenGL / Vulkan

**Comment by unknownbrackets** [comment]
Yeah, this was done intentionally to prevent the severe framedrops (it also shows you dropping to below 100% speed), which even affects music and everything.  It's an option in ppsspp.ini, but not in the UI.

Latest Android versions have also made loading texture replacements slower, so it's getting even worse which was part of the motivation for this setting.  Many people have already said "a big thank you" for fixing the hitches in texture scaling and performance in recent versions, as it was frustrating a lot of people.

The delayed pop-in of replacements will automatically improve or even go away if you get a better, faster device.  If your device was fast enough to load the data right away, there'd be no pop-in and no frame drops either.

I'm going to close this since it was an intentional change that improves a lot of games, and there is a ini setting workaround for those who prefer the other tradeoff.

-[Unknown]
