### ISSUE TITLE
PES AD-HOC SERVER 

### ISSUE THREAD

**Issue by Mighty-v** [hrydgard/ppsspp#16041]
#### Which game or games? PES 2022
 efootball v 1.1.2

#### Checklist

 - [ ] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
 - [ ] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
 - [ ] Try resetting settings or older versions and include if the issue is related.
 - [ ] Include logs or screenshots of issue.

**Comment by adenovan** [comment]
provide some HLE function logs please .

**Comment by unknownbrackets** [comment]
Is this really a PPSSPP issue?  Or is it just some issue with whatever server you're trying to connect to?

-[Unknown]

**Comment by ANR2ME** [comment]
First of all, what is the game/title ID of this efootball v1.1.2 ? because i can only find info about this (which is for PS4/5) https://www.konami.com/efootball/en/topic/news/375

Please provide the Debug Log using the latest version (PPSSPP v1.3.2) when possible.
If you're using a dead adhoc server like http://myneighborsushicat.com/ it won't work of course.
And if you're seeing a red error message on screen, please provide the screenshot of this message.

**Comment by ANR2ME** [comment]
> > efootball
> 
> looks like a game hack for one of the PES games: https://www.youtube.com/watch?v=nHVLSzGgx0A lol.

Hmm... the savedata have this folder `TMART065500001000` doesn't look like a PSP's game/title ID, i guess they also modified the title ID

**Comment by MojoJojoDojo** [comment]
Well if they used the public adhoc server it could be the same issue as for Cars lol.

**Comment by unknownbrackets** [comment]
Given that it's working for others and networking can be tricky with firewalls and things, I'm going to assume this was caused by something else.  It might be good to discuss settings or problems on Discord or the forum for more help.

If it's determined to be a bug, comment here and we can reopen this.

-[Unknown]
