### ISSUE TITLE
Why is armips dependency not newest version?

### ISSUE THREAD

**Issue by GermanAizek** [hrydgard/ppsspp#16136]
### What should happen

Update dependency from here: https://github.com/Kingcom/armips

### Who would this benefit

There are a lot of useful changes in new version.

### Games this would be useful in

-

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
Because there are a lot of other things to do :) 

Would merge a PR that upgraded it.

**Comment by GermanAizek** [comment]
> Because there are a lot of other things to do :)
> 
> Would merge a PR that upgraded it.

@hrydgard OK, I'll try to submit PR merge with new version

**Comment by unknownbrackets** [comment]
I actually did update it locally a bit ago, but was worried about c++17 having compat issues.  I can push it up.

-[Unknown]

**Comment by GermanAizek** [comment]
> I actually did update it locally a bit ago, but was worried about c++17 having compat issues. I can push it up.
> 
> -[Unknown]

@unknownbrackets thx u very much if you do this

**Comment by unknownbrackets** [comment]
Well, I pushed up what I had done earlier this year, and also made some buildfixes.  But it seems like we'd need an ifdef for armips to not use some filesystem funcs, or else we'd need to patch the std::filesystem compat library it's using to support UWP.

Also we'd need to raise macOS and iOS minimum versions.  Otherwise, #16137 has the changes.

-[Unknown]
