### ISSUE TITLE
Corrupted in-game photo and game-stopping crash on TIGER & BUNNY On-Air Jack

### ISSUE THREAD

**Issue by usagiDamaci** [hrydgard/ppsspp#16157]
### Game or games this happens in

NPJH-50589 - TIGER & BUNNY On-Air Jack

### What area of the game

After ending any stage / level. Easily accessible, but it takes a few screens to get there.

### What happens

There's a newspaper showing a photo taken in-game, but the photo is visibly corrupted, and the game black-screens with a crash right after pressing O twice to continue with the story. Luckily, the game saves before the crash, but needs to be resetted.

Here's the newspaper with the corrupted photo (which is saved together with the game data, by the way):
![NPJH50589_00007](https://user-images.githubusercontent.com/10482896/193605783-40956ff0-c271-4596-bcad-cb781912cd38.jpg)
And here's the crash screen, appearing after pausing and unpausing the game:
![NPJH50589_00008](https://user-images.githubusercontent.com/10482896/193606070-c6e35665-1eae-4eeb-a596-db709fba2227.jpg)

### What should happen

Can't take a screenshot because the photos used in the newspaper are from random moments in the game, if I recall correctly, but what should happen can be seen on this video recorded on a real console:
https://www.youtube.com/watch?v=sVhfEGzZ3fw&t=716s

### GE frame capture

[NPJH50589_0001.zip](https://github.com/hrydgard/ppsspp/files/9698639/NPJH50589_0001.zip)

### Platform

Windows

### Mobile phone model or graphics card

AMD Radeon HD 3000

### PPSSPP version affected

v1.13.2

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by Gamemulatorer** [comment]
Might be good to try the recently
build https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by Panderner** [comment]
@usagiDamaci what CPU are you using?

**Comment by hrydgard** [comment]
Should be able to fix that without any extra information, I can hack our cpuinfo code to pretend I don't have it.

**Comment by unknownbrackets** [comment]
I assume the screenshot is just a missing block transfer.  It'd probably be unbearably slow, but if you play the part before this where it's supposed to render whatever is in that photo using the software renderer, it'll probably work.  That would effectively confirm my theory.

We'll probably need to figure out what method of download this is using to hook into the hardware renderers.

-[Unknown]

**Comment by combo-pizza** [comment]
![image](https://user-images.githubusercontent.com/95991264/194196869-0926c25b-16c9-423e-90e2-e84aba7cedba.png)
[NPJH50589 Vulkan.zip](https://github.com/hrydgard/ppsspp/files/9720496/NPJH50589.Vulkan.zip)
[NPJH50589 Software.zip](https://github.com/hrydgard/ppsspp/files/9720497/NPJH50589.Software.zip)

**Comment by combo-pizza** [comment]
![image](https://user-images.githubusercontent.com/95991264/194197781-b084f535-4965-44ef-ab51-4cc23ccdcacf.png)
[NPJH50589 Software.zip](https://github.com/hrydgard/ppsspp/files/9720522/NPJH50589.Software.zip)
Still does the same thing in software for me too

**Comment by unknownbrackets** [comment]
That's interesting.  To be clear, this is from the start?  If you use software to load a save with a corrupted photo already saved, it will dutifully save that corrupted photo.

What I think is happening is that the game takes a screenshot and stores it with the save data.  But the screenshot comes back as garbage during hardware rendering.

-[Unknown]

**Comment by combo-pizza** [comment]
Oh! I could try playing it from the start, the first level is very easy

**Comment by combo-pizza** [comment]
Had to redo the post because I forget a dump, but it basically does it from the beginning too
![image](https://user-images.githubusercontent.com/95991264/194207815-9c546d96-c0b2-410f-9c4e-12b62699fe52.png)
[NPJH50589 software.zip](https://github.com/hrydgard/ppsspp/files/9720918/NPJH50589.software.zip)

**Comment by unknownbrackets** [comment]
Interesting.  Attempting to play that most recent frame dump on my PSP simply makes it shut off (maybe it's overflowing some buffer?  or corruption in display list caused a crash?)  However, the second frame dump here is able to execute without crashing (and just shows that green pattern.)

The red in the GE debugger is a highlight to show where this primitive is drawing to and from.  You can right click to enable or disable it.  Drawing in strips like this is fairly common.  The display list often has "data" in the middle of it which it simply jumps over, but it would normally not be processed.

In the working frame dump, 47/64 is where it draws the texture that already looks wrong (I suspect this was simply while block transfers were broken recently - my mistake.)  Tex format is 8888, 512x512, from RAM, stride=480.  Decal/RGB, which is consistent with texturing from a copy of a rendered 8888 framebuf.  Pointless alpha test and blend enabled (since it's using flat FF vertex alpha, and RGB mode on the texture.)

This corresponds to 48/65 in one of the broken frame dumps.  Texture data looks different but otherwise the draw is fine and tex format looks valid.  If I change the stride to 512 from 480, things look much better:

![Newspaper with proper scene screenshot](https://user-images.githubusercontent.com/191233/194224221-d42c2d1b-b2f0-4732-9197-2bcf6aad6cf5.png)

However, indeed after that it draws a 4096x16 texture at DXT3 which looks totally corrupt.  This draw occurs in the working frame dump, but it doesn't use the same format/etc. and doesn't look corrupt.  I suspect something about the block transfer corrupted metadata the game used to output info about the texture usage.

Approaching draw 62/64 (good frame dump):
```
World data # -20.000000
World data # 8.000000
CullFace enable: 0
Material ambient color: ffffff
Material alpha: 00
Material diffuse color: ffffff
Material specular color: ffffff
Blend mode: add src.a, 1.0 - src.a
Blend fix A: 0000ff
Blend fix B: 0000ff
SetVertexType: float texcoords, float positions
VADDR: a2e878 => 08a2e878
DRAW PRIM TRIANGLE_STRIP: count= 4 vaddr= 08a2e878
```

Approaching 63/65 (broken frame dump):
```
World data # -20.000000
World data # 8.000000
CullFace enable: 0
Material ambient color: ffffff
Material alpha: 00
Material diffuse color: ffffff
Material specular color: ffffff
Blend mode: add src.a, 1.0 - src.a
Blend fix A: 0000ff
Blend fix B: 0000ff
TexMode swizzle, 0 levels, shared clut
TexFormat DXT3 (extra 001010)
TexFlush
Texture stride 0: 0x1019, address high=08
NOP
Texture size 0: 4096x16 (extra 00040c)
TexFlush
TexFlush
Texture map enable: 1
Clut format: 00ff1c (BGR 5650)
CLUT addr: high=00
CLUT addr: low=14111a
Clut load: 00141110, 960 bytes (extra 001500)
SetVertexType: float texcoords, float positions
Texture stride 1: 0x0000, address high=08
Texture address 1: low=8467a0
Texture stride 2: 0x0000, address high=08
Texture address 2: low=8487a0
Texture stride 3: 0x0000, address high=08
Texture address 3: low=848fa0
VADDR: a2e8d8 => 08a2e8d8
DRAW PRIM TRIANGLE_STRIP: count= 4 vaddr= 08a2e8d8
```

In any case, the problem here looks like it's somehow transferring with the wrong stride (and thus overwriting the game's memory.)

It'd help (since you have the game) if you could try using the debugger indeed.  Here are some steps:
1. Open both the Memory Viewer and GE Debugger windows when you're looking at the newspaper issue.
2. Click Step Prim on the GE Debugger until you get to where it starts drawing the bad graphics onto the newspaper.
3. Note the value shown on the left under the garbled texture: in your screenshot it was 0x08c89120, but this might potentially vary so check it.
4. Go to the Memory Viewer, and paste that address into the "Goto:" box, then press enter.
5. Next to the Goto box, change "Show allocations" to "Show writes".
6. Click any of the two hex digits in the first line (i.e. after 08c89120, it'll show 00 00 00 00, or something.  Click those.)
7. At the bottom of that window in the status bar, it'll have some text describing what operation was detected which wrote to this RAM.  It'd help to know what this says (the GE debugger doesn't record this information in frame dumps.)

It's probably one of our download frame hooks, I'm guessing, but could be wrong.

-[Unknown]

**Comment by combo-pizza** [comment]
AH here! I think I got it!!!

![image](https://user-images.githubusercontent.com/95991264/194246618-97e63790-fcfa-463c-9a0a-ddaad1547889.png)

**Comment by unknownbrackets** [comment]
Hm, it seems like maybe it wasn't detected - strange.  Maybe it was a memcpy from VRAM?  If it was detected, that's a memcpy from 0x4040 bytes, or 4112 pixels.  That's a bit of an uneven count, not divisible by 480 or 512.

Framebuffers are usually rendered with a stride of 512 pixels (that's the distance between lines, i.e. between X=0 at Y=0 and X=0 at Y=1), even though the screen is only 480 pixels.  This means there's 32 pixels at the end of each line of "extra space" that is usually ignored.

In this case, the game has the texture set to use a stride of 480.  When I forced it to use 512, the texture looked visually right, but there was corrupted memory (implying it overwrote good memory by writing 512*272 pixels instead of the correct 480*272 pixels.)

So I suspect the texture settings of 480 stride are right, but it may be tricky to figure out where this came from and why it was written with the wrong stride.  It could be the game copied it with the wrong stride, but because of something subtle we did wrong elsewhere...

-[Unknown]

**Comment by combo-pizza** [comment]
It sounds like I couldn't help much anymore with out knowing how the psp GE works. I hope you can find a copy of the game somewhere

**Comment by hrydgard** [comment]
Ah, I think you got it. That's a function we have detected and hooked - since we have no good way to detect CPU readback from VRAM, we detect and hook some common functions that do this. This one simply is:

```
static int Hook_dissidia_recordframe_avi() {
        // This is called once per frame, and records that frame's data to avi.
        const u32 fb_address = currentMIPS->r[MIPS_REG_A1];
        if (Memory::IsVRAMAddress(fb_address)) {
                gpu->PerformMemoryDownload(fb_address, 0x00044000);
                NotifyMemInfo(MemBlockFlags::WRITE, fb_address, 0x00044000, "dissidia_recordframe_avi");
        }
        return 0;
}
```

I think we accidentally make an assumption of the stride (distance in memory between the start of each line and the next). It's possible that in the game it's provided as a parameter to this function, would need to look at disassembly to confrom.

**Comment by hrydgard** [comment]
Could you copy and paste the full disassembly of the function dissidia_recordframe_avi ? From the disassembly window, not the GE debugger.

**Comment by unknownbrackets** [comment]
Based on some logs, #16179 may help this.  You can try the build from the Checks tab (once it's complete), or if it's already showing as merged, you can use the latest git build to verify if it helps.

-[Unknown]

**Comment by hrydgard** [comment]
Great! Credit is mostly unknown's - connecting this to the JPEG decoder and then doing some heroic work properly testing that stuff on hardware.

Just to clarify, when you say "which currently crashes straight at the newspaper with a black screen", what do you mean by currently?

**Comment by hrydgard** [comment]
Great, thanks! Closing then.
