### ISSUE TITLE
when creating the texture.ini file many games are extremely slow and crashing

### ISSUE THREAD

**Issue by DavidSilvadeSa** [hrydgard/ppsspp#16300]
### Game or games this happens in

NARUTO ULTIMATE NINJA HEROES 2, BLAZBLUE, GUILTY GEAR

### What area of the game

ALL

### Speed seen in PPSSPP

5/60, 5/30

### Platform

Android

### Mobile phone model or graphics card

POCO X3 PRO

### PPSSPP version affected

all

### Last working version

all

### Graphics backend (3D API)

OpenGL / GLES

### Any other notes or things you've tried

OPEN GL, VULKAN

https://youtu.be/OFvDvTKcyC8

problem

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the slowdown.
- [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
The latest version of Android made this a lot slower.  Are you really using the latest git build?  If the main screen shows "v1.13.2" instead of "v1.13.2-1711-g1fb7fe02b", you are not.  The latest git build has 1711 improvements that you're missing, some of them help performance in this case.

But it's still going to be slower, especially on Android 11.  Android made IO ridiculously slow.  It can help to move it to internal storage or reset the storage folder in settings, but that only helps on some devices.

-[Unknown]

**Comment by DavidSilvadeSa** [comment]
[v1.13.2-1734-gcf27d1413]

**Comment by unknownbrackets** [comment]
Okay, #16304 may help but not for creating a textures.ini.  However, you'll have to do something different.  Changes to the Android operating system have ruined performance of doing it the old way.

If you create a textures.ini like this, performance will be bad because of the way Android works.

However, now you can create a textures.zip instead.  The textures.zip file should contain a textures.ini plus the images to use for replacement.  This should perform a lot better.

-[Unknown]

**Comment by DavidSilvadeSa** [comment]
like this?

Uploading YouCut_20221030_204633529.mp4…

**Comment by DavidSilvadeSa** [comment]
like this?
https://youtu.be/_qOkl45FTR8

**Comment by unknownbrackets** [comment]
The PNGs, everything has to be inside the textures.zip file.  It's accessing the PNG files that is making it so slow.

-[Unknown]

**Comment by DavidSilvadeSa** [comment]
> Os PNGs, tudo tem que estar dentro do arquivo textures.zip. Está acessando os arquivos PNG que está tornando tão lento.
> 
> -[Desconhecido]

thank you very much, now it is working perfectly PPSSPP is a God now I can continue my REMASTER projects

**Comment by unknownbrackets** [comment]
Great, I'm going to close this then.  Thanks for confirming.

-[Unknown]
