### ISSUE TITLE
(Adreno)(Vulkan) Burnout Legends freeze since #15589

### ISSUE THREAD

**Issue by Gamemulatorer** [hrydgard/ppsspp#16341]
### Game or games this happens in

ULUS-10025

### What area of the game

Selecting cars before racing

### What happens

There's a new issue related to this game but now on my vivo y11 adreno 505 using vulkan issue started in https://github.com/hrydgard/ppsspp/pull/15589

https://user-images.githubusercontent.com/37603562/199276076-11ce67ec-5858-47e4-bfcd-e4f27337b92b.mp4

![Screenshot_20221101_234108](https://user-images.githubusercontent.com/37603562/199276153-166b80aa-0a92-467b-810a-51cae049c1e3.jpg)

### What should happen

No freeze/hang like in opengl

### Platform

Android

### Mobile phone model or graphics card

Vivo Y11 Android 11 Snapdragon 439 Adreno 505

### PPSSPP version affected

v1.13.1-690

### Last working version

v1.13.1

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
That's really curious that just this phone would start having problems at that commit. I'll see if I can repro.

**Comment by hrydgard** [comment]
OK I can actually reproduce this on my Pixel 3a, so that's a good start! Won't need any testing help :)

I turned off the parallelism that -690 introduced and it still happens, so it's something else and I kinda doubt it's that specific commit?

Anyway, what I'm getting is `[G3D] Failed creating graphics pipeline! result='VK_ERROR_...(unknown)'`, and we hang right after since we don't handle pipeline creation errors well.

**Comment by hrydgard** [comment]
Haha, okay, the shader must have failed to compile before too, it's just that that PR caused things to start hanging on failed shaders.

And the reason it failed to compile is that for the offending pipeline, is that the fragment shader always does "discard", which the buggy driver doesn't like. And it always discards because the alpha test is set to NEVER which means nothing is ever drawn - which means that it hardly matters if this pipeline fails anyway, heh.

I'm making things more robust to failures, and adding more logging etc.
