### ISSUE TITLE
WRC - FIA World Rally Championship crashes out on certain tracks (both USA and Europe Version)

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#16427]
### Game or games this happens in

ULUS10093 and UCES00005

### What area of the game / PPSSPP

start the game 
play as guest
choose quick rally
then shuffle until you find the Italy track and start
PPSSPP will crash out

### What should happen

load the track and play

### Logs

[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/10082970/ppsspplog.zip)

### Platform

Windows

### Mobile phone model or graphics card

AMD RX580

### PPSSPP version affected

PPSSPP v1.13.2-2006-g9c21951ef

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by Panderner** [comment]
It's working fine for me when i start the Italy track using Vulkan:
![ULUS10093_00000](https://user-images.githubusercontent.com/37503397/203762137-94f89ba7-e1a9-446a-8b75-040d882317f3.jpg)

**Comment by hrydgard** [comment]
Maybe try again on the very latest build from https://buildbot.orphis.net/ppsspp/ , and see if it's still broken?

**Comment by hrydgard** [comment]
It crashes with the software renderer? That's surprising. Maybe check if your ISO is OK, redump from UMD or check crc..

**Comment by benderscruffy** [comment]
Yes iso is ok

**Comment by hrydgard** [comment]
Hm, log ends with this, though no guarantee the crash is related:
```
07:35:200 user_main    D[G3D]: Software\SoftGpu.cpp:804 Block transfer: 04710000/200 -> 08a66f80/10, 16x8x2 (339,1016)->(0,0)
07:35:200 user_main    W[MEMMAP]: Core\Core.cpp:443 Read Block: Invalid address 0480e2a6 PC 089a83a8 LR 089a83a8
```

**Comment by Panderner** [comment]
@benderscruffy have you tried other backends?

**Comment by unknownbrackets** [comment]
0480e2a6 is about what you'd get if you multiply 1016 by 0x200 and add 339, as an offset to 04710000.  The src address definitely looks like garbage.  I should probably do some specific tests on what invalid VRAM access from block transfers actually does.

As I recall, with load CLUT, it reads zeros and wraps around to the destination (CLUT buffer, which isn't memory mapped AFAIK.)  Maybe this is a game bug that just happens to work because of hardware behavior on block transfers.

-[Unknown]

**Comment by hrydgard** [comment]
Block transfers in the soft GPU are currently barely doing any checking of the addresses being valid, so that's definitely missing.

Likewise the hardware backends are also doing incomplete checking, not checking the end addresses of the ranges.

I think it's likely that on the real PSP, it just keeps on trucking with probably something like zeroes or wrapping around indeed. I don't think it's too likely that games would depend on a particular outcome other than maybe a lens flare not working right for a frame, so just checking and skipping transfers entirely that touch bad address space might be good enough, but you never know...

**Comment by hrydgard** [comment]
I'm suspecting that the reporter tested with the software renderer, since that's what the log points at. Due to the above, I don't think we crash here in the hardware renderers.

**Comment by benderscruffy** [comment]
yes this is fixed now
