### ISSUE TITLE
Crashes reported with texture replacements

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#16640]
D3TR4KT1K on Discord reports that the following texture pack for Fate: Unlimited Codes crashes a lot:

https://github.com/Fate-AI-HD-Team/UnlimitedCodes-HD

"Usually Crash after press start button, when is loading the Background, and randomly on Survival mode"

**Comment by Bearie0912** [comment]
Thank you
fixes have been uploaded to replace the files responsible for crashing in said situations
please keep the reports coming

**Comment by hrydgard** [comment]
Hm, but PPSSPP shouldn't crash, independent of the files in the pack. What did you actually change? Is there some specific PNG type that PPSSPP fails to read?

**Comment by Bearie0912** [comment]
yeah, it shouldn't crash, I am curious about the real cause(s) too. these are just hotfixes until the root cause is found
All I did was reducing the resolution to be no more than 2048px in width or length
fyi some of the files were 4096px+ in width/length
but occasionally a 2400-ish px file can crash the emulator too

another suspicion is about the file size, which I don't know if it's true or not
there was 1 file that's 2048x2048 which was more than 4mb before and it caused a crash too (rarely) so i compressed the file during the export progress (compression level 9). after its less than 1mb, I haven't got a crash from this particular file yet

**Comment by hrydgard** [comment]
Weird. The inconsistency seems to indicate it's some sort of race condition rather than a buffer size limitation or something. Gonna have to look into it. (Though, 4096x4096 textures do consume a rather large amount of memory each (67 MB)).

**Comment by Bearie0912** [comment]
agree with the memory condition
i thought it was just me at first until the others told me they also crashed at the same frame
another thing to add is that it's the most likely to crash on load state the frame with the files in question.
especially if you load state right away after launching the emulator

**Comment by unknownbrackets** [comment]
Was any of this only with zip style texture replacements?

-[Unknown]

**Comment by hrydgard** [comment]
There were some fixes done, so probably it isn't crashing anymore. I have received reports that it still sometimes corrupts the textures after a while, I'd really like a repro instruction for that...
