### ISSUE TITLE
Custom game image in gamelist

### ISSUE THREAD

**Issue by ha7ak3** [hrydgard/ppsspp#16675]
### What should happen

It would be nice to have an option to set a custom image for games cause the internal ones are low quality and look bad specially when zoomed.
I don't mean an autodownload feature just a way to set a custom HD image.

Preview:
![before](https://user-images.githubusercontent.com/81385605/210095425-52f0d28b-b58e-4309-8d85-d3a0c47c2b9d.png)
![after](https://user-images.githubusercontent.com/81385605/210095432-55eb5158-99e2-426d-9e98-ceabfba6b76b.png)

### Who would this benefit

Everyone

### Platform (if relevant)

None

### Games this would be useful in

all games

### Other emulators or software with a similar feature

dolphin, pcsx2, duckstation

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by ANR2ME** [comment]
Isn't this supposed to be part of HD texture pack/mod?

For general case, may be PPSSPP should use texture upscaling too for these images when zoomed in

**Comment by LunaMoo** [comment]
We kind of have support for that already, but only if default pic does not exist in which case first screenshot is used as icon. It should be really easy to just add another check for game's texture folder for custom ICON0.PNG/PIC0.PNG etc. before loading actual icons/backgrounds from the game and using those custom ones instead, but ofc when someone would have a lot of games and provide a lot of high resolution textures for icons, PPSSPP memory usage and time it takes to load the whole list would significantly increase since it does it at launch and caches afterwards. I think that for the sake of android with scoped storage it would also have to be in some separate folder that could be archived and not part of the texture packs.

 Those examples looks weird and not what's most people see through, normally those icons are displayed without such zoom-in and they are neither pixelated nor blurry, they're pretty perfect as they are, not sure if that zoom in is caused by something which might need a fix or just a hyperbole to show a need for something that would just be a very niche feature. For most people icons are just that, something they recognize and click to launch a game not something to zoom in and stare at.

**Comment by IrfanH495** [comment]
tomb raider anniversary and tomb raider legend, two different games but have the same picture.
![Screenshot_20230709-232226_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/b02e18c6-0208-4d3f-bda0-c0747c5b6030)
![Screenshot_20230709-232249_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/1adfd4a0-6629-4564-adc2-9c5556ef767b)
