### ISSUE TITLE
Ys: The Ark of Napishtim (EUR) [ULES 00267] Severe flickering and/or twitching of locations/effects/menus

### ISSUE THREAD

**Issue by Jamato-sUn** [hrydgard/ppsspp#16694]
### Game or games this happens in

Ys: The Ark of Napishtim (EUR) [ULES 00267] 

### What area of the game

First we start a new game. After the first boss we can enter the first ruins full of small buglike creatures from the south. In there exists a vertical room, third from the end (from the northern exit, exit on human island), which twitches, flickers and makes HUD disappear as long as there are enemies. Additionally in human town outdoors shop's menu (with healing items) flickers. Second boss attacks flicker too. Sometimes random attack effects cause the same issue. (P.S. Could not try latest GitHub build, my device refuses to install it)

Included save data south of the ruins:
https://www.dropbox.com/s/nwrsd0m0ocfdtq7/Ys%206%20EUR%20SAVEDATA.7z?dl=0

### What happens

![JZ6npQV](https://user-images.githubusercontent.com/6930757/210181301-2e0cbd53-7430-47e2-93e8-1eaff480f427.jpg)
In this image there is no HUD because it was captured mid-twitch.

### What should happen

There should be HUD.

### Platform

Android

### Mobile phone model or graphics card

Xiaomi Mi 9T

### PPSSPP version affected

v1.14.2

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [x] Include logs or screenshots of issue.

**Comment by Jamato-sUn** [comment]
Changing backend to Vulcan does not no help. Rendering resolution is 1 with upscaling to native.
I will re-add savefile here in case dropbox doesn't work.

Also I currently have access to PC which can't even run PPSSPP and 50kb/s internet so I'm not sure how to capture GE Frame. On Android I can't seem to connect.
[Ys 6 EUR SAVEDATA.zip](https://github.com/hrydgard/ppsspp/files/10329312/Ys.6.EUR.SAVEDATA.zip)

**Comment by unknownbrackets** [comment]
With the US version, I'm not seeing any flickering.  Here:
![image](https://user-images.githubusercontent.com/191233/210187009-ae6a5202-6375-4b78-a779-7657e8a86613.png)

Or here:
![image](https://user-images.githubusercontent.com/191233/210187014-aebba136-8edf-4fae-b16d-74ec81389ef9.png)

Or here:
![image](https://user-images.githubusercontent.com/191233/210187029-b8791160-b765-452a-ae1f-e63f7604c3d7.png)

Is that what you meant by the shop?  I also checked some of the rooms but didn't notice anything and wasn't completely sure I was looking at the right room.  It's been a while since I played through this whole game, I mostly just load it up sometimes to make sure DXT decoding isn't broken (since this game uses DXT and not a ton of others do.)

That said, letters are updating weirdly.  For example this very temporarily happens:
![image](https://user-images.githubusercontent.com/191233/210187140-e0c0b1e8-34bd-422b-8a05-7b8f1e7e7536.png)

Is that what you mean by flickering?

-[Unknown]

**Comment by Jamato-sUn** [comment]
That is the correct shop. Letter updating is a separate issue. I meant full screen effects where frame changes to black or to a different frame or to the a frame that's 20 percent off-center. I can try capturing video if necessary.

**Comment by ANR2ME** [comment]
Does older version of PPSSPP worked fine? or it's been like that for a long time on your device?

**Comment by Jamato-sUn** [comment]
Sorry, I don't know. Last time I played Ys 6 it was on my actual PSP. I can try installing a specific version if you tell me a build number. But my phone refused to install latest GitHub build for some reason.

**Comment by Jamato-sUn** [comment]
I figured out how to install the latest GitHub build, that didn't help.

**Comment by Jamato-sUn** [comment]
I'm sorry for wasting your time! I solved it! This was caused by frame skipping value of 1 that I used globally to try and reduce occasional lag in some other game!

**Comment by hrydgard** [comment]
We should probably list games that aren't compatible with frame skipping and warn, similarly to what we do with buffered rendering..
