### ISSUE TITLE
Outrun 2006 - glitches

### ISSUE THREAD

**Issue by Andrew-Twins** [hrydgard/ppsspp#16700]
### Game or games this happens in

Outrun 2006 - PAL

### What area of the game

Bridges, Canyon stage and stages where there are lots of trees as well.

### What happens

Some flickering black or brown diagonal lines appear hindering gameplay.
![Screenshot_20230102-103342](https://user-images.githubusercontent.com/74879798/210188114-c7ad3698-3dab-4e38-812b-0c19f412dde9.png)
![Screenshot_20230102-103309](https://user-images.githubusercontent.com/74879798/210188115-3f01afe5-369d-47a3-9f82-eb1c41b95368.png)

### What should happen

Those lines simply shouldn't appear.

### Platform

Android

### Mobile phone model or graphics card

Retroid Pocket 3+

### PPSSPP version affected

1.14.2

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by Andrew-Twins** [comment]
Same issue appears using Vulkan. "Geometry shader culling" fixes the problem but slows down the game to unplayable level.

**Comment by unknownbrackets** [comment]
Yeah, Mali devices aren't great for these games - maybe it might be possible for a better graphics driver to improve things, because it's almost weird how slow the geometry shader is on some of these devices.

What's happening is that the game relies on how the PSP graphics chip just threw away parts of certain drawing based on a fixed formula.  Modern GPUs don't use the same formula and it causes problems.

On most other GPUs (mainly not Mali), there's a feature where we can basically give the GPU a formula for what parts of drawing to cut away: perfect.  We use this where ever we can, and it makes graphics look better and is nice and fast.

Because Mali GPUs lack this feature, we use a geometry shader instead to rebuild the triangles manually with the parts that shouldn't be drawn thrown away.  This is extra work obviously, but PSP games didn't draw nearly as many triangles as modern games do - so it ought to run well enough.  Unfortunately, for some reason geometry shaders on some Mali devices/drivers run horrifyingly slowly.

I don't know if there's some sort of newer OS or ROM for that device, but I think newer Mali drivers (at least on some devices) fixed the geometry shader performance issues.  They still compile ridiculously slowly (which we've contacted them about), though.  Definitely an "ugly duckling" feature of the driver all around, but we're only using it because it is missing that simpler and more efficient feature...

-[Unknown]

**Comment by Andrew-Twins** [comment]
Issue was present in 1.14.1 .... Sorry, my mistake!!
In 1.14.2 it has been solved. Thanks to the Devs!

**Comment by hrydgard** [comment]
Yeah, the vertex shader culling that we've had for quite a while now solves this well enough, so that's as expected as 1.14.1 accidentally turned that off on Mali.

**Comment by unknownbrackets** [comment]
Oh, okay, so the culling is enough, I thought this needed the clipping too.

-[Unknown]
