### ISSUE TITLE
Crash in GTA, that doesn't happen with an underclock

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#16807]
Sergey on Discord reports a crash that can be avoided by underclocking to 77Mhz.

Note that some plugins are loaded, so the bug could also be in one of those.

Savestates will be below.

**Comment by ThirteenAG** [comment]
It's actually turned out to be a 60 fps issue.
Here's a savestate seconds before supposed crash, only I made it without 60 fps patch:
[PPSSPP_STATE.7z.zip](https://github.com/hrydgard/ppsspp/files/10418805/PPSSPP_STATE.7z.zip)

Steps to reproduce:
1) 1000 cpu clock
2) Load save state 4
3) Go to debugger, make NOP at address 0x08A070C8 (makes the game run at 60 fps)
4) Wait a few seconds until a cutscene starts, emulator will crash

**Comment by hrydgard** [comment]
Alright, so an internal race condition in the game, or something like that, that only happens if you take out the delay. Unfortunate, but something to fix with a more sophisticated 60fps patch, not by changing the emulator, most likely...
