### ISSUE TITLE
Art of Fighting black screen 

### ISSUE THREAD

**Issue by KamiLordus** [hrydgard/ppsspp#16875]
### Game or games this happens in

NPUH-10061 - Art of Fighting

### What area of the game / PPSSPP

The game works fine until players are selected. Then a black screen appears.
After pressing start you can see the menu, players etc. However, upon returning to the game, the screen is black again.
Tried using other DX11, Vulcan, GL display drivers - same error.
The game was working fine (if my memory serves me right with version 14.0-14.2)

![Art_of_Fighting_USA_PSN_PSP-NRP-230131-135451](https://user-images.githubusercontent.com/123302593/215766309-21c1acb5-8cbd-487c-bb5f-d809daf2f740.png)

After pressing start:

![Art_of_Fighting_USA_PSN_PSP-NRP-230131-140206](https://user-images.githubusercontent.com/123302593/215767235-6d3c059f-d676-4ee3-9d19-e7d82a239d41.png)

### What should happen

Correct image display.

### Platform

libretro / Retroarch

### Mobile phone model or graphics card

GTX 1070

### PPSSPP version affected

1.14.4

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [x] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
Does it only happen in retroarch? Not in standalone?

**Comment by KamiLordus** [comment]
I just checked the ppsspp standalone versions and this one works fine. So the problem is only with the liberto RA version.

**Comment by Gamemulatorer** [comment]
I can reproduce this issue on my vivo y11 standalone ppsspp recently build.

**Comment by hrydgard** [comment]
If it indeed reproduces outside of libretro, then we don't need to tag the issue as such, and it becomes easier to debug.

**Comment by hrydgard** [comment]
Good to know by the way that this works in the software renderer, so that's one workaround.

We should obviously fix it though. Looking at the frame dump in PPSSPP, it goes like this:

* Clearing 0x04000000/565. 
* Texturing from 040e6000 and then 040c6000, rendering into 00a8000 /565. Draws some rects, switching CLUTs but sometimes not texture pointer.
* Texturing from 040a8000, drawing into 00000000, but everything ends up black

Very straightforward, strange that it doesn't work. Looking closer in renderdoc, everything seems fine and the last pass is indeed reading from the correct framebuffer, it's just the fragment shader ending up returning black. This might be the result of one of my recent shader ID optimizations - will look into it.

**Comment by hrydgard** [comment]
Ok, this broke in my commit d4ce134292dd8d34250401a6f22ebccc829b0d42 , which moves FS_TEX_ALPHA to a uniform.

**Comment by Gamemulatorer** [comment]
I still got a black screen in KoF series '94, '95 and '96 same game developers as "Art of Fighting" using OpenGL only.

[NPUH10119.zip](https://github.com/hrydgard/ppsspp/files/10574994/NPUH10119.zip)

**Comment by hrydgard** [comment]
Ah my bad, forgot to apply the fix to OpenGL and D3D9, only did the fix for VK/D3D11.

**Comment by KamiLordus** [comment]
Thanks for the fix. I confirm that in RA DX11 and GL mode works correctly :)
