### ISSUE TITLE
The Godfather - subtitles flicker

### ISSUE THREAD

**Issue by MiguelAngel861** [hrydgard/ppsspp#16915]
### Game or games this happens in

ULES00394 - The Godfather

### What area of the game / PPSSPP

When i turn on subtitles and im in a cinematic the screen starts to blink
 [https://youtu.be/zObQEYlBkOA]() 

### What should happen

The screen doesnt blink

### Platform

Android

### Mobile phone model or graphics card

Samsung Galaxy S9+ Snapdragon 845

### PPSSPP version affected

1.14-648-g05f10ce38

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
If it's possible to catch it, a GE frame dump would be useful.  This is a bit like a screenshot (it's basically a 3D screenshot) so you'd want to try a few times to capture the problem.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by GJVBCHJV** [comment]
Chg

**Comment by Gamemulatorer** [comment]
@MiguelAngel861 no feedback/outdated?

**Comment by hrydgard** [comment]
We seem to be suddenly detecting (and resizing) one of the main framebuffers to the wrong size when subtitles are on... Both if you load from savestate. A very subtitle-like height, too.

I'll investigate properly soon.

**Comment by hrydgard** [comment]
When it renders subtitles, it specifies a tiny viewport (480x32), which seems to cause us to resize the framebuffer to that size. Then it just draws letters fairly conventionally with a bunch of rectangles.

![image](https://user-images.githubusercontent.com/130929/232454080-ab4ba09b-c8b2-46a6-9858-89b81194c365.png)

Then it block transfers the text to RAM:

![image](https://user-images.githubusercontent.com/130929/232455111-1b3efffc-40bf-411f-836a-0c45172a6090.png)

After that, I'm not really sure what happens, I guess the rest is just the video getting decoded, and then it puts the text into place with the CPU? not sure.

Either way, it ends up presenting the tiny fb it used to draw text, which is filled with video data at this point.

However what does work, maybe slightly surprisingly, is to simply reject tiny-height framebuffers when choosing what to present. This is the result:

![image](https://user-images.githubusercontent.com/130929/232457310-bd7b2e2c-f954-47bd-97ca-396cbe074370.png)

There still is a problem here, that the text is kinda hard to read, but at least it's there. Not sure how it gets like that...

**Comment by hrydgard** [comment]
Savestate for repro (ppdmp useless in this case): 
[GodfatherSubtitles.zip](https://github.com/hrydgard/ppsspp/files/11249066/GodfatherSubtitles.zip)

**Comment by hrydgard** [comment]
I checked the text on hardware and it looks much better. Like it's drawn with the wrong CLUT or something in the emulator... not sure.

**Comment by hrydgard** [comment]
Hm, when not loading from that savestate, and instead entering the cutscene in game, I get flickery (but otherwise good-looking!) subtitles due to framebuffer size confusion, it seems: 

00:50:295 idle0        W[FRAMEBUF]: Common\FramebufferManagerCommon.cpp:1 Resizing 8888 FBO at 04088000/04110000 stride=512 from 480x272 to 480x272 (force=1, skipCopy=0)

over and over because vfb->newHeight is tiny (and stays tiny) in 

```
needsRecreate = needsRecreate || vfb->newHeight > vfb->bufferHeight || vfb->newHeight * 2 < vfb->bufferHeight;
```

Something with the logic is not right...

**Comment by unknownbrackets** [comment]
Hm, newHeight being lower on its own is "normal".

The problem this code was trying to solve (which I would expect still exists as a problem if it's forcibly unsolved) is that sometimes a game will temporarily use a buffer as a 480x272 buffer, let's say when opening a screen transition, and then later it will start using the same address as a 64x64 buffer for shadows.

If we say "welp, it was once 480x272, so that's its size now and forever" then it's all well and good, until block transfers happen.  And then its size being wrong risks overwriting bad memory or making matching fail and skewing the size, etc.

There is some code that increases the newHeight outside drawing detection, in block transfers.  But that also sets `dstRect.vfb->lastFrameNewSize = gpuStats.numFlips;`.  So the better question is, why is it going inside `} else if (vfb->lastFrameNewSize + FBO_OLD_AGE < gpuStats.numFlips) {`?  Is it really only being rendered to that often?

-[Unknown]

**Comment by unknownbrackets** [comment]
Although I'm not sure why `vfb->width = drawing_width;` isn't ultimately happening before the recreate, maybe that was a victim of some code refactoring?

-[Unknown]

**Comment by hrydgard** [comment]
@unknownbrackets ah, this is why height/width aren't gotten set to drawing_width:

```
			if (params.isModeThrough && (int)vfb->width <= params.fb_stride) {
				vfb->width = std::max((int)vfb->width, drawing_width);
				vfb->height = std::max((int)vfb->height, drawing_height);
```

The std::max function prevents it, so that breaks downsizing of buffers here.

**Comment by unknownbrackets** [comment]
We probably don't shrink often anyway, I remember there was another game where it happened with subtitles.  Not sure if it was through.

I feel like we should do this:
https://github.com/hrydgard/ppsspp/compare/master...unknownbrackets:ppsspp:framebuf-shrink?expand=1

Does that help this subtitle behavior?  It's probably reasonable to only increase size in throughmode, I guess, but if we've consistently seen it smaller for 5 frames, I think we can size down.  We already were if it was a smaller variance than 50% size.

-[Unknown]

**Comment by hrydgard** [comment]
That fixes the subtitles indeed.
