### ISSUE TITLE
Analog stick input is rotated in UCUS98618 Daxter

### ISSUE THREAD

**Issue by kevin98761234** [hrydgard/ppsspp#17015]
### Game or games this happens in

UCUS98618 Daxter

### What area of the game / PPSSPP

As soon as you start the game and can move your character.

On the keyboard, pressing the top of the analog stick presses a small amount of left, pressing the bottom presses a small amount of right, pressing the right presses a small amount of top, and pressing the left presses a small amount of bottom.

This problem does not occur if the in-game setting is set to move with the directional keys.

Settings are defaults. As far as I can tell, 1.12.3 and 1.13.2 have the same problem.

https://streamable.com/goniia

### What should happen

Analog sticks are pressed correctly on the keyboard.

### Platform

Windows

### Mobile phone model or graphics card

NVIDIA GeForce GTX 1660 SUPER

### PPSSPP version affected

v1.14.4-677-ge685dc910

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
Sometimes games skew the camera movement based on your viewpoint.  I don't have this game, but does this happen even with walking?

For example, in Crisis Core, if I walk back and forth using up and down analog from the keyboard, I go straight.  Of course, the camera rotates if I walk near a wall, so if I hold down, my angle will change.  Left and right also don't go "straight" and curve toward the camera.  But this is intentional and how it also works on a PSP.

It would be best to try other games.

Also, does this definitely not happen when using a controller's analog stick?  It only happens when using a keyboard?

-[Unknown]

**Comment by kevin98761234** [comment]
If I press the up direction of the analog stick on the keyboard, it does not walk straight, but moves diagonally to the left. I have included a comparison with moving with the directional keys.

https://streamable.com/hl1pak

**Comment by hrydgard** [comment]
IIRC it's the game doing it, on the real PSP I guess the game developers decided that it felt better with a slight rotation of the analog stick.

I suppose we could have a compat.ini option to rotate the input to correct for it, it would make some sense (but only if this rotation is applied consistently throughout the game - if there are minigames where it's not, those would have the opposite problem). Overall itm ight be better though.

**Comment by hrydgard** [comment]
This is fixed in both Daxter and the GoW games with #17020, closing.
