### ISSUE TITLE
Burnout Dominator rendering errors in Vulkan on PowerVR GE8320

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#17044]
<img width="583" alt="image" src="https://user-images.githubusercontent.com/130929/222589424-1da49b8d-3095-4532-9b3e-c4c39a2c9a8d.png">

Car looks kinda broken in Vulkan, it seems, while OpenGL is fine.

**Comment by hrydgard** [comment]
On my Galaxy A21, it's utterly broken, much more than in the screenshot above. However, that's because DisableAccurateDepth is set for this game. If I remove that, then all is well. Well, I guess it's still unclear why inaccurate depth is so broken here.. but doesn't seem worth digging into.

So then it's mostly a matter of how we change the workings of that compat.ini flag, so it can still fix whatever it was there for before. Gonna have to do some digging for the reason it was flagged, and testing on other devices, then...

**Comment by unknownbrackets** [comment]
I thought the inaccurate depth path (designed really for OpenGL) sometimes sent depth ranges as i.e. [1.0, 0.75] and assumes glDepthRangef() will handle this.  I think for Vulkan/etc. it tries swapping the values since this isn't supported, which obviously won't actually flip the Z output.

So really I'm not sure why we would use non-accurate depth outside GL...

-[Unknown]

**Comment by hrydgard** [comment]
Right. I think this game was added here because of misbehavior on Mali with OpenGL, and the case for just never using inaccurate depth with Vulkan is probably fairly solid..

**Comment by hrydgard** [comment]
OK so it turns out on most GPU models we already ignored the disableaccurate flag with Vulkan, but not IMGTec/PVR. Fixing that.
