### ISSUE TITLE
Ratchet & Clank - strange sound issue during level loads?

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#17125]
Reported by Lazy on Discord.

> I'm having a weird audio issue when playing ratchet and clank size matters. there's like weird loud buzzing noises and it happens basically whenever I start loading or stop loading a scene. like when going between plants. I tried to disable audio reverb since it's been causing me issues in the past but that hasn't helped. I'm on 1.14.4 of ppsspp

> it's the european version of the game, played on pc. I'm not entirely sure what triggers it. I'm on a new save made on ppsspp where I've played through the first two planets and a race on the third planet. the issue seems to happen when I load a new area for the very first time. for example when I first travel to a new planet the audio will glitch in the flight loading screen and sometimes also in the very beginning of the stage. it'll then go away after a little bit

https://user-images.githubusercontent.com/130929/225312930-ed4b0944-b22a-4b6d-a21e-ac0acfd9673e.mp4

**Comment by LazyDkk** [comment]
I've done some testing on the audio bug and primarily tested its occurrence on the second planet in the game. The audio bug in question is usually distinguished by a loud buzzing noise and similar audio glitches. From my understanding this bug occurs whenever the second planet and the third planet is loaded on a save for the very first time. I have not been able to reproduce it by going back to the planets in a further progressed save. I also have not noticed it on any planets past planet 3 but I've not done extensive testing on this. The audio bug also sometimes happen during the spaceship loading screen.

It is possible to make a save state before the cutscene on the second planet ends and every time you load it you will hear the same audio bug. Since the bug only happens the first time the planets are loaded they could be in correlation with the cutscene that plays the very first time you visit the planets. Be mindful that the audio bug won't allows be same. Sometimes it goes away after few seconds and others it won't go away and will stay around. I haven't tested for how long unfortunately but a decent portion into the first half of the second planet up around till you collect the Sprout-O-Matic (the watering can looking item). The bug seems to be consistent with the save you're on. So on one save it'll sound in one way and on a different save it'll sound another. So if you can't quite hear the audio bug then try and create a new save and then use the save state to jump to the second planet and it should now sound different and sometimes more distinct.

From my testing I can conclude that the audio bug is related to the in-game Effects Volume. turning this volume down will lower the volume of the buzzing and turning it all the way down will make it inaudible. But of course turning the volume back up will also turn up the volume of the buzzing and make it reappear. The Music Volume does not seem to have any effect on the bug.

To reproduce/experience the bug you need to create a new save file, beat the first planet and then travel to the second planet. Sometimes you will hear the audio bug in the spaceship loading scene but this appears to be rare. After the planet 2 cutscene the audio bug buzzing should be noticeable. Making a save state during the planet 2 cutscene ensures you can always go back to the moment before the audio bug occurs. As mentioned, creating another save and going to the same save state before the cutscene ends will often yield a different audio bug in terms of loudness and length of the audio bug.

I'll include my four savefiles I've used during testing. The first is a save further into the game mainly to test returning to the previous planets. The second was saved on the second planet and won't have the audio bug when loaded up but will have the bug if a save state from the second planet cutscene is loaded. The third and fourth are both saves from the first planet and were mostly to test loading the planet 2 cutscene save state on new save files and confirm that the audio bug happens and also notice that it differs from save to save. Interestingly enough I also noticed the audio bug would sometimes happen when going between my planet 2 save and my planet 1 save but I was not able to reproduce this consistently.
Unfortunately due to upload limits I couldn't contain all 4 save states in a single zip file.

[UCES00420DATA - Save Files.zip](https://github.com/hrydgard/ppsspp/files/11066672/UCES00420DATA.-.Save.Files.zip)
[SaveState1.zip](https://github.com/hrydgard/ppsspp/files/11066691/SaveState1.zip)
[SaveState2.zip](https://github.com/hrydgard/ppsspp/files/11066697/SaveState2.zip)
[SaveState3.zip](https://github.com/hrydgard/ppsspp/files/11066701/SaveState3.zip)
[SaveState4.zip](https://github.com/hrydgard/ppsspp/files/11066707/SaveState4.zip)

Another example of the audio bug (Volume warning)
https://user-images.githubusercontent.com/29303860/227646956-534e0bd5-634f-4ddb-8353-c44cb03a7d25.mp4

**Comment by unknownbrackets** [comment]
Interesting, that's helpful information.

I've never played this game myself, but does a video play every time you visit a planet?  Is there anything that only happens the first time you visit it within a given save?

I'm just wondering if, perhaps, a video is ending a bit early and leaving some non-silence audio data in a buffer, or something.  I suppose that wouldn't correlate with it differing per save, but being consistent within a save.  Another possibility is that something (like loading a save with a larger buffer?) should be zeroing out memory, and isn't.

It would be very interesting and helpful to check:
 * Does a save from a PSP (where the planet has not been visited yet) still cause this issue on PPSSPP, or does it never happen from PSP saves?
 * Does a save where it happens in PPSSPP cause the issue on a PSP, or does it never happen on a PSP for any save?

-[Unknown]

**Comment by LazyDkk** [comment]
> Interesting, that's helpful information.
> 
> I've never played this game myself, but does a video play every time you visit a planet? Is there anything that only happens the first time you visit it within a given save?
> 
> I'm just wondering if, perhaps, a video is ending a bit early and leaving some non-silence audio data in a buffer, or something. I suppose that wouldn't correlate with it differing per save, but being consistent within a save. Another possibility is that something (like loading a save with a larger buffer?) should be zeroing out memory, and isn't.
> 
> It would be very interesting and helpful to check:
> 
> * Does a save from a PSP (where the planet has not been visited yet) still cause this issue on PPSSPP, or does it never happen from PSP saves?
> * Does a save where it happens in PPSSPP cause the issue on a PSP, or does it never happen on a PSP for any save?
> 
> -[Unknown]

I have now tested this and as I expected the audio bug does not occur at all on a physical PSP. Neither with physical PSP saves or with a PPSSPP saves. I did try to create a save on my physical PSP and transfer it to PPSSPP. Loading any of the save states listed in the post I can immediately hear the audio bug after the planet 2 cutscene has ended. The audio bug did however sound a bit similar to another save. I did try to test briefly if it was linked to the progress of a save but I couldn't find an immediately correlation. So I can't fully confirm or deny if the bug is linked to new saves, the progress of a save or something else. But the bug does occur on the PPSSPP regardless of whether it was created by a physical PSP or PPSSPP but also regardless of the process on the save. At most the progress might effect the variation of the bug but it is still present.

**Comment by hrydgard** [comment]
Hm, I'm wondering if #18075 , which fixed #14010, might have also fixed this.

**Comment by LazyFace32** [comment]
Yes, I believe you may be correct. I went through and checked the saves and save states that I originally provided in this thread and tried to reproduce the same steps to trigger the audio glitch but so far everything seems to be functioning as intended. I was not able to make the audio glitch appear on any of the saves or save states except for SaveState3.zip (which apparently seems to actually be save state slot 4 in the emulator. Probably a mistake on my part when naming the files). But that save state was made while the audio glitch was active and not prior to it being triggered. So it is likely that the game was already in a glitched state when the save state was made so loading the save state would only return the game to that glitched state.

With that I believe I can conclude that the audio glitch has most likely been fixed. I went through the same locations trying to replicate the same circumstances as originally detailed in this thread but the audio glitch did not appear in any of the locations I expected it to. So I believe it has indeed been fixed.

**Comment by hrydgard** [comment]
Great! Thank you for testing and reporting!
