### ISSUE TITLE
Rendering glitch in Lego Harry Potter Y1-4

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#17242]
Reported by `perhaps` on Discord.

Game: Lego Harry Potter Y1-4

Device: Galaxy A21, Vulkan

Tested on 1.14.4 and latest build.

![SmartSelect_20230404-210337_PPSSPP](https://user-images.githubusercontent.com/130929/230220499-39c2040b-b20b-4237-8f1f-76736f78d8bd.gif)

Nearby save:

[ULUS10500DATA00.zip](https://github.com/hrydgard/ppsspp/files/11163399/ULUS10500DATA00.zip)

Occurs in the Chamber of Secrets (2nd door), quest Collecting Ingredients

**Comment by unknownbrackets** [comment]
A GE frame dump would be more helpful.  Might be some kind of Z fighting...

-[Unknown]

**Comment by mayhaps3500** [comment]
First time creating a dump. Let me know if I've done something wrong.

[ULUS10500_0003.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/11167017/ULUS10500_0003.ppdmp.zip)

**Comment by unknownbrackets** [comment]
Even in a PSP playback of that framedump, something funny is happening:
![#17242_ULUS10500_lego_harry_potter_scrambling](https://user-images.githubusercontent.com/191233/230729157-57320b47-11da-431b-9244-904d3d031a3e.png)

The scene initially is drawn like this, which looks nice and all (2382/4468):
![Brighter scene without artifacting](https://user-images.githubusercontent.com/191233/230729384-55aff33a-9b97-440e-98f2-855230bb7812.png)

But it then darkens everything one by one (4425/4468) and that's when we've gotten the artifact:
![Darker](https://user-images.githubusercontent.com/191233/230729472-a1c780a0-b04a-4b13-867a-fa575213fb42.png)

The initial darkening of that specific area occurs at 3414/4468.  This actually looks more or less right to me:
![After initial darkening](https://user-images.githubusercontent.com/191233/230729583-2c99e751-1519-4f18-9058-50b3c6dec2c3.png)

But then it touches the same area again at 3437/4468 and 3438/4468, which makes it nearly black and gives it that weird pattern.  To confirm, skipping those two draws makes it look as one would expect:

![Scene without strange artifacting](https://user-images.githubusercontent.com/191233/230729781-47609543-6477-4ae6-9564-3cdebf77261c.png)

The first darkening is a simple triangle strip, made up of two triangles:
| X | Y | Z |
|--------|--------|--------|
| 290.119141 | 19.013916 | 2996.390625 |
| 279.134521 | 61.373779 | 2979.410156 |
| 243.680420 | 24.455322 | 3011.021484 |

| X | Y | Z |
|--------|--------|--------|
| 279.134521 | 61.373779 | 2979.410156 |
| 243.680420 | 24.455322 | 3011.021484 |
| 231.450928 | 65.311646 | 2994.353516 |


The second two draws are one triangle each with:
| X | Y | Z |
|--------|--------|--------|
| 231.450928 | 65.311646 | 2994.353516 |
| 290.119141 | 19.013916 | 2996.390625 |
| 279.134521 | 61.373779 | 2979.410156 |

| X | Y | Z |
|--------|--------|--------|
| 243.680420 | 24.455322 | 3011.021484 |
| 290.119141 | 19.013916 | 2996.390625 |
| 231.450928 | 65.311646 | 2994.353516 |

While these are technically the same points, the triangle is drawn in a different order (first is TR BR TL, BR TL BL, second is BL TR BR, TL TR BL.)  This is done as well with a >= depth test, and I think the depth ends up being slightly different because of the order.

And just to confirm, I tried quickly stripping these two triangles out and running on a PSP, which does look good:
![#17242_ULUS10500_lego_harry_potter_scrambling_edit](https://user-images.githubusercontent.com/191233/230730760-8a2a42a2-a85d-4dd8-b7b2-1959f6dde894.png)

It might be there's some CPU emulation bug causing the game to do these extra triangles, but to me this looks like a game bug.

-[Unknown]

**Comment by hrydgard** [comment]
Interesting. If it's indeed a game bug like tha, but the Z fighting glitches just look a bit different than on the real PSP, yeah, there's probably not much worth doing here...

**Comment by hrydgard** [comment]
Somewhat oddly, neither pixel nor vertex depth rounding does anything to improve the look of it on PowerVR, and it does look weirdly worse there. Still, I don't see that we have any good options here, and given that it also does appear to be a game bug, I'm going to close this.
