### ISSUE TITLE
Syphon Filter: Logan's Shadow (US & EUR) Menu's Wrong Colors

### ISSUE THREAD

**Issue by LeyoSFO** [hrydgard/ppsspp#17373]
### Game or games this happens in

UCUS98606 & UCES00710

### What area of the game

Main menu

### What happens

When entering a mission then quitting said mission and going back to the menus, the menu looks like this in the screenshots
![image](https://user-images.githubusercontent.com/71053461/235447156-3d53d87e-d723-44a3-9054-15c922556ac3.png)
![image (1)](https://user-images.githubusercontent.com/71053461/235447160-45022d15-4b79-40c7-8e52-e31661821bdf.png)

### What should happen

the menu's colors should not look in the wrong colors after quitting a mission

### Platform

Windows

### Mobile phone model or graphics card

NVIDIA 2070 Super

### PPSSPP version affected

v1.15

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [x] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
This is a LoadCLUT issue (where we load a palette from a framebuffer). Doesn't persist after a save/reload state, so it seems we end up reading a palette from a framebuffer that contains outdated data, maybe due to sticking around from a previous frame while in reality the game has replaced that memory with the correct data. Checking for changes in the memory area covered by framebuffers might be necessary to fix this. 

Alternatively, maybe if we ignore LoadCLUT from framebuffers not modified during the current frame...

**Comment by hrydgard** [comment]
I'm going to add a compat flag for now, that rejects LoadCLUT from stuff rendered during previous frames.

I don't think it's that common though that we need LoadCLUT from framebuffers from old frames, so perhaps we should eventually invert it, and make it the default - risk seems fairly high to erroneously load CLUTs from outdated framebuffers lingering around. I'll do that after the release though.
