### ISSUE TITLE
libretro: Performance Issues in Vulkan driver

### ISSUE THREAD

**Issue by ToniBC** [hrydgard/ppsspp#17469]
### Game or games this happens in

Mega Man Maverick Hunter X and others

### What area of the game

It affects all or almost all games, the game stays at 40 fps when it goes to 60 fps in standalone and fluidity problems are observed. If the FPS limit is disabled, these do not increase.

### Speed seen in PPSSPP

40 fps

### Platform

libretro / Retroarch

### Mobile phone model or graphics card

RTX 3070

### PPSSPP version affected

1.15.3.26

### Graphics backend (3D API)

Vulkan

### Any other notes or things you've tried

If the GL driver is used, everything works fine, but when switching to Vulkan, for some reason, the game performance drops.

I have tried resetting the options, everything by default, native resolution and nothing, the same problem.

I know that this version is not a priority, but it is one of the most used in consoles or systems like Batocera.

Thank you.

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the slowdown.
- [ ] Include logs or screenshots of issue.

**Comment by bslenul** [comment]
Confirmed with Mega Man Powered Up, it feels very unpleasant to play. Bisected to 42ce6197053ad0728ed32ce6107b17c0b80d6488

**Comment by bslenul** [comment]
Messed a bit with this, so previously `fastForwardSkipFlip` was always false because this if statement was never executed because with the Libretro core `g_Config.bVSync` is false: https://github.com/hrydgard/ppsspp/blob/2d2f23bd6c7a8fcc25b6677965efe23c71bf9e8b/Core/HLE/sceDisplay.cpp#L548-L552

Now `fastForwardSkipFlip` is always true with the new if statement because `fifo` is true: https://github.com/hrydgard/ppsspp/blob/12106ceb7537350ba61a2a8085cccdcec8f7bb04/Core/HLE/sceDisplay.cpp#L548-L556

And yeah, if I skip that if statement with a `#ifndef __LIBRETRO__` Mega Man runs properly at 60fps again.

I don't understand the code and what it does well enough to pretend this is a proper fix, far from it :p Just saying why it started to behave like this with this commit. I wish I had the skills to fix at least some of these Libretro issues... 😓

**Comment by unknownbrackets** [comment]
At least at one point, libretro was forcing fast forward always to do its own timing (although maybe that's a lie, and it just relies on flip timing, so is dependent on device refresh rate?)  Although maybe it ends up in the else here:
https://github.com/hrydgard/ppsspp/blob/f2919598fb083fc44159e12d5588ce4021f4ff22/Common/GPU/Vulkan/thin3d_vulkan.cpp#L407

Anyway, I suppose ifdefing this out would probably be reasonable.  Not sure if that interferes with the ability to fast forward through libretro?

-[Unknown]

**Comment by bslenul** [comment]
> Although maybe it ends up in the else here

Just checked, it properly returns `PresentationMode::FIFO` on the first case, not the default.

> Not sure if that interferes with the ability to fast forward

Fast forward still works fine with the ifdef. At least on PC, haven't tried any other device.

I know you don't really care about the Libretro core so it's very nice of you to take some time to reply, thank you! :+1:

**Comment by bslenul** [comment]
Fixed for me btw since #17687 :+1: @ToniBC could you please test again and confirm if it's fixed on your side as well?

**Comment by ToniBC** [comment]
Yes, it seems to work fine now, I've tested it and it stays at 60fps. So we'll consider it solved.

Thank you so much.
