### ISSUE TITLE
Choose SAVEDATA folder with UI/CLI setting

### ISSUE THREAD

**Issue by nottanumber** [hrydgard/ppsspp#17472]
### What should happen

Hi team! I want to sync my PSP save data between my PC and my laptop using a shared network drive or cloud storage, which seems tricky as is.

Today I can change the `memstick` directory with custom directory in `installed.txt` on my PC. That is great but also carries over all parts, including configuration in `SYSTEM` for one PPSSPP setup. It does not make sense for my PC and laptop to point their memstick folder to the same data.

What I like is ability to target specific folder of my choosing for just SAVEDATA portion, which would allow me more control over how to sync, share, and target the save folders between systems.

### Who would this benefit

Windows/Linux users with the ability a shared folder between systems

### Platform (if relevant)

Linux / BSD

### Games this would be useful in

n/a

### Other emulators or software with a similar feature

mesen / ares allow specifying a specific save folder

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by unknownbrackets** [comment]
This is complicated for a lot of reasons.  Although PSP games use an API to create save data, they aren't so well behaved when it comes to reading savedata.

For example, games may manually list the contents of the memory stick to find the savedata.  There's lots of tricky situations that get in the way, and they expect the free space on the general memory stick to match the free space within SAVEDATA.  This is complicated further by how some games manage DLC - which again, is just whatever the game decides to do.

Since you listed platform as Linux, I'll say that on Linux I would just solve this using a bind mount.  Most of the tricky to solve things are actually already handled by Linux.  It supports overlaying directories, so you could use a different `PSP` folder for each, but bind mount in a shared `SAVEDATA` folder under `PSP/SAVEDATA`.

If you're actually on Windows, Windows does actually support folder mounts for file shares, although you just have to use junctioning or similar.  I'd expect this to work, but haven't tried it, and it might not transparently handle all the tricky things some games do... but might work for most.

https://superuser.com/questions/244562/how-do-i-mount-a-network-drive-to-a-folder

-[Unknown]

**Comment by nottanumber** [comment]
👍 thanks! I can confirm that symlinking the `SAVEDATA` and `PPSSPP_STATE` folders to the network drives did solve my problem
