### ISSUE TITLE
Errors and crashes when trying to run certain emulators

### ISSUE THREAD

**Issue by bsauvage1** [hrydgard/ppsspp#1775]
All of them in the dropbox link below. (taken from the post that deals with working homebrew emus)
https://www.dropbox.com/sh/x5ck8l3gxrw3ymm/McsE78ovd4

1/ CastAway: crashes on open iOS
2/ DaedalusX64: same problem
3/ UAE4Allr1: on iOS: starts, can get the game to load but no picture (seems common problem) and extremely slow =>unplayable

**Comment by unknownbrackets** [comment]
I think a lot of these problems have been improved over the years, and other issues that were iOS specific have been closed and replaced with other iOS specific issues that are already open.  As such, I'm going to close this - hopefully it's fixed.

If it's still happening, feel free to comment with more info about the current situation and we can reopen.

That said, running an emulator inside an emulator is always going to maximize bugs, so if there are any direct emulators available, that might be best.  iOS also isn't well supported by PPSSPP, due to Apple restrictions.  There are hard to fix bugs in PPSSPP's iOS version (mainly the hang on exit thing or lack of jit in some iOS versions.)

-[Unknown]
