### ISSUE TITLE
Simulate block transfer effects missing from Android release 1.5.x

### ISSUE THREAD

**Issue by adibis** [hrydgard/ppsspp#17818]
### What should happen

The option existed a few versions ago, not sure when it disappeared.

### Who would this benefit

Many games that run well with this option checked. Tactics ogre for example.

### Platform (if relevant)

Android

### Games this would be useful in

Tactics ogre 

### Other emulators or software with a similar feature

Older version of ppsspp

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
The important part of it still exists, we've just reorganized things so that options that may cause graphical problems are grouped together in the UI.

It's now known as Skip GPU Readbacks, and you check it now instead of unchecking it.

(All block transfers other than readbacks are now enabled always, since they always perform well, unlike the GPU readbacks).

**Comment by adibis** [comment]
Ah, yeah marking that fixes the menu audio stutter in Tactics Ogre. Thanks!
