### ISSUE TITLE
Android scoped storage: Misbehaviors during first boot

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#17923]
For some reason, on the first boot, after creating/choosing the new PSP directory, the dirs like PPSSPP_STATE, TEXTURES etc don't get created, they're only created on the second boot.

Also, it seems we default to OpenGL for some reason, and vsync off, which doesn't make sense. Not really sure what's going on, but it needs fixing.

**Comment by basharast** [comment]
**Regarding to creating directories:**
I'm not sure if this same issue in UWP too, since every platform don't have same initial process I guess, 
but I recently solved this by forcing `InitSysDirectories(force)` to create folders when memStick changed (on confirm, before move)
the `InitSysDirectories()` at [this line](https://github.com/hrydgard/ppsspp/blob/2c4657175a96204822ae6184612651dabae67730/Core/System.cpp#L712) is set to `return` if memStick location is not empty.
which is not empty after choosing new location in UWP case.

**Comment by hrydgard** [comment]
I've cleaned this up a bit in #17928 , and fixed the folder creation in 6a0c8a8 . Closing.
