### ISSUE TITLE
Metal Gear Acid 1 and 2 cannot use the link battle option

### ISSUE THREAD

**Issue by NirYeF** [hrydgard/ppsspp#17946]
### Game or games this happens in

Metal Gear Acid,Metal Gear Acid 2

### What area of the game / PPSSPP

When you try to play the link battle option the game disconnects and an error is given.
Done locally on a single computer by using the "localhost" option.
I Played the game using a PC with Windows 10
As I understand the game worked before but now it no longer works.

### What should happen

Game should work without any issues using the link battle option.

### Platform

Windows

### Mobile phone model or graphics card

Intel card

### PPSSPP version affected

1.15.4

### Last working version

possibly before/after PPSSPP version 1.10.3

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
Could you provide a step-by-step to guide me how to link Metal Gear Acid ? because i couldn't find anything mentioning linking/multiplayer from start menu

in case the link option need to be unlocked first, may be you can also provide your save data along with the guide.

**Comment by NirYeF** [comment]
> Collaborator

Yeah sure, to unlock the link battle option for Acid 1 you will need to clear stage 6.
There is a savefile you could use instead if you dont feel like it , I got it from GameFAQs:
https://gamefaqs.gamespot.com/psp/920776-metal-gear-acid/saves/8725

Then , you will to load the game and in the bottom you would find Options - it should  be there.

**Comment by ANR2ME** [comment]
The game seems to use NetConfig dialog and somehow it failed to connect the group due to "Busy" state (0x80410b10)
![image](https://github.com/hrydgard/ppsspp/assets/7974720/56e961f8-35ac-47fb-80e3-aa42b97ecdff)
May be it haven't fully reset the state after `sceNetAdhocctlDisconnect`, might have something to do with delayed state change and the game calling `sceNetAdhocctlConnect` too soon after `sceNetAdhocctlDisconnect`

**Comment by ANR2ME** [comment]
Okay, found the problem at `NetAdhocctl_Disconnect` function, when it successfully sent the disconnect packet on the first try it only use `notifyAdhocctlHandlers` (where the busy state is reset to false) when there is at least an adhocctl handler (ie. `adhocctlHandlers` is not empty), but apparently this game never use `sceNetAdhocctlAddHandler` to register a handler (or may be it supposed to be done internally within NetConf Dialog since the game is using such utility to do networking).

I also feel there is a potential similar issue when it failed to send a packet to AdhocServer, where the flow goes to scheduledEvent for a retry while preventing sceNetAdhocctl* from returning before the packet successfully sent or a timeout reached.
Apparently there is no `notifyAdhocctlHandlers` being called from within the sceduledEvent after the rety was successfull. (or may be because it's 3AM where my eyes and mind can't focus and it's been months since the last time i saw PPSSPP source code and kinda forgot how the flow goes, thus need to check carefully all sceNetAdhocctl codes that suppose to use `notifyAdhocctlHandlers` after a rety was successful later when my mind is clearer)

**Comment by ANR2ME** [comment]
@NirYeF Please test the artifact from https://github.com/hrydgard/ppsspp/pull/17947 later to see whether it fixes Metal Gear Acid 2 too or not, as i only tested this on 1

**Comment by Pik-a-boo** [comment]
> @NirYeF Please test the artifact from #17947 later to see whether it fixes Metal Gear Acid 2 too or not, as i only tested this on 1

OK both games work now! well done.

**Comment by NirYeF** [comment]
I will close it as both of the games work now
