### ISSUE TITLE
To resolve conflicting signature 

### ISSUE THREAD

**Issue by leoxxx** [hrydgard/ppsspp#17963]
### What should happen

PPSSPP release and  buildbot release have conflicting signature error. But PPSSPP and PPSSPP Gold no this error.
So I think need change buildbot package name to resolve it.

### Who would this benefit

User.

### Platform (if relevant)

None

### Games this would be useful in

none

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by hrydgard** [comment]
While this would be nice, there are two obstacles to this:

* We currently use a separate upload key and then a Google-generated app signing key on Google Play (see https://support.google.com/googleplay/android-developer/answer/9842756?hl=en). I do not have access to the real key and would have to switch it to a known one, which can only be done once per year (not really an issue though) but may also cause problems with installs and upgrades on older devices, and also makes it even more critical that I keep that key secure which is extra effort.

* I would have to set my up my own buildbot, since while I trust Orphis in a lot of ways, I don't trust him with my app signing key. And setting up my own is a bunch of work that's just not a priority for me right now.

So in practice, this won't happen anytime soon.
