### ISSUE TITLE
Adding additional Resolution Choices to benefit lower spec platforms:)

### ISSUE THREAD

**Issue by KMFDManic** [hrydgard/ppsspp#18058]
### What should happen

Currently, lower spec platforms are quite limited in what they can pull off with speed and performance, with the primary choices of using 1X PSP at 480x272, 2X PSP at 960x544.  I wouldn't necessarily expect this to make it into official commits, especially if it conflicts with other upscale settings already in place.  But, it would be quite nice to at least know the recommended course of action to, at a minimum (if this isn't an important consideration for mainline), get this implemented into my own build/fork.  Something akin (take this with a grain of salt, since the scaling isn't exact!) to:

- .5x psp   = 320 x 240
- 1x psp    = 480 x 272
- 1.5x psp = 640 x 360 
- 2x psp    = 960 x 544
- 2.5x psp = 1280 x 720
- 3x psp    = 1440 x 816
- 4x psp    = 1920 x 1088
- 5x psp    = 2400 x 1360

Thanks for your perusal, as well as thank you in advance for any response to this change which could/should benefit those of us who don't have mid-range+ android/PCs to most optimally enjoy 3x, 4x, and on perimeters!

### Who would this benefit

More or less, it would be a very nice thing to at least know what needs done:)  Theoretically 640 x 360 and 640 x 480 should give a nominal enough boost to help those on Pi2/3/4, and similar platforms, to have better performance/speed, and still look nice, without having to resort to frameskipping!

### Platform (if relevant)

libretro / Retroarch

### Games this would be useful in

3D games, such as Burnout Legends, Outrun Coast to Coast

### Other emulators or software with a similar feature

A majority of other Emulators/Cores already use resolutions, such as 320x240, 640x360, 640x480, 1280x720, with already quite admirable and agreeable results.  It can be a night and day difference between one resolution to the next, and vice versa!  

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by ANR2ME** [comment]
Are these "majority of other Emulators/Cores" have a native resolution of 320x240 (or close by) may be?

**Comment by hrydgard** [comment]
The reason only even multiples are used is to minimize artifacts from rendering at the "wrong" resolution. There are a few games that will not even reasonably work at non-even multiples, like the Tantalus ones with their wacky color hacks (though they already have problems at resultions other than 1x...) and the depth buffer scaling trickery in Ratchet & Clank.

It would though of course be technically possible to enable other resolutions, I can especially see a case for 1.5x and 2.5x to better hit "sweet spots" of older hardware, but they would have a new set of compatibility issues, with all the problems and error reporting that will result in.

So far on this tradeoff I've come down on the side of "even multiples are fine, just go down one and live with a bit lower resolution", instead of taking on a new set of reported problems etc.

**Comment by unknownbrackets** [comment]
0.5x PSP would be 240x136.  The resolution of the NES was 256x224, so that'd be less than the NES resolution.  GBA was 240x160, so it'd even be less than the GBA too.

There's also a factor of decreasing benefits when it comes to lower resolutions (because fixed costs start to become the dominant costs.)  Yes, 0.5x PSP would take 25% the fillrate effort from your GPU - but at that point, it's probably the rasterization and number of triangles that are the problem.  I'm not sure you'd get the experience you're dreaming of from 0.5x PSP.  It'd probably only be slightly faster or possibly even not noticeably faster at all.

-[Unknown]

**Comment by KMFDManic** [comment]
@ANR2ME I never used the word "Native" in describing what I was going for here.  The entire post is about "Additional Resolutions".  I apologize for any confusion regarding my intent.   

@unknownbrackets I have actually communicated with you in the past on a couple thing:)  Nice to see you pop in again.  More or less, I would love to at least be able to "Experimentally" try out this conceptual idea.  320x240 was just a low end number example.  But, 640x360, 640x480, 1280x720, would all be quite nice to comparatively try out on my end.  I know games like Midnight Club 3, Outrun Coast to Coast would surely benefit.

@hrydgard I have also chatted with you in the past, initially, when we were getting PPSSPP up and running on the very low spec SNES Classic Mini:)  Your insight (memory usage, too long to exit games - ended up being related to save states and not enough RAM once myself and another debugged things [we solved by bash scripting saves to strictly work "externally from usb storage/adding ZRam) went a long way in helping with obstacles there.  I primarily opened this feature request to see thoughts on whether this could be considered for mainline, or if you or other devs who commit to this Repo could at least point me in the right direction, within the code base, of what I "should" change to test the altered perimeters.  I feel, based on past experience with utilizing different resolutions on quite a few other emulators/cores, that there is some solid benefits to "lower spec" hardware, which is oftentimes overlooked.  

That being said, I would absolutely love to execute this idea, and see how it plays out.  So, thanks in advance for any and all feedback and replies to this.  I try to think outside the box when working with different emulators.  And, sometimes it works out in grand fashion.  So, thanks again for your time!

**Comment by hrydgard** [comment]
If you want to just mess around, follow g_Config.iInternalResolution around the code and see where it's used (FramebufferManagerCommon::NotifyRenderResized might be a good place to hack). We currently simply store the resolution as an integer factor, so that would have to change too.

**Comment by KMFDManic** [comment]
@hrydgard I greatly appreciate your response, and did a peek into some of the locations relative to g_Config.iInternalResolution  It seems reasonable enough to be able to get a specific resolution, if I wanted to.  But, without doing more digging into the code, I am not exactly sure which way the exact resolutions currently implemented trigger. It would seem it may be possible to utilize this portion of EmuScreen.cpp to specify different resolution perimeters.  Seeing the origin of where and how the integers were initially coded in would have been beautiful.  That is where looking more into the code would benefit, surely.  It has probably been awhile since youve even bothered with worrying about resolutions!

	if (g_Config.iInternalResolution == 0) {
		coreParam.renderWidth = g_display.pixel_xres;
		coreParam.renderHeight = g_display.pixel_yres;
	} else {
		if (g_Config.iInternalResolution < 0)
			g_Config.iInternalResolution = 1;
		coreParam.renderWidth = 480 * g_Config.iInternalResolution;
		coreParam.renderHeight = 272 * g_Config.iInternalResolution;
	}
	coreParam.pixelWidth = g_display.pixel_xres;
	coreParam.pixelHeight = g_display.pixel_yres;

Again, I thank you for your time.  I realize it can be hectic trying to keep up with the sheer amount of feedback regarding this amazing Core!

**Comment by LunaMoo** [comment]
In the code below

````
	coreParam.renderWidth = 480 * g_Config.iInternalResolution;
	coreParam.renderHeight = 272 * g_Config.iInternalResolution;
````

g_Config.iInternalResolution is integer multiplier, if you change that parameter to floating point you can achieve different resolutions, but again this will cause extra glitches and overally worse graphics, it's similar to frameskipping, it's better to have even 30 fps than uneven 45 fps.

**Comment by KMFDManic** [comment]
@LunaMoo hey, thanks for your response.  I did already try this perimeter to achieve 480p and 720p successfully.  What I was hoping for, however, was having it "else" coded, so that I could pull from it for core options and libretro.cpp implementation, and more easily select different variable resolutions from retroarch settings, close content, restart content to see the changes and verify presence of stability/instability:) Thanks again!

I was able to

**Comment by LunaMoo** [comment]
Don't understand what you're trying to do which would be different from what you were told already.


"g_Config.iInternalResolution" is just a configurable variable of integer type, you can change that int variable to a float variable or add new one or even change the hardcoded PSP res to a variable and also change UI part to have it selectable from UI. For example in my build instead of using selection from 1 to 10 I have a slider from 1 to 32, just look for a floating point slider which is already used for some other setting and take it as an example how to add yours, for example a slider from 0.5 to 4.0 with an increment of 0.25 or even smaller.

 Just take note that resolutions which you noted in opening post are totally wrong and not related to PSP at all, for example 320 x 240 is 4:3 ratio and not even close to 0.5x PSP. If you want to change screen ratio, it would be much better to do by post process effect instead of enforcing rendering res to totaly wrong ones. I think I even posted such configurable aspect ratio shader in the past on the forums.

**Comment by ANR2ME** [comment]
With post processing everything will still be rendered at normal (1x or higher) resolution isn't? 
And most of the time post processing made low end devices performs slower.

What he/she tried to do seems to be to make the game renders to a smaller internal resolution (less than 1x) to gain more performance.

**Comment by LunaMoo** [comment]
Yeah, just pointed out that those resolutions were unrelated to any PSP multiplier floating point or not and changing aspect ratio to achieve them is far better via shader than any other way.

 At very low res as Unknown pointed out, benefits of going lower are small to none since pixel fillrate isn't large part of the performance cost anymore while quality at the same time takes the biggest hit.
 Assuming games that doesn't get artifacts from it probably the only useful in-between render res could be something like x1.5 as it would be much less demanding than x2 while still providing a bit of quality boost at least in games it doesn't break. 0.5 just feels wrong on many levels of ugliness.

**Comment by KMFDManic** [comment]
@hrydgard @unknownbrackets @LunaMoo @ANR2ME With a nice collaboration, was able to pull off exactly what I wanted to.  Ability to run alternate resolutions, so that things still looked nice, but frameskip was no longer needed:)

Test Video with one of the new Alt Resolutions, no frameskip.  I was never able to run this previously without resorting to frameskipping.  It was one of the more stubborn PSP games to encounter:)  Thanks again!  The integer to floating point, hacking the values of g_Config.iInternalResolution in the necessary locations achieved the results I was hoping for.  Additionally, Wipeout Pulse no longer lag freezes for me.  It did at 544p.  But, .25 scaled resolution down (840x476), no longer does:  

**Outrun Coast to Coast on crappy specs with no frameskip on alt resolution 840x476**

https://www.youtube.com/watch?v=fRjLEvk1Hw0
