### ISSUE TITLE
Bring Ctrl-W, etc., to Linux

### ISSUE THREAD

**Issue by fp64** [hrydgard/ppsspp#18052]
### What should happen

Ctrl-W was introduced in https://github.com/hrydgard/ppsspp/pull/2723, but only on windows, and brought under "Enable standard shortcut keys" in https://github.com/hrydgard/ppsspp/pull/14229.
The ability to Ctrl-W the game away is convenient on its own, so I'd like to have that on Linux out of the box (and Ctrl-B too), even without most of the "Enable standard shortcut keys" stuff.

A hacky implementation, of basically copying
https://github.com/hrydgard/ppsspp/blob/a0b89b179a65bfb4b6cfd405bee15d2a0305813c/Windows/MainWindowMenu.cpp#L483-L495
to SDLMain.cpp, and commenting out `Core_WaitInactive();` (which freezes) *seems* to work, but looks iffy.
So I'm asking someone who actually knows what they are doing.

### Who would this benefit

Linux users (the ones using keyboard, anyway).

### Platform (if relevant)

Linux / BSD

### Games this would be useful in

-

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by unknownbrackets** [comment]
For better or worse, SDL UI doesn't have a separate thread like Windows, so not including `Core_WaitInactive()` should be fine - it makes sense that it hangs, since it's waiting on the thread that'd become inactive.  On Windows, these inputs could be processed while the emulated CPU is running, but on Linux it only samples inputs once a frame.

I think those things ought to work just fine for SDL after removing the wait.

-[Unknown]

**Comment by hrydgard** [comment]
Just for future reference plan to add a thread for SDL, possibly it will have to be Vulkan-only though. See #17876 .
