### ISSUE TITLE
Power save warnings apparently got more intrusive

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#18119]
I haven't tested it myself and I've completely missed it in testing, but I'm getting reports that the power save warning got a lot more annoying in 1.16, so that needs fixing.

**Comment by unknownbrackets** [comment]
Well, it looks more intrusive I assume?  Before it was just text, now it pops up with a big box and icon and etc. and covers more of the screen.

A lot of people have their devices almost always near or in the range of % that would turn on battery saving.  I think it's still important to let people know when it's activated (both because it's a warning that maybe they need to charge, and because it may explain why performance suddenly gets worse) but it doesn't need to be huge or complex.

Obviously, just to point out since you seem to be trying to react to all user complaints recently, people will always complain about such a feature.  Unless you can snap your fingers and make it so phones don't have batteries and don't need to charge, there will be complaints because that's ultimately what they're about.  All PPSSPP can actually do is make the annoying experience less bad, but if you aim to make all the complaints about this area go away you'll just be flip-flopping and changing how it works every single release until the end of phone batteries.

-[Unknown]

**Comment by hrydgard** [comment]
I finally ended up testing it and it's just not that bad - I was afraid we were repeatedly spamming a notification box.

This is indeed not worth doing anything about, I don't think - unless someone sees something like that, in which case I'd expect a screenshot.
