### ISSUE TITLE
Tokimeki Memorial: Forever With You fps drop

### ISSUE THREAD

**Issue by IrfanH495** [hrydgard/ppsspp#18149]
### Game or games this happens in

ULJM-05078

### What area of the game

OpenGL & Vulkan
cutscene,and several places

### Speed seen in PPSSPP

40/60

### GE frame capture and debug statistics

![Screenshot_20230914-143101_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/0d8c8a97-ed12-4c10-a956-3d45ae8c3866)
![Screenshot_20230914-143024_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/07c17b0a-b469-4491-a35b-04570b712c07)
![Screenshot_20230914-143003_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/a72fa3a7-00de-4bb4-ae12-fec0923b05d0)

[ULJM05078_0001.zip](https://github.com/hrydgard/ppsspp/files/12606134/ULJM05078_0001.zip)

### Platform

Android

### Mobile phone model or graphics card

Samsung M20

### PPSSPP version affected

v1.16.1-3-g9625eaf29-

### Last working version

.

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the slowdown.
- [X] Include logs or screenshots of issue.

**Comment by IrfanH495** [comment]
just information,if add to BlockTransferAllowCreateFB or IntraVRAMBlockTransferAllowCreateFB causes the image to turn green and disappear.
![Screenshot_20230914-173924_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/8386ec78-96ac-4a8a-89c0-f0b8314b7190)
![Screenshot_20230914-173945_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/dd2a1069-8b30-40d5-b48e-b072975d02ed)

**Comment by ANR2ME** [comment]
Probably have similar issue to https://github.com/hrydgard/ppsspp/issues/17987

Btw, is it just me or all the low FPS screenshots have readbacks > 0 ? O.o

**Comment by IrfanH495** [comment]
almost everywhere experiences readbacks 1
![Screenshot_20230915-115252_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/4d6b845c-1ba4-42ea-955c-9ac984601fe3)
![Screenshot_20230915-115305_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/cfec58c6-77df-4377-a0c3-da7048d9439c)
![Screenshot_20230915-115311_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/b5544465-5f9d-4dac-9d03-b2e779ebb833)
![Screenshot_20230915-115321_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/f24eafab-3807-4c2a-9669-98b3c245df53)
![Screenshot_20230915-115329_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/86d7d7b5-9d14-4bb4-a9ac-889dfc74565a)
![Screenshot_20230915-115341_PPSSPP](https://github.com/hrydgard/ppsspp/assets/78854859/0ed74f9f-8fe1-43c2-8a46-b97aa0baa9ec)

**Comment by unknownbrackets** [comment]
> Probably have similar issue to #17987
> 
> Btw, is it just me or all the low FPS screenshots have readbacks > 0 ? O.o

This is generally expected for multiple reasons:

1. Without readbacks, PPSSPP by default allows greater input lag (multiple frames.)  A readback means that multiple frame input lag cannot happen, as rendering must complete same frame.  So on a weaker phone where someone is tolerating largish input lag, the impact of a readback is significant.
2. Readbacks mean the CPU pauses to wait for the GPU.  On many devices, this will cause the CPU to downclock (since it's pausing, it must not be very busy), and then later CPU work will run slower making overall emulation slower.
3. Many games will do readbacks mid-frame, which is unfortunate because it breaks up the rendering work.

So of course, readbacks are "bad."  If you ever write a modern game, do avoid them.  But PSP games do them.  The only tools in our toolchest are:
 * Blindly assume the readbacks are not needed and simply disable them entirely.
 * Replace the readback with a framebuffer copy, assuming it will only be textured from and is not modified or accessed by the CPU.
 * Make the readback asynchronous but delayed (i.e. one frame late.)

All of these have downsides and don't work the same way as they did on the actual PSP.  And PSP game developers often did things that broke the assumptions each of these workarounds make.  Worst part is, the above hacks are only currently applicable at the "entire game" level, so they only work for games with simple engines that do only one thing with readbacks, or if someone thoroughly tests every area of a game (which doesn't happen, instead assumptions are made so that investigating future bug reports can be harder and more confusing.)

Technically function hooks could possibly also be used, and wouldn't apply for the whole game, i.e. recognizing that the game is calling a function which calls another function that performs a readback, but does so only to create a texture.  But this is more complicated than our current function hook/replacements support and there's been no interest in going to this level.

-[Unknown]
