### ISSUE TITLE
PPSSPP's own HTTP client not working at all on Linux

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#18161]
I'm testing on Ubuntu. Went back as far as 1.13, but no version will even open the homebrew store through http??

I don't really understand what's going on, I feel that we should have noticed this before by the homebrew store not working.. Maybe something changed in my network environment, or something.

Strangely, our plain http client does work fine on Windows and Mac, it's just on Linux I'm seeing trouble. Basically when calling send() we just get a broken pipe returned. (I thought connect failed, but it's just that non-blocking sockets are a little confusing). I'm adding more logging now.

This is blocking support for RetroAchievements on Linux (unless we hook up naett and libcurl, but I still want both paths to work).

**Comment by unknownbrackets** [comment]
I've definitely used remote disc streaming practically every time I've used Linux, except maybe in VMs.  But I haven't done much on x86 Linux.  That said, I thought someone had set up a docker thing on Linux to serve their ISOs, so that makes me think it's worked for other people.

I would guess there's some firewall or other thing going on.  If you're getting EPIPE, it means the connection is getting closed for some reason.

-[Unknown]

**Comment by hrydgard** [comment]
@unknownbrackets See #18164. There's weird things going on with resolve, and we need to check for errors in connect before select.
