### ISSUE TITLE
Crazy Taxi Fare Wars - Multiplayer joining issue

### ISSUE THREAD

**Issue by anr2me** [hrydgard/ppsspp#18242]
### Game or games this happens in

ULUS10273

### What area of the game / PPSSPP

Apparently if you don't accept the invitation to join within around 500ms the room creator will be shown a connection error message thinking that the player has left, happened on both Crazy Taxi and Crazy Taxi 2.
![image](https://github.com/hrydgard/ppsspp/assets/7974720/97940d59-b057-4df9-af43-a5bac844291c)

The Logs between the received `JOIN` event to the `sceNetAdhocMatchingCancelTargetWithOpt` call didn't shows anything obvious, it didn't even use any adhoc/networking syscalls between them ~~(not sure whether i've enabled verbose logging or not on this build - will need to do more testing with verbose channel enabled on SCENET).~~

Suspected to be timeout issue where it goes too fast or miscalculated (ie. in case the "time goes backward" [issue](https://github.com/hrydgard/ppsspp/issues/13533) kicks in - will need to test this too if the game didn't use any networking syscall that return a timestamp).

PS: I haven't figured out how the game calculate the timeout yet.
PPS: In-game, after multiplayer game successfully started, the count down timer feels ticking faster (about twice faster)

### What should happen

~~It shouldn't detects that the players has left when it's still there waiting to be accepted.~~ should at least shows the same error message on both players.

### Platform

Windows

### Mobile phone model or graphics card

Geforce MX150

### PPSSPP version affected

v1.15.4 (probably latest version too)

### Last working version

not sure, never tested this game before

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
I've tried enabling verbose logs but still unable to find any network-related syscalls between the join request and the player has left detection, other than `sceNetAdhocPdpSend` and `sceNetAdhocPdpRecv` which is part of the internal AdhocMatching communication instead of what the game calls explicitly.

**Comment by ANR2ME** [comment]
I found the condition that will never goes to that `sceNetAdhocMatchingCancelTargetWithOpt` which allows me to take as much of time as i wanted to accept the player.

But, when i tried to put memory write breakpoint on the value being compared with zero while branching, apparently not triggering at all, even from the moment i choose multiplayer menu (was hoping to see an attempt to initialize the value at beginning, but nothing triggered).

The value itself being decreased by 1 if it was not zero, and goes to `sceNetAdhocMatchingCancelTargetWithOpt` when zero, so it should probably supposed to start at positive value, but apparently stays at zero since beginning without anyone writing to it.

**Comment by ANR2ME** [comment]
Hmm.. apparently the timing feels pretty much the same when i tested this game on JPCSP LLE, it's just that my laptop couldn't get 60 FPS and struggles between 40~46 FPS where the error message appeared within 3 seconds (or more), while on PPSSPP (with 60 FPS) the error message appeared in less than 2 seconds.

I guess this game really did have a short timeout to accept the joining player, while most games allowed us to accept/reject within at least 3 seconds.

The only difference with JPCSP LLE (i couldn't get JPCSP HLE to work with this game) is that both players is showing the same error message, while on PPSSPP one of the player apparently unable to detect that the other player (that have the error message shown) has terminate AdhocMatching.

Also, the count down timer going twice faster issue seems to be more of a general issue, as it also happened on the non-AdHoc multiplayer (which didn't use any networking code at all, basically single player where a single PSP being shared by multiple players in turns)

PS: I couldn't start multiplayer game properly after joining using JPCSP (LLE) multiple instances, so unable to see the difference.
