### ISSUE TITLE
Remote Games Tab

### ISSUE THREAD

**Issue by DoganM95** [hrydgard/ppsspp#18317]
### What should happen

The main menu should get another tab added to show remote disks from the host configured.
So it would look something like 

| Recent | Games (Local) | Games (Remote) | Homebrews |
| ------ | ------------- | -------------- | --------- |

Some of us only stream their games from e.g. a NAS server and never keep local files and currently the user has to go 
Settings -> Tools -> Remote Disc Streaming -> Browse games  
only to get a list of games on the remote location.

Also a default tab should be choosable to be opened every time the user gets back to the main screen (who uses Recents anyway?).

### Who would this benefit

Every user of remote disc streaming would benefit from this, not having to click trough 4 pages just to chose a game, every single time. 

### Platform (if relevant)

None

### Games this would be useful in

*

### Checklist

- [x] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by LunaMoo** [comment]
>(...) (who uses Recents anyway?) (...)

 Me and probably a lot of people who understand you can increase it's size to include your whole collection of games which then get sorted by which ones you're actually playing at the top similary to Steam default main view. If you used it, you probably wouldn't have a reason for another tab as your list would simply be there in the recent tab.
 On the other hand on PC I never have any use for "games" tab, it's just way more useful to keep track of last played games instead of looking at few games in some locatio and also looks prettier too due to not showing folder structure and view settings, so as you see it's very subjective.

 About adding another tab, I think "remote" tab if get's added, should be hidden by default as most commonly people store their games locally and might get confused with another tab.

**Comment by DoganM95** [comment]
Good point, adding a remote tab that can be activated in the settings and is hidden on fresh installs would be fine, as you said, not to confuse users.
As for the default tab, having the option never hurts

**Comment by ANR2ME** [comment]
I do feels that going to Browse through Tools menu is kinda too far. 
And, yes, we should probably shows the Remote tab only when we have Remote disc being enabled/setup properly. 

PS: I uses Recents a lot when testing games :) it's faster than scrolling down far to the bottom looking for the name.

**Comment by hrydgard** [comment]
This is not a bad idea, I think having an optional tab that's not visible by default is the way to go indeed.

**Comment by TotalCaesar659** [comment]
@hrydgard I've got some propositions about tab GUI reorganization:
The options in menu ("Display "Recent" on a grid", "Display "Games" on a grid" and "Display "Homebrew & Demos" on a grid") duplicate this pair of buttons...
![0](https://github.com/hrydgard/ppsspp/assets/14265316/cee96c64-db9c-4cda-a596-e16a65117aaf)
...and look redundant. The pair is not in "Recent" though.
![1](https://github.com/hrydgard/ppsspp/assets/14265316/6b897cea-a7e8-4304-891d-d359928356de)
If it was there, these options could be removed or changed to others. I'd propose to implement an option to hide tabs in menu (something like "Tabs" group and "Recent" - ☑ etc.) cause with new "Games (Remote)" tab all the ones won't fit their space on small screen size.
