### ISSUE TITLE
PPSSPP Core cannot load into any game since Core Version: db24299

### ISSUE THREAD

**Issue by outcastexile** [hrydgard/ppsspp#18370]
### Game or games this happens in

None

### What area of the game / PPSSPP

I cannot load into any game since Core Version: db24299. Any core updated past that version doesn't load any games anymore. I have tried using retroarch v1.16.0 and the nightly builds and the results is still the same.

### What should happen

Game should boot up as usually.

### Platform

Android

### Mobile phone model or graphics card

Retroid Pocket 3+

### PPSSPP version affected

Core Version: db24299

### Last working version

Core Version: db24299

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by master1274** [comment]
I'm not sure if this is the same problem, but I have RetroArch crash when trying to launch games PSP. https://github.com/libretro/RetroArch/issues/15822

**Comment by hrydgard** [comment]
You are specifiying the same version as "Last working version" and "PPSSPP Version Affected", this does not make sense.

That particular commit only touches code that doesn't even run in the RetroArch core, so I don't know how it could be the culprit..

**Comment by master1274** [comment]
I'm very confused about where to write about the problem. Versions RetroArch I tried installing old ones on current versions core ppsspp There's always a crash. On any driver. I don't know exactly when the problem started. This is the only thing in the log.
[retroarch.log](https://github.com/hrydgard/ppsspp/files/13233509/retroarch.log)

**Comment by hrydgard** [comment]
Well what I'm saying is someone needs to try some builds before the one specified in the issue here, and find the last one that actually works. Then we'll know when it broke.

Or I guess I'm just gonna have to set up retroarch myself again, sigh...

**Comment by outcastexile** [comment]
Sorry the last good working core has been the db24299 and I have regularly been updating the core, testing if it boots the game (which it has not been able). Then restoring the backup core. I'm willing to do all the testing but I cannot find the place where I can download previous old cores.

![Screenshot_20231102-160915](https://github.com/hrydgard/ppsspp/assets/41350972/9ba350a5-2c58-4c6f-8111-febc0fcc7b73)

**Comment by master1274** [comment]
I noticed that the problem is similar to a bunch RetroArch+core PPSSPP. Not just a problem core. Because I take core libretro PPSSPP from the emulator Lemuroid where it works, I install it in RetroArch, and it crashes when I try to launch games. Here is the core
[Uploading Img_2023-11-02_144123.webp…]()
 version in the screenshot.
![Img_2023-11-02_144123](https://github.com/hrydgard/ppsspp/assets/20639709/9935cdc1-6a0e-4c3f-89cb-0ed0dd499e89)

**Comment by master1274** [comment]
In the context of my problem, it doesn’t matter how old the version is core ppsspp I'm installing. Always crash. It turns out the problem is RetroArch itself.
![Img_2023-11-03_040504](https://github.com/hrydgard/ppsspp/assets/20639709/508e2fad-4bff-42d6-a3aa-e301ce04a9a7)
![Img_2023-11-03_040921](https://github.com/hrydgard/ppsspp/assets/20639709/f28ead83-6343-495d-81b2-3f1244edaebb)

**Comment by master1274** [comment]
In the context of my problem, it doesn’t matter how old the version is core ppsspp I'm installing. Always crash. It turns out the problem is RetroArch itself.
![Img_2023-11-03_040504](https://github.com/hrydgard/ppsspp/assets/20639709/508e2fad-4bff-42d6-a3aa-e301ce04a9a7)
![Uploading Img_2023-11-03_040921.png…]()


> К сожалению, последним хорошо работающим ядром было [ db24299 ](https://github.com/hrydgard/ppsspp/commit/db24299bc75235494c0355184399dd9c2f84d788) , и я регулярно обновлял ядро, проверяя, загружается ли оно с игрой (чего оно не смогло). Потом восстанавливаю резервное ядро. Я готов провести все тестирование, но не могу найти место, где можно скачать предыдущие старые ядра.
> 
> ![Скриншот_20231102-160915](https://user-images.githubusercontent.com/41350972/279872917-9ba350a5-2c58-4c6f-8111-febc0fcc7b73.png)
> 
> Небольшое обновление: я понял, что переключение драйвера на vulkan -> gl работает с последними обновлениями ядра, но производительность не так хороша.

Three revisions to check. ppsspp_1.10.3, ppsspp_1.12.3-2, ppsspp_1.14.4 https://drive.google.com/file/d/1rshJ2hmPSuqm8y1Enk0lauv2I5JkZ4F4/view?usp=drivesdk

**Comment by hrydgard** [comment]
Is this still an issue?

**Comment by outcastexile** [comment]
For me it's still an issue when using Vulkan, but switching to Open GL is fine.

**Comment by outcastexile** [comment]
I've come to report since updating to RetroArch version 1.17.0. The problem with using an updated ppsspp core on Vulkan has now been fix for me.

**Comment by outcastexile** [comment]
I've come to report since updating to RetroArch version 1.17.0. The problem with using an updated ppsspp core on Vulkan has now been fix for me.
