### ISSUE TITLE
Cannot create a frame dump

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#18373]
### Game or games this happens in

all

### What area of the game / PPSSPP

all

### What should happen

Can connect

### Logs

@unknownbrackets 
I have allowed ppsspp pass firewall 

![2](https://github.com/hrydgard/ppsspp/assets/2177532/f54b71e0-7495-4946-83ba-21da978e819a)

### Platform

Windows

### Mobile phone model or graphics card

.

### PPSSPP version affected

all

### Last working version

no

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
https://ppsspp-debugger.unknownbrackets.org/ will not work.  You'll have to use http://ppsspp-debugger.unknownbrackets.org/.

The reason is that for https://ppsspp-debugger.unknownbrackets.org/ to work, your instance of PPSSPP would individually need a validated SSL certificate that your web browser trusts, and it would also need its own unique dedicated DNS host (a prerequisite, generally, for having a validated SSL certificate.)  It is a pain for every user of the debugger to individually obtain (or to have automatically provisioned) dedicated DNS and SSL resources (and the SSL part might violate the terms and conditions of almost all SSL providers if it's given without restriction), so it's not supported.

You can also use the IP and port of PPSSPP + /debugger.  But this will also be http://.

-[Unknown]

**Comment by sum2012** [comment]
Thanks.Solved
