### ISSUE TITLE
Raspberry Pi 4 OpenGL Performance halved

### ISSUE THREAD

**Issue by MertDalbudak** [hrydgard/ppsspp#18388]
### Game or games this happens in

All Games (eg. Gran Turismo / GoW Chains of Olympus)

### What area of the game

Latest pre-build of PPSSPP for RetroPie has a huge performance issue.
In games like Gran Turismo (2x) I got around 40 fps. Now it's 16-24 FPS only.

### Speed seen in PPSSPP

18/71

### Platform

Raspberry Pi

### Mobile phone model or graphics card

RPi4 GPU

### PPSSPP version affected

1.16.6

### Last working version

1.13.2

### Graphics backend (3D API)

OpenGL / GLES

### Any other notes or things you've tried

Applied same settings prior to the update. Revert all general settings in ppsspp and game settings.

I've installed the latest version from source via RetroPie a week ago and noticed the performance issue.
I removed PPSSPP from my system and installed the pre-build which still was the old version off PPSSPP.

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the slowdown.
- [ ] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
Does Vulkan also have the performance issue on RPi 4?

**Comment by MertDalbudak** [comment]
Vulkan is not available on RetroPie unfortunately.

**Comment by w1ndg** [comment]
I have the same issue after update _standalone ppsspp_ to `v1.16.6` and there more reports about perfomance loss in the RetroPie forum and Reddit.

I use for the tests the Raspberry Pi4  4gb with :
RetroPie 4.5.8 (Debian Buster Lite 32 bit) , RetroPie 4.5.8 (Debian Bookworm Lite 64 bit *experimental) and standalone ppsspp 32 and 64 bit .

The games i tested was : Gran Turismo (USA) , Grand Theft Auto: Vice City Stories. 

The same games with the same ppsspp settings have way better performance with standalone ppsspp 1.13.2 .

Tv resolution: 1280x720 60 HZ

**Comment by ANR2ME** [comment]
If you can build it, may be you can find out which commit causing it by bisecting it.

**Comment by cmitu** [comment]
I may try to bisect it. 
However, the only - visible - slowdown I see is with Vulkan, where it runs below 80% and the stuttering is noticeable. Runnning with OpenGLES (w/ X11) seems to be almost fullspeed. Note that I've just done a quick test is with Gran Turismo, running a simple challenge with the FPS/Game Speed on (default settings, with 2xPSP internal resolution, 1280x1024, standalone and not the libretro core).

System is running on 32bit (`armhf`) with the latest RaspiOS (release a few week ago, based on Debian 12 _bookworm_) - similar with what @w1ndg tested on. If @MertDalbudak is comparing the performance with the previous version availble in RetroPie, then that version would be 1.13.2 and not 1.16.5 as reported.

@MertDalbudak do you get the same slowdown with the standalone emualtor ?
@MertDalbudak, @w1ndg do you have a test scenario where I can see the slowdown better ?

**Comment by MertDalbudak** [comment]
> @MertDalbudak do you get the same slowdown with the standalone emulator ?

I've not tested it on standalone. If the previous prebuild of PPSSPP is indeed 1.13.2 than I did not meant 1.16.6. I will correct it in my Original Post.

@cmitu I am trying to revert the update and install the version prior to the update. Once I've done that I will give you an update and a comparison.

**Comment by w1ndg** [comment]
> I may try to bisect it. However, the only - visible - slowdown I see is with Vulkan, where it runs below 80% and the stuttering is noticeable. Runnning with OpenGLES (w/ X11) seems to be almost fullspeed. Note that I've just done a quick test with Gran Turismo, running a simple challenge with the FPS/Game Speed on (default settings, with 2xPSP internal resolution, 1280x1024, standalone and not the libretro core).
> 
> System is running on 32bit (`armhf`) with the latest RaspiOS (release a few week ago, based on Debian 12 _bookworm_) - similar with what @w1ndg tested on. If @MertDalbudak is comparing the performance with the previous version availble in RetroPie, then that version would be 1.13.2 and not 1.16.5 as reported.
> 
> @MertDalbudak do you get the same slowdown with the standalone emulator ? @MertDalbudak, @w1ndg do you have a test scenario where I can see the slowdown better ?

In the  Grand Theft Auto: Vice City Stories in the intro that is using the 3D engine have slowdowns when with the 1.13.2 didn't have. Also, the game have slowdowns with internal resolution to 1xpsp, resolution set to 720p, frame skip on set to 2. With 1.13.2 the game was running better (not perfect) without frameskip . Gran Turismo for me is laggy with and without frameskip, i try a single race . 

Generally, standalone ppsspp have better perfomance with Debian Bullseye and Bookworm, i can say that is running 30% faster and even more with 64bit.

**Comment by cmitu** [comment]
> I start to believe that issue is only noticable with Buster

Bullseye/Bookworm have more up-to-date video drivers (i.e. newer Mesa) and they also don't use the `fkms` overlay that adds a bit of overhead. Do you see the slowdowns only on Buster (current version used by RetroPie) ?

**Comment by w1ndg** [comment]
> > I start to believe that issue is only noticable with Buster
> 
> Bullseye/Bookworm have more up-to-date video drivers (i.e. newer Mesa) and they also don't use the `fkms` overlay that adds a bit of overhead. Do you see the slowdowns only on Buster (current version used by RetroPie) ?

Yes, after i test 1.16.6, 1.16.5 1.15.4. 1.17 with both Buster and Bookworm i believe the issue is with the Buster.

**Comment by ANR2ME** [comment]
So is this driver issue?

**Comment by w1ndg** [comment]
Vertex cache is disable to the new versions, also i deleted the previous setup before install a new one to avoid issues with older settings. 

Maybe is a driver issue. The facts are that the newer versions are running slower with Buster but running ok with newer Debian versions. Thanks

**Comment by cmitu** [comment]
I've done a bisect starting with 1.13.2 and it seems performance has been impacted by the introduction of the 'Ubershaders' in 7adba20fac63a15bbcab5a962ae10418e29b0b1e. Using 7adba20fac63a15bbcab5a962ae10418e29b0b1e (previous commit) seems the performance is at the same level as 1.13.2. 
 During bisection I noticed that the 'Vertex Cache' option is not used but it's also not available for toggling, begin disabled. Is there some detection being done in order to enable it ? Perhaps the `v3d` driver doesn't have the necessary GL ext. to support it (the version of it incluedd in Mesa 19 that's available in Debian Buster).

Since the change is more than 1 year old (pre v1.14), I'm not sure it's practical to debug it. If the current version works fine with the current RaspiOS, then it's most likely a MESA driver regression that was fixed after Mesa 19.x.

 I'm going to look at 2 more scenarios:
 - re-testing current version of PPSSPP on current RaspiOS to confirm what @w1ndg reported.
 - upgrading Mesa on RaspiOS Buster to see if the current PPSSPP version is still having a performance loss compared to v1.13.2
 
 In RetroPie, we can probably offer different version depending on the OS detected, so that users are not impacted by the v1.14+ changes added with the Ubershaders.

**Comment by cmitu** [comment]
I have tested v1.16.6 on Bookworm/RPI4 and it seems it works fine. Upgrading Mesa on Buster to see if anything changed didn't work right, so I can't confirm this scenario.

For RetroPie, I've sent a PR to revert to the pre-1.14 version on older Mesa systems (Buster), keeping the current PPSSPP release for newer systems.

NOTE: using a 2xPSP resolution on the Pi4 introduces slowdown regardless of the version used - I've noticed it with both 1.13.2/Buster or 1.16.5/Bookworm. Maybe the slowdown is more noticeable in recent PPSSPP versions since 2xPSP seems to be the default (with a high enough resolution), while older versions defaulted to 1xPSP ?

**Comment by MertDalbudak** [comment]
I've installed RetroPie and PPSSPP on Bookworm. After some testing I've noticed that the frametimes are more consistent with 1.16.6 on Bookworm then 1.13.2 on Buster. 

> In RetroPie, we can probably offer different version depending on the OS detected, so that users are not impacted by the v1.14+ changes added with the Ubershaders.

Maybe the PPSSPP version before Ubershading was introduced will offer the same stability in frametimes running on Buster.

**Comment by w1ndg** [comment]
Testing all this, i believe was tedious and time consuming, thank you cmitu, you are the best  !

**Comment by MertDalbudak** [comment]
Since this issue was only present on Debian Buster 32Bit and the RetroPie had removed the update on their side of things I will close this issue.

Thank you all for reaching out!
