### ISSUE TITLE
Not enough space on pause screen for “exit” without scrolling

### ISSUE THREAD

**Issue by HM-TArraria** [hrydgard/ppsspp#18544]
### What should happen

![IMG_20231214_183425](https://github.com/hrydgard/ppsspp/assets/58678252/85e64369-b020-4e91-8b45-f3d2d8e05128)

### Who would this benefit

。

### Platform (if relevant)

Android

### Games this would be useful in

。

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

**Comment by LunaMoo** [comment]
You can just scroll the list as in every other screen.

**Comment by HM-TArraria** [comment]
i mean sometime, scroll isn,t  so wise for such a screen space.

**Comment by hrydgard** [comment]
I would agree this is a problem. I'll figure out something.

**Comment by LunaMoo** [comment]
A simple solution would be to just replace some of those options with icons for example settings(an icon with tools), screen settings(an icon of a screen with small icon of settings in the corner) or exit(just "X" or some round arrow for exit to menu) are some easy choices and place "play/pause" icon in the same line.

 However maybe pause screen just needs some scaling and less care about being evenly resized as it will not fit well every device out there and placing it in the center as proposed here just because some users have ultra-widescreen will just make matters worse for others.
For example here's how it looks at standard 16:9 res
![ULUS10020_00001](https://github.com/hrydgard/ppsspp/assets/5485237/eea27fdb-9736-4fd0-89d4-09c841de3420)
The buttons under savestates to revert actions also need to be scrolled and there's really not much space in the center of the screen.

Not much of a problem for me as when using fullscreen on PC there's tons of space:
![ULUS10020_00000](https://github.com/hrydgard/ppsspp/assets/5485237/57826db1-c47e-4364-b9b5-e9134fc0eb1b)
But I don't think populating center of the pause screen is a good idea especially now where game can be viewed through UI.

**Comment by hrydgard** [comment]
Yeah there are a number of different ways we could fix this with different tradeoffs. I'll fix it soon, but haven't decided on which way yet. Good input above.
