### ISSUE TITLE
Wipeout Pulse ship selection screen black in Vulkan on some device

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#18844]
Reported by Max Mexico over email. 

Device:

Black Shark 4
Snapdragon 870 SDX55 3.2 GHz // RAM 8GB // GPU Qualcomm Adreno 650

Doesn't seem to reproduce on PC.

**Comment by sum2012** [comment]
My black shark 5 pro also
cpu Snapdragon 8 Gen 1 gpu: Adreno 730
[UCUS98712.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/14229106/UCUS98712.ppdmp.zip)
![Screenshot_2024-02-10-19-48-38-661_org ppsspp ppsspp](https://github.com/hrydgard/ppsspp/assets/2177532/3d5a7636-555b-4991-b515-3e94bc57448f)
Can be fixed by dis-enable drive driver bug workarounds
Related 1to #18382

**Comment by sum2012** [comment]
@hrydgard 
![Screenshot_2024-09-12-02-27-00-885_org ppsspp ppsspp](https://github.com/user-attachments/assets/445f5b6e-03cb-4893-9d89-a927dca96537)

**Comment by sum2012** [comment]
@hrydgard I don't need to dis-enable drive driver bug workarounds now

**Comment by hrydgard** [comment]
So it just works properly, and maybe we can close this?

I asked for the screenshot because I couldn't figure out what driver bugs we would possibly detect on that GPU (except the subpass one) :)

**Comment by sum2012** [comment]
*fixed by v1.17.1-446*


#19134 *Don't enable the Mali "never" workaround on all GPUs (oops). Minor
fixes.*

在 2024年9月12日週四 上午5:21，Henrik Rydgård ***@***.***> 寫道：

**Comment by hrydgard** [comment]
Ah, that's good, thanks for reporting!
