### ISSUE TITLE
Orphis' buildbot site down

### ISSUE THREAD

**Issue by beyondmeat** [hrydgard/ppsspp#18916]
please host dev builds on github as pre-releases.

**Comment by hrydgard** [comment]
hardware issue, orphis is on it

**Comment by brujo5** [comment]
![Screenshot_20240308-113556_Edge](https://github.com/hrydgard/ppsspp/assets/4172898/ced75c97-cba3-444d-a8d1-e89274804e12)

@hrydgard 
still the same, I have been wanting to install the latest dev version for days

**Comment by LunaMoo** [comment]
Even if you can't build it on your own, you could just download artifacts from github actions:
~https://github.com/hrydgard/ppsspp/actions/workflows/build.yml

 It's even set up to generate android apk, through requires manual trigger and I'm unsure if it's available for everyone or just contributors.

**Comment by brujo5** [comment]
![Screenshot_20240308-154457_Edge](https://github.com/hrydgard/ppsspp/assets/4172898/429e425c-daca-4d32-96dc-963def35698f)

android artifact does not appear

**Comment by LunaMoo** [comment]
Once it completes it should be [here](https://github.com/hrydgard/ppsspp/actions/workflows/manual_generate_apk.yml)

**Comment by brujo5** [comment]
Thanks

**Comment by IrfanH495** [comment]
sorry, I want to update ppsspp, do I have to check all of these
![Screenshot_20240311-211157_Chrome](https://github.com/hrydgard/ppsspp/assets/78854859/253447fd-fdc8-4610-90a4-e6feeba6b990)

**Comment by LunaMoo** [comment]
With github actions you just go to [artifacts](https://github.com/hrydgard/ppsspp/actions/runs/8210969126#artifacts) of the build that interests you and click "[android-NormalOptimized build](https://github.com/hrydgard/ppsspp/actions/runs/8210969126/artifacts/1311070145)"

Standard workflow "build" is automatic and include merges(last merge is usually latest) and all pull requests(basically any work someone wants in, but it might not be based on latest version and might require changes before being accepted) includes Windows x64, Windows ARM64, macOS and ubuntu builds.

 Android APK, iOS IPA and UWP MSIX have manual triggers, but the trigger might be limited to contributors or collaborators.
 The android build I triggered is just 3 days old, not much happened since then, nothing that would affect android outside of maybe android TV's that doesn't have file browser and even there it's minor change.

**Comment by IrfanH495** [comment]
Thanks @LunaMoo

**Comment by master1274** [comment]
> аппаратная проблема, orphis занимается этим

What do we end up with? The server is still not available. Where can I get the latest preview builds?

**Comment by LunaMoo** [comment]
The way to get latest builds was always there since long time ago separate from Orphis buildbot, just look up into my post explaining [how to download artifacts from github actions](https://github.com/hrydgard/ppsspp/issues/18916#issuecomment-1988663084).

 Also as [can be seen](https://github.com/hrydgard/ppsspp/commits/master/) - nothing significant affecting most user experience or compatibility was worked on any recent time, it's all minor changes, sometimes important to a very narrow number of users.

**Comment by hrydgard** [comment]
New buildbot is up, though doesn't have a lot of history yet:

https://www.ppsspp.org/devbuilds/

It only has Windows and Android so far, like Orphis', but more platforms may be added in the future.

Orphis' bot is still down though.

**Comment by beyondmeat** [comment]
Please consider using github 'prelease' release feature for dev builds, this would be useful for scoop updater.

**Comment by hrydgard** [comment]
@beyondmeat if you know how to set that up, feel free to help out (PR or instructions).

I just spent a bunch of time setting up a new buildbot, so not inclined to dig more right now.

**Comment by beyondmeat** [comment]
I can create the needed github workflows/actions and do a PR

**Comment by Fatcat2024-cpu** [comment]
Orphis buildbot still down :(

**Comment by hrydgard** [comment]
Yeah, and it's not likely to come back up unfortunately, so I'm closing this. New buildbot is at https://www.ppsspp.org/devbuilds/ as mentioned.
