### ISSUE TITLE
SOCOM Fireteam Bravo 3: Z-buffer glitch on character customization screen

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#19245]
Reported by s҉u҉r҉y҉a҉     on Discord.

Happens on OpenGL and Vulkan on iOS (and maybe other platforms).

https://github.com/hrydgard/ppsspp/assets/130929/de7a9e1b-967c-493b-a418-b4a67134673a

**Comment by anr2me** [comment]
> [UCUS98716.zip](https://github.com/user-attachments/files/15551423/UCUS98716.zip) Here's a gs framedump if that helps, issue is present on windows 1.17.1 with all renders.

Your GE framedump looks normal on my Laptop (Geforce MX150), tested on Vulkan, OpenGL, and D3D11 all normal.
![image](https://github.com/hrydgard/ppsspp/assets/7974720/cff9b946-888d-47af-b1f0-560760fa00a4)

PS: i'm getting this error when switching window from Firefox back to PPSSPP:
![image](https://github.com/hrydgard/ppsspp/assets/7974720/9423208a-5c64-4bad-90a3-7d0425be02ec)
Probably due to "Pause when not focused" thing

**Comment by foxsevent** [comment]
Dunno looks broken to me, tested with AMD RX7900GRE

![image](https://github.com/hrydgard/ppsspp/assets/64225743/3b0bfc95-e527-4beb-a6b1-a951db347669)
[UCUS98716.zip](https://github.com/user-attachments/files/15557074/UCUS98716.zip)
Here's another one using latest dev build same issue.

**Comment by anr2me** [comment]
Hmm.. may be because i'm using v1.17.1-623, will try the latest dev build later (currently downloading it at 10 KB/s LOL)

**Comment by hrydgard** [comment]
Hm, euro version here, this still reproduces (vulkan, desktop). 

OK, I see kind of what's happening here. The sub render target where the character is drawn is cleared in 565 mode, but then drawn to in 5551 mode, and we treat it as two separate framebuffers, which unfortunately are not sharing a depth buffer, and reinterpret the contents between them. So the clear happens to the 565 buffer, but everything else to the 5551 buffer... In this case, we should really copy the depth buffer from the reinterpret source to the target.. Or, we should do something more sophisticated and actually share the depth buffer (future project...)
