### ISSUE TITLE
PVS-Studio report

### ISSUE THREAD

**Issue by alphrixus** [hrydgard/ppsspp#19515]
Hello,
I appreciate the work you are doing and I really like your project, so I decided to test it with the PVS-Studio static analyzer.
I also wrote [an article](https://pvs-studio.com/en/blog/posts/cpp/1167/) about it.
It belongs to the release [1.17.1](https://github.com/hrydgard/ppsspp/tree/v1.17.1), so a couple of warnings have already been fixed, but most of the others are still in the project. I've described them in detail and even suggested ways to fix them in the article, so you might be curious to take a look.
Thanks.

**Comment by hrydgard** [comment]
Hi there,

I'll take on board some of your proposed fixes. Though, most of the performance issues flagged mostly aren't actually issues - they're in very cold code that is barely accessed at all during normal use.

The security issue also isn't really one, since that code is only used for decryption of game binaries, and there are no real secrets being leaked.
