### ISSUE TITLE
[Doubt] CRT effect

### ISSUE THREAD

**Issue by SilentMRG** [hrydgard/ppsspp#19548]
Hello everyone!

Getting straight to the point: https://github.com/finalburnneo/FBNeo/issues/1897

Could any noble soul help us with this? My dream is to play good arcade games with this badass filter. AvP, Armored Warriors will look great with this filter!

Thank you for your attention and possible help;
Best regards!

**Comment by anr2me** [comment]
I think PPSSPP use a legacy glsl, thus can not be converted to a newer version as-is using glslcc.
Try replacing it with these:
```
layout(binding = 0) uniform sampler2D sampler0;
layout (location = TEXCOORD0) in vec2 v_texcoord0;
```
But i'm not sure what to do with the `uniform vec4 u_setting;` one, since it gets this error when converted to hlsl using glslcc:
`'non-opaque uniforms outside a block' : not allowed when using GLSL for Vulkan`

**Comment by hrydgard** [comment]
you'll have to figure out how FBNeo wants its shader parameters to work, if it supports some. Otherwise you can just skip the u_setting and hardcode some values.

Either way, this is not a PPSSPP issue, so I'm closing this, the FBNeo issue remains open of course.

**Comment by SilentMRG** [comment]
Thanks for the tips guys!
