### ISSUE TITLE
Killzone Liberation crash on intro (PSP-2000 allows too much memory)

### ISSUE THREAD

**Issue by NEOpath** [hrydgard/ppsspp#2183]
The game crash on intro

OS:Windows 7 32 Bits
Emu : ppsspp-v0.7.6-1249-gdd41d4a-windows-x86
log : http://pastebin.com/rW2EqunA

**Comment by unknownbrackets** [comment]
Does anyone know how CFW determines whether something is homebrew and to give it > standard RAM?

Homebrew (e.g. psplink) is allowed to allocate out of the larger partition via the same standard functions.  I think the CFW actually redefines the partition to be larger and aliases the two partition on top of each other, or something, but I'm not sure.

But even with CFW, games still (via JpcspTrace logging) get the standard partition size.

So, ideally, we would replicate this behavior.

-[Unknown]

**Comment by androidcure** [comment]
Here is what I've figured out while setting PPSSPP emulator:

First, make sure to use the Vulkan, it has been added recently, and it works amazingly:

For average hardware smartphone, Buffer Rendering works good. Otherwise, select the "Non Buffer rendering"

Then, enable all the Performance hacks under this menu expect, "Retain Changed texture"

Then setup controls according to your needs.

Moving next, under the System->Emulation, make sure to use Change emulated PSP's CPU clock (unstable), use the maximum available value available. This will boost the performance on many games.

For rest of the settings, you can try yourself or following the below guide:

[https://techshali.com/best-setting-ppsspp/](https://techshali.com/best-setting-ppsspp/)
Cheers!!

**Comment by Levan7** [comment]
Still an issue on latest daily build doesn't load the DLC chapter 5

**Comment by VosslerXIII** [comment]
> Still an issue on latest daily build doesn't load the DLC chapter 5
> Tried putting my PSP installed files into ppsspp same thing it crashed after the video
> 
> Debug log when i tried to install it from PPSSPP menu
> [Debuglog.txt](https://github.com/hrydgard/ppsspp/files/3636711/Debuglog.txt)

Did you tried to switch to the new versions of the emulator?
