### ISSUE TITLE
Fonts are too wide / wrong size in some games compared to original system (PSP) fonts

### ISSUE THREAD

**Issue by sceckSukoSuLi** [hrydgard/ppsspp#2788]
See screenshot than you see the Problem.

![font fail](https://f.cloud.github.com/assets/4977337/799652/2d3a6768-ed79-11e2-87a4-a97311d67e65.jpg)

**Comment by unknownbrackets** [comment]
So, I'm implementing a little font editor.  I'm thinking this will be the best way to get correct metrics.

So far it can load pgf fonts and display characters for editing, but can't save yet, shadows not supported yet, and the character map is not implemented yet.  For simplicity, I'm just implementing it for the web browser (client side only.)

Anyway, I'm thinking to allow loading a font to work on, and a "reference font".  The reference font would show the metrics (advance, w/h, etc.) for next to your glyph's metrics.  Need to allow editing those, and maybe ideally visualizing them but I'm probably not gonna do that.

Also need to add a "palette" or something.  There's 16 colors, dragging over each box 15 times to make it 100% is kinda too much, heh.

-[Unknown]

**Comment by hrydgard** [comment]
Very cool! Could generate the shadows automatically with a little darken + blur, too.

**Comment by unknownbrackets** [comment]
Well, sometime after that I lost a bit of interest.  Seemed like a lot to expect someone else to do, because I wasn't really interested in drawing the font itself.  Anyway, I quickly fixed saving + minor refactoring and build scripts, and pushed it up here:

https://github.com/unknownbrackets/ppsspp-font
https://ppsspp-font.netlify.com/

All that works right now is loading, drawing, and saving.  Drag a pgf in, hit Save, draw over some letters, and it exports a working (but totally uncompressed) pgf.  Can't change w/h or anything else for now, and it strips out shadow maps.

The UI is pretty ugly, just enough to test that the loading and saving was working, really.

-[Unknown]

**Comment by hrydgard** [comment]
Nobody expects you do to everything. Thanks for pushing it! It's a good reference for future work in this area.

I think the way to go is probably not to hand-draw, but to take an existing free font and stretch it to fit the metrics of the official font, then manually touch up the result as needed.

**Comment by unknownbrackets** [comment]
Right sure, just that touching up might be a bit involved.  We want the same "aspect ratio" for the font glyphs.  Maybe we just leave whitespace in one direction or the other, but match the size...

-[Unknown]

**Comment by hrydgard** [comment]
Well yeah, I mean stretch each individual character to the correct dimensions for that one, both horizontally and vertically. Inevitably the result will be that some chars look a little malformed, and that can be manually touched up. Needs to be tested to see how much touching up is needed, hard to predict. Just inserting whitespace will probably not look very good, can probably do better.

**Comment by marosis** [comment]
Hrydgard here is over 20 references with graphical issues. I think ppsspp really need create PSP font(I know what's you written-a a lot of work)

**Comment by RoylandRW** [comment]
This is a I can see when opening the app on my Nexus Player Android TV 8.0, tried deleting settings backup, tried uninstalling and reinstalling, tried most things I can do without actually being able to access the apps settings menu, cause it is not viewable or changeable in this state.

https://photos.app.goo.gl/ZJtodgT7eS9Y19Jh6

**Comment by hrydgard** [comment]
That's bizarre. But has absolutely nothing to do with this fonts issue, please report separately in its own issue report @RoylandRW .

**Comment by hdanny85** [comment]
My case was different when I downloaded the PPSSPP I tried playing field runners but I couldn't see the money or my lives so I was missing text instead of the large font problem but like you people mention above you have to put the PSP font folder under flash0 and it solved my problem I even created a tutorial to help people with the same problem included a video too go here to download PSP font folder and watch the tutorial https://dailyfiledownloads.wordpress.com/2018/10/20/ppsspp-how-to-fix-missing-text-or-large-font-for-android/

**Comment by superostrich** [comment]
I've been using the texture replacement feature to replace the individual characters for specific titles, and the results are quite good, but it is extremely labor intensive and has to be done on a per-game, per-language basis. 

![ULUS10511_00089](https://user-images.githubusercontent.com/42882652/75914870-595a5e80-5e0a-11ea-9423-9d8aa47e5aa0.png)
  
Would it be possible to have a similar dump -> load feature for the entire system font?   If the entire font could be dumped-to / loaded-from a single texture it would be ideal.

**Comment by unknownbrackets** [comment]
Essentially, that is what a PGF is - the font textures, plus numbers about how big and how wide each character is.

Of course, only a fraction of games use PGFs (system fonts.)  A lot of games don't.  There's no way to just do it once for those.  I'd guess around 15%, but lower if you don't count minis.

But note that PGFs are rendered to RAM and the way the API works - it's much more complicated to upscale them than regular textures.  We could try to track as they are copied around in RAM or something, but it might become per-game and labor intensive for that to work everywhere too.

-[Unknown]

**Comment by nassau-tk** [comment]
Fixed these PGF font below.
Jpn0.pgf (Including : Japanese/Chinese/English)
ltn0.pgf / ltn2.pgf / ltn4.pgf / ltn6.pgf
ltn1.pgf / ltn3.pgf / ltn5.pgf / ltn7.pgf
I want check & test by many user.

I can't make  "ltn8~15" (Small size English PGF font) now.
But,Many games **will become** playing smooth by above modified fonts.
(...I believe....)

**Comment by nassau-tk** [comment]
I made Small Fonts.
And, It was merged.
Please test it everyone!

ltn8.pgf
ltn9.pgf
ltn10.pgf
ltn10.pgf
ltn10.pgf
ltn10.pgf
ltn10.pgf

**Comment by nassau-tk** [comment]
@hrydgard 
@unknownbrackets 

and ALL

This issue is started 8 years ago.
I think can be closed now.
Because,All PPSSPP original fonts are modified/fixed already now.
(Of course,Not perfectlly yet.)
If you need to more brush up about "shape/gap/margin" then we should reopen it or open other topic.

How do you think about it?

@unknownbrackets 
It was possible to make with the history of your making.
Thank you very much.

**Comment by Sanaki** [comment]
Just disabled my own font dumps and tested the new ones out on Jeanne d'Arc (one of the sensitive titles). Gotta say, it looks fantastic, and damn close to the real fonts. The prior experience without those dumps was... unpleasant to say the least.

**Comment by nassau-tk** [comment]
@Sanaki 

Even if there was a conversion tool, font making was handwork.
I didn't have knowledge of a programming conversely, but it was fitting work for me with leisure time.:smile:
Because I don't know how much users there are on earth in the whole world, but it's wasteful that this wonderful emulator seems regrettable because of just characters.
Thank you very much for your wonderful report!

**Comment by hrydgard** [comment]
Thanks again for your great work @nassau-tk :)
