### ISSUE TITLE
Feature Req: [ Android ] Restore Game...

### ISSUE THREAD

**Issue by adriandennis17** [hrydgard/ppsspp#3144]
Is it possible to have a restore game option for android device

If there's an incoming call, or anything that manages to get in

The way of an ongoing game, if you should return to the emulator

Instead of going back to the game, it goes back to the PPSSPP Home,

It would be nice to have an option for interrupted games

To either restore and continue the game or return to PPSSPP Home.

**Comment by unknownbrackets** [comment]
It seems to resume fine for me.  I only tried going to the home screen and then reopening the app after opening a few different apps.  Do note that my device has sufficient RAM to not quit PPSSPP due to memory pressure from the other apps I ran, though.

Is there some specific case or certain apps that cause the problem?

Unfortunately, since creating a savestate requires memory, it's not something we can really do when we're being forced to quit due to memory pressure I would assume.

I would not like it if it created a savestate every time I left the app, personally, but I guess that could potentially resolve it for such devices.  I guess it would be an option if so.  That being said, PPSSPP already loses all its GL memory usage first, and doesn't use all that much RAM otherwise, so I'm not convinced it's a significant problem to begin with.

-[Unknown]
