### ISSUE TITLE
Problem with hid-compliant gamepads

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp#3215]
I do hope this issue wasn't already reported, but although all issues on github that were related to gamepads were closed I still have problems mapping buttons to my two gamepads:
A Saitek Colour Rumble Pad and a PS2 to PC adapter PU305 from Shuang Long. 
They are both hid-compliant so I think it could be related to that.

**Comment by hackedhead** [comment]
Any chance this will get any more attention?
I'm using a Logitech Cordless Rumblepad 2. Have used it successfully with other SDL apps, but no dice here. No response and no success rebinding keys from the interface. I also attempted using xboxdrv to spoof an xbox controller on /dev/js1 (real controller on js0) but no love for that either.

This was on a clean build of 067095e2b4691787a8bf30d701dddae0a9d6c0c8, on Slackware Linux 64bit, 14.1.

Should I try building the Qt version?

**Comment by unknownbrackets** [comment]
Unfortunately, no one has taken a shot at this for a while.  Given SDL2 (Linux) and XInput (Windows), and the tides of time - I'm wondering if this is still relevant.

Is anyone using any controllers that aren't supported now?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other problems, and sometimes drivers and operating systems can solve problems like this.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
