### ISSUE TITLE
Frameskip Problem

### ISSUE THREAD

**Issue by kaiser20xx** [hrydgard/ppsspp#3615]
Why ppsspp FPS drop when I turn on frame skipping. For example I play "Kamen Rider Chou Climax Hero" without frame skipping i get 30/30 fps. But when I turn frameskipping on fps drop become 18/30. Does anyone had same problem like me? Thanks.

**Comment by unknownbrackets** [comment]
Does this still happen with auto frameskip enabled?

-[Unknown]

**Comment by sum2012** [comment]
My friemd has bought new computer,I do not follow this issue

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
