### ISSUE TITLE
Puyo Pop Fever and Puyo Puyo Fever 2 Atrac3+ issues

### ISSUE THREAD

**Issue by internetakias** [hrydgard/ppsspp#3650]
This bug has been occuring for a while now and it happens in both PPF and its sequel, PPF2.
Here's the log: http://pastebin.com/tdCukL1W

**Comment by ppmeis** [comment]
Tested with latest build. Same status. Music background stops after 1 second:
![image](https://cloud.githubusercontent.com/assets/4381277/8891238/01f059be-3322-11e5-95c2-43e8936248c9.png)

**Comment by ppmeis** [comment]
Tested with latest build. Same status.

**Comment by unknownbrackets** [comment]
I'm fairly confident that #8356 will improve at least the parts of this game I've seen debugging data for, but would love to hear confirmation.  If the game uses any streaming music elsewhere, it may not be fixed in those places, so it's probably a good idea to play a level etc. to be sure.

-[Unknown]

**Comment by daniel229** [comment]
Look good play 4 levels without problem.

**Comment by internetakias** [comment]
Yep, it's all been fixed. Thanks for your hard work, guys!

**Comment by andutrache** [comment]
indeed it was and i can confirm, good job :)
