### ISSUE TITLE
phantasy star portable missing text in speech bubble (depth testing)

### ISSUE THREAD

**Issue by emmauss** [hrydgard/ppsspp#3777]
![screen00000](https://f.cloud.github.com/assets/5307160/1145277/4f16a52a-1e04-11e3-9c89-219d6eb3909b.jpg)
all speech bubbles in game are empty,whether it is a team mate makiing a comment during a mission or in the city conversing with other characters.
used ppsspp v0.9.1-811 gfad9720

**Comment by unknownbrackets** [comment]
So, before, I wasn't compensating for the viewport.  Theoretically, the correct thing would be rounding/floring z based on the scale and offset of z, except that still doesn't work the way I'm expecting it to.

Not sure if I'm doing my math wrong.  For this game at least, it would be enough to round z in the vertex shader, because it uses a flat z.

-[Unknown]

**Comment by Lerianis** [comment]
Issue still exists in version 1.01 release. Forcing Depth Write has no effect on the no text issue. Phantasy Star Portable 2 with the special fix just for it enabled has text.

**Comment by ikoul** [comment]
Played with the code a little bit earlier, with Unknown's comments about rounding fresh in my mind. In the code that at one point had the workaround for this (dividing by 65536) it seems like we're getting some 24 bit floats from the viewport z values using a left shift and then doing arithmetic on them. If the actual hardware is only using 24 bit floats (implied by the call to getFloat24 and the comments for that function), that arithmetic is creating inaccuracies in the emulation just by being too precise and the margin of error increases as operations are done on the float (particularly when the result includes having the lowest 8 bits set or the rounding errors reach a point where the top 24 bits are affected).

Just to experiment I added a few lines to clear the lower 8 bits of the resulting floats and then tested the games that people have mentioned in relation to this issue (Phantasy Star's text and the player shadows in FF type 0 and Summon Night 5 which were reported broken by the workarounds) and they all looked as expected so I'm thinking this may be a situation where it's better to intentionally lower precision in some cases.

**Comment by hrydgard** [comment]
@ikoui, teah, it may very well be that the transform unit is only computing with 24-bit floats. Would need hardware tests to make sure, but it would be interesting to see what changes you made, feel free to make a pull request.

**Comment by sum2012** [comment]
@ikoul if you don't know how to use github,please zip the changed file,
then upload in the http://drive.google.com/

**Comment by unknownbrackets** [comment]
In #7918 I've added additional debugging features which may clarify this and why I keep saying that #7912 and #7781 are not correct.

With this feature, when hovering over the area it's about to draw text on, the depth values are shown as 0.580199 and 0.580197.  Represented as 16-bit, these are 38023.3125 and 38023.203125 respectively.  These were drawn in transform mode.

Here's a screenshot of the depth view.  The red highlights are where it's about to draw the text, not areas of greater depth values (maybe it should use different colors for the depth value and highlight...)
![phanstar1-depth-pre-draw](https://cloud.githubusercontent.com/assets/191233/9431168/dbb5f60e-49c0-11e5-9680-c639b9a2c537.png)
(OpenGL; first value float, second value scaled to 0.0f - 65535.0f)

The text is being drawn in throughmode, with depth 38023 (0.580194.)  The depth test is src >= dst.

![phanstar1-text-depth-setting](https://cloud.githubusercontent.com/assets/191233/9431188/3c6320bc-49c1-11e5-8a0f-b75763e8c524.png)
(OpenGL; color tab and settings before drawing text)

On a PSP, 38023 is >= to 38023.  But this isn't the case in OpenGL, because it's not true that 38023 >= 38023.203125.

So again, whether or not floats have smaller mantissas during transform isn't at issue here.  The PSP does depth comparison with 16 fixed point bits.  It's true that 0x3F1487EC (0.580199) and 0x3F148798 (0.580194) have the same leading 24 bits, but that's not actually the issue here.

The PSP cannot possibly do depth conversions with more than 16 bits of integer precision on the dst side, because games only reserve 16 bits * 512 * 272 space for the depth values.  It must necessarily have a truncated value in memory.  This is why the software renderer works, because it performs this truncation:

![phanstar1-depth-swrast-pre-draw](https://cloud.githubusercontent.com/assets/191233/9431245/5d9d6b9c-49c2-11e5-97ce-60c75985e262.png)
(Software renderer; 16-bit raw value first, scaled to float 0.0f - 1.0f second)

-[Unknown]

**Comment by sum2012** [comment]
So we need truncate 38023.203125 to 38023 in opengl ?

**Comment by unknownbrackets** [comment]
Yes, assuming @hrydgard agrees with my above that it is not these other issues.

The truncation is further complicated by the depth range.  We still want the clipping, even if z goes from 28024.5 to 48024.5, which means truncation gets a bit tricky.

In this particular game, we could (I think) get away with truncating in the vertex shader.  This might be enough to get us closer to correct in all games actually (since a gradient usually won't handle >= / <= / etc. in a sane way even on a PSP) but most technically, we should do it in the frag shader.

-[Unknown]

**Comment by hrydgard** [comment]
Nice analysis! Okay, yes, the scale factor fix is obviously wrong, and vertex shader rounding may in fact be enough of a fix, and might not even have perceptible performance impact (but if it does, we could still enable it with a flag ;)

I'll give it a shot soon..

**Comment by sum2012** [comment]
I think this can close now

**Comment by DarkD** [comment]
The issue is still present on D3D9 backend, not OGL, it's fixed there for a long time now...

**Comment by hrydgard** [comment]
@DarkD on what hardware? AFAIK it works on D3D9 now for most..

**Comment by DarkD** [comment]
My old Nvidia Geforce GTS 250, proc. is AMD Athlon II X4 635 and system Win7 x64, if needed.
OGL shows text in speech bubbles, and D3D9 - not.
To be exact - bubbles like NPCs in shops. In cut-scenes, like when you exit room and Vivienne thinking about what to do in free time it shows text no problem.

**Comment by DarkD** [comment]
@hrydgard adding DepthRangeHack to compat.ini for this game isn't fixing issue too...
I wouldn't even noticed it if I hadn't talked to NPC instead of shopkeeper. I've played on OGL, but I've hooked ReShade for D3D9 backend(screenshot is taken with removed ReShade) and if that accident didn't happened I'd probably never learned of issue still present and played whole game never noticing.
