### ISSUE TITLE
MGS Peace Walker: Indicator is inverted

### ISSUE THREAD

**Issue by lp200** [hrydgard/ppsspp#3902]
![pw1](https://f.cloud.github.com/assets/5524322/1197300/9d699112-24d3-11e3-9478-e11791b7f71d.jpg)

Tested v0.8.1 and v0.9.1-1154 
Interpreter and JIT mode

**Comment by unknownbrackets** [comment]
Based on hrydgard/pspautotests#173, I think the problem is likely in non-through.  I didn't find any incorrect throughmode cases in throughmode, but maybe I didn't test properly.

-[Unknown]

**Comment by unknownbrackets** [comment]
As a quick test, I tried this:

```c++
static void RotateUV(TransformedVertex v[4]) {
	// TOD: This is not accurate, just to see if it's right-ish.
	const bool invertedX = gstate_c.vpWidth < 0 || gstate.projMatrix[0] < 0;
	const bool invertedY = gstate_c.vpHeight < 0 || gstate.projMatrix[5] < 0;
	float x1 = invertedX ? -v[2].x : v[2].x;
	float x2 = invertedX ? -v[0].x : v[0].x;
	float y1 = invertedY ? -v[2].y : v[2].y;
	float y2 = invertedY ? -v[0].y : v[0].y;

	if ((x1 < x2 && y1 < y2) || (x1 > x2 && y1 > y2))
		SwapUVs(v[1], v[3]);
}
```

This works as far as passing the test (don't have this game), but of course there's more parts of the matrix that matter.  Also, my test doesn't really test an inverted viewport so I should probably add that... but I expect it to need that check too.

Maybe it makes sense to decide if it's inverted once before processing all the verts of the rectangles?  Not sure what the fastest way to determine that, or if transforming the coords here is the best way.  Although, maybe it doesn't matter, since rectangles in transform mode are quite rare.

-[Unknown]

**Comment by daniel229** [comment]
Comfirm,it works in this game.
