### ISSUE TITLE
Feature: Cheap multisampling on TBRs

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#3999]
Tile based renderers like Mali and PowerVR can do super-cheap MSAA per tile (thus, doesn't require a final resolve like on PC) using this extension:

GL_EXT_multisampled_render_to_texture

http://www.khronos.org/registry/gles/extensions/EXT/EXT_multisampled_render_to_texture.txt

We could add support for that pretty easily.

For multisampling on PC we have to write a bit more complicated code and keep track of two FBOs for every framebuffer. Not super difficult, but a bit more work.

**Comment by unknownbrackets** [comment]
There are Adreno 3xx and 4xx drivers reporting support for this, it seems.  Note GL_IMG_multisampled_render_to_texture and GL_EXT_multisampled_render_to_texture.

Would we need the second FBO on desktop in order to resolve?  Would we only need this for depal and block transfers, or always?  Trying to understand more about multisampling.

Theoretically, it sounds like this could be quite beneficial for a lot of users who are willing to have a lower display resolution but want better internal resolution, right?

-[Unknown]

**Comment by hrydgard** [comment]
Closing in favor of #6218 which is more general.
