### ISSUE TITLE
Naruto Ultimate Ninja Impact Hachibi White Colour

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp#4155]
![screen00000](https://f.cloud.github.com/assets/5674972/1321624/b0e5d094-33dc-11e3-9f3e-c4060447f957.jpg)
Real PSP
![hqdefault](https://f.cloud.github.com/assets/5674972/1321626/f16344f8-33dc-11e3-86a6-c00cfff17423.jpg)

**Comment by daniel229** [comment]
It shows up more color with HW transform off
![01](https://cloud.githubusercontent.com/assets/3481559/6281849/5652e924-b904-11e4-8e4b-3c9fe3bba86f.png)

**Comment by unknownbrackets** [comment]
Hmm, that's different from before:
https://github.com/hrydgard/ppsspp/issues/4155#issuecomment-47613706

Does it change where it shows the color, flicker, or anything?

-[Unknown]

**Comment by daniel229** [comment]
Yes,the head change color when it moving.
![02](https://cloud.githubusercontent.com/assets/3481559/6282095/b9e5c146-b909-11e4-9f71-55d88aa1685e.png)
those chenges since https://github.com/hrydgard/ppsspp/commit/1fe2af3421bb3837208e7b81da492eae375d72f1

**Comment by daniel229** [comment]
D3D9 seems better
![03](https://cloud.githubusercontent.com/assets/3481559/6282120/23614b4a-b90a-11e4-89db-585a9990629e.png)

**Comment by daniel229** [comment]
It got more white colour in hardware transform off in OpenGL since https://github.com/hrydgard/ppsspp/pull/7520
![01](https://cloud.githubusercontent.com/assets/3481559/6544595/c40eba16-c592-11e4-9c83-abf0da4550de.png)

**Comment by unknownbrackets** [comment]
That is very interesting.  So then, it is probably related to one of stencil->alpha or blending, or possibly alpha masking / logic ops (in case that was interacting with blending.)

Blending should be src * src.a + dst * 1.0.  Stencil writes zeros, which should be pretty hard to get wrong, and framebuffer is only 0/1 anyway.  Texture appears fully opaque.  Hmm.

Is it still changed when using 3ff51588f7b0a02b59e83c20c045c3813f4ed690, or was b5126f7236f32d7c50dd18c484ed4cd7874a2209 what made it more white?  Or was it even a3342a72d70e4a38e2073e14d3b70d5e5b0e4fa3 that changed it?

Since it's blending, I wonder if this is some bug related to dual-source blending... hmm.

-[Unknown]

**Comment by daniel229** [comment]
it's https://github.com/hrydgard/ppsspp/commit/3ff51588f7b0a02b59e83c20c045c3813f4ed690 makes it more white.

**Comment by daniel229** [comment]
with https://github.com/hrydgard/ppsspp/pull/7629 ,it looks good when hardware transform off in OpenGL.
![01](https://cloud.githubusercontent.com/assets/3481559/6776868/ed015e36-d17e-11e4-9522-811a93319979.png)

**Comment by unknownbrackets** [comment]
Neat, so that's why it wasn't drawing it.

I think Direct3D is likely to be related to dual source blending, then (since it doesn't support that.)

-[Unknown]

**Comment by daniel229** [comment]
White colour again in software transform since https://github.com/hrydgard/ppsspp/commit/42bcea7b418422695bfd1be704ff26b61245f9d4

**Comment by daniel229** [comment]
comment out two of those WARN_LOG_REPORT_ONCE it works fine again.

**Comment by unknownbrackets** [comment]
That sounds scary.  If they are only WARN_LOG_ONCE does it happen?

-[Unknown]

**Comment by daniel229** [comment]
Still happen.

**Comment by unknownbrackets** [comment]
Does the same happen in debug as release?  Can you comment out only one of them, or if either one is there it does it?

Does changing `WARN_LOG_REPORT_ONCE(minmaxz, ` to `WARN_LOG(` in both make any difference?  Does it log it?

This code really shouldn't be affecting anything...

-[Unknown]

**Comment by daniel229** [comment]
Debug build is different from release build and It's not be affect by this.comment out either one won't help,have to comment out both,Change the log types don't make any different.

debug build coment out or not is the same.
![debugbuild](https://cloud.githubusercontent.com/assets/3481559/7219985/df3d0c74-e6ea-11e4-996f-46c71d00b9d8.png)

release build not comment out
![r01](https://cloud.githubusercontent.com/assets/3481559/7219987/fe0845f6-e6ea-11e4-89b4-67a1127172f8.png)

after comment out,same as before
![r02](https://cloud.githubusercontent.com/assets/3481559/7219988/0deb8596-e6eb-11e4-8449-272ed068e8f8.png)

**Comment by daniel229** [comment]
The game does not hit these logs.
<code>#pragma optimize( "",off )</code> does not help release build.

**Comment by unknownbrackets** [comment]
The codegen changes with commenting it out from about the viewport line down.  But I don't see any substantive differences in the math.  Hrm.  I wonder if it's some inf/nan issue somehow... seems unlikely.

Can you log the values if left, right, bottom, top, depthRangeMin, and depthRangeMax?

-[Unknown]

**Comment by daniel229** [comment]
Add the log <code>NOTICE_LOG(G3D, "left = %f, right = %f, bottom = %f, top = %f, depthRangeMin = %f, depthRangeMax = %f", left, right, bottom, top, depthRangeMin, depthRangeMax);</code> above <code>#ifndef MOBILE_DEVICE</code> ,it works agains.

```
34:40:688 drawThread   N[G3D]: GLES\StateMapping.cpp:870 left = 0.000000, right = 1920.000000, bottom = 0.000000, top = 1088.000000, depthRangeMin = 0
.875013, depthRangeMax = 0.062501
```

**Comment by aldi45ckr** [comment]
if i turn off hardware transform and software skinning its looking good but get more lagg 
![ulus10582_00000](https://cloud.githubusercontent.com/assets/4151577/8537722/28f6f390-248d-11e5-8e35-8b93d40c501c.jpg)
hardware transform and software skinning on
![ulus10582_00001](https://cloud.githubusercontent.com/assets/4151577/8537734/5148bcca-248d-11e5-9701-f7d72720a7f4.jpg)

**Comment by unknownbrackets** [comment]
How does this look in the software renderer?  It sounds like this is a lighting issue, and want to confirm if the software renderer (not the same as hardware transform off) has the issue - since it has different lighting code.

If it doesn't, it probably means an inf/nan type of issue, I think.  If it does, it probably means the hardware transform and software renderer code share a bug, since they are fairly similar now.

-[Unknown]

**Comment by Emulatorer** [comment]
ppsspp-v1.7.1-143-g79d16f7b9-android
![screenshot_2018-11-17-16-48-04](https://user-images.githubusercontent.com/37603562/48659379-eaf06200-ea47-11e8-8939-178ae1013776.png)

**Comment by unknownbrackets** [comment]
Obtained a dump: [ULUS10582_#4155_naruto_white_enemy.zip](https://github.com/hrydgard/ppsspp/files/2592436/ULUS10582_.4155_naruto_white_enemy.zip)

Drawing the eight-tails:
 * Draws with lighting disabled: 0x0891a4e0, 0x0891ff00, 0x0892abe0.  Look like octopus parts.
 * Draws without any texture or color, lighting still off.  This adds some outlines.
 * Draws from 0x08940480, a two-tone black texture.  This applies some shading and definition, no lighting.  Uses slope/bias mip mapping with an additional three-tone mip level.
 * Draws from 0x089528b0, still lighting disabled.  This looks like a white/black gradient.

The later two draws use tex env mapping which seems to be not working right here.

Compare with this image from @daniel229 above:
![naturo_correct](https://cloud.githubusercontent.com/assets/3481559/3440157/aaeb4e64-00f3-11e4-8a4e-389ffccffd26.png)

In softgpu, we get the purple, but it's more flat and ugly than the PSP screenshot.  This appears to be related to slope mipmapping.  Changing the bias from slope + 0.0625 to const 1.0 gives us the smoother shading expected:
![naruto_shading](https://user-images.githubusercontent.com/191233/48667554-aedff000-ea8d-11e8-90eb-152a54b52389.png)

Compared to the more harsh (different backends since I wrote this as testing the different backends, but they're the same):
![naruto_shading_wrong](https://user-images.githubusercontent.com/191233/48667579-2d3c9200-ea8e-11e8-8d8e-202bef184b3c.png)

Notice the white is still missing.  That's where we get to bug 2.  In softgpu, that texenv gradient makes it draw nothing, which is wrong.  In Vulkan/etc. it fills it in with white - more wrong.

Texture settings (same for both dark and light shading passes):
 * gen: tex env map, proj: pos / src s: 3, t: 3.
 * no mips, linear/linear, clamp s/t.
 * verts are normals/positions only.
 * lighting off, but all light flags are enabled.

Various issues here, but the tex env stuff at least has a straight forward fix, afaict.  That makes it much better.  Maybe should open a separate issue for the harsh shading.

-[Unknown]
