### ISSUE TITLE
Stretch to display setting ignored - Android

### ISSUE THREAD

**Issue by ppsspp213** [hrydgard/ppsspp#4879]
Games appear stretched even when unticked, i'm not sure but isn't this supposed to display it with black bars with it's native resolution if rendering resolution is X1, 480x272, X2 960x544 etc

**Comment by unknownbrackets** [comment]
Stretch to display definitely works on my Nexus 5, since there are (small) black bars on the top and bottom with it off.  These bars are necessary to preserve the aspect ratio considering I have virtual buttons on the 1080p screen.

So I think with that working and Small Display available, this issue is resolved.

-[Unknown]
