### ISSUE TITLE
Screen flickering issues (Gta Vice City Stories) iOS

### ISSUE THREAD

**Issue by Nmzik** [hrydgard/ppsspp#4940]
When I disable "Hardware Transform" there is no flickering issues.But the game lags a lot!

**Comment by unknownbrackets** [comment]
No new information in a year.  There've been a lot of improvements in PPSSPP since this was created, and without a response, we have no way of knowing what your issue is or if it's resolved.

Closing this.  If it's still an issue, please provide more information (details about how it behaves with the latest version) and we'll reopen.

-[Unknown]
