### ISSUE TITLE
Max frames always limited at 58 (58/60) on Android (due to device Vsync)

### ISSUE THREAD

**Issue by psennermann** [hrydgard/ppsspp#5135]
I've noticed that on Android every game that should run at 60 fps reaches only 58 fps no matters what happens on screen...even in the menus where the frame rate could potentially be 100 or more (on Windows XP without framelimiter I reach 1600 fps!!!), it is always "limited" to 58 (the PPSSPP frame indicator shows always 58/60)
So even every 2D RPG (like Star Ocean for example) that could easily reach 60 fps without problems are always capped at 58.
That wouldn't be a big problem if it weren't for the fact that playing at 96% speed has an impact on sound that always stutters a bit.

Instead games supposed to run at 30 fps play perfectly at 30/30

Also notice that using the framelimiter, the same game capped at 58 on Android, on Windows XP plays perfectly at 60/60 fps.

My system is an ASUS tablet ME173X with Quad core 1,2 ghz Arm7 + GPU PowerVR 544MP - Android 4.2.2

Last information: I'm using official PPSSPP 9.6, anyway I don't think that the latest revision could have a different Android framelimiter behaviour...

**Comment by unknownbrackets** [comment]
Is there anything left here?

Actually, do we need to try to "align" to the device vsync?  By which I mean (incoming ascii art):

```
           + This is when PPSSPP presents the frame and sleeps.
          /
         /             + This is when PPSSPP wakes up and starts rendering the next frame.
        /             /
-------+------+------+------+------ - - -  -  -  -   -   -   -    -    -    -
               \             \
                \             + This is the next vsync / display.
                 \
                  + This is when the device vsyncs and displays the frame.
```

Or does OpenGL / etc. do this for us already?  Obviously, on devices with a different Hz than the PSP, we will get off alignment, and I can imagine this giving us worse performance than necessary.

On faster devices, as long as we finish before the next vsync, then it will make us sleep too long, and we will "get back on track."  But on slower devices, will this happen?

-[Unknown]

**Comment by hrydgard** [comment]
It's actually a bit more complicated than that due to frame buffering in the graphics driver - especially on PowerVR where (due to how the tiled rendering works) a frame is split into two phases, which can actually straddle "real output frames". But yes, it's a concern - currently we rely on what's called as "back pressure" - we render as fast as we can and we are limited by the framebuffer swap at the end of frames. We do not actually sleep_ms unless we are frameskipping.

On modern Android there is another alternative, where if we have spare processing power we can try to do our stuff closer to the actual framebuffer swap, by using the "Choreographer" to schedule our rendering. It's a bit hard to have that kind of control of timing to make the most of it in an emulator though.. Have not experimented much with it.

http://developer.android.com/reference/android/view/Choreographer.html

**Comment by unknownbrackets** [comment]
> We do not actually sleep_ms unless we are frameskipping.

Are you sure?  We sleep_ms() in two cases, and I think we do it always, even if not frameskipping:

1. In DoFrameIdleTiming, but only if we are sub 30 fps (e.g. only after 2 frames without even trying to flip.)

2. In DoFrameTiming(), as long as we are throttling, and the current planned frame time is before the next planned frame time.  We sleep until we reach the next planned frame time.  This happens before we drop out of the emu screen so that the native code can do its business.

So, I'm pretty sure we do sleep, even when not frameskipping.  Of course, assuming that our next-frame estimate is before the time we are woken up by the flip, it should work itself out, so I'm not sure if it's an actual problem or not...

But basically my worry is that we will take X time to render a frame, and then wait Y time for the `nextFrameTime`, and then end up in the middle of an actual display frame, and end up waiting Z time for it to flip.  Thus waiting a total of Y + Z idle.  After that, the next round will be behind, and Y will = 0, but if Z is short then, we will end up back in the same situation next frame and idle for Y+Z....

We only lock back to current time + timeslice if it's 5.5 frames behind, which probably won't happen, so we'll never leave that cycle...

Choreographer definitely seems like a good way to ensure we get the start of a frame, not sure if it solves the problem.

glNext sounds cool but will probably be forever before I can start using it, heh.

-[Unknown]
