### ISSUE TITLE
Auto Frameskip Problem for Non-High End Androids

### ISSUE THREAD

**Issue by globe94** [hrydgard/ppsspp#5137]
- i thought of bringing it here , since im not the only who has this problem.
- i Figured that Auto Frameskip starts to make Games Lag too Much with Lower FPS.
- build 0.9.6-63 is the last build i tested with Smooth Auto Frameskip.
- the next downloadable build, which is 0.9.6-73, is the first to show the stated problem.
- here is the forum link, http://forums.ppsspp.org/showthread.php?tid=7069&page=15  up to last page, i asked somebody to test too..

**Comment by unknownbrackets** [comment]
This issue is now from 5 years back - I know improvements have been made to frameskipping, and also improvements to performance and compatibility.  Is this issue still relevant?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
