### ISSUE TITLE
pressure sensitive buttons are ignored when a D-pad button is mapped to the same psp button (Moga)

### ISSUE THREAD

**Issue by thedicemaster** [hrydgard/ppsspp#5314]
this is a rather strange problem i'm experiencing with my moga pro in HID mode.
when a D-pad button and either an analog stick or gas/throttle(L/R2) button are mapped to the same psp button the game will only respond to the D-pad.

this causes problems in games like phantasy star and monster hunter when you want to go through menus with the D-pad and control the camera with the right analog stick.

problem occurs on build 0.9.6-736(latest right now) and older.
D-pad blocks use of the following buttons when mapped to the same control:
right analog, left analog, L2(Brake), and R2(throttle/gas).

**Comment by unknownbrackets** [comment]
Is this still an issue?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
