### ISSUE TITLE
iOS: Homebrew Store Issues

### ISSUE THREAD

**Issue by Some1Else46** [hrydgard/ppsspp#5333]
I am using a 5S iOS 7.0.4 using the aXw builds. Currently, after hitting install, the download will complete (Cellular usage shows that it does successfully download) but the homebrew will not be there. It is also not there when checking the /GAME directory when viewing the filesystem in iFile and iFunbox.

**Comment by unknownbrackets** [comment]
Is there a way to shell into the device?  Can you `ls -lh` it to see the owner and file permissions?

I guess we should at least message this situation properly.  Silent failures aren't awesome.

-[Unknown]

**Comment by unknownbrackets** [comment]
Do these issues still happen for people?  Do you get better errors (we now show at least disk full errors)?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
