### ISSUE TITLE
[Enhancement] more rendering resolution settings (Android)

### ISSUE THREAD

**Issue by psennermann** [hrydgard/ppsspp#5413]
Since 2x rendering resolution is often too demanding for Android devices, while 1x plays much smoother but (especially on tablets) it's very low-res, I think it might be a good idea to have more rendering resolution options (for example by steps of x0.5, like 1x, 1.5x, 2x, 2.5x, 3x and so on) in order to have at least a 1.5x resolution option that could suit best the compromise between video quality and speed.

**Comment by Mullin** [comment]
Completely agree with this. My i9305 can run MHF3rd HD at full speed in x1 but i have slightly slowdown with x2. So 1,5 is a good compromise. If you don't want add more 0,5 just add 1,5 for testing. 

My Shield Tablet can run MHF3rd HD at x5(2400x1360) so i don't personnally care but just want help others people.

**Comment by Mullin** [comment]
@solarmystic : Completely agree with this. My i9305 can run MHF3rd HD at full speed in x1 but i have slightly slowdown with x2. So 1,5 is a good compromise. If you don't want add more 0,5 just add 1,5 for testing.

My Shield Tablet can run MHF3rd HD at x5(2400x1360) so i don't personnally care but just want help others people.

**Comment by psennermann** [comment]
PoverVR would also benefit a lot from this, since it has huge performance problems...

**Comment by unknownbrackets** [comment]
The problem with 1.5x is that it's not even.  I just tried it locally and everything looked terrible imho.  I can't imagine picking 1.5x over 1x, which looks sharper and cleaner (especially e.g. text which becomes hard to read at 1.5x.)

It sounds like a reasonable compromise but I don't think it works out in practice.

-[Unknown]

**Comment by Mullin** [comment]
The text is unreadable at x1 but look clean at x2.

Resolution 1280x720 : PSP x1 http://www.hostingpics.net/viewer.php?id=632661Screenshot20150228124227.png

Resolution 1280x720 : PSP x2 http://www.hostingpics.net/viewer.php?id=703787Screenshot20150228124238.png

**Comment by Mullin** [comment]
@unknownbrackets : Can you share the apk with 1.5 for testing ?

**Comment by unknownbrackets** [comment]
What did you do to make the text look like that?  Remember that 1x should be very close to how it looked on real PSPs.

Monster Hunter Portable 3rd sold like > 2.5 million units before PPSSPP and its higher render resolution even existed.  It's inconceivable to me that the text looked that bad and so many people bought it, although I don't have the game / have never played it so don't really know.

Is that using the default fonts that come with PPSSPP (which aren't that great)?  It might look a lot better with fonts taken from a real PSP,

-[Unknown]

**Comment by Mullin** [comment]
@unknownbrackets : This is MHF3rd HD for PS3. So the game is render at 480x272 and then upscale to 1280x720. I think the game is optimised for 720p resolution. So PPSSPP downscale the game and upscale it to 720p.

MHF3rd untested but i can test now.

**Comment by Mullin** [comment]
Any news ? There is a lots of devices which need 1.5 resolution.

**Comment by LunaMoo** [comment]
@Mullin Your screenshots reminds me some rounding algorithms, so I think you were just using texture scaling while making them. The thing is X1 res as name says does not have actual scaling and if you use texture scaling it'll just round the edges and blend them with the background which in narrow things like fonts can look alike to what you see.
 If that's the case, simply disabling texture scaling should help. If not then maybe you have a different problem since no, your screenshots does not show x1 psp res which is much nicer and has no problems with text doesn't matter on the font and stretching filter.

 As for the other thing, there's probably no news, because the conclusion for the above explanations was that we don't really "need" uneven resolutions.
 IMO it would be yet another option which would cause people to report invalid graphical issues just like alpha test or non buffered rendering, which people abuse without even considering they mess up the graphics and soo nobody wants to deal with it;p.

**Comment by Mullin** [comment]
@LunaMoo : There is no texture scaling right here. This is just the PSP resolution X1 stretch to display. This is happen on all devices which have a high resolution. Check out the screen from my Shield Tablet with X1. This is not a issue, just a result of stretching the tiny resolution to a high resolution. 


http://www.hostingpics.net/viewer.php?id=597424Screenshot20150312221853.png

**Comment by LunaMoo** [comment]
Then maybe you're using some shader, I saw something alike when trying to write a fullscreen upscaling shader and failed on the upscaling part;p, I think some of the default shaders can do something like that as well. For me this game in x1 res looks like:
![npjb40001_00018](https://cloud.githubusercontent.com/assets/5485237/6628961/78f19d16-c90a-11e4-814d-3dd310fd92cd.jpg)
which is perfectly readable and using different fonts doesn't change that, so no it's not about game being designed for higher resolution, in higher res it will simply be a bit smoother.

**Comment by unknownbrackets** [comment]
I don't think you understand how stretching works.

The PSP has a 480x272 screen.  Let's call it 272p.  That makes 1.5x into 408p.  What you're requesting is basically to stretch things to 408p (text and other flat textures will be necessarily stretched), which will blur them and make them hard to read.

The worst case scenario for text quality is **exactly** what you are requesting on a 720p device.  First, scale it up to 1.5, blurring it and making it hard to read.  THEN, scale it up further to 720p (also not an even multiple, 1.76 times as large.)  This will add even more artifacts and blur.  This is imho the easiest way to make the render look like complete garbage.

In general, I would not upscale something to less than 2x when it is going to be upscaled again.  Unless you have a 408p device, it will be upscaled a second time, so anything less than 2x is going to look like garbage.

On a 1080p screen, you'll still have the garbage from 1.5x, but you at least won't have the garbage from 408 -> 1080, since that is > 2x.  Both 1x and 2x would produce significantly more readable text than 1.5x for a 1080p screen.

Anyway, the above represents the most time I ever want to ever spend on this issue.  I have zero interest in wasting my time implementing an option to render unreadable garbage.  It's just not interesting to me.  If someone else wants to, I'm sure a pull request wouldn't be outright rejected.

-[Unknown]

**Comment by Mullin** [comment]
Implemented in local, work great for me. This is sad for others users. As if this was time consuming...

**Comment by hrydgard** [comment]
Well, presumably it will work okay for 3d stuff but it's likely to not be all that great for game 2D art. That said, an upscale of such by 1.5x usually isn't THAT destructive, although in combination with further upscaling it will be a bit blurry..  In addition, many drawing techniques used by games will cause weird line artifacts when being rendered at non-integer scales, although this does of course not affect all games.

I guess the reasoning for 1.5x is that the fillrate gap between 1x and 2x is really 4x (2x2) which runs right past the limit of what some mobile GPUs can do, although the percieved quality increase isn't that high, so an intermediate solution does make some sense. I wonder if it might be better to go 1x horiz and 2x vert, or vice versa, as an alternative...

**Comment by psennermann** [comment]
@Mullin If you already implemented it locally, couldn't you create a Pull Request on Github about it?

**Comment by Mullin** [comment]
Sure, pull this soon as possible.

**Comment by psennermann** [comment]
Ok tnx :)

**Comment by hrydgard** [comment]
Closing this because few devices are not powerful enough for 2x these days. And there's always 1x.
