### ISSUE TITLE
Pinball Hall of Fame Williams Collection Lag

### ISSUE THREAD

**Issue by xperia64** [hrydgard/ppsspp#5530]
The Pinball Hall of Fame Williams Collection seems to run too slow when when playing most tables. Hardware is not the bottleneck as it occurs both on my android devices and my PC, plus I can fast forward to a ridiculous speed with no frameskip. It appears to be running about 5%-15% too slow. Perhaps there is some internal frameskip not being emulated or something. Incidentally this lag also occurs on Sony's own PSP emulator on the PS3. This problem has occurred for a while, currently on the git builds.

**Comment by ppmeis** [comment]
Tested with latest build. Fun House still runs at 30fps :/
![image](https://cloud.githubusercontent.com/assets/4381277/8891648/be7fe5c0-3333-11e5-91f3-d42e26218b7e.png)

**Comment by ppmeis** [comment]
Tested with latest build. Same status.

**Comment by xperia64** [comment]
This is still occurring.

**Comment by unknownbrackets** [comment]
Has anything improved or changed here in 1.6.1 / latest git build?

-[Unknown]

**Comment by xperia64** [comment]
Not that I can tell. The game still drops to 30 FPS in the one table for no apparent reason. I haven't checked if running other games first can temporarily fix the issue.

**Comment by xperia64** [comment]
So I've found that whatever the workaround does that persists between games is not something that's stored in the PSP's RAM or VRAM. It is however captured by a savestate. Seems like some register or something HLE-related default that's incorrect. It also happens when using the interpreter.

Is there any way to meaningfully diff savestates?

**Comment by unknownbrackets** [comment]
Yes - they are compressed by Snappy but have markers in them.  If you can attach both save states here I can check to see what's not being reset - it'd be very interesting to see what's not being reset properly.

If possible, try turning off "Run on Load" under Debug (this will require pressing F8/Resume when starting the game - it will appear to hang otherwise.)  You'll be able to save state from the menu (not the pause screen) in this scenario.

The reason for doing that is you'll be able to capture two save states: one fresh, saved at exactly the start; the other after loading project Diva and then loading Pinball Hall of Fame, but otherwise exactly at the same place.

In that situation, the save states should only have timestamps different - any other difference would be a bug.

If you want to take a shot at diffing the save states yourself (though I'm happy to, just don't want to steal your fun if this seems interesting), you just need to decompress with the Snappy library first.  The first 48 bytes are a header, everything after that is the raw Snappy data.

An easy way is to edit PPSSPP's source code in Common/ChunkFile.cpp and change `u8 *compressed_buffer = (u8 *)malloc(write_len);` to `u8 *compressed_buffer = nullptr;`.  It will automatically save uncompressed.

Once decompressed, the file is in chunks, each starts with 16 bytes of "marker" and then an arbitrary amount of data for that chunk.  So it's possible to see approximately which chunk any difference belongs to by using a binary diff and searching upward for the nearest null padded marker (which are always readable strings - the first one is "SaveStart".)

-[Unknown]

**Comment by xperia64** [comment]
Here are the two savestates. Savestate 0 is the bad slow one, and Savestate 1 is the one that works at the correct speed after loading the other game.
[PPSSPP_STATE.zip](https://github.com/hrydgard/ppsspp/files/2120147/PPSSPP_STATE.zip)

I managed to decompress these myself, but I'm still not sure what some of the data is (and the header in this case was actually 176 bytes). Presumably the stuff in the audio buffer area can be ignored.

**Comment by unknownbrackets** [comment]
Oops - yes, we added 128 bytes for the game name (I even was the one who made that change and still forgot...)

Hmm, I don't see much different.  Which state is the one that you can load from startup, and it behaves differently than the game initially from startup?

-[Unknown]

**Comment by xperia64** [comment]
Both savestates were created by disabling "Run on Load" and immediately saving.
The savestate with the _1 suffix behaves differently from loading the game in a fresh PPSSPP instance.

**Comment by unknownbrackets** [comment]
Oops.  We're not resetting the CPU mhz.

So basically it runs better when the CPU has been clocked up to 333 mhz first.  I'm going to fix the reset.

This could mean we have some operation eating more cycles than it really should.  As a workaround (and I don't generally recommend messing with this setting) you can change the "locked CPU mhz" to 333.

In most cases, we eat less cycles than we should - I wonder where it is we're eating more.  It's probably our drawing mhz estimate.

Most of the other stuff is unused uninitialized memory (like after names and stuff), but I'm cleaning some of it up for next time.

-[Unknown]

**Comment by xperia64** [comment]
Yep, that fixed it. Presumably this game is supposed to run at 222 MHz. If I overclock to 224 MHz, it runs fine. 223 MHz or below is too slow. It's really close.
I'm going to leave this open until a fix has been committed so that it runs fine by default.

**Comment by xperia64** [comment]
Decreasing any of the first three cost statements by at least 1 is enough to bring the framerate back to where it should be. There is no effect when decreasing the getUVGenMode() or getNumMorphWeights() cost statements.

**Comment by hrydgard** [comment]
There is definitely a case for tweaking those numbers, they are mostly just a guess as is, I don't think we've benchmarked them anywhere close to accurately, and either way we're not even modelling the speed of rasterization at all, so yeah...

**Comment by xperia64** [comment]
I would assume that decreasing either the first or the second cost statement would make the most sense?
either
`int cost = 18`
or
`cost += 8`
I have no idea which is more appropriate to change, and what the potential side effects in other games may be.

**Comment by hrydgard** [comment]
There's only one way to suss out potential side effects in other games - change it and try it. I think we might just have to pick one and go for it..

**Comment by unknownbrackets** [comment]
I've attempted some tests on hardware.

https://docs.google.com/spreadsheets/d/1vXrieDs2FngInpVc84ljUSqcUB0__rzB_FJgYJhqKN8/edit#gid=985072877
https://docs.google.com/spreadsheets/d/1KOsDhKBUMkjB6_j7aSDU4Z2vgvXiumJWugsf68IBWBI/edit#gid=985072877
(didn't feel like combining after I created the PPSSPP data.)

These are all for 2x2 rectangles with texturing.  Obviously, the cost of a 480x272 rectangle is way more than a 2x2 one (and generally more significant than these vert costs), so without factoring for that nothing will be "accurate."

Either way, this seems to suggest that the per light channel cost is inflated.  Though - I didn't really configure the lighting, outside turning it on.

-[Unknown]

**Comment by xperia64** [comment]
Cool.
That seems to indicate that one of the base costs is too low actually, but the lighting channel cost loop's value should be decreased significantly:
https://github.com/hrydgard/ppsspp/blob/b37938b0616cf76c5f964a5d5c7a031a4f6c78da/GPU/GPUCommon.cpp#L466-L467

Would 7 be a reasonable value to try instead of 10?

**Comment by hrydgard** [comment]
Very cool. I would think that after enabling a light, what could further change the cost would be enabling point or spot light processing, as opposed to simple directional light. Maybe it can also shortcut past specular angle processing. 

Looking at the data, it indeed seems like the cost of lightiing is quite inflated, even more so than would be fixed by changing it to 7. But there's also a case to be made for making conservative changes until we have a proper model of the timing, so I would be fine with that change for now.

**Comment by xperia64** [comment]
Closed via #11254
