### ISSUE TITLE
IOS Controllers for all Wii U Pro Controller

### ISSUE THREAD

**Issue by ell1010** [hrydgard/ppsspp#5616]
the left analogue stick gets read really weirdly (the majority of the directions are incorrect)
this happens on a iphone 5s - 7.0.6

**Comment by unknownbrackets** [comment]
Does this still happen?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
