### ISSUE TITLE
PPSSPP v0.9.7.2 - Persona 3 Portable Graphic Crash

### ISSUE THREAD

**Issue by LordBloodySoul** [hrydgard/ppsspp#5678]
Hello there.
I've got a problem that really bugs me since over a week and I couldn't find a real solution to it...

I am playing Persona 3 Portable on the PPSSPP v0.9.7.2, so the newest model.
Every now and then the game makes my AMDDrive crash and the screen on the PPSSPP went black as well as the audio stops playing. It occures in 4 different situations and in different locations and to different times.
1. During Conversations with other characters (mostly when I give gifts to them and the notes come up)
2. During exploration of Tartarus when I ran across the map searching for enemies. It does not make a difference if I rotate the view or not.
3. During the attempt of catching a Shadow off guard (meaning I strike at it)
4. During battle - It happens with normal attacks, Persona summon magic and items like "Jack Brothers".

My system is as followed:

Prozessor - Intel (R) Core(TM)2 Duo CPU E8500 @ 3.16 GHz
RAM - 4,00 GB (3,19 GB)
System type - 32bit
Graphic Card - ATI Radeon HD 4800 (newest Drive)
Audio Card - AMD High Definition Audio Device & Realtek High Definition Audio

My PPSSPP configuration are now back to standart, but I already tried many of the suggestions posted on the net... It sometimes enables me to play a few hours longer, but crashes after a while still...

I would really apprechiate if someone could help me solve this problem somehow.

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
