### ISSUE TITLE
bright horizontal Line in Gran Turismo

### ISSUE THREAD

**Issue by zschigi2** [hrydgard/ppsspp#5685]
in Gran Turismo there is always a bright line between the sky and the horizont. (buffered rendering or non buffered rendering makes no difference) the bug is the same on pc and android version.

![gt psp pic01](https://f.cloud.github.com/assets/5903251/2470805/cb469c3a-b018-11e3-963d-d72916a7a125.JPG)

I don´t know if this effect is the same in other games.

It would be nice, if one of the developers can have a look on it.

Thanks in advance!

**Comment by thedax** [comment]
@unknownbrackets: You asked me in IRC, but yeah, this still happens at least on my PC.

**Comment by ppmeis** [comment]
Tested in latest build. correct sky colorbut bright line still there (using xBRZ scaling in both cases):
![image](https://cloud.githubusercontent.com/assets/4381277/8891769/79b4aa9a-3336-11e5-8090-7b0f5ee4d477.png)

With Nearest is less agressive but still some white points:
![image](https://cloud.githubusercontent.com/assets/4381277/8891770/9e31f0d0-3336-11e5-8807-e5be78025932.png)


Without scaling filter there's no white bar using Nearest but yes with Linear:
![image](https://cloud.githubusercontent.com/assets/4381277/8891776/d8a36cb2-3336-11e5-8578-5fd458d4ac65.png)
![image](https://cloud.githubusercontent.com/assets/4381277/8891780/f46cb5a2-3336-11e5-903b-4d38f786133a.png)

**Comment by unknownbrackets** [comment]
Could you try exporting a GE debugger dump on PC?  I'm wondering if this is antialias, it probably is.

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by ppmeis** [comment]
@unknownbrackets tested with latest build. Same issues. Debugger dump:

[UCES01245_0001.zip](https://github.com/hrydgard/ppsspp/files/2363773/UCES01245_0001.zip)

**Comment by unknownbrackets** [comment]
For posterity: texture 0x0881ee20 in this dump right now.

Some interesting things about this draw:

1. The mountain texture actually has an outline, but it has alpha = 0.  This is true for all 4 mip levels.
2. The texture is somewhat minified in this screenshot (and it has mipmap linear/linear enabled.)
3. Alpha testing > 0 is enabled, and blend is `fixed 1.0 + 1.0 - src.a`.  All parts of the mountain are either 255 or 0 alpha, so this actually forces the interpolated alpha to be treated as 1.0.
4. Bit 0x100 of tex format is used, but this is otherwise DXT1.
5. Texture alpha is enabled, plus a mystery bit (0x8000).

So first, it could be one of these mystery bits somehow impacts alpha interpolation.  Maybe 0x8000 means don't interpolate alpha, or something.

Another interesting thing is DXT1 decode.  Normal DXT1 has the final color as transparent black if c1 > c2.  We use color2, but transparent.  Because of the blending parameters, if it was transparent black it would have a thinner outline (though, it'd still be there.)

It's possibly also interesting, but likely irrelevant, that the framebuffer is 5551.

Finally, if it used a standard blending parameter `(src.a + 1.0 - src.a)`, it'd have no outline AND we could skip the alpha test.  A shame.  It's almost like it's intentional...

-[Unknown]
