### ISSUE TITLE
Some games issues that bother me (LOTR: AQ stuttering)

### ISSUE THREAD

**Issue by Dante2685** [hrydgard/ppsspp#5782]
Hi, first of all I would like to say that filter you introduced in 0.9.8 that is set to default and cannot be changed doesn't suit me. I would like to have a choice to select it or not.
But first thing first:
1. Tekken Dark Resurrection - Story mode with Devil Jin hangs after 7th stage (always), story mode with Armor King hangs after 3rd stage (always) - so the whole emulator goes back to Windows
2. LOTR Aragorn's Quest - if you wait like 20-30 seconds in the main menu the music starts to stutter, if you don't want to wait the same thing happens in-game

I always use x64 builds with Windows 7 Ultimate, the best revision for me is 20140224-x64, but I everyday check the newest to see if those issues mentioned by me are fixed and they aren't, so please if you could deal with them it would be much appreciated. If I encounter any more I will also write about them. Thank you in advance.

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
