### ISSUE TITLE
Evangelion Jo laoding then back to title

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#5810]
it happens in the new game beginning,after the first battle.
see these in the log
HLE\sceKernelMemory.cpp:1822 HACKIMPL SysMemUserForUser_D8DE5C1E Returning 0
HLE\scePauth.cpp:30 UNIMPL scePauth_F7AA47F6(08c29200, 00000df0, 09ffed80, 09ffed84)

log:
https://gist.github.com/daniel229/10004493

**Comment by daniel229** [comment]
Change to scePauth_F7AA47F6,it works.
![pauth_tool](https://cloud.githubusercontent.com/assets/3481559/12619247/2c2f041a-c552-11e5-934a-cff6847fa5f3.jpg) (rename to 7z)

![01](https://cloud.githubusercontent.com/assets/3481559/12619274/48b82c9c-c552-11e5-90ae-48412aa9d190.png)

**Comment by sum2012** [comment]
Thanks @daniel229 
Can you tell me that how to compile Pauth tool ?
Just for interesting

**Comment by sum2012** [comment]
Where is MAKE.exe download from ?

**Comment by daniel229** [comment]
install cmake-3.4.3-win32-x86

**Comment by sum2012** [comment]
I rename Makefile to CMakeLists.txt
CMake .
It show error
![1](https://cloud.githubusercontent.com/assets/2177532/12674869/478ffbcc-c6c1-11e5-8019-a8ee03f4168c.png)

**Comment by daniel229** [comment]
Don't chang anything in the source.
![01](https://cloud.githubusercontent.com/assets/3481559/12675001/3f049b9c-c6c2-11e5-9ad1-228eb3042567.png)

**Comment by sum2012** [comment]
I install GnuWin to solve make.xee
Now fail on another thing 
Do you have idea ?
![2](https://cloud.githubusercontent.com/assets/2177532/12676242/7f661900-c6cb-11e5-86ee-e32035210c0b.png)

**Comment by sum2012** [comment]
@daniel229 
Can you help to pull request source and the binary ?

**Comment by daniel229** [comment]
This is the source and the binary.
[pauth_tool.zip](https://github.com/hrydgard/ppsspp/files/111065/pauth_tool.zip)

I think it's better to join scePauth_F7AA47F6 and scePauth_98B83B5D into one.

**Comment by sum2012** [comment]
The game still have font issue
![1](https://cloud.githubusercontent.com/assets/2177532/12700244/68eb5630-c816-11e5-8148-3f3376b5be1c.jpg)

**Comment by daniel229** [comment]
Yes, there is an issue for it. https://github.com/hrydgard/ppsspp/issues/3908

**Comment by evamank** [comment]
Game is still not working, I have spent 4+ days trying to fix this what is the current solution?

**Comment by sum2012** [comment]
The game is worked,like mhp3 need decrypt

**Comment by hrydgard** [comment]
So can we close this? I guess ideally we'd link to a guide to how to use a real psp to perform the decryption, but I don't know where to find that.

**Comment by LunaMoo** [comment]
It's already closed?

 Whole guide can be limited to 3 steps:
 - play until the game breaks dumping *.bin and *.key files into "memstick/PAUTH",
 - move those files into psp(same folder - to be exact "ms0:/PAUTH/") and decrypt them using provided pauth_tool homebrew(by simply running it),
 - move *.bin.decrypt files into ppsspp "memstick\PAUTH" and repeat from first step if the problem repeats at later stage / that is if new pauth files get dumped.

 Maybe it also deserve an extra warning that while pauth_tool will also run on ppsspp, it will obviously not be able to decrypt files due to missing keys, if we had those keys we wouldn't need workarounds:].

 Also there are 2 separate tools, we include the one for Monster Hunter Portable 3rd in [here](https://github.com/hrydgard/ppsspp/tree/master/Tools/pauth_tool), for Evangelion Jo the tool was provided by daniel229 [in here](https://github.com/hrydgard/ppsspp/issues/5810#issuecomment-177344973).

**Comment by hrydgard** [comment]
Eh, oops, I was assuming that there was still an open issue here since there was discussion. Can't see the closed status when scrolled down :)

**Comment by evamank** [comment]
Thanks for the solution and reply i am quite new to this and i played this on psp a while ago and was wanting to play it again.

**Comment by TheKillerKilt** [comment]
Is there anyway you can just bypass the issue by downloading a save file set after the first mission but after the briefing? @daniel229 the link you posted doesn't seem to work. Unless I'm doing something wrong.

**Comment by sum2012** [comment]
You need save as 1.zip if I remember right

**Comment by TheKillerKilt** [comment]
How do I do that?

**Comment by sum2012** [comment]
Test on computer,the link are worked.
Anyway , you try download this (I mirro r)https://drive.google.com/file/d/0B3OaSdeV0L8kSTF6MkhpZDg5Rnc/view?usp=sharing

**Comment by evamank** [comment]
I have ordered a psp and i will see if evangelion jo works on it and if i can study the decryptor tool on the psp and if i do find it i will make sure to post it

**Comment by LunaMoo** [comment]
@evamank in case that's what you ment - please do NOT post any game files here. That is aside from savegames, but they wouldn't bypass pauth files that are read on loading screens. It's just not going to happen as those files are intentionally used to cripple game when running outside of psp ~ luckily as far as we know only ever used in 2 games.

 Decryption on PSP surely works and if someone is desperate enough pretty sure decrypted files would even turn on google as PPSSPP is also very popular in biggest nation in the world which might not exactly respect international copyrights.
 Many people live in more strict places through and if we want emulation projects like PPSSPP to openly exist, we have no place for any shady stuff in them. That's why even if file is tiny and generally useless if you don't already have the game, it should not be shared here.

**Comment by evamank** [comment]
ok
