### ISSUE TITLE
Remaining issues with PSP saves not loading on PPSSPP

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#5821]
I got a report by mail that "Sengoku Musou 3z special" and "Musou orochi 2 special" saves can't be transferred from the PSP, PPSSPP considers them as corrupted.  These games are both ULJM.

Let's collect similar issues here and see if we can find common causes.

I tried to find a meta issue for this but my search failed, but maybe we already have one :)

So here's the list (feel free to add to it:)
- Sengoku Musou 3z Special (saves appear as corrupted)
- ~~Musou orochi 2 special (saves appear as corrupted)~~
- ~~Persona 1 (psp shows corrupted, ppsspp tries but game says invalid data)~~
- ~~Persona 2 Innocent Sin~~
- ~~Bakumatsu Rock~~

**Comment by Ranguna** [comment]
## Persona 3 Portable ( ULUS10512 )
I played this game for a long time on my PSP but when I tried to transfer my saves to PPSSPP the emulator crashes.

The saves appear on the screen but when I press the circle after loading the saves PPSSPP stoppes working.

I've tried decrypting the .bin file with the game key that I dumped but it keeps on crashing.

**Comment by unknownbrackets** [comment]
Are you absolutely sure the games are from the same region?  EU games will crash after trying to load US games, etc. commonly.  This is because they save entirely differently and the game code is entirely different.  Did you rip the disc you originally saved using?

-[Unknown]

**Comment by Ranguna** [comment]
I ripped the disk and used it both on my PSP and on PPSSPP, the image is the same. But PPSSPP crashes when I load PSP's savedata.

**Comment by fatwhitelump** [comment]
I have the same issue as Ranguna. I'm using the same iso on the PSP as I am on my Android device. I've tried creating multiple saves in different locations on the PSP but PPSSPP always crashes when loading them.

**Comment by Ranguna** [comment]
So.. Is there any way to use my P3P Saves ?

**Comment by sum2012** [comment]
@fatwhitelump @Ranguna 
Can anyone share the P3P Saves ?

**Comment by Ranguna** [comment]
Encrypted save files: http://forums.ppsspp.org/attachment.php?aid=13627
Decrypted save files: http://forums.ppsspp.org/attachment.php?aid=13626
Key used to decrypt the saves: http://forums.ppsspp.org/attachment.php?aid=13625

**Comment by sum2012** [comment]
@Ranguna 
Encrypted or  decrypted  save files don't work on real psp
![1](https://cloud.githubusercontent.com/assets/2177532/6451518/e831ecba-c169-11e4-8fbd-36b85fcc52e6.jpg)

**Comment by unknownbrackets** [comment]
Note that there are some hacks and CFW that force games into older firmware versions or etc. to try to make them play on older firmware versions than their minimum requirement.

These may alter the way the savedata is made (since savedata depends on minimum required firmware version, kinda.)  Such firmware may not load on real PSPs or in PPSSPP, unfortunately.

PPSSPP is designed to be compatible with saves from a PSP running firmware 6.60, and with games that have been unaltered and are not pirated or bootlegged.

-[Unknown]

**Comment by Ranguna** [comment]
@sum2012 @unknownbrackets My PSP firmware is 5.50, I was hoping that I could fix this but apparently I can't play with my old saves :disappointed: 
Thanks for all the help

**Comment by unknownbrackets** [comment]
That game requires 6.20, so yes, it must've been hacked in some way which most likely affects saves.  Maybe we can add some option to force a different version like CFW does, that might allow loading a save, not sure.

-[Unknown]

**Comment by Ranguna** [comment]
That'd be really great, but it's probably a long shot because games that are played on old firmware are most likely hacked in some way and even thought PPSSPP loads with a differente firmware version then the saves might still fail to load due to the fact that it was hacked to work on old CFW. But it's worth the try.

**Comment by sum2012** [comment]
@unknownbrackets This is v1.0.1-117-gc991dd7@Ranguna save log
https://gist.github.com/sum2012/ece72c581e1c51ff4ceb

I have tried this commit but still fail
https://github.com/sum2012/ppsspp/commit/51095131acf6bb309524d220170954413f71b042

**Comment by Aginamon** [comment]
Still no fix on ppsspp loading p3p saves from psp? :C

**Comment by sum2012** [comment]
@Aginamon as you see above, PPSSPP current don't support  5.50 firmware 's save

**Comment by unknownbrackets** [comment]
It does support firmware 5.50 saves, actually.  What it does not currently support is games that run on 6.20 that were hacked to run on 5.50.  Saves made by the original, unhacked game, will work fine.  Saves made by other, unhacked games which run on 5.50 will also work fine.

-[Unknown]

**Comment by Reptile62** [comment]
# Dissidia: Final Fantasy & Dissidia 012:
Don't know if anyone still works on these, but here goes:
Using PPSSPP v1.2.1.1
Dissidia: Had a corrupt save on my PSP, which PPSSPP would load fine (no cheats on save file). Used magicsave on psp to restore it. Now, data works on PSP, but is considered corrupt on PPSSPP.

Dissidia 012: Similar issue. Had a newly made save file on PSP, transferred from brand new Dissidia save (no cheats). PSP can load it, PPSSPP thinks its corrupt.

The only way I've been able to transfer successfully so far is to use magic save on the PSP to corrupt it, and send it to PPSSPP. Then reverse when I want to play on the PSP again.

**Comment by sum2012** [comment]
@Reptile62 can you upload your save which you used magicsave 
to http://drive.google.com ?
(please zip the save folder first)

**Comment by Reptile62** [comment]
@sum2012 
https://drive.google.com/file/d/0B7hW3T7Tf2wpYXBHcFFqaV9zeXM/view?usp=sharing

**Comment by sum2012** [comment]
@Reptile62 I test my real psp "It said the data is corrupt"
What is your PSP firmware ?

**Comment by Reptile62** [comment]
@sum2012 
I believe I'm running 5.00 M33-6.

**Comment by sum2012** [comment]
@Reptile62 This game 's firmware is 5.5.
PPSSPP current doesn't support CFW that force games into older firmware versions or etc. to try to make them play on older firmware versions than their minimum requirement.

These may alter the way the savedata is made (since savedata depends on minimum required firmware version, kinda.) Such firmware may not load on real PSPs or in PPSSPP

**Comment by Reptile62** [comment]
@sum2012 
Is it possible it's an issue with my .iso instead? My original save data, when I first started playing with my UMD, worked fine for a couple years. It got corrupted (according to my PSP), when I started playing the game from an .iso for it, (my UMD tray broke, and I never got around to fixing it). It worked for a few days, then wouldn't work afterwards. That was a few years ago, and I never bothered looking into it until just last week.

**Comment by unknownbrackets** [comment]
One thing is for sure: the game doesn't support 5.00.  There must be a hack allowing you to play it (either on the disc or via your firmware, most likely the firmware.)

But also, games written for 5.50 and higher typically save differently than games written for 5.00.  That's why the savedata your PSP is producing is wrong.  The hack allowing you to play it in the first place is probably somehow making the savedata work on your PSP as well (so you can load and save the wrong savedata, which is "hack format" data, rather than "official format" data like PPSSPP loads/saves.)

-[Unknown]

**Comment by unknownbrackets** [comment]
I'm going to close this - I think we may have resolved all of these issues.  We recently found #11000, but aside from that PSP/PPSSPP compatibility seems pretty good.

-[Unknown]
