### ISSUE TITLE
Play multiplayer with two PPSSPP on the same machine

### ISSUE THREAD

**Issue by Heoz** [hrydgard/ppsspp#5935]
Will i be able to play two ppsspp on one pc without VMware or programs like that xD

**Comment by asl97** [comment]
It is possible to run it without a VM.

You just need different ip address for each instance of ppsspp.

On linux it's as simple as:

1. Using ifconfig to add an virtual ip address
2. Force the second ppsspp to use the address (http://superuser.com/a/241200/238284)

Note:

1. Mac address for each ppsspp instance require to be different.
    This can be done simply by entering the settings and change the mac on each ppsspp instance.
    It will retain its unique mac address until it is restarted.
2. Most people only have one external ip address.
    This means you will have to host your own ad-hoc matching server for it to work.
3. PSP players should be able to join if they are on the same network.

PS:
1. After hours of searching, I finally found out that by setting `SDL_JOYSTICK_ALLOW_BACKGROUND_EVENTS=1`.
It allow me to control all instance of ppsspp at the same time.
2. Patapon3 doesn't seem to work properly, it disconnect after a third player joined.
3. I didn't embed the images cause they are HUGE.

Video: https://www.youtube.com/watch?v=s7Fj_I4kpY0
* left terminal: standalone ad-hoc server
* bottom terminal: four instance of ppsspp

Images:
* https://cloud.githubusercontent.com/assets/4752645/22347672/c71b3154-e443-11e6-9982-9ed5a3bcbd74.png
* https://cloud.githubusercontent.com/assets/4752645/22347671/c71a2872-e443-11e6-92d3-30f44ffef01c.png

**Comment by LunaMoo** [comment]
Just to note, I belive #8134 should have to code which implements this feature without needing any external linux specific apps. That pr is very messy and might be a pain to rebase, so far I belive we only took port offset from it due to some hackish stuff around other code. It also uses different ident style, through about that, whole adhoc code is very messy already.

**Comment by asl97** [comment]
@LunaMoo The idea I posted isn't linux specific.
In fact, it is the same idea used by that pull request.
Assigning different ip to each ppsspp instances, https://github.com/hrydgard/ppsspp/pull/8134/files#diff-f52473ff92a5693a303c6af9fad3dd9aR169

The main different is that it uses a loop back address which doesn't need additional ip related setup.
However I am wondering if it support external connection.

The example method I provided is just a manual setup up with ways to direct ppsspp to use a specific ip address.
If you do have multiple external ip address, you might just be able to set it up so you could use two or more instances for online playing (multiseat or multiboxing?)

Side note: https://github.com/hrydgard/ppsspp/pull/7590/files adds an config which allow specifying the binding address (so no more hackish bind or network namespaces), however it since it uses the config, it would be more troublesome to setup every time when wanting to run multiple instances.

**Comment by LunaMoo** [comment]
Well I have no idea what "ifconfig" is capable nor if it has equivalent on other platforms, but it IS third party/external app. The branch allows it without any apps, that's really all what I ment. Personally I don't have multi-monitor setup which such feature could be used with(and don't like the idea of squishing multiply 16:9 windows on a single screen), what I do have however is a lan with bunch of devices that doesn't need any workarounds.

 Also for your concern about config. PPSSPP can use different config files by commandline --config as well as --controlconfig, but I think nobody cared to port those to any non-windows platform, you can implement those for linux and open a pull request if you need it.

**Comment by asl97** [comment]
Then do it without `ifconfig` by using a loopback address,  the reason for an additional publicly accessible ip address is so other devices on the network can join.

In other words, just do step 2.

**Comment by LunaMoo** [comment]
It's cool that you're explaining all of that and hopefully some people here will learn a bit, but you might never dealt with user support if you belive that this is practical solution.

 Anyway, if you're good with network stuff and like psp emulation maybe consider contributing, this project really needs more people that are interested in this kind of stuff. You don't really need to do any slave work, anything would help since PPSSPP adhoc support is currently held together by a duct tape.;]

**Comment by asl97** [comment]
It is, of course, not an optimum solution but it answer the question of

> Will i be able to play two ppsspp on one pc without VMware or programs

The reason why it works with an virtual machine is simply because it get it's own ip to play with.
Along with all that bloat and os stuff.

Automatic ip assignment is (afaik) impossible without admin/root access and it wouldn't allow multiple ppsspp to connect to players on the internet anyway since most people only has one external ip.

 ____

> adhoc support is currently held together by a duct tape
It's worse than you think.

Trying to keep compatibility with the current psp plugin and coldbird ad-hoc server is really hard if not impossible.
It need an update anyway since the whole adhoc infrastructure is broken by design.
https://forum.coldbird.net/viewtopic.php?f=23&t=1067&start=40#p10225

It be great if we can get rid of the one psp/ppsspp per external ip address too.

Imo, the solution to this is doing it the psp way, meaning using mac address to figure out which packet goes where and just let the ip layer be the glue that connects ppsspp and psp together.

There could be some kind of routing tunneling thread running in the first 'ppsspp instances' and first 'psp connected'.
Although discovering from another device it might be hard and the psp really don't have much ram to spare.

**Comment by unknownbrackets** [comment]
This is implemented now in latest git builds.

-[Unknown]
