### ISSUE TITLE
wwe 2011 (moded13) running slow

### ISSUE THREAD

**Issue by zahmed770** [hrydgard/ppsspp#6016]
latest ppsspp builds slowed down wwe 2011 on my samsung gt-p5100..tried several latest builds bt issue remians plz do

**Comment by unknownbrackets** [comment]
Since there's been no feedback we probably can't do much to improve this.  It may easily have been a setting change.

If you can test and determine which revision first became slower, and which revision was last faster, we can do something.  Feel free to comment on this issue and reopen if so.

-[Unknown]
