### ISSUE TITLE
Super Robot Wars Z - Crash on launch [user-reported]

### ISSUE THREAD

**Issue by angelXwind** [hrydgard/ppsspp#6119]
Received multiple reports from users saying how Super Robot Wars Z causes an instant crash on iOS and Android.

**Comment by unknownbrackets** [comment]
Recent versions of PPSSPP are reporting warnings like "Lots of blits needed for obscure blending".  This implies the game works, since it's being reported on both iOS and Android (note that this won't be reported for devices which support GLES3 or desktops, because those support the max blend equation.)

Anyway, that probably means this has been fixed.

-[Unknown]

**Comment by hrydgard** [comment]
Hm. iOS is supposed to support GL_EXT_blend_minmax ... maybe we are not detecting it properly?

**Comment by unknownbrackets** [comment]
See here about a 544 MP.  I guess we could look at a screenshot of the GL extensions pane to verify?

http://e2e.ti.com/support/omap/f/885/p/354512/1244473
> I just tested with the current GLSDK6_04, but glBlendEquation(GL_MIN) still leads to a GL_INVALID_ENUM, albeit this press release from Imgtec claims, that min/max blending is supported

-[Unknown]
