### ISSUE TITLE
HARUKANARU TOKI NO NAKA DE 3 WITH IZAYOIKI AIZOUBAN missing BGM and black screen after title

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6127]
If you want to play this game on PPSSPP,you must disable BGM in PSP first,then copy savedata to PPSSPP,the game will run well.

Debug log:(rename jpg to rar)
![ppsspplog](https://cloud.githubusercontent.com/assets/3481559/3073965/34054c2a-e319-11e3-8126-9cea15cb5694.jpg)

savedata with BGM disable.(rename jpg to rar)
![uljm05441](https://cloud.githubusercontent.com/assets/3481559/3073980/dba31a5c-e319-11e3-9d34-1e587bb1f61f.jpg)

**Comment by unknownbrackets** [comment]
Is this improved at all by #8356?

-[Unknown]

**Comment by daniel229** [comment]
No.

**Comment by IntrepidWanderer** [comment]
Before discovering this thread, I tried repeatedly over the years to run this game with little success using previous versions of PPSSPP. Gave up for a long time until I downloaded the newest version a few months ago, and after some trial and error based on hunches from checking out the debug log, I managed to get the game to run normally by changing the I/O timing method setting to "Simulate UMD delays". This allows relatively normal play, with some minor issues occuring when battles start and end, and when opening the options menu (the game stutters during these moments and checking the debug log shows a repeated error related to textures).

Unfortunately, even if we overlook the stutters, it's still not possible to get through the entire game this way, so I came on here to make this report in the hopes of finally making this game fully playable.

I've reached chapter 5 during my 1st playthrough, and ran into an event where the game once again fails to load correctly. Normally, during loading and event transitions, the game will blur the screen and then show the proper event graphics once it deems properly loaded. In this case, the event triggers quite suddenly and when the screen blurs, the actual event never loads, even though the event music is loaded properly and continues playing (I can detect this because the music changes).

![haruka3 ch5 freeze 1 annotated](https://cloud.githubusercontent.com/assets/20574569/17017598/f5573a04-4f01-11e6-9db7-130e201d7bd2.jpg)
![haruka3 ch5 freeze 2](https://cloud.githubusercontent.com/assets/20574569/17017601/f89897a8-4f01-11e6-89f6-3d5dad06b9d2.jpg)

Debug log <script src="https://gist.github.com/IntrepidWanderer/aed111c082e4be59b33a8e6dd6e1398e.js"></script>

I've dumped the "displaylist" log based on the wiki instructions. The "Dump next frame to log" was done when the game blurred during event load. I've also made 2 screenshots to illustrate the exact point in the game when this event happens and what the screen looks like when the game fails to proceed properly.

If the files aren't sufficient, I'll be happy to provide anything else you need. However, please keep in mind I'm only an average computer user with zero experience using Github and zero programming knowledge, so please be patient and provide clear instructions that can be followed by a complete newbie. ;)

**Comment by daniel229** [comment]
Any save files?

**Comment by IntrepidWanderer** [comment]
Yes. Select the 8th one for the closest save point (to the best of my knowledge, this game doesn't provide a way to delete an existing save point. You can only overwrite them with another save).

game save (rename jpg to zip. Weird I can't upload a zip file directly even though it says it's supported...)
![uljm05441](https://cloud.githubusercontent.com/assets/20574569/17020114/e393373a-4f0d-11e6-8d07-52fc7490f346.jpg)

**Comment by IntrepidWanderer** [comment]
What's never worked before? Are you referring to my speculation about how other people reporting in the other thread about this game's Ch 7 Shirogane problem might have managed to play the game?

If you mean that PPSSPP has never managed to run the game before, I was under the same impression, but apparently it was not the case. Based on that thread I linked from the PPSSPP's official forums, the earliest [post](http://forums.ppsspp.org/showthread.php?tid=6999&pid=99713#pid99713) there that mentions the game working was from Dec 30, 2014 by "GamerzHell9137" who claimed "Game works fine. Video, sound and gameplay works fine but there's one place where the emulator hangs." (He claims the music player in under the main menu options can cause the game to "hang". Read the details in his post.) He has a debug log linked there, and after checking it, I found he was using PPSSPP v0.9.9.1-1309-gcb62468 Windows 64 bit. I tested it out with the game, it doesn't work under default settings, but changing the I/O method with my workaround to use Simulate UMD Delays will allow the game to run like with the latest versions. However, it will still get stuck at that same event in Ch.5. Strangely enough, I was NOT able to reproduce the same problem GamerzHell9137 had with the music player causing the game to hang. Could he have been using different settings to run the game?? Does using a different renderer make a difference here?? You would think not, but... Maybe someone can find out more about his exact settings from his debug log, but it's beyond my expertise to fully dissect through that thing. Previously, in the years before when I was trying various settings before to get the game to run, it never occured to me to try to change the I/O timing method until a few months ago, when I tried to run the game again, got desperate and checked my debug log. Even then, I didn't really know anything about emulation and merely guessed that the problem was I/O related and naturally tried the only I/O setting available.

Speaking of which, regarding the stuttering when entering the options menu and when combat starts, it appears to be related to the GE engine. Something changed with the way the framebuffer is handled that makes the game now have trouble handling that step, causing a lag/stutter. This doesn't happen when I was testing with v0.9.9.1-1309-gcb62468, and it was NOT present from the version that I first ran the game on a few months ago, but I can't remember the exact version that started causing this. It was fairly recent and could be in the early versions of 1.2.2 or a little earlier than that.
I see something like this in the log when the stuttering is happening (when opening the options menu or battle start up animation is happening)
I[SCEGE]: GLES\Framebuffer.cpp:1770 Decimating FBO for 00088000 (480 x 272 x 3), age 6

As for Unmei no Labyrinth Aizouban, I've never had a problem running that game. When I tested it a few years ago, it was running fine at default settings, I got past the main menu into the game, though I never tested it very far since I didn't want spoilers (it's suppose to be the expansion to the base Haruka 3 game and I hadn't managed to play the base game yet). Which was why I was always puzzled by the problems the base Haruka 3 game had, since the two Aizoban were released one after the other at around the same time. It didn't make a lot of sense why one worked while the other one had so many problems. Then again, I suppose it wasn't that rare for the game devs to change some internal workings of the games even from one expansion to another. I've seen it happen with other games as well, though it was a bit unexpected for these two games, since they are technically renewal versions of PS2 games, so the system wasn't made from scratch like a new game.

**Comment by daniel229** [comment]
I meant the freezing case happen in some old builds I tested either,the oldest one is 0.8.1-150-ga23553a,so it's a very old issue.
As for the lag/stutter case, maybe there is a workaround by changing the xBRZ to the low level such as 2x or turning off it.

**Comment by IntrepidWanderer** [comment]
Well, it's been over a year since I last reported about my success and problems in running the game. As an average user, there's very little I can do to help, but I've been poking at the issue every once in a while to try to find something, and I've come back with a bit of new information.

I've just recently tested out the game again with the latest version of JPCSP. As of writing this is v0.7 revision 197442d posted on 2017/9/4. There are some strange issues related to the shaders and the display of the title animations, but otherwise the game appears to run normally. The working portion INCLUDES the stalling part on the game map mentioned a few posts above this one, which I previously reported on 2016/7/21.

After running the game and loading my save previously made in PPSSPP and heading to the exact same spot on the game map, the game proceeded normally and triggered a quick character model load along with a text window. After the short line of conversation is acknowledged in the game (by pressing "O" or "X" button), the window closes and the player's character is moved backwards one step on the game map. The one line conversation was telling the player that currently they cannot go to that location. Normally a full fledged conversation triggers with an entire background change and full loading of new scene, whereas in this case I think what happens is the game simply quickly loaded just the conversation character model and the text window (all 2D), while remaining in the 3D map scene which it just freezed in the background. See screenshot below.

![haruka3-with shaders scrnsht](https://user-images.githubusercontent.com/20574569/30729390-268f568e-9f2d-11e7-9dda-35964da5bb0d.JPG)

However, as mentioned, there are some issues in JPCSP related to the shaders and I cannot always reliably run the game when shaders settings are enabled. 9 times out of 10, when shaders are enabled, JPCSP will freeze in the game menu when selecting "continue". This is what the same conversation looks like without shaders.

![haruka3 scrnsht](https://user-images.githubusercontent.com/20574569/30729441-8a1eea34-9f2d-11e7-9c90-48d1a16adc0a.JPG)

Now shader issues and animations aside, I hope something can be learned from JPCSP's example, why this particular conversation loads normally in JPCSP, but doesn't work in PPSSPP. As far as I can tell, apart from this problem, the game overall works better in PPSSPP and it is my sincere and fervent wish that one day, this game which was originally released on PSP back in 2009, will be able run smoothly and without issues on an emulator, and I will finally be able to complete it from start to finish.

Included here are two logs of two separate attempts at initiating that conversation in JPCSP. One is with shaders setting enabled, the other is without. I've done my best to try to capture all of the log during the process, but JPCSP lags horribly whenever the logger is turn on and the game cannot proceed, so I've had to resort to turning the logger on and off during the process. This is the basic process I used: Trigger something in the game first, turn the logger on, let it record for a while, turn it back off, let the game move on until I reach the next cruicial step, turn the logger back on again. Rinse and repeat. I hope this has captured useful information, but I can't guarantee it. If needed, the game and save files can be provided for direct testing on the devs end.

Logs:
[JPCSP Haruka3 logs.zip](https://github.com/hrydgard/ppsspp/files/1323446/JPCSP.Haruka3.logs.zip)

These screenshots show which settings I used when capturing the logs (with the only difference between the two logs being whether or not the shader setting was enabled) :
![jpcsp- haruka3-izaiyoiki-settings-video](https://user-images.githubusercontent.com/20574569/30729661-429256ae-9f2f-11e7-8878-4bc27d09bdc8.JPG)
![jpcsp- haruka3-izaiyoiki-settings-memory](https://user-images.githubusercontent.com/20574569/30729664-4520d558-9f2f-11e7-916c-645fd60fb984.JPG)

**Comment by unknownbrackets** [comment]
It's possible the stutter may be improved now, but probably not the crash.

I see it's logging:
47:55:894 idle0        D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 57145 ticks

And the values just get bigger:

48:01:356 idle0        D[G3D]: GPUCommon.cpp:710 Can't execute a list yet, still busy for 865616 ticks

Seems odd.

-[Unknown]

**Comment by benderscruffy** [comment]
PPSSPP v1.13.1-254-g190f50356
freezes up now when you start a new game
next screen is when you input your name
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/9313541/ppsspplog.zip)
