### ISSUE TITLE
ULJS00422 - Weiss Schwarz Portable 

### ISSUE THREAD

**Issue by pinguallyj** [hrydgard/ppsspp#6222]
Game works fine until this menu:
http://puu.sh/9d4w4/5218ebbd99.png
Log has 2 errors:
http://puu.sh/9d4o4/44f633b56f.png

I tried to use different rendering modes, sound hacks, everything, but no luck.

**Comment by unknownbrackets** [comment]
The screenshots are gone, but we do now support that dialog.  Is this still an issue?  #12712 may help it fail better, at the very least.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
