### ISSUE TITLE
sizeInRAM in QuickTexHash correct, but larger than usage for some textures

### ISSUE THREAD

**Issue by RadarNyan** [hrydgard/ppsspp#6256]
(All codes locate in TextureCache.cpp)

Firstly, I've made a custom build which disabled texture change frequency check by comment out:

``` c++
if (entry->numFrames < TEXCACHE_FRAME_CHANGE_FREQUENT) {
    entry->status |= TexCacheEntry::STATUS_CHANGE_FREQUENT;
}
```

It worked pretty fine for me on most 2D games since I'm running PPSSPP on a desktop computer which is powerful enough. But...

![1](https://cloud.githubusercontent.com/assets/2091529/3211512/a9bff3b6-ef1c-11e3-94b3-51b9fe740ab4.jpg)

ULJS00251 - 密室のサクリファイス

When the OP movie ends and the title screen shows up I experienced a terrible framerate drop - on a static background title screen.

Then I'm wondering why I can scale the OP movie fine (every frame is decoded to a texture and scaled) but not the title screen, so I made more test found out that texture 0x09061400 (which is the background image) keeps getting a random hash, which I think is wrong since it's not changing at all.

So I reduced sizeInRAM to 1/4 of the original size by changing the code:

``` c++
const u32 sizeInRAM = (textureBitsPerPixel[format] * bufw * h) / 8;
```

to (I'll explain why 1/4 not by half later)

``` c++
const u32 sizeInRAM = (textureBitsPerPixel[format] * bufw * h) / 32;
```

![2](https://cloud.githubusercontent.com/assets/2091529/3211514/a9e6318e-ef1c-11e3-9ab2-7be584c6b67f.jpg)

Then I got full speed (60/60 fps) on title screen.

![3](https://cloud.githubusercontent.com/assets/2091529/3211510/a9b91f8c-ef1c-11e3-9f49-c657551937e5.jpg)

Here's the srceenshot for the texture in GE Debugger

![4](https://cloud.githubusercontent.com/assets/2091529/3211511/a9bc9cde-ef1c-11e3-91f6-b88cf773ad65.jpg)

NPJH50656 - それゆけ! ぶるにゃんマン Portable~とりもどせ! あいとせいぎときぼうのつにゃ缶~

Extreme framerate drop in save slot selecting scene.

![5](https://cloud.githubusercontent.com/assets/2091529/3211516/aa868c38-ef1c-11e3-9ca0-307824e354b5.jpg)

Reduced sizeInRAM to 1/4 of the original size helped (while 1/2 doesn't)

In this case, textures that causing the problem are 0x094609c0 and 0x0945c8c0 (screenshot below)

![6](https://cloud.githubusercontent.com/assets/2091529/3211513/a9c59d52-ef1c-11e3-8e8e-4c5f8cb182a0.jpg)
![7](https://cloud.githubusercontent.com/assets/2091529/3211515/a9f768f0-ef1c-11e3-8470-6cb2f3756e3a.jpg)

So I guess the problem is the sizeInRAM is too big for this texture which causes hashing wrong range of ram (larger than the texture acturally uses)

That's all I can do... I know little about programming so it will be nice if someone acturally knows how to find the correct sizeInRAM have a look into this.

**Comment by unknownbrackets** [comment]
I think the best we could do about this might be:

1. Split SetTexture up into two steps.  This would solve a few problems.
   i. The first step would ensure gstate_c values were set correctly (flipTexture, textureFullAlpha, etc.)
   ii. The second step would actually bind the texture, and would happen *after* vertex decoding, etc.
   iii. This means the second step would have vertex information (IsAlphaTestTriviallyTrue() would be correct also.)
2. If rendering in throughmode, detect the minimum maximum X/Y coordinates.
   i. We could consider calculating this within vertexjit, depends on hit.
3. If any y position is ever > 272, set a STATUS_ flag on the texture cache entry.
4. When hashing the texture, clamp height to 272 unless the STATUS_ flag is set.

If we need to make a copy for render-to-self-texture or depal, we can have the dimensions of a subregion (in throughmode only, unless we do the full transform.)  This should help Sonic Rivals 2 and Killzone, for example, although it'd probably help others.  This might even help shader blending, but not commonly, since that is less likely be be in throughmode.

For performance, we could only calculate the bounds if the texture width and height are 512.  This would only cover sprite sheets (usually not a ton of verts) and full-screen draws.  However, it would cover a lot of the depal and render-to-self cases.

Furthermore, we could potentially use the time between first and second steps to hash the texture on a separate thread.  However, my previous attempts at this indicated that the overhead costs as much as the win, but maybe if we only did it for large 512x272 / 512x512 textures...

I've observed that performance in Crimson Gem Saga, within battles, could improve by potentially 10% by eliminating a hash fail that happens with a 512x512 texture pretty much every frame, because the game is overlapping other data after the useful part of the texture.

-[Unknown]

**Comment by hrydgard** [comment]
That sounds good, and I like the potential threading opportunity. It surely should be a win as long as we only do it for large textures, as you say. As for 2.i, doing it in the vertexjit makes sense, we could make it only do it when compiling through-mode vertexdecoders, speed hit should be minimal. That would of course miss a few games that do framebuffer effects with non-through-mode, but I don't think that's very common...

**Comment by unknownbrackets** [comment]
Well, the trouble is that large textures tend to be used with small numbers of vertices.  It may be hard to find a win if only because there won't be enough work to do while it's hashing.

-[Unknown]

**Comment by hrydgard** [comment]
Right, you have a point there :)

**Comment by unknownbrackets** [comment]
Blar.  Crimson Gem Saga in fact uses 320 rows of the texture to do some tricks.  But if I make it work with that, I'm gaining 12%+ performance, yay.

Something thrown together:
https://github.com/hrydgard/ppsspp/compare/hrydgard:master...unknownbrackets:tex-split?expand=1

-[Unknown]

**Comment by unknownbrackets** [comment]
I've updated it with copying subregions, where possible, during depal and shader blending.

-[Unknown]

**Comment by unknownbrackets** [comment]
So the initial work is merged, which allows detecting the height in some situations.  This doesn't work in 3d transform mode, so that's all that's left.

Unfortunately, there are important performance trade-offs there.  It would be nice to make a list of games that still have this issue.

-[Unknown]

**Comment by hrydgard** [comment]
Don't think there's all that much more that can be done here, plus the issue hasn't been updated for 7 years. Closing.
