### ISSUE TITLE
UI navigation very hard (impossible in most cases) to use with a controller / keyboard

### ISSUE THREAD

**Issue by RadarNyan** [hrydgard/ppsspp#6297]
It's overall very hard to use (tested with a xbox360 controller)
IMO, navigation keys should follow Control Mapping settings: Dpad to move, O to confirm, X to go back (or swap O/X following "Confirmation button" settings in Settings - System - PSP settings)

**Can't use d-pad down / arrow down on keyboard**
Whenever I use it, it just takes me back to previous screen.
This makes most UI functions inaccessible with controller / keyboard.
The other three directions working fine.

**In-game pause menu**
If a save slot with no save data is highlighted when you open the pause menu, "Load state" won't become available if you switch to a slot with savedata LB/RB. (d-pad would work, but not very functional since d-pad down doesn't work as expected)

In most cases, it's better to use a mouse or touch screen (like tweaking settings) but it's definitely making more sense to access pause menu with a controller (of course if you're playing with one)

It is true that we can assign save/load/next slot to controller buttons, but on a xbox360 controller there are only 5 extra buttons and LT/RT can not be assigned to "next slot" function since it would be triggered multiple times on one press (definitely need work on those triggers) - well, won't be a problem for keyboard though, we have more than enough buttons to assign to any function we want.

**Comment by unknownbrackets** [comment]
Sorry, never responded to this - the above description made it clear.

The UI very intentionally hardcodes arrow keys to arrow keys on the keyboard.  See here for more information:
https://github.com/hrydgard/ppsspp/issues/7847#issuecomment-165348642

We also hardcode confirm and cancel buttons, I think.  Assuming we don't want to give the user a way to unmap everything and be completely unable to use the UI, the best solution to this problem is probably to ignore X/O mappings that overlap the hardcoded ones.

-[Unknown]

**Comment by benderscruffy** [comment]
Is this still an issue ??
