### ISSUE TITLE
Final Fantasy Tactics: Garbage remains in framebuffer when skipping intro video just after inputting name and birthday.

### ISSUE THREAD

**Issue by thedax** [hrydgard/ppsspp#6317]
Similar to yesterday's issue solved by @unknownbrackets when skipping the attract movie and pressing Continue from the title screen, the only remaining garbage I've noticed is when you start a new game, enter your name, and then proceed to skip the first intro video afterward, where it will show a frame of Arazlam's little history speech before immediately cutting to black and loading the first chapter of the game.

You can see what I mean here:
https://www.youtube.com/watch?v=dp3gd_5IM2U

I've not really played far enough to know if other FMVs have a similar glitch or not.

Tested using this system:
![Screenshot 01](http://i.minus.com/iCgaRBpWPaYDJ.jpg)

**Comment by unknownbrackets** [comment]
Even if I change `Memory::Write_U32(ctx->avc.avcFrameStatus, initAddr);` to always write 0, this still happens (it doesn't display any video though.)

It actually does this:

```
HLE\sceDisplay.cpp:786 sceDisplaySetFramebuf(topaddr=04000000,linesize=512,pixelsize=3,sync=1)
HLE\sceDisplay.cpp:786 sceDisplaySetFramebuf(topaddr=00000000,linesize=0,pixelsize=0,sync=1)
HLE\sceDisplay.cpp:789 - screen off
```

If I allow `topaddr` to be set, latched, to 0... the issue goes away.  I think ultimately this issue is that we don't always (or ever?) allow the game to turn off the display input signal once it's been turned on (I assume that's what this is doing?)

-[Unknown]

**Comment by hrydgard** [comment]
Hm, I don't see why we shouldn't allow games to do that... Makes sense.
