### ISSUE TITLE
Crash on multiplayer on a single computer

### ISSUE THREAD

**Issue by i30817** [hrydgard/ppsspp#6333]
As requested on #6268 I opened a bug report about a crash that happens if PPSSPPSDL gets kicked out of the server on final fantasy type 0 (in this case because the client ip is the same, 127.0.0.1)
backtrace: https://gist.github.com/i30817/62be21abbb48be0e5855

I also tried to hack the server to make it change duplicate localhost ips that try to connect to aliases to see if it would work... well it didn't crash, but they couldn't connect to eachother on type 0, the host -on the same localhost ip as the server, 127.0.0.1- had the 'connecting' wifi icon always animating, and the guest - 127.0.0.2 - couldn't go beyond the multiplayer menu with the shop and the save). It would be nice to be able to connect on localhost multiple instances, especially with multiseat coming to linux.

**Comment by unknownbrackets** [comment]
Does this work better now?  I know there have been a lot of changes here lately.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
