### ISSUE TITLE
UFC Sound shatter

### ISSUE THREAD

**Issue by pinguallyj** [hrydgard/ppsspp#6644]
Ufc is finally fixed, but when using fast forward in game sound is shattering.

**Comment by unknownbrackets** [comment]
Were you using mutlithreaded?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
