### ISSUE TITLE
Darkstalkers Chronicles problem - characters not visible on select screen 

### ISSUE THREAD

**Issue by Dante2685** [hrydgard/ppsspp#6647]
Hi I'm currently using version ppsspp-v0.9.9-34-gb7ac539-windows-amd64 of the emulator and when I enter any game mode, arcade for example, I cannot see characters on select screen. When I select anything in blind and the stage loads up there is nothing visible, no hp bars, no characters, only stage background. It also occurred in 0.9.8 various versions. I downloaded the latest version for testing, but the problem is still happening. Is it possible to fix it somehow? In other 2D beat'em ups like Street Fighter or Samurai Showdown everything works fine.

**Comment by benderscruffy** [comment]
PPSSPP v1.5.4-995-g373366911 Windows 64 bit
still the same problem on the character select screen
and now during gameplay the characters,health bars and score are all invisible

**Comment by hrydgard** [comment]
Since the game is using the CPU to draw directly to VRAM on top of GPU rendered graphics, it's very difficult to make this work correctly except in the software renderer...  It works if you use that.

**Comment by icegallantmon** [comment]
How do I set it to read frame buffers from gpu?

**Comment by LunaMoo** [comment]
You can't.
 There used to be an option that showed character sprites in this game, however it also introduced a lot of glitches even in this game despite some salty people claiming it was making things perfect and due to being really awful and causing lots of other more serious issues to a lot of people it was removed completely.
  Removing options that even remotely helped to some people in emulation always attracts hate, however doing so is necessary for the greater good and longevity of the project - as such that option will not return althrough all of the people who are hating that decision should understand that PPSSPP does not force you to upgrade and you're free to forever use any outdated buggy version that fits your needs.

 There is an open possibility that someone creates a hack that would upload framebuffer just in the right moment, through it might also require some additional very ugly game patching hackery since the whole game is emulated or recompiled into one huge function that makes hacking around it very troublesome.

 If you want to play this game through PPSSPP with nice graphics, you will currently need a modern high thread count desktop CPU(I would say 6 core/12 thread Zen+ for a reasonable minimum for full speed) and make use of software rendering.

**Comment by PilipinoAko** [comment]
This game will fix or not?

**Comment by paulomanrique** [comment]
What was the last version that had the "read frame buffers from gpu"?

**Comment by hrydgard** [comment]
The game basically draws like this:

* First, use the hardware to draw tiled backgrounds.
* Second, draw the characters on top using the PSP CPU, blasting straight to VRAM. This is unusual, PSP games don't normally do this and I believe Sony discourages it.
* Third, use the hardware again to stretch the image from 384x224 to 480x272.

The best way we could render this without (expensive) readbacks is probably: 

* Software rasterize step 1, let it perform step 2. 
* Hook the stretch blit and present the smaller image directly. This would get us a sharper image than is possible on the PSP by avoiding the extra stretch step, and stretching directly to the output resolution instead.

With a readback hack, we'd just readback at the point of the stretch blit. If you render at 2x, most of the blurriness from the stretch would at least not happen, and might be fast enough on newer mobiles.

I'm investigating to see how hard it would be to special case this game in the software rasterizer to get playable speeds on mobile. If it can't be done, I'll do the readback option.

**Comment by Gamemulatorer** [comment]
This game seems ok now using hw rendering
![Screenshot_2022-07-19-23-17-03-308_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/179786763-58c75a7a-e6ee-44d6-a4f0-7023cbd87901.jpg)
![Screenshot_2022-07-19-23-08-58-091_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/179786807-653421ac-5014-4104-b145-23be3e52ac7a.jpg)
I disable this game id in compat.ini (ForceSoftwareRenderer)

**Comment by hrydgard** [comment]
Really? That's very unexpected...

**Comment by Gamemulatorer** [comment]
> Really? That's very unexpected...

Yes, but increasing rendering resolution doesn't change 🤔

**Comment by LunaMoo** [comment]
@Gamemulatorer you sure you actually disabled compat.ini hack and loaded the game from normal in-game save? Because if you loaded a savestate, pretty sure it still loaded with compat hack it was affected earlier.

**Comment by LunaMoo** [comment]
I think to override it and disable via separate ini file you have to set it to false instead of commenting out. It probably still sets it to true in the assets compat.ini you don't have access to on android.

**Comment by Gamemulatorer** [comment]
> I think to override it and disable via separate ini file you have to set it to false instead of commenting out. It probably still sets it to true in the assets compat.ini you don't have access to on android.

Yes you're right!
Sorry for the noise ✌️😅

**Comment by i30817** [comment]
That's counterintuitive.

**Comment by unknownbrackets** [comment]
As always, I'll note that I don't love game hacks and configuring them is one reason.  But anyway, the theory is that you override only the specific settings you want to override.

If the only way to override was making a full copy of the file, it would be bad for updates.  As soon as v1.15.0 comes out and has more compat flags, you'll be stuck with the old ones and have new bugs (maybe even more bugs than you had before.)  Instead, if you configure only the few settings you want to change in your override file, then updates Just Work.

-[Unknown]

**Comment by i30817** [comment]
I get it, but maybe it should be in the log? A line like 'applying overrides: forcesoftwarerenderer, ....'

**Comment by LunaMoo** [comment]
Don't understand how that's "counterintuitive", on the opposite I think it's only natural and functional way that, if you want to override some setting, you have to actually SET the override.
