### ISSUE TITLE
Save state problem (low memory device)

### ISSUE THREAD

**Issue by Xlander11** [hrydgard/ppsspp#6648]
Hi!

When I try to save state in my games, I get an error message which tells me that my memory is full then PPSSPP freezes even though I have 1 GB of free memory on my E and F drive, and 80 MB on my C drive.

```
Phone: Nokia 701
OS: Belle FP2
PPSSPP version: v0.9.9-37-g682e1c1
```

Help please.

**Comment by unknownbrackets** [comment]
Is this still an issue in the latest version?

-[Unknown]

**Comment by Xlander11** [comment]
@unknownbrackets sorry for the late reply.

Yes, it's still crashing.

**Comment by unknownbrackets** [comment]
Can you give a screenshot of your free memory (or just the number), while PPSSPP is running, in a newer version right before you try the savestate that crashes?

-[Unknown]

**Comment by Xlander11** [comment]
@unknownbrackets, I have 238.5 Mb of free ram while PPSSPP( v 1.00-80 the latest ) is running.
E:\ 1.33Gb
F:\ 2.2 Gb

**Comment by unknownbrackets** [comment]
Well, that should be plenty.  @xsacha this is so weird, is there any way to try to get a useful stack trace from the crash?  Or at least hang while it's crashed and check free memory?

We may definitely not handling running out of RAM well at all.

-[Unknown]

**Comment by xsacha** [comment]
I don't think I can get any extra info. I tried running in debug with debugger attached once (only works in Windows) but I couldn't even get that far, due to other issues.
In release mode, it may be dipping to 0MB memory temporarily, too quick to see? Although, the device has a lot of RAM so not sure that's even an issue.

**Comment by jawonder** [comment]
Using (Dev-Latest)  1.0.1-782, i'm having problem saving state on iPhone 6 plus . Getting "Failed to save state".

**Comment by unknownbrackets** [comment]
That's not a low enough memory device to have anything to do with this particular issue.  Your issue may have to do with permissions.  That's a common problem people have with PPSSPP on iOS due to the way some iOS file managers or something manage permissions.

-[Unknown]

**Comment by jawonder** [comment]
Hey unknownbrackets, you are absolutely right , it was a permission issue . working fine after i fixed permissions. Thank you

**Comment by hrydgard** [comment]
What directories had the wrong permissions? Maybe we can detect and fix it or show some instructions.

**Comment by unknownbrackets** [comment]
Generally the PSP/ folder or PSP/PPSSPP_STATE or etc.  They are often owned by a user other than the other PPSSPP runs as, and chmod 755 or something, so not writable.

-[Unknown]

**Comment by jawonder** [comment]
Fixed permission for all three folder :-

PPSSPP_STATE

SAVEDATA

SYSTEM

I made all three permissions  :- Read, Write, Execute.

**Comment by unknownbrackets** [comment]
We did fix one issue in savestates that was causing crashes.  It's possible that memory allocation behavior on these devices made the crashes more likely.  Any change in the latest git builds?

-[Unknown]

**Comment by Xlander11** [comment]
Sorry, I can't test it, my phone is unusable. 
Sorry :(

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
