### ISSUE TITLE
Remaining issues with depth testing precision/clamping

### ISSUE THREAD

**Issue by thedax** [hrydgard/ppsspp#6660]
A lot of games still have depth problems, so let's gather them here for a meta-issue, but not ones that need OpenGL 3 (Jeanne, Danball, Saint Saiya), since that's a limitation of hardware.

~~Cars - Race O Rama: https://github.com/hrydgard/ppsspp/issues/4112~~
~~Kingdom Hearts: BBS (Android only? I never noticed any problems with it on Win32): https://github.com/hrydgard/ppsspp/issues/3058~~
~~Phantom Brave: https://github.com/hrydgard/ppsspp/issues/4064~~
~~Phantasy Star Portable 1: https://github.com/hrydgard/ppsspp/issues/3777~~
~~Phantasy Star Portable 2: https://github.com/hrydgard/ppsspp/issues/1788~~
~~Puyo Puyo Fever 2: https://github.com/hrydgard/ppsspp/issues/3663~~
~~NBA 2K13 (possibly? We need someone to look at it): https://github.com/hrydgard/ppsspp/issues/6603~~
~~Ratchet & Clank: https://github.com/hrydgard/ppsspp/issues/6105~~
Dream Club Portable (possibly?): https://github.com/hrydgard/ppsspp/issues/6497
~~Blazing Soul Accelate: https://github.com/hrydgard/ppsspp/issues/4665~~
Pilot Academy: _No issue created yet_ (NPC planes can be seen crossing in front of buildings they should be going behind)

I've marked some games as "possibly?", as I'm not entirely sure if their problems are depth related or not. We can discuss that in the comments.

_Note: This is not an issue to ask for fixes, ETAs, etc. I know some games are quite desirable to be fixed, but please, let's keep it on topic._

**Comment by ofry** [comment]
Kingdom Hearts: BBS (Android only? I never noticed any problems with it on Win32): I got it in Win7 x64.

**Comment by ofry** [comment]
https://github.com/hrydgard/ppsspp/issues/3058

**Comment by ofry** [comment]
Kingdom Hearts: Birth by Sleep Final Mix

Now my issue with buffered rendering has solved after v1.0.1-769-gc4ea4e3

Please test it on Android smartphones...

**Comment by ofry** [comment]
https://github.com/hrydgard/ppsspp/issues/7877 Blazblue Continuum Shift 2 (ULUS10579)

**Comment by vgturtle127** [comment]
I have a similar issue as well on both v1.1.1 and the latest Git build. Here is the screenshot:

![ucus98633_00000](https://cloud.githubusercontent.com/assets/3183676/12076568/c5c53d14-b176-11e5-940f-01f0f2fd90bb.png)

**Comment by unknownbrackets** [comment]
Random thought: if clipping is disabled, I wonder if depth can go outside the range?  Like if I set the range to 32767.5 +- 1.0f.  Or my 1.5f example above.  Hmm.

-[Unknown]

**Comment by unknownbrackets** [comment]
I wonder if we could use `GL_DEPTH_CLAMP` in throughmode?  I think I found it clamping depth.

-[Unknown]

**Comment by hrydgard** [comment]
GL_DEPTH_CLAMP is not universally supported though, would be nice to do without it..

**Comment by unknownbrackets** [comment]
So did some more testing, and found something interesting.

If I set the depth range to 32769.0 +- 32767.5, then that should set my range to [1.5, 65536.5], right?  Except that any fragments outside [0, 65535] will get discarded based on the minz/maxz test.

Anyway, in this situation, z = -1 maps to 0002, and z = 1 gets discarded.  As expected.  But, `z = (-32767.5 - 1) / 32767.5`, or in other words a z less than -1, does NOT get clipped.  Instead if maps to 0001.

So then I realized I had not sent a `sceGuEnable(GU_CLIP_PLANES);`.  After sending that... unexpectedly, depth was not clipped at all.  Instead, it was clamped.  Now, all my draws (which are all flat by the way) are succeeding, changing the color, and setting depth values.

So... yeah.

-[Unknown]

**Comment by unknownbrackets** [comment]
Okay, so after thinking about this, here are my ideas:

1. When using a "full" depth precision range, take a slice 1/4 the size in the middle, by scaling and offsetting appropriately in the projection matrix.  This means ~22 bits of precision which is still good.

2. If `(clipEnable & 1) == 0`, then we would set the depth range based on minz/maxz only, ignoring viewport.  This will make GL clip for us.  Viewport will get handled by altering the projection matrix.

3. If `(clipEnable & 1) == 1`, then we check minz and maxz.

   3.1. If minz > 0, we use that as the depth range.  Otherwise, we use 0 (300% of our depth range away.)

   3.2. If maxz < 65535, we use that as the depth range.  Otherwise, we use 1 (300% of our depth range away.)

   3.3. Values < -4 and > 4 would still be clipped, instead of clamped, but most games already seem to work, so this may be fine.

   3.4. Where supported, we can also use `GL_DEPTH_CLAMP`, which will work around the 3.3 issue.

4. Perhaps we add an ini-only setting to do per-fragment clamping.  I'm thinking we can ignore it, and just let the values lay outside our "slice".  Not accurate, but not slow either and will probably match most scenarios.

5. There's also a rounding issue.  In general, [-0.5, 65536) seems like it might be allowed for standard [0, 65535] clamping.  We could try adjusting the depth range slightly to account for this.  Need more testing to be sure.

6. All this needs accounting for with depth rounding.

7. Pretty sure the software renderer doesn't handle some of this right either.

-[Unknown]

**Comment by unknownbrackets** [comment]
Valkyria Chronciles 2 is also affected by the rounding / clamping issue:

http://forums.ppsspp.org/showthread.php?tid=433&pid=116239#pid116239

-[Unknown]

**Comment by unknownbrackets** [comment]
I added some additional notes in #12058 based on further testing.

-[Unknown]

**Comment by Gamemulatorer** [comment]
This still an issue?

**Comment by unknownbrackets** [comment]
I think the depth behavior on the PSP is mostly simulated now (just that some devices can't handle it), and working well on a range of devices.  We still have some issues but they're separate already and I think the issues this was tracking are generally all fixed.

So, going to close it.

-[Unknown]
