### ISSUE TITLE
Some issues on 0.9.9 release

### ISSUE THREAD

**Issue by lucasgta95** [hrydgard/ppsspp#6673]
Using Xperia SP
Starting on
Tenchu: Shadow Assassins
Much slow performance, checking some performance options don't speedup

Mana Khemia: Student Alliance
Game running perfectly with 60 FPS patch, but battle is laggish and sound is shitting as well...

The good side is Dissidia 012 is running perfectly on buffered rendering with all graphic performance options checked (except mipmapping)...

**Comment by unknownbrackets** [comment]
It sounds like you're just complaining that the release didn't make these games faster on your device.  Did these games get slower?

For ideas to improve performance, I recommend going to the forum.  If the performance did get worse, a range for when this happened would help.  Otherwise, it may just be a fact of more complex rendering being slower.

Going to close this issue.  If you can comment with helpful details, will reopen.

-[Unknown]

**Comment by lucasgta95** [comment]
This post is from 1 year ago, things must be better now
