### ISSUE TITLE
MGS Peace Walker - ULES01372 : Wrong text on pickups ranks

### ISSUE THREAD

**Issue by Pallanas** [hrydgard/ppsspp#6688]
When standing near an item you can pickup, if the name of the item contains stars indicating its rank it will always indicate five stars, while when you pick them up you see that it's not the actual rank of the item (= the number of stars differ, check the screenshots below if my explanation isn't clear enough).

As I only played the game ~1 hour I'm not sure if it's 100% reproducible but it seems fairly consistant at the moment. Noticed this bug with rations in the second main ops stage and with both rations and fulton sys in the third one (cf screens).
![ules01372_00000](https://cloud.githubusercontent.com/assets/1473063/3799632/883e6402-1bef-11e4-8c2d-8b65540fb44b.png)
![ules01372_00001](https://cloud.githubusercontent.com/assets/1473063/3799633/88482c62-1bef-11e4-8eb6-9998e4d97366.png)

PS : Thanks for this emulator which seems to work like a charm, I hope someday I'll be able to help out with the development :)

**Comment by unknownbrackets** [comment]
Is this still happening?  It might be some sort of texture hashing bug - make completely sure that "vertex cache" and "lazy texture caching" are both off.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
