### ISSUE TITLE
Brave story - graphics glitches (debugged)

### ISSUE THREAD

**Issue by whyisthisfieldhere** [hrydgard/ppsspp#6754]
Hi, I found a few issues in brave story (hardware graphics) and debugged them to varying degrees.
In order of most to least simple to fix / likely to be fixed:

1) Smoke & fire are colored oddly with hardware graphics (also see https://github.com/hrydgard/ppsspp/issues/6332).
From debugging, it looks like the smoke primitives contain various color data and the GE's shademodel is set to GE_SHADE_FLAT.
The software renderer appears to check for the value of shademodel and ignore all but the first color in this case, resulting in the correct image.
However, it looks like no other renderers check shademodel, likely resulting in the colorful smoke.
This should be easy for a dev to fix, I think.   (NOW FIXED)

2) Enemy colors don't always differ in hardware graphics: (Notice color of right bunny in below screenshot in software vs hardware)
From debugging, it looks like brave story sets the framebuffer to the clut area (with inappropriate framebuffer height) and draws colors into it. It then uses the clut for drawing the texture.
In software, you can see that the clut area in memory gets updated between the first and second rabbit.
In hardware, you can see that the clut area in memory doesn't get updated in this case.
(I'm not sure how it's updated at all in hardware, to be honest)

3) With vertex cache set (which is the default), there is serious flickering in the worldmap. Perhaps vertex cache shouldn't be enabled by default until it's more reliable?

screens of bug 1 & 2:
Hardware:
![hardware](https://cloud.githubusercontent.com/assets/8498306/3976241/704084a0-281c-11e4-99e9-24e943fe32e6.png)
Software: (no bug)
![software](https://cloud.githubusercontent.com/assets/8498306/3976239/55c2b54e-281c-11e4-9ffb-4ddb6746ff1d.png)

**Comment by unknownbrackets** [comment]
Even forcing the vertex cache to rehash every draw, the flicker is there still.

I also tried disabling draws by vert count (they're all either 4, 18, 138, 384, 3750, or 6528 in the area I was testing.)  Different areas and types of flicker were caused by different counts of verts.  All but 4 used indexes, and disabling all using indexes did kill the flicker.

After drawing the background, it uses a texture (0x041977f0 in my case) to apply a texture to the ground (you can see the texturing in the video.)  It uses fixed blending to do this: `0 * src + src * dst`, or effectively `src * dst`.  The verts are *only* normals and positions (UVs are omitted, it uses tex matrix UV gen.)

The following completely eliminated the flicker:
```c++
		if (gstate.getUVGenMode() != GE_TEXMAP_TEXTURE_COORDS)
			useCache = false;
```

This only affected ~4% of draws.  So I think this means we have some bug in the vertex cache affecting UVgen.

-[Unknown]

**Comment by hrydgard** [comment]
Hm, interesting. What kind of bug could that be that would not affect drawing non-cached? We do have a slightly different path when uvgen is active but only when texture coord prescale is enabled..

**Comment by unknownbrackets** [comment]
I'm not sure.  I wasn't able to find anything - the shader id is the same, the vertex format is the same, etc.  The issue only happens when using a vbo - using an ebo but no vbo doesn't do it.  And prescale doesn't affect it.

Strange...

-[Unknown]

**Comment by unknownbrackets** [comment]
For reference, a version of render-to-clut that does work for this game:
https://github.com/hrydgard/ppsspp/compare/hrydgard:master...unknownbrackets:clut-render?expand=1

However, the performance hit is not good at all.  815% -> 420% in battle with the rabbits.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, that's surely the downloads killing performance. Will be even worse on mobile, most likely.. I fear we will have to "depal" on-GPU, either directly when rendering (so we have to do the filtering ourselves too) or in a prepass like we do with paletted texturing from framebuffers, as we discussed.

**Comment by unknownbrackets** [comment]
Indeed, I just wanted to validate the uploads to clut and etc. (since the rabbits are rendered differently - one is from a block transfer, the other from a render.)

The upload to clut isn't free either, but it's not nearly as bad.  Without download it's about 780%.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, uploads are much cheaper because they can be queued by the driver and do not stall the rendering more than the time to copy the data to the driver's buffer queue, while downloads require the gpu to catch up to a certain point and sync, which is terrifyingly expensive in comparison, as you know.

**Comment by daniel229** [comment]
Also fixes https://github.com/hrydgard/ppsspp/issues/6162

**Comment by unknownbrackets** [comment]
Neat, thanks for testing.  I should've realized it might be doing that.

@hrydgard, would it be better to upload as single channel?  It's tempting to try to upload the raw texture directly, but I think we'd need to translate everything (definitely at least 4-bit) to 8-bit first.  Then, maybe upload as GL_ALPHA / GL_RED depending on GL version?

With my other change (tex-split), we can potentially detect 1:1 texture draws, might might allow us to make different choices in where we decode the texture.  But I suppose the simplest thing would be to process it first (like fb depal.)

Not sure if it makes sense to try to combine this code into the existing depal.  Maybe not...

-[Unknown]

**Comment by unknownbrackets** [comment]
I haven't necessarily given up on #8246 yet, but I'm not really sure how much gain we'll see from it now...

Anyway, this particular issue is fixed, I believe.  The vertex cache flickering is still there a bit, but not as bad.  I would personally like to disable by default, but it's still a big speedup on some devices and in some games.

Can reopen if I missed anything.

-[Unknown]

**Comment by LunaMoo** [comment]
Reopening since it still seems to be a thing and differ depending on backend:
 - OGL - enemies are usually completely invisible, their effects like fire are looking correct through
![ulus10279_00001](https://user-images.githubusercontent.com/5485237/34121849-c62778e2-e42a-11e7-8bf6-c477b7cdb054.jpg)

 - D3d11/D3d9/Vulkan - some enemies are partially flashing or partially invisible - I guess not with those birds, but they have other problem and their fire effects have rainbow colors:
![ulus10279_00002](https://user-images.githubusercontent.com/5485237/34121941-0df41680-e42b-11e7-8247-bfd343c1af0a.jpg)
(enemies below are from earthrift / optional dungeon at the north east island)
![ulus10279_00003](https://user-images.githubusercontent.com/5485237/34122227-018dd1dc-e42c-11e7-8cf2-325e495cf664.jpg)


 Weirdly the graphics sometimes display fine, or the problems are reduced by disabling and re-enabling slower effects, using savestates seem to also affect it in various ways.

 The problem doesn't show on frame dumps, so here's a post-game savedata which has access to pretty much every place on the world map with dragon travel(triangle -> other -> Vyne) as well as ability to freely swap party members as some special attacks might also be affected/buggy on it's own.
[ULUS102790002 post game.zip](https://github.com/hrydgard/ppsspp/files/1569028/ULUS102790002.post.game.zip)

**Comment by unknownbrackets** [comment]
The game does drawing for characters to render CLUTs - it sounds like this is what's going wrong on your card, maybe?

Vulkan definitely has messed up effects for me, but OpenGL - I messed around and didn't see any missing parts or invisible enemies.  I only tried like 5 or 6 battles though - how common was it for you?

I think the CLUT download isn't fully working on non-GL, though... that or flat interpolation isn't.

-[Unknown]

**Comment by LunaMoo** [comment]
Heh, so another driver bug it is.. as for me every single fight in OGL has invisible enemies. Unless I disable slow effects only their special effects like fire in those birds can be seen. Stupidly OGL is the only backend where that fire actually looks ok:P.

 I tried to see if it's not a regression, but in older versions PPSSPP was just crashing when trying to boot that game in OGL for me.

**Comment by unknownbrackets** [comment]
Hmm, crash on boot in this game was caused by (and I think has always been caused by) "read framebuffers to memory".

-[Unknown]

**Comment by hrydgard** [comment]
It's really time to rip out those modes now... I know, I know, some rare game still needs it but they're clearly way more trouble than they're worth.

**Comment by LunaMoo** [comment]
I never use read framebuffers to memory, so I'm quite sure it's my AMD ogl drivers:C. But yeah the option itself doesn't have much reason to be available. Many people might consider going from skipping buffer effects through buffered rendering as a gradation and consider read framebuffers to memory as the best which is really bad.

**Comment by LunaMoo** [comment]
Actually turns out I lied about testing latest buildbot not crashing, it still crashes, I just confused with my custom build. So official version doesn't have missing graphics in OGL, it simply crashes.

 Also I found out it's caused by be removal of legacy BGRA path, that also caused missing graphics in Final Fantasy on AMD gpu's as can be seen [here](https://forums.ppsspp.org/showthread.php?tid=1971&pid=127526#pid127526). Except in this game it simply crashes:c.

**Comment by unknownbrackets** [comment]
On NVIDIA, all backends look good.  Is this still an issue on AMD with the latest git?

Note: make sure vertex cache is off.  It's now off by default, except when OpenGL is the default.

-[Unknown]

**Comment by unknownbrackets** [comment]
How does this look now on AMD devices?

Note: The BGRA path has probably been removed again with the latest rewrite, but hopefully it still works.

-[Unknown]

**Comment by benderscruffy** [comment]
Please close as this has not been updated in years

**Comment by unknownbrackets** [comment]
I think this is probably fixed, not sure about AMD devices but hopefully we're in a good place now.  Probably should create new issues if there are new problems.

-[Unknown]
