### ISSUE TITLE
text problem in Valhalla Knights.

### ISSUE THREAD

**Issue by piau9000** [hrydgard/ppsspp#6766]
There's some text problem in Valhalla Knights in where some characters does not show up or keep flickering.
Here's some screenshots.
![text1](http://i.imgur.com/FGXzJN5.jpg)
As you can see there's a lot of missing letters like the top where it should say something like "please use your bonus points" and the numbers where the value for VIT is missing.
If you move the feater to VIT the value shows up but the value for RES dissapear.
![text2](http://i.imgur.com/WEEH30x.jpg)

This happens in other places in the game too. It seems to be some character limit.

**Comment by unknownbrackets** [comment]
Thinking about this, flooring the value should make sense no matter what, since we don't want `65534.5 / 65535.0` no matter what.  The PSP only supports even divisions anyway.

Anyway, here's the #7516 version:

```
// 32-bit
const float z = (int)pos[2] * (1.0f / 65535.0f);
pos[2] = z > 1.0f ? 1.0f : (z < 0.0f ? 0.0f : z);

  cvttss2si eax, pos[2]
  movss xmm1, &1.0f
  movd xmm0, eax  
  cvtdq2ps xmm0, xmm0  
  mulss xmm0, &(1.0f / 65535.0f)
  comiss xmm0, xmm1
  ja above

  xorps xmm1, xmm1
  comiss xmm1, xmm0
  ja above
  movaps xmm1, xmm0

above:
  movss pos[2], xmm1
```

This seems pretty reasonable to me, and resolves it.  If I don't cast to int, the problem still exists.  I'm not 100% sure why it's only affecting 32-bit still, but casting to int should be more correct anyway.

-[Unknown]
