### ISSUE TITLE
Stop Working

### ISSUE THREAD

**Issue by Kurozawa** [hrydgard/ppsspp#6915]
when I play the SAO and the 80th floor boss fight, suddenly my PPSSPP stop working and my computer too. what happen..?

**Comment by unknownbrackets** [comment]
If your computer stops working, most likely it's a problem with your drivers.  I would definitely suggest updating them.  It could also mean you have faulty RAM or other hardware.

Since PPSSPP should (theoretically) not be capable of taking down your entire operating system, and no one else has reported this, I'm going to close it.  If you have more information, please feel free to comment and we'll reopen.

-[Unknown]
