### ISSUE TITLE
Ys I & II Chronicles hangs randomly on title

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#6966]
Since https://github.com/hrydgard/ppsspp/commit/c5b15cc9fcf337c2e8e60d789b666ff0b0fcff67
revert that,it works fine.~~release build with PSP 2000 model and debug build with any models work fine even not revert.~~
Revert that commit or just comment out these
```
//hleEatCycles(900);

//hleEatCycles(500);
```
![01](https://cloud.githubusercontent.com/assets/3481559/4493623/ffc380e6-4a4a-11e4-92f2-ce8ffc56ac05.png)

**Comment by unknownbrackets** [comment]
So, yeah, it almost always sleeps for ~3541969 cycles, but when it dies, it's always 2701 cycles.

Interestingly, 4207 cycles works.  If I make it never wake at exactly 2701 cycles, it never freezes.  That's interesting...

Also, making drawing take longer, even ridiculously longer, doesn't make any difference.  Hmm.

-[Unknown]

**Comment by unknownbrackets** [comment]
So, I realized that the small number of cycles it takes to die is about as long as it takes to reschedule.  This got me thinking: if I'm right about to enter a vblank, will it really only sleep 12 us?  That seems impossible, since even `sceKernelDelayThread()` etc. typically doesn't have that accuracy.

Based on my testing, if you try to begin a wait >= 16500 us (give or take a couple us) into the frame, it takes an extra frame to wake.  This makes sense because it probably even takes time to slot it into the process anyway.

I think that's the right fix for this issue, too, because it will avoid weird timing issues.  If you near the next vblank, it's basically like you're at it already.

-[Unknown]
