### ISSUE TITLE
Final Fantasy I framerates drop

### ISSUE THREAD

**Issue by metaasza** [hrydgard/ppsspp#7229]
When I was roaming in the map, framerates were dropped as I can notice that my character walks slower. I use ppsspp v0.9.9.1-1296-g8ec0069 android version(Galaxy S III). Thank you for your attention.

![image](https://cloud.githubusercontent.com/assets/10046089/5556795/91e269a8-8d1a-11e4-862e-f13c8096a334.jpg)

![image](https://cloud.githubusercontent.com/assets/10046089/5556791/6d2963aa-8d1a-11e4-882b-448c343cdab8.jpg)

**Comment by klyoungblood** [comment]
I've done some testing related to this, and it appears the world map screens in both Final Fantasy I and Final Fantasy II have extreme FPS drops on ARM hardware. Reproduced these issues on both Raspberry Pi 3 and a Ellipsis 8 tablet, both with ARM A-7 cpus.

**Comment by unknownbrackets** [comment]
Are there any settings, such as "skip buffer effects" or "block transfer" that change that behavior?

Worth noting - the devices you noted have  VideoCore 4 and Vivante GC2000, respectively.  Both are probably not the fastest or most full featured GPUs on ARM...

The original poster has a Mali-400 MP4 or Adreno 225, though, which aren't powerhouses either but shouldn't necessarily have special problems.  Will probably need to try benchmarking it.

-[Unknown]

**Comment by klyoungblood** [comment]
Had no speed improvements from changing graphics settings. Also reproduced it on a Galaxy S5, which is admittedly a bit old by now. No sign of this slowdown on a mid-spec Windows x86-64 system.

**Comment by unknownbrackets** [comment]
Hm.  With a Marshmallow Nexus 5 (very similar to the Galaxy S5's except the SM-G900H), I'm getting basically full speed.  I say basically due to the display timing on the [Nexus 5](https://code.google.com/p/android/issues/detail?id=82922) - I get the usual near-60fps with frameskip off and smooth with auto frameskip 1.

I tried walking down to the edge, then up from the start to the cave and then back down to the town.

This is with the USA version of the game, and PPSSPP v1.2.2-785-g1f7a137.  I had vertex cache off, 1x PSP render, 2x aniso, host IO timing, and otherwise default settings.

-[Unknown]

**Comment by klyoungblood** [comment]
I'm only seeing a mild slowdown on Final Fantasy I on the S5, but a more severe slowdown on Final Fantasy II. I suspect they are the same root cause. Would you prefer I log a separate issue for Final Fantasy II?

**Comment by unknownbrackets** [comment]
No, Final Fantasy 2 is a completely separate monster.

The slowdown there will be experienced everywhere (to different degrees) and is caused by the way it does palette swapping (which is not very friendly to OpenGL.)  What you're seeing is actually the result of multiple optimizations that have yielded large performance gains - it used to be completely unplayable on any mobile device, it was so slow.

Worth noting - have experienced pretty decent gains on desktop Vulkan with FF2.  There's some hope that may help on mobile when we have it working on Android.

Final Fantasy 1 doesn't do the same thing, though.

-[Unknown]

**Comment by klyoungblood** [comment]
Thanks for setting us straight. I'm not sure this is even a PPSSPP issue so much as weak GPU hardware then.

**Comment by unknownbrackets** [comment]
Well, if certain areas are slower than others in Final Fantasy 1, there might be something that can be done... but yes, it may just be a hardware limitation.

@metaasza have you tried this with a more recent version of PPSSPP?  There have been optimizations since v0.9.9.1-1296-g8ec0069.  We're basically at v0.9.9.1-6324-g2015d68 now, so ~5000 commits further along.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
