### ISSUE TITLE
 libSDL2-2.0.so.0 not found

### ISSUE THREAD

**Issue by TheKiwi5000** [hrydgard/ppsspp#7233]
Hello,
I am very happy to see somebody made PSP emulator on linux, but i can't start it. This is the log:
 
./PPSSPPSDL: error while loading shared libraries: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
How can i fix it?

Using dev-working version

**Comment by lightfirst** [comment]
sudo apt-get install libsdl1.2-dev libsdl2-gfx-dev libsdl2-gfx-1.0

**Comment by Bigpet** [comment]
You don't need any of those `libsdl1.2-dev` is the old 1.2 version, `libsdl2-gfx-dev libsdl2-gfx-1.0` are two packages that are graphics extensions to SDL but we only use SDL to open the window, not to draw with it (but installing those packages would work since they depend on the actual SDL2 packages).

You only need `libsdl2-2.0-0` to run it, and the `-dev` package to compile

**Comment by unknownbrackets** [comment]
I'm going to assume that resolved it.  If it didn't, please comment, but I suppose it's better to look for help installing system packages on the forum.

-[Unknown]
