### ISSUE TITLE
Monster Hunter Portable 3rd HD - adhoc related crash

### ISSUE THREAD

**Issue by tywald** [hrydgard/ppsspp#7237]
First of all, I didn't know there was a place where you could report issues until now so I used the forums.
Original thread: http://forums.ppsspp.org/showthread.php?tid=14149

This is an adhoc related crash in Monster Hunter Portable 3rd HD where it will freeze sometimes when you open the guild hall window or enter a guild hall.

To reproduce: Either join someone else's adhoc server or start your own and walk up to where the guild hall is: Then simply open and close the "guild hall window". Repeat until you crash. Shouldn't take more than a minute.

Version I used was: <b>v0.9.9.1-1316-gfd1a748</b>

<img src=http://i.imgur.com/Km6S5W4.png>
<img src=http://i.imgur.com/AjYHRH7.png>

**Comment by tywald** [comment]
I tried with older versions and it doesn't crash on 0.9.8 but it does on 0.9.9. I'm going to try pin point what revision it started crashing. The log is also a bit different on 0.9.8. I went for a good 5 minutes, no crash. When I changed to 0.9.9 I crashed within 10 seconds.

It appears to be faster as well, when I join someone's server. Currently when the ping is pretty high it's like the emulator is having a "hiccup" when it's opening the guild hall menu and joining a room. But it doesn't do that on 0.9.8. There is just a slight delay then it immediately goes through.

<img src=http://i.imgur.com/2cAV8GJ.png>

**Comment by hilesaz** [comment]
Putting a breakpoint at 0x088307f0 and then just letting it run causes this to always happen for me.  That and some other odd behaviors regarding breakpoints around this function make me suspect this is actually a jit bug.

**Comment by unknownbrackets** [comment]
Unfortunately, 7f7b2a3800f4682f72c6e24b858c14cb0f270672 is a huge commit and wasn't really broken up, so it's difficult to tell what part may have caused the problem.

Does it actually crash in jit?  What's the stack trace?  You can get one using Visual Studio and compiling it.  There are instructions on how on the forum, it's not hard.

http://forums.ppsspp.org/showthread.php?tid=5231

-[Unknown]

**Comment by hilesaz** [comment]
Setting a breakpoint at the entry to the function, 088307e4, and then hitting step into jumps you to 0887c36c which appears to be completely unrelated.  If I instead hit step over, it doesn't move the PC and zeros a0.

**Comment by unknownbrackets** [comment]
Well, that probably means that the adhoc code is changing the pc from off thread in in advance.  When you step, you end up calling Advance right after stepping.

The networking code currently uses ScheduleEvent_Threadsafe_Immediate from a separate thread.  This will never produce deterministic behavior, because when it interrupts the CPU will depend heavily on network speed, latency, etc.

It probably ends up scheduling the event while the breakpoint is paused, e.g. while you are looking at the debugger.  Then you get deterministic results of it always failing.

I'd mentioned before (maybe it was in #6749?) that a better way would be to drop things into a queue (with locks) from the thread, and then on the CPU thread set a timer on a well-defined interval to check said queue.  This way interrupts would reliably happen at defined times (maybe it should even be near vblanks, I don't know...)

Based on the threads `sceNetInit()` creates, I assume it probably polls the hardware on real PSP firmware, in this same sort of way, rather than getting CPU interrupts.  I don't know when it polls though, but it'd probably be possible to create tests to figure it out.

-[Unknown]

**Comment by hilesaz** [comment]
Yeah, it looks like making __KernelExecuteMipsCallOnCurrentThread save A1 as well makes this problem go away.  That's pretty bad for it to non-deterministically change around registers.

**Comment by unknownbrackets** [comment]
It's really not safe to call __KernelDirectMipsCall anywhere except:
 * From an HLE syscall (where you're destroying the volatile regs.)
 * From the idle threads (e.g. on an interrupt, which has to be switched to first.)

-[Unknown]
