### ISSUE TITLE
PSP2 Loading Issue

### ISSUE THREAD

**Issue by Heoz** [hrydgard/ppsspp#7280]
Multiplayer in lobby works but missions still can't get in xD i saw that in windows 7 can't enter but in windows 8 can

**Comment by unknownbrackets** [comment]
Is this working better given recent improvements to the networking code?

-[Unknown]

**Comment by ANR2ME** [comment]
PSP2 and PSP2i working fine on LAN, not sure over the internet

**Comment by unknownbrackets** [comment]
This issue is being closed because it appears to be fixed and was created some years ago.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
