### ISSUE TITLE
Final Fantasy II slow on world map due to excessive sceKernelDcacheWritebackInvalidateAll calls

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#7286]
This causes speed to drop from 800fps to 250fps on my PC, and likely much worse on mobile. 

It seems to call this function a lot (as much as 16 times per frame) due to being too lazy to specify the actual range of texture or vertex data it may have changed. Our current hashing works pretty well here so simply disabling this does not seems to affect the game badly in any way.

So, what do we do? The PSP CPU data cache is very small so zapping the whole texture cache on this call is guaranteed to be excessive, but on the other hand we can't know what the game changed, we just have to hope that our data hashing catches it.

I don't want to say "game specific hack" ... but I wonder if any games do break from simply disabling this function. We already disable this function every frame when the count reaches 5 calls this frame.

**Comment by unknownbrackets** [comment]
Hmm, I hadn't really looked at the world map because the town was enough trouble.

Anyway, GPU_INVALIDATE_ALL / InvalidateAll does NOT zap all textures.  Anyway, when you're not using the backoff cache, it already doesn't do anything.

Lazy texture hashing actually makes this game a good bit slower in general.  Note that it is off by default.  The whole point of hashing every time was to not have to deal with invalidations, and to have better accuracy.

-[Unknown]

**Comment by hrydgard** [comment]
Doh, I did have the two cache options on for some reason. Also, for some reason I cant reproduce the slowness I saw yesterday???  I saw it spending unusually much time in texture hashing but I can't get it to do that now...

Ignore this for now, sorry.

**Comment by unknownbrackets** [comment]
Well, it may have been where you were precisely.

For example, I recall that near water when birds are flying in the sky is particularly bad (it may spend tons of time rehashing the texture because it is actually changing a lot, iirc.)  Propagating the hash mismatch to all clut variations really helped this, though, iirc (in addition to not rechecking the current texture when only certain params were changed.)

-[Unknown]
