### ISSUE TITLE
Ikkitousen XROSS IMPACT, returns internal error when trying to initialize Adhoc

### ISSUE THREAD

**Issue by issuer** [hrydgard/ppsspp#7310]
![npjh50222_00000](https://cloud.githubusercontent.com/assets/10441372/5691422/dfcbc2b6-98ac-11e4-80c1-2a8da091b602.jpg)
![ikkicrossimpact](https://cloud.githubusercontent.com/assets/10441372/5691423/e55077ae-98ac-11e4-8f17-15029169a6b7.png)

Due unimplemented functions, maybe. Still, thought this was interesting. It's the only game i've got that actually returns an internal PPSSPP error when trying to initialize Adhoc functions.

**Comment by unknownbrackets** [comment]
Just for reference, that error is ERROR_NET_ADHOC_INVALID_ARG.  PPSSPP returns it in some cases, not sure if it's accurate.

-[Unknown]

**Comment by issuer** [comment]
I've opened the game and went straight to the AdHoc hosting. After the error, stopped and closed the emulator. Here is the full Debug log:
https://www.dropbox.com/s/n8mqkmkv2eszscu/IkkitousenXI_Adhoc_ppsspplog.rar?dl=0

**Comment by benderscruffy** [comment]
PPSSPP v1.5.4-995-g373366911 Windows 64 bit
still has the same problem

**Comment by unknownbrackets** [comment]
Is this still an issue, given recent improvements in networking code?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
