### ISSUE TITLE
AdHoc - set coldbird.net as default address instead of localhost?

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#7325]
This would make ad-hoc one step easier to set up.

Would coldbird approve? I have no idea really and found no email on the site :)

**Comment by unknownbrackets** [comment]
Note #2590, I thought I remember there being concerns with PPSSPP users cheating with the PPSSPP features.  I'm not sure if / how this is prevented on real PSPs.  Maybe I'm just wrong.

-[Unknown]

**Comment by hrydgard** [comment]
Well, the PSP itself is thoroughly hacked so that's nearly as much of an issue with real hardware. Also, JPSCP defaults to coldbird.net...

**Comment by lightfirst** [comment]
playing on coldbird.net require enabling dmz / upnp (if I am right, ppsspp no support upnp). another issue is ppsspp no support chatting room, can chatting with other plays on coldbird.net.
JPCSP support upnp and chatting room...

**Comment by issuer** [comment]
I've made a tutorial on the forums talking about this: http://forums.ppsspp.org/showthread.php?tid=14264

It's unfortunate PPSSPP doesn't support UPnP the way Evolve does for example. That's the only reason why many people need to install VPN programs to play online.
If PPSSPP supported something like UPnP, it would be much easier since most modern modems come with UPnP enabled by default, no messing around inside your Router. Plus, it would render any third party VPN program useless.

**Comment by MrColdbird** [comment]
I personally would welcome it if coldbird.net was chosen as the default ad hoc server.

I've been hosting it since I first started emulating the ad hoc libraries and intend to maintain it for an unforeseeable time along with my other network services.

I also root for a upnp implementation of some kind, as this should some 99% of all the issues PPSSPP players have with setting this up.

Furthermore it won't be as much of a problem to implement as the PSP one used in my native client due to the way better specifications of the devices PPSSPP runs on.

**Comment by hrydgard** [comment]
Thanks for your comment @MrColdbird !  I'll make the change then, and will later look into what we can do with uPNP.

**Comment by unknownbrackets** [comment]
Changed, so I suppose we should close this right?  #7268 is probably related.

http://miniupnp.free.fr/ or something might work for UPnP.

-[Unknown]

**Comment by hrydgard** [comment]
Right, #7268 is a better issue to keep open for UPnP, thanks.
