### ISSUE TITLE
[Ad Hoc] Player leave detection

### ISSUE THREAD

**Issue by vnctdj** [hrydgard/ppsspp#7331]
It seems that PPSSPP doesn't detect correctly when another player leave ad hoc / close his PPSSPP.
Here is an example :
There is 2 players in the Gathering Hall.
Player 1 close his PPSSPP.
The screen of player 2 still shows that player 1 is here, even if its debug log is showing that player 1 has disconnected.

When I enter the Gathering Hall :
![enter](https://cloud.githubusercontent.com/assets/3978690/5742128/1dd4fb98-9c10-11e4-9df3-a362b97a47e2.png)
When I leave the Gathering Hall :
![leave](https://cloud.githubusercontent.com/assets/3978690/5742143/468ed55e-9c10-11e4-88da-bac16ed0c13d.png)
And even this one that has appeared when I closed PPSSPP :
![leave2](https://cloud.githubusercontent.com/assets/3978690/5742159/6aaa522e-9c10-11e4-945b-b0378abc46b4.png)

**Comment by tywald** [comment]
Still occurring in 1.0 and it happens a lot.

**Comment by issuer** [comment]
I was able to replicate this issue. It seems it only affects MH games for some reason.
Versions of PPSSPP 0.9.9.1 without the Ad hoc branch merge, used to display a Pop-up window in-game asking you if you would like to connect to another Gathering Hall instead of this error showing up (The room is full). Maybe a regression would help here, since it was working fine before.

**Comment by vnctdj** [comment]
@issuer If you are talking about this :
![0](https://cloud.githubusercontent.com/assets/3978690/6004115/c85fec90-ab00-11e4-9571-abba69fa77f8.png)
Then this has nothing to do with PPSSPP as it's an in-game option to show the list of Gathering Halls or not.

**Comment by tywald** [comment]
People in our Evolve group became annoyed with v1.0 and are going back to older versions to avoid this bug for now. They preferred to have the random crash in 0.9.9.1 as it wasn't as frequent, but still happened quite a bit.

Since v0.9.8-1396-ga1d359f it was randomly crashing (MHP3rd HD) as I wrote a while back #7237 
Which was fixed when you added the new Ad Hoc branch in v0.9.9.1-1392-g1fa6710 but we got this bug now that is being discussed here.

I hope this will be resolved soon!

**Comment by hrydgard** [comment]
Thanks for reporting, I'll see what I can do but it won't make it to the 1.0.1 quickfix release. It's quite hard to tell what's going on in these strange network protocols...

**Comment by issuer** [comment]
@vnctdj No i wasn't talking this. When you entered a DH and it was full it would show the error message (The room is full) just like 1.0 but it would show another pop-up window asking you if you would like to change to another GH and it worked if you did. This pop-up is nonpresent after the Ad hoc branch merge.

**Comment by vnctdj** [comment]
@issuer Oh OK, no problem then :) By the way, I have never seen the "room is full" message :/

@hrydgard If some debug logs or anything else can help, please let me know :)

**Comment by tywald** [comment]
@vnctdj are you playing with a lot of different people? It happens very frequently here at least, especially when you finish a quest, leave the GH to visit farm / change equipment and then come back.

**Comment by vnctdj** [comment]
No, I don't play with a lot of different people. To be honest, it has been a very long time since I haven't played with a friend... I don't have enough time unfortunately :/
My tests are most of the time done between my PC and a virtual machine :)

**Comment by tywald** [comment]
I'm investigating this issue for MHP3rd(should also affect other MH games) and I set breakpoints in proAdhoc.cpp at line 1130 and 1140 and it never gets there.

When you join a GH and receive peer data it will call addFriend() as normal but when you disconnect it won't call deleteFriendByIP() so when 4 different users are added to "the list" it will fool the game thinking it's full when you try to join any GH even if it's an empty one.

line 1129: else if (rx[0] == OPCOE_DISCONNECT) seems to always become false?

I don't know if I can solve it but I thought I would let you know what's happening at least. I guess AdamN knows more about this.
