### ISSUE TITLE
compilation fails on bananapi Ubuntu 14.04

### ISSUE THREAD

**Issue by danboid** [hrydgard/ppsspp#7372]
Before I get onto my bug, I think the build instructions need updating to say that building PPSSPP requires SDL v2 to build now.

I'm trying to build PPSSPP for my bananapi which is running Ubuntu armhf 14.04. It uses a cortex A7 CPU so NEON should be supported but I get NEON related errors when I try to build it.

https://gist.github.com/anonymous/d8541c61ed1fa8c32722

I have tried building it with cmake after exporting this:

export CFLAGS="$CFLAGS -mfloat-abi=softfp -mfpu=neon"

only to get basically the same errors.

**Comment by unknownbrackets** [comment]
Is this still happening in the latest version?

-[Unknown]

**Comment by unknownbrackets** [comment]
I think this is fixed now, because of:
https://github.com/hrydgard/ppsspp/blob/99c2440d1465c0c7ce5c004539ce1fba804e4876/CMakeLists.txt#L40

It's possible that adding the flags to CFLAGS didn't help either because cmake caches CFLAGS (you have to delete CMakeCache.txt for it to pick it up again, I believe.)  But I know people were getting similar errors before due to enabling NEON different ways, and it's been cleared up.

There's still the issue of hardfloat and ffmpeg/etc., but that's #7394.

If I'm mistaken, please feel free to comment with what happens in the latest builds and we'll reopen.

-[Unknown]
