### ISSUE TITLE
God of war ghost of Sparta

### ISSUE THREAD

**Issue by shae23** [hrydgard/ppsspp#7411]
at the temple of Athena there is a section where you have to jump from one rope to the other, Keaton's should grasp the rope once you jump but he never does, he just keeps falling to his death

**Comment by vsub** [comment]
Can you post your save?
PC or Android version and which version exactly?

I cleared this game at least 4 times without any problems.

**Comment by shae23** [comment]
Version 1.0 & 0.9.9.1, played on Windows, Android and IOS, all have the same bug, i don't see an option to post save, can you give me your email for me to send it to you?

**Comment by shae23** [comment]
here is my save game a little before the rope jump bug  http://www.mediafire.com/download/edukq5sxpbb89bj/Ghost+Of+Sparta.zip    if you manage to get past it could you save at the next save point and send me the save?

**Comment by hrydgard** [comment]
Hm, is this the place where you really, really need to use an analog stick to swing? If so, try using the on-screen touch joystick.

**Comment by shae23** [comment]
![1](https://cloud.githubusercontent.com/assets/10815842/6010679/870730e4-aae9-11e4-92ae-eb728313cc10.jpg)

**Comment by shae23** [comment]
Here are screenshots of the area, no matter how many times i try he just doesnt grab the second rope, always falls to his death
![1](https://cloud.githubusercontent.com/assets/10815842/6010718/e112c7ba-aae9-11e4-9c2a-36d4cb785055.jpg)
![2](https://cloud.githubusercontent.com/assets/10815842/6010719/e11d5dce-aae9-11e4-9c6e-f60c6adc02a6.jpg)
![3](https://cloud.githubusercontent.com/assets/10815842/6010717/e10bc58c-aae9-11e4-87a6-2025a2acf930.jpg)

**Comment by hrydgard** [comment]
Strange. Looks like you are doing a downclock, does it do this even if you run the emulator at the correct clock? (set it to 0 for default)

**Comment by shae23** [comment]
Yes it does it even at the default 0, even with the default emu settings

**Comment by shae23** [comment]
Hey I set it to 0 and was able to make the jump, thanks for the help

**Comment by unknownbrackets** [comment]
Yeah, bizarre glitches that make games unplayable in weird ways are exactly the expected result from changing that setting.

-[Unknown]

**Comment by angiolucci** [comment]
I'm having this very same issue, with v. 1.0.1 on Android (x86).
I've set the clock to default (0), but it has no effect; Kratos always fail to grab the second rope.

I also changed screen resolution to 1xPSP, 2xPSP and device resolution (wich means 720x1280), but it did not work. I have no more ideas =(

**Comment by kafkas35** [comment]
Hey angiolucci here is whatsapp number +905364572667 send message to me 
ı will say solution to u

**Comment by kafkas35** [comment]
http://www.youtube.com/watch?v=hBRTMoX3iMY&feature=youtube_gdata_player

here is solution ;-)

**Comment by angiolucci** [comment]
@kafkas35, thank you, it worked. But I  had to enable the speed counter,
just like the video guy suggests at the video description.
So, the steps I did were:

1. Switched to the on-screen joypad;
2. At first rope, turned on the speed hack;
3. Turned on the speed counter;
4. While pressing the "play" button, jumped to the second rope.
(Here the 'magic' happens and Kratos successfully grabs the rope);
5. Jumped as usual to the roof.

Thanks for helping!
Em 05/08/2015 00:05, "kafkas35" <notifications@github.com> escreveu:

**Comment by kafkas35** [comment]
You r welcome brother ;-)

**Comment by ModiFlasher** [comment]
I try setting from you guys but there no take effect.
I think because from my Spec phone.
I'm using mediatek Processor
So much many time i try it but then always Fall Down...
Can you help me...???

**Comment by angiolucci** [comment]
I followed the steps from the above youtube video. Enabling speed counter
(not the fps counter) is also important (otherwise, you'll fail to grab the
rope).
I don't like this kind of black magic, but it's the only workround that
worked for me.

Hope it can help you too.
Em 26/08/2015 09:32, "ModiFlasher" <notifications@github.com> escreveu:

**Comment by ModiFlasher** [comment]
I don't know about Speed counter but you mean like this...???
http://i.imgur.com/yStL7yn.jpg

**Comment by angiolucci** [comment]
Yes! Sorry about that, I'm not using the english version, so I'm not sure
about the exact option. label.

I don't know about Speed counter but you mean like this...???
http://i.imgur.com/yStL7yn.jpg

—
Reply to this email directly or view it on GitHub
<https://github.com/hrydgard/ppsspp/issues/7411#issuecomment-134995059>.

**Comment by 360smchandan** [comment]
i tried everything but i cant jump to the second rope.please anybody send me all supported settings

**Comment by 360smchandan** [comment]
I tried everything from you guys but i cant jump to the second rope.Please anybody send all the supported settings.

**Comment by beverlyB** [comment]
i needthe SCreenshots of this settings

**Comment by scar139** [comment]
can any one save the game after passing the ropes and send the save to me..please..???

**Comment by gamershelp** [comment]
Hi! Friends are you crazy on god of war gost of sparta and using ppsspp.. are you facing the glitch problem? Like can't leaping to 2nd rope? Don't worry friends i think i can help you, i give you solutions contact me on  (michaeljack454@gmail.com)

**Comment by angiolucci** [comment]
If you have a solution why not to write it here?

This issue actually has no (in game) deterministic solution.
One day, it just worked. Once.

I don't have a save state anymore, but it is the best solution: use a save
state after this point on the game.

Good luck.

Em 26/10/2016 06:03, "gamershelp" <notifications@github.com> escreveu:

**Comment by deibid101** [comment]
but what happens if its in the psp? :'( no salvation?

**Comment by deibid101** [comment]
please guys :'( yelp :'(

**Comment by qerom** [comment]
![new bitmap image 3](https://user-images.githubusercontent.com/33870571/33078293-3aa05b5a-cef8-11e7-8d06-c9b95b9e9f
after inserting gear key ppsspp stuck at black screen

**Comment by hrydgard** [comment]
That sounds like a different issue, please make a new report. Also your image doesn't load for some reason..

**Comment by hikari82** [comment]
The solution is to set Change Emulated PSP Cpu clock to EXACTLY 222 mhz.  it should be an easy jump then. Thanks for this great software

**Comment by LunaMoo** [comment]
Setting it at 0 is the "correct" way as it allows the game to decide, even through most of the time it will request 222mhz, that's still a hack since game might request other value elsewhere and have different problems with enforced 222mhz.

 A lot of the confusion in here seems to be coming from people expecting for that option to work instantly from savestates made before the problem arises - which it really doesn't - as it only forces specific value WHEN game is calling specific syscall which some games might as well call only once on boot. Hence to make sure it's properly disabled when causing problems like in this game a restart of emulation and reload from normal in-game save should be required.

**Comment by unknownbrackets** [comment]
Maybe it would make sense to show a message when playing this game that it's known to have problems with locked, like we do for non-buffered?

-[Unknown]

**Comment by hrydgard** [comment]
@unknownbrackets Added such a message. Not sure whether the other God of War game might have a similar problem so left it out, but can of course be easily added in compat.ini.

**Comment by hikari82** [comment]
I set 222 mhz just for the jump .. off course after that i revert it back to auto.

**Comment by Bigbro4040** [comment]
I've tried all the steps you've described to no avail please help 
I'm using the ppsspp v1.5.4 I don't know if that's part of the issue

**Comment by vsub** [comment]
This is really weird.
I tried it once on the latest beta without changing anything other than the controls and on my first try,I encounter the problem.
Then I tried a ppsspp version I used long time ago to clear the game at least 3 times,and the problem did not appear.
Then I tried to use the same settings from the old version to the latest beta(no,I am not using the ini from the old version),and the problem did not appear again.
Then I tried one by one the settings that are not the default and every time the problem did not appear
In the end,I tried deleting the ini and try the game again and....no problem again

If someone is interested,I used v0.9.8-431-g839936d to clear the game and the options that are disabled there are(I was using MUCH weaker pc then and even setting the CPU speed to 80 but it also worked now and with Auto too)

Vertex Cache - on
Fast Memory - off
Multithreaded - off
I/O on thread - off
PSP Model - PSP-1000

Simulate Block Transfer did not existed yet(I tried turning it on/off too)and I don't know if ppsspp is using Multithreaded by default now

You have to load a memory card save because the save state is remembering your settings(and bugs)on those above so changing them makes it pointless if you use save states

During the testing the problem appear 1 out of 7 times loading the memory card save and go all the way to the rope

And also,I don't know if it is somehow related but I keep making save states on the puzzle before the rope because you have very little time to go down and jump on the platform that takes you up

**Comment by PhantomX9** [comment]
(Stone block is controlled by handle when you pull handle that stone will stay on floor and in few sconds it will goes up automatically) ,For that you have to set that stone block in front of " entrance door like area " then go back to that ladder climb up and pull tha handle to control that stone block ,you have to run very fast toward that block then wait till stone goes up in air automatically and then jump into next area.
