### ISSUE TITLE
Some games run full speed, some get 1fps and run at 18% speed

### ISSUE THREAD

**Issue by BonzaiThePenguin** [hrydgard/ppsspp#7418]
This is on an LG Tribute, which is quad-core 1.2 GHz and Android 4.4.2. LittleBigPlanet and LocoRoco run full speed, but then the God of War games and the Madden series run at a single frame per second with severe slowdown. I've tried turning the various video settings on and off and disabled audio but nothing seems to help.

Is this normal, like is it due to the complexity of the underlying games? LocoRoco I can understand being easier on the hardware than God of War, but LittleBigPlanet seems like it'd be heavier on the resources than Madden.

**Comment by unknownbrackets** [comment]
I don't know anything about Madden, but God of War is definitely way too heavy for a 1.2 Ghz / Adreno 305 to handle.

The reality is that, for game developers, the nice thing about consoles is that they're all the same.  It doesn't really matter if the Madden developers are sloppy as long as it runs well on hardware.  It doesn't really matter if the LittleBigPlanet developers are super efficient because it still runs on the same hardware anyway.

Generally the games with better graphics are harder, but it's not always the case.

You can try reading on the forum about options to improve speed.  For example, try enabling frameskip, check "disable slower effects", and make sure you're set to 1x PSP render resolution.  All of these things can help.

I don't think this is an issue we can do anything about, though, so i'm going to close it.  Probably better for the forum.

If we know that Madden is drawing things in a way that should be efficient, but there's something getting in the way, that's something we might be able to fix.  I don't have the game, so I can't tell.  You might try comparing it on a desktop - if it's also slower at high render resolutions / settings on a desktop, then that's probably just how it is.

-[Unknown]
