### ISSUE TITLE
Input issue with 60Hz

### ISSUE THREAD

**Issue by GamerzHell9137** [hrydgard/ppsspp#7426]
There's none Issue posted about it so i guess i'll make one.
75 Hz makes the input in rhythm games better, Unknown has said that it has to do with Vsync.
Other than the 75 Hz, changing to WASAPI, enabling Force Real Clock Sync, setting Audio Latency to Low and enabling the Audio Resampler makes the input perfect. Only downside to resampling is that it makes the music rougher/louder.

**Comment by unknownbrackets** [comment]
Are you able to turn off vsync in your video driver settings?  And make sure PPSSPP is not using vsync?

I mean, that should be the only difference between 60 and 75, really.  It shouldn't affect emulation except for the delay it imposes when flipping a frame, and that will only happen with vsync on.

-[Unknown]

**Comment by GamerzHell9137** [comment]
Yup, turning off Vsync fixes it but without it you get screen tearing..

**Comment by hrydgard** [comment]
I don't think there's anything in particular that can be done about it. The average time from keypress to seeing something might be slightly shorter in 75Hz, giving a better feeling even though it doesn't match the real psp framerate very well. We might be able to reduce audio latency a bit further, which should also help. I'm closing this because I can't think of any relevant actions to take.
