### ISSUE TITLE
Are these buttons of savestate too closed?

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7437]
Some people said it may get pressing wrong button.
![01](https://cloud.githubusercontent.com/assets/3481559/6057944/a6056508-ad5d-11e4-914b-ca790427ece1.png)

better change to
![02](https://cloud.githubusercontent.com/assets/3481559/6057951/b0faea0a-ad5d-11e4-8f4e-f8d034b97f5e.png)

**Comment by Pulfer** [comment]
Makes sense indeed.

**Comment by LunaMoo** [comment]
Except it looks even worse and both bugs anyone that was forced to learn literature in the school since repeating same phrase/words in a sentence or visually small area is pretty serious crime there:P.

 Does it even have to be there? As I see this, it's only really usefull and at the same time the distance between buttons might be problematic - for touchscreen devices. Previously to use that you had to select a slot then press save or load which equals to 2 clicks, if we would add a save button to preview  and remove all of those repeated buttons from pause screen it would look cleaner, could be spaced further away and still end up as 2 clicks.

**Comment by hrydgard** [comment]
The second one has a problem with languages where the strings are longer, the layout breaks. Having them like them are now cuts the problem in half.. 

However, I'm starting to lean towards LunaMoo's solution, where we just show thumbnail images with dates, and popup the buttons (together with the zoomed screenshot) when you click the thumb.

**Comment by vnctdj** [comment]
> However, I'm starting to lean towards LunaMoo's solution, where we just show thumbnail images with dates, and popup the buttons (together with the zoomed screenshot) when you click the thumb.

I also think this is the best option :)

**Comment by r1c4rd0** [comment]
Having to do 2 clicks/taps would be better than accidentally writing over a state you didn't mean to.

**Comment by Gamemulatorer** [comment]
> > However, I'm starting to lean towards LunaMoo's solution, where we just show thumbnail images with dates, and popup the buttons (together with the zoomed screenshot) when you click the thumb.
> 
> I also think this is the best option :)

Yes this is the best solution 👍
