### ISSUE TITLE
PPSSPP 1.0 | Monster Hunter Portable 3rd | Frameskipping Problem

### ISSUE THREAD

**Issue by Pajee** [hrydgard/ppsspp#7441]
I posted an issue three weeks from now about MHFU slows down when Frameskipping is on. For some reason I fixed it by restarting the emulator. But this game, I couldn't fix. 

I don't know why this thing occurs :(

Please help.

**Comment by Pajee** [comment]
It's much more faster if it's off. But I need it.

**Comment by Pajee** [comment]
More info:

As I was copying the settings that was set on MHFU to MHP3rd, I realized that Auto Frameskipping is on. When I unchecked it, the problem went back. I'm thinking that Frameskipping has a problem. It only goes smoothly with Auto Frameskipping.

**Comment by unknownbrackets** [comment]
Frameskipping will give you lower FPS.  That's exactly what it does.  Auto makes it only skip frames (e.g. only lower FPS) if necessary.

If you get choppy graphics when you have auto frameskip off, good news: you're getting exactly what auto being off is supposed to do.

Why do you want to turn off auto frameskipping?

-[Unknown]

**Comment by Pajee** [comment]
Oh. Sorry. I thought Frameskipping makes FPS much faster. I've been using it since .9.6 and I thought it speeds things up. 

I also tried it on P3P, KHBBS,MHFU,Radiant Mythology, etc. and it has the same result.

I'll probably stick with Auto frameskipping because audio becomes smooth but minor slow down. I'm getting pretty decent frames though.

**Comment by unknownbrackets** [comment]
It does speed things up.  It does this by reducing the FPS.

So for example, 0 frameskip means render frames A, B, C, D, E, F, G.

But 1 frameskip means skip every other frame.  Only render A, C, E, G.  So this means you can't possibly get better than 15 FPS if the game was originally 30 FPS, since it's making sure to only render half of the frames.

Frameskip 5 would give you 5 FPS at best for a 30 FPS game.  Even 60 FPS games will only give you 10 FPS **at best** with frameskip = 5 and auto off.

But, it actually is faster.  For example, it won't burn your battery as much to play a game at 5 FPS.  Although it also won't be as smooth, obviously.  Smoothness isn't the same as speed, exactly.

I think in older versions like v0.9.6, auto was not a separate option (it was always on.)  Some people complained that auto was worse than a fixed 1 frameskip for them (since it tries to balance it out, and a fixed frameskip can look smoother if you're already getting near 15 FPS anyway), so it became an option.

So sounds like this is no longer an issue, I'll close it.

-[Unknown]
