### ISSUE TITLE
Windows phone? Soon or when?

### ISSUE THREAD

**Issue by skynet32rus** [hrydgard/ppsspp#7485]

**Comment by unknownbrackets** [comment]
As soon as someone becomes interested in playing games as the speed of a snail and writes a port.  Since it won't have jit, it'll probably never be that fast or enjoyable, so it'll take someone porting it because they just like Windows phones that much that it's worth playing games at 10 FPS.

-[Unknown]

**Comment by hrydgard** [comment]
I think some simpler games could become quite playable, but the big thing someone needs to do first is to write a Direct3D 11 graphics backend. Apart from the terrible performance likely because of the lack of JIT, that's really the major hurdle.

**Comment by unknownbrackets** [comment]
Well, my point is that it sounds like a very very exciting project for someone to dedicate the next X months of their life to - a few playable simple games and a bunch of completely unplayable popular games.  Don't forget the icing on the cake of a bunch of new Windows phone users coming in and complaining constantly about the poor performance.

Where do I sign up for that?  Gotta have it.

-[Unknown]

**Comment by hrydgard** [comment]
Hehe, sure. Just saying what needs to be done, as it is actually possible to a degree.

It's not likely I will personally tackle it anytime soon for the above-mentioned reasons, unless MS lets up the JIT restrictions, and maybe not even then :P
