### ISSUE TITLE
Add NSIS project to make Installer

### ISSUE THREAD

**Issue by gamelaster** [hrydgard/ppsspp#7498]
I got a idea to add NSIS project to git for make Installer + if has been ./b.sh setted to Release, its automatically make a Executable Installer. I wanted to do it but i dont have images, terms etc... for make this. Yes, is small issue but its can help :-)

**Comment by unknownbrackets** [comment]
There is already an installer, although it hasn't been updated in a while.  It's not NSIS, but instead InnoSetup.

https://github.com/hrydgard/ppsspp/blob/master/ppsspp.iss

Ultimately, I think we haven't seen a lot of interest/demand/benefit for an installer, which is why it's been left behind.

Do you want to update it?  Also, would help to understand the motivation.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
