### ISSUE TITLE
Low FPS in high graphic games for low computers.

### ISSUE THREAD

**Issue by kirous** [hrydgard/ppsspp#7504]
Low FPS in high graphic games for low computers.

Hi, I wonder why some games that have high graphics, lower the FPS from 100 to 25 or 30, on slow computers.

The games are:

- God Of War
- Princes of Percia
- Dantes Inferno
- Tekken
- And others.

Instead type games: RPG, visual novels, fighting games and adventure in 2D and 3D little. The graphics are almost low and level of FPS is high.

Games like:

- Lego Harry Potter
- FIFA
- Valkyria Chronicles
- Street Fighter
- Metal Slug
- And others.

However if a game INTEL CORE DUO or i5, the two sets of high and low level runs perfectly.

I have two PCs:

- A Core DUO 4GB RAM and 1GB Video - OpenGL 2.0 and 3.0 (ATI)
- And the other is a Pentium IV 3GB RAM, and 256MB Video - OpenGL 2.0 (NVIDIA)

They do not give a given requirement specification, those games would be good senior can get to support a Pentium IV .... so to speak, no. Sorry my bad english XD

**Comment by unknownbrackets** [comment]
You've stumbled upon an amazing fact.

As surprised as I am, double checking your findings, I'm able to reproduce: it is in fact true that games which render more complex graphics *do*, as much as it confounds logic, require more power from the hardware.

The startling revelation really opens your eyes to how a lot of things work.  This could finally explain the question that has long puzzled economists for decades: why do people buy new hardware at all?  Assuming this issue report is right, it seems likely that users actually buy new hardware because it's better.  The amazing new knowledge may help us, nay, all of humankind advance significantly.

Unfortunately, that doesn't leave us in any place where we can resolve this issue.  If only somebody else's problem field generators were real, we could use one to solve this problem right away.  And probably world hunger and ever cause of sadness or unhappiness that has ever been.

Sarcasm aside, we can't do anything about facts.  I don't think there's any reason to keep this open.  I'm assuming it was opened in jest, because obviously games will run better on more recent hardware.  Even the simpler games run better, it's just not as noticeable.

-[Unknown]
