### ISSUE TITLE
Ys: The Ark of Napishtim [ULUS-10051] (CWCheat) Freeze emulator

### ISSUE THREAD

**Issue by YogSottot** [hrydgard/ppsspp#7524]
```
_C1 EXP Level Boost
_L 0x20164E50 0x4B18967F
```

After turning on the code, you need to open the inventory menu (start button).  Then, when you exit the menu, the emulator stop working.

I'm try  v0.9.9.1-190-x64, v1.0-38-x64, v1.0-105-x64. windows 7

DebugLog.bat --> http://pastebin.com/a7w9v8xS

**Comment by LunaMoo** [comment]
There's surely nothing wrong with that code type on ppsspp, meaning the cheat has incorrect address. That's either because your cheat is for different game version or because the memory differs on ppsspp and psp in this game.
 In first case, you have to find cheat specially made for your game version, in the second case you could try to change psp model to psp1000 in system settings, but if it doesn't help then you'll need a cheat made specially for ppsspp.
 Either way that cheat will not work, you have to search for a different one or ask in the game cw cheat thread in the forums.

**Comment by YogSottot** [comment]
Code for this version. That cheat is work. I got 9999999 exp points.
I'm already try psp1000 - still freeze.

**Comment by LunaMoo** [comment]
This will now be tracked in #11167 closing.
