### ISSUE TITLE
Patapon 3 can't save in multiplayer (adhoc, saving issue)

### ISSUE THREAD

**Issue by TehPlayer14** [hrydgard/ppsspp#7557]
So anyone can't save patapon 3 after multiplayer misson it says missing temp save files

Sorry if it has been reported already

Heres some console output

51:32:380 user_main    W[UTIL]: HLE\sceUtility.cpp:123 sceUtilitySavedataInitStart(099a48a4): wrong dialog type
51:32:447 user_main    W[UTIL]: HLE\sceUtility.cpp:123 sceUtilitySavedataInitStart(099a48a4): wrong dialog type

**Comment by sum2012** [comment]
Did you use "load save status" ?

**Comment by Michal1324** [comment]
No its just not working It says wrong dialog.

**Comment by foxxy429** [comment]
Boost - having same issue with Kingdom Hearts: Birth By Sleep

**Comment by unknownbrackets** [comment]
Does this still happen in the latest git build?  A recent change may have helped this.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
