### ISSUE TITLE
Ipega 9025 problem

### ISSUE THREAD

**Issue by lajuardix** [hrydgard/ppsspp#7579]
Hello i have a small problem with my ipega 9025 everytime i move my analog it work as dpad too so it's convlicting each other, although i already set it in keymapper in ppsspp ,and i think that cause this is because analog is worked as dpad when you are in ppsspp menu (selecting games,option) and when you jumped into the games it's still read you are in menu while moving your analog .but i that's just my thought tho i think you guys know more than me ,so i hope you guys will fix it soon

**Comment by unknownbrackets** [comment]
Did you click X on the mapping for the dpad?  It doesn't show for both?

It's possible this is a device problem, sending both when you press it.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
