### ISSUE TITLE
No Fluency games God of War and other games in the old PC.

### ISSUE THREAD

**Issue by kirous** [hrydgard/ppsspp#7602]
Hello, query, because the God of War games and other heavy games are not flowing at 100% (was down to 30%) in the FPS when this mode of gameplay in old machines, while in other modern machines.

The other games that are not as heavy if they're 100%
I have a Pentium IV 3.20 GHz with 3 GB RAM with Windows 8.1 Operating System pro.

It would be nice that these games can be playable on old PC. Sorry my Bad English XD!!

**Comment by thedax** [comment]
This seems like a repeat of https://github.com/hrydgard/ppsspp/issues/7504 to me. Some games are just really demanding, and old machines are just not fast enough to handle them, especially as the accuracy of the emulator improves. While I'm sure we can still squeeze out some more speed here and there, PPSSPP is already pretty optimised as it is, and thus not every old PC, phone, or tablet will be able to keep up.

**Comment by unknownbrackets** [comment]
Well, I did really think you were joking before, but now I think you were not.

Please understand that your Pentium 4 computer **is older than a PSP** (or most likely is, since they made Pentium 4s of that speed sometime in 2003 and the PSP was released in Japan end of 2004.)

But, actually, a Pentium 4 3.2 Ghz might have a hope and a dream of playing God of War - with a decent video card.  You most likely have a video card also from 2003, and that's probably your main problem.

I use a video card from 2008, which is part of why I'm able to play God of War at full speed.

Please see the FAQ:
http://ppsspp.org/faq.html

> **What are the PC CPU and GPU requirements?**
> Any reasonably modern CPU will be just fine...

Unfortunately, a computer that is over 10 years old **does not qualify** for "reasonably modern" status.  While I'm personally glad to try to make sure games run even on such older systems, I won't shed any tears for anyone who cannot play demanding games at full speed without frameskip on such an old device.

-[Unknown]
