### ISSUE TITLE
Cannot Load/Tranfer Save Files : Gods Eater Burst

### ISSUE THREAD

**Issue by Xaelath** [hrydgard/ppsspp#7606]
I havent played the Gods Eater since the old build build (well i already finished it) i am currently in 80th Story and cannot load it.
And heres what i found in the log
11:58:041 Main         I[UTIL]: Dialog\PSPSaveDialog.cpp:86 sceUtilitySavedataInitStart(08a8d440) : Game key (hex): D06718475CFBD26266D61198AABFF738
11:58:043 Sound        I[ME]: HLE\sceAtrac.cpp:1275 sceAtracReleaseAtracID(-1)
11:58:056 Sound        I[ME]: HLE\sceAtrac.cpp:1275 sceAtracReleaseAtracID(-1)
11:58:059 Sound        I[ME]: HLE\sceAtrac.cpp:1275 sceAtracReleaseAtracID(-1)
11:58:065 Sound        I[ME]: HLE\sceAtrac.cpp:1275 sceAtracReleaseAtracID(-1)
11:58:068 Sound        I[ME]: HLE\sceAtrac.cpp:1275 sceAtracReleaseAtracID(-1)
11:58:071 idle0        I[SCEGE]: GLES\Framebuffer.cpp:1851 Decimating FBO for 00044000 (480 x 272 x 1), age 6
11:58:072 idle0        I[UTIL]: Dialog\SavedataParam.cpp:586 Loading file with size 426064 in ms0:/PSP/SAVEDATA/ULUS105630680502102040001000/SECURE.BIN
11:58:089 Sound        I[ME]: HLE\sceAtrac.cpp:1275 sceAtracReleaseAtracID(-1)
11:58:090 Sound        I[ME]: HLE\sceAtrac.cpp:1275 sceAtracReleaseAtracID(-1)
11:58:095 Sound        I[ME]: HLE\sceAtrac.cpp:1275 sceAtracReleaseAtracID(-1)
11:58:106 Sound        I[ME]: HLE\sceAtrac.cpp:1275 sceAtracReleaseAtracID(-1)
11:58:116 Sound        I[ME]: HLE\sceAtrac.cpp:1275 sceAtracReleaseAtracID(-1)
11:58:125 Sound        I[ME]: HLE\sceAtrac.cpp:1275 sceAtracReleaseAtracID(-1)
11:58:134 Sound        I[ME]: HLE\sceAtrac.cpp:1275 sceAtracReleaseAtracID(-1)
11:58:136 Main         I[KERNEL]: HLE\sceKernelMemory.cpp:1151 sceKernelPrintf: !!! Error !!! : src/app_task/save.c 2146 : _workFlowSaveTask_WorkType_OptionLoad : hash broken.
11:58:138 Sound        I[ME]: HLE\sceAtrac.cpp:1275 sceAtracReleaseAtracID(-1)
11:58:144 Sound        I[ME]: HLE\sceAtrac.cpp:1275 sceAtracReleaseAtracID(-1)

Its keeps looping while the new saves files did work without any problems.
Also i've a dlc which may affect the games , however i also tried to remove it but it didnt work, same goes with transfer.
Its already happened on the way through 0.9.9 i havent tried to oldest one since i already deleted it and used the latest on the git.

**Comment by ThePhoenixRises** [comment]
@Xaelath , Hi there,
If you look on the emulators menu, take a look on the System tab / under Emulation section, there is an option made for that very game, Respect FPU Rounding (Disable on GEB), un-tick that option and try again. Hope that helps.

**Comment by Xaelath** [comment]
@ThePhoenixRises 
Thank you and sorry again i havent played the for year.

**Comment by unknownbrackets** [comment]
Note that unchecking that option will cause glitches in some games, such as Metal Gear Solid: Peace Walker, and will also make it so that the savedata produced by PPSSPP for Gods Eater Burst is not compatible with savedata on a real PSP.

You can check the option once you have loaded your game, and save.  Old versions of PPSSPP won't be able to load the save anymore, but the savedata will be compatible with real PSPs and "correct".  You'll also be safe from possible bugs in other games, maybe even Gods Eater Burst, that unchecking that may cause.

Since the option is essentially a compatibility option for versions from already a year ago, it may eventually be removed in a future version.  I recommend using it as a transitional step rather than a permanent crutch.

-[Unknown]
