### ISSUE TITLE
PPSSPP Mac OS X ___sincosf_stret not found error

### ISSUE THREAD

**Issue by MatthewAKelly** [hrydgard/ppsspp#7607]
This is not a new issue. This is, actually, an old issue, discussed in previous threads. However, it's not clear to me how to fix this issue.

I get this error message when launching the PPSSPP Mac OS X application bundle from: https://drive.google.com/folderview?id=0B7W70ATEvsNdV0t1b25ENUpnQnc&usp=drive_web

The error message is this:

Dyld Error Message:
  Symbol not found: ___sincosf_stret
  Referenced from: /Volumes/VOLUME/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL
  Expected in: /usr/lib/libSystem.B.dylib

This error has been discussed before here and closed:

https://github.com/hrydgard/ppsspp/issues/5835

I'm afraid the discussion is very technical and beyond me (I'm not a UNIX expert).

If there's a known solution, then can someone provide step-by-step instructions on how to fix this problem?

I'm running Mac OS X 10.8.5.

Thanks,
Matthew.

**Comment by unknownbrackets** [comment]
There's already an issue for this, #7423.

This isn't a forum, the forum is here (and pretty much all of the contributors are active there):
http://forums.ppsspp.org/

The right thing to do when you want to discuss an issue that's already been reported is to either comment in the existing issue, or post on the forum.  Opening duplicate issues here only makes things get fixed slower.

I don't know where you're getting the Mac build from, but without compiling anything yourself, the best solution to this issue is to either wait or upgrade your Mac OS X.  The issue is that the current binary is not compatible with older versions of Max OS X, including 10.8.  This is not intentional, and **is** a bug, however.

-[Unknown]

**Comment by MatthewAKelly** [comment]
Thanks, and apologies for the duplication. I didn't see #7423. The Mac build is from the forum: http://forums.ppsspp.org/showthread.php?tid=12283
