### ISSUE TITLE
Invalid Emuhack Op 6b736154 in Dissidia 012 Final Fantasy

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7617]
Happens at the beginning of the last battle in the chapter 3,and looks like it causes invalid addresses in the next battle.
```
27:40:313 ffst_thread  E[JIT]: JitCommon\JitBlockCache.cpp:327 JitBlockCache: Invalid Emuhack Op 6b736154
```

**Comment by daniel229** [comment]
Other invalid adresses in battle,can't reproduce this second time.
![01](https://cloud.githubusercontent.com/assets/3481559/6763033/eda6e4ce-cfa7-11e4-960c-578289a403b8.png)

**Comment by hzjslm** [comment]
Thanks

**Comment by unknownbrackets** [comment]
Is this working any differently nowadays?

-[Unknown]

**Comment by daniel229** [comment]
Still happen.seem the same.

**Comment by unknownbrackets** [comment]
Just to confirm, the game plays fine in this area without jit enabled?

If so, that means it's probably self-modifying code.  Can you set a Visual Studio breakpoint on that line (`ERROR_LOG(JIT, "JitBlockCache: Invalid Emuhack Op %08x", inst.encoding);`) and see the stack trace?  You can put `#pragma optimize("", off)` at the top of Core/MemMap.cpp and Core/MIPS/JitCommon/JitBlockCache.cpp.  If the call is from `Read_Instruction` or `Read_Opcode_JIT`, then we're after the value of `address`, and if it's from `GetBlockNumberFromStartAddress` just want `addr`.

Once we have that, we know where the emuhack is getting corrupted.  The next thing would be to set a memory breakpoint (in PPSSPP's debugger, not Visual Studio) for that address.  You can uncheck "Enabled" so that it doesn't actually break, and only logs.

If it writes to that address sometime before this error, that tells us it's modifying code in a way our jit doesn't support.  If this happens, it'll log the PC of the code that modified jit, so we can potentially do something about that function or at least look at the code.

-[Unknown]

**Comment by daniel229** [comment]
with jit off,the texture will become bigger when it fall down,but it seems not related to this issue.
![ppssppwindows64v1 1 1-456-gb278299 2015-12-27 09-58-11-168 mp4_20151227_100128 031](https://cloud.githubusercontent.com/assets/3481559/12008592/d92a93ea-ac80-11e5-8b95-70e39f822a36.png)

**Comment by daniel229** [comment]
it's from GetBlockNumberFromStartAddress.
addr	0x08b3efb0
![02](https://cloud.githubusercontent.com/assets/3481559/12008655/57394c0e-ac86-11e5-9b9b-c353458262b9.png)

```
34:30:259 ffst_thread  N[MM]: Debugger\Breakpoints.cpp:41 CHK Write12450592 at 089dea6c ((089dea6c)), PC=088647b4 (z_un_08864760)

34:48:778 ffst_thread  N[MM]: Debugger\Breakpoints.cpp:41 CHK Write12775840 at 089dea6c ((089dea6c)), PC=088647b4 (z_un_08864760)


34:58:479 ffst_thread  N[MM]: Debugger\Breakpoints.cpp:41 CHK Write12450592 at 089dea6c ((089dea6c)), PC=088647b4 (z_un_08864760)
34:58:671 ffst_thread  N[MM]: Debugger\Breakpoints.cpp:41 CHK Write12775840 at 089dea6c ((089dea6c)), PC=088647b4 (z_un_08864760)
```

the last two lines looks like just before the error,but when I set the breakpoint the <code>Invalid Emuhack Op 6b736154</code> is gone

**Comment by daniel229** [comment]
without breakpoint
![01](https://cloud.githubusercontent.com/assets/3481559/12008665/8aa66a4e-ac87-11e5-8186-e898480544d6.png)

with breakpoint
![02](https://cloud.githubusercontent.com/assets/3481559/12008666/8d0d6e2c-ac87-11e5-9d08-9a262a8e6095.png)

**Comment by daniel229** [comment]
z_un_08864760
![03](https://cloud.githubusercontent.com/assets/3481559/12008716/5acf396e-ac8b-11e5-831e-b9827a5bec6e.png)

**Comment by unknownbrackets** [comment]
Interesting, so it's writing around ~1.5MB using sceIoRead.  Must contain code.

It's probably just "luck".  That's data, and it happens to match enough that it looks like an invalid emuhack, where one used to be?  But then, this might account for the emuhacks... hmm.

A breakpoint might cause it to evaluate the jit block cache differently.  Maybe we need to ensure sceIoRead invalidates jit.  That sounds like a good idea.

Hmm.  A bit tricky with threaded IO.  For now, in Core/HLE/sceIo.cpp, change:
```c++
ioManagerThreadEnabled = g_Config.bSeparateIOThread;
```

To:
```c++
ioManagerThreadEnabled = false;
```

And then change:
```c++
				if (g_Config.iIOTimingMethod != IOTIMING_REALISTIC) {
					result = (int) pspFileSystem.ReadFile(f->handle, data, size);
				} else {
					result = (int) pspFileSystem.ReadFile(f->handle, data, size, us);
				}
				return true;
```

To:
```c++
				if (g_Config.iIOTimingMethod != IOTIMING_REALISTIC) {
					result = (int) pspFileSystem.ReadFile(f->handle, data, size);
				} else {
					result = (int) pspFileSystem.ReadFile(f->handle, data, size, us);
				}
				currentMIPS->InvalidateICache(data_addr, size);
				return true;
```

Does that help?

-[Unknown]

**Comment by daniel229** [comment]
yes,It does.
