### ISSUE TITLE
Dante inferno unplayable after beat the first boss [video][iOS]

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#7631]
here an video tested in build v1.0.1-202

video size 75mb, please watch all video https://mega.co.nz/#!5swGQCZK!Aga6E599a6t4SDBokyZIgx43hcElTeFMu5pSKulEqyI

**Comment by daniel229** [comment]
Seems like not happen on desktop.

**Comment by brujo5** [comment]
this problem is longtime.
Testing build from 0.9.8-1538 to 1.0.1-202 still happend
So I keep looking at much earlier versions.

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
