### ISSUE TITLE
Can play only 1 game and other games black screen

### ISSUE THREAD

**Issue by JohnRve21** [hrydgard/ppsspp#7644]
I can only play God of war i dont know why or how but i have tekken 6 on my ppsspp and since i downloaded God of war it started to have black screen when i play other games like tekken or soul calibur. I always get black screen on other games but on God of war it works pretty well with good and fast gameplay. I have only one game on my ppsspp and i want to play many games not just one. Please fix this black screen issue. I hope i will get a respond. And sorry for my bad english..Thanks

**Comment by metaasza** [comment]
tekken 6 won't load until you changa CPU clock to 0

**Comment by unknownbrackets** [comment]
These are setting issues.  God of War requires Buffered Rendering, it won't draw at all using Skip Buffer Effects rendering (since it uses a buffer effect to draw the entire screen.)

Potentially I think we could provide messaging to users to guide them to reset settings to defaults when things aren't working (e.g. reporting problems), but I think that's a separate effort.

I'm closing this.

-[Unknown]
