### ISSUE TITLE
[Adhoc] Issues with Lobby in Monster Hunter 3rd

### ISSUE THREAD

**Issue by GamerzHell9137** [hrydgard/ppsspp#7646]
There's some weird issue with the game.
If you leave the lobby while people are in there, connecting back won't show them and everyone's forced to re enter the lobby until everyone can see everyone again. (Horribly worded sentence lol)

https://www.youtube.com/watch?v=Bml2FwDBmyE&feature=youtu.be

Here's how it looks like.

Btw, that didn't happen on older builds so what's going on?

**Comment by GamerzHell9137** [comment]
Bump
Anyone know what's going on?

**Comment by GamerzHell9137** [comment]
Weird that no one knows what's happening.

**Comment by Mullin** [comment]
You're not alone, this happen to me too.

**Comment by tywald** [comment]
This issue started with: v0.9.9.1-1392-g1fa6710 and is still present as of now. There is another bug where it says all GH are full but they aren't so you are forced to restart the emulator every time it happens.

The version I found most stable for MHP3rd even today is: v0.9.8-1394-g384d8e3

**Comment by vnctdj** [comment]
Is it the same issue as https://github.com/hrydgard/ppsspp/issues/7331 ?
It seems closely related.

**Comment by GamerzHell9137** [comment]
@tywald I'll check the build you posted and report back.

**Comment by unknownbrackets** [comment]
Is this still an issue in the latest git builds?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
