### ISSUE TITLE
Controller no longer works in linux

### ISSUE THREAD

**Issue by Deminarcis** [hrydgard/ppsspp#7704]
The title says it all  , i woke up this morning and my controller no longer works with ppsspp but it works with my other apps. This issue efftects both Qt and SDL versions in the stable and unstable ppas.

I'm not sure what information you need  but i am using Ubuntu 14.10 64 bit;  kernel version 3.16.0-34-generic and the package version installed is 1.0.1+r52.f46.n1177.l1577.a156~15~ubuntu14.10.1.

please let me know if i can provide more information or if this is not where to report what appears to be a bug

**Comment by unknownbrackets** [comment]
My guess is that this is mapping related.  Does this still happen?

Does it work on older versions?  If so, in which git build did it stop working?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.  It's likely this has been improved by recent changes to controller handling.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
