### ISSUE TITLE
cheat engine 6.4 not working

### ISSUE THREAD

**Issue by RockinsGeorge** [hrydgard/ppsspp#7705]

**Comment by LunaMoo** [comment]
First of all this is not Cheat Engine issue tracker, if you find any bugs in CE that bothers you, you should report that to CE developers. Avoid reporting here anything not directly related to ppsspp/psp emulation.

 On a side note CE team would probably not be interested either in what you wrote, since it does work just fine. To use it with certain software like PPSSPP you have to select "MEM_MAPPED" in edit->settings->scan settings. Also not all games are easy to mess with, you should probably ask for a guide in CE forums and/or follow some tutorials before reporting anything anywhere.

**Comment by thedax** [comment]
I think LunaMoo pretty much said it all. It's not our job to make Cheat Engine compatible with PPSSPP.
