### ISSUE TITLE
Pangya: Episode 2, Cecilia Story, Chapter 2

### ISSUE THREAD

**Issue by chantinelle14** [hrydgard/ppsspp#7715]
The game crashes every time I try to play this chapter.

I uploaded the saved state and debug logs here:
http://www.sendspace.com/filegroup/1rsvyaKOMh5dtoFRfbkvAQ

Hit me up when you need additional information. Thanks!

**Comment by sum2012** [comment]
I have differcult problrem to you.
I cannot load the game from the beginning
10:57:691 user_main    E[MODULE]: HLE\sceKernelModule.cpp:2008 UNIMPL sceKernelStopUnloadSelfModuleWithStatus(00000001, 00000000, 00000000, 00000000, 00000000): game has likely crashed

ppsspp-v1.0.1-448-gaee69d4 info log
https://gist.github.com/sum2012/66f685bb445d3004e84e

debug log:
https://drive.google.com/file/d/0B3OaSdeV0L8kQlVnVzFMUVZmYm8/view?usp=sharing

**Comment by unknownbrackets** [comment]
@sum2012 see https://github.com/hrydgard/ppsspp/issues/4996.

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets I see

**Comment by chantinelle14** [comment]
I could provide the iso that I used if you need it.

**Comment by unknownbrackets** [comment]
No, we don't need to add piracy to the bug that exists here.

-[Unknown]

**Comment by vigaristAA12** [comment]
This match can also be "bypassed" by activating FuncReplacements = False in ppsspp.ini and Fast Memory disabled. Same weird behavior happens with Bob being transparent.

Pretty ironic that he gives up against Cecilia, and that this issue is peculiar to this one match.

**Comment by unknownbrackets** [comment]
I think this issue is somehow timing related.  You can verify this by trying to tweak the "CPU Speed" setting.  Try different, irregular values like 200, 150, 40, or 400.  Do any of them work?

If one of them works, I think it confirms that it's timing related somehow.  If none of them work, it might mean I'm wrong.

-[Unknown]

**Comment by vigaristAA12** [comment]
I will check as soon as I can and edit this coment, unknown. However I am not the best at testing consoles due to my lack of knowledge, i'll come back with results ;D
...By the way, I have FuncReplacements set to True, and on the epilogue, there is ANOTHER bugged ai, on a different character this time (Damien Keeper, it's EP4..i think)

**Comment by Saramagrean** [comment]
Fixed since v1.9.3 build 155.

**Comment by unknownbrackets** [comment]
Great, that means #12509.  Thanks for reporting.

-[Unknown]

**Comment by Saramagrean** [comment]
yeah, and fixed this https://github.com/hrydgard/ppsspp/issues/6746 too. :)
