### ISSUE TITLE
Blazblue Continuum Shift Extend hang for muti-player freeze (Need wait >3 minute).

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#7728]
It hang after select player.
The game sent udp data (of port 4) to each other to ensure network stably.
The hang due someone don't ready the udp data.
I have tried
https://github.com/hrydgard/ppsspp/pull/7725
fail (Change to 50 seem work but very lag)
@unknownbrackets What do you mean "Using more realistic timing (e.g. between 1/30 of a second frames) might help more" ?

**Comment by sum2012** [comment]
Using  "real time sync option"
Wait 4 minute,it is unfreeze

**Comment by sum2012** [comment]
No need that option alsowork,
just need wait 5 minutre

**Comment by unknownbrackets** [comment]
The option had some bugs and might work better now.

-[Unknown]

**Comment by unknownbrackets** [comment]
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
