### ISSUE TITLE
[iOS][OpenGL ES 3][A7-S5L8960X] Some missing 2D sprites in Kingdom Hearts Birth By Sleep (ULJM05600, ULJM05775, ULUS10505)

### ISSUE THREAD

**Issue by angelXwind** [hrydgard/ppsspp#7756]
Under iOS with the OpenGL ES 3 renderer (A7-S5L8960X), many 2D sprites are missing in Kingdom Hearts Birth By Sleep.

This includes (but probably isn't limited to):
- First-time world warp title cards
- Dropped munny/other items from Unversed and other attackable objects

I do not have my Android device with me at the moment, so I cannot test to see if this bug happens on an OGLES3-capable Android device.

The issue is NOT present under OpenGL 2.1 on neither OS X nor Windows.

Screenshots:
Improper behaviour under OpenGL ES 3.0: ![img_6527](https://cloud.githubusercontent.com/assets/1980487/7739012/247430f0-ff29-11e4-877a-2a7b430a786d.jpg)

Proper behaviour under OpenGL 2.1 (OS X): ![image](https://cloud.githubusercontent.com/assets/1980487/7739178/0fb9e482-ff2b-11e4-862c-5c5fb25cb448.png)

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
