### ISSUE TITLE
Ppsspp auto shut down when saving in quick save file In iPad

### ISSUE THREAD

**Issue by yihchun92** [hrydgard/ppsspp#7770]
When I was playing duodecim 012 dissidia, whenever I quicksave the file in any state, it will auto shutdown and the progress of the game will be gone :( it happened in the recent patch,

**Comment by unknownbrackets** [comment]
It seems like iOS often has file permission issues - depending on how PPSSPP was installed.

Is this still happening?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
