### ISSUE TITLE
metal gear acid 2 ULUS-10077 and many other games cwcheats not work support other cheat formats

### ISSUE THREAD

**Issue by nfjorgebueno** [hrydgard/ppsspp#7775]
_S ULUS-10077
_G Metal Gear AC!D 2 [US]
_C0 Venus has 900 HP
_L 0x10EF7150 0x00000384
_C0 Snake has 1000 HP  
_L 0x10EB8280 0x000003E8
_C0 Snake Infinite Health  
_L 0x10CD81C6 0x000003E8
_L 0x10CD81CE 0x000003E8
_L 0x10D09C40 0x000003E8
_C0 Snake 0 Cost Per Turn  
_L 0x00CB651E 0x00000000  
_C0 Snake always has 6 cards
_L 0x00CDC528 0x00000006  
_C0 Max cards  
_L 0x00C838AC 0x000000FF  
_C0 Infinite turns  
_L 0x00C8389D 0x00000000  
I tried every way I know but do not work appreciate the help of someone who knows the subject, thank you very much

**Comment by nfjorgebueno** [comment]
consider that the codes are not correct, it is not a problem of the emulator, but it would be good to ppsspp take all formats of codes as a real psp, as pcsx2 which takes all kinds of codes as a real play 2, thank you for your attention

**Comment by nfjorgebueno** [comment]
is a pity that one of the best emulators that there is this conditional only to the use of cwcheats, as I put in another post the cwcheats are very difficult to achieve, thanks for your attention, best wishes

**Comment by hrydgard** [comment]
Why did you close this then?

We may very well have bugs in our CwCheat implementation, but more information is needed to fix them. For example, what happens when these codes are used? Does the game crash, or does nothing happen?

**Comment by Bigpet** [comment]
@hrydgard if I read his comments right then it was the cheat code that was wrong. His remaining issue with PPSSPP is that it doesn't support other cheat formats, so if this stays open it would probably be best to rename it to "support other cheat formats" or mark it as a duplicate for modules support, since I assume that it would solve that issue.

**Comment by LunaMoo** [comment]
The codes posted here are very simple and look correct through, so it's probably just the usual difference in address between real psp and ppsspp, which is rather common especially with psp-2000 setting.
 Different cheat engines would have exactly same issue since they all do pretty much same thing especially with those common code types which usually differs only by formatting and eventual encryption.

**Comment by nfjorgebueno** [comment]
I tried every method I know to run the code, but do not work or crash the game occurs, or the screen goes dark, thanks to github for listening friends, my best wishes

**Comment by nfjorgebueno** [comment]
Snake Infinite Health, sample code, nothing works
cwcheat 
_L 0x20000000 0x10CD81C6
_L 0x200003E8 0x10CD81CE
_L 0x200003E8 0x10D01C40
_L 0x200003E8 0x00000000
    RAM Write - Writes 0x10CD81C6 to the RAM address 0x0.
    RAM Write - Writes 0x10CD81CE to the RAM address 0x3E8.
    RAM Write - Writes 0x10D01C40 to the RAM address 0x3E8.
    RAM Write - Writes to the RAM address 0x3E8.
original
_L 0x10CD81C6 0x000003E8
_L0x10CD81CE 0x000003E8
_L0x10D01C40 0x000003E8
    RAM Write - Writes 0x10CD81C6 to the RAM address 0x0.
    RAM Write - Writes 0x10CD81CE to the RAM address 0x3E8.
    RAM Write - Writes 0x10D01C40 to the RAM address 0x3E8.
    RAM Write - Writes to the RAM address 0x3E8.

**Comment by LunaMoo** [comment]
This will now be tracked in #11167 closing.
 Through since partially it was about supporting new cheat format I will open a new issue/feature request about that, however take note as mentioned in the new issue for tracking this, memory allocation will affect all cheat formats or even real plugins and will not solve anything.
