### ISSUE TITLE
Blackscreen when opening ppsspp

### ISSUE THREAD

**Issue by pinguallyj** [hrydgard/ppsspp#7788]
I played a lot of games on PPSSPP but recently whenever I launch emulator, I get black screen. I can press and even launch games, but no image displayed, only sound.

**Comment by hrydgard** [comment]
Can you try to move PSP/SYSTEM/ppsspp.ini out of the way, and see if that helps? If it does help I would be interested to see the contents of your ppsspp.ini.

**Comment by 716Girl** [comment]
I solved the problem by switching backend from opengl to d3d, not sure why opengl not works but I can play games now, thanks!

**Comment by unknownbrackets** [comment]
That very probably means you have an old video card or old video card driver that doesn't work too well with PPSSPP.  What video card do you have?  You can find out, for example, with GPU-Z (google it) or typing "dxdiag" in Windows -> Run and going to the Display tab.

-[Unknown]

**Comment by 716Girl** [comment]
I have laptop geforce 520m card.

**Comment by unknownbrackets** [comment]
Is this on Windows 10?  Have you tried updating your drivers?

Does it still happen with the latest git build?

What games have you tried?  Just because your favorite 3 games don't display an image doesn't necessarily mean all games don't.  Maybe it's a problem with those 3 particular games that we can fix.

-[Unknown]

**Comment by Hydroque** [comment]
This issue occurs commonly on older, other non-mainstream graphics cards. For example, my embedded acer's laptop GPU will go super-buggy when you install dependencies or try to uninstall them for visual studio and msvs itself. (If msvs wasn't bad enough already, doesn't even cleanup well).

The workaround fix is to use non-buffered drawing.

**Comment by unknownbrackets** [comment]
We default to Vulkan or Direct3D 11 now on newer operating systems.  Hopefully this will help things.

Closing this for now as there have been a lot of changes to graphics in PPSSPP and no feedback otherwise.  Hopefully the newer APIs dodge the issues you've mentioned @tilkinsc (but they sound like driver bugs which there's not always much we can do about...)

-[Unknown]

**Comment by tilkinsc** [comment]
That PC has been long since used. Rocking that gtx 1080 now with a good processor.

However, it is appropriate to ask if PPSSPP could bundle local redistributable targets so that issues with user APIs don't exist (which was my problem, uninstalling MSVS totally feked my PC).

**Comment by unknownbrackets** [comment]
The stable releases should bundle it AFAIK - just not the git builds.

-[Unknown]
