### ISSUE TITLE
Green borders around certain sprites in Final Fantasy IV

### ISSUE THREAD

**Issue by nhanb** [hrydgard/ppsspp#7799]
For example:

![ulus10560_00000](https://cloud.githubusercontent.com/assets/1446315/8025908/cefc411a-0d8f-11e5-85ce-d8d32338120d.jpg)

It's quite subtle in many cases but very distracting when it does stand out (the soldiers and wheel in this scene for example). Is there any workaround that I can try? I'm using v1.0.1 from the Ubuntu PPA (trusty).

And of course, thank you for such a fine project. I'm expecting some quality time with Trails In The Sky in the next few days! :+1:

**Comment by unknownbrackets** [comment]
This is because you're using texture scaling.  The sprites the game uses do actually have green, so scaling is just "bleeding" that into the pixels nearby.  The best way to solve this would be texture replacement, I guess, which there's a separate bug for.

There's not really a good way to tell that the green is just used as a background filler color here.

-[Unknown]

**Comment by Bigpet** [comment]
I think for 2D games like this framebuffer upscaling would probably work without having to re-do each transparent texture. Which I think some of the postprocessing shader are already doing.

**Comment by unknownbrackets** [comment]
Right.  Either way, if you choose to use texture scaling on this game, you're going to get green outlines.  I'm going to close this.

I think there's no xBRZ post-processing filter right now but that's something someone can contribute, and I think there was already a bug open about that sort of thing anyway.  And there are already post-processing shaders that provide similar effects.

-[Unknown]
