### ISSUE TITLE
Tales of rebirth hangs

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#7868]
Since https://github.com/unknownbrackets/ppsspp/commit/2910f7e7a2f721d02068e8e6e968012e4306e21f

**Comment by unknownbrackets** [comment]
Where does it hang?  Can you give a save or anything?

-[Unknown]

**Comment by daniel229** [comment]
Not far away from new game.
Here is the save.just go outside of the village and walk toward south,and then see a house,when they go into the house it hangs
![uljs00132user002](https://cloud.githubusercontent.com/assets/3481559/8763819/29a0650c-2de2-11e5-978e-1ee79beecde3.jpg) (rename jpg to 7z)

Not far away from the village,see the following picture.
![01](https://cloud.githubusercontent.com/assets/3481559/8763827/92177f3a-2de2-11e5-9dbc-dfa7964eab8a.png)

**Comment by daniel229** [comment]
After loading a savestate it won't hang.

**Comment by unknownbrackets** [comment]
Interesting.  It seems like the invalidation is happening in battle.

Maybe it's restoring the emuhack incorrectly, or maybe it's not invalidating everything that changed and the inconsistency is causing the crash.  Hmm.... still debugging.

-[Unknown]

**Comment by unknownbrackets** [comment]
Note: if I just `Clear(); break;` whenever a block is matched by `InvalidateICache()`, it works.  This should still be resetting the emuhack etc., so it implies to me that it isn't the issue.

So I think it's caused by one of:
 * Bookkeeping (e.g. not clearing the block map right.)
 * Something DestroyBlock does when the maps aren't cleared yet.
 * Other related blocks not getting cleared when a changed one is.

-[Unknown]

**Comment by unknownbrackets** [comment]
Hmm.  It fixes it to handle `sceKernelIcacheInvalidateAll()`, which is probably the right thing here.

-[Unknown]

**Comment by unknownbrackets** [comment]
Okay, so this is caused by block linking.  What happens is a block is changed, but linked blocks to it aren't and never get invalidated.  It seems indeed to work when I also invalidate another small region of memory, so I think it's just that these two functions need to "agree" on some memory addresses or something.

Erasing all jit on every call to `sceKernelIcacheInvalidateAll()` could be a huge perf problem in some games, so gonna try something more optimal.

-[Unknown]
