### ISSUE TITLE
Screen flickering: Buffered rendering,Directx 9 backend,no frameskipping!

### ISSUE THREAD

**Issue by PlayerGameSK** [hrydgard/ppsspp#7898]
Hi guys,

Yet I'm back with another issue with the emulator,flickering screen. It was happening it GTA LCS but not as often as in GTA VCS (except there was no flickering on the ending credits in VCS but really much flickering on the credits in LCS). I already 100%-ed them both but I would still like you looking at it,as you can see in the title I am using buffered rendering along with no frameskipping,it doesn't happen with OpenGL (at least for me) but I must use frameskipping with OpenGL or it'll be too slow.

Thanks :)

**Comment by sum2012** [comment]
No problem to me 
Windows 7 64 bit Nvidia GeForce  GT 630

**Comment by unknownbrackets** [comment]
Does this still happen in the latest git build?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
