### ISSUE TITLE
Windows: Games in eboot.pbp format fail to load if they're more than one directory deep

### ISSUE THREAD

**Issue by thedax** [hrydgard/ppsspp#7905]
This one is a bit tricky for me to explain, so bear with me. We all know PPSSPP can boot PSP eboots that are contained in a folder (such as /SomeISODirectory/Game/Eboot.pbp), but if you have them in a folder hierarchy like so:

/SomeISODirectory
-----/GameIDHere
-------------/USRDIR/Eboot.PBP (so the full path is /SomeISODirectory/GameIDHere/USRDIR/eboot.pbp)

Then the game is instead recognised as 'save data' and PPSSPP will refuse to boot it.

**Comment by thedax** [comment]
I'm not sure if this happens -only- on Windows or not.

**Comment by vsub** [comment]
Just for a test I move all of my demos in this directory
D:\Games\PSP\Games\DEMOS\New folder\New folder\New folder
Games loaded from the ppsspp widow were always loaded without any problems but any other method(drag-drop,the screen button to load games and the File=>Load)almost always resulted in all kind of errors from which ppsspp crashes.

After that I moved the demos to the old location and while I was trying drag-dropping games,ppsspp will randomly(rarely)crash or don't load the game but the game is always loaded if I stop the emulation before dropping another game

Sometimes I get those
FileSystems\BlockDevices.cpp:500 E[LOAD]: LZRC decompress error! lzsize=-1
and then ppsspp says that it couldn't locate the executable

**Comment by unknownbrackets** [comment]
I wasn't aware this was a thing that the PSP supported.  Is it only USRDIR?  I couldn't find any docs on this.  I know the PS3 uses a different structure than the PSP.

The blockdevices issue has already been fixed separately, I believe.

-[Unknown]

**Comment by unknownbrackets** [comment]
As far as I can tell, this works as well as it should, but I'm still not sure if there was something I was missing before and now.

For example, putting Cave Story's EBOOT.PBP inside ms0:PSP/GAME/somewhere/cavestory/EBOOT.PBP works fine (as long as it has its data files next to it.)  Similarly, ms0:PSP/GAME/cavestory/USRDIR/EBOOT.PBP also works, again assuming I put data files inside USRDIR.

On my PSP, I used a "Game Categories" plugin to put things in folders, i.e. ms0:PSP/GAME/RPG/ and ms0:PSP/GAME/Action/, etc.  I don't know of any special handling on the PSP for the memory stick involving USRDIR.

Since this all seems to be working currently, and this has been open for 7 years, I'm going to close it.  Please comment if I've misunderstood and something isn't working.

-[Unknown]
