### ISSUE TITLE
PPSSPP Crash on OpenGL Backend

### ISSUE THREAD

**Issue by Connor37** [hrydgard/ppsspp#7916]
Lately, I've been experienced crash to desktop when opening ppsspp. The Direct3D9 don't have this problem.
I'm using Windows 10 64bit build 10240.

**Comment by unknownbrackets** [comment]
Have you updated your graphics drivers before this change?  Have you made sure they're properly updated afterward?

Most likely this is a driver problem and not something to do with PPSSPP, especially if it happens right after opening.  Not sure there's much we can do.  You should probably contact your video card vendor about Windows 10 support.

-[Unknown]

**Comment by Connor37** [comment]
Pretty sure that I'm on the correct driver for Windows 10. Try to do a clean driver installation, but didn't solve anything.

It's not always crash, sometimes I managed to open it without any crashes.

**Comment by unknownbrackets** [comment]
What's your exact video card model?  Which driver version exactly are you on?

Saying "lately" makes me think this changed on its own.  Do you mean recent PPSSPP nightly builds?  If so, which build exactly last worked fine and which build exactly first started giving problems?

If it started happening without changing PPSSPP versions, then it's probably caused by a change you made to something else (or that was automatically made for you.)  Examples include system updates, driver updates, etc.

Please note that Windows 10 is new.  That means the drivers (or parts of them) you're running are new, and a chunk of the software running on your computer is new.  New stuff is more likely to have bugs.  Just a nature of the beast problem.

It's also possible that PPSSPP has a compatibility problem with Windows 10.  If by "lately" you meant since you upgraded to Windows 10, then the best thing would be for you to compile it yourself (there's a topic on the forum) and get a stack trace of the crash.  This should give us a hint as to where the problem actually lies.

But it sounds like other users are running on Windows 10 and haven't reported crashes yet, at least that I've seen.

-[Unknown]

**Comment by Connor37** [comment]
I'm using laptop with Nvidia GT 630M/Intel HD 4000. The latest driver version 355.60.

"Lately" I meant since upgrading to Windows 10. It have been several months since I updated PPSSPP. Also thought about trying latest version of PPSSPP, but it still crash.

Will try to compile it myself and give you a stack trace of the crash. Thanks for quick response.

**Comment by sum2012** [comment]
Can you try newest version (v1.0.1-832-ge99ba86 or newer) in
http://buildbot.orphis.net/ppsspp/ ?

**Comment by Connor37** [comment]
@sum2012 The same thing until today I try new driver from Nvidia, PPSSPP doesn't crash anymore.

I guess I'll closed this now.
