### ISSUE TITLE
[Feature Request] add loading indicator when cache iso to ram is enabled

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#7951]
On the x64 version there is an option that allows you to read the game image from the ram rather than from the hdd.
Since ppsspp looks like it freezed,is there is a way to add some kind of indicator showing how much of the image is copied to the ram.

And btw how exactly this work...why any game I try to load(even couple of games one after another...even larder games)the loading time is slow the first time but after that even if I restart ppsspp,the games are loaded MUCH faster

**Comment by hrydgard** [comment]
It's of course possible, although a little tricky. Just need to prioritize it against all other improvements the emulator needs..

That speed the 2nd time would be Windows keeping the file in RAM cache

**Comment by vsub** [comment]
But the ram usage is the same as when the game was not started.
I have 16GB and 4gb is used before starting ppsspp

**Comment by unknownbrackets** [comment]
Windows uses a cache for all file/disk reading.  This is because disks are slow.  When you read a file in any program, it will read into this cache, typically.  I don't know the exact rules of this cache, but if you have enough free ram you can be sure some of that free ram is being used for disk cache.

I don't think it ever shows the memory as used when it's in the disk cache, but I might be wrong.  Physical memory usage indicators might count it.

IMHO we should just start the game while caching the iso (like the CachingFileLoader does), but just have no upper limit on preloading and maybe a (short) early preload delay to get things started.  This has the following benefits:

1. If the file is a cso, it will cache that instead of the raw iso, requiring less RAM.
2. If the ISO is 1800 MB and the disk is 2 MB/s (worst case scenario on both ends, I think?) then it will take 15 minutes to load in fully.  But a more standard disk/iso will take < 90 seconds.  This means it'll be fully cached by the time they're in game, most of the time.  Either way it's a better experience.
3. It still fully solves the original goal of the setting.

I think this would also be easier to implement than a loading indicator (except when the multithreaded setting is on.)

-[Unknown]
