### ISSUE TITLE
Buffered rendering issue on PowerVR SGX 544 for Dissida 012 duocecim : Final Fantasy on PPSSPP 1.0.1

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#7961]
Here is screenshot for this issue
i hope it's will fix on the build version or v1.1
![screenshot_2015-09-12-19-34-47](https://cloud.githubusercontent.com/assets/11285640/9831550/5104f9d4-5987-11e5-929e-76d0e916f990.jpg)

**Comment by zminhquanz** [comment]
It's missing and glitch texture

**Comment by zminhquanz** [comment]
Can you see this issue ? @hrydgard

**Comment by hrydgard** [comment]
Sure. Just as strange as all the other PowerVR issues....

**Comment by zminhquanz** [comment]
@hrydgard 
Non-buffered rendering , everything is normal , no issue
![screenshot_2015-09-14-12-25-10](https://cloud.githubusercontent.com/assets/11285640/9842709/ede262dc-5adb-11e5-90d1-feab4c92439c.jpg)
![screenshot_2015-09-14-12-22-42](https://cloud.githubusercontent.com/assets/11285640/9842710/edf86442-5adb-11e5-9852-04a01577b81b.jpg)
![screenshot_2015-09-14-12-23-38](https://cloud.githubusercontent.com/assets/11285640/9842712/edfece68-5adb-11e5-8106-4cf39336cc6e.jpg)
![screenshot_2015-09-14-12-24-24](https://cloud.githubusercontent.com/assets/11285640/9842711/edfdd238-5adb-11e5-9d5c-75ae87e785de.jpg)
Buffered rendering , missing texture , character ( Lighting , Cecil , Yuna , etc ... ) and glitches
![screenshot_2015-09-14-12-25-23](https://cloud.githubusercontent.com/assets/11285640/9842731/23c86306-5adc-11e5-897a-cc45bf083bac.jpg)
![screenshot_2015-09-14-12-22-57](https://cloud.githubusercontent.com/assets/11285640/9842732/23cbfab6-5adc-11e5-81d8-6759f23845b1.jpg)
![screenshot_2015-09-14-12-23-53](https://cloud.githubusercontent.com/assets/11285640/9842734/23e21382-5adc-11e5-965a-337f05fe72fe.jpg)
![screenshot_2015-09-14-12-24-38](https://cloud.githubusercontent.com/assets/11285640/9842735/23e3bcc8-5adc-11e5-8c22-310ba9c41425.jpg)
P/s : Like as title , my device using PowerVR SGX 544

**Comment by unknownbrackets** [comment]
Do any errors show up int the log?  For example: shader compile errors?

Otherwise, my guess is that this is blending, stencil, or depth related.  It's very possible the backbuffer has different settings for one of those things that the FBOs.  That would explain why "skip buffer effects" would render differently.

The characters are drawn with:

1. Alpha testing > 0x04.
2. Stencil testing: ALWAYS, but replace stencil/alpha with 0x80 on pass/pass.
3. Depth testing: src >= dst
4. Blend: simple src.a + (1.0 - src.a).
5. Weights/skinning, between 1-5 weights.  Multiple flushes even so.

I guess the most likely issues there are the alpha test and depth test.  Does it help to "disable alpha test" in the settings?

-[Unknown]

**Comment by zminhquanz** [comment]
Disable Alpha Test can't help this , the issues still there

**Comment by unknownbrackets** [comment]
This is the same as #7740 and ended up wasting time doing things twice.  Closing this as a duplicate.

-[Unknown]
