### ISSUE TITLE
Metal Gear Solid: Peace Walker can't do anything except cancel out at mission select screen

### ISSUE THREAD

**Issue by JeffreyZic** [hrydgard/ppsspp#8014]
MGS: PW won't allow me to do anything but cancel out once I get into the Mission Select menu (can't even use controls to change to different parts of menu). I select "Mission Selector" from Mother Base and it seems to hang on the loading screen for several seconds before loading. After it loads it shows the 'Starting Search" dialog, and once that goes away everything stops.

Might be related to issue #2549  It doesn't get completely stuck at the loading screen, but when it hangs the symbols becomes dull like in the screenshot there (http://i.imgur.com/682G9o2.jpg).

Tried on multiple versions, and occurs on all I've tried as late as the 'v1.0.1-2789-gc2f4fad' revision. Occurs in both x86 and x64 versions.

I've gotten it to work before and once it works it seems to work for the entire session, though I'm not sure how I did get it to work,  it may have just been trying it enough times rather than anything specific

Here's my ppsspp.ini:
https://gist.github.com/Gixugif/4fba775127ae275522e9

**Comment by SukharevAndrey** [comment]
PC configuration? PPSSPP settings? I have 100% working MGS PW on the latest Git build (and several previous too).

**Comment by hrydgard** [comment]
If I remember correctly, one of the Metal Gear games has problems when using Install Data. Did you do that, by any chance?

**Comment by Gixugif** [comment]
Yes, you're right, I did use Install Data. I'll try and see if it works without doing that

**Comment by Gixugif** [comment]
Ok, I finally got around to removing the install data. It forces you to install some, but I skipped over what I could, and it still didn't help. Running v1.1 now.

**Comment by Gixugif** [comment]
Ok, I've managed to figure out what's causing it, it seems to be having networking enabled. If I disable it I can load into the Mission Selector fine, and in fact, if I re-enable it while playing I can too, however when I try to search for host it is at that point that the problem starts again.

Since it's a beta feature, I guess problems are to be expected, but I didn't have this problem at first and most other people don't seem to, but I'm still curious what exactly it is about my set-up that causes it.

**Comment by SamueldeSena** [comment]
this problem has already been corrected in the new version of ppsspp v1.5.4 this topic can already be closed
