### ISSUE TITLE
absdiff blend effect broken in Super Robot Taisen Z2

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8035]
SInce https://github.com/hrydgard/ppsspp/pull/7870

wrong
![01](https://cloud.githubusercontent.com/assets/3481559/10338019/2b379ad2-6d36-11e5-8f3b-6399c715b253.png)

correct
![02](https://cloud.githubusercontent.com/assets/3481559/10338020/2b42568e-6d36-11e5-9557-78b9dfaac731.png)

**Comment by daniel229** [comment]
This one caused. https://github.com/unknownbrackets/ppsspp/commit/62de281e3580a27b7fa185e21a7a0b0d1639126b

**Comment by daniel229** [comment]
absdiff blending is also broken in Beats and Tenchu 4

**Comment by unknownbrackets** [comment]
The absdiff blending is working in Dragon Ball Z: Tenkaichi Tag Team Demo for me, I don't have the other games.

If you make this false, does it change?

https://github.com/unknownbrackets/ppsspp/commit/62de281e3580a27b7fa185e21a7a0b0d1639126b#diff-5ce09ad7d00cb20e6759a64a887cce54R1056

It's not completely impossible this was accidentally working before.

-[Unknown]

**Comment by daniel229** [comment]
Don't change anything.

**Comment by unknownbrackets** [comment]
What about changing:

https://github.com/unknownbrackets/ppsspp/commit/62de281e3580a27b7fa185e21a7a0b0d1639126b#diff-5ce09ad7d00cb20e6759a64a887cce54R1121

From `BINDFBCOLOR_MAY_COPY_WITH_UV` to `BINDFBCOLOR_MAY_COPY`?

If not that one, this one?

https://github.com/unknownbrackets/ppsspp/commit/62de281e3580a27b7fa185e21a7a0b0d1639126b#diff-81225357fb059f16c55ad743d356f41bR907

-[Unknown]

**Comment by daniel229** [comment]
Those changes make the color from black to white,still not right.

**Comment by unknownbrackets** [comment]
If you revert that commit on latest master (not sure if it will revert clean), does it look right?

-[Unknown]

**Comment by daniel229** [comment]
Just do something wrong,leave the disable slow effect option on.
 Change from <code>BINDFBCOLOR_MAY_COPY_WITH_UV</code> to <code>BINDFBCOLOR_MAY_COPY</code> ,don't change anything.

reverting that commit,it looks right.

**Comment by unknownbrackets** [comment]
Well, breaking it down... the main parts are:

1. https://github.com/unknownbrackets/ppsspp/blob/62de281e3580a27b7fa185e21a7a0b0d1639126b/GPU/GLES/Framebuffer.cpp#L875-L882
2. https://github.com/unknownbrackets/ppsspp/blob/62de281e3580a27b7fa185e21a7a0b0d1639126b/GPU/GLES/TextureCache.cpp#L1055-L1082
3. Removing RebindFramebuffer from BindFramebufferColor and putting it in the callers.

It's most likely one of the first two.  Does removing either of them help?  I think you already tried one - was that with disable slow effects off?

-[Unknown]

**Comment by daniel229** [comment]
Removing the first part,it works.
The second part  have done before,make it false and it doesnot work,of course disable slow effect is off.
Not really understand the third part means.

**Comment by unknownbrackets** [comment]
Can you add a log inside `if ((flags & BINDFBCOLOR_MAY_COPY_WITH_UV) != 0 && gstate_c.vertMaxU > gstate_c.vertMinU) {`, first before the changes to x/y/w/h, and then after them, and see what it's changing them to?

The two lines here should be the only ones passing that flag, though... hmm.

https://github.com/hrydgard/ppsspp/issues/8035#issuecomment-146418992

Did you try changing both of them, maybe?  Just want to be sure.  Changing both should be the same as removing the first part.

-[Unknown]

**Comment by daniel229** [comment]
In the master,is it add one log after 
```
				// If we bound a framebuffer, apply the byte offset as pixels to the copy too.
				if (flags & BINDFBCOLOR_APPLY_TEX_OFFSET) {
					x += gstate_c.curTextureXOffset;
					y += gstate_c.curTextureYOffset;
				}

```
if so,this is the log of beats,
https://gist.github.com/daniel229/d48367ec7c9b07f68f3f


https://github.com/hrydgard/ppsspp/issues/8035#issuecomment-146418992
those lines,changing both of them still nothing change.
https://github.com/unknownbrackets/ppsspp/commit/62de281e3580a27b7fa185e21a7a0b0d1639126b#diff-5ce09ad7d00cb20e6759a64a887cce54R1121 is a little difference from master.

**Comment by unknownbrackets** [comment]
Ah, I had a thought.  Maybe it's uvScale?

Does prescale texcoords help this?

Can  you log this inside that same place?

```c++
NOTICE_LOG(HLE, "UV scale: %f,%f off: %f,%f", gstate_c.uv.uScale, gstate_c.uv.vScale, gstate_c.uv.uOff, gstate_c.uv.vOff);
```

I probably need to account for those inside.  Honestly, prescale is better, we should figure out the remaining bugs in it... I guess theoretically, I could handle wrapping too... maybe a fixup step on the maxV/etc. values.

-[Unknown]

**Comment by daniel229** [comment]
What is prescale texcoords?
Yes,it logs  <code>UV scale 1.0, 1.0 off: 0.0, 0.0</code>.
https://gist.github.com/daniel229/811cd9ec6513aabd4d33

**Comment by unknownbrackets** [comment]
"Texture coord speedhack (speedup)" in graphics settings under Hack settings.  This one is mostly a hack because it has bugs we don't know the cause of, last I remember...

Hmm, so it's not uv scale.  Darn.  I thought that'd be it.

This log:
https://gist.github.com/daniel229/d48367ec7c9b07f68f3f

Do you remember if x2/y2 were after the `if (flags & BINDFBCOLOR_APPLY_TEX_OFFSET) {` part?  It's such small chunks and not very spread out...

-[Unknown]

**Comment by daniel229** [comment]
"Texture coord speedhack (speedup)" didi not help.
I forgot there are two,just do it, they log the same thing.

**Comment by daniel229** [comment]
Gedebugger for Beats,This looks simple.

![03](https://cloud.githubusercontent.com/assets/3481559/11028496/f6c73ea0-86f9-11e5-9674-398cb53e2e04.png)
Other tabs
https://gist.github.com/daniel229/0118259b77a894c37c1a

wrong
![01](https://cloud.githubusercontent.com/assets/3481559/11028500/ff7febc8-86f9-11e5-879c-ced7e3f59e71.png)

correct
![02](https://cloud.githubusercontent.com/assets/3481559/11028499/ff7e3b16-86f9-11e5-9e07-e3176fb926ac.png)

**Comment by unknownbrackets** [comment]
Okay, looking at that screenshot I just realized... I'm dumb.  Shader blending can't use the UVs, it has to use the positions.  I'm an idiot.  Was just thinking of all the 1:1 bloom stuff.

Well, maybe it would make sense to measure ranges afterward.  Arg...

a821cd3

@hrydgard so, maybe here we could just check `VertexReader reader(decoded, decVtxFormat, vertType);` again, and examine for the X/Y range if in throughmode, which is probably common (as in the above example.)  Then we could get the range that we can properly limit the blit to.

This could work for depal too, even for non-through formats, we could scan the UVs and get the optimization for that Sonic Rivals 2 game (which doesn't use through, but it's only UVs in that case because depal.)  Would need to add a method to transform pipeline or something to grab this info though, not sure of a clean way offhand...

We still want to do it in the reader as we do now, at least, to avoid hashing > 272 of textures where possible.  That's the common case...

-[Unknown]

**Comment by daniel229** [comment]
Great,fixed.
