### ISSUE TITLE
i tried everything 

### ISSUE THREAD

**Issue by 360smchandan** [hrydgard/ppsspp#8090]
i tried everything but  i can't jump to the second rope.Please anybody send me all supported settings for this please.

**Comment by unknownbrackets** [comment]
In this day and age with the internet, searching is another thing you should try.  It helps with almost anything.  Google is great.

https://github.com/hrydgard/ppsspp/search?q=%22second+rope%22&type=Issues&utf8=%E2%9C%93

Basically, some people say it has to do with changing the CPU clock, others say it has to do with not saving and reloading the game due to a bug in the game.  Still others say it has to do with not using the analog stick.  Apparently it happens on real PSPs.

Anyway, this isn't an issue.

-[Unknown]
