### ISSUE TITLE
Ys Seven music suddenly stops!

### ISSUE THREAD

**Issue by blackman91** [hrydgard/ppsspp#8093]
Using the latest dev version on Android, the background music in the game YS Seven suddenly stops after playing a few minutes and you can just hear the sound effects and they all have a weird echo.  I am using the default settings with skip buffer effects option enabled.

**Comment by unknownbrackets** [comment]
Yeah, this is the looping issue.  As soon as it "thinks" it has the entire music buffered, it stops loading more.  Already have a fix but need to do more work/testing on it.

-[Unknown]

**Comment by blackman91** [comment]
Thanks great support as always.

**Comment by dhty** [comment]
The same problem takes place in Sora no Kiseki Series, which are porduced by the same company with Ys7, so I wonder they may have the problems due to the same reason. 

tested on 1.1.1-41, will test again on newer versions later

**Comment by blackman91** [comment]
Tested the newest version, it appears the issue is still present.

**Comment by dhty** [comment]
Well, this problem has appeared for a long time in Sora no Kiseki Series (tested on a very old version, maybe before 1.0.0?). really hope this can be solved because every time this problem takes place, I have no choice but to save & reload the game.

**Comment by unknownbrackets** [comment]
I do actually have a solution but right now, it involves a lot of changes.  We'll probably merge it not that long from now, but it may break other things (in these games or others.)

-[Unknown]

**Comment by dhty** [comment]
@unknownbrackets That sounds really good, hope this solution may be compatible with other isos in the future.

**Comment by blackman91** [comment]
Awesome, curious about what other things could this fix break?

**Comment by unknownbrackets** [comment]
Well, the problem is that sceAtrac can be used for a lot of different things.  It's not just a play button in a media player - it's more like a complicated appliance.

Sometimes two bugs are "working together."  For a simple example, let's say that sometimes we loop music when we shouldn't, but because sometimes looping breaks and doesn't loop, games work anyway.  Fixing looping might actually break those games, because it exposes the other bug (even if those games would work better with both bugs fixed.)

To be more technical, the PSP has multiple "modes" for playing ATRAC3+.  They mainly split between "all the data gets put in memory" and "since the PSP only has 24MB of memory for the game, only part of the music can be in memory at any given time (streaming.)"  The old code treated ALL music the first way - since desktops have plenty of memory, there's no need to feel limited by the PSP's meager memory supply.

However, games aren't written for the system appearing to have a magical amount of RAM - and that's part of the reason looping wasn't working here.  Now that it's actually (partially) acting like it has the limits it should, there's tons of potential bugs that might've been previously hidden from us.

It can also be the case that I've introduced a new bug in my changes - maybe music will click sometimes now or something.  Or maybe timing will be off, or music won't end properly.

I plan to implement more changes to sceAtrac to make it even more correct, but I prefer to do it "bitesize", because if I try to change everything at once, I'll just end up breaking a lot of things at once.

-[Unknown]
