### ISSUE TITLE
MGS Peace Walker recruit function

### ISSUE THREAD

**Issue by Antonio1994** [hrydgard/ppsspp#8094]
I was a long time off from ppsspp and git hub. Now that I'm back I see a lot off progress on this game and AFAIK only the recruit option is not working. I play on a PC and tryed connecting via WiFi and router but it doesn't work. Does anyone have a clue what could cause it? Sorry if its double posted, haven't found the same issue here ;),

**Comment by thedax** [comment]
I could be wrong, but I think that function tries to connect to an actual router to "download" new recruits. Such functionality isn't implemented in PPSSPP.

**Comment by Antonio1994** [comment]
Hmmm...haven't thought about that...I'll check the log if anything shows
up...I'm stuck at lvl90 with the combat unit so I thought off speeding
things up :-)

subota, 24. listopada 2015. korisnik thedax <notifications@github.com>
napisao je:

**Comment by asl97** [comment]
@Antonio1994 if you talking about the ap recruit, i think it depend on the amount of wireless access points and their signal strength. it doesn't "download" anything so it doesn't require internet access.

in any case, iirc, those recruit that you get from the ap recruit are pretty weak,
it's better to target those extra (hard) missions for recruits

**Comment by Antonio1994** [comment]
I have S ranked every mission and submission. I dont need recruits, I'm just saying this function doesn't work properly :)

**Comment by LunaMoo** [comment]
If anyone cares, I got to mess around with this game and made this work:
https://gist.github.com/LunaMoo/ec340ddf0f6bc7c7277e7b9603061a8e

 That code is hackish, full of guesses, definitely not for merging.
In short the 3 functions that have to be implemented for this to work are:
```
sceNetApctlScanSSID2
sceNetApctlGetBSSDescIDList2
sceNetApctlGetBSSDescEntry2
```
 But I also added a nasty hack which checks for and replaces one opcode for something I couldn't figure out.

 It's also feeding the game with completely random stuff instead of allowing some kind of UI selection or emulating it properly ~ which actually isn't all that bad as with static data feed from stationary device like a pc the game would heavily limit this feature. Still could be improved as the random data should follow some rules, I filled everything with same number of random data which is completely wrong, could in fact break some other game or affect the randomness of recruits if it for example depend on lenght of data or takes only ascii characters for example.

 Use at your own risk / someone will have to investigate it further, don't have any psp I could use anymore and I don't think anyone ever documented those syscalls at least I couldn't find anything on them.:]

**Comment by benderscruffy** [comment]
Is this still an issue ??

**Comment by kp8888** [comment]
Recruiting with AP scan works normally for me now

**Comment by unknownbrackets** [comment]
Thanks for checking, I'm going to mark this as closed then.

-[Unknown]
