### ISSUE TITLE
Patapon 1

### ISSUE THREAD

**Issue by fredbcode** [hrydgard/ppsspp#8133]
During the tree dance, the inputs for beat are messed up. 
GPD XD android PSSPP 1.1.1

EDIT: FI there is also a little lag not noticed with others games because timing is not so critical

**Comment by unknownbrackets** [comment]
I don't know much about that device, but it seems this is its SoC:
https://en.wikipedia.org/wiki/Rockchip_RK3288

If you are using frameskip, lazy texture caching, or the vertex cache, you may definitely experience lag.  Most of all, you'll want to enable "Force real clock sync", although this may drain your battery more quickly.

Other than that, issues like this can really just be up to the device.  The hardware must deliver the signal to PPSSPP before anything can even be done with it.

Please note that the game samples at a rate of 60 times per second, which means the game itself (even on a PSP) has an input lag of around 16ms.  Without "Force real clock sync", the speed of your device will impact this; faster devices will have up to 33ms of input lag, because the game only actually *renders* at 30 fps.

I'm going to close this.  If that setting doesn't work for you, please feel free to reply.  But if you're expecting better than 16ms input lag, note again that the PSP wasn't giving that for this game either.

-[Unknown]
