### ISSUE TITLE
Found more games broken by DepthRounding.

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8187]
Adding to compat.ini really can't solve the problem,better to find other way,pretty micro flicker though.
Seventh Dragon 2020 1
Seventh Dragon 2020 2
Toukiden
Toukiden Kiwami
Nariso konai eiyuutan
Assassin's Creed Bloodlines

**Comment by unknownbrackets** [comment]
Does the other option (not suggesting this is a fix) for using per-pixel depth rounding help?  Just trying to get a handle for what is happening here.

I know that depth rounding fixed a few games.  Perhaps we can look at heuristics for what they are doing that makes it help; I know that in Phantasy Star 1, all cases were flat - e.g. all vertices had the same Z.  I doubt that is a good heuristic, but I would assume that case is perfectly safe to do the rounding in.

-[Unknown]

**Comment by daniel229** [comment]
Per-pixel depth rounding help those games

**Comment by unknownbrackets** [comment]
Yeah, so that implies to me that we're losing some accuracy by rounding each vertex when it's not flat (or causing the interpolated values to change significantly because the end-point changed enough.)  Hmm.

Maybe we should log the depth testing these games use.  For example, we could enable rounding only when `>= <= = !=` tests are used.  That means one frame would be wrong, but it might improve speed of later frames?  Then again, shader compiles.  But if these games are only using > and <, the rounding is probably unnecessary.

-[Unknown]

**Comment by hrydgard** [comment]
It's very possible that micro flicker is actually present on the real PSP, just not too noticeable because the resolution is smaller and the screen is very slow to update.

Higher bit depth usually fixes such glitches, except in the few games that rely on some very close values to match. You could actually easily argue that what we do without depth rounding, that is, using a 24-bit depth buffer instead of 16-bit, is actually a quality improvement of the same kind that we currently do with resolution and color depth - we optionally render at higher resolution, and we always render with 32bit color even if games request 16-bit, so it's not too strange to always render using a higher bit depth Z-buffer to reduce depth glitches that happen on the real PSP.

From this point of view, an "enable" compatibility setting makes more sense than the current "disable". We do want things to look as good as possible but be as accurate at possible at the same time, and these goals conflict in a few cases.

That said, it's very possible that we lose a bit too much precision somewhere in vertex depth rounding, but not enough to break Phantasy Star obviously. So it makes sense to keep both vertex and pixel depth rounding, but having both of them disabled by default, but we should also, now or later, look into seeing if we can improve vertex rounding more.

**Comment by unknownbrackets** [comment]
Well, I like quality improvements that are "undetectable," the kind that can't cause issues.  Unfortunately, this isn't one... but I agree that in spirit, higher depth makes more sense.

I still think it might be possible to use heuristics to determine when the quality improvement is unsafe.  While there are scenarios where `<` and `>` could rely on rounding, this is very unlikely.  Unfortunately, Phantasy Star Portable relies on it because it uses a `>=` or `<=` check later in the same frame.

If none of the games affected ever use an equal depth check ever, which I'm pretty sure is the case in most games, we could safely disable depth rounding in them without much concern for compatibility impact.

-[Unknown]

**Comment by hrydgard** [comment]
Both color depth and resolution increase are definitely "detectable" (although color depth not so easily), and 

Let's wait a day for your report results. I have a feeling that in general, >=/<= is way more common, probably because in the normal case, that will reduce depth fighting issues compared to >/<.

**Comment by unknownbrackets** [comment]
Fair enough.  You're aware I generally run at 1x, right?  Heh.

Hmm, okay, seems you're right.  I guess it's just the problematic draws that I've spent time looking at which use > and <, haha.

The problem really comes in when the depth is handled differently.  In Phantasy Star, it writes depth using throughmode, and also using transform, and so the precision is different.  Technically, this could be caused by matrices, but it's probably most common when the same framebuffer is written with different depth formats/transform.  But, that's kinda a gnarly heuristic maybe.

-[Unknown]

**Comment by unknownbrackets** [comment]
Well, bugger, equality depth tests even in throughmode are still pretty common:
http://report.ppsspp.org/logs/kind/782

Even Ridge Racer...

-[Unknown]

**Comment by unknownbrackets** [comment]
@hrydgard so, we have a 1x and 2x option.  Maybe we should just have an option to turn on per-fragment depth rounding (where supported), or turn it off?  We can keep the whitelist for per-vertex rounding when per-fragment is not on.

I found some z fighting in Phantasy Star Portable 2, and turning on per-fragment rounding fixes it for me.  In some ways it's like 1x vs 2x issues.  There are tradeoffs.

-[Unknown]

**Comment by daniel229** [comment]
Since https://github.com/hrydgard/ppsspp/issues/8433 is merged,closed
