### ISSUE TITLE
Cant see any files in filesharing!

### ISSUE THREAD

**Issue by milk-hue** [hrydgard/ppsspp#8201]
Everytime I try to add files threw itunes with file sharinh, I don't see any folders. Clicking add a file doesnt add anything either.

**Comment by unknownbrackets** [comment]
I think this may have been implemented in some way in #10921.  Does that work?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
