### ISSUE TITLE
sound is glitchy on dragon ball z shin budokai 

### ISSUE THREAD

**Issue by Gear22** [hrydgard/ppsspp#8207]
The game runs fine, no lag at all but gets between 60 and 80% on the speed and 50fps. What would make the sound stop stuttering? Thanks!

**Comment by hrydgard** [comment]
Getting speed to 100% is the only way to improve audio stuttering. Try to decrease the rendering and display resolution, and set Frameskipping to 1 or 2. The latter will cause the graphics to be a bit more choppy, but it can be worth it to get more speed.

Anyway, this is really a support issue rather than a bug, for this type of questions see the forums, http://forums.ppsspp.org/ .
