### ISSUE TITLE
On-screen controls don't work when hidden

### ISSUE THREAD

**Issue by Verycoolbotan** [hrydgard/ppsspp#8208]
Google Play version from 13/11/2015

**Comment by hrydgard** [comment]
When turned off, of course they don't work. If you want them to work, keep them on and make them really, really transparent.

**Comment by Verycoolbotan** [comment]
Thanks for reply. They aren't turned off, they are hidden in visibulity settings.

**Comment by unknownbrackets** [comment]
Buttons that are "not visible" are disabled.  Perhaps we should phrase it better.  "Choose"?  "Buttons"?  "Change"?  "Palette"?  It's hard with just one word.  I can see how "Visibility" is misleading.

-[Unknown]

**Comment by hrydgard** [comment]
Oh, individual buttons. I wouldn't expect them to work when hidden.

I would recommend to just reduce transparency of all the buttons until they don't bother you....  Individual invisible buttons sounds incredibly confusing.

**Comment by unknownbrackets** [comment]
Does auto-hide solve this use case?

I'm not sure we can come up with a clearer wording...

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

The auto-hide feature seems to make controls a lot less in your face, and the opacity settings give options too.  So far it seems like the terminology of visible hasn't misled too many people, so hopefully it's making sense.

-[Unknown]
