### ISSUE TITLE
[Feature request] Automatic settings for netplay

### ISSUE THREAD

**Issue by thatcadguy** [hrydgard/ppsspp#8226]
At the suggestion of Henrik, putting this here instead of on the forums.

I've been messing around with the netplay and in doing so I've been seeing a lot of threads/pages saying to change this setting or that setting (settings not in the networking section, e.g. frameskip). If a handful of settings should be set a particular way in order for netplay to work correctly, these settings should be set automatically when "enable networking/WLAN" is checked. Also, if there are any settings dependent on latency, it'd be nice if devices could ping each other and set these automatically as well. Netplay (for all emulators, not just PPSSPP) can be a major headache when trying to do anything but play with someone in the same room, anything that can be done to make the process easier and more reliable would be great.

**Comment by hrydgard** [comment]
Do you have a proposal for how it should work? What are some better defaults we could set?

**Comment by thatcadguy** [comment]
Thing is, I don't have much knowledge of settings since I just started using PPSSPP weeks ago (great work BTW!). For instance though, if you go to the ad-hoc section of the forum, some of the tutorials mention changing certain settings e.g. disable fast memory, change frameskip if needed to get 100% speed, disable timer hack, etc. If these are true, then they should be dealt with automatically if networking is enabled (if possible).

Perhaps it's my own lack of knowledge of the emulator itself and this might already be available via logs, but I think a great start to improving netplay would be more verbose error messages, e.g. was there a problem opening a port, was a packet send but no response received, is there a latency issue, etc. I say this because of the troubles I've encountered trying to get two Android phones to work together, and trying to get a PC to play with an Android phone. I'd like to be able to give a helpful report instead of "it doesn't work".

If there are known issues that need work, I can take a crack at them if someone can point me to which files to start with.

**Comment by GamerzHell9137** [comment]
@hrydgard Why not make it like Dolphin uses game settings per .ini ?

**Comment by hrydgard** [comment]
@GamerzHell9137 how would that help with this issue?

**Comment by GamerzHell9137** [comment]
@hrydgard Can't we like put settings for each game in a .ini file and make it load the settings while launching the game? Doesn't Dolphin do that already?

**Comment by hrydgard** [comment]
Of course we can but nobody has made clear what those settings are.

I don't know much about netplay myself as I don't play it, so if you guys want something done in this area, either send pull requests or be VERY SPECIFIC.

**Comment by LunaMoo** [comment]
We only have somewhat still active MH community for online play, so I would say there are much more people who use adhoc only to play with friends locally and probably even more who enables wifi without using multiplayer just for some features that check it - my point saying that - there's no need to force online related stuff for everyone.

 Shipping hundreads of ini files with emulator for few people to use a wip feature is bad idea in general, there could just be an additional compatibility setting in network menu that enabling would disable some settings/features + force restarting emulation or disable ability to set it when game is already running.
 Speaking of which outside of some short online testing I only play on lan, but I would list: fast memory, multithreading, cpu clock, timer hack, read framebuffers to memory rendering modes as well as unthrottle and savestates as unsafe/adhoc breaking settings/features. Pretty much default settings with fast memory disabled is all that's needed for best compatibility, however for actual online you also need to make sure firewall doesn't stop you, set your device in DMZ and/or using one of the few third party tunneling software, so either way this will not be plug and play by just setting some stuff in ppsspp. Connection also has to be pretty solid, psp games were not designed for real online multiplayer and while they don't transfer much for the most part can't deal with latency issues.

 Also going back I belive @thatcadguy doesn't even need any special settings, his problem is trying to play on android which requires port offset like #8134 otherwise compatibility is very low even in comparing to windows which already isn't all that perfect and goes even worse with wan.

**Comment by ANR2ME** [comment]
The reason why "Fast Memory" need to be disabled is to increase the chance for the game to keep running in the case of crashes/invalid address access (hoping the game to handle the exception) happened due to a buggy Adhoc Matching callback handler causing registers/memory corruption, with Fast Memory enabled it could cause PPSSPP to crash. 
I've tried to reduce the chance for these register/memory corruption on my previous commits (resulting a quite stable 6-players on Dissidia-012), but sometimes i still seeing invalid address in the log during adhoc matching, so there must be something else to be fixed.

**Comment by unknownbrackets** [comment]
Any case in which "fast memory" needs to be disabled is simply a bug.  IMHO it would be more ideal to fix bugs than to ship a few thousand ini files disabling it in certain games that expose these bugs.  Because that is basically like plastering the bugs so they will never be squashed.

We might as well revere and celebrate the bugs if we're gonna do that.  At that point it's a game of "how can we make the bugs work together to make the game only break randomly *sometimes*?"

Not saying that the network code isn't complex, just arguing against the idea of "default settings" for bugs.

-[Unknown]

**Comment by thatcadguy** [comment]
If this is the case then I retract my request. I agree with unknown.

**Comment by unknownbrackets** [comment]
To be fair, I don't use netplay either; if there are some latency settings or something that some games need, that may make sense.  I'm not aware of any settings except the "real time clock sync" setting, which we could potentially auto-enable when networking turns on, I guess.  Note that it has a significant battery drain impact, especially on Windows (e.g. laptops.)

-[Unknown]
