### ISSUE TITLE
[ Feature Request ] Custom resolution for textures

### ISSUE THREAD

**Issue by Hipnosis183** [hrydgard/ppsspp#8230]
In higher resolutions, even with xbrz and fxaa, some textures look bad. But with lower resolutions (like 2x or 3x) they look better.
Is possible play with lower resolution textures in high rendering resolutions?

**Comment by unknownbrackets** [comment]
I think the reason some textures will look worse is because they are sampled more times at higher resolutions.  I guess MSAA might "improve" this, as well as upscaling textures.  We have an issue open for MSAA already, and we already have a feature for upscaling.  Texture replacement is another possible option, and that also already has an issue.

Since a lot of drawing will use textures, using lower resolution for textured drawing just means using a lower resolution.

Closing this as such.

-[Unknown]
