### ISSUE TITLE
tales of phantasia cross editon crash problem andriod

### ISSUE THREAD

**Issue by asbel123** [hrydgard/ppsspp#8247]
i got one crash in tales of phantasia cross edition when i fight in the battle one of eniemes to do one magic is summon demon it will crash already will quit ppsspp automaticlly when to andriod home screen please fix it hygard thats wierd bug i cant finsh the game.

 i am using samsung galaxy s6 edge.

**Comment by daniel229** [comment]
Any savedata provided？

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
