### ISSUE TITLE
extrange issue's in the latest nightly builds

### ISSUE THREAD

**Issue by itornukem64** [hrydgard/ppsspp#8248]
I don't know if you already know about this, but in the 1.1.1-340 and as far i can say in 1.1.1-336 too, the emulator displays some objects

**Comment by itornukem64** [comment]
Sorry for that, touched the button accidentally,  well,  some objects in black, of the ui.
I'm using x86, I don't known if is part of the problem,  a Samsung galaxy tab 3 10.1.
Oh n btw the game Daxter is broken since 1.1.1, n dead to rights reckoning doesn't load in x86.

**Comment by unknownbrackets** [comment]
What's the first git build that stopped working, and the last git build that still worked?

-[Unknown]

**Comment by itornukem64** [comment]
Mmm the latest was the 1.1.1-321 and in 1.1.1-336 it's not working already I don't tested the others ones.

**Comment by unknownbrackets** [comment]
Does that mean it was working in v1.1.1-321-g63769a2?  If not, what was the most recent git build it was working in?

For me, it's almost impossible to "guess" what version might've started having the problem, or when it started.  I neither have your device nor either game you mentioned, so I cannot test either.

However, you on the other hand are quite powerful: by trying just a few builds, you can narrow down the problem.

First, try an older release, like v1.0.1 - https://github.com/hrydgard/ppsspp/releases/tag/v1.0.1.  If it doesn't work there, you'll have to go back further until you find where it worked for you before.  If you can't find it working before, you probably changed some settings that broke it instead.

If that works, look at the buildbot - http://buildbot.orphis.net/ppsspp/index.php?m=fulllist

Since v1.0.1 (2015-02-26), we've made 3200 changes.  While I would have to look at *each one* of these 3200 changes, one at a time, and try to guess if *maybe* it broke either game, you are like a superhero compared to me.  You can try one build, half way in between those two, and bam - you'll blow away 1600 of those changes as if they were just scraps of paper.

It turns out that while I could spend the next year of my life pouring over those 3200 commits, and maybe still not figure it out, with your superhero powers you could try just around ~12 builds (cutting it in half each time) and you'd narrow it down to a small handful of "small fry", something like 5 changes.

I can probably deal with the small fry - but I need you, the superhero, to take on the huge wave.  I can't do it alone.  You're the one with the powers here.

-[Unknown]

**Comment by itornukem64** [comment]
The game stopped working (Daxter) in 1.0.1-2699, in 1.0.1-2686 is still working. And don't be so rude, I'm not a super hero XD.

**Comment by unknownbrackets** [comment]
Heh, not trying to be rude at all.

So that points to #7952.  Hmm, there might be something different about how it's interpreting the ISO, or else maybe there's something more tricky about the case insensitivity?  It's definitely case insensitive...

-[Unknown]

**Comment by unknownbrackets** [comment]
Did you find something?

-[Unknown]

**Comment by itornukem64** [comment]
Yeah now

**Comment by itornukem64** [comment]
Sorry yeah now the extrange black bordes are gone.
