### ISSUE TITLE
[Hardware Dependent] Snapdragon 810/Adreno 430 Graphical Corruption.

### ISSUE THREAD

**Issue by sewer56lol** [hrydgard/ppsspp#8254]
Not explicitly technically an emulator bug in itself but how the GPU hardware functions with the driver which has an adverse result on the emulator (some kind of hack may need to be necessary for the future potentially).

This is more of an oddball issue which I have noted and is probably (presumably) caused by how the hardware interacts with the driver for Qualcomm Adreno GPUs (known for not so good drivers on Android regarding emulation) - for all the devices I currently possess it is limited only to my Oneplus Two (my only Snapdragon 810/Adreno 430 device) which I have received yesterday.

Below are some screenshots of Sora no Kiseki/Trails in The Sky SC taken from my acquired device (all 3 games of the series - and (presumably) other games are affected) - whenever the game applies alpha/transparency effects on the whole screen, some serious display corruption is seen on the Adreno 430. *(However equally well when alpha/transparency is only applied to part of the screen - (see 3rd screenshot) the corruption is not present)*

-Given result: http://imgur.com/a/LNcww 
*(Screenshot from Oneplus TWO w/ Marshmallow Preview 3 GPU Driver - the most recent known Adreno driver for 3xx/4xx functional in Lollipop)*
**Adreno 430**

-Expected result: http://imgur.com/a/kwQzV 
*(Screenshot from Nexus 5 running the same GPU Driver)*
**Adreno 330**

**What I have personally tried as workarounds:**
- Flashing (presumably) newer Adreno driver (last most recent known 4xx driver known to function on lollipop is the driver bundled with Marshmallow Preview 3 as mentioned above).

- Flashing non stock kernel/ROM: The existing Cyanogenmod 12.1 build for the OPT device which features a completely different kernel based on CodeAurora Forums (CAF) and non stock Firmware sources - it had no effect.

- Obviously all of PPSSPP settings - none had an impact on the corruption present.

**In other words - it is not**
- A bug in the driver itself (tested with 3 devices on 1 same driver) **but** a bug with the hardware (Adreno 430) running any known Adreno driver.
- Caused by the device firmware.
- Caused by the kernel.
- Caused by any PPSSPP settings.

**To easily replicate**
- With a Snapdragon 810/Adreno 430 device simply press start to open up the menu in game, (Or use any art with heavy effects during battle such as Aero Storm).

**Specsheet of the affected device first spotted with adverse effect (if useful)**
- OS: **Android OS, v5.1.1 (Lollipop)**
- Firmware : Oxygen OS 2.1.3 / Cyanogenmod 12 (Unofficial)
- Chipset: **Qualcomm MSM8994 Snapdragon 810**
- CPU(s): Quad-core 1.56 GHz Cortex-A53 && Quad-core 1.82 GHz Cortex-A57
- GPU : **Adreno 430**
- Architecture: **ARM64**

**And a small oddball**
~~My Nexus 5 (ARM) emulates the game faster (by approx 30%) than my Oneplus Two (ARM64) (suggesting that the GPU might also not be properly supported or bottlenecks or that ARM64 in PPSSPP is not yet fully optimized to levels of ARM).~~

After a few of my own tweaks I've done on the kernel I take that back a longshot.

**Comment by unknownbrackets** [comment]
So, this is interesting, but please note - the particular screen at the top you're looking at has a very important effect that I can DEFINITELY imagine being the problem.

Is the problem the same even with "disable slow effects" checked and "simulate block transfer" unchecked?  This would disable the effect I suspect.  If it just shows a solid color (like black), then it may confirm my theory.

The effect in question is downloading the framebuffer and then re-uploading it.  The game does this to create a still of the game's screen while in the menu.  It performs related effects other places, but the menu is one I'm certain about.

It could be that the download is failing.  Even if it isn't, it's quite likely that the Adreno driver may be logging something.  Can you try running `adb logcat` right after the problem presents?

Whether that helps or not, I may give you some code changes to try and build ppsspp with (it's easy, don't worry), to try and narrow down the problem.  But knowing the above will help me plan those correctly.

-[Unknown]

**Comment by sewer56lol** [comment]
I've made 3 short clips in order to point out the problem - I actually noticed this time around that save states carry the broken framebuffer (which means that I have 'missed' this during tweaking) - and in fact your theory appears correct.

Here is result as expected with disabled effect:
 https://youtu.be/sQBikdSrHwc

Regular settings: 
https://youtu.be/H7DtMUkMuKQ

Load from save state (with effect disabled - the corrupt framebuffer is stored in the savestate it appears):  https://youtu.be/1M48Wu6mLCk

An another interesting tidbit is that as you play the game I have noticed that the corrupt framebuffer is identical one every time and is the one from the very start of the regular session/very first one taken (so if I were to play the game 100% via savestate saving in one session even at the end of the game the corrupt version of the image I would be seeing would be that same one from chapter 1).

As I also pointed out in the recordings due to the way save thumbnails are made the effect also appears to carry there.

I'll make a logcat soon as I grab spare time - I actually took time out of my studies to reply to this.

**Comment by unknownbrackets** [comment]
The save icon also uses a download.  All of these cases use downloads, I think.  It actually looks like it could be a stride-width problem, possibly, although the bands look a bit short.

Yes, when those features are disabled the original "broken" data will not be overwritten, so it will stick around.

Sorry, not trying to drag you out of your studies - but looking forward to the logcat.  I'll still be here even if it's weeks from now.

-[Unknown]

**Comment by sewer56lol** [comment]
Haha, don't worry, it's nothing that serious and I'm well prepared, will post in a couple of hours when I'm done for the day.

**Comment by sewer56lol** [comment]
Edit (That's not really an edit so you see the notification): If you're fine with a quick and dirty log then this should suffice. http://pastebin.com/4089rDsi

I noted this with Catlog which takes logs right from the device. The log here was taken after a reboot - it starts right before opening PPSSPP and exiting Catlog. (during the log in PPSSPP the game is loaded, save loaded and 20 seconds of gameplay occur before I switch off the game and load the other game disc just for extra samples - the log then ends).

**Comment by unknownbrackets** [comment]
@hrydgard fwiw I updated the buildbot to include `assets/compat.ini` in the apk.  Unrelated, but seen in these logs.

The only GL error in that log, unfortunately, is this:

```c++
12-05 20:22:21.120 E/libEGL  ( 9255): call to OpenGL ES API with no current context (logged once per thread)
```

That's interesting, it seems like it's occurring when gl_lost restores some Thin3D shaders.  They're failing to compile (due to the above?)  Anyway, this doesn't appear to be the cause of the corruption.

So, looks like we're going to need to make some changes to get to the heart of this.  To compile, you'll need to install a few things, but it should be easy to build.

First, let's make the change.  In GPU/GLES/Framebuffer.cpp, find:

```c++
		glPixelStorei(GL_PACK_ALIGNMENT, 4);
		GLenum glfmt = GL_RGBA;
		if (UseBGRA8888()) {
			glfmt = GL_BGRA_EXT;
		}

		int byteOffset = y * vfb->fb_stride * 4;
		glReadPixels(0, y, vfb->fb_stride, h, glfmt, GL_UNSIGNED_BYTE, packed + byteOffset);
		// LogReadPixelsError(glGetError());
```

Replace with:

```c++
		glGetError();
		glPixelStorei(GL_PACK_ROW_LENGTH, vfb->fb_stride);
		glPixelStorei(GL_PACK_ALIGNMENT, 4);
		LogReadPixelsError(glGetError());

		GLenum glfmt = GL_RGBA;
		if (UseBGRA8888()) {
			glfmt = GL_BGRA_EXT;
		}

		int byteOffset = y * vfb->fb_stride * 4;
		glReadPixels(0, y, vfb->fb_stride, h, glfmt, GL_UNSIGNED_BYTE, packed + byteOffset);
		LogReadPixelsError(glGetError());
```

And then one more change in that file, find:

```c++
	case GL_STACK_OVERFLOW:
		ERROR_LOG(SCEGE, "glReadPixels: GL_STACK_OVERFLOW");
		break;
```

And make it:

```c++
	case GL_STACK_OVERFLOW:
		ERROR_LOG(SCEGE, "glReadPixels: GL_STACK_OVERFLOW");
		break;
	default:
		ERROR_LOG(SCEGE, "glReadPixels: %08x", error);
		break;
```

Note: `glGetError()` has a performance impact, but we're calling it here to see if any errors are occurring.  I've also added `GL_PACK_ROW_LENGTH` in case it's not using the default somehow.

Now to compiling: we have [build instructions] (https://github.com/hrydgard/ppsspp/wiki/Build-instructions), but I think Eclipse (which they were written for) might be going away.

If on Windows, you might just try installing NVIDIA's GameWorks: https://developer.nvidia.com/gameworksdownload.  Some of the tools are meant for NVIDIA SHIELD, but it also sets you up with things automatically.  Otherwise, just install the [Android SDK] (http://developer.android.com/sdk/installing/index.html), [NDK] (http://developer.android.com/ndk/downloads/index.html), and [Ant] (https://code.google.com/p/winant/).  The last is a Windows link, if you're not on Windows, just install it using your favorite package manager.

Armed with those things (or maybe you already had them), next steps are:

For Windows:
1. Go into the Android directory.
2. Edit ab.cmd and change `SET NDK=C:\AndroidNDK` to whatever your NDK path is.  Or just install it to that path.
3. Delete custom_rules.xml.
4. Run `ab.cmd`.
5. Make sure it doesn't say any errors at the end.  It should finish with "Install" lines.

On Linux/Mac:
1. Go into the Android directory.
2. Run `export NDK=/path/to/ndk`.

And finally, on any platform, after the above:
1. Run `ant debug`.
2. It should look like it succeeded without anything that says "error".
3. Run `adb shell am force-stop org.ppsspp.ppsspp`.
4. Run `adb install -r bin/PPSSPP-debug.apk`.

You've now installed the newly compiled version on your phone (assuming nothing failed above.)

If the problem is gone, it probably means GL_PACK_ROW_LENGTH helped.  If the problem is still there, logcat might give better error messages.  You can plug your phone in and type `adb logcat` (comes with the SDK or NDK.)

-[Unknown]

**Comment by sewer56lol** [comment]
Is there any way I could pull everything at once on the Git repo without installing the git shell? Windows 10 being what it is breaks far more easily than running Arch w/ base-devel as a daily driver - downloading everything linked to other repos like armips after figuring out what was missing every time the compile failed was tedious to say the least.

Downloading zip of master doesn't pull any other repos it links to along.

(Note - am learning programming as a student but never properly used git).

**Comment by hrydgard** [comment]
@unknownbrackets thanks!

Nice find and nasty driver bug, seems you guys are on the right track - that the savedata icon is broken really strongly points to specifically glReadPixels being off in its stride handling, as mentioned above...

**Comment by sewer56lol** [comment]
I'm clueless as how I use Apache Ant in order to compile the Android version of PPSSPP, running Ant with sdk.dir and ndk.dir set in project properties gives: http://pastebin.com/Y6BD8be8

And without it tells me that it is failing due to sdk.dir / ndk.dir missing.

I've spent over an hour trying to get over the hurdle of getting it to compile but I am not getting there :/.

I've used ant -debug -f ppsspp-master\android\

**Comment by unknownbrackets** [comment]
Ah, sorry.  Maybe I already have ANDROID_HOME set.  In my case:
ANDROID_HOME=C:\ProgramData\NVPACK\android-sdk-windows

So that would be the SDK dir.  On Windows, just run:

```sh
set ANDROID_HOME=path
```

Also, I personally just use git from cmd (not bash or powershell or anything.)  Does fine.  Still on Windows 7, though.  I would be surprised if it didn't work on Windows 10, though.  If so that's a sure shame.

> Setting project property: ndk.dir -> C:AndroidNDK
> Setting project property: sdk.dir -> C:Userssewer56lolAppDataLocalAndroidandroid-sdk

Ah, for Ant, make sure to use `/` not `\`.  It might get confused with `\`s.  But I think I use [this version of Ant for windows] (https://code.google.com/p/winant/), it's not the newest version but I think it handles paths right.  Otherwise you might need to run from within a bash shell.

-[Unknown]

**Comment by sewer56lol** [comment]
My stupidness of being unable to compile was indeed of the wrong direction of the slashes, changing those to frontslashes worked and I tested it with unaltered clone of master resulting in a successful compile.

When making the changes ab.cmd/ab.sh will break leaving me 

```jni/../../GPU/GLES/Framebuffer.cpp:1713:40: error: 'LogReadPixelsError' was not declared in this scope
         LogReadPixelsError(glGetError());```

where the changes were made.

I'll see what happens of compiling without the line makes - so at least I can assess the other changes present.

**Comment by sewer56lol** [comment]
@unknownbrackets @hrydgard 
So I have compiled the apk with the changes given - though had to remove the LogReadPixelsError(glGetError()); methods as they were spitting errors out for me - needless to say the results are that the effect in game is now displayed correctly on Snapdragon 810/Adreno 430.

Screenshots post build:

**Comment by unknownbrackets** [comment]
Grr, this is why commented out code is bad.  Anyway, find this:

```c++
#ifndef USING_GLES2

// TODO: Make more generic.
static void LogReadPixelsError(GLenum error) {
```

And change it to:

```c++
// TODO: Make more generic.
static void LogReadPixelsError(GLenum error) {
```

Then below that, find:

```c++
void FramebufferManager::PackFramebufferAsync_(VirtualFramebuffer *vfb) {
```

And change to:

```c++
#ifndef USING_GLES2

void FramebufferManager::PackFramebufferAsync_(VirtualFramebuffer *vfb) {
```

That should make it compile with the lines.  Also, I'm not seeing your screenshots.

-[Unknown]

**Comment by unknownbrackets** [comment]
Actually, you'll want to delete these lines as well, sorry:

```c++
	case GL_STACK_UNDERFLOW:
		ERROR_LOG(SCEGE, "glReadPixels: GL_STACK_UNDERFLOW");
		break;
	case GL_STACK_OVERFLOW:
		ERROR_LOG(SCEGE, "glReadPixels: GL_STACK_OVERFLOW");
		break;
```

-[Unknown]

**Comment by unknownbrackets** [comment]
Anyway, it's apparent that fixed it.  I think we can just add the PACK_ROW_LENGTH line in.

-[Unknown]

**Comment by sewer56lol** [comment]
Do you still want a logcat with the extra logging methods added then?

**Comment by unknownbrackets** [comment]
Nah, doesn't seem necessary.  Although, silly driver for allowing some other row length value to leak in... unless I'm mistaken and the default is not required to be 0.

-[Unknown]
