### ISSUE TITLE
Sol Trigger loading for a long time after bgm looping

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8261]
may happen in saving point,gong into another area or in the conversation.

like this one last 52 seconds 
```
51:43:417 sound at3 th I[KERNEL]: HLE\sceKernelThread.cpp:2066 sceKernelExitThread(0)
52:35:945 main         I[KERNEL]: HLE\sceKernelThread.cpp:1943 425=sceKernelCreateThread(sound at3 thread, 08931270, 00000010, 10240, 00004000, 00000000)
52:35:945 main         I[KERNEL]: HLE\sceKernelThread.cpp:2014 0=sceKernelStartThread(425, 4, 08a8c6d0
```

**Comment by daniel229** [comment]
It happens after BGM looping and can be reproduced in demo.
A savestate for reproduce the  bug in demo,walk to next area.
https://drive.google.com/file/d/0BzGZGDfFE68zTUNFdm9NRGY5UFE/view?usp=sharing

**Comment by daniel229** [comment]
Looks like it's waiting for the bgm to be finished.
Since https://github.com/unknownbrackets/ppsspp/commit/959887d407775990903c4ea48647f3d90ca5d261 in https://github.com/hrydgard/ppsspp/pull/8189

**Comment by unknownbrackets** [comment]
So it turns out, once all data is available for a stream that isn't going to loop, it seems like remaining frames becomes -2 (currently it does become -1 for halfway, but not for streaming... I thought my tests implied this wasn't correct, so I need to test more.)  Maybe it's waiting for the value to change like that.

That or it could be stream data info, in which case this could be fixed.  Have not tested it yet.

-[Unknown]

**Comment by daniel229** [comment]
Gran Turismo freezing also caused by the same commint.
Here is the Atrac log (rename jpg to 7z)
![ppsspplog](https://cloud.githubusercontent.com/assets/3481559/12190018/93419ce8-b5fe-11e5-836b-75819a7a409f.jpg)

**Comment by unknownbrackets** [comment]
This no longer seems to reproduce without that savestate.

What happened in that savestate is that it looped, and the remaining frame value became very large.  This is because the "virtual" buffer had a ton of frames remaining in it, far more than the real buffer ever could.

The game waited patiently until the value became sane before continuing to the next area.  #8435 should prevent the value from becoming too high, but still allowed it to become negative and too low.  That didn't seem to cause issues (somehow), but #8442 fixes that.

Are you still able to reproduce?

-[Unknown]

**Comment by daniel229** [comment]
Looks like has been fixed for Sol Trigger.
But for Gran Turismo it's silence at the point that froze before.

log for Gran Turismo
https://gist.github.com/daniel229/d5c170b0799ac8554295

**Comment by unknownbrackets** [comment]
What does the log from when it worked look like?

Relevant parts, I think:
```
58:39:982 PDI:00000017 N[ME]: HLE\sceAtrac.cpp:1542 0=sceAtracGetRemainFrame(1, 09efb040[00000056])
58:39:982 PDI:00000017 N[ME]: HLE\sceAtrac.cpp:1619 0=sceAtracGetStreamDataInfo(1, 09efb030[08ea9ed0], 09efb034[0000f9f0], 09efb038[003af770])
58:39:989 PDI:00000017 I[ME]: HLE\sceAtrac.cpp:1627 0=sceAtracReleaseAtracID(1)
```

I have an idea.  What if you find:

```c++
		// If you don't think this should be here, remove it.  It's just a temporary safety check.
		if (first_.offset + first_.writableBytes > bufferMaxSize_) {
```

And replace with:

```c++
		u32 bytesLeft = first_.filesize - first_.fileoffset;
		if (first_.writableBytes > bytesLeft) {
			first_.writableBytes = bytesLeft;
		}

		// If you don't think this should be here, remove it.  It's just a temporary safety check.
		if (first_.offset + first_.writableBytes > bufferMaxSize_) {
```

I need to test to validate, but this could be... it makes sense.

-[Unknown]

**Comment by daniel229** [comment]
It works fine with that change.

**Comment by daniel229** [comment]
Fixed by https://github.com/hrydgard/ppsspp/pull/8458
