### ISSUE TITLE
MH3 HD, short freezes/lock-ups while playing online with a friend/friends.

### ISSUE THREAD

**Issue by Detnom** [hrydgard/ppsspp#8267]
I've scoured the internet trying to find the reason for my problem, but I've basically exhausted all my resources, so here I am, hoping someone can help. Using the newest version of PPSSPP, Tunngle, and the built in AdHoc server. If it makes a difference, I'm the one who hosts our server.

Everything is fine when I'm playing solo, or in an online game/guild hall alone, but after a friend joins, intermittent freezes will start. The emulator locks up for 5-10 seconds or more, then works fine for a few minutes, only to continue repeating this pattern. Makes playing more than a little frustrating.

This morning I tried downloading an older version of the emulator (v0.9.8-1394-g384d8e3) as I'd read somewhere newer versions were causing some freezing, and while the freezes seemed to be a little shorter, they still occurred, so that didn't help either. Not to mention my buddy who was helping me test started seeing two of himself in the Guild Hall, perhaps I downloaded a version of the AdHocServer that's too old and buggy? Not really the reason I'm posting, but I digress. Thanks a ton for reading and any advice I may get in advance. Love PPSSPP, and wish I could play with my friends without locking up during battles and stuff, haha.

**Comment by thongthai2810** [comment]
Thi

**Comment by Detnom** [comment]
Pardon?

**Comment by unknownbrackets** [comment]
Does this still happen in the latest git builds?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
