### ISSUE TITLE
Incorrect Resolution Display on These Games

### ISSUE THREAD

**Issue by SwinglesMan** [hrydgard/ppsspp#8310]
The Display of the resolution isn't correct on the following games. No matter what you set the game rez to, it'll always be the same psp internal game rez displayed.

Final Fantasy I
Final Fantasy II
Final Fantasy IV
Street Fighter Alpha 3 Max

If I play the PPSSPP emulator with desktop rez at 4K (no matter the internal resolution), these games are also very very slow. If I play them with my desktop rez at 1080p, they play fine. Wondering if it was related to the improper display or if you guys locked it to that rez on purpose to prevent something bad from happening. But then what about the bad performance at 4K?

**Comment by unknownbrackets** [comment]
I'm not sure what graphics card you have.  If it's older, 4K may just be beyond its capabilities or something.  Just to be clear, 1080p is 1920x1080.  4K usually refers to 3840x2160 (very misleading imho.)  Nevertheless, this is 4x as much work for your GPU.

To put it another way, if 1080p uses up 33% of your GPUs potential, then it's simply not capable of 4K.  Your GPU needs to be able to juggle 1080p behind its back while blindfolded to be able to handle 4K decently.  So it's not impossible that 4K might be just a little too much for it.

I'm not sure what settings you're using.  Here's a graphic illustrating the differences:

![ff4-res](https://cloud.githubusercontent.com/assets/191233/12008739/52d939b0-ac06-11e5-9f4b-a3f2345411b7.gif)

Remember that 2x won't magically make textures more detailed.  As you can see here, in FF4, texture scaling makes the green background "bleed into" the textures.  This particular game just was not originally designed to ever be at a higher resolution.  But that doesn't mean the settings aren't working.

The best "saving grace" for this particular game would be if someone put time and effort into it, and created custom, cleaned up HD textures for it.  We'd also have to implement texture replacement.  Neither of these things have happened, though, atm.

-[Unknown]

**Comment by SwinglesMan** [comment]
980m
i7-4960x
I play all my games in 4096x2304 with max settings just fine except 3 in which I have to not use their particular AA with. I don't think you touched what I am saying.

Turn on your resolution display by turning on fps. No matter what resolution I put the game rez in (1xpsp, 2xpsp, 3xpsp, etc., it always reads as 480x272 in the on screen display on those games stated only. That is what I'm talking about.

**Comment by unknownbrackets** [comment]
Emulators can sometimes be more demanding than PC games, so your comparison may not be apples-to-apples.  Nevertheless, I would expect a 980M to probably be able to handle 1x internal resolution on a 4K display at full screen fine.  But then if you're using a post-rendering shader it might be super duper slow.

Not really sure though since I don't have (or want) a 4K monitor, personally.  But I'm not aware of anything in PPSSPP that would reacts specially to 4K but not 1080p.  Just again, know that it is 4x as much work.  And a post-shader that runs at output resolution might be severely impacted by that.

The on-screen display of resolution shows fine for me when I switch resolutions.  Make sure you're using the latest git build, although I don't think there's been a bug in that.

I recommend you go to the forum and find out if any other people are experiencing lag playing games at 4K resolution.  I'm pretty sure other people have talked about using 4K and have not reported unusual performance.  But maybe no one has noticed and they're all experiencing it.

-[Unknown]

**Comment by SwinglesMan** [comment]
I went to newest build. Ok, the lag was an external shader's fault. But still, the resolution won't change from 480x272. You don't need 4K screen to do 4K. Nvidia DSR.

**Comment by unknownbrackets** [comment]
BloomHack = 1 (Lower resolution for effects) could cause some framebuffers to stick to 1x.
InternalResolution = 1 is actually 1x.

-[Unknown]

**Comment by SwinglesMan** [comment]
The lower resolution for effects is greyed out for all those 2d games I listed but not for any of the 3D games. I am unable to toggle the option.for the 2D games.

**Comment by unknownbrackets** [comment]
PostShader = UpscaleSpline36 is an upscaling filter so it forces internal resolution at 1x.  That's the definition of an upscaler.

-[Unknown]

**Comment by SwinglesMan** [comment]
ok, cool. that was it. didnt know a shader could influence an option like that. Thanks.
