### ISSUE TITLE
Final Fantasy Tactics Lines Above Native Game Rez

### ISSUE THREAD

**Issue by SwinglesMan** [hrydgard/ppsspp#8311]
In final fantasy tactics, anything about 1xpsp makes map lines or either enemy lines. If there is anything that can be done to fix that, feel free to explain. Also, playing the game with the desktop rez of 4K makes this game lag really bad even if on 1xpsp.

**Comment by unknownbrackets** [comment]
lease see this description of what happens when you render at higher resolutions:

http://forums.ppsspp.org/showthread.php?tid=13556&pid=96345#pid96345

I go into some detail.  If you're interested in how computer graphics work, this is probably a good read (I hope, unless I made some careless mistake in my explanation.)

If it lags at 4K display resolution, it sounds like your graphics card is just not capable of it.  I'm going to close this, but feel free to reply if you have more questions.

-[Unknown]

**Comment by SwinglesMan** [comment]
My graphics card is a 980m with a i7-4960x processor. I can play every pc game in 4096x2304 on max settings just fine.

**Comment by unknownbrackets** [comment]
Well, that ought to be sufficient.  In any case there's no reason to have two issues about the same problem you're having.

-[Unknown]
