### ISSUE TITLE
x86-64 JIT on Mobile can be improvement similarly Desktop

### ISSUE THREAD

**Issue by zminhquanz** [hrydgard/ppsspp#8325]
In the future , can you improve this ?

**Comment by hrydgard** [comment]
Yeah, we don't currently do an x86-64 build because nearly no devices currently support that - they may use 64-bit x86 CPUs, but the Android OS is 32-bit. 

Do you have one that runs a 64-bit OS, if so which one?

**Comment by zminhquanz** [comment]
but Android Lollipop on Zenfone 2 it's support 64 bit

**Comment by unknownbrackets** [comment]
It doesn't help if no one is shipping devices actually using it, or if there aren't video card drivers, etc.  Plus, it ultimately needs to be verified working on a device.

-[Unknown]

**Comment by zminhquanz** [comment]
and how do you think to improve x86 JIT on Mobile ( 32 bit on Intel ) ?

**Comment by unknownbrackets** [comment]
It's the same jit we use on x86 32-bit desktop.  We've already done a lot to optimize it.

Most likely if you are playing games and they are not full speed, your problem is not how fast the jit is.  More likely the bottleneck is the OpenGL driver, or your GPU itself.

This can be verified pretty easily: press fast forward.  When you fast forward (with default settings), it automatically skips rendering frames.  But it does not ever skip any jit.

If the bottleneck, the thing making the game slow, is the jit - then you will not get any faster.  Fast forward will not work.  It will simply stay the same speed, even though it's skipping rendering some frames.

That doesn't mean a faster jit won't help, but the faster the game can get with fast forward, the less a faster jit can help.  Because fast forward already shows you how fast the CPU emulation is.

Our current hope: Vulkan.  This will probably only be supported on more modern Android devices, but hopefully that will include x86 devices.  There's good reason to hope (can't be sure yet) that Vulkan will allow us to improve the performance, based on what is often the bottleneck right now: the OpenGL driver.

-[Unknown]

**Comment by maximu** [comment]
I'm starting work binary x86-64 version based on GCC 4.9 support for x86_x64-android.
- Load Ok library and detected cpu/extensions Ok.
- ffmpeg Ok 
- no detected crashes 

This Tested under Ivy bridge i7 with Intel hd 4000 supported Opengl es 3.0 under Remix OS or Android x86-x64 images . 

![screenshot_2016-01-17-17-32-00](https://cloud.githubusercontent.com/assets/1274014/12378836/ba0dd562-bd42-11e5-8cc0-aa5370834b67.png)

![screenshot_2016-01-17-17-31-43](https://cloud.githubusercontent.com/assets/1274014/12378864/7b754488-bd43-11e5-89e8-0c900850529a.png)

![screenshot_2016-01-17-18-01-29](https://cloud.githubusercontent.com/assets/1274014/12378903/a9c04684-bd44-11e5-9e42-9cdc27a6a728.png)

![screenshot_2016-01-17-18-02-38](https://cloud.githubusercontent.com/assets/1274014/12378908/c33ba0ea-bd44-11e5-8870-af210e178323.png)

I Upload apk if working for you @zminhquanz   http://s000.tinyupload.com/index.php?file_id=78412168732326930659

**Comment by unknownbrackets** [comment]
Nice, did it require any code changes?  I was a bit worried we might have some place where we assume ANDROID and _M_IX64 are exclusive of each other, but don't know of any such place.

-[Unknown]

**Comment by maximu** [comment]
In the Android.mk reuse te same estructure .for x86 but with flags -D_ARCH_64 -D_M_X64 in local.mk

>ifeq ($(TARGET_ARCH_ABI),x86_64)
ARCH_FILES := \
$(SRC)/Common/ABI.cpp \
$(SRC)/Common/x64Emitter.cpp \
$(SRC)/Common/CPUDetect.cpp \
$(SRC)/Common/Thunk.cpp \
$(SRC)/Core/MIPS/x86/CompALU.cpp \
$(SRC)/Core/MIPS/x86/CompBranch.cpp \
$(SRC)/Core/MIPS/x86/CompFPU.cpp \
$(SRC)/Core/MIPS/x86/CompLoadStore.cpp \
$(SRC)/Core/MIPS/x86/CompVFPU.cpp \
$(SRC)/Core/MIPS/x86/CompReplace.cpp \
$(SRC)/Core/MIPS/x86/Asm.cpp \
$(SRC)/Core/MIPS/x86/Jit.cpp \
$(SRC)/Core/MIPS/x86/JitSafeMem.cpp \
$(SRC)/Core/MIPS/x86/RegCache.cpp \
$(SRC)/Core/MIPS/x86/RegCacheFPU.cpp \
$(SRC)/GPU/Common/VertexDecoderX86.cpp
endif

local.mk
>ifeq ($(TARGET_ARCH_ABI),x86_64)
  LOCAL_LDLIBS += $(LOCAL_PATH)/../../ffmpeg/android/x86_64/lib/libavformat.a
  LOCAL_LDLIBS += $(LOCAL_PATH)/../../ffmpeg/android/x86_64/lib/libavcodec.a
  LOCAL_LDLIBS += $(LOCAL_PATH)/../../ffmpeg/android/x86_64/lib/libswresample.a
  LOCAL_LDLIBS += $(LOCAL_PATH)/../../ffmpeg/android/x86_64/lib/libswscale.a
  LOCAL_LDLIBS += $(LOCAL_PATH)/../../ffmpeg/android/x86_64/lib/libavutil.a
  LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../ffmpeg/android/x86_64/include
  LOCAL_CFLAGS := $(LOCAL_CFLAGS)  -D_ARCH_64 -D_M_X64 -fomit-frame-pointer -mtune=atom -mfpmath=sse -mssse3 -mstackrealign
endif 

Script for ffmpeg only change to lib64 and compiler for gcc x86_64 and compile ok 

I had to change in ext/native/gfx/gl_common.h line 58 need change GLint mask to GLbitfield mask.

**Comment by hrydgard** [comment]
Cool, I'm surprised it was that painless.

**Comment by unknownbrackets** [comment]
Okay, I think #8455 has fixed this.  Closing.  If there are issues with it we can open them separately.

-[Unknown]
