### ISSUE TITLE
Disgaea Wlan Disbaled problem

### ISSUE THREAD

**Issue by latot** [hrydgard/ppsspp#8333]
Hi again, well here a little problem, when we try to play on wlan with disgaea but with wlan disabled from settings the game its in loop:

```
27:19:328 user_main    I[NET]: HLE/sceNetAdhoc.cpp:1385 sceNetAdhocctlConnect(groupName=TEST0LB) at 088ad5d8
27:19:328 user_main    I[NET]: HLE/sceNetAdhoc.cpp:1310 sceNetAdhocctlCreate(TEST0LB) at 088ad5d8
```

This two lines re repeated until forever.

complete log:
https://gist.github.com/latot/689562e2539503c3a0c1
the log ends when i force close the game.

Cya.

**Comment by unknownbrackets** [comment]
Most likely those syscalls or else another syscall that isn't logged should be returning an error to indicate that wlan is off, but they aren't, or are returning the wrong error.

-[Unknown]

**Comment by Hydroque** [comment]
Was this fixed in a future issue?

**Comment by unknownbrackets** [comment]
Might be.  Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
