### ISSUE TITLE
Cannot save the language setting

### ISSUE THREAD

**Issue by cheneydc** [hrydgard/ppsspp#8345]
Set the language to other, like Chinese:
Click Options -> language -> "简体中文"
Quit ppsspp and restart it, the language still the default, not Chinese

**Comment by daniel229** [comment]
Which version are you using,unicode path has a fix recently,If you are on windows try updated build from http://buildbot.orphis.net/ppsspp/index.php

**Comment by unknownbrackets** [comment]
I'm going to close this as fixed, based on that, since I thin that's likely the issue.

If you're experiencing this in the latest git build, please feel free to comment.  We'll reopen if this is still an issue.  Include whether the path you're using for PPSSPP includes non-Latin characters too, if possible.

-[Unknown]

**Comment by cheneydc** [comment]
@daniel229 @unknownbrackets I install ppsspp from apt-get on ubuntu, use the http://ppa.launchpad.net/ppsspp/stable/ubuntu source url, the version is 1.1.1

**Comment by daniel229** [comment]
It'd better try the latest build from http://build.ppsspp.org/?page/downloads
