### ISSUE TITLE
Texture cache error ?

### ISSUE THREAD

**Issue by vnctdj** [hrydgard/ppsspp#8364]
Since https://github.com/hrydgard/ppsspp/commit/37cfea0fdc27218b7c37e8684d9e0bb65d2c2f7c, with some postprocessing shaders enabled (e.g. FXAA, Natural colors, ...), when resizing the screen, the following line is produced in the log :

```
18:48:972 user_main    W[G3D]: GLES\TextureCache.cpp:1865 Got an error in texture upload: 00000502
```
I thought it might be important to notice :)

**Comment by unknownbrackets** [comment]
This may not *specifically* be related to the texture cache.  But when we upload textures, we check if any error has occurred since the last time we uploaded a texture, and we now log it.

What this means is that resizing is causing some OpenGL error.

Checking errors is a bit expensive, so we don't normally do it unless there's a good reason.  In the case of the texture cache, we're checking to make sure the texture uploaded - because it's not that uncommon for people to run out of memory, especially with texture scaling on.

-[Unknown]

**Comment by vnctdj** [comment]
Oh, thanks for the explanation and the quick fix !
