### ISSUE TITLE
Eien no Aseria - Kono Daichi no Hate de sound effect broken

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8401]
Since https://github.com/unknownbrackets/ppsspp/commit/1b6dbd45e767d3a36326a1fbda510ed259f33a39 in https://github.com/hrydgard/ppsspp/pull/8356

Atrac log v1.1.1-570-g959015f
https://gist.github.com/daniel229/c212b1a379b6ed5aacce

v1.1.1-644-g94c91e1
https://gist.github.com/daniel229/efacc87069e8ffe39094

**Comment by unknownbrackets** [comment]
This is streaming.  Does it help to change:

```c++
			if (atrac->bufferState == ATRAC_STATUS_STREAMED_WITHOUT_LOOP) {
				readOffset = 0;
			} else {
```

To:

```c++
			if (atrac->bufferState == ATRAC_STATUS_STREAMED_WITHOUT_LOOP || atrac->first.writableBytes == 0) {
				readOffset = 0;
			} else {
```

Although, this is still incorrect, it might be "better".  This is pretty certainly triggered by the "resetBuffer" hack, that I'm hoping to remove.

-[Unknown]

**Comment by daniel229** [comment]
Doesn't.

**Comment by unknownbrackets** [comment]
Just to pull it out, here's what's happening.

Before:
```
27:27:259 ADX_STM_BGM  N[ME]: HLE\sceAtrac.cpp:1490 sceAtracGetStreamDataInfo(2, 09f99c48[089e8680], 09f99c4c[00000000], 09f99c50[001030f4])
27:27:259 ADX_STM_BGM  I[KERNEL]: HLE\sceKernelThread.cpp:2014 0=sceKernelStartThread(303, 4, 09f99c14)
27:27:259 THFSAsyncRea I[KERNEL]: HLE\sceKernelThread.cpp:2066 sceKernelExitThread(0)
27:27:259 ADX_STM_BGM  N[ME]: HLE\sceAtrac.cpp:970 0=sceAtracAddStreamData(2, 00000000)
```

After:
```
25:19:160 ADX_STM_BGM  N[ME]: HLE\sceAtrac.cpp:1554 0=sceAtracGetStreamDataInfo(2, 09f99c48[089e8680], 09f99c4c[00000000], 09f99c50[00000094])
25:19:160 ADX_STM_BGM  I[KERNEL]: HLE\sceKernelThread.cpp:2014 0=sceKernelStartThread(303, 4, 09f99c14)
25:19:161 THFSAsyncRea I[KERNEL]: HLE\sceKernelThread.cpp:2066 sceKernelExitThread(0)
25:19:161 ADX_STM_BGM  W[ME]: HLE\sceAtrac.cpp:1029 80630018=sceAtracAddStreamData(2, 00103060): too many bytes
```

Specifically, the streamdatainfo values are only mildly different.  Before, the readOffset is 0x001030f4 (clearly the end of file), and after the change it is (00000094) for looping.

What's really incorrect here is the writableBytes.  Since it's looping, it really should be asking for more bytes.  Clearly the game is confused by `0` and treats it as `0x001030f4 - `00000094` or `00103060`.  At the end of file, this bug in the game works, but here it doesn't.

What will likely help, but might be more dangerous (and also still not accurate), is:

```c++
		if (readOffset >= atrac->first.filesize) {
			if (atrac->bufferState == ATRAC_STATUS_STREAMED_WITHOUT_LOOP) {
				readOffset = 0;
			} else {
				readOffset = atrac->dataOff;
				atrac->first.writableBytes = (atrac->bufferMaxSize / atrac->atracBytesPerFrame) * atrac->atracBytesPerFrame;
			}
		}
```

-[Unknown]

**Comment by daniel229** [comment]
Yes,the sound works again with that code.
