### ISSUE TITLE
Mali-400 MP4?

### ISSUE THREAD

**Issue by blackman91** [hrydgard/ppsspp#8402]
Any optimizations planned for this gpu? Most games I run with the latest devs run slower and need a lot of frameskipping.

My cpu is 1.9 ghz

**Comment by unknownbrackets** [comment]
Since the GPU does not support GLES 3, it won't support Vulkan.  Vulkan is a new graphics API that may allow us to avoid inefficiencies common in mobile video card drivers.

We may be able to find ways to optimize things, but I would not anticipate going from "a lot of frameskipping" to "no frameskipping."  In fact, an Android OS update that also updates the video card driver may be your best bet at a performance increase.

Anyway, this is not an issue.  Discussion like this is best for the forum.

-[Unknown]
