### ISSUE TITLE
Sora no kiseki SC / HD light problem

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8403]
HD version capture from https://youtu.be/n94plorFBXE?t=14m40s
![schd1](https://cloud.githubusercontent.com/assets/3481559/12186811/2db3233c-b5e1-11e5-9d10-a31207f9f098.png)

PPSSPP OpenGL just black behind the box 
![schd2](https://cloud.githubusercontent.com/assets/3481559/12186825/52fb5eca-b5e1-11e5-80c6-3a22e33a9828.png)

PPSSPP software redering looks fine.
![schd3](https://cloud.githubusercontent.com/assets/3481559/12186838/608411a4-b5e1-11e5-8a02-a6caf1800f98.png)

Non-HD version 
PSP Looks darker
![psp1](https://cloud.githubusercontent.com/assets/3481559/12186854/7a5c749a-b5e1-11e5-8c8a-31b039e7856c.png)

PPSSPP OpenGL less darkness
![psp2](https://cloud.githubusercontent.com/assets/3481559/12186861/88878532-b5e1-11e5-8ba3-d5662a73da1f.png)

software rendering looks like the HD version
![psp3](https://cloud.githubusercontent.com/assets/3481559/12186882/c27f95b8-b5e1-11e5-81df-946c5809c756.png)

**Comment by daniel229** [comment]
GE debugger ,don't know if this one,next prim still not draw the boxes.

HD version
![hd](https://cloud.githubusercontent.com/assets/3481559/12187181/95d2a3a4-b5e4-11e5-99e8-586df0cf85fe.png)
https://gist.github.com/daniel229/c24d3f143c47bb08c055


Non-HD
![non-hd](https://cloud.githubusercontent.com/assets/3481559/12187123/f619c720-b5e3-11e5-9e36-fd1a6ff25ce7.png)
https://gist.github.com/daniel229/26d2c8c8bcdbe13503c5

**Comment by unknownbrackets** [comment]
I think that's the right place.  If you go there, and then double click one of the lights (like light 3), does it look any closer to the PSP?

I wonder if this could be influenced at all by the normals.  Maybe it's just a precision thing.

-[Unknown]

**Comment by daniel229** [comment]
Yes,double click lights3,it looks closer to the PSP.

**Comment by unknownbrackets** [comment]
Here's a dump (just hurried to the same place, since it's early): [NPUH10191_#8403_trails_lighting.zip](https://github.com/hrydgard/ppsspp/files/2593802/NPUH10191_.8403_trails_lighting.zip)

Should look like this per a PSP (as noted above, just showing this dump's frame):
![npuh10191_ 8403_trails_lighting](https://user-images.githubusercontent.com/191233/48686622-bb3d7900-eb71-11e8-82fd-2fa018e910e8.png)

Though, of course, it looks much better the way PPSSPP displays it.  I'd ideally prefer it looked like the HD version.

Draw uses texture 0x04100000, and point light as above.  It also uses color doubling.

To make software renderer use the PSP behavior (correct?) I can make this change:

```diff
-		if (gstate.isUsingSpecularLight(light)) {
+		if (gstate.isUsingSpecularLight(light) && diffuse_factor > 0.f) {
```

That is, ignore specular if diffuse factor was <= 0.

To make the Vulkan/backend renderer use the HD/software behavior (better looking - I think the PC version looks this way too):

```diff

				WRITE(p, "  dot%i = dot(normalize(toLight + vec3(0.0, 0.0, 1.0)), worldnormal);\n", i);
+				WRITE(p, "  if (dot%i <= 0.0 && light.matspecular.a == 0.0) {\n", i);
+				WRITE(p, "    dot%i = 1.0;\n", i, i);
+				WRITE(p, "  } else {\n");
+				WRITE(p, "    dot%i = pow(dot%i, light.matspecular.a);\n", i, i);
+				WRITE(p, "  }\n");
+				WRITE(p, "  if (dot%i > 0.0)\n", i);
+				WRITE(p, "    lightSum1 += light.specular[%i] * %s * (dot%i %s);\n", i, specularStr, i, timesLightScale);
-				WRITE(p, "    lightSum1 += light.specular[%i] * %s * (pow(dot%i, light.matspecular.a) %s);\n", i, specularStr, i, timesLightScale);
```

Note the logic - similar to #2424.  Importantly, this includes `<= 0.0` not just `== 0.0`, which might be interesting to try in the powered diffuse case (not sure...)

Anyway, I wonder if this difference affects lighting in other cases, such as other lighting bugs we're aware of...

-[Unknown]

**Comment by hrydgard** [comment]
I think if we do this, the  ```if (gstate.isUsingSpecularLight(light) && diffuse_factor > 0.f) {``` should check the diffuse factor before it gets changed by the powered diffuse - that is, just use the dot product directly. It seems very plausible that the PSP would use that check to skip the specular processing if possible.
