### ISSUE TITLE
PS3 Controller Trigger Sensitivity Problem

### ISSUE THREAD

**Issue by GamerzHell9137** [hrydgard/ppsspp#8414]
Not sure when it got changed but the triggers on PS3 controller must be fully pressed for PPSSPP to see them being used. Its a lot annoying.

**Comment by GamerzHell9137** [comment]
Checked if something was wrong with my controller but x360ce and PC games say that the triggers work fine only PPSSPP asks for full presses to make the buttons work which means something's wrong with the sensitivity.

**Comment by GamerzHell9137** [comment]
https://youtu.be/a5PuNUwzKkw

**Comment by LeonBlade** [comment]
I have had problems with controllers myself, but I run on OS X and not Windows.  I haven't had this exact problem though, is this still an issue for you?

It seems that the problem here is with how the L2 and R2 buttons are interpreted in the bindings.  Likely the half axis(?) bindings are not actually what's triggering in PPSSPP, but instead the full press.

I would try to see if you can rebind the L2 and R2 buttons, if this is still a problem I will try to reproduce it on my end and see if I can create a fix for it.

**Comment by GamerzHell9137** [comment]
@LeonBlade What am i supposed to do? Just rebind the buttons? If so then nothing's happening, the R2 L2 thing is the same.

**Comment by LeonBlade** [comment]
@GamerzHell9137 Yeah, that's what I was asking, I'll have a look later tonight and see if I can fix the problem for you.  What sort of setup do you have for using your DS3 so I can recreate your environment?  Drivers, third party programs, etc.

**Comment by GamerzHell9137** [comment]
@LeonBlade DS3 controller with the SCP Server
Here's from where i got the tools http://forums.pcsx2.net/Thread-XInput-Wrapper-for-DS3-and-Play-com-USB-Dual-DS2-Controller
And i'm using imy controller wired.

**Comment by unknownbrackets** [comment]
Is this still happening?  Do you know if the controller is exposed as XInput or DirectInput?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]

**Comment by SixelAlexiS90** [comment]
@unknownbrackets Hi! This is still a thing on 1.16.6.
I'm using an Xbox One controller and the triggers get activated almost all through.
Here a screen of the right trigger not pressed (Z Axis):

![PPSSPP trigger not pressed](https://github.com/hrydgard/ppsspp/assets/63536218/6a88f0f4-fcb0-4a41-9333-99666c68824d)

Here a screen of when the right trigger is actually read (I've mapped it to "look back"):

![PPSSPP trigger pressed](https://github.com/hrydgard/ppsspp/assets/63536218/f19fbb76-b500-4879-9cbc-884e6bf99683)

As you can see you have to press it almost all through to activate it, specifically at 75% of pressure.
There really should be 0% to 100% slider in the emulator settings to manually set the trigger sensitivity like it happen already in other emulators.
