### ISSUE TITLE
MotoGP graphical artifact

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8424]
Since https://github.com/hrydgard/ppsspp/pull/8376

![03](https://cloud.githubusercontent.com/assets/3481559/12286989/04461c76-ba04-11e5-8e40-6b24cc08e052.png)

before
![04](https://cloud.githubusercontent.com/assets/3481559/12286990/044cbe32-ba04-11e5-9fc8-115d03960515.png)

**Comment by daniel229** [comment]
PixelDepthRounding fixes it。

**Comment by unknownbrackets** [comment]
Hmm.  Does it flicker at all or is it constant?

The latest change to clamping didn't help, right?

-[Unknown]

**Comment by daniel229** [comment]
It's changing when you are moving.latest change did not help.
Video (rename jpg to mp4)
![ppssppwindows64v1 1 1-682-g067095e 2016-01-17 12-56-39-441](https://cloud.githubusercontent.com/assets/3481559/12376022/ef13cf4c-bd19-11e5-98a1-599355453553.jpg)

**Comment by unknownbrackets** [comment]
Ew, that looks annoying.

Was able to reproduce in the demo.  I wonder why there's a white box it's texturing areas from at 0x04131600.  Seems suspicious.

Anyhow, the depth values in that general area of the road are pretty low - ~500-1000.  There are many draws, some are higher, but most have depth values that are even lower.  The trick is: depth testing is **not even enabled** when it draws the wrong thing.  Go figure?

I guess it must be clipping.  The scale is -32768, and the center is 32767.  Meaning, it's adjusting to get a range of [-1, 65535] instead of [0,65535].

In this case, the adjustment should be fairly tiny:
```
z' = (z * 1.00001525902) - 0.00001525902
z' => [-1.00003051804, 1.0]
```

A precision issue?  This should be exactly representable as 0.00001525902, but 1.00001525902 will be a bit off.

-[Unknown]

**Comment by unknownbrackets** [comment]
Just to confirm, disabling just `if (near < 0.0f || far > 1.0f) {` makes this problem seemingly go away.

There are a few other values logged if I log in there, but this is one when drawing the road and the artifact:

zScale=1.000015, zOffset=-0.000015 adjusted near=0.000000, far=1.000000

-[Unknown]

**Comment by unknownbrackets** [comment]
If I force zOffset to 0, or force zScale to 1, the issue also does not occur.

`zScale = 1.000025f;` causes the issue to occur, and `zScale = 1.000005f;` does not cause the issue to occur.  `zScale = 1.000100f;` makes the issue occur, and worse.  This feels very much like a precision issue.

I tried maintaining `vpDepthScale` as a double, until the matrix math, and made that use it as a double.  This did fix the issue, and I'm no longer haunted by an evil shadow that follows me as I race.  Not sure if it's the best solution, though...

-[Unknown]

**Comment by hrydgard** [comment]
Huh, that sounds better than most of the other alternatives at least...

**Comment by unknownbrackets** [comment]
Wait, no I made a mistake.  I applied the scale after applying the translation.  It doesn't actually help.

-[Unknown]

**Comment by unknownbrackets** [comment]
To clarify what's happening here:

1. It's a 5551 buffer, and the road is drawn with filled stencil bits.  Other pixels have zero stencil.
2. A texture is blended on top of the road only (alpha test) with no depth testing, and several polygons.  It uses fixed blending to lighten the color of the road
3. The shadow is actually an area that is incorrectly not brightened by this operation; it's not an area getting darkened.

So the issue here definitely is clipping.  The darker portion is what is getting incorrectly clipped.

I tried forcing depth to be written by enabling an ALWAYS depth test, and enabling depth write.  The depth values written are all _very_ low values, < 5 / 65535.

I tried drifting positive by the equivalent of 0.325, to account for rounding issues, but this only improves the issue, the shadow is there but smaller.  Clipping IS enabled while it is drawing also, so it's not as if it's supposed to skip clipping or something.  Also, since this improved the issue, it makes me feel less sure about precision being the problem here...

It seems like our previous mapping of [-1, 65535] -> [0, 65535] was making this work correctly, and now that we are mapping the most extreme values appropriately to -1, it's clipping and that's causing this issue....

-[Unknown]

**Comment by unknownbrackets** [comment]
Crazy idea: maybe the PSP "rounds" the depth center to 0.5?  That could potentially explain this and #7932 (in that case, which also uses a range of 32768 and center of 32767.)

Using this after `float vpZCenter = gstate.getViewportZCenter();` in GPUStateUtils.cpp "fixes" MotoGP:

```c++
		if (vpZCenter == 32767.0f) {
			vpZCenter = 32767.5f;
		}
```

-[Unknown]

**Comment by hrydgard** [comment]
@unknownbrackets That seems like the most plausible explanation so far...

**Comment by unknownbrackets** [comment]
I have another theory.  I didn't test the depth clipping all that carefully, and I'm not super up to speed on how clipping is done in OpenGL / etc.

With #8454, I removed the clamping, so the shadow was gone.  Then I forced depth write on, and used the GE debugger to examine the depth values written in the area that was being incorrectly clipped.  My theory: it would be negative.

I did not find any negative values, just small values.  Maybe my math in the debugger is wrong, but 0 works right.

So either this means something is wrong or... it means something is getting clipped or culled wrong by a vertex?  I suspect the PSP only clips by the viewport (so [-1, 65535]), and then applies the per-fragment discard of minz/maxz.

-[Unknown]

**Comment by hrydgard** [comment]
We know that the PSP has very deficient hardware triangle clipping - games do their own clipping against the near plane, for example...

You will never see negative depth in the depth buffer as it can only represent positive values - the 16 or 24 bits are an unsigned fixed point number.

**Comment by unknownbrackets** [comment]
But it can be negative when I'm scaling to a subset of the depth range (the middle 1/256th) and then allowing values outside that range.  I implemented scaling logic in the GE debugger so it shows the values as scaled into that 1/256th range.  So I would see negative values.

-[Unknown]

**Comment by unknownbrackets** [comment]
#8454 now works properly with `DepthPrecision = 16`.  It seems there's some rounding happening with the float values, and that matches tests better.

However, there are some other issues I found.  Will update the other bug on those.

-[Unknown]
