### ISSUE TITLE
Phantasy Star Portable 2 see through wall bug

### ISSUE THREAD

**Issue by Robsoie** [hrydgard/ppsspp#8425]
Hi, starting with the build 1.1.1-621-gf081229 for windows-x86 the game PSP2 has permanent see through wall bug when playing with Direct3D backend

![621](https://cloud.githubusercontent.com/assets/976867/12295554/0ec1a528-ba02-11e5-86b7-fb113a81fe00.jpg)

In previous available windows-x86 , build 1.1.1-608-gabc0f27 this bug does not exist and you can't see through the walls

![608](https://cloud.githubusercontent.com/assets/976867/12295580/3597a792-ba02-11e5-941c-6888198427ad.jpg)

**Comment by GamerzHell9137** [comment]
Seems like the new build made those trough the wall things but fixed the shadows. Neither builds are good i guess.

**Comment by unknownbrackets** [comment]
This works in OpenGL right?  It seemed like there were issues related to stencil/alpha that caused things to bleed through.

A savestate that easily reproduces the issue, or stepping through the GE debugger, could probably confirm.

-[Unknown]

**Comment by Robsoie** [comment]
No, after testing it does not work in OpenGL either, in latest available build v1.1.1-660-g4a337f7 , OpenGL and Direct3D both have this "see through walls" problem, same as posted screenshot.
In past both worked.

Here is a save state made with latest build.

.. Hmm, can't seem to attach the zipped state file, continuously have message "Something went really wrong, and we can’t process that file. " , not sure how to process from there.

PSP2 game is ULES01439 in case it makes a difference

**Comment by Robsoie** [comment]
pressed wrong buttons sorry

**Comment by unknownbrackets** [comment]
Can you upload it somewhere else and paste a link?

-[Unknown]

**Comment by Robsoie** [comment]
Hello, hopefully i think i did it correctly , here's the link to the downloading page 
http://www.filedropper.com/psp2state660

Let me know if it does not work for you, i'll look for another uploading solution.
save state is made with  v1.1.1-660-g4a337f7

**Comment by unknownbrackets** [comment]
Thanks.  So I see it's drawing the two overlapping things at different viewport depth settings.  It seems likely to be a depth issue, and it happens indeed in OpenGL as well.

I looked around more (haven't played much into this game), and found other areas with the problem as well.

It seems the game always clips fragment depth at < 10000 and > 65270.  It didn't look like this clipping was important (it's not implemented in PPSSPP.)

In one particular area, the depth offset/ranges were:

Background: scale=-27635, offset=26116
Behind background: scale=-27635, offset=37635

It seemed like the background ought to have had a higher depth value than it ended up with.  It was around 39100 that the thing that ought to be behind it was being drawn at, with src >= dst.

Using pixel depth rounding did not help.

From the above, the effective range of the background should've been: 0 (clamped) - 53751, and the thing wrongly on top: 10000 - 65270.  Since the background was clamped, but the thing drawn incorrectly wasn't, this implies that there is some issue in the clamping logic here.

-[Unknown]
