### ISSUE TITLE
Control Mapping: Numpad Keys not detected

### ISSUE THREAD

**Issue by CtrlFreak1337** [hrydgard/ppsspp#8428]
When I try to enter my numpad keys in the control mapping menu, they aren't read properly. When numlock is disabled, it simply reads as kbd.5, kbd.7, etc., and when it's enabled, it reads num5 as kbd.00?, 2,4,6 and 8 as their respective arrows, and 1, 3, 7, and 9 as end, pgdn, home, and pageup, respectively. 0 is read as insert. The math symbols aren't read at all; PPSSPP doesn't react in the "input key" phase when I press one of them.

On a previous version of PPSSPP, these controls worked fine. I have checked to ensure that it is PPSSPP reading the keys incorrectly, and not my system; when I open the test keyboard menu, it properly reads the numpad keys as numpad inputs, not regular number or function keys. This confirms that PPSSPP is reading them wrong.

I'm using PPSSPP 1.1.1, downloaded via apt-get on Ubuntu 15.10.

**Comment by unknownbrackets** [comment]
These should be `(SDLK_KP_0, NKCODE_NUMPAD_0)` etc. which was added before v1.1.1.... hm.  And the keymap has defined it for a while too.

We had updated to SDL2 recently at that point, so maybe it is related to some SDL2 issue.  Does this still happen with a recent SDL2 version?  Also, does it happen with Qt?

-[Unknown]

**Comment by vnctdj** [comment]
I can't reproduce the issue in my SDL build, all keys work (numbers, /, *, -, +, ., Enter).
I don't know about Qt as I don't use it.

A note:
I don't know if it's intentional, but Num Lock has no effect: it's as if it was always enabled.

**Comment by unknownbrackets** [comment]
It's been a while since this issue was created and it's reported working more recently.  It's possible this was a bug with SDL or the platform, even.  I'm going to close assuming it's been fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
