### ISSUE TITLE
Riviera: Blankscreen

### ISSUE THREAD

**Issue by LightVR0** [hrydgard/ppsspp#8429]
Riviera (all versions) runs on blank screen on 1.1.1 and Direct3D, this don't ocurrs on 1.0.1.

**Comment by vsub** [comment]
Use OpenGL if you can(works fine...at least here)

**Comment by unknownbrackets** [comment]
Works fine for me in OpenGL and Direct3D.

Probably something broken in your system, or some hacks you're using.  It sounds like you're using a device with a video card that doesn't even support OpenGL 2, so that could easily be the problem as well.

Also, you seem to refuse to try the latest git build.  This issue list is only for the latest git build.  If you won't test whether it works in the latest git build, I'm going to close this.

-[Unknown]

**Comment by LightVR0** [comment]
Fixed on v1.1.1-808-gd5539c4
