### ISSUE TITLE
PPSSPP starts silently in background

### ISSUE THREAD

**Issue by SukharevAndrey** [hrydgard/ppsspp#8476]
After some recent (about 2 months) update in Windows 10 (or it may be NVIDIA drivers) PPSSPP just starts in background and does nothing. I can see the process in Task manager, but that is it.
It is not the emulator problem I guess, because old builds don't work either.
Starting processs through DebugLog.bat or InfoLog.bat also gives nothing, no log files are created.
How can I determine what causes the problem?

**Comment by SukharevAndrey** [comment]
I found the problem: GeForce Experience. If Share function is activated (Alt-Z for stream options), PPSSPP doesn't work. If I disable it, everything is ok.

**Comment by unknownbrackets** [comment]
Hmm, I don't know what that feature does.

Does anything different happen if you switch backends (e.g. Vulkan, Direct3D9, GLES)?

-[Unknown]

**Comment by TehPlayer14** [comment]
I assume it got fixed with newer versions of GeForce Experience 

Please close

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
