### ISSUE TITLE
Phantasy Star Portable missing text

### ISSUE THREAD

**Issue by blackman91** [hrydgard/ppsspp#8492]
Using the latest dev in Android, no settings change fixes it:
http://i1312.photobucket.com/albums/t539/talos910/Screenshot_2016-01-23-19-03-18_zpsscgzmlli.png

Using the europe iso, it seems the compatibility ini doesnt fix the issue, I thought this issue was already fixed?

**Comment by unknownbrackets** [comment]
Can you try editing your ini file, and change `HighQualityDepth = True` to `HighQualityDepth = False`?  There's no UI for this setting, you'll have to connect your device to a computer or something.

-[Unknown]

**Comment by unknownbrackets** [comment]
Hmm, actually, it seems the per-pixel rounding and also the scaled range are not working.  Only GPU_ROUND_DEPTH_TO_16BIT works.

Hmm.

-[Unknown]

**Comment by unknownbrackets** [comment]
Using `255.0f` as the scale factor happens to work.... also, this fixes it, offsetting ALL values by an extra half bit:

```
// This is used for float values which might not be integers, but are in the integer scale of 65535.
static float ToScaledDepthFromInteger(float z) {
	const float depthSliceFactor = DepthSliceFactor();
	const float offset = 0.5f * (depthSliceFactor - 1.0f) * (1.0f / depthSliceFactor) + (1.0f / (65535.0f * 256.0f));
	return z * (1.0f / depthSliceFactor) * (1.0f / 65535.0f) + offset;
}
```

Maybe it wasn't a d3d9 specific issue after all... this works on my desktop too.

-[Unknown]

**Comment by unknownbrackets** [comment]
It seems like this may also be affecting the minigame at the start of Ridge Racer for me.

-[Unknown]

**Comment by unknownbrackets** [comment]
Just to summarize, at least on my phone (Adreno 330):

Phantasy Star Portable 1 (text):
 * Does NOT work with GPU_ROUND_FRAGMENT_DEPTH_TO_16BIT
 * Works with GPU_ROUND_DEPTH_TO_16BIT
 * Does NOT work with GPU_SCALE_DEPTH_FROM_24BIT_TO_16BIT

Ridge Racer 1 (minigame):
 * Works with GPU_ROUND_FRAGMENT_DEPTH_TO_16BIT
 * Does NOT work with GPU_ROUND_DEPTH_TO_16BIT
 * Does NOT work with GPU_SCALE_DEPTH_FROM_24BIT_TO_16BIT

All 6 scenarios work on desktop, at least NVIDIA.

Ridge Racer seems like a clear + a throughmode draw.  I tried some offsets based on the theory that `glClearDepth(0.5f);` was a "center" and `glDepthRangef(0.5, 1.0f)` was edges, but none of that played out...

-[Unknown]

**Comment by hrydgard** [comment]
Wow. Depth sure is a minefield of badly tested drivers and unnecessarily different behaviours...

**Comment by unknownbrackets** [comment]
This really seems like a precision issue.  I'm suspecting that the precision of the depth range or clear registers is terrible, or something...

In Ridge Racer, it first does a clear to 0, and then draws on top with 0.  The test is `src >= dst`.  Clipping is enabled, but it doesn't matter - and it's throughmode.  This really should be simple, and hard to mess up, imho.

Anyway, since it's not drawing, it's clear that the cleared depth of 0 is > the drawn depth of 0.  Must be.

Therefore, I tried adding an offset.  I've found that if I subtract `1 / pow(2, 20)` from the clear's "0", it works.  Any smaller value does not seem to have an impact.  And adding an offset to both (in case it's rounding bias) doesn't seem to help either... but maybe I could find the "right place" to align to `1 / pow(2, 20)`.  I can also add the same `1 / pow(2, 20)` to the depth range, and this fixes it - again, no smaller values help.

This is all while using a 1/256th scale range.  And the above doesn't help Phantasy Star Portable 1 -  but forcing minz/maxz to 0/65535 does help it.  Note that it normally sets this range to 0x2710 - 0xfef6.  If we assume that we lose 4 bits when specifying the range, 0xfef6 won't work right... and 0xff00 works just fine, which confirms this.

I think this means it's either using half floats of fixed 20 bit values for the depth range and clear, although the actual depth buffer has 24 bits of precision... ugh...

-[Unknown]

**Comment by unknownbrackets** [comment]
@blackman91 what device are you using?  I'm mainly wondering what GPU...

-[Unknown]

**Comment by unknownbrackets** [comment]
@hrydgard I'm not really seeing great options here for Adreno, at least, and who knows about other drivers:

Even a DepthSliceFactor of 2.0f, using 0.25-0.75, causes `glDepthRangef(0.25f, 0.75f)` != `glClearDepthf(0.25f)`.  Some hacky solutions using offsets kinda work but seem wrong.

If we use DepthSliceFactor 1.0f, clear works - but then we lose the clamping - the sombra de la muerte follows you again in Moto GP.

We can sorta fix clear in this specific case by mapping a clear for 0 to actually 0 - it won't work if a silly game uses a == or <= test drawing with only 0 depth values, though.

Or we could go with what we had before, but then clipping is wrong for Phantasy Star Portable 2 and other games, since depth is incorrectly scaled...

-[Unknown]

**Comment by hrydgard** [comment]
:(

Well, we can treat this as a vendor bug and apply "hacky solutions using offsets" when Adreno hardware version < 4xx, for example...

**Comment by blackman91** [comment]
I have a Mali 400mp

**Comment by unknownbrackets** [comment]
Then a single blacklist won't help.  Maybe I can create a test to figure out where clear/draw/range precision lies... we'll need to run it on various hardware though, and no guarantees future hardware will be sane either...

The most conservative approach I can think of so far is: 1. Use a range of [0, 1] on mobile or everywhere, potentially with option?  Dunno.  And then 2. Clamp depth that's near the edges in the vertex shader (similar to what we did before, ultimately), but only for a fixed extent - too far, and allow it to clip.  That shouldn't distort Z too much.  Pretty darn hacky, but it might give us the best of most worlds...

Where we can have accurate depth, I really like what we're doing right now, though...

-[Unknown]

**Comment by hrydgard** [comment]
So how about this: On Adreno < 4xx and PowerVR, we fall back to the old style vertex depth rounding, which does fix Phantasy Start etc, while we use the new limited range method on all other GPUs?

**Comment by unknownbrackets** [comment]
@hrydgard it's not about vertex depth rounding, though.  The problem goes deeper, although our old method was working more often.

Let me summarize what we're doing now, which all seems not to work:

 * We're mapping PSP z=0 to GL z=something other than 0.  This allows us to "pretend" to clamp.  **Does not work on Adreno 3xx at least.**

 * We've stopped shrinking viewports that have depth go from < 0, which was previously partially working around clamping but caused glitches in Phantasy Star Portable 2.  **Does not work on Adreno 3xx at least.**

 * We're using the depthrange to clip minz/maxz.  **Does not work on Adreno 3xx at least.**

 * We're trying to simulate a 16-bit depth buffer, when necessary, using a segment of the depth range.  **Does not work on Adreno 3xx at least.**

That is, **each** of these **in a vacuum form the others** seems to have different problems on Adreno 3xx.  Right now it looks like we have to get rid of **each** of these things.

It's not enough to go back to the "old method of vertex rounding."  We'd need to stop respecting minz/maxz, start skewing wide viewport depth ranges to [0, 1] again, go back to clipping clamped ranges, AND go back to the old method of vertex rounding.

-[Unknown]

**Comment by unknownbrackets** [comment]
Just to clarify the problem I've observed on Adreno so far, glClear(x) *seems* to end

**Comment by unknownbrackets** [comment]
Just to give context on some debugging I did on my phone, `glClearDepthf()` can clear individual depth values at a precision of `1 / (2^24-1)`.  I don't know if the way I'm reading the values is accurate, but there are some values that don't seem "addressable" using any float I've tried.  For example, I can get `0x007f8002` and `0x007f8001`, and `0x007f7fff` - but I can't get `0x007f8000` no matter what I try.

Also, when doing the 1/256 slicing - because we're slicing to `1/256th` and then dividing that by 65535, is actually off.  The actual range is 65535.996, which causes some inaccuracy.  This is probably fixable, and just slicing differently seems to have fixed it.

But, even trying different values, it doesn't seem like I can match clear and the min range.  From what I can see, *any* value passed to glClearDepthf() ends up being at a half pixel offset of the range, and then it just rounds differently than a draw with the range.  In other words, `glDepthRangef(0.5f, 1.0f)` and `glClearDepthf(0.5f)`, then drawing with a shader output of `-1.0` would not match the 0.5 - the clear value would be slightly higher than the min depth value.

If I'm right, there are workarounds - 1. Clear 0 to 0, and hope games never use an == test.  Clear other values to those values but hope they don't happen.  2. Convert depth clears to draws.  3. Keep the range at [0, 1] as before and keep hoping no one clears values other than 0.

It also seems like the depth range is "quantized."  Or at least, It works properly if I round minz/maxz to the nearest 16 (or less than that at different slice values.)

Even a slice of 2 - [0.25, 0.75] doesn't work.  Even starting at 0.5 with a 1/4 slice (so [0.5, 0.75]) doesn't work.

-[Unknown]

**Comment by DarkD** [comment]
It's me again commenting on Phantasy Star Portable(though in different thread as there's so many of 'em for this game that I couldn't find previous) and you will be laughing, or maybe not, but as it started working properly on DX9 it stopped working on OGL...
It shows text properly on build 806 and since 808 it isn't. On DX9 it works perfectly for me now on 888 can't trace it, somewhere between 757 and 797 it was fixed. If needed - tell me and I'll look up exact build it was fixed tomorrow.
As I stated in other thread I'm playing on Win7, x64 build of PPSSPP and my graphic card is Nvidia GeForce GTS 250.
Really hope you'll be able to avoid all mine on this minefield with elegant solution, guess it cost you a lot of nerves already...

**Comment by unknownbrackets** [comment]
Well, that means that switching to per-pixel rounding broke it for you in OpenGL, rather than using per-vertex rounding.  In Direct3D, you're using a different method, which is narrow depth-range based.

-[Unknown]

**Comment by DarkD** [comment]
Seems like that - works like a charm on 907. Thanks for taking care of that!

**Comment by sum2012** [comment]
So do I of my mother's phone in  #8541
Tokimeki Memorial 4 work fine now

**Comment by hrydgard** [comment]
So hm. What do we do with this? What remains?

**Comment by unknownbrackets** [comment]
We could switch back from per-pixel, which might bring back some flickering.  See #8475 and #8484.

-[Unknown]

**Comment by Gamemulatorer** [comment]
This issue doesn't produce on my phone using latest version of ppsspp.

### The issue missing text
![Screenshot_2016-01-23-19-03-18_zpsscgzmlli](https://user-images.githubusercontent.com/37603562/119235446-2a422100-bb65-11eb-9085-5940e2eb82e6.png)

Using my Redmi Note 9 text is not missing
### Vulkan
![Screenshot_2021-05-23-01-18-54-143_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/119235461-41810e80-bb65-11eb-94ac-94551a57ab63.jpg)
### OpenGL
![Screenshot_2021-05-23-01-19-15-133_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/119235476-55c50b80-bb65-11eb-918a-3f1888d37499.jpg)

**Comment by Gamemulatorer** [comment]
Ah sorry this issue can only reproduce on Europe but not in USA version of the game 😅

**Comment by Gamemulatorer** [comment]
This issue maybe related to #1788 ?

**Comment by unknownbrackets** [comment]
It's a depth comparison issue.  The game relies on an exact comparison.

The #1788 issue is really just a problem with not using accurate depth ranges, I think, so separate.

-[Unknown]
