### ISSUE TITLE
Final fantasy 3 stutter on first attack in every battle

### ISSUE THREAD

**Issue by delongeone** [hrydgard/ppsspp#8506]
Hi it seems that with any sort of texture upscaling on regardless of level, with the first attack I make in every battle, the game stutters for a second. If I turn off upscailing completely the issue disappears. I was just wondering if there is a fix for this. I am using an original Nvidia shield tablet.

**Comment by unknownbrackets** [comment]
Upscaling takes a chunk of CPU whenever a texture shows up.

The reason it happens on the first attack in battle is because the time between battles is long enough that the texture is no longer cached.

You may be able to combine it with auto frameskipping to reduce the stutter, if you can't live without the upscaling.

-[Unknown]

**Comment by asbel123** [comment]
i got no issue on my samsung galaxy s6 edge i am using auto battle u get 60 frames turn off auto will go 30 frames. i am using high resloution 5x and upscale and are u using shader  u get slow down.

**Comment by hrydgard** [comment]
Closing this because there's nothing we can do to prevent this specifically. In the future we'll likely move upscaling to the GPU which should help.
