### ISSUE TITLE
Kingdom Hearts Birth by Sleep sound issues.

### ISSUE THREAD

**Issue by blackman91** [hrydgard/ppsspp#8508]
Using the latest dev on android, the sound during cutscenes randomly stops and sometimes it starts again, same thing happens sometimes with the background music. I read this was an already fixed issue?

**Comment by unknownbrackets** [comment]
Is it reproducible in some area?  The intro seems fine to me.

-[Unknown]

**Comment by blackman91** [comment]
I am not using cheats nor cpu clock changes, Yeah the intro seems fine it started happening when I reach the palace for the test and it is pretty noticeable when you talk to maleficent (I am playing as terra). Also when using commands sometimes there is a high pitch noise that happens out of nowhere.

**Comment by blackman91** [comment]
Hi have you been able to reproduce it? I found an old post in the ppsspp forums describing the exact same problem I am having in an older version:
"Latest android revision (9.9.1-1278-g2e675c7) fixed audio issues I was having previously. During in-game cutscenes audio would randomly cut out while characters were speaking and music wouldnt play in the background. Its fixed now."  from http://forums.ppsspp.org/showthread.php?tid=445&page=31

So maybe the issue is back for some reason?

**Comment by blackman91** [comment]
I think the timer hack was what was causing the sound issues.

**Comment by unknownbrackets** [comment]
Oh, the timer hack would definitely cause issues like that.  Like I said, hacks can cause weird bugs.

Are you not able to reproduce with that off?

The timer hack basically allows the time the game sees to use your phone's clock.  Normally, if emulation is running slow (just so it's consistent), we tell the game a simulated time, that moves as fast as emulation does.  Some games will start frameskipping (themselves, not ppsspp frameskipping) if the clock shows lag.  So it can make things faster.

But, if you're actually getting close to / full speed without the hack, it can just make things worse.  In that case, the game will do 16ms of stuff, and the clock will only have progressed by 1ms.  This can make games slower, or play sound incorrectly.

Anyway, that's why it's called a hack.

-[Unknown]

**Comment by SamueldeSena** [comment]
this problem has already been corrected in the new version of ppsspp v1.5.4 this topic can already be closed
