### ISSUE TITLE
Feature Request.

### ISSUE THREAD

**Issue by blackman91** [hrydgard/ppsspp#8519]
Hi is this feature going to get implemented? 
http://forums.ppsspp.org/showthread.php?pid=54178

 android devices would benefit a lot from it, cheers.

**Comment by hrydgard** [comment]
I've changed opinion on it since then. Async audio may work in some games, but as was seen in Dolphin, it will break many others. Many games check for sound effects to finish before doing something, and if things happen at the wrong time, which often happens with async audio, games can either get stuck, misbehave or crash. These crashes can be extremely difficult and annoying to reproduce and debug, and I don't want that.

What we could do is add better time stretching of audio to cover the gaps better when the framerate can't keep up.

**Comment by unknownbrackets** [comment]
Also, we do already process some sound effects using a thread, where possible.  So SAS for example is already as async as it can safely be.

-[Unknown]
