### ISSUE TITLE
Tokimeki Memorial 4 black screen in latest git version in Android

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#8541]
Only my mother 's phone happen
Hope this night debug finish
Work in 
v1.1.1-778-g6ad9af4

don't work in 
v1.1.1-784-g4c8384a

**Comment by sum2012** [comment]
Here is my mother 's phone's information
![screenshot_2016-02-02-04-04-56_org ppsspp ppsspp](https://cloud.githubusercontent.com/assets/2177532/12729570/729bc988-c962-11e5-85c8-d70a6afd617d.png)
![screenshot_2016-02-02-04-05-21_org ppsspp ppsspp](https://cloud.githubusercontent.com/assets/2177532/12729572/72a9f83c-c962-11e5-805c-b3f6c0fccb6a.png)
![screenshot_2016-02-02-04-05-31_org ppsspp ppsspp](https://cloud.githubusercontent.com/assets/2177532/12729571/72a93870-c962-11e5-9ef9-14925982423e.png)

**Comment by sum2012** [comment]
@hrydgard @unknownbrackets 
It is https://github.com/hrydgard/ppsspp/commit/b80c02c27259b9271261ccd0f26f73a749c538df in #8461

**Comment by unknownbrackets** [comment]
I don't think this is a different issue from #8492.  Adreno 2xx and 3xx have some accuracy problems that make #8461 not work correctly.  Some of it can be worked around by rounding to the nearest 16 on minz/maxz, but it's really not a great situation.

I'm going to close this as a duplicate since I'm pretty much certain it has the same cause, along with Ridge Racer and several other games.

-[Unknown]
