### ISSUE TITLE
Macross Triangle Frontier Lag 

### ISSUE THREAD

**Issue by AizerMortenort** [hrydgard/ppsspp#8545]
I experience a great lag when using the multi-missles from my spaceship .
The emulator FPS drops very low and game lags like hell .
Otherwise it plays fine but the "missiles " shot by the Vajura Queen are causing the emu to lag.
My PC is 8 GB Ram/ WIN 7, 3.5 GHZ Quad Core with GTX660 OC if you need this info. It's powerful enough to handle this,
I tried everything and nothing fixes this lag.

Can you take a look.
VIDEO :
https://youtu.be/Q7bay5tQfNo

**Comment by piau9000** [comment]
Yeah, I used to have this problem too.
Wherever there a lot of missiles or explosions it lags real hard.
The same thing kind of happens on G Generation Overworld where some special moves that have a lot of effects and lights kind lags too.

It's been some time since I tested it so I don't know if it's still happening.

**Comment by AizerMortenort** [comment]
it does.
With latest builds. That is why I am reporting this to be solved.

**Comment by LunaMoo** [comment]
Couldn't reproduce this until I enabled vertex cache, so yeah just disable it. It's under performance for a reason.

**Comment by piau9000** [comment]
Also, in Texture Scaling, change Upscale Level to "off".
With it on it kinda lags some 2D effects.

**Comment by AizerMortenort** [comment]
Vertex Cache did the work!
Thank you luna moo
Upscale Level set to 5x and no lag lol.
Thanks for the suggestion trough piau9000
