### ISSUE TITLE
toukiden fps and speed issues

### ISSUE THREAD

**Issue by ivyking007** [hrydgard/ppsspp#8547]
using v1.1.1-818 dev version , when after the first moster battle it will turn out to 60/30(200.0%)overspeed and fps , use completly default setting  i don't touch any setting

**Comment by ivyking007** [comment]
on win7 64 version

**Comment by vsub** [comment]
I don't know if this is the case but this is one possible scenario to get that result(exactly at 60fps)

1.The game is 30fps
2.You have alternative speed enabled(the ~ key)
3.You have vsync enabled(always on)in your video card control panel and your monitor refresh rate is 60hz

**Comment by unknownbrackets** [comment]
Does this still happen in the latest builds?  What graphics backend are you using?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
