### ISSUE TITLE
Guilty Gear Judgment text problem.

### ISSUE THREAD

**Issue by blackman91** [hrydgard/ppsspp#8551]
Using the latest dev on android, default settings:
http://i1312.photobucket.com/albums/t539/talos910/Screenshot_2016-02-04-18-55-52_zpspy1o7upk.png

**Comment by blackman91** [comment]
Also I have noticed the music and sound effects stop in a couple of stages, just play all the 1-3 area in story mode to reproduce the issue.

**Comment by unknownbrackets** [comment]
Does this happen with fonts from a PSP?

-[Unknown]

**Comment by unknownbrackets** [comment]
It'd help to test with PSP fonts.  It'd also help to have a GE frame dump if possible.  These help a lot.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.  But I'm assuming it's related to PSP vs open source fonts, which we have other issues open for.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
