### ISSUE TITLE
Lag Gods Eater Burst on Asus Zenfone 4

### ISSUE THREAD

**Issue by ekkysw** [hrydgard/ppsspp#8553]
Hai, i playing Gods Eater Burst on Asus Zenfone 4...it so lag when i use 4 character and get just 60-70 % speed ,sound is no good too in condition, but when i use solo mission its so full speed and playable...so can you explain what settting to fix this lag ?
Ppsspp i use latest build 1.1.1-888
Setting ingame non buffered ,frameskip 1, others default

**Comment by unknownbrackets** [comment]
The GPU your phone has is a PowerVR SGX544MP2.  It could be this is just too much for the GPU, or much more likely, its drivers.  Also, this GPU is not capable of GLES 3.0, which means Vulkan probably won't help, and we're already doing more work to try to simulate features it doesn't have.

You might try checking "Disable slower effects (speedup)".  This may make it faster, but may also make the graphics look wrong.  But if you're already using "Skip buffer effects (non-buffered, faster)" then you're probably already missing the most important effects, anyway.

You can also try unchecking "Simulate block transfer effects", but I suspect that's already disabled due to "Skip buffer effects".

-[Unknown]

**Comment by ekkysw** [comment]
Thanks for your respon...but it still lag after i choose 4 character and battle with many aragami...hmmm maybe my smartphone dont strong enough to play this ???????

**Comment by ekkysw** [comment]
Some game that i try play in ppsspp lag too :(
1. Lego Batman Video Game ( its lag during gameplay but cutscene no lag)
2. Super Monkey Ball Adventure ( its lag during gameplay and its not playable in my phone)
I dont know other games because i dont have time to try play that...
So games that just playable in my phone is Kamen Rider Chou Climax Heroes, Harvest Moon Hero of Leaf Valley, Patapon 1, and Metal Slug XX....

**Comment by hrydgard** [comment]
There are limits to what's possible, I can't promise we'll ever get everything running smoothly on your particular phone. Try increasing frameskip to 2, if that doesn't help you're probably out of luck.
