### ISSUE TITLE
Menu toolstrip missing in Linux SDL version

### ISSUE THREAD

**Issue by GAMELASTER** [hrydgard/ppsspp#8630]
In Qt is menu integrated, but Qt version I must still build myself. Is possible to add menu to SDL version?

**Comment by unknownbrackets** [comment]
Android users don't have the menu either.  SDL and Android don't really provide a way to present a traditional application menu to the user.  Qt is a more complicated framework, and provides this feature - as does Windows.

In general, the entire application is designed to be used without a menu.  The only things that are present only on the menu are the debuggers, which SDL can't help you with anyway (because those are separate windows with buttons and etc.)

If you want a menu on Linux, Qt (or I suppose GTK or some other toolkit) is the solution.  I'm going to close this.

-[Unknown]
