### ISSUE TITLE
FF4 Atrifacts

### ISSUE THREAD

**Issue by GamerzHell9137** [hrydgard/ppsspp#8710]
Not sure if anyone realized but there's this weird black tear that happens sometimes in the game.

https://youtu.be/FodXKl95-_w

And for some reason the castle looks like it floats.

**Comment by unknownbrackets** [comment]
Disable vertex cache.

-[Unknown]

**Comment by GamerzHell9137** [comment]
The castle still floats.

**Comment by unknownbrackets** [comment]
I'm not really able to see the floating clearly in that video - maybe I don't understand what you mean.

Does it happen in the latest build, and with Vulkan?  At 1x / no texture scaling even?  How about in slow software rendering?

Note: vertex cache is off by default now.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
