### ISSUE TITLE
Crimson Gem Saga:

### ISSUE THREAD

**Issue by Vyguard** [hrydgard/ppsspp#8749]
For what ever reason the game seems to crash at totally random times. Sometimes you can get past it, sometimes you can't. I've run into an instance that I can't seem to get past. The ppsspp crashes, and I just get the nice message for windows to attempt to find a solution. Are there any fixes for this, or any settings that need to be changed? I'm running it on the ppsspp64 all the other games run perfectly fine. I'm also running default settings for the program.

**Comment by unknownbrackets** [comment]
This was reported here:
http://forums.ppsspp.org/showthread.php?tid=1243&pid=106156#pid106156

As a regression from 879baec692b299381756a41fa0c383d3736cc472.  We weren't sure why, though - this just suggested it was somehow timing related.

@LunaMoo created a [cheat workaround](http://forums.ppsspp.org/showthread.php?tid=1243&pid=119532#pid119532), but of course that's not really a full solution.

Looking into it further, the problem seems to be io timing related (noting for #7647).  By increasing the seek delay from 0.1ms to 0.3ms, for example, I'm also able to avoid the problem.  More tests may be needed, but changing the seek latency is probably the "correct" fix here.

-[Unknown]

**Comment by unknownbrackets** [comment]
It seems even 0.101ms latency instead of 0.1ms will work.  It's very possible that 0.1ms is just the wrong value and slightly too low, but I need to do more tests to try to verify.  Maybe we should change it for now, although I'm not sure if it fixes this issue everywhere.

The change is (all occurrences in sceIo.cpp):

```c++
return hleDelayResult(result, "io seek", 100);
```

To:

```c++
return hleDelayResult(result, "io seek", 101);
```

-[Unknown]

**Comment by y-salnikov** [comment]
101 does nothing but 200 is work for me. Don't know what i'm doing though.

**Comment by unknownbrackets** [comment]
Turns out it was actually too high - it works consistently for me without the too-large delay.

-[Unknown]
