### ISSUE TITLE
Mystic Chronicles not working since v1.1.1-392

### ISSUE THREAD

**Issue by vsub** [hrydgard/ppsspp#8764]
ppsspp-v1.1.1-392-g63e749d
There are two problems since 392(works fine with 390)

1.It says that it can't access the memory stick and you can't start the game because of that
2.If you compress the iso to cso,it skips the first 3 logos and the loading screen and "freezes" in the next screen(problem 1)but it shows an empty box without any text

In the console its also spamming non-stop(it also do that on 390)
E[HLE]: HLE\HLE.cpp:550 Unimplemented HLE function sceUtilityNpSigninGetStatus
E[UTIL]: HLE\sceUtility.cpp:772 UNIMPL sceUtilityStoreCheckoutGetStatus()

**Comment by unknownbrackets** [comment]
Hmm, for me it works fine as a CSO.  Natume, Kemco, and Hit-Point all show fine.

It does spam those functions but they seem unimportant since I'm able to play anyway.  I'm not sure we could make them do anything interesting except not log.

It has no problems accessing the memory stick.  I'm able to save and load just fine.

Could you possibly have corrupt save data?  I can try your save data, if you want (if it's the US version)?

-[Unknown]

**Comment by LunaMoo** [comment]
Seems to be caused by caching iso to ram, no clue why it would affect saves, but with compressed formats it seems to fail caching, similar thing happens with pbp format, except it just crashes with decompression error there.

 Would probably be good to silence all errors related to playstation store/network stuff since as I understand to avoid legal issues those will never be supported anyway and damn they are spammy.

**Comment by unknownbrackets** [comment]
Seems like it's a threading issue, or possibly an over-read issue on the last block.

-[Unknown]

**Comment by vsub** [comment]
Works fine now(iso and cso),thanks
