### ISSUE TITLE
Sound gets choppy

### ISSUE THREAD

**Issue by ibrahimqatar** [hrydgard/ppsspp#8768]
I'm using the new IR interpreter on my jailbroken iPhone 6s on 9.0.2 and tge sound is choppy/stuttering in all games.

I also tried it on non-jailbroken ipad pro 12.9 and 9.7 inches on 9.3.1 with the same bug. 

Update #1: I forgot to mention that the gameplay is butter smooth, the audio is the only problem.

Update #2: I also tested the latest dev version on an iphone 6 on ios 8.4 and using JIT, the sound still lags chops.

**Comment by ibrahimqatar** [comment]
I forgot to mention that the gameplay is butter smooth, the audio is the only problem.

**Comment by unknownbrackets** [comment]
Sound is choppy when the device can't run the game fast enough.  Does it actually run at 100% speed / 60 fps?  There's a setting in graphics to display this.

Try turning on frameskip.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
