### ISSUE TITLE
playtime error

### ISSUE THREAD

**Issue by sacrivared** [hrydgard/ppsspp#8815]
just update to v1.2.2-678-g239d6d3..

my warriors of the lost empire savedata playtime become 99:59 (save game after update)

**Comment by unknownbrackets** [comment]
Is there a specific way to trigger this?  Does it happen when you create a new save and play for a while?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
