### ISSUE TITLE
Menmapfunctions in PMW3

### ISSUE THREAD

**Issue by Mentifisto** [hrydgard/ppsspp#8838]
The emulator keeps freezing at exactly the frame below, anyone knows if it's fixable?

![untitled5](https://cloud.githubusercontent.com/assets/13773700/16475696/824aecac-3e78-11e6-8c87-ba1fde24f21e.png)
## 

Pac-Man World 3 - [EUR 1.00](http://report.ppsspp.org/game/ULES00260_1.00) / [USA 1.01](http://report.ppsspp.org/game/ULUS10055_1.01)

**Comment by unknownbrackets** [comment]
Other users have reported this game runs well:
http://report.ppsspp.org/game/ULES00260_1.00

Are you sure you have a good disc?  I recommend checking its crc, or just pulling it from your PSP again.  It's also possible this is related to settings - some are dangerous.  Try resetting to defaults.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
