### ISSUE TITLE
[ Steam/SteamOS related ] Steam Controller is not recognized as Xinput

### ISSUE THREAD

**Issue by ekianjo** [hrydgard/ppsspp#8849]
This is something to replicate under SteamOS. I find it impossible to map the Steam Controller correctly in PPSSPP when running it under SteamOS. The mapping that you specify in the Steam interface it not reflected in PPSSPP - somehow the keymap is never changed no matter what you do, and therefore I cannot play PSP games with the Steam Controller. I checked with a Xbox360 controller and that worked fine, I could map Xinput correctly, but even when disconnecting that Xbox360 controller and restarting my Steam Controller in Gamepad mode (i.e. Xinput) the keypresses are not correctly recognized.

Anyone can help ?

**Comment by unknownbrackets** [comment]
Does this work now?  Is it just a matter of adding the mapping to the gamecontrollerdb thing?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
