### ISSUE TITLE
Save state crashes on load iOS 

### ISSUE THREAD

**Issue by Rapsac11** [hrydgard/ppsspp#8855]
When loading a save state, ppsspp will crash to springboard. Additionally the same thing happens "some of the time" when loading a game. Tested iso: FF - Crisis Core, Valkyrie Profile. Running iOS 9.0.2 JB 6S+. Happens with and without IR interpreter

**Comment by unknownbrackets** [comment]
Are you able to get a log of the device?  Has this always happened or is it new?

-[Unknown]

**Comment by Rapsac11** [comment]
How can I obtain the log file? Is it stored in a particular location? I downloaded the latest version from Cydia today and the crash now occurs, prior to that I was on an older version from a few months back and save states worked.

**Comment by unknownbrackets** [comment]
Looks like it can be done with iTunes potentially, and definitely Xcode:
https://developer.apple.com/library/ios/qa/qa1747/_index.html

You can also apparently use the iPhone Configuration Utility?
http://stackoverflow.com/questions/2334664/can-i-get-console-logs-from-my-iphone-app-testers

-[Unknown]

**Comment by Rapsac11** [comment]
Oh right, iOS crash logs. Sorry I thought maybe there was a specific ppsspp log with my config saved.

Basically it's a bad access error. I'm not at a computer now but I may have some time later to turn zombies in Xcode and try get some more info.

**Comment by Jamesthecanaidian** [comment]
I have the same problem are you on iOS 9.3.3

**Comment by unknownbrackets** [comment]
Well, is it a bad access error because it ran out of memory?  Or something else?  What I'm really after is a stack trace or some info on where the crash occurred.

I realized you didn't mention what version of PPSSPP you're using.  Some months ago we did fix a crash bug that affected some games when you saved or loaded state.  I don't think it affected either of those games, but make sure you're running the latest version too.

-[Unknown]

**Comment by goduck777** [comment]
I have the same problem on iOS 9.0.2, using the latest working and dev version of PPSSPP.

The crash log is
http://pastebin.com/vs4ndwaS

**Comment by unknownbrackets** [comment]
So that says it's crashing inside here somewhere:

https://github.com/hrydgard/ppsspp/blob/cc1a16b0e05f32e893d2c892eb63b578b6604af1/Core/MIPS/MIPS.cpp#L254

It lists `MIPSState::DoState(PointerWrap &)` twice which is suspicious, so the top stack entry might be misleading.

This operation does reset the jit, so maybe it's reallocating and crashing there. 

-[Unknown]

**Comment by unknownbrackets** [comment]
This was probably something related to the jit, but current jit on an iPhone 6 / iOS 10 is able to save and load states just fine.  Closing this, as it appears to be fixed.

-[Unknown]
