### ISSUE TITLE
Virtual Lan

### ISSUE THREAD

**Issue by Heoz** [hrydgard/ppsspp#8858]
When we try to play tag force 3 we can only see each others on hamachi, but not on tunngle or evolve :O and we cant tag duel on hamachi so can you make something for this?

**Comment by unknownbrackets** [comment]
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
