### ISSUE TITLE
Make better packages.

### ISSUE THREAD

**Issue by orbea** [hrydgard/ppsspp#8859]
I maintain some build scripts (SlackBuilds) for Slackware and would like to add a ppsspp script to slackbuilds.org, but the way ppsspp is packaged makes that difficult.

1. ppsspp require `git submodule update --init` to compile, but SBo does not allow any scripts that require downloading additional sources during the build process.
2. the ppsspp tarballs as provided in the github releases are missing the .git directory so that the above command won't work anyways.

For my own personal use I am fine tracking the git master, but for SBo it would help a lot if you could provide more complaint source packages. Thanks!

**Comment by unknownbrackets** [comment]
If you're talking about the tarballs here:
https://github.com/hrydgard/ppsspp/releases/tag/v1.2.2

These are automatically generated by GitHub.  I agree that it'd be better if they included submodules, but I think they're basically generated using `git archive`, which doesn't - for whatever reason.

I recommend:
```sh
git clone --depth 1 --shallow-submodules --recursive https://github.com/hrydgard/ppsspp --branch v1.2.2
```

Or, if you can't depend on git 2.9+:
```
git clone --depth 1 --recursive https://github.com/hrydgard/ppsspp --branch v1.2.2
```

Basically, I think git should be the source of packages.  It will also automatically verify the data and commits with sha hashes.  Otherwise, we'd have to store the tarballs somewhere, and worry about them and their .asc files getting hacked or something to get the same thing.

Worth noting - the syntax above only works for tags and branches.  For specific git builds like v1.2.2-763-gdddb3c3 (which we often recommend users use and have automated builds for on many platforms), a full clone might be necessary.

-[Unknown]

**Comment by orbea** [comment]
I guess the solution is to make the tarballs personally, but nvm on this issue. I did it myself. 

PPSSPP is now available on SBo.

https://slackbuilds.org/repository/14.2/games/ppsspp/
