### ISSUE TITLE
One game mode

### ISSUE THREAD

**Issue by Anuskuss** [hrydgard/ppsspp#8862]
I know this may sound really abstract, but bear with me:
I currently run PPSSPP on my iPhone and only play **Yu-Gi-Oh! GX: Tag Force 2** because I don't have much space left. So I was thinking why not let PPSSPP automatically start my only game? You could make it .ini only and expand this by compiling it with Xcode.

You could change the title and the icon, so I for example have an app with the title **Yu-Gi-Oh!** and the icon of the cover of that particular game. And by clicking it, it automatically starts my game and I don't have to bother with the rest. What do you think about it?

Btw, sorry for misusing the issue tracker as a forum.

**Comment by hrydgard** [comment]
Hm, I don't know if we support command line parameters on iOS - if so that might be a solution, if you can somehow add command line parameters to shortcuts.

If you are building PPSSPP yourself it should be easy to hack it to only start your game - in NativeInit, set boot_filename somewhere before 

    screenManager->switchScreen(new EmuScreen(boot_filename));

Though it seems like a really small issue, the game will show up on Recently Played and it's only one touch to start it. If you want the icon and stuff you're going to have to build it yourself anyway probably, so then you can also just hack it to start the game as described above.

**Comment by Anuskuss** [comment]
Yeah that makes sense, I will test it when I'm free.
I know it's one click away but I liked the idea of having a native app. One could even create multiple instances of PPSSPP and put them in a folder (which would look really neat).

**Comment by unknownbrackets** [comment]
On Android you can do exactly that.  Just tap and hold on the screen, select widgets, then the "PPSSPP widget", and you can add any game you want to the home screen / a folder.

I don't know iOS well enough to know, but if it has "widget" or "shortcut" creation functionality, then it might be possible there too.  It would definitely take someone who has an iOS device to get that working, though.

I think iOS may have that because I thought Safari could create home screen shortcuts to websites.  However, it could be functionality that is not allowed for third party apps...

-[Unknown]

**Comment by Anuskuss** [comment]
Well, on iOS we have URL schemes `scheme://host/path?query` which could use the CLI of PPSSPP. A website could generate those icons which could then be saved to the home screen.

We also have widgets in the notification center which could also use the URL schemes.

We just need some iOS developer (@angelXwind).
