### ISSUE TITLE
Initial D Android with Windows XP with hotspot multiplayer Issue

### ISSUE THREAD

**Issue by NgJinXiang14** [hrydgard/ppsspp#8865]
At first i can see my opponent and start the game, but it stuck at engine start scene so we close our fast memory. But after that we cant see each other so i reenable fast memory, but we also cant see each other. Can you all help me? 
![20160721172047](https://cloud.githubusercontent.com/assets/6142827/17018183/2edf1a3c-4f69-11e6-96c0-93f424bad533.jpg)

**Comment by Margen67** [comment]
Why are you still using Windows XP?

**Comment by NgJinXiang14** [comment]
Old laptop

**Comment by unknownbrackets** [comment]
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
