### ISSUE TITLE
Kirin 950 multthread issue

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#8895]
My freind said that PPSSPP only use Kirin' s two weak core in multthread.
Other CPU such as Qualcomm 801 ,MediaTek 6592 , MediaTek  6752 are stronger in multthread.
Any possible to solve it ? Thanks

**Comment by unknownbrackets** [comment]
Unfortunately this happens on some devices.  It *MAY* help to turn on "real time clock sync".

The reason: in some games, there are only "spikes" of activity.  Much of the time, PPSSPP may actually not use a ton of CPU - and the OS may decide to save battery power by putting it on the weaker cores.  But this causes problems when the spikes happen.

This is why some users report custom ROMs with customized CPU governors help...

-[Unknown]

**Comment by sum2012** [comment]
My friend said no help.
One core 90% full speed but after a while it would become to use weaker core

![3](https://cloud.githubusercontent.com/assets/2177532/17460952/5daab0e6-5cad-11e6-8378-0c1c4c2fae45.jpg)

![1](https://cloud.githubusercontent.com/assets/2177532/17460949/1bd47468-5cad-11e6-93e4-ce7316650bd1.jpg)

![2](https://cloud.githubusercontent.com/assets/2177532/17460951/4f140550-5cad-11e6-9a01-7181912df7b3.jpg)

**Comment by sum2012** [comment]
He tried to use only power core,but only use 1 core in playing.
This issue I think can use.
Closing

**Comment by sum2012** [comment]
Other users in china have same problem
Keep issue here.
The main problem is that why cannot use 2 power core to play.

**Comment by unknownbrackets** [comment]
Because the PSP is a single core device (so games are written in a way that won't allow them to be run on multiple cores or they'll crash), and OpenGL is a single core API.

Think of CPU cores as employees.  OpenGL allows one employee to be assigned to rendering.  Another employee is assigned to the CPU.  We're actually able to assign another employee to disk activity and even another one to some audio decoding.

But the audio decoding and disk employees don't have much to do.  They spend most of their time just sitting around doing nothing.

The OpenGL rendering employee is super busy.  But she isn't willing to work with other people - so we're stuck with only one person doing rendering.  If rendering is behind, everything is behind, and we're stuck.  We can't have two employees work on rendering.

The situation is the same with CPU emulation.  We're limited to one employee working on it.

That's why it uses one core - you're seeing that one of the employees is super busy, and making all the others wait for them to complete their job.  Someone is holding everything up.

Vulkan may allow spreading out the GPU load onto more cores (multiple employees doing rendering), but there's a lot of complexity there.

-[Unknown]

**Comment by ijoinit** [comment]
no wonder the apple CPUs are always some customized bigger cores,and powerful gpu,I wonder if multithreading rendering can have better performance, I wonder if the apple metal rendering API support multiple cores threading.and exept CPU,does the OpenGL use multiple gpus or only use one gpu? I think it's multithreaded gpus,like sgx 543mp4,mail 400multiple4,but only one CPU,this seems like a bottleneck of OpenGL.
