### ISSUE TITLE
Add Battlegrounds 3 v0.4 to homebrew store

### ISSUE THREAD

**Issue by ebraminio** [hrydgard/ppsspp#8923]
I guess bug tracker is not best place for requesting addition of an app to Homebrew Store however I didn't find the suitable place on the forum other than [this topic](http://forums.ppsspp.org/showthread.php?tid=11243), so I thought it worth to be mentioned here once also. BG3 is an advanced homebrew game which is fortunately **a free and opensource software**, published under BSD license. Originally, last version of it is released on [this blog post](https://battlegroundspsp.wordpress.com/2009/10/31/bg3-0-4x-updated-binary-source-released/#comments) but as I didn't want to lose this great game [again], I am re-uploading it here also: 
[bg3-0.4x-p.zip](https://github.com/hrydgard/ppsspp/files/427539/bg3-0.4x-p.zip)
It has an exceptionally (between homebrew games) great 3D graphic and I think it would be great addition to the PPSSPP Homebrew Store. Thank you!

PS: If being FOSS is not of a main criteria for the addition, my next candidate would be [JellyCar](http://forums.ppsspp.org/showthread.php?tid=5005), downloadable from [here](http://dl.qj.net/psp/homebrew-games/jellycar-for-psp-v11.html), [mirror](https://github.com/hrydgard/ppsspp/files/427600/JellyCar.zip).

**Comment by hrydgard** [comment]
I just downloaded and tried the game but it doesn't actually work very well. Audio and graphics are stuttery for some reason.

Before adding it, we should probably investigate what's wrong with it and fix it. I want the stuff in the PSP Store to actually work well on the emulator.

**Comment by unknownbrackets** [comment]
Hmm, performance seems good for me at least on desktop?  I remember this game because it had weird shadow glitches which helped fix the issues in God of War and other games.  I haven't tried many modes, though.

-[Unknown]

**Comment by hrydgard** [comment]
Huh, maybe I have some strange setting activated. Got bad audio stutters, I'll try again later.

**Comment by wickles** [comment]
I'm the maintainer for this game (it is now available at https://github.com/xfacter/battlegrounds3). I am planning some fixes eventually but I noticed that it is stuttery and slow when you turn off the 60FPS cap (on by default). This may be your problem @hrydgard. 

While I'm here I would like to suggest [Kosmodrones](http://www.kosmodrones.com/). It's a really great homebrew game by Abhoth, but not FOSS AFAIK.

**Comment by hrydgard** [comment]
There's a visible FPS counter in battlegrounds that's rather distracting, makes it look like a debug build. Also it seems wrong in PPSSPP... 

There seems to be some bad flickering issues, too, especially on mobile for some reason. I think the game is doing something wrong with vsync...

**Comment by hrydgard** [comment]
I did upload Kosmodrones now though!

**Comment by wickles** [comment]
> I did upload Kosmodrones now though! And a few other new ones.

Great! Maybe now somebody will beat my high scores ;)

> There's a visible FPS counter in battlegrounds that's rather distracting, makes it look like a debug build. Also it seems wrong in PPSSPP...

You're absolutely right, I guess I somehow left the debug flag on since the last release. Woops. I just rebased and posted a new build so you can grab that. (If anyone cloned already, please delete and clone again.)

You're probably right about vsync, I noticed the same strange behavior with the FPS counter. I have some simpler sample code based on the same engine, that I tried with a more accurate counter (counts per second instead of 1/dt), and it showed 114 when the 60 FPS cap was on. So that's odd, will look into it. 

I should probably also delete the useless/misleading menu options too while I'm at it.. 👶

**Comment by unknownbrackets** [comment]
Hmm strange, you seem to call bg3_game_update_render (and ultimately sceDisplayWaitVblankStart) once per xTimeUpdate(), not sure why that would report other than 59.94 at a glance...

-[Unknown]

**Comment by wickles** [comment]
What's the problem with GOW referenced in the 60FPS cap setting? Is this the same kind of behavior?

**Comment by wickles** [comment]
Actually it isn't calling sceDisplayWaitVblankStart because it never enables X_WAIT_VBLANK (or X_PSEUDO_AA). I just enabled X_WAIT_VBLANK and it fixes both the FPS display and the slowdown without FPS cap. But then it's capped at 60fps of course -- is that expected or does PPSSPP try to work around vsync to push higher framerates?

**Comment by unknownbrackets** [comment]
Keep in mind the PSP display only refreshes 59.94 times per second, and the same behavior happens in PPSSPP.  Higher than 60fps doesn't really gain you anything.

God of War renders as much as it can, as fast as it can - at variable FPS.  IIRC, the menu screen renders at ~100+ fps on a real PSP.  Pretty sure some areas render a bit under 60 fps.

Rendering at > 60fps also causes performance problems in PPSSPP.  We track "emulated time" that runs at a deterministic pace, no matter how fast or slow your actual device is (which means everyone gets the same bugs, or not bugs.)  However, this means a "second" of emulated PSP time might actually take 2 seconds of real world time.

That's why we have the setting - God of War runs better on more devices with it on, and doesn't really look any different (because either way you only *see* 59.94 frames every second.)

-[Unknown]

**Comment by wickles** [comment]
That seems to explain everything then. If I understand correctly, then any app running at >60fps would slow down without the FPS cap on, correct?

**Comment by unknownbrackets** [comment]
Yes.  Well, if the device is capable of running the game at 120fps in real time, then the app can run at 120fps without a cap and it won't noticeably slow down.  Depends on what operations the app is doing, how slow they are to emulate, etc.

-[Unknown]

**Comment by wickles** [comment]
Good point, I was just thinking about that, since I noticed my sample code runs fine at >1000fps with the cap disabled.

**Comment by ebraminio** [comment]
(Than you so much @wickles for this discussion to make this happen, big fan of the game here btw)

**Comment by hrydgard** [comment]
@wickles , let me know when you've posted a new build with fixed vsync, if you haven't already?

**Comment by ebraminio** [comment]
@hrydgard can you put jellycar, linked at the end of the first post, if it meets your criteria also? Two best games of the old days. Thanks

**Comment by wickles** [comment]
IIRC I originally disabled Vsync to improve performance on the real PSP since I don't think that it consistently hit 60fps. So I'm not sure if it's appropriate to release a build with Vsync on by default. If you just want it for testing I could post a build here. Anyway, I'd like to make a few other tweaks before you put it up, if you don't mind. Shouldn't take too long. 

In the mean time there is also [Battlegrounds2](https://github.com/xfacter/battlegrounds2/releases) which seems to work pretty well for me in PPSSPP, if you would like to put that on the store.

**Comment by unknownbrackets** [comment]
I'd suggest you check `sceDisplayGetVcount()`.  Like this:

```c
int vcount = 0;

...

    int newVcount = sceDisplayGetVcount();
    if (newVcount == vcount) {
        // Wait for the next frame.
        sceDisplayWaitVblankStart();
    }
    vcount = newVcount;
```

This would cause you to call `sceDisplayWaitVblankStart();` only when render takes < 16.6ms.  If rendering slower, it would maximize fps.

That being said, if performance is significantly different inside PPSSPP compared to a PSP, it's technically a bug...

-[Unknown]

**Comment by wickles** [comment]
Ah, that's a nice solution, guess I'll use it. 

> That being said, if performance is significantly different inside PPSSPP compared to a PSP, it's technically a bug...

I could be wrong, it's been a while since I tried it on a real PSP.

**Comment by unknownbrackets** [comment]
Oops, edited it above seeing it again - `sceDisplayWaitVblankStart();` will change the vcount of course, oops.

-[Unknown]

**Comment by wickles** [comment]
One thing I'm trying to fix is the shadow maps drawing not only the projection below the tanks but also the reverse projection up on the hills above the tanks. Do you know if there's an easy GU/GUM way to fix this? I've been trying to adjust the near plane in the projection matrix, and adjusting the texture bias matrix:
```
ScePspFMatrix4 texProjScaleTrans = {
	{0.5f, 0.0f, 0.0f, 0.0f},
	{0.0f, -0.5f, 0.0f, 0.0f},
	{0.0f, 0.0f, 1.0f, 0.0f},
	{0.5f, 0.5f, 0.0f, 1.0f}
};
```
But I can't seem to get it right, either the shadows stop showing up at all or they're backwards, distorted, or rendered at different perspectives. Any ideas?

**Comment by wickles** [comment]
@hrydgard new build up now

**Comment by ebraminio** [comment]
Hey guys, can this get another [final] boost? Thanks

**Comment by hrydgard** [comment]
Which link is the newest build?

**Comment by LunaMoo** [comment]
Probably [here](https://github.com/xfacter/battlegrounds3/releases)
 On a side note it might be showing some new Vulkan issue - seems to have ocassional(possibly rare, I used unthrottle) flashing of some terrain in the background of the main menu.

**Comment by hrydgard** [comment]
Battlegrounds 3 is now up.

**Comment by Emulatorer** [comment]
> Battlegrounds 3 is now up.

@hrydgard why this hembrew game is super lag on phone?
GE Dump: 
[BG3H00252_0001.zip](https://github.com/hrydgard/ppsspp/files/4524311/BG3H00252_0001.zip)

I'm using ppsspp v1.9.3-702-gitbuild
