### ISSUE TITLE
iOS 9.3.1 [JB] Crash at launch

### ISSUE THREAD

**Issue by Asinith** [hrydgard/ppsspp#8948]
Hello , so i'd like to share my issue , i installed PPSSPP via the official Repo that we can find in the official website , everything is installing but when i try to launch it , it makes a black screen and closes 

Exactly like this guy https://www.youtube.com/watch?v=HoRm5J_HkJ4

Thanks for future helpers

**Comment by unknownbrackets** [comment]
That video seems to feature an ancient version of PPSSPP.  Are you using a recent git build?  v1.2.2 won't work on older devices, see #8122.

-[Unknown]

**Comment by Asinith** [comment]
Hello , thanks for the reply i'm using an iPhone 5S 
On the Cydia Repo it's the version 1.1.1

**Comment by unknownbrackets** [comment]
Those are both fairly old.  There's been a recent fix which I think is necessary for iOS 9:

http://build.ppsspp.org/?page/downloads

As mentioned, jit doesn't really work on older versions than a recent git build (including v1.1.1), because of #8122.  It's a security change made by Apple, it caused PPSSPP to stop working.

-[Unknown]
