### ISSUE TITLE
ppssspp not detect all host cores in the Device info

### ISSUE THREAD

**Issue by sl1pkn07** [hrydgard/ppsspp#8951]
I have a dual CPU setup, but ppsspp only detect one of the cores in the Device info window

![](http://wstaw.org/m/2016/09/03/Screenshot_20160903_220144.png)

![](http://wstaw.org/m/2016/09/03/Screenshot_20160903_220637.png)

**Comment by hrydgard** [comment]
Dual CPU setups are pretty rare, I haven't seen one in ages so no wonder we missed this case.

However, it's not like PPSSPP is going to use more than at most 3 threads anyway, so it hardly matters. I'm leaving this open though in case someone would like to take a look and fix it, but as I can't test locally, I'm probably not gonna dive in.

**Comment by unknownbrackets** [comment]
#11388 should have fixed this, though it wasn't tested on multi-cpu systems.  It should work however, and not have the problems that existed before.

It'd be great if you could test and report results here.

That said, since this probably works and has not seen a lot of activity in a few years, I'm going to close it assuming the change did fix it.

-[Unknown]
