### ISSUE TITLE
PowerSaveModeReceiver crashes on Android

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#8992]
Can't repro myself, but getting tons in the Play console, so I pushed out what I believe to be a workaround.

```
java.lang.UnsatisfiedLinkError: Native method not found: org.ppsspp.ppsspp.NativeApp.sendMessage:(Ljava/lang/String;Ljava/lang/String;)V
    at org.ppsspp.ppsspp.NativeApp.sendMessage(Native Method)
    at org.ppsspp.ppsspp.PowerSaveModeReceiver.sendPowerSaving(PowerSaveModeReceiver.java:76)
    at org.ppsspp.ppsspp.PowerSaveModeReceiver.onReceive(PowerSaveModeReceiver.java:27)
```

Really strange, it's like it's trying to call sendMessage before the .so is loaded. What do you think @unknownbrackets ?

**Comment by unknownbrackets** [comment]
The change should be safe since we always send initially:

https://github.com/hrydgard/ppsspp/blob/279a8e26580fb17c61e65636dba6967577f486f7/android/src/org/ppsspp/ppsspp/NativeActivity.java#L275

I should've thought of that race condition, though, because it's registered in the manifest:

https://github.com/hrydgard/ppsspp/blob/175f3316e0c7131d050c7dda765cbfe7f42544ac/android/AndroidManifest.xml#L99

Essentially, I think the workaround is the right thing - I don't think it has a downside.  Sorry for not thinking of that case...

-[Unknown]

**Comment by unknownbrackets** [comment]
I think this is no longer an issue - closing.

-[Unknown]
