### ISSUE TITLE
Failed to build ppsspp-sdl on Debian 8

### ISSUE THREAD

**Issue by Sunderland93** [hrydgard/ppsspp#9000]
Hello. I try to build ppsspp-sdl on my Debian 8 repo on Open Build Service https://build.opensuse.org/project/show/home:Sunderland93 I use debscripts from [PPA](https://launchpad.net/~ppsspp/+archive/ubuntu/stable), but build failed with error

`[  401s] /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libavcodec.a(tiff.o): undefined reference to symbol 'lzma_code@@XZ_5.0'
[  401s] //lib/x86_64-linux-gnu/liblzma.so.5: error adding symbols: DSO missing from command line
[  401s] collect2: error: ld returned 1 exit status
[  401s] CMakeFiles/PPSSPPSDL.dir/build.make:817: recipe for target 'PPSSPPSDL' failed`

P.S. I try to build FFmpeg and PPSPP with -llzma flag, but without result.

**Comment by unknownbrackets** [comment]
Hmm, not sure.  Maybe there's some enable flag missing in the ffmpeg configure script?

-[Unknown]

**Comment by Sunderland93** [comment]
FFmpeg 3.0.2 from Debian Backports repo. I just build it with Nvidia NVENC codec support. But PPSSPP won't build even with vanilla Debian FFmpeg

**Comment by sergiobenrocha2** [comment]
Are you trying to link against libav or ffmpeg? I had that once, when trying to link against libav.

Try use this deb package instead: https://mentors.debian.net/package/ppsspp

**Comment by unknownbrackets** [comment]
Does this still happen with the latest git build?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other issues, and sometimes certain OS updates can help too.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same build, just create a new issue instead.

-[Unknown]
