### ISSUE TITLE
cannot run under 8.4.1

### ISSUE THREAD

**Issue by saiikii** [hrydgard/ppsspp#9006]
Just now I deleted the old version without jit and interrupted the process because I forgot to restore my game and I got them out of the psp file. And as I resumed to the deleting and finished it, I cannot run ppsspp again. It would be stuck at the screen of the 'ppsspp' and then stop working. Could you please tell me how to restore it:)

**Comment by saiikii** [comment]
I'm just used to putting the game under the psp file:), a little weird

**Comment by unknownbrackets** [comment]
I think this is fixed in the latest git build, with whatever the newest jailbreak is.  There seems to be an issue with the buildbot, though (#10399), so it has to be compiled manually right now.

That said, I'm going to close this.  It runs on recent iOS devices, although there are other iOS bugs.

-[Unknown]
