### ISSUE TITLE
Ppsspp ios bug

### ISSUE THREAD

**Issue by shen88** [hrydgard/ppsspp#9017]
I recently updated ppsspp, however ehen i tried to open it, i can't load my save states. Even my cofigures gone back to default. Also i can't make new save states. Cheats are not working too. Please help!

**Comment by zero2029** [comment]
Ppsspp latest version 0v1.3-23-gff66fe7 has a weird bug. Ppsspp doesn't open sometimes when trying to launch from the home screen. And when that happens it makes springboard unresponsive (can't open apps) and I have to hard reset my iPhone. I'm on ios 10.0.2 and I have the 256gb 7 plus.

**Comment by unknownbrackets** [comment]
Does this still happen in the latest version?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
