### ISSUE TITLE
Perfect GTA LCS camera movement

### ISSUE THREAD

**Issue by TheOfficialFloW** [hrydgard/ppsspp#9019]
Recently I have found a way to gain native control over the pspemu in the PS Vita. Soon I have written a plugin for GTA LCS that patches the camera functions in order to return the right analog values.

I have posted an explaination/tutorial on how I have found them and I would love if developers join this project and try to patch other games.
http://wololo.net/talk/viewtopic.php?f=5&t=47219&p=413608#p413608

This will also highly benefit PPSSPP as people will get the best gaming experience using this.

Tell me what you think,
TheFloW

**Comment by unknownbrackets** [comment]
We actually do support the right analog stick already:

https://github.com/hrydgard/ppsspp/blob/842a29b0aedd2e5db59128f3b25b06d803d27386/Core/HLE/sceCtrl.h#L27
https://github.com/hrydgard/ppsspp/blob/master/UI/ControlMappingScreen.cpp#L501
https://github.com/hrydgard/ppsspp/blob/master/UI/EmuScreen.cpp#L705

And we handle it in the way you would expect: we just fill the ctrl bits.  This was used by some HD remasters released for the PS3, and I believe it's been tested with them.  So any hack to make a game read these bits should Just Work.

Have you already tried the patch in PPSSPP?  Did it not work?

-[Unknown]

**Comment by TheOfficialFloW** [comment]
The codes you have shown me are only supposed to support the hd remasters that you have mentioned. Filling the ctrl bits will not magically allow you to use the right analog stick as camera in normal games.

I think you didn't open my link yet, thus your response.

My patch hooks the game's camera functions in order to return the rx/ry values. You might ask: why not just simply map the keys? GTA for example uses L+left analog stick. If you simply simulate this combo using the right analog stick you won't be able to walk and use camera at the same time for obvious reasons.

Here's a demonstration:
https://twitter.com/theflow0/status/780481867149615104

**Comment by unknownbrackets** [comment]
Yeah, it sounds like an interesting project.  There has also been work done on 60 fps patches for various games and texture replacement packs.  Lots of cool areas to enhance games.

I mean, theoretically, one could even enable touch.  It would just mean exposing a new function which would have to be added to the stub table in the game patch - or potentially just reusing something like sceIoDevctl.  But I'm sure a touch controls patch would be a ton of work.

But this right stick support is pretty cool since it additionally works on the Vita and maybe even on the PS3 (not sure if its remaster support can be coerced into running non-remaster games - afaik it's just an emulator, likely same as with minis.)

-[Unknown]

**Comment by LunaMoo** [comment]
Just done one myself for [a completely different game](http://forums.ppsspp.org/showthread.php?tid=1847&pid=122555#pid122555) as a proof of concept, so yeah such patches are already possible on ppsspp using cwcheats to inject code, and right analog is read just fine by normal non remastered games.

 Not terribly hard and seems to work better than 8 direction + acceleration which is the case when mapping face buttons to analog stick, but in the end I don't feel like it greatly improved my experience, using a real gamepad over psp was already a huge improvement, so maybe that's why, or maybe psp games are just too simple for it to matter:P.

**Comment by TheOfficialFloW** [comment]
Nice patch!

For GTA it really makes my gaming experience better, my reason for this post here is to see whether PPSSPP would like to integrate my patches and also because I want to motivate people to write patches for more games, at least for the AAA games, so maybe you @LunaMoo, might be interested too in supporting this project.

Myself I am going to find offsets for all GTA regions and versions.

**Comment by LunaMoo** [comment]
Will probably not do much more myself simply because I don't have many of such games and also it might be too time consuming, a resource which I recently don't have much.
 With GitS I had some general plan already since I thought about doing something similar in the past ~ for mouse control, considered using external program / cheat engine to feed the game with mouse info ~ to avoid dealing with ppsspp mouse issues ~ and that had it's own issues, not really sure, if it could get close to proper mouse control anyway so I just gave up on it.


 Unsure if [Unknown] or Henrik would like the idea of "integrating" game mods within ppsspp, if cwcheat support isn't enough for your mod, you might need to wait for #724

**Comment by Fadi5555** [comment]
Can this patch working on tomb raider legend as well?
I mean without need to put square to use camera.
If this works on will be great.

**Comment by Zetchzie** [comment]
@Fadi5555  I think this would benefit allot of games.

**Comment by Fadi5555** [comment]
@Zetchzie you're absolutely right. Because most of games don't support camera button. My dream to play tomb raider legend with right analog stick for camera.

When we can see this patch on ppsspp?

**Comment by Zetchzie** [comment]
@Fadi5555 AFAIK these patches will need to be made individually for each game so this isnt universal. someone would need to code it into TRL and other games

**Comment by Fadi5555** [comment]
@Zetchzie got your point. Thank you for info.
I hope this gonna happen soon.

**Comment by unknownbrackets** [comment]
It doesn't sound like there are any bugs to fix here - it works.  I'm sure people would like to see these patches, but it's not really about the emulator.

If anything, it might make sense for someone to create a separate repo, and manage the patches for various games there.

As far as including them in PPSSPP by default, I personally have my reservations, but could see it making sense.  Probably makes more sense to consider that when there are a number of patches available so we can think through the UI right for users, if we decided to include (and of course, would need the patch authors to be okay with them being included.)

-[Unknown]

**Comment by unknownbrackets** [comment]
Closing as per the above.  We now have some support the plugins as well (although not kernel function support), so it may be possible to use the same plugins on a PSP and in PPSSPP.  See #13335.

-[Unknown]
