### ISSUE TITLE
P3P - Persona 3 Portable - Crash Help?

### ISSUE THREAD

**Issue by GWCount** [hrydgard/ppsspp#9024]
Seems like people have been able to solve issues with P3P crashing?  Mine goes down at the end of the decision with Ryoji, right after you max the S.Link on 12/31, and I believe right before it cuts back to the lounge.

Save states and my normal save all fail to work?

I'm running it on a Galaxy Note 4, PPSSPP v1.3.0.1

Thank you for any help you can offer.  (TTATT)

Save Info:

(.BIN)
https://drive.google.com/file/d/0B4vdvFA6jUqPcFZ6WnhwTFBONHc/view?usp=sharing
(.SFO)
https://drive.google.com/file/d/0B4vdvFA6jUqPZWV2X1k5aExDYms/view?usp=sharing

**Comment by unknownbrackets** [comment]
Are you using any cheats?  Have you used any cheats?  I know that crashes in this game have been connected with using certain cheat codes.  Sometimes, even after turning off the cheat codes, the damage is done - I think there may even be an issue with one of the cheats that irreversibly damages your save.

If you load the save on a real PSP, does it not crash?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
