### ISSUE TITLE
My phone gets really hot

### ISSUE THREAD

**Issue by Legoman1013** [hrydgard/ppsspp#9046]
When ever I use this emulator after like 3 minutes or less my phone started getting really hot and I don't really know why

**Comment by unknownbrackets** [comment]
That's how mobile electronics work.  How much this happens varies by device (you didn't specify what phone you have), but it's completely normal.

Electricity generates heat.  Your phone doesn't have a fan or water cooling pump, so it has these options:

 * Get hot (dissipating heat as best it can by making the device body hot)
 * Limit the CPU speed (lower FPS but better battery life and cooler)
 * Turn off because things got too real

Most of the time, devices will automatically limit their CPU speed to manage heat.  This is why some people will complain that after playing PPSSPP for a few minutes, it suddenly starts getting worse FPS.  This is because the phone decided it was working too hard, and kicked into low gear.

If your device isn't slowing the CPU down, it's probably able to keep up with the temperature - but it's going to be hot, and it's going to burn through its battery.

Your best bet is to reduce your settings.  Turn down the render resolution, DEFINITELY make sure texture scaling is off, etc.  These things are not free, and each one costs heat and battery.

For more information, check the forum.  This isn't an issue we can fix, so I'm closing.

-[Unknown]

**Comment by hrydgard** [comment]
@unknownbrackets Yeah. By the way, android 7.0 has an interesting feature that we might want to use, which will help this issue in a way:

https://developer.android.com/about/versions/nougat/android-7.0.html#sustained_performance_api

This locks the device into a performance level that it can sustain for long periods without overheating. While we'll get lower performance, at least it'll be consistent and sustainable.

**Comment by unknownbrackets** [comment]
I wonder if we ought to make this an option, like immersive mode?  We could display it based on `isSustainedPerformanceModeSupported`, which we're apparently supposed to check prior to ` setSustainedPerformanceMode`.

I kinda think we should just enable it (who wants roller coaster performance?) but maybe [some people would complain about not having the option](https://xkcd.com/1172/)....

-[Unknown]

**Comment by hrydgard** [comment]
Well yeah, that will have to be an option.
