### ISSUE TITLE
Activision Hits Remixed (USA) black screen

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#9052]
when you first load up the game there is nothing but a blank screen
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/523550/ppsspplog.zip)

**Comment by unknownbrackets** [comment]
Does it work if you use the software renderer?  It may be very slow, I'm not suggesting this as a fix - just trying to figure out what's wrong.

-[Unknown]

**Comment by LunaMoo** [comment]
No idea why, but this title ends up with few endless loops, might be just another timing issue or some kind of weird protection.
 Made a CWCheat workaround for EU version that made it boot just by breaking those loops, then noticed multithreading affects some timing and also makes it boot. ;p
![ules00640_00000](https://cloud.githubusercontent.com/assets/5485237/19337000/cd3a0708-9110-11e6-80db-ee5a3f7576be.jpg)
 After booting works fine althrough requires quite powerful hardware since it abuses some slower effects. Disabling those or using frameskipping is also an option, will break graphics in selection menu and hud(which can be disabled), but doesn't affect games themselves.

**Comment by SimPiko** [comment]
- before ea2fc552179f931790e8c344936ebfb543faec20 (build 'v1.4.2-649-gb280e30a2' and older) 
it was booting/running after enabling "multithreaded (experimental)"
- after ea2fc552179f931790e8c344936ebfb543faec20 (build 'v1.4.2-660-gea2fc5521' and newer)
no "multithreaded" option makes the game not running at all

I've tried to tinker with CPU clock rate (on newest build, v1.6), seems like values ranges 40-41, 78-81 and 100 MHz, makes game bootable again, so it's probably timing issue that messes everything up.

**Comment by unknownbrackets** [comment]
Could you upload a log file with it running, and another one from it not running?  Ideally, same PPSSPP version for both - e.g. 100 Mhz (working) and 120 Mhz (not working.)

That might give us an idea where the timing first starts to really make things different.

-[Unknown]

**Comment by SimPiko** [comment]
here're logs, 
80MHz, working, https://gist.github.com/SimPiko/96b712c00d834b2fe770e6875771d1e8 (~15 MB)
120MHz, not working, https://gist.github.com/SimPiko/e21827777a589465f063e9ccce4f6741 (~2 MB)

It's bit weird, but even with 'right' MHz, emu failed to launch the game... it's probably because i had to turn "I/O timing method" to "fast", idk anymore.

**Comment by benderscruffy** [comment]
goes ingame now no problems
