### ISSUE TITLE
Wolfenstein 3D v5.2 Beta (homebrew) cannot start game

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#9075]
on the options screen after you press X to choose your game it says to press square to start the game but it is like it doesnt detect it

http://www.brewology.com/downloads/get.php?id=9352

**Comment by LunaMoo** [comment]
I tested latest version of this homebrew that is [6.0](http://www.brewology.com/downloads/download.php?id=9730&mcid=1) and it seems like the per-game executable files simply aren't loaded since game uses unknown syscall 0x28d0d249 - by jpcsp it's [sceKernelLoadExecVSHMs2]( https://github.com/jpcsp/jpcsp/blob/c32400a698e6459fc0d9d9614cd225be774a4341/src/jpcsp/HLE/modules/LoadExecForKernel.java#L67), adding it should be enough to fix this.

 By the looks of it in-game, it's just an alternative nid to sceKernelLoadExec? Not sure if jpcsp doesn't do anything more with it, but I manually changed that unknown syscall to sceKernelLoadExec in disassembly and the game booted fine.:P
![menu_00005](https://cloud.githubusercontent.com/assets/5485237/26284785/547b6358-3e43-11e7-84c9-9ef8cd8253b2.jpg)

**Comment by hrydgard** [comment]
Cool. Feel free to pull request that, it's obviously rare enough that even if it does do something a bit different, it hardly matters. Likely it's just something for internal use.

**Comment by LunaMoo** [comment]
Just to note, I think the pauses in this homebrew are of same nature as pauses in [Frontier 1337](http://forums.ppsspp.org/showthread.php?tid=16138), not sure of their cause yet, but after some tries I could boot into smooth game, full fps was higher as well, maybe it's something with gpu timings.
