### ISSUE TITLE
ppsspp sdl linux fails to enter full screen on startup

### ISSUE THREAD

**Issue by thesourcehim** [hrydgard/ppsspp#9086]
Though fullscreen option is enabled in config, ppsspp starts in windowed mode (starting the game does not change that). If after that I go to graphics options, I see "Full screen" checkbox checked. If I press that checkbox, ppsspp goes to full screen and checkbox stays checked.

**Comment by mac1202** [comment]
Confirm this behavior using the latest git version.

**Comment by Bracket-** [comment]
This also causes a minor bug with cursor visibility. The cursor should be visible while windowed but is hidden since fullscreen is set but not enabled. Entering and exiting fullscreen restores the cursor.

This is all assuming SDL cursor enabling/disabling is enabled. It's currently disabled on master due to what appears to be a oversight after the native merge.
