### ISSUE TITLE
Ultimate Ghosts and Goblins: crash on texture loading

### ISSUE THREAD

**Issue by yoshisuga** [hrydgard/ppsspp#9089]
When playing Ultimate Ghosts and Goblins, it crashes after a few minutes of play.

I'm using iOS (non-jailbroken iOS 10.0.3, latest master) and through the debugger, i was able to see that the crash occurred on Core/GPU/GLES/TextureCache.cpp (:

```
        PROFILE_THIS_SCOPE("loadtex");
        glTexImage2D(GL_TEXTURE_2D, level, components, w, h, 0, components2, dstFmt, pixelData);  <--- here
```

The issue appears to be that the memory couldn't be allocated, as I'm getting a lower level memory allocation assertion at the iOS Metal API. There's a block of code after this that tries to detect a memory error but it isn't getting called because of the os-level error that happens as a result of making the open gl call to glTextImage2D.

**Comment by unknownbrackets** [comment]
Unfortunately, a lot of iOS devices have not a lot of memory - and more importantly, limit apps to a max amount of memory.  Here's [a list about that](http://stackoverflow.com/questions/5887248/ios-app-maximum-memory-budget).  If you're using anything older than an iPhone 5, PPSSPP will be force-crashed at ~300 MB.

Generally, PPSSPP doesn't use a ton of memory - but especially when you enable graphics enhancements, it can start to use a ton.

From my perspective, glTexImage2D is broken if it crashes when there's not enough free memory for it to do its thing.  That's the responsibility of the (in this case, clearly slightly broken) driver.  We don't know how much memory is available to us (Vulkan allows us to know, but won't ever happen on iOS anyway), so it's hard for us to make informed decisions here anyway.

Make sure you have these settings:
 * Render resolution: 1x
 * Rewind: off
 * Expect saving state to potentially crash on iPhone 4/4S and below.
 * Texture upscaling: off
 * Texture replacement: off
 * PSP mode: PSP-1000
 * Retain changed textures: off

On iPhone 6S and higher, you can probably safely use savestates and higher settings without much concern.  In no case should you ever enable "Retain changed textures" on an iOS device, and rewind is probably still straight out.

If this crash even happens with minimal settings, it may be that some undersireable situation is causing us to allocate a lot of textures - that may be a bug.

-[Unknown]

**Comment by LunaMoo** [comment]
This seems to be a regression starting from https://github.com/hrydgard/ppsspp/pull/8761/commits/f168978d3e0f148a65982c18baca140138cac5b9

 Leaks ~ 1mb per frame when some enemies carrying torches are visible, or more exactly when some effect likely related to those torches light tries to do it's job ~ rendering to texture(althrough it doesn't seem to work or at least doesn't bring any noticeable change).

 Additional notes:
- skipping buffer effects avoids the problem,
- dx9 works fine even with buffered rendering,
- potentially unrelated since skipping buffer effects avoids the problem, but Vulkan crashes at https://github.com/hrydgard/ppsspp/blob/ff66fe7f896a766564e95a25032985506e9bef7f/GPU/Vulkan/DrawEngineVulkan.cpp#L416 the moment those opponents shows up.

**Comment by yoshisuga** [comment]
I'm using an iPhone 7 Plus on iOS 10.1 (non-jailbroken) and yes it does look like using non-buffered rendering avoids the crash.

I'm afraid fixing the issue is beyond my ability (right now), but thanks for tracking it down @LunaMoo !

**Comment by LunaMoo** [comment]
Can easily say the same thing;p, maybe [Unknown] or Henrik will be able to find something when they have more time as the problem can be easily reproduced by starting the demo:
http://www.pspdemocenter.com/demos/ULJM91004/EBOOT.PBP
(it's Capcom 3 in 1 demo pack, the first demo from the top is japanese version of this game)
 In addition to memory leak, the demo also shows some artifacts over whole screen via the same framebuffer, some leftovers from demo selection menus I guess, full game shouldn't have that.

 Either way the framebuffer which causes this leak has address 0x04044000, and 512x512 size, was detected same way in older builds.
 The only difference I noticed between older/working code and now while checking for the framebuffer that causes this issue is that AttachFramebuffer() seems to be called more often now.

**Comment by hrydgard** [comment]
Repro'd. Will fix for 1.4.

**Comment by hrydgard** [comment]
This seems to be solved now, I think I accidentally fixed this bug while doing minor refactors in the texturecache...

**Comment by LunaMoo** [comment]
@hrydgard hmmm you didn't tested in different backend or without buffered rendering by accident? As trying v1.3-705-gb94ad12 the memory leak still happens here both in demo and full version.

**Comment by hrydgard** [comment]
Hmm, maybe... I didn't see it in the demo now, tried with GL. But I'll give it another shot.

**Comment by hrydgard** [comment]
Really found it this time, I think :)
