### ISSUE TITLE
[Android] can't replace textures

### ISSUE THREAD

**Issue by Juliex** [hrydgard/ppsspp#9107]
in windows,after the emulator dumps the textures in:
.../game-ID/new
and in ppsspp.ini:
savenewtextures=True
Replacetextures=False

,then I copy a texture from .../game-ID/new 
to:   .../game-ID.
and in textures.ini , for example texture:

[hashes]
093c5080ade3a490e4bf08a5.png
[hashranges]
093c5080ade3a490e4bf08a5.png 

then, again in ppsspp.ini:

Savenewtextures:True
Replacetextures:True
or:
Savenewtextures:False
Replacetextures:True

.then they will replaced in game.

but this way didn't work on android.i have tested several ways,but never worked at all.
means no way to replace any texture on android.

**Comment by LunaMoo** [comment]
That:
```
[hashes]
093c5080ade3a490e4bf08a5.png
[hashranges]
093c5080ade3a490e4bf08a5.png
```
placed in textures.ini does absolutely nothing, when you run ppsspp on a desktop platform and create the ini file from ui it should have two links which explains proper syntax of that file:
- https://github.com/hrydgard/ppsspp/pull/8715
- https://github.com/hrydgard/ppsspp/pull/8792

 Also, if you would paste just that text you had to a clear file called textures.ini it would actually disable the feature since textures.ini file to avoid some future problems has to include:
```
[options]
version = 1
hash = quick
```


That being said, while I'm not really using android, tested it just now to be sure and it worked fine, at least with properly made textures.ini file. In your case that would look like:
```
[options]
version = 1
hash = quick
[hashes]
00000000ade3a490e4bf08a5 = Filename.png #comment after "#" in case it's needed
```
where Filename.png would be your png "093c5080ade3a490e4bf08a5.png", but I would recommend naming it properly.
00000000ade3a490e4bf08a5  is the original filename with first 8 digits zero'ed as that's most common case how you'll use wildcards for hashes, but best just read the syntax in links above or browse through [this thread](http://forums.ppsspp.org/showthread.php?tid=18963) which has lots of that explained as well.

**Comment by Juliex** [comment]
it worked.
the problem was from ini file.
when removed it,new textures worked.
All the time it was disabled replacement.
thanks to all.
