### ISSUE TITLE
Can't save in-game?

### ISSUE THREAD

**Issue by z-ss** [hrydgard/ppsspp#9126]
I've been playing Final Fantasy IV: The Complete Collection, and I can't seem to save at all. 
Errors that show when I go into "Load Game":
![1](https://cloud.githubusercontent.com/assets/23653132/20517366/fa92f6f4-b057-11e6-9734-99cdf314ba45.png)
![2](https://cloud.githubusercontent.com/assets/23653132/20517367/fc7e7ab0-b057-11e6-9384-4838a7de3c15.png)
The save option is greyed out:
![3](https://cloud.githubusercontent.com/assets/23653132/20517368/fd235116-b057-11e6-86e7-e8b86883de41.png)

I'm running version 1.3.0 of ppsspp on a Windows 10 PC.

**Comment by LunaMoo** [comment]
Not sure if you ever played any game like that, but you can only save in some places, like on the world map or special "save points" and it's grayed out everywhere else since the game wants it to be(old/console games do that to limit savedata size).

 The error shows up because it can't find any existing savedata to load. It will stop showing up once you save in-game properly.

**Comment by LunaMoo** [comment]
The error as explained in #8329 shows up on real PSP without savedata as well, so closing since nothing here is bugged.
