### ISSUE TITLE
PES 2014 texture replacement issues

### ISSUE THREAD

**Issue by Endarko** [hrydgard/ppsspp#9133]
pes 2014 are not all texture texture saved and not all can be replaced

**Comment by unknownbrackets** [comment]
This issue is over 3 years old now - but I'm not aware of anything that would cause textures not to save, except `textures.ini` rules/config or "textures" that are actually rendered by the game real-time.

I think we at one point did have an issue that caused problems for textures in certain areas of VRAM.

Is this still an issue?  Can you be specific on what textures are not saved, and where they show up in the GE debugger?

Remember: games can recolor textures or do a lot with lighting and other rendering parameters.  For example, a black and white texture might be used to draw tree leaves, and they might be colored different shades at render time.  Just because you don't see exactly the thing you expect, or just because the texture has alpha=0, doesn't necessarily mean it's not saving or can't be replaced.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
