### ISSUE TITLE
God Eater Burst Blocky grass and trees

### ISSUE THREAD

**Issue by ayaobayo** [hrydgard/ppsspp#9167]
![ulus10563_00000](https://cloud.githubusercontent.com/assets/24616548/21283832/67037c62-c3bf-11e6-82f6-1cb3accb61a5.jpg)

Hi everyone i tried looking around for this problem but i cant find anything this is my only place to go the game runs smooth and all and the only problem i have is the blocky texture i notice this happen on metal gear aswell with the grass but i only play this game since im hooked atm need help please.

**Comment by zminhquanz** [comment]
Turning off " Disable Alpha Test " to fix that

**Comment by LunaMoo** [comment]
Yeah, PPSSPP unfortunately by popular demand has a lot of game breaking settings for people that choose to sacrifice everything from graphics to stability for performance.

 You can't just disable important graphic features and expect games that actually use them to still look good - it will never happen.

 As such closing this since it's not an issue and from some time many awful settings like that already inform users about the dangers of using them. Can't really do more without removing those settings completely.
