### ISSUE TITLE
iOS Micro stutter

### ISSUE THREAD

**Issue by iOSSOi** [hrydgard/ppsspp#9197]
There are micro stutter playing any game on iOS. I've noticed that the stutter appear at the exact same place every time, so it's not a random stutter. I have tried both with and without JIT enabled, the stutter still appears.

Version 1.3-191
iPad Pro 12.9
iOS 10.2.1 beta 1
Non-Jailbroken

**Comment by iOS4all** [comment]
Me too I face exactly same issue

Version 1.3-191
iPhone 7 plus 
iOS 10.1.1 jailbroken.
Any help please?

**Comment by pongtapza89** [comment]
Ppsspp gord

**Comment by iOS4all** [comment]
We need something to prevent that annoying micro stutter.

**Comment by Orphis** [comment]
We don't have any proper iOS developer to work on this and our iOS devices are broken. So no work is going to happen on this soon.
But we're aware of the issue, it's been there for a while.

**Comment by iOS4all** [comment]
two weeks ago I saw a thread talk about this issue and fortunately I copied it. Here you go


(@hrydgard hi there. It's been long time about getting JIT finally to work on ios 9. But unfortunately all iOS users facing a terrible issue is most of games had stutter every 3-4 seconds. And this issue is killing our enjoying of playing. Yesterday I accidentaly discover a new way to prevent that stutter which happens every 3-4 seconds regularly. And you can't imagine how I was happy to play without any stutter (finally).

the method that I did personally is:
1-go to the cydia app.
2-download any app or tweak from the cydia. I prefer to download large app or tweak ( I'll tell you later why just keep reading)
My example app that I downloaded is (retroarch).
3- when is just start to download that app. directly exit from the cydia app (don't kill the cydia app from multitasking) just keep it download in background.
4-go to ppsspp app and run any game you want to play.
5-enjoy playing without any annoying stutter every 3-4 seconds.

Now I want to tell you why you should download large app/tweak? Because when cydia finish downloading that app the ppsspp will return back to stutter every 3-4 seconds immediately.

Note: I tried to download any app/game on AppStore but it doesn't work. (Only works from cydia).

From what I understand ppsspp on iOS it didn't detected to powerful mode cpu/source correctly. I mean it's not use a full power of iOS devices. As I said this issue belong to ios 9 Unlike ios 8 there is no stutter issue at all.

Anyway this is my method that I discovered and I just shared it to you guys.
We are now find a window to prevent that stutter.
I really hope from you guys to apply and fix this issue according to this method.

Thanks a lot.)

I'll try his method and be back later for results.

**Comment by hrydgard** [comment]
Still have no idea why this happens. We're not doing anything to tell ios we're not needing the full power of the device, or anything like that. It indeed does seem likely that the device is using less power than it should.

**Comment by iOS4all** [comment]
I agree with you on this point. I also remember my brother's iphone 5s when its on iOS 8.4 with TaiG jailbreak I played ppsspp on it. And there's no micro stutter at all. All games on stable speed.but after he upgraded to iOS 9 this issue is apear. Like Me. I have a jailbroken iPhone 7 plus on 10.1.1. And also noticed a micro stutter with all games. as you know iPhone 7 with A10 fusion is the most powerful device and even that there is a micro stutter as well. So that's why I agreed with you about the power of the device is doesn't matter. Because iPhone 5s run all games on iOS 8 very smoothly.
So there is something wrong maybe in JIT code or something like that.

**Comment by LunaMoo** [comment]
Don't have iOS, but since I lurk on forums, I would compare it to Galaxy Edge / maybe also some other high end smartphones which apparently on current android version have some gaming performance and power saving services which decide which apps should get more power(and fail badly in case of ppsspp).
 Apple could simply introduce similar solution for exactly same problem which all of those new higher end smartphones have - overheating.

 Fixing this on android is fairy simple - uninstall/disable the problematic functions. Unless there's some new functions to request more power, probably nothing can be done on ppsspp side. The reason running other apps in the background helps is simply because they add extra weight and OS has no choice, but to switch to performance mode, don't think it has anything to do with JIT since then other apps would not affect it.

**Comment by Orphis** [comment]
Silly question, do you have "low power mode" enabled?
When doing your tests, are you connected to power or using battery?

**Comment by iOS4all** [comment]
@Orphis it's not silly at all. Anyway to answer. Yes we have low power mode but when I'm never enable it when I using ppsspp.
My tests are different (I mean sometimes connected to the power and other times on my battery. But it all gives the same result.

I could prevent that micro stutter from two method that's I took it from other guy here.
1- using cydia download method.
2-connect my iOS device to TV.
We really hope to could get a permanent fix.

**Comment by hrydgard** [comment]
So how's the micro stutter in recent builds? Of course, you do have to run with IR interpreter, but at least for some games it should be fast enough to notice whether it's there.

**Comment by iOS4all** [comment]
@hrydgard hi there. I tested both my iPad Air 2 on iOS 9.3.3 and iPhone 7 plus on iOS 10.1.1 and the micro stutter still there.

BTW the JIT also works and can be selectable. But as I said the micro stutter still there.
What do you think about implementing an old JIT or just see its code to see the difference between it and the new one. I'm sure you'll notice something important to could match between them in order to get a solid fix.

**Comment by hrydgard** [comment]
I noticed that if I make a 32-bit build, it works again, yes. Working on fixing the 64-bit JIT, which will probably be a little faster.

**Comment by iOS4all** [comment]
Good luck with that. BTW if you fixed 64-bit JIT did this will fix the micro stutter as well?
Because this is our big issue on all iOS devices. If you could fix that issue we'll be very thankful and we don't want anything more. Because iOS devices are strong enough to get 60fps in games without any drop in speed at all. I said that because I personally stayed on jailbroken iOS 8.4 for long time and still remember how was fast and all games are running in the fullspeed without any issues even with my old iPhone 5s. So that's why this issue (micro stutter) is ugly and killing our enjoying of playing.

**Comment by Anuskuss** [comment]
>**iOS4all (02.01.2017)**
 I also remember my brother's iphone 5s when its on iOS 8.4

> **iOS4all (26.01.2017)**
I personally stayed on jailbroken iOS 8.4 for long time [...] with my old iPhone 5s.

We all know that you're @Fadi5555 and you've been banned from several other repos for simply spamming the same issues over and over again. @hrydgard is not dumb and he understands what you're ~saying~ trying to say without repeating it multiple times. Please let him do his thing and even if he decides not do anything about it, it's his work and you should appreciate everything he has done for PSP emulation.

**Comment by iOS4all** [comment]
Even if I'm fadi what do you want? I'm never tell him to do it very quickly or rush I always said take your time. Also I know you you You have been banned from Twitter to use bad words and always attack people who disagree with you I still remember you. You feel so bad with me because you have been banned because of my report to you on the Twitter. I know you still a child and see all people like your enemies. So please stop fighting and stop following people only to said bad word to them in order to feel satisfied to yourself. Free yourself from this before killing you.
This just an advice.

**Comment by Anuskuss** [comment]
I don't wanna to pollute this issue like you already did several times (by repeating the same phrases over and over) but I don't have a Twitter account and you should first learn some manners and proper english before releasing the nonsense out of your brain. This is the third issue you have opened about the exact same problem and this is only going to make it harder for the maintainers to keep track off, little kid.

**Comment by iOS4all** [comment]
It's normal to said that no one can say I'm a killer take me to the jail.
Now you're here to do like what you did on the Twitter only to attack people and fight who you don't like. I Knew I should not tell you to stop fighting there but this is was my only fault. Anyway I'm sorry if didn't like my advice about fighting people. so please be behavior here and don't said something not related to this issue. If you are the creator it should be another story. So please be silent.

**Comment by Anuskuss** [comment]
I hope this never gets fixed, you cry again in your nursery and create another issue in a month under a different name. This is my last word on this since I don't want to deal with an autistic person right now and want to let **hrydgard** to do his thing.

**Comment by iOS4all** [comment]
Oh finally you finished your war. You always said I'll never deal with you and you already said many things related to you an empty brain. Poor thing.

**Comment by LunaMoo** [comment]
Ok let's stop this BS. This is not a forum.

**Comment by iOSSOi** [comment]
Any news on this issue?

**Comment by unknownbrackets** [comment]
Using the profiler on an iOS device, it looks like there's clear signs of CPU throttling.

What you see is a pattern like this for FF4 with frameskip 1, no vertex cache, and non-lazy texture caching (game runs at native 60fps):

1. Game runs well, and everything is decently under the 1/60s barrier even.
2. You see frame time go up in steps, until it hovers near double the 1/60s barrier, so around 1/30s (game still appears to run at "full speed" since using 1 frameskip.)
3. After a little while, Flush time spikes.  Usually other times, like jit, also spike at this time.
4. Next there's a gap, where less time is spent on everything.
4. You hear very noticeable audio stutter and then the performance improves (goto 1.)

However, that doesn't specifically explain the spikes, which usually (but not always) last for a single frame.  It's not clear if these are a result of throttling, but it seems like they aren't.

With lazy texture caching on, it mostly stays about 15% above the 1/60s barrier.  With those settings, the spikes don't quite reach 1/30s, so it runs smoothly without the above pattern.  However, the spikes still occur - and likely contribute to microstutter.

It's also not clear if it stops at 15% above 1/60s in the second case because of max throttling.  It probably does, or else there must be a reason for it to throttle the clock even lower when there's more cpu usage.

-[Unknown]

**Comment by ijion** [comment]
The iOS buildbot  never update since 1.42 in cydia repo,but there's a guy upload one 1.54-336 IPA file in #10509,build for nonjailbreak iOS 64,I tested it in jail broken iOS 10,jit works fine,and it seems can use enough power of CPU ,no need of that weird way in #10511,which means speed up!?

**Comment by iOSSOi** [comment]
I can confirm the that the the micro stutter is gone. Games always runs at full speed. Even the heaviest scenes in the game dont drop. I switched on so the FPS are visible and changed JIT to IR interpreter. The games are running at 5xPSP.

Devices: 
iPad Pro 12.9 2017(gen 2). iOS 11.2.5 Beta 5
IPhone X iOS 11.2.5 Beta 5

Games: 
Final Fantasy Type-0
Ys Seven
Wipeout Pure

The are no micro stutters at all. I Tested a scene in i wipeout where i know for sure that the micro stutter appears, i even used my slow motion video rcording at 240fps on my iphone filming the ipad. I can confirm no more micro stutters. But somebody needs to test on slower devices like the iPhone 5s.

I can provide the ppsspp ipa file if necessary, just let me know.

**Comment by iOS4all** [comment]
Please can you give me link to test it on my iPad Air 2

**Comment by unknownbrackets** [comment]
Sounds like this might be fixed now, or at least modern iOS devices are throttling differently.  Going to close this.

If you're still seeing this issue, and believe it has the same behavior (see https://github.com/hrydgard/ppsspp/issues/9197#issuecomment-354582384), then please comment and we'll reopen.  If you're seeing a new issue that wasn't present before, please open a new issue.

-[Unknown]
