### ISSUE TITLE
W^X JIT on Raspberry Pi 2 (Regression?)

### ISSUE THREAD

**Issue by Anuskuss** [hrydgard/ppsspp#9229]
**Device:** Raspberry Pi 2
**Version:** Libretro PPSSPP `v1.0.1` | PPSSPP `v1.3-329-g59d80a3`
**Game:** Yu-Gi-Oh! GX - Tag Force 2

Since the new **W^X JIT** was implemented, I get a huge slowdown when loading a new duel in **Yu-Gi-Oh! GX - Tag Force 2**. On the **Raspberry Pi 2** it's like 2 seconds and I can even feel it on my old PC.
Beforce the new JIT (testing with the Libretro Core v1.0.1) there's no slowdown at all. I think @hrydgard mentioned that there might be a slowdown when new data is accessed.

Is there an option or flag to get the old JIT back and if not, should I just get a version without the new JIT? Will I miss some Raspberry Pi specific fixes/enhancements if I use, lets say, `1.2.2`?

Either that or fix **Yu-Gi-Oh! GX - Tag Force 2**, but I do think that it is more of a weak CPU problem.

Cheers

**Comment by LunaMoo** [comment]
Don't compare PPSSPP to libretro, we don't deal with third party hackish builds here, also how did you even get to a conclussion it's fault of the "new W^X JIT"? It really can't be since that's only enabled for iOS(which is the only platform that needs it).

 If all you did was comparing to some horribly outdated, broken and hackish version more likely than not the game is using some previously not emulated graphic effect which is too slow for pi devices(since they were never ment for gaming and are as slow as low end smartphones). Try disabling slower effects in graphics settings and it will run(and look in case of glitches) as it was before.
 Chances are it's some other effect which can't be disabled aka is not even considered heavy, yet pi's just too slow or you're using graphic enhancing or some other features of ppsspp which third party hackish versions might not have, it also might force some game breaking, but popular - speedhacks which will never be on by default in actual ppsspp(few might even be completely removed in the future ~ wishful thinking;p).

 Also  if you so sure it's cpu emulation messup and you want to help, you should find which commit started the performance drop. Guessing is not an option - you can check PlatformIsWXExclusive() ~ no platform aside from iOS uses W^X ~ unless your RPi2 magically runs iOS, it can't be affected by it.

**Comment by Anuskuss** [comment]
@LunaMoo I appreciate your answer, really, but I somehow got the feeling that your comment has a slight passive-aggressive undertone to it. I'm still a beginner and still have stupid question, but I'm working on it.

My wrong assumtion is based on an old comment **hrydgard** made:
> No numbers, but there should only be a difference when it's compiling new code, which mostly happens when you enter new levels or do new things. We have to do some extra memory operations to un-write-protect and then write protect the generated code in this case. I'd expect possibly very small stutters when you enter a new level and then no difference to the old JIT.

Pair that with the fact that I only get slowdowns when I *start* (load) a new duel, and you can understand my conclusion.

I will try to bisect until I get the commit, but compiling on a Raspberry Pi 2 is very slow and I don't know a way to make it faster. Will report my results.

**Comment by LunaMoo** [comment]
There's nothing passive nor specially agressive for that matter in not liking hackish, third party builds mentioned as a comparison, it really is just pointless.

 Loading different stage/mode in game also doesn't really point at anything by itself, JIT might be a favourite thing to blame despite ppsspp cpu emulation almost never being a bottleneck, graphic emulation on the other hand - most of the time is, often by bad graphic drivers through(aka wasting lots of cpu power).

 When it comes to RPi the only known weird slowdown that was affecting it AFAIK was related to constantly writing some files, it was fixed some time ago.

**Comment by hrydgard** [comment]
It's hard to say without investigating in detail what the real cause might be. A bisect might help. W^X should not be enabled on your raspberry, so I don't think that's the cause.

**Comment by Anuskuss** [comment]
Sorry again for the misleading title. Compiling on Raspberry Pi was a pain in the ass and I figured that I can live with the slowdown since the new versions have more benefits than downsides.

**Comment by hrydgard** [comment]
Well, if load is that much slower, it might still need some investigation. The cause is likely not what's in the title, no :)
