### ISSUE TITLE
[Report] Hardware Tessellation test on android failed.

### ISSUE THREAD

**Issue by xebra** [hrydgard/ppsspp#9234]
Just simple report.
I tried auto-built v1.3-321-gce2feb2 but it's failed with Hardware Tessellation.
I hope to fix it but I don't know how to fix and debug with android.

Tested bezier in pspgl on ZenFone 5(Android 4.4.2)

![screenshot_2017-01-25-05-13-38](https://cloud.githubusercontent.com/assets/1607422/22273572/dbcb90ae-e2e4-11e6-88c6-79be8bacaa97.jpg)

**Comment by zminhquanz** [comment]
you can install aLogCat to view debug logging
https://play.google.com/store/apps/details?id=org.jtb.alogcat&hl=vi

**Comment by xebra** [comment]
@zminhquanz Thank you for the information. I'll try it later.

**Comment by xebra** [comment]
Hmm, I don't know how to use this app...
I want to find ppsspp's log of developer mode. Where can I find it?
I don't know about android well...

**Comment by zminhquanz** [comment]
@xebra enable debug logging in tools -> developer

**Comment by zminhquanz** [comment]
i don't know how to tell you to understand , wait @hrydgard going to tell this

**Comment by LunaMoo** [comment]
On android everything(this means other apps as well) logs to one place and there are apps which you can use to read it directly from your phone or it can also be read on pc. Last time I had to check a shader I used "CatLog" app, note you don't have to(nor want to!) change any logging options in ppsspp to debug a shader, debug log will not give you anything more since shader errors are very verbose already and would just spam the log.

 Just run ppsspp, run your test app to fail a shader compilation / hardware transform, then pause, press home button and launch the CatLog app to read logs, you can pause logging in it and filter the results for NativeApp which will show you ppsspp logs hiding everything else and hopefully expose some useful errors.


 General problems with shaders on android are dumb drivers with very poor compilers. This means 2 things:
 - your code has to follow exact glsl specs without any shortcuts, it's likely impossible to test on pc since even shaders tested with official glslangValidator can fail on mobiles due to bugs or other weirdness:|,
 - it also means shaders has to be optimized by hand if you care about optimizing them because mobile compilers will not do that, they'll just literally just eat what you feed it with and produce s... ;]
 - some older gpu's can just fail to compile shader based on it's size;p.

 Checking http://report.ppsspp.org/logs/kind/39 newer errors seems to be related to tesselation. And ugh lots of them, but most seems to be just dumb int/float conversion/overload functions which is exactly something that desktops drivers will interpret correctly, but doesn't really follow glsl specs where you have to cast ints into floats etc. by hand for example if function expects (float, float), something like (1, 2) is incorrect, but interpreted on pc's just fine, for mobiles we have to  (float(1), float(2)).

**Comment by hrydgard** [comment]
Or just 1.0, 2.0. Looks nicer.

**Comment by LunaMoo** [comment]
Yeah, I was giving an example in case of variables.:3

**Comment by xebra** [comment]
@LunaMoo Thank you so much for your explain with details. I understood a little about android system.

> General problems with shaders on android are dumb drivers with very poor compilers. This means 3 things:

Hmm, I think it's very hard to fix them. If I could fix it on my device, but others...
Anyway, I appreciate your help :)

BTW, I'm implementing this on DX9 but still something a little buggy...

**Comment by hrydgard** [comment]
If necessary we can just turn off the feature on Android, or whitelist certain devices.

**Comment by xebra** [comment]
Yeah, you right.

**Comment by LunaMoo** [comment]
Would be much easier if there was a tool that simulate the awfulness of mobile gpu drivers on pc.
 [Khronos reference compiler](https://www.khronos.org/opengles/sdk/tools/Reference-Compiler/) is so far best tool I tried to debug glsl code aka fails to compile most stuff written for pc's. Can just save a shader to a file and run it through this compiler to catch most problems, but from my experience with post process effects it unfortunately still can pass stuff that doesn't work on smartphones.

 And yeah I would be for just disabling it there as well. People are excited by "hardware tesselation" for various reasons primary being the screenshots comparison showing fps difference and missunderstanding caused by it. This isn't free speedup, it shifts heavy work from cpu to a shader - really nice for most typical pc's, gles devices however are nowhere close:].

**Comment by brujo5** [comment]
Work great in my galaxy S6

**Comment by LunaMoo** [comment]
So you actually checked game which uses this code or the test homebrew?

Meanwhile I found a way to reproduce the problem on pc;p linux under virtualbox - yay for poor gpu/drivers.

Log from test homebrew:
```
51:02:871 user_main    E[G3D]: GLES/ShaderManagerGLES.cpp:73 Error in shader compilation!

51:02:875 user_main    E[G3D]: GLES/ShaderManagerGLES.cpp:74 Info log: 0:92(18): error: `gl_InstanceID' undeclared
0:92(14): error: no matching function for call to `mod(error, int)'; candidates are:
0:92(14): error:    float mod(float, float)
0:92(14): error:    vec2 mod(vec2, float)
0:92(14): error:    vec3 mod(vec3, float)
0:92(14): error:    vec4 mod(vec4, float)
0:92(14): error:    vec2 mod(vec2, vec2)
0:92(14): error:    vec3 mod(vec3, vec3)
0:92(14): error:    vec4 mod(vec4, vec4)
0:92(10): error: cannot construct `int' from a non-numeric data type
0:93(11): error: `gl_InstanceID' undeclared
0:93(11): error: operands to arithmetic operators must be numeric


51:02:876 user_main    E[G3D]: GLES/ShaderManagerGLES.cpp:75 Shader source:
#version 130
#define lowp
#define mediump
#define highp
attribute vec3 position;
attribute mediump vec3 normal;
attribute lowp vec4 color0;
uniform mat4 u_proj;
uniform mat4 u_world;
uniform mat4 u_view;
uniform vec3 u_lightpos0;
uniform mediump vec3 u_lightatt0;
uniform mediump vec3 u_lightdir0;
uniform mediump float u_lightangle0;
uniform mediump float u_lightspotCoef0;
uniform lowp vec3 u_lightambient0;
uniform lowp vec3 u_lightdiffuse0;
uniform lowp vec3 u_lightspecular0;
uniform vec3 u_lightpos1;
uniform mediump vec3 u_lightatt1;
uniform mediump vec3 u_lightdir1;
uniform mediump float u_lightangle1;
uniform mediump float u_lightspotCoef1;
uniform lowp vec3 u_lightambient1;
uniform lowp vec3 u_lightdiffuse1;
uniform lowp vec3 u_lightspecular1;
uniform vec3 u_lightpos2;
uniform mediump vec3 u_lightatt2;
uniform mediump vec3 u_lightdir2;
uniform mediump float u_lightangle2;
uniform mediump float u_lightspotCoef2;
uniform lowp vec51:02:878 user_main    E[G3D]: GLES/ShaderManagerGLES.cpp:845 Shader compilation failed, falling back to software transform
```

So mod() fails and expects floats since as with my edit above integer math requires GL_EXT_gpu_shader4, so that's one thing we need to check and enable. Not doing that could probably be the reason why it failed for the person with nvidia gpu on win 10 reporting in merge thread. Another problem is gl_InstanceID which requires gles 3.00 or if someone really cares, it could also work on older iOS with some [apple stuff](http://stackoverflow.com/questions/25387959/instanced-drawing-with-opengl-es-2-0-on-ios), probably not worth.

 Guess both of those could be supported on new higher end smartphones like mentioned GS6.

**Comment by mrcmunir** [comment]
Not working also  in mesa3d 17.0  intel driver Opengl es 3.0 

![screenshot_20170125-091236](https://cloud.githubusercontent.com/assets/1274014/22307830/b5dfbf3c-e398-11e6-967b-f1c904c6d3ec.png)

![screenshot_20170125-091327](https://cloud.githubusercontent.com/assets/1274014/22307844/bfeb2c46-e398-11e6-9f2f-03329be98b7c.png)

![screenshot_20170125-091702](https://cloud.githubusercontent.com/assets/1274014/22307851/c616b572-e398-11e6-84b6-2a52a1c1b470.png)

**Comment by Ar37** [comment]
New build (1.3-388) tested, break some textures in NFS MW and bornout legend

**Comment by mrcmunir** [comment]
In mesa3d intel driver under linux Workaround fix needed Force Compatibility core because by default run 130 GLSL unsuported for gl_instanceID

https://www.opengl.org/sdk/docs/man/html/gl_InstanceID.xhtml

export MESA_GL_VERSION_OVERRIDE=3.3COMPAT 

That function only avaible GLSL 140 and higher

**Comment by xebra** [comment]
@LunaMoo Your cooperation is really appreciated.

> Would be much easier if there was a tool that simulate the awfulness of mobile gpu drivers on pc.
Khronos reference compiler is so far best tool I tried to debug glsl code aka fails to compile most stuff written for pc's. Can just save a shader to a file and run it through this compiler to catch most problems, but from my experience with post process effects it unfortunately still can pass stuff that doesn't work on smartphones.

I didn't know that, I'll try to check it out.

> I was just checking the vertex shader generator code and shouldn't it check for and enable GL_EXT_gpu_shader4? Most of that code seems to need it, we could also maybe disable it for all devices that doesn't support it. There's also gl_InstanceID which requires minimum gles 3.00.

Ah, yes, I forgot it.

> Meanwhile I found a way to reproduce the problem on pc;p linux under virtualbox - yay for poor gpu/drivers.

I was thinking similar situation like Android emulation on Android Studio or something but I didn't realize that. Linux on Virtualbox seems good solution.

> Log from test homebrew:

It's very useful infomation! thanks :)

**Comment by xebra** [comment]
@brujo5 I'm glad to hear your report :) Thanks!

@mrcmunir Thank you for the log and information, it's very helpful for me.

@Ar37 Thank you for testing and reporting.

**Comment by zminhquanz** [comment]
because hardware on mobile is different ( GPU like Mali , Powervr , Adreno ) , and is having problem graphic

**Comment by mrcmunir** [comment]
@xebra you're welcome and also with llvmpipe driver like virtualbox/vmware too work mesa3d based drivers are implemented GLSL 130 you can force Opengl 3.3 with that command :+1: 

![captura de 2017-01-26 05-31-40](https://cloud.githubusercontent.com/assets/1274014/22320081/46f0f94c-e389-11e6-9a88-04cc9b1bad5d.png)
![captura de 2017-01-26 05-29-27](https://cloud.githubusercontent.com/assets/1274014/22320082/46f8f0e8-e389-11e6-9019-48c6d8b458ae.png)

**Comment by xebra** [comment]
I pushed DX9 version(still incomplete).
So I'll try to fix again about GLES.
@zminhquanz @mrcmunir Thanks again for the infomation :)

**Comment by DonelBueno** [comment]
Is it fixed? I don't have a device to test.

**Comment by mrcmunir** [comment]
In my Adreno 305 GPU compile shader Ok I no see any error in the log but has  flickering and glitches errors.

![17 - 1](https://cloud.githubusercontent.com/assets/1274014/22370911/3886c6d2-e494-11e6-9e21-cd5a5b41a1c2.png)

Later try with Mesa3d Opengl es 3.0 if working ok.

**Comment by LunaMoo** [comment]
It still can fail to compile due to to gl_InstanceID.

 For GLES it requires [shader version 3.00](https://www.khronos.org/opengles/sdk/docs/man3/html/gl_InstanceID.xhtml), for OGL [it's 1.40 version](https://www.opengl.org/sdk/docs/man/html/gl_InstanceID.xhtml). On lower versions the feature should be completely disabled.

**Comment by hrydgard** [comment]
Qualcoom (Adreno) is not known for good drivers...

**Comment by mrcmunir** [comment]
Ok well if I wait 30 seconds avg crash libsc-a3xx.so and libGLESv2_adreno.so driver fault 
Let's see if I can capture the log and Upload it..

**Comment by Abz1** [comment]
@hrydgard i thought newer adrenos are better?

**Comment by xebra** [comment]
Thank you all :)
@mrcmunir I have same gpu but it crashes when loading pspgl bezier.
However, PuzzleBobble worked fine, but second time run the game, it does not draw nothing about bezier. Maybe, it's shader cache issue, I think.

@LunaMoo Thank you for detailed information for fix this.

**Comment by hrydgard** [comment]
@Abz1 They are, but from what I understand their shader compiler is still not exactly the best.

**Comment by hrydgard** [comment]
Now that #9249 is solved, did any of this start to work? :)

**Comment by xebra** [comment]
@hrydgard In my zenfone5, it can run only PuzzleBobble. Bezier in pspgl can not run because it crashes the app when starting.
Anyway, building issue and shader cache issue fixed, closing this thread.

**Comment by mrcmunir** [comment]
@hrygdgard with Adreno device not work anywat is driver fault maybe need disable in Adreno 3xx series? In blacklist series v84 driver .

**Comment by brujo5** [comment]
Why Tessellation is disabled in my galaxy s6?

I didn't experience any issue before.

Some user have problem with old mali400 but my device have mali t760 mp8 with sles 3.1

**Comment by hrydgard** [comment]
@brujo5 Sorry about that, the compatility check simply needs to be refined. @xebra  ? :)

**Comment by mrcmunir** [comment]
Also happen in mesa3d driver too not are avaible now with Opengl 3.3 GLSL .

**Comment by LunaMoo** [comment]
@brujo5 did the v1.3-450-g052660b worked for you? (the last build before compatibility check)

 I think it shouldn't, but instead being disabled it would probably break since Mali t720 doesn't have(?) [OES_texture_float](https://www.khronos.org/registry/webgl/extensions/OES_texture_float/) and it became a new requirement from some earlier changes. At least that's the only thing listed as required which seems to be missing on [SGS6](http://opengles.gpuinfo.org/gles_generatereport.php?reportID=664).

**Comment by xebra** [comment]
@brujo5 @mrcmunir Thank you for reporting, I tried fix the issue.

**Comment by xebra** [comment]
@hrydgard @LunaMoo Thank you for supporting me :)

**Comment by xebra** [comment]
I tried to fix it but it's not fixed yet.
So reopen this.

**Comment by mrcmunir** [comment]
@xebra yep , I found for mesa3d drivers the fault is check for EXT_gpu_shader4 never can't supported and working without that function with GLSL compatible

**Comment by xebra** [comment]
@mrcmunir Oh, I just found same issue when I checked all extensions in my zenfone5.
I'll fix it soon.
