### ISSUE TITLE
Texture replacement and dumping not implemented [Qt]

### ISSUE THREAD

**Issue by Royal-Jelly** [hrydgard/ppsspp#9259]
I understand you have other priorities and sorry if this come off  as rude in anyway but, why you would leave this feature unimplemented for linux? 

It would save a hell of alot of time if I didn't have to constantly move files over usb to my phone just to test textures, *pouts in corner* i guess I'm just tilted because this feature is implemented for android but not linux.

anyways im not all that upset, just trying to be humorous and thanks for your time ~ Royal-Jelly

**Comment by hrydgard** [comment]
I didn't even know this feature wasn't implemented in Linux. It should work. What problems do you have using it?

**Comment by LunaMoo** [comment]
Seems to work fine here, tested using LXLS distro(based on ubuntu LTS) under Virtual Box with SDL build of ppsspp.

 The only bothersome things about linux version/differences from windows I experienced soo far is lack of drag&drop support and the folder ppsspp saves it's files is hidden by default(home/username/.config/) and the latter I think might be the problem here;p.

**Comment by hrydgard** [comment]
Yeah the latter one is a pain..

**Comment by Royal-Jelly** [comment]
*Pats LunaMoo on the back* you know something you just reminded me that there was an SDL build .... I have been using the QT build for a while now *facepalms* and everything works with the SDL build ~ wellp I probably would have never noticed so thanks for helping me out ~

**Comment by LunaMoo** [comment]
Ah, Qt needs to use different libs or something to deal with png's and nobody worked on it;p. Well let's start by renaming the title.

**Comment by unknownbrackets** [comment]
I believe this is implemented now, see #13514 and #13561.  Now we just use libpng everywhere.  Closing.

-[Unknown]
