### ISSUE TITLE
PPSSPP  parou de Funcionar

### ISSUE THREAD

**Issue by moura464** [hrydgard/ppsspp#9271]
![dasdqeqeq](https://cloud.githubusercontent.com/assets/22099440/22532840/30d6e520-e8d1-11e6-8115-02f016ef52eb.png)

**Comment by araujoigor** [comment]
@moura464 Can you give any information on how/when it happened? Does it happen often?
Please add some info in your issues. 
Can you give information about this one here? Could be in Portuguese if you prefer then I translate it.

**Comment by moura464** [comment]
brasil Portuguese SIM

**Comment by unknownbrackets** [comment]
Does this still happen?

I think it's saying that you ran out of video memory.  This could mean your settings are too powerful.  It could also be a bug.  It might be fixed already.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
