### ISSUE TITLE
Decreased performance on better hardware (Android) / Forum problems

### ISSUE THREAD

**Issue by darro87** [hrydgard/ppsspp#9272]
Hey, long time user. Really appreciate the work.

I use this emulator on android boxes primarily, and specifically upgraded from an Amlogic s905 box to a s912 box (both have 2gb RAM) to squeeze out a little more performance from this emulator. To my dismay however, games that work more or less smoothly on my s905 (Burnout Legends is a specific example), run noticeably worse on the newer device (I have matched the settings exactly, and further to this, actually freshly experimented with all new settings but could never reach the same level of performance as the older box, even if I drop all the settings to lowest).

Any ideas as to why? I know you're probably busy and this may be a minor isolated incident, but it's just strange to me, and it would be super cool if you could share any thoughts as to why :(. I have posted the core specs of the 2 systems below for comparison:

**Amlogic S905**
Android 5.1
CPU - Quad core Cortex A53 @ 1.536 GHz
GPU - Penta-core ARM Mali-450MP [Click here for specs](https://www.arm.com/products/multimedia/mali-gpu/ultra-low-power/mali-450.php)

**Amlogic S912**
Android 6.0.1
CPU - Quad core Cortex A53 @ 1.536 GHz + Quad core Cortex A53 @ 1.0 GHz
GPU - ARM Mali-T820MP3 [Click here for specs](https://www.arm.com/products/multimedia/mali-gpu/high-area-efficiency/mali-t820-t830.php)

Lastly, I can't create an account on the forum. It tells me: The image verification code that you entered was incorrect. Please enter the code exactly how it appears in the image.

Problem is, there's no image verification on the page, so I'm stuck (tried different browsers).

Any comment on these things would be epic. Keep up the good work all!

**Comment by LunaMoo** [comment]
This is an issue tracker, not a forum for support questions, I think I'll keep this open through and just rename it to "Forum problems" since @hrydgard is the only one who can help with that.


 As for your problem, the thing is the device you call "better" isn't really stronger, it has newer gpu and exactly same cpu, unfortunately gpu drivers on android tend to be POS and they can affect performance a lot especially in rarely used functions that emulators like ppsspp have to use, so to get actually faster device you usually have to get lucky with drivers.

 Also since your new device cpu uses littleBIG architecture with 2 quad core cpu's, from experience of other people having problems with those I would guess android is just not switching to faster quad when running ppsspp effectively leaving you with much slower cpu. There's usually nothing to do about that on ppsspp side since it's a fault of android power management/performance services that are commonly bad at doing their work with that architecture, if you have root on that device, you can probably find ways to disable those / force higher performance cores if they aren't used.

**Comment by darro87** [comment]
Thanks for the feedback. I understand things a bit more now. I would have prefered to post this to a forum, but since it's broken at the moment, this was the only place I could find that allows me to post. Apologies for that.

I found that the emulator was running on the little cores all the time. Even if I restricted those core speeds to 100mhz max, the application would not use the BIG cores, but instead just crawls @100mhz. I found a way to disable the little cores completely, forcing it to run on the BIG cores, but the performance was the same as when I originally reported the issue, so I guess it's a lost cause from that perspective.

Went a step further and tried it on a s905X box, which has the same CPU and GPU as the s905, except that it runs on Android 6, but the performance was about the same as the s912, so I think it's an Android 6.0 thing, probably related to drivers.

Thanks again for the input, hopefully things improve as time goes on.

**Comment by LunaMoo** [comment]
I think I read somewhere Nougat got better vs Marshmallow, so if you can update to android 7.x probably worth trying, especially since you really want Vulkan drivers;p. I mean ppsspp's Vulkan backend isn't ready for android yet, but someday hopefully will be and then the newer device should gain a lot from it.

**Comment by darro87** [comment]
Noted. The device is a Beelink GT1, and so far it receives regular updates, so I will be on the lookout. Thanks for the advisement.

**Comment by LunaMoo** [comment]
Forum problems seems to be solved now:) ~ closing.
