### ISSUE TITLE
Ratchet & Clank bloom/overbrightness issue on Galaxy S2

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#9288]
Reported by Viper168 on IRC.

On his Galaxy S2, Ratchet & Clank looks like this, which is obviously not right:

![](http://dump.bitcheese.net/files/debyfuw/Screenshot_1999-12-31-19-26-15.png)

**Comment by luizthiagor** [comment]
Hello hrydgard ! I would to inform : I have this same issue on raspberry PI3 ppsspp version 1.5.4 if the "Disable more slow effects (fast)" option is enable .... if i disable this option, screens goes black and has no way to play this game ...... Otherwise, same problem occur with other games of "High Impact gamers (same producer) like Jak and Daxter .....

**Comment by unknownbrackets** [comment]
The image is missing.  Is this still an issue?  Can we get a GE frame dump?

-[Unknown]

**Comment by ResurrectionRedmi9** [comment]
Galaxy S2 GPU is Mali-400 is also problematic on ppsspp. Maybe related to https://github.com/hrydgard/ppsspp/issues/11598?

**Comment by Gamemulatorer** [comment]
Where is the part that this game is too much bloom?
![Screenshot_2021-09-14-19-08-37](https://user-images.githubusercontent.com/37603562/133247093-6408d7b1-5dca-4bcf-9b85-991ec1ac8b68.png)
Mali-450 GPU

**Comment by unknownbrackets** [comment]
That's #6105.  If there's no overbloom issue, maybe this should be closed.

-[Unknown]

**Comment by Gamemulatorer** [comment]
> That's #6105. If there's no overbloom issue, maybe this should be closed.
> 
> -[Unknown]

Yes no overbloom  as I play this game on my mali-450 gpu.
