### ISSUE TITLE
Screen Flicker when using OpenGL Fullscreen

### ISSUE THREAD

**Issue by Clevername02** [hrydgard/ppsspp#9303]
I have 2 monitors.  If I run PPSSPP in fullscreen with OpenGL backend and drag a window from my 2nd monitor to the monitor with PPSSPP on it the whole screen flickers several times.  If I use Direct3D backend there is no flickering, I can drag a window on top of it without issues.

I believe this happens because under OpenGL ppsspp runs in exclusive fullscreen mode, but under Direct3D it runs in a borderless window.  

If you don't have 2 monitors you can test this by alt tabbing out of ppsspp while in fullscreen.  In Direct3D alt tabbing is instant with no flickering.  In OpenGL it flickers before switching windows.

I tested it on this revision: v1.3-554-g9dd3e18

**Comment by LunaMoo** [comment]
PPSSPP doesn't support exclusive fullscreen in any of it's backends aka they all are borderless window, it's just that OGL while best and most polished in terms of emulation, in general tends to be buggy under windows.
 So this is probably just some driver issue, or opposite caused by existing workaround for a driver issue like the nvidia crash workaround(affecting all brands) which stops rendering(aka causes a momentary flicker).

**Comment by unknownbrackets** [comment]
I don't experience this exactly, but I do experience something similar.  I think it's just NVIDIA's driver, though.

When PPSSPP is full screen (borderless) in OpenGL or Vulkan, switching focus to an app on my other monitor makes it flicker black.  Focusing back flickers again.  This doesn't happen in Direct3D 11 (I didn't test 9, but probably the same.)

We do have a workaround to stop rendering on Intel when minimized.  But it shouldn't activate here.

FWIW, calling `ChangeDisplaySettingsW` with `CDS_FULLSCREEN` does nothing to prevent this flickering.

If this is NVIDIA only, I suspect there's not much we can do about it...

-[Unknown]

**Comment by benderscruffy** [comment]
does this  still happen 
is it a driver issue ??

**Comment by hrydgard** [comment]
I would guess it's a driver issue, hopefully long resolved.
