### ISSUE TITLE
Nascar 07 and DTM Race Driver

### ISSUE THREAD

**Issue by fuentescg** [hrydgard/ppsspp#9339]
Hi, there´s still the same graphical glitches on both games. Anyone had news about that?. Sorry for my english, i´m from Argentina. 

Thanks.

**Comment by LunaMoo** [comment]
This place is to report unknown issues eventualy for requesting features, not to ask why things aren't fixed yet nor asking when they'll be fixed, noone can answer that.

 We also don't want a duplicate issues it creates a mess and makes things harder to track, closing since those problems are already listed in #6583 and #5001.

**Comment by fuentescg** [comment]
So, where are the rules of the site to read them. Also, I don´t want it to be repaired right now, I just wanted to know if there was news of where the bugs were, These glitches dated about 2 years ago and with the new versions that were coming out, the errors are still the same. I could not find where the error is in the code and so I do not know how to repair it. So you don´t have to be rude.

**Comment by LunaMoo** [comment]
Use common sense, this is an issue tracker, a place where problems are listed for anyone who likes solving them to pick whatever they want to work on. There are far more problems than people interested to work for free and even less those who in addition to it will spend their money to buy games they don't own and might not even like just to try solving some problem.

 In other words there will always be problems nobody will pick and even if someone does, there's no guarantee they will be able to solve them, doesn't matter how many years passes, this is just a hobby not work and if some issue is too hard to solve properly or annoying to even debug or if it affects some game you have no interest in wasting money on you'll just work on something else and the issue will await forever until someone like you who really likes one of the broken games, learn how to program, learn how to debug psp games and eventually fixes the problem. Or until fix for other game happens to affect it by accident as that's probably more likely:].

 Take your time to digest that without going emotional and oversensitive, because I wasn't and still aren't rude. Quite the opposite I just wasted another 5 minutes of my time to hopefully give you better idea why I close duplicates and why it's really bad place to ask nagging questions.

**Comment by fuentescg** [comment]
Well, you said "This is an Issue Tracker", and i said "I just wanted to know if there was news of where the bugs were". I´m learning  how to program, debug and eventually fix it. Use YOUR common sense.

**Comment by iOS4all** [comment]
@LunaMoo I discovered something important related to JIT. The jailbreak of iOS 10 doesn't patch kernel which is extremely important to get success JIT. I talked to the creator of jailbreak he said the current jailbreak is not patch kernel however he can do it easily.
![img_0062](https://cloud.githubusercontent.com/assets/24762554/23193355/9c887fe8-f8b9-11e6-9aed-e7e309a48e42.PNG)

If you don't mind I want to open an issue about this please. I just want to take your permission please.
Thanks.

**Comment by LunaMoo** [comment]
@iOS4all - despite trying to keep this place clean, I'm not actually from giving permissions, but no, please don't open new issues around iOS JIT, it doesn't help in any way.
 Also the same person(kpwn) already provided information to potentialy fix JIT in PPSSPP in fact he did it in your own issue ~ #9232.

 What we would need is a dedicated iOS developer that would do nothing else but fix JIT on iOS whenever apple updates their system, but we don't have anyone like that ~ so please - learn what being patient means. I'm sure Henrik will eventually do something about it, but nobody likes to work under pressure so you trying hard to make everyone remember about it, likely has an opposite effect.:]

**Comment by iOS4all** [comment]
@LunaMoo All I can say thank you so much for all what you have said. Also thanks for your kindness.
You can't imagine how nice if someone replying like this way without saying something rude.

I finished my thread while ago but I said I must take your permission first. 

The idea is just make other version of jailbreak including patch kernel to match TaiG jailbreak that's it.
So if you let me do that last time just to see. Even if want to close it later just make @hrydgard see it after that it's up to you. I'll appreciate your help a lot.
Thank again.
