### ISSUE TITLE
Texture tiling fix

### ISSUE THREAD

**Issue by ppsspp213** [hrydgard/ppsspp#9341]
Texture tiling artifacts on 2d backgrounds caused by the bilinear filtering when running games above their native resolution.
Street Fighter Alpha3 Max is good example of this.

Possible fix???
http://www.matim-dev.com/texture-packer---get-rid-of-sprite-artefacts.html

**Comment by Hydroque** [comment]
No, no, no. The reason why there is texture bleeding with bilinear, and such, has to do with how pixels are mapped via texcoords and the image. The black cells represent the image pixels. The blue cell represents the texture coordinates and the 'hitboxes' at the center.

The want is that every two pixels is one tile. This tileset is only one tile. What we are actually doing is using a texture coordinate to target the pixels wanting to draw, also respect the precision finickyness of floating point numbers, which are used for vectors.

Since the pixel has to have more than or equal to 0.5 of it captured by the bounding box, you will have to play with offsetting the bounding box to be pixel inclusive. This means some light math. One way of doing this is by using a constant for that specific image size and offsetting the texture coordinate some amount.

Move a fraction of the pixel
```
int tile = 0; // which tile
int width = 2;
int height = 2;

vec2 tile_len = vec2(2, 2);
vec2 pixel_ratio = vec2(1/width, 1/height);
vec2 quarter_pixel_ratio = pixel_ratio/0.25; // off top of head, untested and probably wrongly presented
// but the idea is there

vec2 texcoord = (tile_len * pixel_ratio * pass_texcoord) + quarter_pixel_ratio;
```

**Comment by hrydgard** [comment]
Best solution if you want upscaled graphics in games like this is to use OpenGL and use the 5xBR filter, which forces rendering to 1x and upscales from there in a shader.

**Comment by ppsspp213** [comment]
Using Texture Filtering: Nearest along with Screen Scaling Filter: Linear 
Texture Scaling: xBRZ
Texture Scaling: Hybrid
Texture Scaling: Hybrid+Bicubic 
scale without texture tiling but 
Texture Scaling: Bicubic has texture tiling.

Texture Filtering: Linear along with Screen Scaling Filter: Linear 
has texture tiling but only on the moving textures like the fighting stance at the character selection menu the rest of the 2d background looks fine for all the Texture Scaling options except just Bicubic 
which has texture tiling on both 2d backgrounds and the fighting stance at the character selection menu same with Texture Filtering: Linear.

**Comment by LunaMoo** [comment]
As far as I know and the person I discussed it with confirmed that, all scaling algorithms cause the issue in that game and no wonder since there are only 2 unique ones and the other two are based on them.
 Looking at the example from reports which pretty sure uses basic xBRZ as bicubic looks more severe:
 http://report.ppsspp.org/uploads/ULUS10062_1.00/compat-51312.jpg
 Characters are the only one who are clearly glitched, however look at HP bars, backgrounds(check for example the left side where there's contrast between black sky and the brown thing), Portraits, if you look closely - just about everything which uses tileset for sprites will get glitched.

 The cause for different algorithms is same they mess up edges of every tile, we can't avoid that as that's what those algorithms were designed to do, so just don't use them.

 Other, more modern games might have similar looking problems, but the cause is completely different and there bleeding around sprites is actually helpful, so scaling in opposite to this game, actually tend to hide glitches in those games, most 3D games UI is an example of that.


 As for 5xBR looking bad - yea it takes whole screen as an input and asumes a square of specific size is a "pixel", unfortunately cheap ports of old games, as well as indie games tend to have stretched graphics, what's worse different elements are stretched with different multipliers. so can't just modify the size of "pixel" as each detail would have to be treated differently. The results really only look nice in native 2D psp games that had a budget to go full 480x272 res(AAA quality:3).

 There are however other post process shaders which might be used for scaling, for example GuestAA 4.o with "filtro" setting set to a low value like maybe 2.0 up to 4.0(lower = more blurry) can deal with such weirdly resized graphics quite well and looks similar to scaling filters despite not being advertised as one:]. It however is extremely heavy so I would only use it on desktop pc with dedicated gpu.

**Comment by ppsspp213** [comment]
https://forums.libretro.com/t/reverse-antialiasing-shader/118/17

**Comment by unknownbrackets** [comment]
I think the reasons and workarounds for this are pretty clear - I'm going to close.  If there's a new upscaling shader you want to add to PPSSPP, pull requests are often accepted.

-[Unknown]
