### ISSUE TITLE
God of War Games OGL Graphical Error on RX 480

### ISSUE THREAD

**Issue by RinMaru** [hrydgard/ppsspp#9343]
I got a new computer and everything is updated Im using PPSSPP GIT v1.3-421-gd5d9d87 
I'm using GL backend.  
**UPDATE 2 Only happens in OGL. DX9 & DX11 Does Not present the issue** 

My specs-
AMD RX 480 4GB
Intel i5 6402p 8GB

Everything runs at full speed but both god of war games have some weird stuff going on as you can see
![ucus98653_00000](https://cloud.githubusercontent.com/assets/15071652/23198555/677d1cd2-f896-11e6-9a69-e4441bdba2d4.jpg)

**Comment by hrydgard** [comment]
Very strange, though you might as well use the D3D11 backend, which is available in the latest builds. 

1.3-421 is not very fresh anymore, try 1.3-705 from http://buildbot.orphis.net/ppsspp/ .

Would be interesting to hear if this problem with GL is also present in 1.3-705 - and if it persists in 1.3-421 if you make sure to install the latest drivers from AMD.

**Comment by Hydroque** [comment]
This could be hardware dependent. AMD is really good with compatibility, but can have a few bugs as a result. Try playing with the settings in AMD Catalyst.

**Comment by LunaMoo** [comment]
AMD OGL drivers are still buggy, they just changed from crashing to glitches ~ see bottom of  https://community.amd.com/thread/205702
On older AMD gpu's using 2015 pre-crimson drivers for OGL, works around this, but it might not work with newer gpu's, so yeah D3d11 backend is best option here.

**Comment by zminhquanz** [comment]
AMD driver still buggy

**Comment by Zetchzie** [comment]
I just tried 1.3-705 the error is still present. yes im using the latest Crimson Drivers

**Comment by Hydroque** [comment]
I am still not backing down with what I said with modifying the settings. Your year old thread doesn't say much.

**Comment by LunaMoo** [comment]
That thread I linked states facts acknowledged by AMD themselves and it's not a year old, latest replies are from AMD worker apologizing for the poor situation we are in and those are current and affecting latest drivers from this month. The only reason that thread is still active despite starting few months ago is because it took soo long for them to release the fix... which happened to break stuff again.

 And as an owner of 2 AMD gpu's I can confirm that AMD OGL drivers currently sucks and certainly don't have "a good compatibility". Old drivers on the other hand which I use as a workaround don't have problems here:
 ![ucus98713_00000](https://cloud.githubusercontent.com/assets/5485237/23227378/0c36ebe8-f939-11e6-94b1-14f71f213e2b.jpg)
 but that's not a solution for users of newer gpu's since those don't have older drivers, at least nothing old enough that would work.

**Comment by hrydgard** [comment]
That's one more reason to have the D3D11 backend then, as I presume it doesn't happen on that...

**Comment by Hydroque** [comment]
I have a non-crimson 2007 PC with limited OGL support. I get no graphical errors and everything looks great with the same game. DX9 looks exact. So I guess it is a bug with crimson? Any AMD GPU I ever touched is flawless compared to intel.

**Comment by RinMaru** [comment]
this issue is fixed closing
