### ISSUE TITLE
Bizarre Text Issue

### ISSUE THREAD

**Issue by TheBeverage** [hrydgard/ppsspp#9380]
When playing at 1xPSP text in many games seems to be stretched randomly from letter to letter. Attached screenshots of it in some games, as well as a title screen that looks normal and a settings page. http://imgur.com/a/9ksRp

**Comment by LunaMoo** [comment]
That's not an issue, that's you using nearest for texture filtering. Switch to auto which let's the game work as it was designed.

**Comment by TheBeverage** [comment]
Auto just switches it to linear which results in everything being a blurry mess. This is not just because it's stretched to fullscreen, this appears even in a 1x window.

**Comment by LunaMoo** [comment]
It's blurry mess because the game is a port of PSOne game and stretches everything to PSP display ratio, use original resolution patches if you want.
 You CAN'T stretch any graphics with nearest filtering by non even multiplayers. It's impossible without the artifacts you see that's why game doesn't do that.

**Comment by TheBeverage** [comment]
Here is it scaled at 3x integer scaling by comparison: http://i.imgur.com/W6JOGOP.jpg

**Comment by TheBeverage** [comment]
Here it is with the "linear" scaling from auto: http://i.imgur.com/YanWrZ0.jpg
As you can see even at an integer scaled window size, the text is now blurry.

Here is the only way I seem to be able to get it to look right: http://i.imgur.com/l6wGF23.jpg
This is with nearest scaling, but at a whopping 6x internal resolution. I don't want to run at higher than native resolution because effects/models will look out of place, but this is just to show how it *should* look in the first place. I don't understand how the text is being garbled when all the other assets are scaling up just fine, I have to assume some sort of filter is being applied that doesn't need to be.

**Comment by LunaMoo** [comment]
When you're rendering at higher resolution, the artifacts simply become less visible at some point even disappear, it's not magic. Let's say you stretch some textures by 1.5 multiplier, with linear it becomes blurry, with nearest it will randomly force some "pixels" to be wider than others. That's how nearest filtering works and you can't jump around that, there's nothing to fix here.

 No, the game should not look like on your screenshot. The game was same blurry on PSP and like for some other PSOne ports to PSP, people made original resolution patches which un-stretch the game and display it properly. If you want, just use those, don't expect for forcing nearest filtering to work on stretched textures in x1 res with PSP display ratio. The only reason we even have such option is because many native psp games use linear filtering on 1:1 textures and forcing nearest will work fine on those.

**Comment by TheBeverage** [comment]
I guess my confusion stems from this: http://i.imgur.com/KHzNAE5.jpg
Other games (Final Fantasy III here) seem to scale quite well using my low-res settings. But it's also not a Tactics-specific issue, Disgaea also suffers from the same issues. I understand that nearest scaling causes issues but those should be negated running a game at an integer scale, no?

The problem with that explanation in Tactics is it's *only* an issue with the main text. All other textures and assets look perfect. And even then, it doesn't explain the issue with other games like Disgaea. I guess I'll have to run at the super high rendering resolutions and just hope my computer can handle it as that seems to be the only way to fix the issue.

**Comment by TheBeverage** [comment]
Oh, I didn't see your edit. That makes more sense then! Sorry it wasn't adding up for me earlier, appreciate the patience.

Is Disgaea suffering from a similar issue?
Here is with linear: http://i.imgur.com/wpdutGL.jpg
Here is with nearest: http://i.imgur.com/7nsVDkM.jpg
It seems to have the same sort of text scaling issue.

**Comment by LunaMoo** [comment]
Well there are different ports, some better than others.
 Disgaea was ported from PS2 which also had 4:3 pixel ratio, but it's not a fully 2D game and doesn't involve nasty stretching for everything. I think in this case PS2 version also had a blurry UI(althrough at probably higher res), so it could be a design choice, not a lazy port.
 As mentioned earlier native PSP games also might choose to use linear where it's not required and might look bad by design.

**Comment by TheBeverage** [comment]
Alright, makes sense. I patched Tactics and it looks great. Thank you for the help!

**Comment by LunaMoo** [comment]
You're welcome.;3
