### ISSUE TITLE
Midnight Club flickers when using the JIT on OS X

### ISSUE THREAD

**Issue by montajd** [hrydgard/ppsspp#9398]
Recent versions of dev-latest and dev-working PPSSPP have constant flickering or just black screen with JIT enabled. Example game: Midnight Club LA Remix. Right after hardware tessellation was introduced, the first build bot version (or two) worked fine, but since, if in-game doesn't flicker, its just black, and can't even get back to PPSSPP settings. Even the dev-working version is doing the same thing. Tried deleting ppsspp.ini, and does not fix. When using IR Interpreter the game loads and works fine, but of course is extremely slow. Can someone at least  post a version of the last PPSSPP version for OS X that isn't broken? Also noticed in-game with PPSSPP for iOS, constant flickering of on-screen controls upside down on screen, and this has also been happening with versions from the past couple months.
I have tried every combination of settings, turning on and off, testing and testing, and nothing.

Macbook Pro, El Capitan 10.11.6, PPSSPP v1.3-807-g150619c
iPhone 7, iOS 10.1.1(JB), PPSSPP (gave up and uninstalled)

**Comment by hrydgard** [comment]
Don't need that angry tone, it's not easy to keep 5 platforms all working perfectly while reworking the fundamentals of the emulator. I can't fix everything at once.

That said, I just did a fresh build for my Mac and it seems to work fine. Did you try resetting settings to default?

**Comment by montajd** [comment]
Definitely not an angry tone at all, sorry if it sounded like that. Just wanted to make sure I covered everything I've tried and experienced. I just completely deleted the entire PSP folder from the .config folder and still the same issues. Not sure if it matters, but my Mac is an early 2011 Macbook Pro 17" i7 with AMD Radeon graphics.

**Comment by hrydgard** [comment]
Just found and fixed the instacrash bug of the iOS build.

Now, for the Mac one, it's definitely not the JIT that's broken, no idea why you put that in your title.

**Comment by montajd** [comment]
The reason I believe that JIT maybe messed up is because the game runs fine with other interpreters, no flashing/flickering/black screen. I just tried SSX on Tour (with JIT enabled), and ran without issue. Then I tried Midnight Club LA Remix, and Midnight Club Dub Edition Remix, and both flicker and go to black screen after in-game menus. Maybe it has something to do with games that require buffered rendering?

**Comment by hrydgard** [comment]
But the JIT is exactly the same as on the other platforms, works on my machine, and hasn't changed recently, while the framebuffer management code has been partly rewritten...

**Comment by montajd** [comment]
https://youtu.be/DGeWP4RAK8Y

Here's quick screen capture. I reset PPSSPP right before I recorded it (aside from adding my game library)

**Comment by unknownbrackets** [comment]
If you're able to download Xcode (it's a big download, but it's from Apple and it's free - found in the Mac Store), there's a few files you could edit to verify for sure whether it's jit or not.

We could also go back to the version where it last worked, and validate what changed to break it.

For example, a possibility is that the flicker has to do with how fast the game is running.  Since jit disabled is so much slower, it may prevent the flicker, even though jit isn't actually the cause.  Of course, this is just one possibility

This would require compiling PPSSPP on your Mac, but that can just involve you pasting a few things and telling us how it goes.  Since you're experiencing the problem and have the game it happens in, you can most easily reproduce it - and most easily expose the bug, too.

-[Unknown]

**Comment by ijoinit** [comment]
How about setup a windows system so that make it double platform on your mac as it's perfectly running  on windows to play at home.

**Comment by seadil** [comment]
I've just tested Midnight Club 3: DUB Edition on the latest DEV-Version. The flicker occurs only on the main menu, ingame there seem to be no issues.
System: MacBook Retina Late 13, El Capitan 10.11.6, PPSSPP v1.3-812-g9f17c7f

@unknownbrackets 
How to debug it in Xcode?

**Comment by montajd** [comment]
Just tried the Same dev-latest and still same issues. Very strange. What are your settings? Everything was working fine until a month ago. As for the recommendation for loading windows, I do have a bootcamp partition with windows 7 on it, and I had similar issues. Just to clarify, I have a Macbook Pro Early 2011 17" AMD Radeon HD 6750m graphics

**Comment by montajd** [comment]
https://youtu.be/ErzkoznBm7c better video

**Comment by unknownbrackets** [comment]
## Step 1: Setup Xcode

Install Xcode from the Mac Store, and then follow these instructions to get the command line tools:
http://railsapps.github.io/xcode-command-line-tools.html

## Step 2: Setup Brew

Install Homebrew following this page (just paste that into Terminal and press return, as it says):
https://brew.sh/

Next paste "brew install sdl2 cmake" into Terminal and press return.

## Step 3: Compile PPSSPP

Open a Terminal, and paste the following into the window (this downloads PPSSPP's source code):

```
cd ~/Documents
git clone --recursive https://github.com/hrydgard/ppsspp.git
mkdir ppsspp/build
cd ppsspp/build
cmake -GXcode ..
open PPSSPP.xcodeproj
```

It may take a bit of time, depending on your connection speed.  Once it's done, you should have a window open (for Xcode) with a big play button in the top left, labeled Run.  Click it.

Congratulations - you've compiled PPSSPP.

## Step 4: Disable parts of the jit to validate

You should be able to browse the files in the left panel of Xcode, or use the menu to Open a file.  Unfortunately, I don't have this in front of me right now.

You want to open `Core/MIPS/x86/CompVFPU.cpp` inside the `ppsspp` directory it just downloaded into `Documents` in Xcode.  Worst case, open Finder and drag it into Xcode.

Find these two lines:
https://github.com/hrydgard/ppsspp/blob/234e3b10bd6b0dd36e6a2bba00f1eabb7c1ab3a2/Core/MIPS/x86/CompVFPU.cpp#L41-L42

Change from:
```c++
// #define CONDITIONAL_DISABLE { fpr.ReleaseSpillLocks(); Comp_Generic(op); return; }
#define CONDITIONAL_DISABLE ;
```

To:

```c++
#define CONDITIONAL_DISABLE { fpr.ReleaseSpillLocks(); Comp_Generic(op); return; }
// #define CONDITIONAL_DISABLE ;
```

This disables all the parts of the jit in the file.  Now do the same thing in `Core/MIPS/x86/CompLoadStore.cpp`:
https://github.com/hrydgard/ppsspp/blob/234e3b10bd6b0dd36e6a2bba00f1eabb7c1ab3a2/Core/MIPS/x86/CompLoadStore.cpp#L44-L45

They'll end up being:
```c++
#define CONDITIONAL_DISABLE { Comp_Generic(op); return; }
// #define CONDITIONAL_DISABLE ;
```

We're just switching the `// ` part from one line to another.  This is designed to be easy.

Next `Core/MIPS/x86/CompFPU.cpp`:
https://github.com/hrydgard/ppsspp/blob/234e3b10bd6b0dd36e6a2bba00f1eabb7c1ab3a2/Core/MIPS/x86/CompFPU.cpp#L44-L45

At this point you've disabled maybe 75% of the jit.  It's time to hit that Play button again.

## Step 5: Test and report back

Now simply play the game and see if it still happens - make sure jit is enabled.  The parts of the jit that are still enabled are (usually) the most stable and also most frequently used parts of the jit.  It should still be faster than other cores.

If it doesn't happen, then try undoing the changes above one file at a time (going backwards, starting with `CompFPU.cpp`.  If enabling one of the files starts it happening again, then we know the bug is in that file.  Comment back, and I can explain how to even narrow it down to the exact bug (don't worry, it's probably even more painless.)

If it does still happen, it could mean that I'm wrong about the most stable parts of the jit being stable, or it could mean it's not related to the jit after all.

In that case, I recommend undoing all your changes - good news, though, this can be done easily in Terminal.  No need to remember the things you changed.  Just paste this:

```bash
cd ~/Documents/ppsspp
git checkout Core/MIPS/x86/
```

You're back to the official latest and greatest.  Now paste this:

```bash
git checkout -f 150619c
git submodule update --init
```

Once that's done thinking, go back to Xcode and press Run.  We've rewinded to v1.3-807-g150619c, and just make sure it's still flickering.  Next:

```bash
git bisect start
git bisect bad
git checkout -f v1.3
git submodule update --init
```

Now we're back to v1.3 release version.  Hit Run again, and see if it happens - it sounds like it won't.  If it does, stop following these instructions and comment back.

Assuming it doesn't happen there, great.  Now git can do some magic for us.  Paste into Terminal:

```bash
git bisect good && git submodule update --init
```

Since there are about 807 commits between the two versions, it will go by halves to find the problem for you.  After you've tested about 10 versions, it'll tell you EXACTLY when the problem was introduced.

At this point (after pasting the above), the code has been updated to somewhere around v1.3-400.  Hit Run, see what happens.  There are three things that can happen:

1. It doesn't flicker.  Paste `git bisect good && git submodule update --init` and Run again.
2. It does flicker.  Paste `git bisect bad && git submodule update --init` and Run again.
3. Xcode says there's a problem with the code and can't run it.  Paste `Paste `git bisect skip && git submodule update --init` and Run again.

Since it's going by halves, this is the fastest way to test - it'll take about 9 or 10 "good" or "bad" to find it.

Once it does, the Terminal will say something about "first bad commit".  Copy everything it says and paste here.

-[Unknown]

**Comment by Rekrullurker** [comment]
I'm having this same issue with both Midnight Club games on the Windows 32-bit version of PPSSPP. I checked a bunch of older builds and narrowed it down to v1.3-493. All the versions below that seem to run the games fine with just a very occasional flicker in the menus (like a single quick blink every 30 seconds or so), but from v1.3-493 on, the games are pretty much unplayable. 

Right from the start, the title screens flicker badly. The menus seem fairly stable, but do show the occasional flicker as described above. When you select a race mode, the loading screen again flickers badly. Once in the race, it continues to flicker, although not as much as the title and loading screens. However, eventually the screen will go either completely black, or there will be a large black square covering up about 3/4 of the screen starting from the upper left. Here are a couple of screenshots (for some reason, I can't attach the files);

https://s21.postimg.org/9tezt2hyv/Midnight_Club_3_DUB_Edition_small.jpg
https://s17.postimg.org/4rf13jxcv/Midnight_Club_LA_Remix_small.jpg

If you press the ESC key to pause the emulator while this is happening, PPSSPP won't display the menu. It WILL pause the emulation, it just stays on the game screen rather than displaying the menu. If you continue to play the game, the screen will eventually go back to normal, although the problem will continue to reoccur every few seconds, making the games unplayable.

My system specs;

CPU: Core-2-Duo @ 2.4Ghz
RAM: 4GB
GPU: GT430 (Nvidia GeForce)
Audio: CMI8738/C3DX PCI Audio Device (onboard)
OS: Windows XP Pro, SP3

**Comment by unknownbrackets** [comment]
If v1.3-493-g83ff9f4 was when it started working incorrectly, that implicates #9280.  Which seems like it could be related for sure.

-[Unknown]

**Comment by Rekrullurker** [comment]
To be clear, I didn't compile any of the versions myself, I only tested the ones that are available from the automated builds page. Both Midnight Club games work correctly for me in v1.3-483, but flicker and go black in v1.3-493. I can't say for certain that the problem didn't start in one of the intervening builds for which there is no download.

**Comment by hrydgard** [comment]
It appears that after CopyDisplayToOutput, more display lists are executed and more render target switches happen before we get to EndHostFrame, and if one of those framebuffers are still bound, things break. This shouldn't happen and I don't quite understand how...

**Comment by unknownbrackets** [comment]
So that would mean somehow `coreState` is not remaining `CORE_NEXTFRAME`, or else `CORE_NEXTFRAME` is working improperly, right?

Maybe something like:

```c++
bool doNextFrame = false;
		const bool fbReallyDirty = gpu->FramebufferReallyDirty();
		if (fbReallyDirty || noRecentFlip || postEffectRequiresFlip) {
			if (coreState == CORE_RUNNING) {
				coreState = CORE_NEXTFRAME;
doNextFrame=true;
				gpu->CopyDisplayToOutput();
				if (fbReallyDirty) {
					actualFlips++;
				}

...

		// place to do housekeeping.
		CoreTiming::ScheduleEvent(0 - cyclesLate, afterFlipEvent, 0);
		numVBlanksSinceFlip = 0;
if (doNextFrame && coreState != CORE_NEXTFRAME) __debugbreak();
	} else {
		// Okay, there's no new frame to draw.  But audio may be playing, so we need to time still.
		DoFrameIdleTiming();
	}
```

**Comment by hrydgard** [comment]
That check unfortunately doesn't catch whatever it is.

Here's a log (with some new logging added) from a flickery loading screen.

We clearly have some kind of bug with the corestate check after running HLE functions:

    57:11:865 idle0        I[FRAMEBUF]: HLE\sceDisplay.cpp:679 Setting coreState to NEXTFRAME (globaltime = 8542421325)
    57:11:866 idle0        D[FRAMEBUF]: Common\FramebufferCommon.cpp:891 Displaying FBO 00000000
    57:11:866 idle0        D[FRAMEBUF]: Common\FramebufferCommon.cpp:477 Switching render target to FBO for 00000000: 481 x 273 x 3
    57:11:866 idle0        D[FRAMEBUF]: Common\FramebufferCommon.cpp:477 Switching render target to FBO for 00088000: 481 x 273 x 3
    57:11:867 idle0        I[FRAMEBUF]: System.cpp:562 RunLoopUntil finished (globaltime = 8542421849)

Note that about 500 cycles passed between setting coreState and RunLoopUntil finished, and this must have been enough for the game to enqueue a display list, drawing, switching render targets and causing havoc.

**Comment by hrydgard** [comment]
So it's happening inside the vblank interrupt (of course) but we should still be able to exit before executing any more code..
```
18:02:398 idle0        D[CPU]: HLE\sceKernelInterrupt.cpp:151 Entering interrupt handler 08aacb64
18:02:398 idle0        I[FRAMEBUF]: HLE\sceDisplay.cpp:679 Setting coreState to NEXTFRAME (globaltime = 7994192624)
18:02:398 idle0        D[FRAMEBUF]: Common\FramebufferCommon.cpp:891 Displaying FBO 00000000
18:02:398 idle0        D[SCESCEGE]: HLE\sceGe.cpp:357 sceGeListEnQueue(addr=08c82900, stall=00000000, cbid=00000000, param=00000000)
18:02:398 idle0        D[FRAMEBUF]: Common\FramebufferCommon.cpp:477 Switching render target to FBO for 00000000: 481 x 273 x 3
18:02:398 idle0        D[FRAMEBUF]: Common\FramebufferCommon.cpp:477 Switching render target to FBO for 00088000: 481 x 273 x 3
18:02:399 idle0        D[SCESCEGE]: HLE\sceGe.cpp:364 List 889192460 enqueued.
18:02:399 idle0        I[FRAMEBUF]: System.cpp:562 RunLoopUntil finished (globaltime = 7994193135)
18:02:410 idle0        D[SCEINTC]: HLE\sceKernelInterrupt.cpp:409 Left interrupt handler at 08000020
18:02:411 idle0        D[CPU]: HLE\sceGe.cpp:128 Entering GE interrupt handler 00000001 (subintr: 08aacc34 data: 0000 handlerArg: 00000000)
18:02:411 idle0        D[SCEINTC]: HLE\sceKernelInterrupt.cpp:409 Left interrupt handler at 08000020
18:02:413 MC3Loading   D[SCESCEGE]: HLE\sceGe.cpp:413 sceGeDrawSync(mode=0)  (0=wait for completion, 1=peek)
18:02:415 idle0        D[CPU]: HLE\sceKernelInterrupt.cpp:151 Entering interrupt handler 08aacb64
18:02:415 idle0        I[FRAMEBUF]: HLE\sceDisplay.cpp:679 Setting coreState to NEXTFRAME (globaltime = 7999748683)
18:02:415 idle0        D[FRAMEBUF]: Common\FramebufferCommon.cpp:891 Displaying FBO 00000000
18:02:415 idle0        D[SCESCEGE]: HLE\sceGe.cpp:357 sceGeListEnQueue(addr=08c70900, stall=00000000, cbid=00000000, param=00000000)
18:02:415 idle0        D[FRAMEBUF]: Common\FramebufferCommon.cpp:477 Switching render target to FBO for 00000000: 481 x 273 x 3
18:02:415 idle0        D[FRAMEBUF]: Common\FramebufferCommon.cpp:477 Switching render target to FBO for 00088000: 481 x 273 x 3
18:02:416 idle0        D[SCESCEGE]: HLE\sceGe.cpp:364 List 889192461 enqueued.
18:02:416 idle0        I[FRAMEBUF]: System.cpp:562 RunLoopUntil finished (globaltime = 7999749194)
18:02:427 idle0        D[SCEINTC]: HLE\sceKernelInterrupt.cpp:409 Left interrupt handler at 08000020
18:02:427 idle0        D[CPU]: HLE\sceGe.cpp:128 Entering GE interrupt handler 00000001 (subintr: 08aacc34 data: 0000 handlerArg: 00000000)
18:02:427 idle0        D[SCEINTC]: HLE\sceKernelInterrupt.cpp:409 Left interrupt handler at 08000020
18:02:429 MC3Loading   D[SCESCEGE]: HLE\sceGe.cpp:413 sceGeDrawSync(mode=0)  (0=wait for completion, 1=peek)
18:02:430 idle0        D[CPU]: HLE\sceKernelInterrupt.cpp:151 Entering interrupt handler 08aacb64
```

(we don't want to see sceGeListEnQueue after ```Setting Core State``` but before ```RunLoopUntil finished```...)

**Comment by hrydgard** [comment]
Wait, it's not a syscall, hleEnterVblank which calls CopyDisplayToOutput is called from CoreTiming::ProcessFifoWaitEvents, which is called from Advance - and after running Advance we don't have an immediate check for CoreState! So it falls back into the loop a bit before exiting. This needs fixing.
