### ISSUE TITLE
Feature request - Build system - Visual Studio - Version independent solution

### ISSUE THREAD

**Issue by pal1000** [hrydgard/ppsspp#9423]
PCSX2 developers did this, it made things hassle free when multiple Visual Studio versions are supported like now. We have again 2 supported versions - Visual Studio 2015 and 2017.

**Comment by hrydgard** [comment]
So what do we need to do? The solution we have opens flawlessly with both, though of course if you open it in VS2017 it will still use the VS2015 toolchain unless you change it in the project settings.

**Comment by Orphis** [comment]
Well, you could also fix the CMake build system and generate the solution for whatever version of Visual Studio you fancy.
Hmm, well, am I not supposed to work on that? :-/

**Comment by LunaMoo** [comment]
I think all we have to do here is change platform toolset to $(DefaultPlatformToolset)_xp I'm trying this now:3. If it works in both, I'll open a pr.

**Comment by hrydgard** [comment]
Oh, yeah, I'm totally fine with that.

**Comment by LunaMoo** [comment]
Heh a bit of delay, but had a weird problem with my setup(installed vs2017 yesterday), was failing to open projects in VS 2017 saying about missing component: Microsoft.VisualStudio.ComponentGroup.NativeDesktop.WinXP

 After few tries VS proposed to install the missing component with installation that takes 0 kb space(no wonder since I for sure installed it), and it worked;].
