### ISSUE TITLE
Unclean Changes causes Crashes

### ISSUE THREAD

**Issue by Hydroque** [hrydgard/ppsspp#9438]
It appears that changing settings under 'more settings' and going back to the game can cause crashes on windows. I understand that this can go on because PPSSPP needs to restart, but crashing when pressing exit can and will happen. OpenGL Windows.

I am thinking this could be unclean changes that cause this?

**Comment by hrydgard** [comment]
Just some bug, that needs fixing. Can you tell me a sequence of clicks that always crashes?

**Comment by Hydroque** [comment]
> leaves to go play around with it

**Comment by hrydgard** [comment]
Oh yeah, where do you see "More settings"? Didn't know we had that..

**Comment by Hydroque** [comment]
Game Settings > More Settings...
o.o

**Comment by hrydgard** [comment]
Which backend? D3D11, OpenGL, D3D9 or all of them?

**Comment by Hydroque** [comment]
OpenGL is the only one I use. I don't have libraries for dx9 or dx11.

**Comment by hrydgard** [comment]
Oh, right, I forgot about going through that menu, I always click ESC. 

shouldn't have deleted that post :P

**Comment by Hydroque** [comment]
Eww geeze now I just crash for trying to load up a game o.o

**Comment by hrydgard** [comment]
Hm, yeah, something is indeed different when you go through More Settings instead of the other way. That's a bug.

**Comment by Hydroque** [comment]
Is there any option where I can stretch the 1x rendered image without anything special added?

**Comment by hrydgard** [comment]
Many parts of the graphics code are dependent on this setting, even vertex decoders. So we need to add some complicated logic to wipe a bunch of caches if this setting changes in-game.

Maybe it'll be easier to just not allow changing this particular setting while in a game....

**Comment by unknownbrackets** [comment]
It's just vertex cache, vertexjit, and vertex decoder cache - right?  Theoretically, we should clear all of those when settings change.

 - [X] Clear [`lastVType_` and `dec_`](https://github.com/hrydgard/ppsspp/blob/a272a4ee3f4dfd39333ada81879ad65eb0947b64/GPU/GLES/DrawEngineGLES.cpp#L1014).
 - [X] Flush [`decoderMap_`](https://github.com/hrydgard/ppsspp/blob/a272a4ee3f4dfd39333ada81879ad65eb0947b64/GPU/GLES/DrawEngineGLES.cpp#L1019).
 - [X] [`decJitCache_->Clear();`](https://github.com/hrydgard/ppsspp/blob/a272a4ee3f4dfd39333ada81879ad65eb0947b64/GPU/GLES/DrawEngineGLES.cpp#L1013).
 - [ ] `ClearTrackedVertexArrays();` (vertex cache - maybe not necessary?)
 - [X] [`UpdateCmdInfo();`](https://github.com/hrydgard/ppsspp/blob/a272a4ee3f4dfd39333ada81879ad65eb0947b64/GPU/GLES/GPU_GLES.cpp#L774)

Not sure if we need to clear the vertex cache, or maybe we do.  Everything else seems to be cleared?  Where does it crash from Pause?

I did find that it's not working from More Settings.  This is because it bypasses Pause, which also bypasses this code:
https://github.com/hrydgard/ppsspp/blob/9e390510df7d2865bdcb13da3613719ff056bfa6/UI/PauseScreen.cpp#L358

Because that was introduced and is hiding things, we only have a few hooks:
https://github.com/hrydgard/ppsspp/blob/master/UI/GameSettingsScreen.cpp#L928

Simpler might be to trigger resized when exiting the GameSettingsScreen, instead of PauseScreen.

-[Unknown]

**Comment by hrydgard** [comment]
There's got to be something else, too. I just hooked it up to onFinish in GameSettingsScreen but it still happens. Crisis Core reproduces easily if you have a few characters on screen.

**Comment by Hydroque** [comment]
Lemme know what you want me to test.

**Comment by hrydgard** [comment]
@Hydroque  Just download the latest build http://buildbot.orphis.net/ppsspp/ and see if you can still get it to crash - and if so provide instructions :)

**Comment by Hydroque** [comment]
I set up my default settings. It still crashes. I reset the default settings manually. Still crashes. >.< I didn't even touch software skinning and the like. I need to test a bit more.

**Comment by hrydgard** [comment]
Uh, what? Please tell me what you are doing when it crashes.

**Comment by Hydroque** [comment]
Just loading up a game under OpenGL. Freshly unrar'd. I discovered that turning off buffered rendering fixes this issue.

**Comment by hrydgard** [comment]
Uh, that works perfectly fine here.

**Comment by Hydroque** [comment]
Could it be recent changes? I haven't modified anything on my computer other than installing dx9 libraries... which took like 0.0001 seconds to do with the web installer that didn't even download anything >.>

**Comment by hrydgard** [comment]
It shouldn't be, but that's why I'm asking you to test a few builds back to see if it is.

**Comment by Hydroque** [comment]
Hmm. I wouldn't worry about it any further. I uninstalled visual studio and now it doesn't work any longer on default settings. That is literally the only thing that I have done to change my computer.

Thanks microsoft.
