### ISSUE TITLE
(Gundam Assault Survive)Unable to adhoc 3 player

### ISSUE THREAD

**Issue by NgJinXiang14** [hrydgard/ppsspp#9474]
As the title,we can play without problem at 2 player mode but when come to 3 player it always infinite connect to the host and later disconnected.Test with 2 pc and 1 android with 1100 port offset.

**Comment by tywald** [comment]
Try have **everyone** to disable "Fast memory" in System; works for other games(Monster Hunter specifically). Maybe Gundam Assault Survive is in the same boat.

**Comment by NgJinXiang14** [comment]
@tywald But without Fast Memory,this game will get black screen when start the game and flickering if you enable fast memory later disable it.

**Comment by unknownbrackets** [comment]
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
