### ISSUE TITLE
Sound problem on Android when using VOIP

### ISSUE THREAD

**Issue by NgJinXiang14** [hrydgard/ppsspp#9480]
While using voip on android,the audio of ppsspp become like sometime normal and sometime small volume ,already test at different phone it also the same.

**Comment by hrydgard** [comment]
Which voip app?

**Comment by NgJinXiang14** [comment]
@hrydgard Wechat,Skype,Razor Comm,all there got same problem

**Comment by enniobattista** [comment]
I have recently encountered the problem with the sound, this is due to the fact that sometimes goes in spurts.

**Comment by unknownbrackets** [comment]
Hmm, I wouldn't be shocked if this was intentional.  I already have weird problems with other apps when mixing sound play + VOIP, but it's mostly that they sometimes don't play at all.

Does this still happen?

-[Unknown]

**Comment by unknownbrackets** [comment]
Is this still an issue?  And does it consistently not happen with other games / apps?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
