### ISSUE TITLE
Strange delay when holding buttons

### ISSUE THREAD

**Issue by winterdrake** [hrydgard/ppsspp#9513]
Hi there, I'm loving the program but I'm having an issue.
I'm trying to play MegaMan Powered Up, but I'm getting a weird delay with the movement controls. Basically, when I hold a button, it'll register the button press instantly for one frame, then wait half a second, then start registering it as a held press from then on. 
So, to clarify, my character moves forward for one frame, waits half a second, and then starts running forward. This happens using the analog stick,dpad, or my keyboard. I checked how ppsspp is registering the inputs using the "test analog controls" screen, and it's definitely registering one button press, then a delay, then a button hold. It makes it very difficult to play. 

The delay reminds me of how when you hold a letter on your keyboard, it types one of that letter, pauses, and then starts spamming that letter. Not sure if this helps!

**Comment by hrydgard** [comment]
That sound really strange. Is this on PC, Mac, Linux or on Android? We had a change to keyboard repeat functionality recently that would only affect Mac and Linux if it's broken.

**Comment by winterdrake** [comment]
Yeah, it is strange. I'm on Windows 10.
When I get home I'm actually going to double check I have the latest version, as well.

Thanks for the awesome response time, by the way 😊

**Comment by hrydgard** [comment]
You didn't accidentally enable some accessibility feature, like slow keys, or whatever they're called these days?

**Comment by winterdrake** [comment]
I just checked with my control panel, slow keys is not enabled. But you know how if you hold a key on a text field, it types one of that character, pauses, and then starts rapidly repeating the character? The delay is similar to that (although it could be totally unrelated, I don't know)

**Comment by unknownbrackets** [comment]
It probably won't change anything, but you can try the latest git builds here:
http://buildbot.orphis.net/ppsspp/

These are basically what will be called 1.4, which is releasing soon.

Do you have anything that is simulating gamepad/controller input based on keyboard input?

-[Unknown]

**Comment by winterdrake** [comment]
You mean like JoyToKey or anything? No, my controller was mapped directly into ppsspp.
And I'll try the new build, thanks

**Comment by winterdrake** [comment]
New build did not fix the problem, and I've recorded a video to show it off for clarity: https://www.youtube.com/watch?v=WX4eVZrpYQ8&feature=youtu.be

Also, in the new build, postprocessing shaders just aren't working? And it seems like all of the linear smoothing effects I had are gone. I'm gonna be reverting to 1.3 until that's fixed

**Comment by LunaMoo** [comment]
Nothing's wrong in that video, I would dare to say the only problem here is expecting re-released game with Capcom logo on the boot screen to work flawlessly and not be a cash grab, because pretty much they all have some problems.:P

 Sadly that's how this Mega/Rock Man game worked on psp, easily seen in many videos recorded from psp, for example [here](https://www.youtube.com/watch?v=9C2YsiYyif8) where short pause is easily visible there when changing from standing to running animation and that's a video from 2009, certainly not recorded in emulator:].

 If this can be improved in any way it would be through game hacking, as it stands the game showing this problem means it's properly emulated and as such I'm going to close this.
