### ISSUE TITLE
Nascar and DTM still the same issues.

### ISSUE THREAD

**Issue by fuentescg** [hrydgard/ppsspp#9524]
Dear @hrydgard 

So many new revisions later and those games are still having the same issues with textures even from the first version. The only thing I want to say is that about 2 years ago and still nobody is interested in repairing these errors, even in new revisions, the bugs are the same and haven´t changed. The only thing you do is to add new functions, most of them useless to the performance of the emulator, and leave the same bugs in each new version that comes out. I recently asked if anyone had an idea where the errors could be and they closed it saying that there was already an issue open with the same theme "closing since those problems are already listed in #6583 and #5001". It turns out that the open issue is from over 2 years ago and you only resolve new ones that come out (# 9xxx +). You should worry about resolving the old issues and leave waiting a little bit the new ones that come out. In addition, you are more concerned with the cosmetic of the interface and adding functions as useless as Vulcan and do not worry about improving performance and compatibility in OpenGL, which is more compatible and works on any old or new generation GPU. Most of the bugs and regressions that are presented, are in many ways for adding functions that really are useless for the majority of users. For example, why to add Tesselation if the original PSP does not have that feature?.I do not care if you insult me ​​or treat me like crazy, but what I say is true. Instead of adding functions, and I repeat, most useless, you should be concerned about compatibility and resolving the old open issues first. If you want the people to BUY the emulator to support the development, you should consider what i said.

Regards,

**Comment by LunaMoo** [comment]
Right before releasing new versions people concentrate on finding/fixing regressions, which is why new issues took priority.
 If some old issues are left unsolved, it simply means nobody know how to solve them, very likely doesn't even have those games and they don't have free demo versions.

 Closing. As this is no place for rants. To begin with understand that this is free, open source project and people work on whatever they want to work, trying to put pressure just turns people away, if you keep nagging people to fix your favourite issue all you will get is being ignored.

**Comment by ijoinit** [comment]
Yeah,you just need wait,Or learn C++ or something ,and try to do it yourself

**Comment by hrydgard** [comment]
Well, this reminded me that I think I know what's going on in #5001 (the horizontal glitches).  I'll comment further there.

**Comment by unknownbrackets** [comment]
The PSP does actually have tessellation - and your argument could really be used on world hunger.

I mean, recent releases of the World - such as 2016.0 and 2017.0 - have all had new features/effort such as self-driving cars, 3d printed prosthetic limbs, and many other things.  Yet still no one has solved world hunger.  In fact, no one has even really solved diabetes.

Obviously, emulating games is neither as important or as complicated as solving those important problems.  But, if no one knows how to solve a problem, or if no one who can can get the information they need to fix it... it tends to stick around.

My recommendation: if you think a problem needs more work, that it's important and not getting the attention it needs - that's when you roll up your sleeves.  People are not born with the knowledge to do great things, and whether it's agriculture or the fix for Persona 2's graphics, things are solved by people who sought out the knowledge and fought for the skill to fix them.

-[Unknown]
