### ISSUE TITLE
[Qt] Missing layers in Kingdom Hearts in 1.4

### ISSUE THREAD

**Issue by sergiobenrocha2** [hrydgard/ppsspp#9532]
Testing with latest commit, happening only with Qt, Ubuntu 14.04

![screenshot - 02042017 - 01 34 16](https://cloud.githubusercontent.com/assets/5431285/24584443/a56e1830-1744-11e7-9ea6-1b1ff76bf019.png)

Press ESC then return, it'll show fine:

![screenshot - 02042017 - 01 34 44](https://cloud.githubusercontent.com/assets/5431285/24584444/a56f61fe-1744-11e7-814e-daf32849975f.png)

It's happening with clean settings as well

**Comment by sergiobenrocha2** [comment]
Does not happen with 1.3.0

**Comment by unknownbrackets** [comment]
We've improved a lot of dirtying behavior.  Does this still happen in the latest git builds?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
