### ISSUE TITLE
Crisis Core white screen

### ISSUE THREAD

**Issue by sergiobenrocha2** [hrydgard/ppsspp#9533]
Open a save in that spot (Modeo Ravine - North), you'll notice that bottom and top screen get white, then suddenly/randomly it return to normal. Happening with Qt and SDL

Testing on Ubuntu 14.04, last commit.

mesa 10.1.3
core i7-4700HQ
00:02.0 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)

![crisis core - 0 - screenshot - 02042017 - 02 11 22](https://cloud.githubusercontent.com/assets/5431285/24584633/272b4c8a-174a-11e7-812a-721dcfca11db.png)

![crisis core - 1 - screenshot - 02042017 - 02 11 22](https://cloud.githubusercontent.com/assets/5431285/24584634/272cb5ac-174a-11e7-9a1f-955a41b47cbe.png)

**Comment by unknownbrackets** [comment]
Has this worked correctly in earlier versions?

-[Unknown]

**Comment by sergiobenrocha2** [comment]
Happens with 1.3.0 too. I can try with other versions later.

Does not happen with 1.0.1-git from libretro fork

**Comment by unknownbrackets** [comment]
Has this improved in latest versions after switching to core profile by default?

It's worth trying OpenGL and Vulkan to see if it happens in one, the other, or both.

-[Unknown]

**Comment by unknownbrackets** [comment]
Has this improved in 1.6.0?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
