### ISSUE TITLE
Salamander Portable ULJM05219 corrupt graphics with d3d11

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#9551]
ppsspp-v1.4-31-g0ca16c2
choose xexex (doesnt happen in any other games you choose)
using d3d11 the graphics are not correct
![uljm05219_00001](https://cloud.githubusercontent.com/assets/2696404/24642911/16fc3a3c-193d-11e7-8650-4e8d9e06d8cd.jpg)
![uljm05219_00003](https://cloud.githubusercontent.com/assets/2696404/24642918/264c0ed6-193d-11e7-964c-d036e6308140.jpg)

using ogl the graphics are correct
![uljm05219_00000](https://cloud.githubusercontent.com/assets/2696404/24642936/3b643776-193d-11e7-96ac-65a6c9cebb3e.jpg)
![uljm05219_00002](https://cloud.githubusercontent.com/assets/2696404/24642946/49bf7a92-193d-11e7-86ed-3ffe120e5098.jpg)

**Comment by benderscruffy** [comment]
v1.6.3-526-g669079454
still present
GE debugger dump
[ULJM05219_0001.zip](https://github.com/hrydgard/ppsspp/files/2437017/ULJM05219_0001.zip)

**Comment by unknownbrackets** [comment]
This seems to work from the dump now - I think I had reproduced the issue before, but never commented on this issue (sorry) since I had no idea.

Is it working now?  If not, it might help to create a new dump (there's been some bugfixes for that recently) and confirm if you still see the issue when you view the dump.  It's possible the issue could be only visible in gameplay and not via the dump, but I'm hoping it's just fixed.

-[Unknown]

**Comment by benderscruffy** [comment]
v1.7.5-566-gf316a6590
still the same problem
[DUMP.ZIP](https://github.com/hrydgard/ppsspp/files/2966067/DUMP.ZIP)

**Comment by hrydgard** [comment]
Still happens, I guess?

**Comment by benderscruffy** [comment]
yep still happens on the latest version
![salamander](https://user-images.githubusercontent.com/2696404/60960997-bbc39380-a33d-11e9-9c87-22348d5c9e8c.PNG)

**Comment by hrydgard** [comment]
Trying the dumps, this seems to have been fixed, maybe as a result of all the consolidation between backends.
