### ISSUE TITLE
[iOS]v1.4-48-gf66e54c4c is freezing on game load on iOS 7.0.4 .

### ISSUE THREAD

**Issue by Theo1996** [hrydgard/ppsspp#9561]
I installed through the repo the latest version as mentioned in the title and any game i tried to play ,heavy or light,it always freezes and when you try to close it it freezes you phone requiring restart.

But it doesn't crash so i ahve no crash log,but something similar happens on version 1.1.1 and a log is created,will attach it.The log is from an app called crash logger.
Log: https://pastebin.com/ukBX3pjx

Temporarily i have downloaded the 0.9.8-1043-gfddb289 and it works.

**Comment by unknownbrackets** [comment]
Does this happen in the latest git build?  It works on newer iOS versions just fine.

Reminder: various jailbreaks have bugs.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
