### ISSUE TITLE
Video Playback [DoA-Paradise] broken in 1.4

### ISSUE THREAD

**Issue by Sur3** [hrydgard/ppsspp#9567]
Hi the Videos Playback [at least Intro-Videos] in DoA-Paradise is visually broken in 1.4, but it worked fine in 1.3. The Intro-Video in Mortal Kombat Unchained works fine so it seems not to be the Video-Playback in general.
My used Backend is OpenGL.

**Comment by unknownbrackets** [comment]
Unfortunately, FFmpeg doesn't believe in keeping a stable API and never really has.

Closing this as a duplicate of #9026 in that case -  we don't support the newer versions of FFmpeg, because they are not backwards compatible (if they were following semver, they would have much higher version numbers.)

-[Unknown]
