### ISSUE TITLE
ppsspp's button sometimes do not restore

### ISSUE THREAD

**Issue by sum2012** [hrydgard/ppsspp#9570]
report from badiu of Windows Tablet
v1.3 no problem
v1.4 have this problem
I will tell him to test which commit\pull request break it.

**Comment by unknownbrackets** [comment]
What does "restore" mean in this context?

-[Unknown]

**Comment by sum2012** [comment]
When we are pressing the ppsspp button,the button become bigger,after release,the button restore small .v1.4 sometimes do not restore small

**Comment by sum2012** [comment]
@hrydgard @unknownbrackets 
The report said that it is very easy to reproduce problem that press multi button at once.
Most likely it is thread mutex change

**Comment by hrydgard** [comment]
Oh, you mean the virtual controls?

I don't think it's the mutex change, but I'm not 100% sure.

**Comment by sum2012** [comment]
Yes , virtual controls (triangle,square,circle,cross)
now v1.3 no problem
v1.3-290-gd91f826 have problem

**Comment by hrydgard** [comment]
Thanks, good info.

**Comment by sum2012** [comment]
Sorry,I get wrong report,
last work v1.3-908-g6278663 
first break v1.3-918-ge17772b
![1](https://cloud.githubusercontent.com/assets/2177532/24929984/769ea008-1f3a-11e7-9ff5-a8c84e7ea855.png)
That mean #9430 
The  virtual controls do not return small

**Comment by hrydgard** [comment]
Thanks @sum2012 . @unknownbrackets , that's surprising, didn't think that merge changed a lot with the touch events... I'll investigate tomorrow.

**Comment by unknownbrackets** [comment]
Well, the biggest change there was related to Windows touch events, mainly just the way it determines which id to use.  I can only assume something wrong is happening to `pointerDownMask_`?

This sounds like a hack, but I wonder if it'd improve this issue to change...
https://github.com/hrydgard/ppsspp/blob/22782b643971e2f065380b7b270432919374a413/UI/GamepadEmu.cpp#L79-L87

To:
```c++
	if (input.flags & (TOUCH_DOWN | TOUCH_MOVE)) {
		if (bounds_.Contains(input.x, input.y))
			pointerDownMask_ |= 1 << input.id;
		else
			pointerDownMask_ &= ~(1 << input.id);
	}
```

Which might at least more aggressively fix it if up/down became unpaired somehow.

Anyway, looking harder at the logic:
https://github.com/hrydgard/ppsspp/pull/9430/files#diff-c3532e1a49254f9d8a00e53675aa251aR51

I did it wrong.  I think the issue *probably* is this:
1. I press down finger 1, touching say X.
2. I press down finder 2, touching say O.
3. I release finger 1 (now touchIds[finger1] = 0.)
4. I release finger 2, but it allocates a new touch id (since the first slot is == 0.)

Dumb mistake, arg.  I wonder if this is also affecting iOS (I think a similar issue has been reported on iOS.)

-[Unknown]

**Comment by sum2012** [comment]
My friend test on  v1.4-87-g627c280
All things are fixed.Thanks @hrydgard @unknownbrackets 
Closing
