### ISSUE TITLE
Pause button not closing pause menu

### ISSUE THREAD

**Issue by Anuskuss** [hrydgard/ppsspp#9592]
When pausing a game with a user defined button, that button should also allow the user to leave the pause menu. The correct behaviour only happens when that button is mapped to `ESCAPE`.

**Comment by Anuskuss** [comment]
This is still an issue. To clarify:
If you are in the pause menu, you can leave it by either clicking on **Continue** or hitting the `ESC` key (this is hardcoded). I can't pause the game by hitting `ESC` since I changed that in the controls menu. So I should be able to leave the pause menu with that same configured button, but I can't.

**Comment by unknownbrackets** [comment]
Well, this is more about the keymap concern.  For example, what if you map the pause button to X?  You might be happy today, because X pauses, but then you leave the pause menu with another button.

That's probably not likely, but the core issue is that you want to map the keys of the UI, not just the game.  Currently, you can only map the keys of the game.

-[Unknown]

**Comment by Anuskuss** [comment]
**My suggestion:**
When you first download PPSSPP or have a untouched `controls.ini`:

Action | Keyboard | Controller
--- | :---: | :---:
Go up | `kbd.Up` | `x360.Up`
Go down | `kbd.Down` | `x360.Down`
Go left | `kbd.Left` | `x360.Left`
Go right | `kbd.Right` | `x360.Right`
(Un)Pause  | `kbd.Esc` | `x360.Home`
Select | `kbd.Enter` | `x360.[A]`
Return | `kbd.Backspace` | `x360.[B]`

After you change your mappings:

Action | PPSSPP
--- | :---:
Go up | Dpad Up
Go down | Dpad Down
Go left | Dpad Left
Go right | Dpad Right
(Un)Pause  | Pause
Select<br>System -> Confirmation button | X
Return<br>System -> Confirmation button | O

So the UI never becomes non-controllable if you delete all mappings, but you can use the new mappings to control the UI (maybe someones likes to have the DPAD on WASD and the face buttons on the arrow keys). Also always use the keyboard fallback in the first table if there is no keyboard key specified for each action.

**Comment by hrydgard** [comment]
This now works for simple key bindings.

**Comment by Anuskuss** [comment]
Thanks it's works but why does it have to be so complicated though?

> Normally we don't process key bindings in the UI.

If I map `pad1.Down` to any button at all I'm allowed to use that button to go down in the UI. But what I have some weird controller (or maybe let's say some sort of accessibility device) and I wanna map `pad1.Down` to `Dpad Up` and `pad1.Up` to `Dpad Down`? Or do you thinks that's not a plausible scenario?

**Comment by unknownbrackets** [comment]
Anything can be a plausible scenario.  But people can also be confused by the mapping screen and setup a mapping configuration that is unsuable for them.  If after that, they're hardlocked out of ever using the UI again to fix it, that's a Bad Thing.  That probably also greatly impacts accessibility controllers, likely moreso than other controllers.  And the situation is probably even more confusing and frustrating in that situation.

There's a lot of reason for any controller maker to try to make up/down/etc. relatively standard because they are so common.  Yes, anything can be mapped, but you also want an escape hatch and this isn't a problem unique to PPSSPP.

-[Unknown]

**Comment by Anuskuss** [comment]
The "escape hatch" is deleting `controls.ini` but that might be too drastic.

Anyway I've implied something that I want to make more clear: You cannot control the UI with `pad1.Down` unless that button is mapped to anything at all. Meaning if I map `pad1.Down` to e.g. `Dpad Left` I'm allowed to go down but that doesn't mean that `pad1.Up` will allow me to go up. This also means that I can get softlocked via "Clear All". But every PC has a mouse and every phone has a touchscreen so this would only be an issue on consoles (which could be hardcoded as a safety net).

**Comment by hrydgard** [comment]
Well, I try to keep things as similar as possible between the various platforms to reduce the testing burden. Adding special cases like that would require more testing everytime we changed something in controls.
