### ISSUE TITLE
Add an option to developer tools to dump gamekey when loading the game?

### ISSUE THREAD

**Issue by alpakeno** [hrydgard/ppsspp#9607]

**Comment by ResurrectionRedmi9** [comment]
What?

**Comment by LunaMoo** [comment]
As far as I understand why this was requested is because gamekey is used by some homebrew to "fix savedata", however it's not actually able to fix corrupted/broken savedata, only savedata which was saved with wrong/outdated encryption which most games would detect same as "corrupted/broken".

 From quite some time PPSSPP "fixes" such savedata on it's own, by default, so I'd say this feature is pointless and as such will close this.
 If there are other reasons, state it, but overall all people I saw it requesting over the forums in the past had just this one use case and were very mislead that homebrew can actually fix trully broken savedata(ie due to file system corruption) - which obviously it can't and what it can do, PPSSPP as noted does already.
