### ISSUE TITLE
Manhunt 2 - ULUS10280 minimap problem

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#9615]
using v1.4-84-ga4cb215
in the minimap the yellow square boxes are supposed to be arrows so you know what direction people are facing
happens in both d3d11 and ogl
![ulus10280_00000](https://cloud.githubusercontent.com/assets/2696404/25059841/de3a0fd0-21c0-11e7-8444-2e3a96fad061.jpg)

**Comment by unknownbrackets** [comment]
Can you try using the GE debugger to find when it draws those?  That's pretty broken looking... I wonder what effect it's using, or if it's some framebuffer download issue or something...

-[Unknown]

**Comment by majesticR3** [comment]
Can you also take a look why original color depth suddenly losing during frame drawing?

Here what we got ingame, it looks like colors was reduced to 16:
http://i.imgur.com/L6tVdoL.jpg
Here I clicking Step Draw in GE debugger. It looks okay....
http://i.imgur.com/rOIU1rn.jpg
...but SUDDENLY we got this texture (switching to red/green/blue colors) and GE draw with reduced colors.
http://i.imgur.com/f0cSAbR.jpg

**Comment by unknownbrackets** [comment]
My guess is the game is running some sort of color filter after render, but doing it in CPU.  If so, this probably defeats:

 * PPSSPP's internal resolution: because the game recolors it pixel-by-pixel, it lowers the resolution back to 1x.  PPSSPP can't apply its effects at a higher resolution because the game is explicitly performing the effect at lower resolution.

 * PPSSPP's higher internal bitdepth: when the game modifies the pixels one by one, we have to give it a pixel in the format it expects on a PSP.  If it asks for a 16-bit pixel, we have to dither the color down to 16-bit to give it to the game.

If the color filtering is unnecessary, it may be possible to create a cheat code to disable the parts of the game's code applying it, to avoid running this inefficient filter which drops the higher quality PPSSPP uses.

But this is also probably unrelated to the minimap.

-[Unknown]

**Comment by unknownbrackets** [comment]
Did this work previously or has it always been broken?

-[Unknown]

**Comment by benderscruffy** [comment]
v1.6.3-526-g669079454
still happens
[ULUS10280_0001.zip](https://github.com/hrydgard/ppsspp/files/2437913/ULUS10280_0001.zip)

**Comment by benderscruffy** [comment]
v1.7.1-210-g9bda7cb64
still happens
[DUMP.ZIP](https://github.com/hrydgard/ppsspp/files/2623073/DUMP.ZIP)

**Comment by benderscruffy01** [comment]
still happens
![manhunt](https://user-images.githubusercontent.com/48821663/54875863-4f319100-4e41-11e9-8494-816b45f0ea74.PNG)
[DUMP.ZIP](https://github.com/hrydgard/ppsspp/files/3000100/DUMP.ZIP)

**Comment by unknownbrackets** [comment]
Hmm, that's odd.  This dump seems to have it drawing the frame no less than three times.  I wonder if this has the same issue as God of War...

Anyhow, at 515 / 1587, 0x04181a40 (16x16) is used to draw these icons.  And the texture kinda looks like that... ah.  Found it, dumb mistake.

Some other interesting things... a real PSP:
![ULUS10280_#9615_manhunt_mipmap](https://user-images.githubusercontent.com/191233/54890386-5e770580-4e66-11e9-8a43-fa1fd3a94865.png)

The software renderer gets this closer, but it's still wrong (not affected by the dumb mistake):
![ULUS10280_#9615_manhunt_mipmap_softgpu](https://user-images.githubusercontent.com/191233/54890435-a007b080-4e66-11e9-95ca-b43e6daad38e.png)

The shadows are interestingly wrong, and actually just more wrong on in GLES/etc.:
![ULUS10280_#9615_manhunt_mipmap_gles](https://user-images.githubusercontent.com/191233/54891124-8ae05100-4e69-11e9-8648-1b7d69b490ee.png)

I wonder what's causing the softgpu to be wrong, hmm...

-[Unknown]

**Comment by unknownbrackets** [comment]
Thanks for the dump by the way, sorry for taking some time to dig into it properly.

If you can tell - in general, do the shadows seem to be wrong in a bad way (like make the game less suspenseful or something)?  It might just be that we're doing some lighting with too much accuracy or something, but if it doesn't get in the way I may not worry about it.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah I would bet the shadow difference is at least partially down to accuracy, but since it also shows in the software renderer there might be more going on (though if the game is running at low bit depth, it's still possible we're computing blending too accurately or something? Or maybe it has a dither pattern set, full of zeroes to darken, or something?). Anyway I think that's a separate issue, which should probably be open though just for the software rendering being off.
