### ISSUE TITLE
YuGiOh! Gx Tag Force multiplayer not working

### ISSUE THREAD

**Issue by KloeinBastie** [hrydgard/ppsspp#9623]
When starting Network Mode in YuGiOh! GX Tag Force, it just stops and not responsive after confirming "While in ad hoc mode, hold the SELECT button to disconnect and return to the main menu." Trying every different Video and Network settings but nothing work. Thank you.

**Comment by SF1997** [comment]
Try to set a port (ex: 1200) btw both device should have a same port

**Comment by unknownbrackets** [comment]
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
