### ISSUE TITLE
（Mac OS ）1.4 version will prompt the lack of memory

### ISSUE THREAD

**Issue by PokerXu** [hrydgard/ppsspp#9631]

**Comment by unknownbrackets** [comment]
This doesn't happen for me on Mac OS X.  Did you make sure you had free disk space?  Can you post a screenshot?

-[Unknown]

**Comment by PokerXu** [comment]
my internal storage is 16 GB 1600 MHz DDR3.It just a prompt box show “内存不足”

**Comment by unknownbrackets** [comment]
"16 GB 1600 MHz DDR3" is your "memory" or "RAM."

"Memory" and "storage" are separate.  Storage is like a warehouse.  Storage is big and has lots of things in it.  You will usually have 500 GB of storage or more in a computer.

Memory is like trucks.  Memory is used to transport the things kept in storage.  Memory is also more expensive.  Computers typically have around 16 GB of memory.

The biggest difference is that memory is only temporary.  When you turn off the power to your computer, everything inside memory is thrown away.  You only keep things that are in storage.

The message means that your storage is full.  The game is trying to save some data, but it can't, because there's no space left in storage.

-[Unknown]

**Comment by unknownbrackets** [comment]
Closing as it seems this is resolved from lack of replies.

-[Unknown]
