### ISSUE TITLE
7th Dragon 2020 not showing new save icon

### ISSUE THREAD

**Issue by deadair3210** [hrydgard/ppsspp#9632]
In the emulated system save save dialog, the question to save is perfect, but the confirmation afterwards is all glitched up.

Using fonts from a PSP-2000 on 6.61
ppsspp-v1.4-109-g2c6161c-windows-amd64
![xczx](https://cloud.githubusercontent.com/assets/1053504/25307235/f2856c76-2762-11e7-84aa-e2dbaab6a1b9.PNG)

This does not happen with English games, only non-English
![dcx](https://cloud.githubusercontent.com/assets/1053504/25307280/bcae67e6-2763-11e7-85b4-6e158cea3401.PNG)

**Comment by unknownbrackets** [comment]
This is probably related to the specific game, your settings, or the backend you're using.  What graphics backend are you even using?  What game is this?

It likely means alpha blending is not working.

-[Unknown]

**Comment by deadair3210** [comment]
Sorry, should have been more verbose.

Game: 7th Dragon - 2020
Backend: OpenGL
CPU: i5-2500k
GPU:HD 7800 Series

Graphics Settings screenshots
![1](https://cloud.githubusercontent.com/assets/1053504/25310188/7502845e-27a4-11e7-9537-d1233913fc12.PNG)
![2](https://cloud.githubusercontent.com/assets/1053504/25310189/75039b8c-27a4-11e7-893d-d95a314dba5a.PNG)
![3](https://cloud.githubusercontent.com/assets/1053504/25310187/75002d3a-27a4-11e7-8eaf-74612ab080f3.PNG)

**Comment by LunaMoo** [comment]
This isn't happening in "non-english games", as far as I see it's limited to 7th Dragon 2020(and II'nd part of it), eventually limited to manual save of system data which might even be unique to that series, or at least I can't recall any other game which allows it and shows save dialog, it's always auto save or in-game confirmation since it's really pointless to show save dialog for one slot to begin with.

 Also this problem isn't much about the text, it doesn't display icon. [This video](https://www.youtube.com/watch?v=qIUhG7GtIA8) starting at around 6:21 includes how saving system data looks on the real thing, and the icon is what causes the messup. It looks like that:
```
Texture map enable: 1
Texture map enable: 0
BASE: 080000
VADDR: 010228 => 08010228
DRAW PRIM RECTANGLES: count= 2 vaddr= 08010250   <- icon
BASE: 080000
VADDR: 010250 => 08010250
DRAW PRIM RECTANGLES: count= 30 vaddr= 08010250  <- "Save completed."
```
The texture that exist all the time during that is just the font, can't see icon anywhere in GE debugger, but it does save png to system data folder correctly.

Also that problem exist earlier when game asks "Do you want to save this data?" but the icon on that screen is drawn before everything else and the texture for text get's enabled right after it.

```
Texture map enable: 1
Texture map enable: 0
BASE: 080000
VADDR: 010228 => 08010228
DRAW PRIM RECTANGLES: count= 2 vaddr= 08010278  <- icon
Texture map enable: 0
BASE: 080000
VADDR: 010250 => 08010250
DRAW PRIM RECTANGLES: count= 2 vaddr= 08010278  <- selection box for yes/no
Texture map enable: 1
BASE: 080000
VADDR: 010278 => 08010278
DRAW PRIM RECTANGLES: count= 6 vaddr= 08010278  <- text
```

 This might be something completely random with timing or memory allocation since PPSSPP draws everything correctly, it's just the game code that's residing in memory doesn't have much sense:], maybe caused by displaying english text instead of japanese? At least it's really a non-bothersome problem.

**Comment by deadair3210** [comment]
Come to think of it, it doesnt happen with KH: Birth By Sleep Final Mix, so you might just be right on it being a game issue more than a wide issue, although I can find no mention of this before, so its either just not that popular of a game to emulate, or it just started doing it recently.

**Comment by unknownbrackets** [comment]
@LunaMoo PPGe draws that screen (PPSSPP code), no?  It sounds like `PSPSaveDialog::DisplaySaveIcon()` or similar is getting a null texture - also look at `SavedataParam::ClearFileInfo()`.

So we must not be loading the texture correctly.  And `PPGeDisableTexture();` definitely should be removed from `PSPSaveDialog::DisplaySaveIcon()`, by the sound of it.  I see how that can break text now.

-[Unknown]

**Comment by LunaMoo** [comment]
Not entirely sure how to recognize PGe or not - guess by the address ~ all that code starts around 08000200 and the font texture at 08020b00 it would mean yes.

**Comment by unknownbrackets** [comment]
Okay, instead change:

```c++
	if (curSave.texture != NULL)
		PPGeSetDefaultTexture();
```

To not have the if.  Then it'll re-enable texturing for the text, even when there's no save icon.

-[Unknown]

**Comment by LunaMoo** [comment]
Yeah, that shows the missing text, the only mystery why icon texture is missing.:3

**Comment by hrydgard** [comment]
Maybe some weird state that PPGe is forgetting to reset properly? Though not sure what that might be.

**Comment by unknownbrackets** [comment]
After it saves - it should create a png file under SAVEDATA.  Does this PNG render properly?  Can you upload it here?

Does the icon show in the list when overwriting the save?  Or is it also wrong there?

-[Unknown]

**Comment by LunaMoo** [comment]
Icon is created just fine in system data folder:
![icon0](https://user-images.githubusercontent.com/5485237/33514590-a6ae12fe-d756-11e7-8036-88b33abbb9dd.PNG)
but never shows as a texture in game or GE debugger.
 Normal save data icons are loaded just fine, don't think there's any significant difference in them althrough normal has slightly smaller filesize:
![icon0](https://user-images.githubusercontent.com/5485237/33514720-35ab78f0-d759-11e7-8987-5cba2855f295.PNG)

 Not counting missing icon, only other difference from PSP is that at save dialogs are in japanese on PSP, in PPSSPP all text is in english.
![snap025](https://user-images.githubusercontent.com/5485237/33514756-cab30760-d759-11e7-914a-6edbd7c44508.png)
![npjh50459_00000](https://user-images.githubusercontent.com/5485237/33514771-04105c88-d75a-11e7-9055-799c35e1e44c.jpg)
Maybe english takes more memory and the game doesn't have enough for icon?


Here's a dump, but it doesn't really show anything I guess:
[NPJH50459_0001.zip](https://github.com/hrydgard/ppsspp/files/1523750/NPJH50459_0001.zip)

**Comment by unknownbrackets** [comment]
Haven't done careful tests, but I'm pretty sure this just means that for SAVE, we should use the icon0 for display (potentially even if the "new data" icon is provided.)  Created a PR for that.

Also made it show the save title underneath.  Just to say, I personally don't think emulating the PSP's UI exactly is a worthwhile goal... but I think showing the title/etc. here makes a lot of UX sense.

The English is because the game specifies a field for the "language".  We actually ignore this field and use the configured PPSSPP language instead.  I think that's better behavior in our case.

-[Unknown]

**Comment by LunaMoo** [comment]
Well I wasn't complaining to see "yes/no" instead of "hai/iie", just mentioned in case it matters as this game actually has a nice example of a situation where english of it's fan translation from japanese to english most likely requires more memory than the original which causes pretty nasty glitches in some parts of the game.

 Can confirm #10230 fixes the icon, althrough it doesn't have a shadow which causes it to blend with the background of similar color which makes it look a bit bad.
![npjh50459_00000](https://user-images.githubusercontent.com/5485237/33517642-17015b5c-d788-11e7-9b7f-28bb3a283df5.jpg)


 Small icon in top left corner still is missing so might be different problem.

**Comment by unknownbrackets** [comment]
Ah, I think it's drawing it shaded (0xFF777777) because it doesn't exist, which may or may not be a great thing to do.

Would also say that showing higher quality dropshadows and adding one to the image would be nice, yeah.  Aside from a real case of no icon, I think maybe it should only shade it when showing in the list, perhaps?  Or not... the game already specifies a new save icon...

-[Unknown]

**Comment by deadair3210** [comment]
Sorry, was going through issues, and fumbled the button
