### ISSUE TITLE
Ppsspp crashes when trying to open game

### ISSUE THREAD

**Issue by omegaxalpha108** [hrydgard/ppsspp#9646]
Ppsspp crashes on my iphone 7+,128gb,non jailbroken,3 seconds whenever i try to open a game.this happens even after i changed the cpu core to ir interpreter.help plz

**Comment by Michal1324** [comment]
Maybe check if it works on your PC or MAC it might be corrupted ISO

**Comment by unknownbrackets** [comment]
Unfortunately, iOS is not well supported because the platform doesn't really allow for emulators.  Make sure you're running the latest git build - but you're possibly just seeing #9186.

I'm going to close this, but if you have more information feel free to comment on this issue and it'll be reopened.

-[Unknown]
