### ISSUE TITLE
Texture dumping/replacing - Make the address hash optional

### ISSUE THREAD

**Issue by SonofUgly** [hrydgard/ppsspp#9665]
Currently when textures are dumped they're saved with the address hash, CLUT hash, and data hash as their filename, but some games (like GTA:LCS and GTA:VCS) will have a different address hash nearly every time the texture is loaded, leading to thousands of duplicate textures.
Also having the address hash isn't necessary for most texture projects, the handful of people who have messed around with replacing textures on the forums either zeroed out the address on replacement textures to ignore it, or had confusion when their replacement textures weren't loading do to address mismatches.

I think it would be best to have the address hash off by default, having the texture filenames be only 16 character CLUT+data hash strings, and have there be an option in textures.ini to enable the address hash if someone should need it.

**Comment by Royal-Jelly** [comment]
I have put so much time into zeroing out duplicate address hashes in my textures.ini 

I would say such a feature is necessary, please help us so we can make more texturepacks ~

**Comment by LunaMoo** [comment]
Just to clear this - there's no such thing as "address hash", filename is made of 3 elements: address, clut hash and texture hash.

 Hash is just a result of some math that describes potentially very large things with a fairy simple number. It's how programs can quickly detect whenever something is same or not, althrough it's imperfect and different things might end up with same hash, especially true for clut hash since it's just a color pallete which some games might reuse quite often.

 Address on the other hand just points where texture is stored in memory, sometimes it's conventionally always in same place, sometimes might change often.

 With my PR, just add "ignoreAddress = true" under [options] in textures.ini file. Address will be set to zero for all textures dumped with it, [hashranges] feature can still be used, but you'll have to look up the address in GE debugger or by dumping the texture with this option disabled.

**Comment by SonofUgly** [comment]
Well that was quick, thanks. Should make things much less tedious.
