### ISSUE TITLE
Hajime no Ippo Portable Victorious Spirits multiplayer ad hoc won't work 

### ISSUE THREAD

**Issue by SF1997** [hrydgard/ppsspp#9703]
Hey, Recently I played Yu gi oh Arc v special with my bro (used Android -Xperia z2- as host and pc as guest). it worked right without any problems, till I try Hajime no ippo Portable Victorious Spirits. It keeps sending this error "申し込みは拒否されました。"  
![capture122](https://cloud.githubusercontent.com/assets/21049124/26276467/08920f2e-3d70-11e7-8927-7f3db55bbce9.PNG)
![screenshot_20170520-151733](https://cloud.githubusercontent.com/assets/21049124/26276483/466e0ab4-3d70-11e7-87f0-f4a8f68a52b4.png)
Note: used the same version of ppsspp (1.4)
Thanks a lot for advanced.

**Comment by motorcitybison** [comment]
Same hrre

**Comment by motorcitybison** [comment]
Found out how to fix it?

**Comment by unknownbrackets** [comment]
Is this still an issue on the latest git build with recent networking improvements?

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
