### ISSUE TITLE
Bomberman Europe: ask for memory stick duo (not playable)

### ISSUE THREAD

**Issue by legluondunet** [hrydgard/ppsspp#9723]
Hello,
when I launch Bomberman Europe rom, I obtain this message:
"memory stick duo verification"
then a black screen, nothing more.
Thank you for your help.

**Comment by LunaMoo** [comment]
Can't reproduce. The only problem I saw that it doesn't detect enough space to save data on boot when no save data exists, seems like a common problem of many games, but that can be skipped, the game saves fine in any other place including auto-save.

 Either way this game was playable from ancient times and still is in latest version, so must be your settings, corrupted game copy or device specific problem.

  In that order would recommend:
-  restoring PPSSPP settings to default(option for that in system settings),
-  getting a fresh and legit copy of the game(aka NOT broken warez crap).


 And then if neither of those help provide as much information as you can, since if this even is a real issue, it might as well be affecting only you/your system/platform.

**Comment by unknownbrackets** [comment]
Some games have bugs associated with certain amounts of free space (and have these same bugs on real PSPs.)  For example there was one game that would delete your save if you ever had > 9GB of free space on your stick, iirc.

Maybe this also operates wrong with a certain range.

-[Unknown]

**Comment by legluondunet** [comment]
Sorry I forgot to specify I'm using the last PPSSPP module for Retroarch (PPSSPP v1.0.1 git 5f7bcf7).
Perrhaps it is the wrong place to declare this bug?

I tested with several Bomberman Europe roms available on the internet, same result:
312c7c494107ab858cd28ad6abd56000  Bomberman (Europe).iso
ca29f6886726a2d5e8e859cfbd0f41aa  Bomberman.iso

**Comment by hrydgard** [comment]
Uh, yeah. Retroarch builds are not supported - they forked the code a while ago and have not kept it up to date.

**Comment by legluondunet** [comment]
I will open a bug on the retroarch github. Thanks.

**Comment by LunaMoo** [comment]
Also just using google on those hashes, the EU one is clearly marked as "BAD" aka broken warez crap ~ ;p.

**Comment by legluondunet** [comment]
fyi: https://github.com/libretro/libretro-ppsspp/issues/89

**Comment by legluondunet** [comment]
I downloaded your PPSSPP Linux build and I can confirm you the roms work ok.
