### ISSUE TITLE
Tactic ogre let us cling together - blurry text

### ISSUE THREAD

**Issue by HeartnetXin** [hrydgard/ppsspp#9731]
![screenshot_20170527_094207](https://cloud.githubusercontent.com/assets/28992319/26516930/7280523c-42c1-11e7-8a04-e200a88e729c.png)
The word so blur can't even read it...any kind method to fix it?

**Comment by unknownbrackets** [comment]
Does this happen even when you make sure you have the following settings...?

 * Texture scaling: Off
 * Texture filtering: Auto
 * Render resolution: 2x or 1x

If it does, what device are you using?  Is this Android, iOS, Windows, Mac...?  If Android/iOS, what device model?  If desktop/laptop, what video card?

-[Unknown]

**Comment by HeartnetXin** [comment]
![screenshot_20170528_032557](https://cloud.githubusercontent.com/assets/28992319/26523907/c3a509fc-4355-11e7-801a-2b5ffbf27134.png)

- Texture scaling: Off 
- Texture filtering:Auto
- Render resolution:3x

**Comment by HeartnetXin** [comment]
The text still blur

**Comment by HeartnetXin** [comment]
I play other game just fine except this one....the dialog, equipment name even the instruction game play text blur......update my phone system and ppsspp latest version... The text still blur... What the conclusion to fix?

**Comment by HeartnetXin** [comment]
Sorry for trouble...  I'm fix it already...thanked..

**Comment by hrydgard** [comment]
What setting did you change to fix it? Might be useful to know.

**Comment by HeartnetXin** [comment]
I'm change the texture scaling setting 
Upscale level off to auto...at first it blur then it fix the text see clear now

![screenshot_20170529_162459](https://cloud.githubusercontent.com/assets/28992319/26543310/0cc69322-4490-11e7-99e2-5ae262dbf2ef.png)

**Comment by unknownbrackets** [comment]
It's probably because of a combination of your render resolution (3x) and anisotropic filtering settings.  Texture scaling should work around it, yes.

-[Unknown]

**Comment by DarkD** [comment]
No it isn't combination, it's very same on any rendering resolution and with any/off anisotropic filtering, but indeed texture filtering makes text readable.
Will try to trace version this started with...

**Comment by unknownbrackets** [comment]
Okay, I think I see what's happening here:

1. The game sets two texture levels, 0 and 1.
2. Both point to the same address and have the same width/height.  Probably because in some locales, it uses two different textures for more charset space.
3. The game renders text with AUTO mipmapping and +1 bias.
4. GLES is unable to handle the matching mipmap levels, so it rejects them and generates auto mipmaps instead.
5. When rendering, the bias causes a smaller texture level to be used.

Also noticed that `entry->maxLevel = 0;` is used on GLES.  This seems bad: it would cause `Matches()` to fail if the maxLevel wasn't already 0, so the texture will be continually re-uploaded to GLES.  Oops.

At the very least, if no mip level is smaller than the top mip level, I think we should never auto-gen mipmaps....

-[Unknown]

**Comment by LunaMoo** [comment]
Shouldn't we just add other regions of this game to [FakeMipmapChange] compat? Japanese ones are already there.

**Comment by unknownbrackets** [comment]
Well, no, because there are a few thousand other games that aren't this one, and I don't want to test each one to see if they have the same bug.  I can fix it generically, so why should I go for the needle-in-a-haystack approach?

Sure glad we didn't fix individual straws of hay back when PPSSPP was crashing on just about every game.  We'd probably only be able to run Monster Hunter, Crisis Core, and maybe a Diva game - all badly - if we had.

-[Unknown]

**Comment by LunaMoo** [comment]
I just thought the hack is already doing the same thing, for same game;p, just different ID.

**Comment by unknownbrackets** [comment]
Also, that hack wouldn't even work here, since it's using AUTO+1 not CONST 1.  Probably the developer started removing it and decided it wasn't worth the time.

-[Unknown]
