### ISSUE TITLE
Random crash on Tactics Ogre startup if using Vulkan.

### ISSUE THREAD

**Issue by TallgeeseHeaven** [hrydgard/ppsspp#9752]
What it says on the tin.

Using AMD 7850, latest git.

If you get past startup, it seems to generally work fine aside from how it seems to stop for a moment when it needs to scale a new texture.

**Comment by unknownbrackets** [comment]
What's your texture scaling setting?

I seem to remember this game had a texture with a very high bufw (1024) or something.  It used to crash OpenGL on startup long ago...

-[Unknown]

**Comment by unknownbrackets** [comment]
There's a validation error on startup:

```
ERROR: [DS] CommandBuffer Code 6 : For image 0xac7 you cannot transition the layout of aspect 1 from VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL when current layout is VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL.
```

Which is for the fb at 0.  `BlitFramebuffer` is tacking it on to the src's cmdBuf.  This is just in `ResizeFramebufFBO`, which was called because the fb's detected size changed.  But it seems like this is just a validation layer bug maybe?  I don't see why the transition wouldn't be run...

-[Unknown]

**Comment by hrydgard** [comment]
Well, could just as well be faulty logic from my side. Command ordering is a bit complicated, since I tried to design it so we can reorder render passes later by giving each one its own command buffer (the PSP likes to bounce back and forth between render targets, such as in Wipeout where it does some scene rendering, then renders a billboard, then continues the main scene using that billboard texture which is terrible), but when something is done to a framebuffer before we've given it a command buffer that frame I do it in the frame global command buffer.

It's all getting very tricky, especially with the conflation between thin3D and the other stuff, and I'm thinking about just dumping all the frame's Vulkan commands in an array which we optimize and reorder before creating the actual vulkan command buffers. For good Vulkan usage, you really need to know up front what you are going to do and you don't until you have the whole frame from the PSP game...

**Comment by unknownbrackets** [comment]
Hm.  What's the cost of more command buffers?  For example, is submitting 10 command buffers much more expensive than 2?

If we want to reorder, I'd think we'd want to tag the command buffers with dependencies.  In the billboard example, FBO "B" would have no dependencies (except texture loads), and the overall scene "A" would just depend on "B"..

The tricky thing is bloom: in that case the draw up to bloom calculation becomes "A1", and then the bloom effect "B1" depends on "A1" and resizes down up to "D1" (each depending on the previous.)  After that, "A2" depends on "D1" and renders the rest of the scene.

So if we track an ID for each command buffer and a vector/set/w/e of dependency bufs, I think that'd be our best bet at reordering?  Though, we'd need to flush for any readback... maybe we could get smart and only submit the bufs that depend on the FBO we're reading from?

--

All that aside, it seemed like this warning from the validation layer was actually being generated before any of the bufs were submitted.  I guess we can validate the Tales game that resizes in a more obvious way...

-[Unknown]

**Comment by hrydgard** [comment]
Submitting many command buffers instead of a single big one is no big deal, they aren't expensive. 

Yeah, dependency tagging and some tricks like that is the plan, though the details I haven't though about much yet.

**Comment by TallgeeseHeaven** [comment]
@unknownbrackets The random crash happens regardless of scaling settings, tried 1x and 2x.

**Comment by unknownbrackets** [comment]
This crash appears to be fixed now.  Closing - please comment if you're still seeing with the same steps, and we'll reopen.

No validation errors at startup anymore.

-[Unknown]
