### ISSUE TITLE
An old chubby sounds issue

### ISSUE THREAD

**Issue by Terrarian51** [hrydgard/ppsspp#9777]
Description of the issue: Any game begins to lag constantly,  just after loading the ISO file into memory of PPSSPP v1.4.2. These lags includes strange chubby sounds and low FPS rate, which makes slideshow from  time to time, though. Also, I take a look through PPSSPP logs, where i saw this error message:  "Got an error in texture upload: 00000502" etc. 
I  was searching the Internet, when have found topic with similar error: https://github.com/unknownbrackets/ppsspp/commit/b39094ff74aad0ba48fe8cd87e33494c65b74efe 
That error was caused by wrong coding in the file "Framebuffer.CPP". However, after an year of active program development, that issue still remains unfixed. I can't fix it by myself, so i'm asking to the community and to the developer's team to fix this strange error as fast as they can.
Sincerely, Terrarian51

**Comment by LunaMoo** [comment]
Sound and video output is created by emulated game, if your hardware can't emulate the game at full speed the sound will break/stutter and the video will be slow/laggy, that's completely normal and expected behaviour in emulated games.

 Error with texture upload would mean you got out of video memory, that would really only happen if either:
 - you have an awfuly old gpu,
 - abuse very high texture scaling.


 Both of which would also explain why you can't emulate your game at full speed, depending which of that is your case you'll have to buy more powerful modern hardware or/and stop using heavy graphic enhancing features.

 Neither of that is an emulation issue through, so I'm closing this.
 You can read [this guide](http://forums.ppsspp.org/showthread.php?tid=5236) to understand some ppsspp options affecting performance, but if you have really serious problems, better give up on psp emulation until you can afford better hardware as miracles does not happen.
