### ISSUE TITLE
Agile.h can only be used with zw

### ISSUE THREAD

**Issue by MysteriousHercules** [hrydgard/ppsspp#9788]
Everytime I compile the ppsspp solution, only 7 of the 8 solutions compile. the eighth one says has an error in agile.h saying it only runs with zw.

That being said, I looked in the code. and the error line is defined under:
#if !defined(__cplusplus_winrt){
error agile.h only runs with zw
}

**Comment by unknownbrackets** [comment]
It sounds like you're trying to compile without /ZW - try enabling?

That said, I'm not sure how well UWP works and travis/buildbot/etc. don't even try to build it.  If you're just on Windows, try compiling the solution in Windows/ instead - it will likely work better, and lack less features.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
