### ISSUE TITLE
How to disable the game icon shake effcet?

### ISSUE THREAD

**Issue by leoxxx** [hrydgard/ppsspp#9791]
I found it in ver1.4.2.
The game icon shakes when I click it.
The effcet in both windows and android ver.
Then how to disable it?

**Comment by hrydgard** [comment]
What? There's no such thing. Or shouldn't be, at least..

**Comment by leoxxx** [comment]
@hrydgard
https://goo.gl/photos/SkJ6bK3dUNKsJm7E9

**Comment by tywald** [comment]
Hm, doesn't happen for me on official v1.4 on Windows.
When I click on a game, the icon just goes down then up only once, no shaking.

**Comment by leoxxx** [comment]
@tywald 
How about android for you?

**Comment by Hydroque** [comment]
Well by the looks of it, since it is teleporting, there must be something wrong with the thread created (which handles the tweening) or the teleport is being caused by a double click or such. Which it might be just their system. My old pc cracked up that bad to where it had very weird behavior. Also, things installed and uninstalled can severely mess with it.

Thats all I got.

**Comment by unknownbrackets** [comment]
I guess this is caused by removing the initial clear in EmuScreen.  So now you're able to sometimes see the frame where the down_ flag is false, before gameplay begins.  Possible it may only happen in multithreaded or something.

-[Unknown]

**Comment by leoxxx** [comment]
It be fixed in v1.5.4-105-g6fb2d1fa6.
I tested windows version.
I will test Android version later.
@hrydgard @unknownbrackets
