### ISSUE TITLE
Wwe svr11 settings help 

### ISSUE THREAD

**Issue by denzela426** [hrydgard/ppsspp#9792]
I been trying to play this game for 2 years now and it keeps lagging and it's going slow and the music is messing up I try changing the settings but it doesn't work so what do u do also is there a way to play multiplayer

**Comment by LunaMoo** [comment]
Closing since it's not a valid issue. This is an issue tracker, not a support forum.

 Note that every game has different hardware requirements, if you have performance problems you can read [this](http://forums.ppsspp.org/showthread.php?tid=5236). For more specific support you should ask inside the game existing thread [here](http://forums.ppsspp.org/showthread.php?tid=280).

 Also to make it clear PPSSPP is an EMULATOR, it doesn't just "run" video and sound for you to see/hear, it emulates the game and it's up to the game to do everything it wants to do. This means if your hardware can't emulate the game at full speed, video will be laggy and music will be messed up, it's normal, refer to links above which could help a bit, but if your device is really weak or old, don't expect miracles, it's very rare for an option to make a huge difference in game's requirements and when it does, it usually comes at a price of missing graphics, bad framerate etc..
