### ISSUE TITLE
Filename case sensitivity

### ISSUE THREAD

**Issue by BenMcLean** [hrydgard/ppsspp#9794]
[Wolfenstein 3D v6.0 homebrew](http://www.brewology.com/downloads/download.php?id=9730&mcid=1) runs the shareware version on PSP by just unzipping it onto your memory stick without renaming any files but it does not run the shareware version on PPSSPP unless you rename files to uppercase. Something about the way PPSSPP handles case sensitivity in file names does not match the PSP's behavior, resulting in the shareware version (without renaming files) crashing on PPSSPP but working fine on PSP.

[Some code was suggested to fix this](https://github.com/hrydgard/ppsspp/pull/9793) but it may have issues.

**Comment by Hydroque** [comment]
Well the PSP will autoname any file created on the PSP as uppercase. I think it does it if you write to it too. It is actually a defacto standard. iirc uppercase and lowercase doesn't matter when homebrew interacts with the files. Loading the files onto the stick doesn't change any naming.

**Comment by unknownbrackets** [comment]
No, that's not right - VFAT is case insensitive, but using all uppercase is not required, and lowercase on a PSP does work just fine.

It's just that it doesn't support the lowercase flags, which were introduced in NT's VFAT driver.  Remember, when you plug a PSP in via USB to Windows, Windows is writing the VFAT directory entries directly - it's not going through the PSP's VFAT code.

So really, Wolf 3D is depending on a PSP firmware bug.  And that bug is only triggered when uploading files to the PSP via USB via Windows NT/2000/XP/7/8/10/etc.  Which almost everyone uses.

I would assume if you used a PSP FTP client, or PSP unzip program, etc. the game would not work.  Since then, the filenames really would be lowercase.

-[Unknown]

**Comment by Hydroque** [comment]
How would the lowercase file names be a problem then if lowercase works just fine? Isn't that what Wolf 3D is expecting? Or does the presence of the lowercase flags enforce that it will only be read as lowercase and not case insensitive?

**Comment by BenMcLean** [comment]
So, when PPSSPP is running on Windows and its GAME directory is on a Windows file system, emulating the PSP should involve forcing case insensitivity in the file names, shouldn't it?

**Comment by BenMcLean** [comment]
Oh wait it looks like unknown brackets wrote a hack to fix it already. Thx :)

**Comment by Hydroque** [comment]
Should expect nothing less @BenMcLean 
People here are top quality :)

**Comment by unknownbrackets** [comment]
It's not an issue of case sensitivity.  The game is actually asking "what is the filename?" and because the answer is not UPPERCASE, failing.  If the game said "I want GAMEMAPS.WL1" it would just work, because it's case insensitive.  It's poor design in the game.

To explain further, Windows 98 and the PSP create and list files like this:

Short Filename | Long Filename
--- | ---
UPPER.TXT | -
GAMEMAPS.WL1 | gamemaps.wl1
FOO.BAR | foo.bar
REALLY~1.TXT | reallylongname.txt

Microsoft extended this with a new field, though, in NT and higher:

Short Filename | Long Filename | Actually Lowercase
--- | --- | ---
UPPER.TXT | - | N
GAMEMAPS.WL1 | - | Y
FOO.BAR | - | Y
REALLY~1.TXT | reallylongname.txt | N

Without going into why Microsoft did this, the PSP doesn't even know about this new flag.  So it thinks gamemaps.wl1 is uppercase... because it only looks at the first two columns of the table.  It's ignoring the Y.

So the hack just assumes that anything Windows would've written "Y" for in "Actually Lowercase"... /would/ have been read wrong by the PSP.  We can't actually use the real flag, because most people use NTFS/ext4/HFS/APFS/etc.  PPSSPP probably uncommonly stores PSP/GAME/ on anything FAT-related.

A few things are simplified in the explanation above.

-[Unknown]
