### ISSUE TITLE
spiderman 3 on android

### ISSUE THREAD

**Issue by gyanprakash13** [hrydgard/ppsspp#9797]
this game hasn't been corrected as many games has been fixed after many updates, is there any way to run this correctly? with some changed settings, it runs at 30-45% and with default settings it runs at 15-20% ppsspp version-1.4.2

**Comment by gyanprakash13** [comment]
and about my device
redmi 3s prime
3gb ram
1.4ghz octacore processor
screen resolution 1280×720

**Comment by Hydroque** [comment]
Can you run this on windows/linux to testcase what is being strained? It could either be the gpu or the processor. Identifying the bottleneck is the first step to optimizing your settings, too. Some poorly coded games can be their own fault. Also, your rip could be the problem (esp if you are using warez). Also, how do you run other games? Okay?

**Comment by gyanprakash13** [comment]
I don't own a pc so that I can run it, and other games work fine and even that don't works runs at 50-65% and gpu is adreno505 @ 450mhz and the game is .cso file

**Comment by BenNottelling** [comment]
Decompressing the .cso to be an .iso may help a little bit

**Comment by hrydgard** [comment]
@BenNottelling Highly unlikely that doing that would help anything.

**Comment by Hydroque** [comment]
@hrydgard does ppsspp decompress before loading?

**Comment by unknownbrackets** [comment]
No, many devices wouldn't have the free RAM (alongside OS and background apps) to store the entire disc uncompressed.  And if we were just going to "unzip" it to the storage, again, some devices may not have an extra 1.8 GB of storage space for that either.

CSO is designed as a streaming format.  There are popular myths that it causes performance issues, because an old version of some PSP CFW (custom firmware) had a performance bug that caused slowdowns in some games.  PPSSPP doesn't have that bug, and may even perform better (rather than worse) with CSOs than with ISOs.

That said, there's not a lot to go on here.  A 1.4Ghz (octa core, dual core, doesn't matter) is bit on the slow side for PSP emulation, though it should be able to run quite a few games.  This could just be a bad driver being slow on some graphics operation, but we need debug stats or something to know.

-[Unknown]

**Comment by Hydroque** [comment]
I have the ram space on windows! Does the 'store in ram' option in the settings store it compressed or decompressed? Sorry OT, but I would like to know.

**Comment by unknownbrackets** [comment]
It's stored compressed, but decompression is an small part of overall performance in PPSSPP.  More importantly, it's basically 0% of common runtime in almost any game.

Remember, on the PSP-1000, disc access was slow, and there was no cache.  So unless the game also ran at 35% speed on a real PSP-1000, the game developer probably optimized disc access to happen only during loading.

That means, even if there was a horrible performance issue in decompression somehow - it wouldn't cause static 35% performance in game.  It'd cause slower loading times.

At worst, it might come in "waves" (I think that's what happened in the PSP CFW bug I mentioned, though I haven't seen it), for example as games load background music.  If that were happening, the game would run at 100% for a while, then run slower for a few seconds, then 100% again, etc.  But again, PPSSPP doesn't have the bug mentioned.

-[Unknown]
