### ISSUE TITLE
PSP GFX

### ISSUE THREAD

**Issue by Hydroque** [hrydgard/ppsspp#9798]
(best labeled as question)
What exactly is the common method for commercial games (versus homebrew) to render graphics?

Going back to my development in GBA with C, I used DMA to transfer blocks of data in different ram banks, like VRAM if I wanted to draw things manually. Otherwise I would store them in separate blocks of the VRAM and the hardware would take over.

There are quite a few homebrew libraries. Is the native library 'Gu'?

**Comment by unknownbrackets** [comment]
Well, this is probably better asked in the forum.  But, briefly:

The PSP GPU actually renders triangles - and that's how the vast majority of commercial games render.  This is done using "display lists".  Those are managed by sceGe (the native library), which sceGu is a wrapper around (to make things easier.)

Ultimately, you can almost think of display lists as "code".  You write a list and each item in the list (each item is 32-bits) tells the GPU to do something.  Here's an example:

```
Set "clear mode" flag to "clear color, depth, and stencil".
Set "framebuffer address" to 0x04000000.
Set the "vertex address" to 0x08900000.
Set the "vertex format" to "s16 positions".
Draw 1 rectangle primitive form the vertex address.
```

sceGu provides convenience functions to write these commands to the lists, i.e.:

```
sceGuDrawBuffer(GU_PSM_8888, (void *)(0x04000000 - 0x04000000), 512);
sceGuClear(GU_COLOR_BUFFER_BIT | GU_STENCIL_BUFFER_BIT | GU_DEPTH_BUFFER_BIT);
```

Which would write commands similar to the human-readable version I gave above.

To understand this better, I recommend using the Windows build (in WINE should work), and opening the "GE Debugger" in the Debug menu.  Then just hit "Step Frame" while a game is running, and then "Step Into".  When you do this, some drawing will be delayed for optimization reasons - to see it "real time", switch to the "software renderer" (which is much slower, but doesn't buffer draws.)

As you continue to hit "Step Into", you'll see the individual commands of the display list executed.

If you do end up copying things wholesale to the framebuffer in VRAM, I recommend using `sceDmacMemcpy`.  PPSSPP will be better able to detect that you are writing directly to the framebuffer.  When using GLES/anything but the software renderer, we generally don't notice direct pixel writes to the framebuffer.  Even when games do it, they generally copy VRAM into RAM, and then back.

Note that from a 3D or even 2D rendering perspective, reading blocks of memory causes a stall and will be slower.  It's better to render everything everything using primitives, if possible.  This goes for modern PC and smartphone rendering too.

-[Unknown]

**Comment by Hydroque** [comment]
Like I am not new to graphics rendering, but I was just wondering what the general stuff was. Last time I posted on ppsspp forums it got deleted and the end. So I take it, since display lists, we are talking about opengl? Or is it to mimic opengl functionality?

**Comment by unknownbrackets** [comment]
Well, sceGu is not exactly OpenGL, although it's clearly modeled to have a similar API in many areas.  There's a lot of "it's the same but different."  For example, display lists are client allocated and `sceGuDrawArray` is used instead of enabling/disabling arrays.

But, I don't think display lists were made to mimic OpenGL, really.  The hardware executes lists, so it's more a way of managing the GPU (which was probably designed, in general, to support most OpenGL features.)

I think there may actually be a GL implementation for the PSP, though.  I think most commercial PSP games do not use it, but I don't have any stats on that.  I assume you'd only be able to use a subset of the GE's functionality (i.e. none of its special blend modes, color bitmasks, custom mip sizing, bezier/spline, etc. etc.), and might only be able to use a subset of GL features (although most GL features could be emulated if not natively supported by the GPU.)

Forum posts in general are deleted when the refer to piracy in some way, I'm not sure why it'd be deleted otherwise.

-[Unknown]

**Comment by unknownbrackets** [comment]
Well, sceGu is not exactly OpenGL, although it's clearly modeled to have a similar API in many areas.  There's a lot of "it's the same but different."  For example, display lists are client allocated and `sceGuDrawArray` is used instead of enabling/disabling arrays.

But, I don't think display lists were made to mimic OpenGL, really.  The hardware executes lists, so it's more a way of managing the GPU (which was probably designed, in general, to support most early OpenGL features.)

I think there may actually be a GL implementation for the PSP, though.  I think most commercial PSP games do not use it, but I don't have any stats on that.  I assume you'd only be able to use a subset of the GE's functionality (i.e. none of its special blend modes, color bitmasks, custom mip sizing, bezier/spline, etc. etc.), and might only be able to use a subset of GL features (although most GL features could be emulated if not natively supported by the GPU.)

Forum posts in general are deleted when the refer to piracy in some way, I'm not sure why it'd be deleted otherwise.

-[Unknown]

**Comment by Hydroque** [comment]
Nice double post and nice information. I appreciate it.
