### ISSUE TITLE
Streets of heraklion issue 

### ISSUE THREAD

**Issue by Varun1224** [hrydgard/ppsspp#9809]
At the streets of heraklion when the hallway comes which is collapsing .at that pt. My ppsspp emulator screen turns out black and i am not able to cross it .please help me out .

**Comment by unknownbrackets** [comment]
Did you try the latest PPSSPP build?  Have you tried OpenGL, Vulkan, Direct3D11 to see if it happens everywhere?  Does music still play while the screen is black?  Does some action make the screen not black, such as going backwards?  What device is this on?

-[Unknown]

**Comment by Varun1224** [comment]
Yeah man i have tried the latest the version of ppsspp .the music is playing but the screen gets black .the power bar and the orbs are also showing but other than that everything is turned black .when the camera goes back to show that everything is falling the screen turns black right at that time .Moving backwards didn't worked .I'm using LeEco Le2 .please help me out .

**Comment by unknownbrackets** [comment]
Has this improved in the latest git builds?

It might help if you can provide a log.  It's possible part of the game is crashing.

https://github.com/hrydgard/ppsspp/wiki/How-to-get-an-adb-logcat-from-a-PC

-[Unknown]

**Comment by unknownbrackets** [comment]
Also, is this God of War?  If yes, it seems like this would be an issue more would report.  Check that you have a good copy of your disc,. if so.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
