### ISSUE TITLE
Prince of Persia Revelations powers bug

### ISSUE THREAD

**Issue by leveophan1987** [hrydgard/ppsspp#9848]
There is a bug in Prince of Persia Revelations with powers (sand time powers) on Samsung Galaxy S7 edge(exynos version) device. The powers bar is not filling in normal camera mode. If you change the camera perspective in the game the powers bar will fill but will drain if you change back to normal mode.  Bug may be checked only after completing ship sinking sequence (as only after that bar should be filled). I've checked the game on other device (zenfone 5) and everything works as it should there.
Tried almost all setting combinations. Bug is present on both backends. Using v1.4.2-264.
![empty power bar](https://user-images.githubusercontent.com/30230713/28263008-4d453eb2-6af6-11e7-97ca-9426d4ca7cca.jpg)
![full power bar](https://user-images.githubusercontent.com/30230713/28263009-4d46c8a4-6af6-11e7-97bf-3b421f7033a5.jpg)

**Comment by sern19** [comment]
Same issue on iPhone SE. Using 1.5.4-673

**Comment by unknownbrackets** [comment]
Does it graphically deplete/replenish, or are the powers actually depleted by changing view?

I guess that would point to a jit bug, maybe?  Does this happen even if you change the CPU mode (under Developer Tools) to Interpreter or IR Interpreter?

Zenfone I believe is an x86 Android device, so that may support this assumption.

-[Unknown]

**Comment by unknownbrackets** [comment]
I'm wrong actually Zenfone 5 is an ARM device.  Not sure then...

-[Unknown]

**Comment by unknownbrackets** [comment]
That's very interesting.  I don't suppose you're able / willing to compile and test PPSSPP?  I could give you some code changes to try.

Unfortunately I don't have this game to try myself, but it'd be awesome to track down a jit bug.

-[Unknown]

**Comment by sern19** [comment]
I can do that.

**Comment by unknownbrackets** [comment]
Okay, not sure if you're a programmer or not so I'll walk through it.

First you'll need to build it.  Hopefully installing Android Studio and the Android NDK works as per the [build instructions](https://github.com/hrydgard/ppsspp/wiki/Build-instructions#building-for-android-with-android-studio).

After that, we want to find which instruction is misbehaving.  It could be other things, so step 1 is validating this assumption.

In [Arm64CompVFPU.cpp](https://github.com/hrydgard/ppsspp/blob/master/Core/MIPS/ARM64/Arm64CompVFPU.cpp#L40-L41) you'll see these two lines:
```c++
// #define CONDITIONAL_DISABLE { fpr.ReleaseSpillLocksAndDiscardTemps(); Comp_Generic(op); return; }
#define CONDITIONAL_DISABLE ;
```

Remove "// " from the first one, and put it on the second one instead.  This disables all the instructions in the file.

Next, do the same thing in Arm64CompLoadStore.cpp, Arm64CompFPU.cpp, and Arm64CompALU.cpp.  Now compile and run - it should be much slower.  If the bug doesn't happen, that's a good sign.  If it doesn't, time to abort - we're chasing our tail here.

Assuming it was one of those, the next thing to do is narrow down which file.  Arm64CompVFPU.cpp is probably most likely, so try undoing the change in the three other files.  when you run it this time, it should be much faster.  If the bug doesn't happen, it's in that file.  If it does happen, then try the other files one by one.

Once you find the file it's in, the next step is finding which function it is.  Doing that one by one would take forever, so we'll bisect instead.

Start with the change at the top of the file (so the longer version of CONDITONAL_DISABLE is enabled, and the short one is commented out with `//`.)  Go about halfway down, and look for something like `void Arm64Jit::Comp_Vmtvc(MIPSOpcode op) {` (the Vmtvc part will differ.)  Put this right above it:

```c++
#undef CONDITIONAL_DISABLE
#define CONDITIONAL_DISABLE ;
```

This way we've only disabled the first half of the file.  If the bug doesn't happen, it must be somewhere in the first half, so move it up to 1/4 of the file or so, and try again.  If the bug does happen, it must be in the lower half, so move it downward to 3/4.

Eventually, you'll find the one function that changes things.  It's possible multiple might be involved, so to validate this: undo the changes in the file again, and then put this around the function:

```c++
#undef CONDITIONAL_DISABLE
#define CONDITIONAL_DISABLE { fpr.ReleaseSpillLocksAndDiscardTemps(); Comp_Generic(op); return; }

	void Arm64Jit::Comp_SOMETHING(MIPSOpcode op) {
		...
		...
	}

#undef CONDITIONAL_DISABLE
#define CONDITIONAL_DISABLE ;
```

If the bug is still gone, then we have a good lead on where the bug likely is.  It could still be a more complicated register cache bug, but I'm hoping it's just a buggy VFPU instruction.

-[Unknown]

**Comment by sern19** [comment]
Since I don't have any android device I experimented with iPhone. Seems like something is wrong with `void Arm64Jit::Comp_FPU2op(MIPSOpcode op)` function in [Arm64CompFPU.cpp](https://github.com/hrydgard/ppsspp/blob/master/Core/MIPS/ARM64/Arm64CompFPU.cpp). With that one disabled, the bug doesn't appear.

**Comment by unknownbrackets** [comment]
Ah, okay.  iPhone should work fine too.  Probably something with rounding then or *maybe* sqrt.

If you want to experiment a bit more, you can try undoing all the other changes, and adding DISABLE; above this line, for example:

https://github.com/hrydgard/ppsspp/blob/5177db0f9188ca4540d215f317401d6e8c1b7d03/Core/MIPS/ARM64/Arm64CompFPU.cpp#L276

If that fixes it, then `cvt.w.s` is where it broke, which looks the most likely of those ops, perhaps.

-[Unknown]

**Comment by unknownbrackets** [comment]
Hm, it seems like that should handle infinity and nan correctly:
https://github.com/hrydgard/ppsspp/blob/4b46bb4ecf92460b89c1d067efd7840fd453a138/Core/MIPS/ARM64/Arm64Asm.cpp#L306

Compare with:
https://github.com/hrydgard/ppsspp/blob/2709472abdfaa16d959847d9c3b35a03544eb9a5/Core/MIPS/IR/IRInterpreter.cpp#L814

Quick test program just to be certain:
```c++
	float f1 = INFINITY, f2 = -INFINITY, f3 = 5.0f;
	int r1 = 42, r2 = 42, r3 = 42;

	__asm__ volatile (
		"fcvtns %w0, %s1"
		: "=r"(r1) : "w"(f1)
	);
	__asm__ volatile (
		"fcvtns %w0, %s1"
		: "=r"(r2) : "w"(f2)
	);
	__asm__ volatile (
		"fcvtns %w0, %s1"
		: "=r"(r3) : "w"(f3)
	);
	printf("RESULT: r1=%08x, r2=%08x, r3=%08x\n", r1, r2, r3);
```

RESULT: r1=7fffffff, r2=80000000, r3=00000005

A trick I've used to validate before is...

First, instead of this line:
https://github.com/hrydgard/ppsspp/blob/5177db0f9188ca4540d215f317401d6e8c1b7d03/Core/MIPS/ARM64/Arm64CompFPU.cpp#L286

Replace with:

```
fp.STR(32, INDEX_UNSIGNED, r, CTXREG, fpr.GetMipsRegOffset(MIPSReg(32 + 128)));
DISABLE;
```

This means after the jit does it wrong, it'll store the wrong result somewhere, and then we'll run the slower interpreter and do it correctly.

Next, replace this code:
https://github.com/hrydgard/ppsspp/blob/2709472abdfaa16d959847d9c3b35a03544eb9a5/Core/MIPS/MIPSInt.cpp#L917-L929

With:

```c++
			{
				u32 interp_input = FsI(fs);

				if (my_isnanorinf(F(fs)))
				{
					FsI(fd) = my_isinf(F(fs)) && F(fs) < 0.0f ? -2147483648LL : 2147483647LL;
					break;
				}
				switch (currentMIPS->fcr31 & 3)
				{
				case 0: FsI(fd) = (int)round_ieee_754(F(fs)); break;  // RINT_0
				case 1: FsI(fd) = (int)F(fs); break;  // CAST_1
				case 2: FsI(fd) = (int)ceilf(F(fs)); break;  // CEIL_2
				case 3: FsI(fd) = (int)floorf(F(fs)); break;  // FLOOR_3
				}

				// The result we wrote from the jit and interp.
				u32 jit_result = currentMIPS->t[0];
				u32 interp_result = FsI(fd);

				if (jit_result != interp_result) {
					printf("Ji cvt.w.s failed: %08x -> jit=%08x, interp=%08x\n", interp_input, jit_result, interp_result);
				}
			}
			break; //cvt.w.s
```

But you'll need to connect Console or Xcode to the iPhone to get the printfs, I think.

That should identify the specific conversion that isn't going as expected.

-[Unknown]

**Comment by sern19** [comment]
I'm not sure if I did it correctly. I replaced `r` in `fp.STR(32, INDEX_UNSIGNED, r, CTXREG, fpr.GetMipsRegOffset(MIPSReg(32 + 128)));` with `fpr.R(fd)` because it was undeclared.
File: [Output.txt](https://github.com/hrydgard/ppsspp/files/1865445/Output.txt)
I think line 41482 is where the bug should occur (after loading save).

**Comment by unknownbrackets** [comment]
Oops - sorry, it should be `S0` (this is the temporary holding the result) not `fpr.R(fd)` (since we leave it alone for the interpreter to set.)  The reason we're making it not change `fpr.R(fd)` is because fd and fs (the source) could be the same, so then the interpreter would perform a different operation.

-[Unknown]

**Comment by sern19** [comment]
Results with `S0`: [OutputS0.txt](https://github.com/hrydgard/ppsspp/files/1865837/OutputS0.txt)

**Comment by hrydgard** [comment]
Helpful converter for the input data: https://gregstoll.dyndns.org/~gregstoll/floattohex/

In the first erronous output, looks like 2.7 gets rounded to 2 by jit and 3 by interpreter. Not sure which rounding mode is selected though, should probably log that too...  (currentMIPS->fcr31 & 3)

**Comment by unknownbrackets** [comment]
Hm.  Each mode rounds properly for 0x402ccccd for me, with one exception: if the same block sets the rounding mode for the first time, then it doesn't kick in right away.

That's a bug, but it doesn't explain this occurring around syscalls.

I wonder: does this only happen on iPhones - or does it happen on Android devices with Cortex/Kryo/etc?  Maybe there's some limitation in the Twister?

-[Unknown]

**Comment by hrydgard** [comment]
In the original issue report, this happens on a Galaxy S7 so I doubt it's iOS specific. Though it of course theoretically could be hardware bugs in the CPUs, I don't think it's very likely since that would mean bugs both in Apple and Exynos chips... That said, I don't understand it either.

**Comment by unknownbrackets** [comment]
Ah, right.  I was thinking about the problems we had with armv7s.

Does anything change if we use a GPR?  Find this code:

https://github.com/hrydgard/ppsspp/blob/0ec1e5e3b24229563215fa2fdcfe189a70c6dcb4/Core/MIPS/ARM64/Arm64Asm.cpp#L304-L308

And replace with:

```c++
		fp.FCMP(S0, S0);  // Detect NaN
		fp.FCVTS(SCRATCH1, S0, roundModes[i]);
		FixupBranch skip = B(CC_VC);
		MOVI2R(SCRATCH1, 0x7FFFFFFF);
		SetJumpTarget(skip);
		fp.FMOV(S0, SCRATCH1);
```

In theory, it shouldn't matter except be a bit slower, but just wondering if this behaves differently.  On my Pixel or NVIDIA SHIELD TV, it still works either way (but I don't have the game - just testing this particular conversion.)

-[Unknown]

**Comment by sern19** [comment]
Sadly that didn't changed anything.

**Comment by sern19** [comment]
I also checked rounding mode, it's 0.

**Comment by unknownbrackets** [comment]
Thanks for all the help - sorry for the back and forth.

0 is round to nearest (tie to even) - we should be using FCVTNS, which should do exactly the same thing.

What if we just force rounding mode 0, to see if it's somehow not using it?  Keeping the logging for jit vs interp from above...

```c++
		if (js.hasSetRounding) {
			// We're just going to defer to our cached func.  Here's the arg.
			//fp.FMOV(S0, fpr.R(fs));
			//MOVP2R(SCRATCH1_64, &js.currentRoundingFunc);
			//LDR(INDEX_UNSIGNED, SCRATCH1_64, SCRATCH1_64, 0);
			//BLR(SCRATCH1_64);

			fp.FCMP(fpr.R(fs), fpr.R(fs));
			fp.FCVTS(S0, fpr.R(fs), ROUND_N);
			FixupBranch skip_nan = B(CC_VC);
			MOVI2R(SCRATCH1, 0x7FFFFFFF);
			fp.FMOV(S0, SCRATCH1);
			SetJumpTarget(skip_nan);

			//fp.FMOV(fpr.R(fd), S0);
			fp.STR(32, INDEX_UNSIGNED, S0, CTXREG, fpr.GetMipsRegOffset(MIPSReg(32 + 128)));
			DISABLE;
		} else {
```

If this changes the logging, we must have a bug somewhere updating currentRoundingFunc or in how it works...

-[Unknown]

**Comment by sern19** [comment]
Ok, after changing these lines there are no logs with rounding mode 0 (that's good?), instead there are a lot of logs with rounding mode 1 (but that's ok because we forced mode 0, right?). Results: [OutputForcedRounding.txt](https://github.com/hrydgard/ppsspp/files/1866293/OutputForcedRounding.txt)

Also, Happy Easter guys

**Comment by unknownbrackets** [comment]
Ah - that's very good info.  So it sounds like a problem of it not updating properly, not of the rounding code not working.  I have an idea why - or at least, I found one problem.

-[Unknown]

**Comment by unknownbrackets** [comment]
I'm hoping #10847 will do the trick.  Turns out we were forgetting to update the rounding mode on thread switch.

-[Unknown]

**Comment by sern19** [comment]
Just tried that, it's fixed now :)
