### ISSUE TITLE
White overlap in Cars Race-o-Rama

### ISSUE THREAD

**Issue by bodqhrohro** [hrydgard/ppsspp#9850]
A white rectangle overlaps almost all the screen during a race. Had no luck in fixing it by playing with graphics settings. Some game objects appear over this overlap but track and enemies are invisible. System: Windows 8.1, Asus X540S.with Pentium N3700, Intel HD Graphics.

![Race screenshot](http://pic4a.ru/77/Xm.png)

**Comment by unknownbrackets** [comment]
Which backends have you tried (i.e. Direct3D 11, OpenGL, etc.)?

Is it any better on the latest git build from the downloads page?

Has it ever worked in a previous version of PPSSPP?

-[Unknown]

**Comment by ppmeis** [comment]
Tested with latest Windows build, default settings.

Vulkan crash after enter first race.
[ppsspplog_vulkan.zip](https://github.com/hrydgard/ppsspp/files/1594867/ppsspplog_vulkan.zip)

OpenGL has a lot of glitches:
![image](https://user-images.githubusercontent.com/4381277/34458088-6976932c-edc5-11e7-896d-44e17d394ab2.png)

Direct3D9:
![image](https://user-images.githubusercontent.com/4381277/34458093-9b1b78f2-edc5-11e7-8c32-d78f8a5c8fd7.png)

Direct3D11:
![image](https://user-images.githubusercontent.com/4381277/34458099-bafb215e-edc5-11e7-8f27-fa9268b78234.png)

Software renderer is the "best":
![image](https://user-images.githubusercontent.com/4381277/34458104-eb7deef6-edc5-11e7-8423-149000457ac1.png)
![image](https://user-images.githubusercontent.com/4381277/34458106-f8cc675e-edc5-11e7-9b98-e2cb487054c0.png)

**Comment by benderscruffy** [comment]
still happens in v1.7.1-195-g04f57bd49 
![cars dx11](https://user-images.githubusercontent.com/2696404/48975036-7f8b3d80-f0a2-11e8-9057-0543a9eb9ada.PNG)
[ULUS10428_0001 DX11.zip](https://github.com/hrydgard/ppsspp/files/2612795/ULUS10428_0001.DX11.zip)
[ULUS10428_0001 opengl.zip](https://github.com/hrydgard/ppsspp/files/2612796/ULUS10428_0001.opengl.zip)

**Comment by unknownbrackets** [comment]
This is fairly similar to #9604, right down to the detection of the target width.  It's also doing depth texturing.

I wonder if it might be an okay hack - at least for GLES2 and some devices that will probably never have depth texturing - to specifically ignore draws that are from depth...

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, for GLES2 that should be okay.

I should revive my depth texturing branch, if I still have it somewhere... hm. Or just reimplement it, it isn't all that difficult. Just need to take into account that games like to depal from depth...

**Comment by unknownbrackets** [comment]
I think I've seen 565 from depth (maybe just to copy it, though.)

-[Unknown]

**Comment by Emulatorer** [comment]
This game has a terrible graphics glitches that's make all the screen white and very lag see screenshot below
![Screenshot_2019-08-18-18-03-05](https://user-images.githubusercontent.com/37603562/63223146-d104cb00-c1e3-11e9-991d-5ad3cad1e190.png)
[GE Debug.txt](https://github.com/hrydgard/ppsspp/files/3512883/GE.Debug.txt)
•Mali-450
•Android 5.1
•PPSSPP v1.8.0-530 beta build

**Comment by Gamemulatorer** [comment]
![Screenshot_20200512-095926](https://user-images.githubusercontent.com/37603562/81630358-f7385e00-9437-11ea-90f2-5c8be1fe3be9.png)
No improvement in the lastest git

**Comment by Gamemulatorer** [comment]
ppsspp latest git build
### HW rendering
![Screenshot_20200604-170036](https://user-images.githubusercontent.com/37603562/83736998-0308f000-a685-11ea-95af-264c620085f8.png)

### SW rendering
![Screenshot_20200604-165956](https://user-images.githubusercontent.com/37603562/83737025-09976780-a685-11ea-852d-7eba228f1b8d.png)

**Comment by Alif-Test** [comment]
I used v1.10.3-593-g9f18489fd with Vulkan renderer and oh god, it's fucking black!
![ULUS10428_00000](https://user-images.githubusercontent.com/70889233/92372534-a9a2d800-f12f-11ea-8002-df2bf1ff7737.png)

**Comment by Gamemulatorer** [comment]
It's getting worst on the latest build of ppsspp (opengl)
![Screenshot_20200908-204921](https://user-images.githubusercontent.com/37603562/92478552-e399da00-f214-11ea-9bcf-5cdd27955b8f.png)

**Comment by Panderner** [comment]
Even software renderer are glitched out. 

Here's a screenshot of this game running on Real PSP:
![IMG_20201012_185631](https://user-images.githubusercontent.com/37503397/95738981-aebdee80-0cbc-11eb-82ad-b1352b9a5609.jpg)

**Comment by Gamemulatorer** [comment]
Both OpenGL and Vulkan
![Screenshot_2021-05-03-18-15-58-037_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/116865192-bda9c580-ac3b-11eb-9a52-a1e7da17461c.jpg)

**Comment by unknownbrackets** [comment]
Seems better but there seem to be some blotchy parts - did this get better with the guardband changes?  Maybe there's still a precision issue here...

-[Unknown]

**Comment by Panderner** [comment]
Still an issue in hardware modes:
![Screenshot_2021-10-21-02-18-06-594_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/138149094-ea3a0c24-5bae-40e8-8f6a-2e00ff33554a.jpg)

**Comment by Panderner** [comment]
Hardware:
![Screenshot (25)](https://user-images.githubusercontent.com/37503397/184075668-322fe12b-0edd-4118-ab6e-fed2de9887cf.png)

Software:
![Screenshot (24)](https://user-images.githubusercontent.com/37503397/184075688-4bd1ac29-49ef-4182-a522-d39f1e079906.png)

Note: using Direct3D 9 crashes PPSSPP.

**Comment by benderscruffy** [comment]
here is a GE Dump with software renderer (might help or might not ???)
[ULUS10428.zip](https://github.com/hrydgard/ppsspp/files/9307206/ULUS10428.zip)

**Comment by unknownbrackets** [comment]
The most obvious problematic draw is 8796/18278.  This textures from depth, simply taking (depth >> 1) & 0xFF.  Interestingly, I see depth values ranging between 0-10000 or so.

It does this in strips:
1. First, from depth to a temp buffer strip (0x000883c0) as noted above.  The target is 5650, and it stretches 16x272 of source data to 32x272 of destination data.
2. Next, it textures from the main color buffer to the same temp buffer.  However, here it treats the target as 8888 with half the stride, and uses 16 -> 16 wide strips.  Flags and masking aren't enabled, so I think this just overwrites the previous draw (replacing with the original colors)?
3. Now it textures back to the screen.  However, this is a 32 pixel wide strip, treated as 5650.  It treats the target as 565 through, and doubles the stride... so the format doesn't matter, it's really 16 pixels of 8888, copied.
4. It moves forward, copying 16 pixels of depth (starting, though, at offset 32) as in step 1 to the same strip.
5. Next it's offset by 16 for 16 from the color buffer.
6. And finally back to the color buffer, overwriting starting at 32.

The third step uses the output of step 1 (instead of 2, even though I can see it does render it), and it's because the framebuffer formats don't match and there's an offset.  We end up with two framebuffers (one offset and with the alternate format), and then texturing also has choices to make and doesn't use the latest one.

I wonder if some CPU logic determines whether to blend the depth and color, or something.  All flags are off in this state, though.

At 8822/18278 (cycle starting on 8820/18278), it gets to the strip at x=256, and at this point it uses an offset framebuffer (+0x200) for some reason.  It does seem like this is correctly detected as an offset.

Then at 8886/18279, at draws some depth strips with a fixed depth value, and clears stencil where depth is less, and clears color with depth is more.  It's black at this point, I think because it changed from 565 -> 8888.

At 9118/18278, it draws an image from RAM which looks like a square render (probably a previous download.)  This is a fixed blend of about 10% for bloom.  Since this was in RAM, I'm not sure if it downloads properly on hardware (it could be after the clear above.)

So there's more to this than simply depth texturing.

-[Unknown]
