### ISSUE TITLE
Cwcheat code type not working properly

### ISSUE THREAD

**Issue by omarrrio** [hrydgard/ppsspp#9869]
Hi, the 0xCYYYYYYY 0xZZZZZZZZ (condition code type) has a bug in it, the emulator interprets it differently.

**What it does:** if value @0x0YYYYYYY is not equal to 0xZZZZZZZZ, all the lines after this one will be disabled, including all the codes after this line.

**What it should do:** if value @0x0YYYYYYY is not equal to 0xZZZZZZZZ, all the lines after this one will be disabled, but only up to the next code.

**_Example_:**
```
_C1 DP multiply x2
_L 0xC07008D8 0x0E3C1F11  <------ The condition
_L 0x207008DC 0x02442021  <------ What it should execute or stop
_C1 No banlist
_L 0xC003E454 0x90420002  <------- The first condition affects these lines aswell, which is a bug
_L 0x2003E454 0x34020003
```

**Comment by hrydgard** [comment]
Wow, that is weird. @LunaMoo , any ideas here?

**Comment by LunaMoo** [comment]
No idea, I mean it's clear it works as was described it has special function just for that code type doing exactly that - skipping all code lines after it.
 This means all cheats, because the way PPSSPP cheat engine was implemented means all enabled cheats are then parsed line by line together, there's no way to tell where the cheat #2 started or where cheat #1 ends etc. or at least I think that's the case by looking at it, probably was made that way for performance or to keep things simple.

 I also can't confirm how this code type really should work, the only CWCheats I ever see with 0xC codes are described as not working and not have any other code lines so either this should work as it already does aka work as a conditional for other cheats and not be limited to itself or all those cheats I see are just incorrectly auto-translated from different format since there really was no solid standard when it comes to psp cheats and similar syntax was reused for different things.

 I can only recommend using 0xD and 0xE code types instead, those are proper conditional code types, in opposite to 0xC those were actually commonly used by everyone also on psp and will work fine since they require number of lines to skip in their syntax.

**Comment by omarrrio** [comment]
First of all, thank you both for replying, I am no expert when it comes to C++, the 0xC type basically executes or not the following lines of codes, not the actual ENTIRE list of codes, maybe this c# i made can probably be of use, and i apologize if i sound like either an idiot or someone who thinks they know better, and yes, the 0xE is better, but i just don't want others to start an issue relating to this same problem:
`//Variables Needed
            List<string> Cheats = new List<string>();
            List<List<string>> Codes = new List<List<string>>();
            string[] AllLines = CheatCodes.Text.Split('\n');
            //Parsing the text
            for(int i = 0; i < AllLines.Length; i++)
            {
                if (AllLines[i].StartsWith("_C? ")) //to determine if it's a cheat name or cheat instruction
                {
                    Cheats.Add(AllLines[i]);
                    List<string> InstructionLines = new List<string>();
                    for (int j = i+1; j < AllLines.Length; j++)
                    {
                        if (AllLines[j].StartsWith("_L ")) //to determine if it's a cheat name or cheat instruction
                        {
                            //a little check to see if the code is properly typed
                            int CheckInstruction = AllLines[j].Split(' ').Length;
                            if (CheckInstruction != 2) //This is only a simple check, i just don't want to get way into checking all types and of the 0x is written etc
                            {
                                InstructionLines.Add(AllLines[j].Replace("_L ", ""));
                            }
                        }
                        else if (AllLines[j].StartsWith("_C? ")) //to determine if it's a cheat name or cheat instruction
                        {
                            i = j;
                            Codes.Add(InstructionLines);
                            break;
                        }
                    }
                }
            }
            //Now that we have a list of instruction for every cheat name, let's do a 0xC type Parsing
            bool CtypeFlag = false;
            for (int i = 0;i < Cheats.Count; i++)
            {
                Result_text.AppendText(Cheats[i]);
                foreach (string instruc in Codes[i])
                {
                    if (instruc.StartsWith("_L 0xC"))
                    {
                        string[] forParsing = instruc.Replace("_L", "").Replace("0x", "").Split(' ');
                        //Let's parse !
                        string Add2Check = forParsing[0].Substring(1, 7);
                        string Val2Check = forParsing[1];

                        //...Work your c++ memory check magic here, too much of a noob but i guess it's already obvious from how stupid this code is

                        //if the condition is met, the lines after this one should execute
                        CtypeFlag = false;
                        //if the condition is not met, the lines after this one should stop
                        CtypeFlag = true;
                        Result_text.AppendText(instruc + "  <---- The condition is " + (CtypeFlag==true ? "NOT MET!":"MET!"));
                    }
                    else
                    {
                        Result_text.AppendText(instruc + "  <---- The instruction will " + (CtypeFlag == true ? "NOT EXECUTE!" : "EXECUTE!"));
                    }
                }
            }
            //The End`

The result should be like this:
`_C1 DP multiply x2
_L 0xC07008D8 0x0E3C1F11  <---- The condition is NOT MET!
_L 0x207008DC 0x02442021  <---- The instruction will NOT EXECUTE!
_L 0x207015CE 0x02668031  <---- The instruction will NOT EXECUTE!
_C1 No banlist
_L 0xC003E454 0x90420002  <---- The condition is MET!
_L 0x2003E454 0x34020003  <---- The instruction will EXECUTE!`
