### ISSUE TITLE
 framerate issue on mod nation racer usa and Europe versions 

### ISSUE THREAD

**Issue by omarguerrero5310** [hrydgard/ppsspp#9925]

**Comment by omarguerrero5310** [comment]
When first loading the game on ppsspp it loads crazy fast but when loading the first race of the campaign it  crashes the whole app , I tryed a lot of devices (android,pc,window,mac,jxd,ios,amazon fire stick tv,.
I tryed every method of framerate improvement

**Comment by omarguerrero5310** [comment]
And nothing work

**Comment by unknownbrackets** [comment]
If you select Show FPS in settings, what does it show?

-[Unknown]

**Comment by ppmeis** [comment]
Tested with latest windows build, default settings. LGTM except the other issues found on #9851

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback and wasn't reproduced by ppmeis.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
