### ISSUE TITLE
sceJpeg uses wrong width/stride

### ISSUE THREAD

**Issue by Florin9doi** [hrydgard/ppsspp#9931]
Here is the program : [testJpeg.zip](https://github.com/hrydgard/ppsspp/files/1253485/testJpeg.zip)
The expected result:
![background](https://user-images.githubusercontent.com/2995486/29739708-b8efac0e-8a4c-11e7-9b85-e206c4e286a0.jpg)
The observed result: 
![eboo00649_00000](https://user-images.githubusercontent.com/2995486/29739701-a22849f4-8a4c-11e7-84b4-e9a5f08d0b6b.png)

**Comment by Florin9doi** [comment]
bufferwidth @ sceDisplaySetFrameBuf seems to be ignored

**Comment by unknownbrackets** [comment]
This doesn't happen in the software renderer, right?  Is it all other backends like GL/D3D/Vulkan?

-[Unknown]

**Comment by Florin9doi** [comment]
Seems to be the same, whatever I choose

**Comment by benderscruffy** [comment]
PPSSPP v1.5.4-997-g3472d62ff Windows 64 bit
still the same problem

**Comment by LunaMoo** [comment]
That's just jpeg decoding issue, probably it doesn't use standard psp texture and in the end isn't square like in all commercial products, which my current implementation was based on. Don't have time/care about weird test homebrew, ppsspp doesn't work well with software that manually copies stuff into vram anyway.

**Comment by hrydgard** [comment]
This definitely should work with the software renderer at least. Anything else is a bug.

My suspicion is that the app doesn't configure the framebuffer properly though and that our defaults don't match the PSP's defaults.

**Comment by benderscruffy** [comment]
nope doesnt work in software renderer

**Comment by unknownbrackets** [comment]
Looking at the VRAM this produces in PPSSPP, it's quite clear the issue is sceJpeg as @LunaMoo says.

It's clearest when drawing a line along the edges of the JPEG.  The first 0x780 bytes are the top white line, as expected.  But instead of the left line continuing at 0x800, it continues at 0x880.

This is because sceJpeg rounds its decoding up to a power of two:
https://github.com/hrydgard/ppsspp/blob/2d882b73702786089f6833e1f39d957fda9cd8d2/Core/HLE/sceJpeg.cpp#L143-L148

This test app shows that's definitely wrong, but we probably need to check more usages of sceJpeg because it was probably implemented that way for some reason/some game.

-[Unknown]

**Comment by LunaMoo** [comment]
Yeah it was done for PlayView apps graphics, that was the only solution I could think of that resulted in correct graphics in those apps and every other commercial game which uses sceJpeg ~ related pr #9760

**Comment by Florin9doi** [comment]
👍
