### ISSUE TITLE
Screen flicker problem with framSkipper

### ISSUE THREAD

**Issue by hanooty** [hrydgard/ppsspp#9937]
Is there any way to stop screen flickering which occurs when framskipper is on, i have notice that some games work faster with framskipper but because of flickering screen is not playable i wonder is there any setting or any way to stop flickering screen!!
Please please give me better issue to fix it...
Tested On PES2017 
Default Settings With FrameSkiping

**Comment by hrydgard** [comment]
Frameskipping together with Rendering Mode set to Buffered Rendering is usually pretty flicker-free. In non-buffered, there are indeed sometimes some issues I can't quite explain, so leaving this open for future investigation.

Are you running with Buffered?

**Comment by hanooty** [comment]
Yeah running with 
Buffering Render
Semulate block transfer  [on]
Frame Skip [1]
Auto FrameSkip [checked]
Force emulator from excel 60 [checked]
Alternative speed Unlimited

**Comment by ResurrectionRedmi9** [comment]
Outdated/No Feedback.

**Comment by unknownbrackets** [comment]
Is this still an issue in recent git builds (https://buildbot.orphis.net/ppsspp/)?  This functionality may have improved since you experienced it.

If you're using "skip buffer effects", this will still sometimes flicker in some games, but we changed some flip timing that might have improved it as well.  That said, there will always be unavoidable glitches and issues in that mode, as it disables the game's ability to use buffers - it's a speedhack.

-[Unknown]

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
