### ISSUE TITLE
Compiling last version in PI (Retropie with PI3)

### ISSUE THREAD

**Issue by Darknior** [hrydgard/ppsspp#9939]
Hi

Is some one here working on the PI version ?
Is it possible to know if all your updates i can see every day will impact the PI version ?
Because on Retropie we have an old version, with some controller bugs, and i really want to try a new one with all the Retropie users.
Thanks a lot to read and answer me

**Comment by dankcushions** [comment]
you can compile ppsspp on retropie by source. this will always get the latest version. this goes for all almost all emulators on retropie.

**Comment by Darknior** [comment]
Thanks
Yes i know i can do it, but when i try i don't have the same version number than the last version here.
I'm sure it is an older version :(
How can we be sure that the PI version is the same and use all the news upgrade of the officiel one ?
They write having fixed controller issue but we always have it for exemple :(

**Comment by dankcushions** [comment]
@Darknior maybe your build is failing - you could check retropie's build logs to be sure. in any case this is nothing to do with ppsspp, and you should confirm issues on retropie's forum before wasting developers' time on github. please close this issue and continue this discussion there.

**Comment by Darknior** [comment]
I understand you think wasting developers time here.
But i compile from source PPSSPP many times and it never crash, all is working fine.
But the version is not **1.4.2** but **ee6086c**.
I want to understand why, and i think only developers can answer me...

**Comment by unknownbrackets** [comment]
Well, imagine a theater near you announced they were showing an old movie you liked, and wanted to see again.  Let's say Star Wars, for example.

You went to watch it, and realized it was an old version of the film.  It didn't include the sound / visual / extra scenes / other improvements from releases in the 40+ years since the initial release.

Annoyed that the theater near you had shown an older release, you call Lucas Arts, and ask them why their newest version isn't being shown at your theater.

But Lucas Arts doesn't know why.  They don't own the theater, they didn't decide to play the film.  All they know is they've already released plenty of remastered versions.  They have the same question as you: why isn't the theater using their newer, better release?

It's the same thing here.  To get to the bottom of this issue, you need to contact the theater (Retropie.)  Only they know why they are using an old version of PPSSPP.  They are the ones who chose to do this.

-[Unknown]

**Comment by unknownbrackets** [comment]
As far as the version number - if you compile the latest source, you will get a version newer than v1.4.2.  ee6086c looks like a more recent version than v1.4.2, if that's what you're actually compiling.  That doesn't answer anything about the version Retropie comes with, or if you're running the version you compiled.

-[Unknown]

**Comment by Darknior** [comment]
Thanks if ee6086c is a better version than 1.4.2 it's cool, where can i find this information for the future ?
If i understand it is not a version number but release number.
And if you are real i have nothing more to answer,Retropie compile the last source code.
If the games are slow it is normal, i understand we are on PI3 ... not a really powerfull computer ... maybe it will change with PI4 or 5 one day lol
Now i'm only sad to see we always have the PAD mapping bug that is there from some years ...

**Comment by unknownbrackets** [comment]
Well, that's a git sha - if you want a method to see, you can check using two URLs like this:

`https://github.com/hrydgard/ppsspp/compare/{put the sha here}...v1.4.2`
`https://github.com/hrydgard/ppsspp/compare/v1.4.2...{put the sha here}`

Everything outside the `{put the sha here}` has to stay the same, including the three dots.

The first link tells you what has changed in v.1.4.2 since that git sha.  So if it says, "There isn’t anything to compare." then you're up to date.

The second link tells you what has changed in that git sha since v.1.4.2.

-[Unknown]
