### ISSUE TITLE
Castlevania Symphony of the Night in Dracula X Chronicles crashes PPSSPP at a certain boss fight

### ISSUE THREAD

**Issue by claybutton** [hrydgard/ppsspp#9940]
![jkd](https://user-images.githubusercontent.com/31455183/29843940-a08a108c-8cdb-11e7-84ab-ef9b8e6edb8d.png)
![kutydc](https://user-images.githubusercontent.com/31455183/29843946-a77b10d0-8cdb-11e7-88fb-adfb9a585203.png)

**Comment by hrydgard** [comment]
Thanks for reporting. A savegame and/or a savestate right before the crash would help investigation.

**Comment by claybutton** [comment]
Sorry, I'm not very techie. Is this the file you need? Also what should I use to share it?
![hteahuae](https://user-images.githubusercontent.com/31455183/29846299-3f5685f8-8ce4-11e7-96de-f8f5cd8ff6e6.png)

**Comment by claybutton** [comment]
I think I got it.
[https://drive.google.com/drive/folders/0BwfM2MjLgyUhd1U1U1lGRnF2MzQ](url)

**Comment by res0nance** [comment]
To reach the crash you need to select original game and symphony of the night then load the file and move right for 2 screens to enter the boss room.

The crash happens when you hit the up button to trigger the boss after the screen fades to black.

Using a debugger gives a crash at the enterDispatch function pointer call which gives a read access violation.

**Comment by LunaMoo** [comment]
This problem might be limited to US version or caused by non default user settings. Also possible there's just another popular bad dump flying around the net which people pirate since crashes like that when loading assets from another location commonly are caused by missing/corrupted files.

 Tested on legit copy of EU version and it works fine even with that savedata(after renaming;p) and I also remember finishing whole SotN to 200+ % whatever was the max including the mirror/upside down castle starting from 0 and don't remember any bugs.

**Comment by res0nance** [comment]
I made a fresh dump of the US version and still got a crash using the save provided.

Exception thrown at 0x19220CBB in PPSSPPDebug.exe: 0xC0000005: Access violation reading location 
0x13C00017.

Possible regression or a bug limited to the US version

**Comment by unknownbrackets** [comment]
Does it happen when you disable "fast memory" in settings?

A crash inside "enterDispatch" means it's crashing somewhere in jit.  Fast memory uses memory directly, which means bugs crash - disabling it puts the kid gloves on, and might avoid the crash.

That won't tell us if it's US or not, but it will confirm if it's crashing on a bad memory access.

Another thing you could try is changing the CPU core from "Jit" to "IR Interpreter" in developer settings.  This might be a little slow, but if it doesn't crash, that might point to a jit bug.

Also - it looks like the crash you have is using 32-bit.  Can you try 64-bit to see if it crashes there too (with jit and fast memory)?

-[Unknown]

**Comment by Emulatorer** [comment]
This is that game?
sorry for my english 😅😟
![Screenshot_20200307-161544](https://user-images.githubusercontent.com/37603562/76140258-45755d80-6093-11ea-99e7-0e50b760cba8.png)

**Comment by unknownbrackets** [comment]
Any update here?

Note that you'll get more information on crashes now in recent versions.

-[Unknown]

**Comment by Gamemulatorer** [comment]
Cannot reproduce this or I'm doing it wrong to reproduce this issue?

https://user-images.githubusercontent.com/37603562/134573184-77c1402d-4373-4731-a0d2-dd73321c6174.mp4

**Comment by Gamemulatorer** [comment]
@claybutton any update to reproduce or updated link of your savestates?

**Comment by unknownbrackets** [comment]
This issue is being closed because it hasn't been updated with feedback.  It seems like it may have been fixed.

It's hard to tell when fixes in PPSSPP might fix other games, and sometimes certain settings or cheats may cause bugs that can't be fixed.

If you have more information or can confirm it still happens in the latest git builds, please reply to this issue and it'll be reopened.  If you have a new issue with the same game, just create a new issue instead.

-[Unknown]
