### ISSUE TITLE
is there a ppsspp sdk to read ppsspp user memory?

### ISSUE THREAD

**Issue by weituotian** [hrydgard/ppsspp#9952]
i plan to write a program about cheating some games.
so i need to read or write the user memory, of runing ppsspp program. 
is there a ppsspp sdk can be include in my c program to finish that?

**Comment by hrydgard** [comment]
No, currently the only quick option is to write your cheat in Action Replay commands and use the existing cheat facility.

Or you can simply modify PPSSPP itself, though it won't be convenient for others to use your stuff.

(I think some people have had success with CheatEngine or whatever it's called as well).

**Comment by weituotian** [comment]
@hrydgard 
thanks for your reply!

i had a case below that,

![image](https://user-images.githubusercontent.com/7270968/30003847-e374fdf2-90f6-11e7-9049-7df7fade4bd3.png)

the Visual novel game is `ULJM06232グリザイアの果実`，[download](http://dx3.ferriyy.com/Grisaia_no_Kajitsu_Portable.zip?qqdrsign=06012)
i had found the `0x09CA6704` is starting address of the text in this game.

![image](https://user-images.githubusercontent.com/7270968/30003806-2b5be578-90f6-11e7-94c0-e4dbe4d14fd1.png)

i want to read the bytes in this address `0x09CA6704 `
and convert it to string, then send it to the online translation engine to translate the text.

i am using windows os, and confused about how to get the start of the ppsspp memory.

**Comment by unknownbrackets** [comment]
It would probably be doable to have a simple API for things like this.

That said, the data in question may likely be on the disc.  Commonly people translate this on disc.

Anyway, I do currently have a hacked version of PPSSPP (for a specific game) which hooks a certain PSP function, and looks up replacement text from a webservice (in case it's been translated since this build.)  It's definitely useful, and also allows for logging and save states when new strings are encountered.

Would probably be doable to add an dll/so API with:
 * Basic events: start game, stop game, display flip.
 * Allow registering a replacement entry.
 * Allow capturing a screenshot.
 * Allow capturing a save state.

But that'd still not really cover my use case, as I also allocate a small chunk of kernel RAM for the replacement string, and add config settings to the UI.

-[Unknown]

**Comment by hrydgard** [comment]
Or maybe game specific lua scripts. ULUS12345.lua etc :)

**Comment by unknownbrackets** [comment]
Please see here: https://github.com/unknownbrackets/ppsspp-api-samples/tree/master/js

There's a sample with the ability to read and write memory.  We could add more APIs and features, of course, but I think this may already allow the online translation thing noted here.

Closing this as such.

-[Unknown]
