### ISSUE TITLE
Dante's Inferno freezes and cannot be finished in Ver 1.3

### ISSUE THREAD

**Issue by PlayBoyMan** [hrydgard/ppsspp#9961]
I haven't been able to continue the game when I get to a certain point in the game.

**Comment by unknownbrackets** [comment]
Does this happen in v1.4.2 or the latest git build?  Plenty of bugs were fixed since 1.3.0.

What's the "certain point"?  This is like someone saying, "you missed a spot" without pointing at the missing spot.  Where?

What happens, does it crash, does the screen turn black, does music continue?  What device are you using - perhaps a Samsung Galaxy S3?  A desktop computer with a Core 2 Duo 1.2 Ghz CPU and NVIDIA 7600 GT running Windows XP?

What's the game's region - US, Europe, Japan, something else?  Have you verified the crc is good and you have a clean disc rip?

Have you tried saving in game, restarting the emulator, not loading any save state, and loading the save game?  Some PSP games have bugs in them - not all of them work correctly when you've been playing for hours and hours straight, which is what save states simulate.

If yes, can you upload the save game somewhere, so someone else can try?

-[Unknown]

**Comment by PlayBoyMan** [comment]
I'm on the 1.3 version, and I saved the game, no save states.
I have the save data here: https://www.dropbox.com/sh/ebmt7l36m9uirnu/AAABZ9PNJh03jdgMOR-R42Spa?dl=0

**Comment by LunaMoo** [comment]
Closing for same reason why #7923 was closed it's not really an emulation issue, that place in-game is known to be broken on some(apparently popular) pirated copy of the game due to file corruption.

 Buy the game, dump it yourself and it will work, copy from the official PS Store will also work fine, your bad copy will never work, doesn't matter which version of PPSSPP you will use and what options you try.

**Comment by PlayBoyMan** [comment]
This was made from a legit copy I acquired 3 years ago. I redid the dump and it works fine now.
