### ISSUE TITLE
Crash when using Google Pinyin input method

### ISSUE THREAD

**Issue by clouds56** [hrydgard/ppsspp#9963]
When using [Google Pinyin input method](https://www.google.com/intl/zh-CN/ime/pinyin/), and open the ppsspp in Win10, then any type like "x" or "z" at any place, both google pinyin and the ppsspp would be crash.
PPSSPP version: prebuilt windows version [1.4.2](https://www.ppsspp.org/files/1_4_2/ppsspp_win.zip)

PS: I've tried Microsoft Pinyin input method which is embedded in Windows, and type "a" it would have no response in PPSSPP, I'm not sure why Google Pinyin input method would crash.

**Comment by hrydgard** [comment]
I can reproduce this. It crashes inside the Google Pinyin DLL when we call TranslateMessage on a WM_KEYDOWN message. I don't see anything wrong with how we call that function. Seems to be a bug in Google Pinyin, though why it would only affect PPSSPP I have no idea...

**Comment by unknownbrackets** [comment]
It seems like it hasn't been updated since 2013, and I saw some notes about it not working anymore in the latest Windows 10.

Are there other options available?  Does this happen on earlier versions of Windows, such as Windows 7 or 8?  It may be that Google Pinyin isn't fully compatible with Windows 10.

-[Unknown]

**Comment by clouds56** [comment]
sure, I've changed a IME and it works well
