### ISSUE TITLE
Error code 80410814 Ace Combat Joint Assault Adhoc android tablet

### ISSUE THREAD

**Issue by jistjak** [hrydgard/ppsspp#9969]
Trying to play Ace combat joint assault on adhoc with android tablet and i got this weird error code. weird because there is nothing on the error code forum about error code 80410814. I've messed around with some options to see it i could fix it (fast memory, io method, use built in adhoc server, enable wlan [just doesn't even try with it off, gives error code ffffffff], server ip address [tried setting it to 10.0.0.153 which is the host server for my private lan, then to the public pro.coldbird.net nothing changes].) This game works on pc to pc without problems but android tablet doesn't want to join adhoc game. Infrastructure mode doesn't work at all on pc nor tablet no error code just hangs without crashing (i can still go into ppsspp menu).
![screenshot_2017-09-13-17-44-27](https://user-images.githubusercontent.com/20390531/30404774-cc49702c-98ad-11e7-92a4-c99b03a5c744.png)

**Comment by Michal1324** [comment]
Change the port waaay higher on android otherwise it won't work

**Comment by jistjak** [comment]
Ok, i did that and no longer get the error code, but i can't find the game im hosting. I host it on my laptop and join with my tablet. All the network settings are identical between them and when i am in the lobby, the text say "No games found". I also switched hosts from laptop to tablet and there is no games found on laptop either.

**Comment by Michal1324** [comment]
Make sure you have configured firewall on laptop

For setting up local mp search for some guide because I've forgot already.

Close

**Comment by jistjak** [comment]
The game is allowed through the firewall, I was able to play the game with two PCs without any problems, so firewall isn't the problem for the PC. Android's just doesn't want to cooperate with the PC

**Comment by unknownbrackets** [comment]
This is basically #7268, as far as I understand.

Linux, Android macOS, Unix, etc. systems aren't going to allow free use of ports below 1024.  Since we directly use those ports (for compatibility with the PSP, which can), that causes these errors.  Using port offset works around this generally, but breaks compatibility with real PSPs.

Closing this in favor of #7268 which would be a better and more automatic solution than the port offset - although it would also break PSP compatibility.

-[Unknown]
