### ISSUE TITLE
how to play dreamcast game on ppsspp?

### ISSUE THREAD

**Issue by Julxxx** [hrydgard/ppsspp#9971]
I really want to play a certain games from a phase out console. I searched and that it can be done through the psp console but how about in ppsspp for android? Please help thanks.

**Comment by LunaMoo** [comment]
You can't. PPSSPP is PSP emulator and will not run games from other platforms, it will never happen.

 Also no, PSP was not able to "play DC games" nor any other non-PSP games for that matter. There are emulators for PSP, some fan made released as homebrew, others official sold with games, but in general most of those emulators were providing pretty poor experience being slow and/or buggy. PSP was just too weak to emulate any newer platform with playable fps, it struggled even with some SNES games.

 You should just find a native DC emulator dedicated for your platform, in case of android I belive there's one called "Reicast", if it works bad on your device, that's just life, upgrade your hardware or forget about the whole thing, emulating an emulator would be far slower and more buggy than running a native emulator anyway.

 Closing since it's not a valid issue.

**Comment by Julxxx** [comment]
Thank you for your answer, regarding Reicast, yes I tried it. It work
perfectly with other games but on the Omikron:the nomad soul only half of
the screen is working. Anyway thank you for answering my concern. I asked
and comment to multiple forums but your the fastest one to answer. Keep on
assisting others and more power.

On Sep 15, 2017 4:46 PM, "LunaMoo" <notifications@github.com> wrote:

You can't. PPSSPP is PSP emulator and will not run games from other
platforms, it will never happen.

Also no, PSP was not able to "play DC games" nor any other non-PSP games
for that matter. There are emulators for PSP, some fan made released as
homebrew, others official sold with games, but in general most of those
emulators were providing pretty poor experience being slow and/or buggy.
PSP was just too weak to emulate any newer platform with playable fps, it
struggled even with some SNES games.

You should just find a native DC emulator dedicated for your platform, in
case of android I belive there's one called "Reicast", if it works bad on
your device, that's just life, upgrade your hardware or forget about the
whole thing, emulating an emulator would be far slower and more buggy than
running a native emulator anyway.

Closing since it's not a valid issue.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/hrydgard/ppsspp/issues/9971#issuecomment-329720881>,
or mute
the thread
